pytest-dev/pytest

- CHANGELOG.rst
Now that we have fixed towncrier to render the proper title, seems fitting
to update the others
> Fix "Pytest" to "pytest" in the CHANGELOG

- changelog/2639.removal.rst
- setup.py
- src/_pytest/deprecated.py
- src/_pytest/hookspec.py
- testing/test_pluginmanager.py
This is based on #3732, so it is better to review after that PR gets merged.
Fix #2639
> Deprecate pytest namespace

- changelog/3695.bugfix.rst
- src/_pytest/python_api.py
- testing/python/approx.py
With respect to #3695 , flip the arguments in the initialization and also use keywords so it's more obvious and less likely to happen in future.  
Can add tests along the lines of the code in #3695 if desired but it seems like an obvious typo fix
> bugfix in ApproxNumpy initialisation, use keywords for arguments to fix

- .travis.yml
- CHANGELOG.rst
- changelog/2220.bugfix.rst
- changelog/2283.feature
- changelog/2639.removal.rst
- changelog/3295.doc.rst
- changelog/3519.trivial.rst
- changelog/3576.feature.rst
- changelog/3579.feature.rst
- changelog/3610.feature.rst
- changelog/3623.feature.rst
- changelog/3661.removal.rst
- changelog/3695.bugfix.rst
- changelog/980.bugfix.rst
- doc/en/announce/index.rst
- doc/en/announce/release-3.7.0.rst
- doc/en/example/markers.rst
- doc/en/example/nonpython.rst
- doc/en/example/reportingdemo.rst
- doc/en/example/simple.rst
- doc/en/fixture.rst
- doc/en/getting-started.rst
- tox.ini
> Release 3.7.0

- CHANGELOG.rst
- changelog/3473.bugfix.rst
- changelog/3712.bugfix.rst
- src/_pytest/python_api.py
- testing/python/approx.py
This PR fixes a couple small issues with ``approx()``:
- Change the output of ``repr(approx(np.array(...)))`` to reflect the dimension of the array being compared.  For example, ``repr(approx([[1, 2], [3, 4]]))`` would look something like ``approx([[1±..., 2±...], [3±..., 4±...]])`` rather than ``approx([1±..., 2±..., 3±..., 4±...])``.  This was supposed to fix #3712, but it turns out that #3615 already fixed it.  Still, I think it's nice to have a more accurate repr.
- Check for type errors as soon as the approx object is instantiated, rather than waiting until a comparison is made.  Fixes #3473.  This includes very clear error messages if the user tries to use nested dictionaries or lists, since people seem to assume that this will work.  (And maybe it should, but that's a different …
> Miscellaneous improvements to approx()

- changelog/3748.bugfix.rst
- src/_pytest/python_api.py
Fix #3748
cc @ironiccode @tigarmo
I tested this patch manually using this example from @tigarmo using `numpy 1.11`:
```python
def testApprox():
from pytest import approx
import numpy as np
a = np.array([1, 2, 3])
assert a == approx([1, 2, 3])
```
I did not add tests for this because it requires `numpy<1.13`. I thought it overkill to add another CI environment because of this.
> Fix recursion in pytest.approx() with arrays in numpy<1.13

- changelog/3747.bugfix.rst
- src/_pytest/compat.py
- src/_pytest/fixtures.py
- testing/deprecated_test.py
- testing/python/fixture.py
This refactors the code so we have the real function object right during
collection. This avoids having to unwrap it later and lose attached information
such as "async" functions.
I've tested this with `pytest-asyncio` and it fixes https://github.com/pytest-dev/pytest-asyncio/issues/89.
Fix #3747, Fix #3720
Fix https://github.com/pytest-dev/pytest-asyncio/issues/89
> Refactor direct fixture call warning to avoid incompatibility with plugins

- src/_pytest/main.py
- testing/example_scripts/fixtures/custom_item/conftest.py
- testing/example_scripts/fixtures/custom_item/foo/test_foo.py
- testing/python/fixture.py
- testing/test_collection.py
I did not have time to investigate the issue yet, but took a few minutes to produce a failing test for #3742.
At first I'm not sure how to fix the regression, so I would appreciate suggestions here.
cc @jonozzz
> Workaround for #3742

- changelog/3775.bugfix.rst
- src/_pytest/config/__init__.py
- testing/example_scripts/config/collect_pytest_prefix/conftest.py
- testing/example_scripts/config/collect_pytest_prefix/test_foo.py
- testing/test_config.py
> Only consider actual functions when collecting hooks

- changelog/3771.bugfix.rst
- src/_pytest/python.py
- testing/example_scripts/collect/package_infinite_recursion/conftest.py
- testing/example_scripts/collect/package_infinite_recursion/tests/test_basic.py
- testing/python/collect.py
Adding an example for a bug we found at work. This blows up with:
```
.env36\lib\site-packages\pluggy\hooks.py:258: in __call__
return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
.env36\lib\site-packages\pluggy\manager.py:67: in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
.env36\lib\site-packages\pluggy\manager.py:61: in <lambda>
firstresult=hook.spec_opts.get('firstresult'),
src\_pytest\python.py:210: in pytest_collect_file
return ihook.pytest_pycollect_makemodule(path=path, parent=parent)
.env36\lib\site-packages\pluggy\hooks.py:258: in __call__
return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
.env36\lib\site-packages\pluggy\manager.py:67: in _hookexec
return self._inner_hookexec(hook, methods, kwargs) …
```
> Fix infinite recursion collection bug with pytest_ignore_collect hook

- AUTHORS
- changelog/3784.feature.rst
- doc/en/reference.rst
- src/_pytest/config/__init__.py
- src/_pytest/helpconfig.py
- testing/test_config.py
If `PYTEST_DISABLE_PLUGIN_AUTOLOAD` is set, disable auto-loading of
plugins through setuptools entrypoints. Only plugins that have been
explicitly specified are loaded.
ref #3784.
> Add option to disable plugin auto-loading

- src/_pytest/compat.py
- src/_pytest/fixtures.py
- testing/acceptance_test.py
- testing/example_scripts/acceptance/fixture_mock_integration.py
- testing/test_compat.py
> Fix issue where fixtures would lose the decorated functionality

- src/_pytest/config/argparsing.py
Encountered the warning myself and to me the message was not clear about
what should be done to fix the warning
> Improve warning messages when addoption is called with string as `type`

- changelog/3768.bugfix.rst
- changelog/3789.bugfix.rst
- src/_pytest/python.py
- testing/python/collect.py
This should fix the issue but I still can't find a better fix. See the comment in the code.
What happens is: the files and directories are marked as duplicates when the Session starts collection even though they're not turned into nodes right away (the package nodes will do that later). Ideally is that when Session finds a Package it should stop recursing and move on.
> Fix test collection from packages mixed with directories. #3768 and #3789

- changelog/3804.bugfix.rst
- src/_pytest/_code/code.py
- testing/code/test_excinfo.py
> Fix traceback reporting for exceptions with `__cause__` cycles.

- .pre-commit-config.yaml
More and more are hitting this now that brew moved to python3.7.  Here's a few reports:
- https://github.com/pytest-dev/pytest/issues/3833#issuecomment-414195025
- https://github.com/pytest-dev/pytest/pull/3838#issuecomment-414214293
Note that this is what upstream `black` does in their configuration: https://github.com/ambv/black/pull/430
> Use more flexible `language_version: python3`

- changelog/3033.bugfix.rst
- src/_pytest/capture.py
- testing/test_capture.py
The problem is that the fixtures didn't live up to the promise to properly accumulate output between setup/call/teardown. This works in `3.2` because we didn't allow to access the fixture during setup/teardown from the first place, so it didn't need to accumulate any buffer.
Follow up to #3066, fixes #3033.
> Fixtures during teardown can use capsys and capfd to get output from tests

- AUTHORS
- changelog/3837.feature.rst
- src/_pytest/pytester.py
- testing/test_pytester.py
Added support for xfailed and xpassed outcomes to the ``pytester.RunResult.assert_outcomes`` signature.
closes https://github.com/pytest-dev/pytest/issues/3837
> Support xfailed and xpassed outcomes in RunResult.

- changelog/3845.trivial.rst
- doc/en/skipping.rst
The documentation (https://docs.pytest.org/en/latest/skipping.html) references
issue #568, which has since been fixed.
> Remove warning about #568 from documentation

- changelog/3816.bugfix.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
Add a check before printing teardown logs.
'print_teardown_sections' method does not check '--show-capture' option
value, and teardown logs are always printed.
Resolves: #3816
> Fix '--show-capture=no' capture teardown logs

- changelog/3843.bugfix.rst
- src/_pytest/main.py
- testing/acceptance_test.py
The problem was that _matchnodes would receive two items: [DoctestModule, Module]. It would then collect the first one, *cache it*, and fail to match against the name in the command line. Next, it would reuse the cached item (DoctestModule) instead of collecting the Module which would eventually find the "test" name on it.
Added the type of the node to the cache key to avoid this problem, although I'm not a big fan of caches that have different key types.
Fix #3843
> Fix collection error when tests is specified with --doctest-modules

- AUTHORS
- changelog/3824.doc.rst
- doc/en/example/pythoncollection.rst
- doc/en/reference.rst
Expanding the documentation a bit to be more explicit about how to search for multiple glob patterns when changing test collection.
> Resolving Issue #3824 

- testing/acceptance_test.py
- testing/code/test_code.py
- testing/code/test_excinfo.py
- testing/python/collect.py
- testing/python/fixture.py
- testing/python/metafunc.py
- testing/test_assertrewrite.py
- testing/test_cacheprovider.py
- testing/test_capture.py
- testing/test_collection.py
- testing/test_config.py
- testing/test_conftest.py
- testing/test_doctest.py
- testing/test_terminal.py
I also manually reindented a lot of tqs literals since `black` munged them
I only touched `./testing` as to avoid changing public behaviour
> Replace Source with dedent where possible

- changelog/3848.bugfix.rst
- src/_pytest/config/argparsing.py
- src/_pytest/pytester.py
- testing/test_pytester.py
CI for [my plugin](https://github.com/wimglenn/pytest-custom-report/pull/1) is failing on  2.7, but when checking in the code I don't think I'm doing anything wrong actually.  Look to me like the problem is in `pytester.py`, so trying to fix it there - don't randomly call str() on args which might be unicode objects (this seems to have been originally done to convert py.path.local instances to ordinary strings, but done a bit over-zealously).
> fixed a bunch of unicode bugs in pytester.py

- doc/en/example/assertion/global_testmodule_config/conftest.py
- doc/en/example/multipython.py
- src/_pytest/_code/_py2traceback.py
- testing/acceptance_test.py
- testing/code/test_excinfo.py
- testing/test_argcomplete.py
- testing/test_assertrewrite.py
- testing/test_helpconfig.py
- testing/test_parseopt.py
- testing/test_pdb.py
- testing/test_terminal.py
I'm doing these slowly because I found one kind of unfortunate thing that I didn't notice in my code (because I only use `from __future__ import unicode_literals`, but `pytest` does not 😭)
The one python2-only quirk is this:
```pycon
>>> '%s' % u'\u2603'
u'\u2603'
>>> '{}'.format(u'\u2603')
File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)
```
In this PR I've formatted the tests, and one file which was exposed by tests (more to come but I didn't want to get burned out on this branch and just abandon it).
> Some pyupgrade 1.4.x changes

- src/_pytest/assertion/rewrite.py
- src/_pytest/assertion/util.py
- testing/test_capture.py
`bytes` is an alias for `str` in python2.6+
> Use `bytes` directly instead of `binary_type`

- doc/en/goodpractices.rst
Should fix #2421.
I noticed that the formatting for the sample `setup.py` code block looks like a quote instead of code block, but I'm not sure why.
> Move information on `pip install -e` to the top

- changelog/3870.doc.rst
- doc/en/goodpractices.rst
Addressing #3870 
If you follow the guide to this point, the correct key for `cmdclass` will be the canonical name 'pytest' rather than the alias 'test' created in setup.cfg.
> Correct cmdclass for doc: Good Integration Practices

- src/_pytest/python.py
> Collect any tests from a package's __init__.py

- .travis.yml
This will run it with `--show-diff-on-failure` then, and helps to keep
it in line / in a central place.
See https://travis-ci.org/pytest-dev/pytest/jobs/420595379 for an example failure.
Appveyor uses TOXENV=linting already.
> Travis: use TOXENV=linting for linting stage

- changelog/3773.bugfix.rst
- src/_pytest/pytester.py
- src/_pytest/python.py
- testing/example_scripts/collect/collect_init_tests/pytest.ini
- testing/example_scripts/collect/collect_init_tests/tests/__init__.py
- testing/example_scripts/collect/collect_init_tests/tests/test_foo.py
- testing/test_collection.py
> Collect tests from __init__.py files if they match 'python_files'

- testing/test_monkeypatch.py
- testing/test_pluginmanager.py
- testing/test_pytester.py
Noticed these while working in something else
> Remove dangerous sys.path manipulations in test_pluginmanager

- changelog/3853.bugfix.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
> Cache now obeys -q when showing summary for --lf and --ff

- changelog/3883.bugfix.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
> Fix bad console output when using console_output_style=classic

- .travis.yml
- changelog/3888.bugfix.rst
- src/_pytest/doctest.py
- testing/python/fixture.py
> travis: run tests on macOS

- changelog/3506.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
What happens is that atomic_write on Python 2.7 on Windows will try
to convert the paths to unicode, but this triggers the import of
the encoding module for the file system codec, which in turn triggers
the rewrite, which in turn again tries to import the module, and so on.
This short-circuits the cases where we try to import another file when
writing a pyc file; I don't expect this to affect anything because
the only modules that could be affected are those imported by
atomic_writes.
The fix has been tested in an actual repository showing the problem: https://github.com/Pylons/pyramid-cookiecutter-starter/pull/56
Fix #3506
> Avoid possible infinite recursion when writing pyc files in assert rewrite

- .travis.yml
Given that our guidelines demand that the CI have already passed, it seems
wasteful to run all those jobs again for the exact same commit.
As discussed in https://github.com/pytest-dev/pytest/pull/3906#issuecomment-417094481,
this will skip the "test" stage when building a tag for deployment.
> Skip the "test" stage when making a release

- .coveragerc
- .travis.yml
- tox.ini
https://codecov.io/gh/pytest-dev/pytest/tree/coverage
TODO:
> Travis: report coverage with all builds

- changelog/3907.doc.rst
- doc/en/skipping.rst
> doc fix: raises accepts tuples instead of lists

- changelog/3911.bugfix.rst
- setup.py
- src/_pytest/terminal.py
as discussed in https://github.com/pytest-dev/py/pull/197
> improve line width estimate

- AUTHORS
- changelog/3566.doc.rst
- doc/en/conf.py
- doc/en/usage.rst
PR for https://github.com/pytest-dev/pytest/issues/3546#issuecomment-396193071 and  https://github.com/pytest-dev/pytest/issues/3566
> T3566,T3546: added a blurb in usage.rst for usage of flag -r

- src/_pytest/outcomes.py
> Mention explicitly when pytest.skip and pytest.xfail can be called

- appveyor.yml
Ref: benhoyt/scandir#105
Ref: #3111
> Reenable pypy now that scandir can be installed without a compiler

- AUTHORS
- changelog/3913.bugfix.rst
- src/_pytest/config/argparsing.py
- testing/acceptance_test.py
> Fix exit code for command line errors

- testing/python/metafunc.py
- tox.ini
This hopefully fixes the flaky test_idval_hypothesis on AppVeyor
Fix #3707
> Use -n auto now that xdist behaves well in Travis and AppVeyor

- .pre-commit-config.yaml
- changelog/3955.trivial.rst
- scripts/fail
- tox.ini
Resolves #3955
Before:
```console
$ pre-commit  run changelogs-rst --all-files
changelog filenames......................................................Failed
hookid: changelogs-rst
changelog files must be named ####.(feature|bugfix|doc|removal|vendor|trivial).rst
changelog/3251.feture.rst
```
> Improve pre-commit detection for changelog filenames

- changelog/3975.trivial.rst
- src/_pytest/python.py
- src/_pytest/unittest.py
- testing/python/metafunc.py
> Remove im_func

- doc/en/reference.rst
https://docs.pytest.org/en/latest/reference.html#confval-python_files
Also added an example of using one pattern per line.
> Fix rendering of the ini example for python_files

- .gitignore
- doc/en/backwards-compatibility.rst
- doc/en/warnings.rst
Not changed much, only updated with new best practices and described how we will remove functionality in two steps instead of removing them in major releases directly.
> Review backward compatibility policy 

- AUTHORS
- changelog/3849.feature.rst
- doc/en/reference.rst
- src/_pytest/mark/__init__.py
- src/_pytest/mark/structures.py
- testing/test_mark.py
Currently, `parametrize` skips or xfails a test if no arguments are collected. In both cases, the test is considered successful in most (all?) testing systems. This can potentially hide bugs in the argument collection of parametrize, and thus lead to tests not being performed by mistake. The PR adds an ini option that causes a specific exception to be raised when parametrize collects no arguments.
Implements feature request #3849
> Raise exception if parametrize collects an empty parameter set

- changelog/3973.bugfix.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/compat.py
- src/_pytest/paths.py
- testing/test_assertrewrite.py
- testing/test_paths.py
Unfortunately we need to get a `py.path.local` object to perform the fnmatch
operation, it is different from the standard `fnmatch` module because it
implements its own custom logic. So we need to use `py.path` to perform
the fnmatch for backward compatibility reasons.
Ideally we should be able to use a "pure path" in `pathlib` terms (a path
not bound to the file system), but we don't have those in pylib.
Fix #3973
> Fix assertion rewriter crash if cwd changes mid-testing

- changelog/3964.rst
- src/_pytest/logging.py
- testing/logging/test_reporting.py
The logging plugin does not output log messages generated during the
collection-phase when live-logging is enabled. This fixes this.
Fixes #3964
> Add support for logging in collection-phase

- .coveragerc
- .travis.yml
- scripts/prepare-coverage.bat
- tox.ini
This should increase coverage for subprocesses, where `source` is used
only from the config file, but not the initial `--source` argument.
> coverage: use modules

- changelog/3941.bugfix.rst
- src/_pytest/python.py
- testing/python/metafunc.py
> Fix scope determination with indirect parameters

- changelog/3998.bugfix.rst
- src/_pytest/logging.py
- testing/test_pdb.py
Without this caplog.record_tuples etc is not available when using
`--pdb`.
Maybe related to https://github.com/pytest-dev/pytest/issues/3099.
> logging: del item.catch_log_handler only in teardown

- changelog/3999.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
> Fix UnicodeDecodeError in assertion with mixed non-ascii bytes repr + text

- changelog/3749.bugfix.rst
- src/_pytest/main.py
- testing/example_scripts/collect/package_init_given_as_arg/pkg/test_foo.py
- testing/python/collect.py
> Fix 'Package has no len()' error during collection

- src/_pytest/monkeypatch.py
Trivial typo fix in docstring.
Many thanks for everyone's awesome work on `pytest`! I use it every day and could not imagine what my workflow would be without it. Your work is hugely appreciated!
> Fix typo in docstring

- changelog/4013.feature.rst
- doc/en/warnings.rst
- src/_pytest/warnings.py
- testing/test_warnings.py
> Show deprecation warnings even if filters are customized

- AUTHORS
- changelog/3539.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
The current reload hook did not reload code of already imported modules.
See https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.load_module
Fix #3539
> Fix #3539: reload module with assertion rewrite import hook

- doc/en/assert.rst
wip.  cf https://twitter.com/nicoddemus/status/1044314722332561408
> add documentation of register_assert_rewrite

- changelog/4040.trivial.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
A check is added to avoid empty reports with headline only when `-r P` option is used.
> Exclude empty reports for passed tests

- AUTHORS
- changelog/4034.bugfix.rst
- src/_pytest/reports.py
> Ensure user_properties is a list

- changelog/4036.removal.rst
- src/_pytest/hookspec.py
Our policy is to not deprecate features during bugfix releases, but in this
case I believe it makes sense as we are only documenting it as deprecated,
without issuing warnings which might potentially break test suites.
This will get the word out that hook implementations should not use this parameter
at all.
Fix #4036
> Document that item parameter of pytest_warning_captured hook is deprecated

- changelog/4056.bugfix.rst
- src/_pytest/monkeypatch.py
- src/_pytest/recwarn.py
- testing/acceptance_test.py
- testing/code/test_source.py
- testing/test_cacheprovider.py
- testing/test_junitxml.py
- testing/test_monkeypatch.py
Fixes the bug described in https://github.com/tox-dev/tox/pull/1025#discussion_r221273830, which is more evident when using `unicode_literals`.
cc @gaborbernat
> Ensure Monkeypatch setenv and delenv use bytes keys in Python 2

- changelog/4066.bugfix.rst
- src/_pytest/_code/source.py
- testing/code/test_source.py
> Fix source reindenting by using `textwrap.dedent` directly.

- changelog/2535.bugfix.rst
- src/_pytest/fixtures.py
- testing/example_scripts/unittest/test_parametrized_fixture_error_message.py
- testing/python/fixture.py
- testing/test_unittest.py
> Improve error message when TestCase functions use a parametrized fixture

- testing/code/test_excinfo.py
- testing/logging/test_fixture.py
cherry picked a few from `pytest testing/{subdir} --durations=5` and wanted to see what I could do to make them faster.
this saves ~11 seconds off of a test run (which isn't much but it's something!)
interesting to note that `runpytest_subprocess` adds about 500ms per invocation. (I guess we should avoid it if possible? @nicoddemus do you know if there's a reason why it was used for #3124?)
> Improve performance of ~3 of the slowest tests

- appveyor.yml
broken in #4089
will revert after `virtualenv` releases with upgrade `pip` which _should_ fix the installation issue
> Temporarily disable `linting` env in appveyor

- .pre-commit-config.yaml
- appveyor.yml
- src/_pytest/config/__init__.py
> re-enable linting tox env on windows

- testing/test_pdb.py
https://github.com/antocuni/pdb
> tests: fixes for pdbpp

- changelog/4012.bugfix.rst
- changelog/4102.bugfix.rst
- changelog/4102.feature.rst
- src/_pytest/recwarn.py
- testing/test_recwarn.py
Resolves #4102
I'm targetting `features` because it changes the exception type and message.  Though it ~could be considered a bugfix by stretch and target `master` instead?
Edit: Resolves #2917
> Implement pytest.deprecated_call with pytest.warns

- changelog/4093.trivial.rst
- doc/en/example/assertion/failure_demo.py
- doc/en/example/reportingdemo.rst
- src/_pytest/assertion/util.py
- src/_pytest/cacheprovider.py
- src/_pytest/capture.py
- src/_pytest/compat.py
- src/_pytest/deprecated.py
- src/_pytest/helpconfig.py
- src/_pytest/python.py
- src/_pytest/recwarn.py
- src/_pytest/terminal.py
- testing/acceptance_test.py
- testing/logging/test_formatter.py
- testing/test_junitxml.py
- testing/test_pdb.py
>  Fix multiple string literals on a line #4093

- changelog/2293.feature.rst
- changelog/2293.trivial.rst
- src/_pytest/fixtures.py
- src/_pytest/mark/__init__.py
- src/_pytest/mark/structures.py
- src/_pytest/nodes.py
- src/_pytest/python.py
- testing/python/fixture.py
- testing/python/metafunc.py
- testing/test_mark.py
- testing/test_runner.py
Currently some usage errors produce very ugly traceback with pytest's internals. For example, mistyping the `scope` of a fixture produces this:
```
============================================= ERRORS ==============================================
_____________________________ ERROR collecting test-scope-mismatch.py _____________________________
src\_pytest\fixtures.py:699: in scope2index
return scopes.index(scope)
E   ValueError: 'modu' is not in list
During handling of the above exception, another exception occurred:
src\_pytest\runner.py:201: in __init__
self.result = func()
src\_pytest\runner.py:265: in <lambda>
call = CallInfo(lambda: list(collector.collect()), "collect")
src\_pytest\python.py:475: in collect
self.session._fixturemanager.parsefactories(self) …
```
> Improve internal error messages

- changelog/3713.doc.rst
- doc/en/reference.rst
> Update usefixtures documentation

- .travis.yml
- appveyor.yml
Docs also checks the documentation for syntax failures, so it should
part of the baseline to bail out early.
> Run docs, doctesting and linting in the same job to save some CI time

- doc/en/deprecations.rst
https://github.com/pytest-dev/pytest/blob/c27c8f41a881cf719e2f12f14c4a9331c8f79e8a/doc/en/deprecations.rst#L241-L247
In the proposed new style using `@pytest.mark.parametrize`,
the example function signature missed the actual arguments.
Add the missing arguments.
> docs: deprecation.rst: Add missing arguments to example code

- changelog/4063.trivial.rst
- doc/en/usage.rst
- src/_pytest/runner.py
- testing/acceptance_test.py
Implements #4063 by excluding 0.00 second long durations from the --durations output unless -vv is used.
> Exclude durations that are 0.00 seconds long.

- src/_pytest/debugging.py
- testing/test_pdb.py
`help quit` in pdb says:
> Quit from the debugger. The program being executed is aborted.
But pytest would continue with the next tests, often making it necessary
to kill the pytest process when using `--pdb` and trying to cancel the
tests using `KeyboardInterrupt` / `Ctrl-C`.
TODO:
> pdb: handle quitting in post_mortem

- tox.ini
- no need for {posargs:testing} really
- remove `-ra`, used with addopts already
> tox.ini: pexpect: use posargs; cleanup posargs

- changelog/4108.bugfix.rst
- src/_pytest/fixtures.py
- src/_pytest/main.py
- testing/acceptance_test.py
- testing/test_conftest.py
This fixes runnings `pytest tests`, where `tests` is a symlink to
`project/app/tests`: previously `project/app/conftest.py` would be
ignored for fixtures then.
> Resolve symlinks for args

- testing/acceptance_test.py
- testing/python/fixture.py
Unfortunately due to fluctuations in runtime "test_something"
might still appear in the final message.
Example failure:
https://ci.appveyor.com/project/pytestbot/pytest/builds/19494829/job/8lx847u0c78m63wf
> Fix flaky durations test

- changelog/4135.bugfix.rst
- src/_pytest/pathlib.py
- testing/test_tmpdir.py
> fix #4135 - handle symlinks in tmp path cleanup

- changelog/4098.feature.rst
- src/_pytest/main.py
- src/_pytest/outcomes.py
- testing/test_runner.py
> Add returncode argument to pytest.exit

- changelog/4149.feature.rst
- pyproject.toml
- setup.cfg
- setup.py
ref #3266 
this starts a build tooling cleanup,
> modernize packaging for setuptools>30.3

- AUTHORS
- CONTRIBUTING.rst
- changelog/4151.doc.rst
> Add testdir examples to CONTRIBUTING guide

- changelog/4152.bugfix.rst
- src/_pytest/assertion/rewrite.py
Resolves #4152 
Couldn't think of a way to test this without implementation / version specific code 🤷‍♂️ -- at least the commit message contains the reproduction
```console
$ cd t && rm -rf __pycache__ && pytest t.py -q -c /dev/null; cd ..
.                                                                        [100%]
=============================== warnings summary ===============================
<unknown>:2: DeprecationWarning: invalid escape sequence \.
-- Docs: https://docs.pytest.org/en/latest/warnings.html
1 passed, 1 warnings in 0.01 seconds
```
```console
$ cd t && rm -rf __pycache__ && pytest t.py -q -c /dev/null; cd ..
.                                                                        [100%]
=============================== warnings summary =============================== …
```
> Display the filename when encountering `SyntaxWarning`.

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- AUTHORS
- CONTRIBUTING.rst
- appveyor.yml
- changelog/4063.trivial.rst
- changelog/4132.bugfix.rst
- changelog/4151.doc.rst
- changelog/4152.bugfix.rst
- doc/en/deprecations.rst
- doc/en/usage.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/debugging.py
- src/_pytest/fixtures.py
- src/_pytest/main.py
- src/_pytest/pytester.py
- src/_pytest/runner.py
- testing/acceptance_test.py
- testing/python/fixture.py
- testing/test_pdb.py
- tox.ini
> Merge master into features (prepare for 3.9, pt2)

- tox.ini
xdist has a workaround inplace for Travis so "-n auto" works.
Fix #4162
> Pass TRAVIS env var to test environments [skip appveyor]

- changelog/4159.feature.rst
- src/_pytest/terminal.py
- testing/acceptance_test.py
- testing/test_terminal.py
To show the subclassed file in legacy test suits in the runtest output
you have to set the verbosity level to at least "-vv" now.
Closes #3211
> Increase required verbosity level for debug output

- changelog/3533.bugfix.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
Using string formatting with the raw escaped object lead to string evaluation
resulting in "<py._xmlgen.raw object>" in skipped test Junit report
Format the unescaped string first, then use the XML escape method as a last step.
> Fix #3533: properly escape raw XML object

- doc/en/deprecations.rst
As mentioned in https://github.com/pytest-dev/pytest/issues/4128#issuecomment-430690498
> Fix hook name in deprecations.rst

- testing/test_tmpdir.py
> fix test_cleanup_keep for expecting symlinks

- .travis.yml
We have moved to codecov for awhile now, and uploading to coveralls is breaking
OS-X builds for py37 [1], so we might as well take this opportunity to drop
it.
[1] https://travis-ci.org/pytest-dev/pytest/jobs/442858038
> No longer upload code coverage to coveralls

- AUTHORS
- changelog/4188.feature.rst
- src/_pytest/terminal.py
This patch makes `pytest --color yes` look like this in case `--verbose` is not passed. I always thought it was too bland before! The colored dots really make failures stand out.
> Make --color more colorful

- changelog/4026.bugfix.rst
- src/_pytest/compat.py
- testing/test_collection.py
This is an improvement as it at least indicates which is the problematic function:
```
============================================= ERRORS ==============================================
__________________________________ ERROR collecting test-foo.py ___________________________________
Could not determine arguments of <bound method TestCase.fix of <test-foo.TestCase object at 0x000001A6AA687908>>: invalid method signature
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================== 1 error in 0.10 seconds =====================================
```
Fix #4026
> Improve error message when it is not possible to determine a function's signature

- .pre-commit-config.yaml
I've seen some issues with pre-commit-hooks<2.x though I think they only affect python2? not sure -- but either way this upgrade passes: https://github.com/pre-commit/pre-commit-hooks/issues/328
> Upgrade pre-commit/pre-commit-hooks to 2.0.0

- changelog/3691.bugfix.rst
- src/_pytest/warnings.py
- testing/test_warnings.py
- tox.ini
> Use safe_str() to format warning message about unicode in Python 2

- doc/en/tmpdir.rst
> fix typo in tmpdir documentation (trivial)

- changelog/3340.bugfix.rst
- src/_pytest/logging.py
- testing/logging/test_reporting.py
Fix issue #3340: missing logging on some hooks
Add logging capture for `pytest_sessionstart()` and `pytest_sessionfinish()`
I didn't find anywhere this could be documented; these hooks aren't well documented and this just restores a normal behavior.
> Fix logging usage in hooks pytest_sessionstart/finish

- changelog/2909.bugfix.rst
- src/_pytest/fixtures.py
- testing/example_scripts/fixtures/fill_fixtures/test_detect_recursive_dependency_error.py
- testing/python/fixture.py
> Improve error message when a recursive dependency between fixtures is detected

- doc/en/skipping.rst
> Remove pytest.config example from skipping at module level docs

- doc/en/example/py2py3/test_py2.py
- doc/en/example/py2py3/test_py3.py
- src/_pytest/assertion/rewrite.py
- src/_pytest/pathlib.py
I'm prepping the 3.6.0 flake8 release, figured I'd try some larger codebases :)
> Fixes for flake8 master

- changelog/4174.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_conftest.py
Fixes https://github.com/pytest-dev/pytest/issues/4174.
> Fix "Plugin already registered" error with symlinks

- .travis.yml
This has been failing as of 2018-10-23 while installing gcc with
this message:
```
==> Installing numpy dependency: gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-8.2.0.high_sierra.bottl
######################################################################## 100.0%
==> Pouring gcc-8.2.0.high_sierra.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
rm '/usr/local/include/c++'
To force the link and overwrite all conflicting files:
brew link --overwrite gcc
To list all files that would be deleted:
brew link --overwrite --dry-run gcc
Possible conflicting files are:
/usr/local/include/c++ -> …
```
> Fix MacOS py37 on Travis

- changelog/4225.feature.rst
- src/_pytest/terminal.py
Running `pytest -k doesnotmatch` on pytest's own tests takes ~3s with
Kitty terminal for me, but only ~1s with `-q`.
It also is faster with urxvt, but still takes 2.2s there.
This patch only calls `report_collect` every 0.1s, which is good enough
for reporting collection progress, and improves the time with both Kitty
and urxvt to ~1.2s for me.
TODO:
> TerminalWriter: write "collecting" msg only once every 0.5s

- changelog/4028.trivial.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
Resolves #4027
I noticed this code while working on [future-breakpoint](https://github.com/asottile/breakpoint).
Here's the tests with that installed under python2.7:
```
=========================== short test summary info ============================
FAIL testing/test_pdb.py::TestDebuggingBreakpoints::()::test_supports_breakpoint_module_global
===================== 1 failed, 41 passed in 17.26 seconds =====================
```
> Revert patching of breakpointhook as it appears to do nothing

- src/_pytest/debugging.py
> Fix flake8: os imported, but unused

- src/_pytest/config/__init__.py
For pytest's own suite the `cache_info()` looks as follows:
> session.config._getconftest_pathlist.cache_info()
CacheInfo(hits=231, misses=19, maxsize=None, currsize=19)
While it does not really make a difference for me this might help with
larger test suites / the case mentioned in
https://github.com/pytest-dev/pytest/issues/2206#issuecomment-432623646.
/cc @boxed
> Use functools.lru_cache with _getconftest_pathlist

- changelog/2619.feature.rst
- src/_pytest/debugging.py
- src/_pytest/hookspec.py
- testing/test_pdb.py
After `pdb.set_trace()` capturing is turned off.
This patch resumes it after using the `continue` (or `c` / `cont`)
command.
I've noticed that any captured output from before the `set_trace` is lost, but that does not appear to be caused by my patch - need to investigate.
I've only tested this on `master` for now.
TODO:
> pdb: resume capturing after `continue`

- src/_pytest/compat.py
- src/_pytest/config/__init__.py
Ref: https://github.com/pytest-dev/pytest/pull/4227#discussion_r228060373
> Move lru_cache wrapper to compat

- src/_pytest/main.py
- src/_pytest/python.py
- testing/test_session.py
This removes the hack added in
https://github.com/pytest-dev/pytest/pull/3802.
This also improves performance a bit with the test case for #4237:
Before: 7.95s
After: 7.51s
> Move handling of duplicate files

- changelog/4243.bugfix.rst
- src/_pytest/recwarn.py
- testing/test_recwarn.py
> fix #4243 - support positional argument stacklevel on python2

- src/_pytest/config/__init__.py
Ref: https://github.com/pytest-dev/pytest/issues/2206#issuecomment-432623646
I cannot see a real difference myself with clock time (1.2s vs 1.15s with some project and `-k doesnotmatch`), but I think it makes sense anyway, and might help with the above comment.
For pytest itself:
new: 1 loop, best of 5: 1.73 sec per loop
old: 1 loop, best of 5: 1.61 sec per loop
However, pytest itself displays "2287 deselected in 1.06 seconds" vs "2287 deselected in 1.22 seconds".
> _getconftestmodules: avoid isfile()/dirpath()

- changelog/4181.bugfix.rst
- src/_pytest/pathlib.py
- testing/test_tmpdir.py
for the deferred elements i created issues
> handle race condition when creation and deletion of a numbered dir overlap

- changelog/4255.doc.rst
- doc/en/reference.rst
Added the missing documentation to [filterwarnings](https://docs.pytest.org/en/latest/reference.html#pytest-mark-filterwarnings) section that module names passed are not regex-filtered.
> Fixes #4255 by adding to the doc that module names are not regex-escaped

- changelog/4260.bugfix.rst
- src/_pytest/_code/source.py
Resolves #4260 
For the same reasons as [this](https://github.com/pytest-dev/pytest/pull/4153#issuecomment-429675418) it's difficult to write a future-proof regression test for this.
Here's what I used locally to verify this though:
```python
import pytest
@pytest.mark.xfail
def test_xfail():
assert False
def test():
'\d'
```
```
$ rm -rf __pycache__/ && pytest -Wonce t.py
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.9.4.dev5+ge6e40db9, py-1.7.0, pluggy-0.8.0
rootdir: /tmp/pytest, inifile: tox.ini
collected 2 items                                                              
t.py x.                                                                  [100%]
=========================== short test summary info …
```
> Swallow warnings during anonymous compilation of source

- doc/en/contents.rst
- doc/en/example/multipython.py
- doc/en/flaky.rst
Adding a docs page giving guidance on treatment of flaky tests. Discovered there are no less than 5 plugins that will rerun failed tests!
I tried to build the docs locally but got this error which I am not sure how to resolve:
```
Warning, treated as error:
autodoc: failed to import function 'hookspec.pytest_assertrepr_compare' from module '_pytest'; the following exception was raised:
No module named 'pluggy'
ERROR: InvocationError for command '/home/brianna/workspace/pytest/.tox/docs/bin/sphinx-build -W -b html . _build' (exited with code 2)
```
The markup looks ok in https://livesphinx.herokuapp.com/ , aside from the :ref: references.
> Add docs page discussing flaky tests

- changelog/2701.bugfix.rst
- src/_pytest/fixtures.py
Fix #2701 
its tricky to trigger those warnings under normal circumstances as they happen before pytest hooks into the warnings system
`python -W always -m pytest testing/test_tmpdir.py --collectonly` could be used to trigger them for example on the cli
> don`t parse compat properties as fixtures

- .pre-commit-config.yaml
I promise I commit things to pytest other than changing this yaml file :sob:
> Upgrade pyupgrade for crlf fixes (again)

- changelog/4277.trivial.rst
- src/_pytest/capture.py
- src/_pytest/debugging.py
- testing/test_pdb.py
Do not display "IO-capturing turned off/on" when ``-s`` is used to avoid
confusion.
TODO:
> pdb: improve msg about output capturing with set_trace

- src/_pytest/config/__init__.py
- testing/test_conftest.py
Also renames `_path2confmods` to `_dirpath2confmods` for clarity (it is
expected to be a dirpath in `_importconftest`).
Merges master to avoid conflict with 63691f56 (which should have been done on features probably).
> _getconftestmodules: use functools.lru_cache

- doc/4266.bugfix.rst
- src/_pytest/compat.py
- src/_pytest/python.py
- testing/python/raises.py
- testing/test_collection.py
- testing/test_compat.py
Fixes https://github.com/pytest-dev/pytest/issues/4266.
> python: collect: ignore exceptions with isinstance

- src/_pytest/main.py
- src/_pytest/pathlib.py
- src/_pytest/python.py
Discussion here: https://github.com/pytest-dev/pytest/issues/2206#issuecomment-433038236
TODO:
> Performance fixes

- changelog/4287.bugfix.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
Causes:
E             def test_1(testdir):
E                 testdir.runpytest()
E         >       __import__('pdb').set_trace()
E
E         ../../test_trace_after_runpytest.py:3:
E         …/Vcs/pytest/src/_pytest/debugging.py:81: in set_trace
E             tw = _pytest.config.create_terminal_writer(cls._config)
E
E         config = None, args = (), kwargs = {}, tw = <py._io.terminalwriter.TerminalWriter object at 0x7f1097088160>
E
E             def create_terminal_writer(config, *args, **kwargs):
E                 """Create a TerminalWriter instance configured according to the options
E                 in the config object. Every code which requires a TerminalWriter object
E                 and has access to a config object should use this function.
E                 """
E …
> debugging: make pytest_configure re-entrant

- HOWTORELEASE.rst
Remove last step, because it was merged already before (changed in
77cad3c4).
[ci skip]
> doc: fix HOWTORELEASE.rst

- changelog/4305.trivial.rst
- testing/test_capture.py
> replace byte/unicode helpers in test_capture with python level syntax

- changelog/4306.bugfix.rst
- src/_pytest/config/__init__.py
> Don't string-compare version numbers

- src/_pytest/main.py
- src/_pytest/nodes.py
this removes a perky monkey-patch on configu
> move Bestrelpath cache move to session

- changelog/4310.bugfix.rst
- src/_pytest/main.py
- src/_pytest/python.py
- testing/test_collection.py
Packages are collected twice.
Fails with:
E       Failed: nomatch: 'collected 2 items'
E           and: '==================================================================================== test session starts ====================================================================================='
E           and: 'platform linux -- Python 3.6.6, pytest-3.10.1.dev18+g01c8fab1, py-1.7.0, pluggy-0.8.0'
E           and: "hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('…/Vcs/pytest/.hypothesis/examples')"
E           and: 'rootdir: /tmp/pytest-of-user/pytest-683/test_collect_init_tests0, inifile: pytest.ini'
E           and: 'plugins: testmon-0.9.13, hypothesis-3.71.10'
E       exact match: 'collected 2 items'
E       fnmatch: '<Package *'
E          with: "<Package …
> Fix handling of duplicate args with regard to Python packages

- changelog/4329.bugfix.rst
- src/_pytest/terminal.py
`_collect_report_last_write` might be None, when `pytest_collection` was
not called before.  Not sure if this indicates another problem, but it
can be reproduced with `testing/test_collection.py::TestCollector::()::test_getcustomfile_roundtrip`.
Fixes https://github.com/pytest-dev/pytest/issues/4329
> Fix TypeError in report_collect with _collect_report_last_write

- AUTHORS
- changelog/4304.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_pluginmanager.py
> #4304 the stepwise plugin must be blocked on cacheprovider plugin block request

- src/_pytest/config/__init__.py
- testing/test_collection.py
Fixes https://github.com/pytest-dev/pytest/issues/4332.
> Fix/improve handling of chdir with no-args and testpaths

- .travis.yml
This reverts commit 28dbffdaf26519c79c86df67347ef09c31abf6ae.
Appears to be not necessary anymore:
https://travis-ci.org/pytest-dev/pytest/jobs/452598885#L906
[skip appveyor]
> Travis: fix MacOS py37 build

- changelog/4270.feature.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
Fixes https://github.com/pytest-dev/pytest/issues/4270
"rst" pre-commit hook fails:
> ERROR changelog/4270.feature.rst:1 Unknown interpreted text role "confval".
I think we should fix it to allow for our own roles etc.  /cc @asottile
> cache_dir: use $TOX_ENV_DIR/ prefix if set

- src/_pytest/nodes.py
- testing/acceptance_test.py
- testing/test_nodes.py
- testing/test_session.py
Ref: https://github.com/pytest-dev/pytest/issues/4321#issuecomment-436951894
> Fix nodes._check_initialpaths_for_relpath for dirs

- testing/test_argcomplete.py
Fixes https://github.com/pytest-dev/pytest/issues/4162.
> tests: fix equal_with_bash to handle appearing .coverage files

- changelog/4358.removal.rst
- src/_pytest/nodes.py
- src/_pytest/runner.py
- src/_pytest/terminal.py
- testing/python/collect.py
- testing/test_collection.py
- testing/test_nodes.py
- testing/test_session.py
Fixes https://github.com/pytest-dev/pytest/issues/4127.
> Node: do not add "::()" to nodeid

- changelog/4321.bugfix.rst
- changelog/4325.bugfix.rst
- src/_pytest/main.py
- testing/test_collection.py
Fixes https://github.com/pytest-dev/pytest/issues/4325.
Fixes https://github.com/pytest-dev/pytest/issues/4321.
TODO:
> Fix collection of symlinked files

- .travis.yml
- CONTRIBUTING.rst
- appveyor.yml
- tox.ini
Closes https://github.com/pytest-dev/pytest/issues/4370.
> CI: use py37 instead of py36 by default

- changelog/3737.removal.rst
- doc/en/example/assertion/failure_demo.py
- src/_pytest/warnings.py
- testing/acceptance_test.py
- testing/deprecated_test.py
- testing/python/collect.py
- testing/python/fixture.py
- testing/python/metafunc.py
- testing/test_config.py
- testing/test_mark.py
- testing/test_nose.py
- testing/test_pdb.py
- testing/test_runner_xunit.py
- testing/test_stepwise.py
- testing/test_terminal.py
- testing/test_tmpdir.py
- testing/test_warnings.py
- tox.ini
To keep existing tests which emit RemovedInPytest4Warnings running, decided
to go with a command line option because:
* Is harder to integrate an ini option with tests which already use an ini file
* It also marks tests which need to be removed/updated in 4.1, when
RemovedInPytest4Warning and related functionality are removed.
Fix #3737
> Change RemovedInPytest4Warnings to errors by default

- .travis.yml
- appveyor.yml
- use py27-pexpect,py27-trial,py27-numpy and py37-xdist in baseline,
using pexpect there catches errors with pdb tests early, and
py37-xdist is much faster than py37.
- move py34 and py36 out of baseline.
> Travis: move faster builds to baseline

- src/_pytest/pytester.py
- testing/test_cacheprovider.py
Closes: https://github.com/pytest-dev/pytest/pull/4378
Fixes: https://github.com/pytest-dev/pytest/issues/4366
No changelog, wasn't released yet, and only affects internal usage.
> pytester: pop TOX_ENV_DIR from os.environ

- changelog/3554.bugfix.rst
- src/_pytest/runner.py
- testing/test_runner.py
Fixes https://github.com/pytest-dev/pytest/issues/3554
Ref: https://github.com/pytest-dev/pytest/pull/3560
Ref: https://github.com/pytest-dev/pytest/pull/3562
> Fix CallInfo.__repr__ for unfinished call

- tox.ini
Taken out of https://github.com/pytest-dev/pytest/pull/4347.
> tox: fix/improve posargs with pexpect factor(s)  [ci skip]

- changelog/4405.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_collection.py
Fixes https://github.com/pytest-dev/pytest/issues/4405.
> Fix collection of testpaths with `--pyargs`

- tox.ini
Do not cause a SyntaxError for something like:
> DeprecationWarning: invalid escape sequence \w
This was happening via pdb++ when it imported pygments (and that had no
compiled .pyc file).
> tox.ini: do not cause SyntaxWarning with py37  [ci skip]

- changelog/4400.bugfix.rst
- src/_pytest/python.py
- testing/test_session.py
> fix #4400 - rearrange the handling of yield test warnings/errors

- changelog/4412.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
> Fix assertion rewriting involving Starred + side-effects

- setup.py
- tox.ini
Use this in tox to stream-line base testing requirements.
Closes https://github.com/pytest-dev/pytest/issues/4410.
> setup.py: add "testing" extra requirement

- src/_pytest/config/__init__.py
- src/_pytest/config/findpaths.py
Taken out of https://github.com/pytest-dev/pytest/pull/4337.
> Optimize/revisit determine_setup

- src/_pytest/pytester.py
I just expected this with `monkeypatch.setenv("PYTHONPATH", str(testdir))`,
wondering why it was not picked up correctly.
> Add Testdir.__str__ to return str(self.tmpdir)

- changelog/4421.removal.rst
- src/_pytest/config/__init__.py
- src/_pytest/deprecated.py
- src/_pytest/hookspec.py
- testing/test_pluginmanager.py
> remove pytest namespace hook

- AUTHORS
- changelog/4315.trivial.rst
- src/_pytest/config/__init__.py
Checklist:
---
Fix #4315
Tasks from The issue:
I couldn't figure out the best way to add an acceptance test, but I found that `testing/test_config.py::TestParseIni.test_tox_ini_wrong_version` was already checking the behaviour.  I tried to add a 'right version' test by copying that one and changing the minver in the generated ini to 3.0, but whenever I ran it I'd be getting errors about reading from stdin.  I couldn't figure out what was causing the errors, so I just moved on.
note: I tested this with python 3.7, *not* 3.6 - it was pretty easy to get that to work. Easier than setting 3.6 up in my dev environment at least.  I assume CI will do 3.6, so we'll still have all the coverage and I don't anticipate any issues cropping up.
> Use packaging/pkg_resources to check minversion

- changelog/4397.bugfix.rst
- src/_pytest/compat.py
- src/_pytest/mark/structures.py
- testing/python/metafunc.py
- testing/test_mark.py
Resolves #4397 
targeting `features`:
- *require* that `param(id=...)` is a string
- alter the `id=...` on construction when manually passed to enforce printability
- changes the ids of parametrized bytestrings that weren't printable
> Ensure that node ids are printable

- doc/en/example/markers.rst
Small explicit note on using multiple markers on module level.
> Adds note on multiple module marker usage

- src/_pytest/terminal.py
Very minor consistency improvement.  The bar demonstrating an "ERROR" for a test is now colored bold-red.
Top is before, bottom is after:
> Color the setup ERROR red

- changelog/4425.bugfix.rst
- src/_pytest/monkeypatch.py
- src/_pytest/tmpdir.py
- testing/test_tmpdir.py
> fix 4425: resolve --basetemp to absolute paths

- changelog/4440.trivial.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/cacheprovider.py
- src/_pytest/config/__init__.py
- src/_pytest/config/findpaths.py
- src/_pytest/resultlog.py
- src/_pytest/warnings.py
- testing/test_warnings.py
> Adjust stacklevel of "config" warnings

- changelog/4393.bugfix.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
Fixes https://github.com/pytest-dev/pytest/issues/4393.
It will not "upgrade" existing dirs anymore - not sure if we want to keep this behavior?!
Could be achieved with more logic, but certainly `cache_dir = .` should be skipped etc.
> cacheprovider: do not write README/.gitignore to existing dir

- changelog/4386.bugfix.rst
- src/_pytest/_code/code.py
- testing/python/raises.py
this is a backport of the fixing strategy from #4438
> fix #4386 - handle uninitialized exceptioninfo in repr/str

- changelog/4386.feature.rst
- src/_pytest/_code/code.py
- src/_pytest/assertion/util.py
- src/_pytest/main.py
- src/_pytest/python.py
- src/_pytest/python_api.py
- src/_pytest/runner.py
- src/_pytest/unittest.py
- testing/code/test_code.py
- testing/code/test_excinfo.py
- testing/test_resultlog.py
- testing/test_runner.py
> fix #4386 - restructure construction and partial state of ExceptionInfo

- changelog/3952.bugfix.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
Fixes https://github.com/pytest-dev/pytest/issues/3952.
Ref: https://github.com/pytest-dev/pytest/pull/3956.
> Display "short test summary info" after (main) warnings again

- testing/python/fixture.py
* Run it in a subprocess to reduce possible intereference from the outer pytest
* Print the leaked objects to see if they provide any hints
> Try to fix/improve reporting of test_request_garbage

- changelog/4458.bugfix.rst
- src/_pytest/nodes.py
- testing/python/collect.py
- testing/python/metafunc.py
- testing/test_collection.py
- testing/test_terminal.py
> Display actual test ids in `--collect-only`

- changelog/4435.deprecation.rst
- doc/en/assert.rst
- doc/en/deprecations.rst
- doc/en/example/assertion/failure_demo.py
- doc/en/example/parametrize.rst
- src/_pytest/deprecated.py
- src/_pytest/python_api.py
- src/_pytest/recwarn.py
- testing/code/test_code.py
- testing/code/test_excinfo.py
- testing/code/test_source.py
- testing/example_scripts/fixtures/fill_fixtures/test_conftest_funcargs_only_available_in_subdir/sub2/conftest.py
- testing/python/collect.py
- testing/python/fixture.py
- testing/python/metafunc.py
- testing/python/raises.py
- testing/test_capture.py
- testing/test_config.py
- testing/test_monkeypatch.py
- testing/test_parseopt.py
- testing/test_pluginmanager.py
- testing/test_pytester.py
- testing/test_recwarn.py
- testing/test_runner.py
- testing/test_session.py
- testing/test_terminal.py
> Deprecate `raises(..., 'code(as_a_string)')` / `warns(..., 'code(as_a_string)')`.

- changelog/3083.removal.rst
- changelog/4489.removal.rst
- doc/en/deprecations.rst
- src/_pytest/deprecated.py
- src/_pytest/fixtures.py
- src/_pytest/python.py
- testing/acceptance_test.py
- testing/deprecated_test.py
- testing/python/fixture.py
- testing/python/metafunc.py
Removed `request.cached_setup` and `Metafunc.addcall`.
Fix #4489, #3083
A note: I had to remove some tests because `Metafunc.addcall` can combine arguments in multiple levels of `pytest_generate_tests` hooks, while `Metafunc.parametrize` specifically has a check against that. For example:
```python
def test_generate_plugin_and_module(self, testdir):
testdir.makeconftest(
"""
def pytest_generate_tests(metafunc):
assert "arg1" in metafunc.fixturenames
metafunc.addcall(id="world", param=(2,100))
"""
)
p = testdir.makepyfile(
"""
def pytest_generate_tests(metafunc):
metafunc.addcall(param=(1,1), id="hello")
import pytest
@pytest.fixture
def arg1(request):
return request.param[0]
@pytest.fixture
def arg2(request):
return request.param[1]
class TestClass(object):
def test_myfunc(self, arg1, …
```
> Remove cached_setup and Metafunc.addcall

- changelog/3079.removal.rst
- changelog/3616.removal.rst
- changelog/4421.removal.rst
I think this makes all the difference when users need to read the CHANGELOG. 👍
> Add links to the deprecations docs for the "removal" changelog entries

- changelog/4487.bugfix.rst
- src/_pytest/capture.py
```
22:56:26,997 [pytestsalt.utils:206 ][INFO    ][1024] Stopping process psutil.Process(pid=1228, name='/home/vampas/.d', started='22:55:17') and respective children: [psutil.Process(pid=1245, name='/home/vampas/.d', started='22:55:18'), psut
il.Process(pid=1262, name='/home/vampas/.d', started='22:55:19'), psutil.Process(pid=1263, name='/home/vampas/.d', started='22:55:19')]                                                                                                        
Error in atexit._run_exitfuncs:                                                                                                                                                                                                                 …
```
> Logging done late enough might happen when capture already stopped.

- changelog/4487.bugfix.rst
- changelog/4500.bugfix.rst
- testing/test_capture.py
> Test case for #4500 and respective fix #4487

- doc/en/requirements.txt
the upstream sphinx issue seems resolved.  I'll watch this carefully as it merges
I also bumped pygments-pytest to get improved `-q` coloring support
> Upgrade sphinx doc requirements

- changelog/1495.doc.rst
- doc/en/doctest.rst
> Document doctest fixture pitfalls

- changelog/3191.feature.rst
- src/_pytest/assertion/rewrite.py
- testing/test_warnings.py
> [#3191] Give hints when an assertion value is None instead of a boolean 

- changelog/4265.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_config.py
Ref https://github.com/pytest-dev/pytest/issues/4265.
> Ensure that PYTEST_ADDOPTS are valid by themselves

- changelog/3532.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_pluginmanager.py
This still does not use an actual argument parser, which only gets
instantiated below, and it does not appear to make sense instantiating
it just for this pre-parsing it seems.
`-p` without the required value is being handled before already though,
so it could potentially be passed down from somewhere already?!
Fixes https://github.com/pytest-dev/pytest/issues/3532.
> Handle missing space with -p

- testing/test_assertion.py
- testing/test_config.py
- testing/test_junitxml.py
- testing/test_terminal.py
Fix pytest's own tests with PYTEST_DISABLE_PLUGIN_AUTOLOAD=1.
> tests: fix tests that require PYTEST_DISABLE_PLUGIN_AUTOLOAD to be unset

- changelog/3974.deprecation.rst
- doc/en/deprecations.rst
- src/_pytest/deprecated.py
- src/_pytest/python_api.py
- testing/deprecated_test.py
- testing/python/raises.py
- testing/test_pytester.py
> Deprecate the 'message' parameter of pytest.raises

- changelog/4538.bugfix.rst
- src/_pytest/python_api.py
- testing/python/raises.py
> Raise `TypeError` for `with raises(..., match=<non-None falsey value>)`.

- changelog/4532.feature.rst
- src/_pytest/terminal.py
- testing/test_skipping.py
Often in large test suites (like pytest's), the -ra summary is very useful
to obtain a list of failures so we can execute each test at once to fix them.
Problem is the default shows errors and failures first, which leads to a lot
of scrolling to get to them.
> Change -ra to show errors and failures last, instead of first

- changelog/4292.feature.rst
- src/_pytest/main.py
- src/_pytest/outcomes.py
- src/_pytest/runner.py
- testing/test_runner.py
This is required for properly getting out of pdb, where
KeyboardInterrupt is caught in py36 at least.
Ref: https://github.com/pytest-dev/pytest/issues/1865#issuecomment-242599949
/cc @The-Compiler
> Derive outcomes.exit.Exit from SystemExit instead of KeyboardInterrupt

- changelog/4543.removal.rst
- doc/en/deprecations.rst
- src/_pytest/config/__init__.py
- src/_pytest/deprecated.py
- src/_pytest/fixtures.py
- testing/deprecated_test.py
- testing/python/fixture.py
> Remove pytest_funcarg__ prefix support for defining fixtures

- changelog/3050.deprecation.rst
- changelog/3079.removal.rst
- changelog/3083.removal.rst
- changelog/3191.feature.rst
- changelog/3616.removal.rst
- changelog/4278.feature.rst
- changelog/4278.trivial.rst
- changelog/4292.feature.rst
- changelog/4386.feature.rst
- changelog/4416.feature.rst
- changelog/4421.removal.rst
- changelog/4435.bugfix.rst
- changelog/4435.deprecation.rst
- changelog/4483.feature.rst
- changelog/4535.removal.rst
- changelog/4543.removal.rst
I used `towncrier --draft` to see the full changelog, and decided to "nitpick" it
so it reads better as a whole. 😁
> Review changelog entries for features branch

- changelog/4483.feature.rst
- doc/en/usage.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
Just realized while reading the changelog that "junit_time" is not a very good
name, so I decided to open this PR renaming it to "junit_duration_report" which
I believe conveys the meaning of the option better
cc @aparamon
Follow up to #4529
> Rename "junit_time" to "junit_duration_report" option

- changelog/3085.removal.rst
- changelog/4547.removal.rst
- doc/en/deprecations.rst
- src/_pytest/config/__init__.py
- src/_pytest/deprecated.py
- src/_pytest/junitxml.py
- testing/acceptance_test.py
- testing/deprecated_test.py
This removes:
* `record_xml_property`
* string support in `pytest.main()`
Decided to open a single PR because the set of changes is small, but note that each feature was removed in their own commit.
Fix #3085, Fix #4547
> Remove record_xml_property and support for strings in pytest.main()

- changelog/2169.removal.rst
- src/_pytest/python.py
- testing/python/metafunc.py
> Errors in parametrize id functions now propagate the error instead of issuing a warning

- AUTHORS
- changelog/4327.bugfix.rst
- src/_pytest/compat.py
- src/_pytest/python_api.py
- testing/python/approx.py
approx() was updated in 9f3122fe to work better with numpy arrays, however at the same time the requirements were tightened from requiring an `Iterable` to requiring a `Sequence` - the former being
tested only on [interface](https://github.com/python/cpython/blob/f19447994983902aa88362d8fffe645f1ea2f2aa/Lib/_collections_abc.py#L252-L256), while the latter requires subclassing or [registration](https://github.com/python/cpython/blob/f19447994983902aa88362d8fffe645f1ea2f2aa/Lib/_collections_abc.py#L926-L929) with the abc.
This broke our code which uses many custom containers (though it wasn't apparent to us that things were broken until the Scalar testing was tightened in cd2085ee718fb297537638bb33a70fc781ea450f). For various (mainly political) reasons it's hard to change our code for …
> Let approx() work on more generic sequences

- changelog/3078.removal.rst
- doc/en/deprecations.rst
- doc/en/reference.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/cacheprovider.py
- src/_pytest/config/__init__.py
- src/_pytest/config/findpaths.py
- src/_pytest/deprecated.py
- src/_pytest/hookspec.py
- src/_pytest/nodes.py
- src/_pytest/resultlog.py
- src/_pytest/terminal.py
- src/_pytest/warnings.py
- testing/acceptance_test.py
- testing/deprecated_test.py
- testing/test_assertrewrite.py
- testing/test_config.py
- testing/test_pluginmanager.py
- testing/test_pytester.py
- testing/test_warnings.py
> Remove config.warn, Node.warn and pytest_logwarning

- changelog/4545.removal.rst
- doc/en/deprecations.rst
- src/_pytest/deprecated.py
- src/_pytest/fixtures.py
- testing/deprecated_test.py
- testing/python/fixture.py
> Calling fixtures directly is now an error instead of a warning

- changelog/3086.removal.rst
- changelog/4548.removal.rst
- doc/en/deprecations.rst
- src/_pytest/config/__init__.py
- src/_pytest/config/findpaths.py
- src/_pytest/deprecated.py
- testing/deprecated_test.py
> Remove support for [pytest] in setup.cfg files and pytest_plugins in non-top-level conftests

- changelog/4546.removal.rst
- changelog/891.removal.rst
- doc/en/deprecations.rst
- doc/en/reference.rst
- src/_pytest/config/__init__.py
- src/_pytest/fixtures.py
- src/_pytest/mark/__init__.py
- src/_pytest/mark/structures.py
- src/_pytest/nodes.py
- src/_pytest/python.py
- src/_pytest/unittest.py
- testing/test_mark.py
- tox.ini
this removes marker info in various ways
a) no more legacy marker objects on functions (this has surprising effects)
b) keywords are changes in a backward incompatible way as markerinfo goes away
c) plugin hook parsing needs an additional compatibility hack, i registered #4562
d) mark finding got a bit tighter to sort out mistakes in prior normalization
e) gruesome bugs in parameterize and fixture handling have been resolved by switching from attributes to definition markers
fixes https://github.com/pytest-dev/pytest/issues/3515
fixes https://github.com/pytest-dev/pytest/issues/3537 (removes legacy marker transfer which triggers the error)
fixes https://github.com/pytest-dev/pytest/issues/891
fixes #4546
>  Remove MarkInfo

- doc/en/fixture.rst
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>
> Remove an extraneous comma from the docs.

- doc/en/getting-started.rst
Was scrolling through the docs and noticed this, I figure it's easier to remove this than try and keep it in sync with setup.py
> Remove out of date dependencies list in docs

- changelog/4371.feature.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
This implements #4371 by updating --collect-only to display test descriptions when running in verbose mode.
Example output:
```
plugins: xdist-1.23.0, forked-0.2, env-0.6.2, hypothesis-3.73.4
collected 2 items
<Module example_description.py>
Module containing tests.
<Function test_a>
This test has a description
<Function test_b>
This test has one docstring line.
and a second one.
======================== no tests ran in 0.03 seconds =========================
(test_env) C:\Users\User\Desktop\pytest>
```
> 4371: Update --collect-only to display test descriptions when ran in verbose

- changelog/4599.feature.rst
- src/_pytest/outcomes.py
- testing/test_runner.py
> Custom reason support for "importorskip"

- changelog/3375.doc.rst
- doc/en/reference.rst
> Documentation configuration files

- testing/test_warnings.py
Follow up to https://github.com/pytest-dev/pytest/pull/4620#discussion_r246404439
> Change test_warningschecker_twice to a unittest

- AUTHORS
- changelog/2256.bugfix.rst
- src/_pytest/assertion/util.py
- testing/test_assertion.py
Fixes #2256 
Adds a new explanation handler to show reprs of arbitrary objects. The handler shows the full `repr` in test failure output for `assert x==y` when `-vv` is given on the command line.
Here's a test case:
```python
class Nums:
def __init__(self, nums):
self.nums = nums
def __repr__(self):
return str(self.nums)
def test_f():
x = list(range(5000))
y = list(range(5000))
y[len(y)//2] = 3
x = Nums(x)
y = Nums(y)
assert x == y
```
Running on master this gives:
```terminal
$ pytest test_f.py -vv
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.7.1, pytest-4.0.3.dev19+ge8152207, py-1.7.0, pluggy-0.8.0 -- /Users/enojb/current/sympy/venv/bin/python3 …
```
> Show full repr with assert a==b and -vv

- changelog/3456.bugfix.rst
- src/_pytest/doctest.py
- testing/test_doctest.py
>  Doctest: hack in handling mock style objects

- AUTHORS
- changelog/4631.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
> Assertion rewrite breaks for objects that reimplement `__getattr__`

- doc/en/conf.py
- doc/en/deprecations.rst
- doc/en/requirements.txt
Fix https://github.com/pytest-dev/pytest/issues/4568
This is blocked by https://github.com/MrSenko/sphinx-removed-in/pull/1:
---
```
λ tox -re docs
docs create: C:\Users\bruno\pytest\.tox\docs
docs installdeps: -rC:\Users\bruno\pytest/doc/en/requirements.txt
ERROR: invocation failed (exit code 1), logfile: C:\Users\bruno\pytest\.tox\docs\log\docs-1.log
ERROR: actionid: docs
msg: getenv
cmdargs: "'C:\\Users\\bruno\\pytest\\.tox\\docs\\Scripts\\python.EXE' -m pip install '-rC:\\Users\\bruno\\pytest/doc/en/requirements.txt'"
Collecting pygments-pytest>=1.1.0 (from -r C:\Users\bruno\pytest/doc/en/requirements.txt (line 1))
Using cached https://files.pythonhosted.org/packages/49/3e/fc3a0102c4ae97430d34303c0963cc779e8a1c74a73fe6a04539665fdbb0/pygments_pytest-1.1.0-py2.py3-none-any.whl …
```
> Use sphinx removed in extension in the documentation

- changelog/4643.trivial.rst
- src/_pytest/python_api.py
`np.asscalar()` has been deprecated in numpy 1.16:
https://github.com/numpy/numpy/blob/master/doc/release/1.16.0-notes.rst#new-deprecations
> Use a.item() instead of deprecated np.asscalar(a)

- AUTHORS
- changelog/4536.bugfix.rst
- src/_pytest/monkeypatch.py
- testing/test_monkeypatch.py
Correct monkeypatch.delattr to match the correct behavior of monkeypatch.setattr when changing class descriptors.
Issue: https://github.com/pytest-dev/pytest/issues/4536
> Bugfix: monkeypatch.delattr handles class descriptors

- doc/en/contents.rst
- doc/en/py27-py34-deprecation.rst
> Add docs page about plans for dropping py27 and py34

- changelog/4649.bugfix.rst
- src/_pytest/mark/legacy.py
- testing/example_scripts/marks/marks_considered_keywords/test_marks_as_keywords.py
- testing/test_mark.py
which is distinct from nodekeywords
> fix #4649 - also transfer markers to keywordmapping

- changelog/3094.feature.rst
- doc/en/xunit_setup.rst
- src/_pytest/python.py
- src/_pytest/unittest.py
- testing/python/collect.py
- testing/python/fixture.py
WIP for #3094.
Unfortunately I'm not able to get this to work with yield tests, their expectations about when `setup_*` functions are called break when we move the `setup_*` call to fixtures.
Consider this test (simplified from `test_runner_xunit.py::test_func_generator_setup`):
```python
import sys
def setup_module(mod):
mod.x = []
def test_one():
assert x == []
def check():
assert True
yield check
```
This is what happens on `master`: during collection, `setup_module` is called (by `Node.setup()`), then `test_one` is called to generate the internal yield test function `check`. For this reason, the `assert x == []` line at the beginning of `test_one` works.
What this PR does is to inject an autouse module-scoped fixture which calls `setup_module`. The problem is that this changes the …
> Use fixtures to invoke xunit-style fixtures

- changelog/4667.bugfix.rst
- src/_pytest/junitxml.py
- src/_pytest/pytester.py
- src/_pytest/reports.py
- src/_pytest/skipping.py
- src/_pytest/terminal.py
- testing/acceptance_test.py
- testing/test_skipping.py
- testing/test_terminal.py
`pytest_terminal_summary` uses result from `pytest_report_teststatus` hook, rather than hardcoded strings
Fix https://github.com/pytest-dev/pytest/issues/4667
> short report summary to use report teststatus data

- changelog/4402.bugfix.rst
- src/_pytest/terminal.py
- testing/example_scripts/warnings/test_group_warnings_by_message.py
- testing/test_warnings.py
Currently pytest shows warnings grouped by node id. What usually happens is that in large codebases the offending code ends up called from multiple tests, generating a lot of output which usually points to the same code over and over again.
For example:
```python
import warnings
import pytest
def func():
warnings.warn(UserWarning("foo"))
@pytest.mark.parametrize("i", range(5))
def test_foo(i):
func()
def test_bar():
func()
``` 
Currently generates:
```
========================= warnings summary ==========================
test-warning-grouping.py::test_foo[0]
c:\pytest\.tmp\test-warning-grouping.py:6: UserWarning: foo
warnings.warn(UserWarning("foo"))
test-warning-grouping.py::test_foo[1]
c:\pytest\.tmp\test-warning-grouping.py:6: UserWarning: foo
warnings.warn(UserWarning("foo")) …
```
> Group warnings by message instead of by test id

- AUTHORS
- changelog/3547.bugfix.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
Continuation of #4493 
cc: @nicoddemus @RonnyPfannschmidt 
Known issues so far:
1) A few failing tests
2) Debugging output needs to be removed
3) There's no good way to inform either `_NodeReporter` or `LogXML` about which family they should choose. Not without horrifically breaking either of them.
4) Use of module-global variable
Note:
Despite the tests failing this _does_ emit different/corrected XML for the selected `junit_family=[(old|xunit1),xunit2]`.
> Toggle JUnit behavior with INI option

- doc/en/deprecations.rst
Based on recent discussions in #3974
> Improve pytest.raises 'message' deprecation docs

- changelog/4669.bugfix.rst
- src/_pytest/nose.py
- testing/test_nose.py
> Handle unittest.SkipTest exception with non-ascii characters

- changelog/4688.feature.rst
- src/_pytest/hookspec.py
- src/_pytest/resultlog.py
- src/_pytest/terminal.py
Now that `pytest.config` is deprecated, this allows users to access the config object and avoid "hacks" such as https://github.com/hackebrot/pytest-emoji/pull/4
> Add config to pytest_report_teststatus

- changelog/4680.bugfix.rst
- changelog/4681.bugfix.rst
- src/_pytest/tmpdir.py
- testing/python/fixture.py
- testing/test_tmpdir.py
> Fix 4680 - `tmp_path` and `tmpdir` now share the same temporary directory

- changelog/4691.feature.rst
- src/_pytest/hookspec.py
- src/_pytest/terminal.py
The docs stated that this hook got the 'config' parameter in 3.5, but the docs
were probably changed by mistake.
> Add config to pytest_terminal_summary hook

- changelog/4627.feature.rst
- src/_pytest/terminal.py
- testing/acceptance_test.py
- testing/deprecated_test.py
Output:
```
testing\deprecated_test.py .                                             [100%]
========================== deprecated python version ==========================
You are using Python 2.7.15, which will no longer be supported in pytest 5.0
For more information, please read:
https://docs.pytest.org/en/latest/py27-py34-deprecation.html
=================== 1 passed, 14 deselected in 0.13 seconds ===================
```
Fix #4627
> Show deprecation message when running under Python 2.7 and 3.4

- .pre-commit-config.yaml
- src/_pytest/config/__init__.py
- src/_pytest/fixtures.py
- src/_pytest/logging.py
- src/_pytest/mark/structures.py
- src/_pytest/runner.py
I opted to _remove_ the PEP 484 type comment annotations for now since we're not linting for mypy
Also upgraded the pre-commit hooks since `virtualenv` has been released fixing the weird `black` issue that was happening before
> fixes for flake8 3.7

- changelog/3899.bugfix.rst
- src/_pytest/config/__init__.py
- testing/acceptance_test.py
> Do not raise UsageError when "pytest_plugins" is a module

- src/_pytest/logging.py
> Only call _setup_cli_logging in __init__

- changelog/2895.bugfix.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
> Call pytest_report_collectionfinish hook when --collect-only is passed

- AUTHORS
- changelog/4709.doc.rst
- doc/en/warnings.rst
I added a section to the docs on how to customize test failure messages for missing warnings when using `pytest.warns`, following some discussion in #3974 and adapting an example from @asottile.
> Document how to customize test failure message for missing warnings

- changelog/3899.doc.rst
- doc/en/plugins.rst
> Mention that `pytest_plugins` should not be used as module name

- changelog/4739.bugfix.rst
- src/_pytest/python.py
- testing/python/metafunc.py
> Fix `parametrize(... ids=<function>)` when the function returns non-strings

- changelog/4592.bugfix.rst
- src/_pytest/main.py
- src/_pytest/python.py
- testing/test_collection.py
`_collectfile` should be called on files only.
Fixes https://github.com/pytest-dev/pytest/issues/4592.
TODO:
- ~~[ ] remove assertions?~~
> Fix handling of collect_ignore from parent conftest

- tox.ini
Fixes https://github.com/pytest-dev/pytest/issues/4750.
> tox: py37-freeze: use --no-use-pep517 for PyInstaller

- changelog/526.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_conftest.py
Some build systems (e.g. bazel) create build directories that have original source files symlinked and not copied or hardlinked.
This confused pytest which tried to refer to a conftest file by realpath in some cases and with symlink path in others, leading to "ValueError: Plugin already registered"  exception. This PR fixes that.
> Fix "ValueError: Plugin already registered" exceptions when running in build directories that symlink to actual source.

- AUTHORS
- changelog/3711.feature.rst
- doc/en/example/pythoncollection.rst
- doc/en/reference.rst
- src/_pytest/main.py
- testing/test_collection.py
- testing/test_session.py
This changes the `--ignore` option to allow Unix-style wildcards so
that `--ignore=integration*` excludes all tests that reside in files
starting with `integration`.
Fixes: #3711
> Add ability to use globs when using --ignore

- changelog/4741.trivial.rst
- src/_pytest/logging.py
- src/_pytest/terminal.py
The workaround was removed from the logging module by creating python
properties for verbosity related settings in the terminalreporter.
Closes: #4733
> Remove terminal_reporter workaround from logging.py

- src/_pytest/pytester.py
- testing/test_pytester.py
> Add __repr__ for RunResult

- changelog/4745.bugfix.rst
- src/_pytest/main.py
- testing/test_collection.py
Ref: https://github.com/pytest-dev/pytest/issues/4344#issuecomment-441095934
TODO:
> Fix handling of pkg init and test file via args

- src/_pytest/pytester.py
This can spam a lot of warnings (per invocation), e.g.:
> lsof: WARNING: can't stat() nsfs file system /run/docker/netns/default
Output information may be incomplete.
Or from Travis/MacOS:
> lsof: WARNING: can't stat() vmhgfs file system /Volumes/VMware Shared Folders
>       Output information may be incomplete.
>       assuming "dev=31000003" from mount table
> --lsof: suppress stderr

- changelog/2753.feature.rst
- changelog/4651.bugfix.rst
- src/_pytest/config/__init__.py
- src/_pytest/config/argparsing.py
- src/_pytest/helpconfig.py
- testing/test_config.py
- testing/test_parseopt.py
Fixes https://github.com/pytest-dev/pytest/issues/2753.
TODO:
> Display --help/--version with ArgumentErrors

- changelog/4347.bugfix.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
TODO:
~~- [ ] harden/warning: https://github.com/pytest-dev/pytest/pull/4347#discussion_r232208919~~
> pdbpp: fix capturing with recursive debugging

- appveyor.yml
This is meant to help with AppVeyor builds being being too much.
[skip travis]
> AppVeyor: use xdist for py?? envs, drop py27/py37

- src/_pytest/fixtures.py
flatten is an alias in more-itertools anyway
> Replace flatten() with chain.from_iterable

- azure-pipelines.yml
- tox.ini
Just a few environments for now to see how it will behave for a few days
> Set up CI with Azure Pipelines [skip travis] [skip appveyor]

- .travis.yml
The master and features branches are tested daily, so we can test
pluggymaster only therein.
> Travis: add cron_only stage for py38-dev

- src/_pytest/tmpdir.py
The `attrs` package is in the process of deprecating the `convert` kwarg for `Atrribute` in favor of `converter` for consistency (see https://github.com/python-attrs/attrs/issues/307). Ironically this removal is stalled as `attrs` uses pytest, which of course fails when the `convert` kwarg is removed.
Support for both presently exists in `attrs>=15.2.0`.
> Update kwarg for attr.ib to use 'converter' as 'convert' is due to be deprecated.

- changelog/4782.bugfix.rst
- src/_pytest/main.py
- src/_pytest/python.py
- testing/test_collection.py
Fixes https://github.com/pytest-dev/pytest/issues/4782.
> collect: python: fix `AssertionError` with broken symlinks

- doc/en/assert.rst
As per:
https://github.com/pytest-dev/pytest/issues/3974#issuecomment-463462732
Also made the 'match' parameter more prominent
> Remove 'message' parameter docs from assert.rst

- AUTHORS
- changelog/4707.feature.rst
- doc/en/logging.rst
- src/_pytest/logging.py
- testing/logging/test_reporting.py
First of all thanks to @thisch who allowed to make this PR possible.
Without this patch there was only one static way to customize log_file path: --log-file starter option.
This patch allows to customize log_file value also from hooks, which helps to create log-files dynamically even for each testcases.
> LoggingPlugin: Support to customize log_file from hook

- testing/code/test_source.py
- testing/test_skipping.py
> Fix python3.8 / pypy failures

- doc/en/bash-completion.rst
- doc/en/cache.rst
- doc/en/capture.rst
- doc/en/customize.rst
- doc/en/doctest.rst
- doc/en/example/markers.rst
- doc/en/example/pythoncollection.rst
- doc/en/example/simple.rst
- doc/en/fixture.rst
- doc/en/getting-started.rst
- doc/en/license.rst
- doc/en/logging.rst
- doc/en/nose.rst
- doc/en/parametrize.rst
- doc/en/skipping.rst
- doc/en/tmpdir.rst
- doc/en/usage.rst
Default sphinx highlight language here is `python`, which is effective for all code-blocks after `::`.
As a result we sometimes see erroneous highlights like these
Fixes are in two docs only (`doctest.rst` and `pythoncollection.rst`) and if this PR is ok I could probably fix others.
> Fix sphinx code-block types (syntax highlighting) in two docs

- doc/en/goodpractices.rst
- doc/en/links.inc
Recommend use venv instead of virtualenv
From the Python docs:
"Changed in version 3.5: The use of venv is now recommended for creating virtual environments."
-https://docs.python.org/3/library/venv.html
> Doc update - recommend use venv instead of virtualenv

- azure-pipelines.yml
- testing/freeze/create_executable.py
- tox.ini
PyPy needs a little more work I suspect
> Add same environments to Azure, except py37-freeze

- changelog/4810.bugfix.rst
- src/_pytest/logging.py
- testing/logging/test_reporting.py
Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>
> Logging: Make pytest_runtest_logreport() hook available for logging

- testing/test_assertion.py
- testing/test_config.py
pluggy now calls iter_entry_points with different arguments, and tests
which mocked that call need to be updated accordingly.
> Fix test failures after pluggy 1.8 release

- .travis.yml
- azure-pipelines.yml
- changelog/4810.bugfix.rst
- doc/en/bash-completion.rst
- doc/en/cache.rst
- doc/en/capture.rst
- doc/en/customize.rst
- doc/en/doctest.rst
- doc/en/example/markers.rst
- doc/en/example/pythoncollection.rst
- doc/en/example/simple.rst
- doc/en/fixture.rst
- doc/en/getting-started.rst
- doc/en/goodpractices.rst
- doc/en/license.rst
- doc/en/links.inc
- doc/en/logging.rst
- doc/en/nose.rst
- doc/en/parametrize.rst
- doc/en/skipping.rst
- doc/en/tmpdir.rst
- doc/en/usage.rst
- src/_pytest/logging.py
- testing/freeze/create_executable.py
- testing/logging/test_reporting.py
- testing/test_assertion.py
- testing/test_config.py
- tox.ini
To save time, opening a PR merging master into features, including #4816, to save time. 😅 
For consistency we should merge #4816 first.
> Merge master into features (including fix from 4816)

- doc/en/goodpractices.rst
> Fix docs about pytest conventions for test functions

- doc/en/customize.rst
Notice to use [tool:pytest] in setup.cfg, cause [pytest] is no longer supported.
> add notice to use [tool:pytest] in setup.cfg

- .travis.yml
- scripts/upload-coverage.bat
Using many flags are a reason for timeouts on their backend, and we do
not really need those.
> codecov: use only linux/windows/osx flags

- appveyor.yml
pluggymaster is rather stable (not changing often), and currently the same as the released version anyway.
I think it is good enough to test this on Travis, and/or manually with new releases (for Windows).
> AppVeyor: use xdist with pypy, drop pluggymaster

- changelog/4815.trivial.rst
- setup.py
> Require funcsigs>=1.0 on Python 2.7

- tox.ini
Just noticed that `test_usefixtures_marker_on_unittest` is parametrized
for unittest2, but no environment ever installed that library.
> Add unittest2 testing to trial environment

- changelog/4718.feature.rst
- changelog/4718.trivial.rst
- doc/en/plugins.rst
- doc/en/usage.rst
- setup.py
- src/_pytest/config/__init__.py
- src/_pytest/helpconfig.py
- testing/acceptance_test.py
- testing/test_config.py
~~Related to https://github.com/pytest-dev/pluggy/pull/189~~
Fixes #4718
> Change -p so it is possible to early load setuptools plugins

- doc/en/mark.rst
- doc/en/reference.rst
I've been looking into the behaviour of unknown marks today, and discovered that the docs for the `--strict` option are a bit misleading:  even with `--strict`, you don't need to list marks in `pytest.ini` if they come from pytest or are added by a plugin.  IMO this is the right thing to do, as `--strict` is really to catch typos, so I've just fixed the docs.
> Clarify docs on --strict marks

- .travis.yml
- appveyor.yml
Via https://github.com/pytest-dev/pytest/pull/4829#issuecomment-467593937.
> Less coverage reporting

- doc/en/assert.rst
Also changed how the section is presented: instead of "Note" blocks, use proper
sections as those contain enough information to exist on their own.
Fix #1680
> Document how to disable caching rewritten .pyc files to disk

- .coveragerc
- .travis.yml
- azure-pipelines.yml
- scripts/upload-coverage.bat
This appears to improve performance - ~4s with `tox -e py37-coverage --
testing/test_collection.py`.
> coverage: use run.include, remove --ignore-errors, send TOXENV as name to codecov

- setup.py
- testing/test_parseopt.py
Previously it was not run with a) xdist ("-c"), and b) "python -m
pytest" ("…/pytest.py", not executable).
We still need an env to acutally have argcomplete installed.
Where should it go?
Thought about `py27-trial` (what does trial stand for there?), but it appears to only run `test_unittests`?!
> Fix test_argcomplete: use python -m pytest

- .travis.yml
- scripts/upload-coverage.bat
This appears to be one of the reasons for timeouts on their backend.
> ci: codecov: remove flags completely for now

- .travis.yml
- azure-pipelines.yml
- tox.ini
Remove `py27-nobyte` from tox.ini, which was using xdist already.
Therefore this also removes `py27-xdist` from Travis.
`py27-xdist` is still run on Azure.
> tox: add generic nobyte and numpy factors

- src/_pytest/assertion/rewrite.py
Moved/added there in 250160b4, but apparently not intentionally?!
`# noqa` was only added later in two steps.
/cc @benjaminp
> Move import of  _format_explanation in _pytest.assertion.rewrite

- .travis.yml
- tox.ini
This is required for combining.
> tox: split default posargs, use --lsof with single job only

- bench/skip.py
- setup.py
- src/_pytest/assertion/truncate.py
- src/_pytest/deprecated.py
- src/_pytest/hookspec.py
- src/_pytest/logging.py
- src/_pytest/main.py
- src/_pytest/mark/structures.py
- src/_pytest/pathlib.py
- testing/code/test_source.py
- testing/example_scripts/perf_examples/collect_stats/generate_folders.py
- testing/test_resultlog.py
- testing/test_warnings.py
- tox.ini
Ref: https://github.com/pytest-dev/pytest/issues/4233#issuecomment-433032277
> [merge later] Add config for isort

- .coveragerc
Apparently this causes missing coverage with pdb/pexpect tests.
Ref: https://github.com/pytest-dev/pytest/pull/4865#issuecomment-468735403
> .coveragerc: use globs with includes

- changelog/4851.bugfix.rst
- src/_pytest/pytester.py
Pulled out of https://github.com/pytest-dev/pytest/pull/4851, which needs fixes for pytest's own tests.
> pytester: unset PYTEST_ADDOPTS

- src/_pytest/cacheprovider.py
It is only called with empty/new dirs since 0385c273.
> WIP: [merge later] cacheprovider: _ensure_supporting_files: remove unused branches

- changelog/4875.feature.rst
- src/_pytest/terminal.py
- testing/test_config.py
- testing/test_session.py
- testing/test_terminal.py
> Show testpaths option in the header if it has been used for collection

- testing/test_capture.py
It fails reliable for me now without the fix from 9517c3a2a, and had
actually a wrong assertion in the end.
Ref: #2370
> tests: make test_crash_on_closing_tmpfile_py27 more reliable

- .coveragerc
PyPy uses "site-packages" directly.
> .coveragerc: fix include for pypy

- azure-pipelines.yml
> Fix master: ci: Azure: remove pypy3

- .travis.yml
- azure-pipelines.yml
- testing/test_assertrewrite.py
This should bring coverage back that got missing with 9dcd6f2.
Continuation of #4839 / #4846.
> ci: revisit coverage reporting

- changelog/4768.trivial.rst
- src/_pytest/config/__init__.py
> Avoid pkg_resources import at the top-level.

- changelog/4890.trivial.rst
- src/_pytest/pytester.py
This became unused after ab9f6a75 (in 2009).
Not sure if this can be considered an API breakage?!
> pytester: remove unused anypython fixture

- src/_pytest/python.py
This uses modern property definition syntax, declaring both getter
and setter as obj() functions. That definition has always bothered me a little. 🙃 
It was defined this way so the getter and setter wouldn't be a part of the API. The modern property declaration also has the same characteristics.
> Simplify 'obj' property definition in PyobjMixin

- doc/en/reference.rst
> Add missing plugin hooks to docs

- doc/en/requirements.txt
Ref: https://github.com/pytest-dev/pytest/issues/4912
> docs: pin Sphinx to <2.0

- changelog/4829.trivial.rst
- src/_pytest/debugging.py
- src/_pytest/python.py
Just noticed some code that no longer is needed when we removed yield-tests
> Remove dead-code related to yield tests

- changelog/4903.bugfix.rst
- src/_pytest/assertion/rewrite.py
Without this change, the python-apache-libcloud tests failed
in the year 2039 with
```
fp.write(struct.pack("<ll", mtime, size))
E   error: 'l' format requires -2147483648 <= number <= 2147483647
```
Note: 2nd hunk is untested
modeled after https://github.com/python/cpython/pull/9892/files
> Allow tests to pass after 2038

- testing/test_assertrewrite.py
As suggested in https://github.com/pytest-dev/pytest/pull/4903#issuecomment-472759958.
I verified this manually against `features` (which still doesn't contain the original patch) and verified that the test breaks as expected with the original exception.
> Add test for mtime issue in #4903

- src/_pytest/_code/code.py
The expected behavior is that there is no "`__tracebackhide__`" attribute,
so use `getattr` instead of multiple try/except.
> Optimize TracebackEntry.ishidden

- .travis.yml
For pip the usual http caching should be good enough.
This keeps the cache for pre-commit with the linting env for now.
Ref: https://github.com/pytest-dev/pytest/issues/3502
Timings:
1. Ran for 28 min 24 sec, Total time 1 hr 15 min 36 sec
2. Ran for 25 min 3 sec, Total time 1 hr 9 min 18 sec
> ci: Travis: disable cache by default, only for pre-commit

- src/_pytest/debugging.py
This is good practice in general, and I've seen it cause problems (MRO)
with pdb++.
> pdb: post_mortem: use super()

- AUTHORS
- changelog/4911.feature.rst
- src/_pytest/doctest.py
- src/_pytest/outcomes.py
- testing/test_doctest.py
As discussed in https://github.com/pytest-dev/pytest/issues/4911#issuecomment-471992106, it would be nice if doctest can be conditionally skipped.  It seems that just adding three lines is enough (close #4911).  All this patch does is throwing `Skipped` instead of `UnexpectedException` if the original exception is `Skipped`.
I'll add tests and docs if this direction looks OK.
---
- ~Target the `master` branch for bug fixes, documentation updates and trivial changes.~
> Make pytest.skip work in doctest

- changelog/2224.feature.rst
- src/_pytest/python.py
- testing/acceptance_test.py
> Emit a warning when a coroutine test function is encountered

- changelog/4931.feature.rst
- src/_pytest/pytester.py
- testing/test_pytester.py
This can be helpful when passing a set accidentally.
> pytester: LineMatcher: assert lines

- changelog/4936.feature.rst
- src/_pytest/config/__init__.py
- testing/test_pluginmanager.py
This is useful to override e.g. "addopts" config from the command line.
Might be worth adding `set_unblocked` to pluggy.
> Handle `-p plug` after `-p no:plug`

- doc/en/reference.rst
> Minor grammar fixes in pytest.mark.xfail docs

- bench/bench.py
Fixes:
>   File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 60, in main
>     config = _prepareconfig(args, plugins)
>   File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 179, in _prepareconfig
>     raise TypeError(msg.format(args, type(args)))
> TypeError: `args` parameter expected to be a list or tuple of strings, got: 'empty.py' (type: <class 'str'>)
> Fix bench/bench.py without args

- changelog/4941.feature.rst
- src/_pytest/pytester.py
- testing/test_junitxml.py
- testing/test_pdb.py
This avoids loading user configuration, which might interfere with test
results, e.g. a `~/.pdbrc.py` with pdb++.
TODO:
> pytester: testdir: set $HOME to tmpdir

- changelog/4920.feature.rst
- src/_pytest/reports.py
- src/_pytest/runner.py
- src/_pytest/terminal.py
- testing/test_terminal.py
#1367 is about adding unittest subtest support to pytest. After long discussions, it was decided to introduce a new report type and new hook into pytest. After some experiments, I realized we only needed a few internal changes in order to support unittest subtests and a new `subtests` fixture with similar semantics. 
An external plugin is a better approach here IMO because it allows it make more frequent iterations on the details and mature outside of pytest's release cycle. After the plugin matures, we can consider introducing it into the core.
This PR showcases:
* The internal refactorings required to make the plugin work as I intended.
* The `pytest-subtests` plugin implementation. I'm committing the plugin files (`subtests.py` and `test_subtests.py`) just for context about the other …
> Internal refactorings required for *external* pytest-subtests plugin

- changelog/4928.bugfix.rst
- src/_pytest/fixtures.py
- testing/python/fixture.py
Fixes https://github.com/pytest-dev/pytest/issues/4928.
> Fix line offsets with `ScopeMismatch` errors

- changelog/4941.feature.rst
- changelog/4956.feature.rst
- src/_pytest/pytester.py
- testing/test_junitxml.py
Ref: https://github.com/pytest-dev/pytest/issues/4955
> pytester: set HOME only with inline_run/popen

- src/_pytest/cacheprovider.py
- cacheprovider: move call to _ensure_supporting_files
This makes it less likely to have a race here (which is not critical),
but happened previously probably with xdist, causing flaky coverage with
`if not readme_path.is_file():` etc checks in
`_ensure_supporting_files`, which has been removed in the `features`
branch already.
> Revisit mkdir/_ensure_supporting_files in cacheprovider

- .travis.yml
- azure-pipelines.yml
- tox.ini
Ref: https://github.com/pytest-dev/pytest/pull/4848#issuecomment-467909204
> ci: rename "trial" tox factor to "twisted"

- src/_pytest/terminal.py
- testing/test_terminal.py
This is meant for stable coverage with "collecting X item(s)".
I've thought about monkeypatching the duration from inside the first collected test, since the test is rather slow (1s).  Do you think that's a good idea?
> tests: add test_report_collect_after_half_a_second

- src/_pytest/config/__init__.py
- src/_pytest/main.py
- src/_pytest/runner.py
- src/_pytest/terminal.py
- testing/test_config.py
This excludes some plugins for now, which are not trivial (but not impossible) to fix.
Some of them, e.g. "main" should be disallowed to be disabled though maybe?  (e.g. internal/core plugin versus interal default plugin)
> Fix some issues related to "-p no:X" with default_plugins

- src/_pytest/config/__init__.py
- testing/test_pluginmanager.py
This is only required after/with 415899d4 - otherwise argparse ensures
there is an argument already.
> config: fix consider_preparse with missing argument to -p

- doc/en/reference.rst
pytest 4.3.1 throws an error if `pytestmark` is set to a tuple of marks; it appears to insist on a list.
With `pytestmark = [pytest.mark.api, pytest.mark.good]`:
```
============================== test session starts ==============================
platform win32 -- Python 3.6.3, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: C:\Temp\git\sphobjinv, inifile: tox.ini
plugins: timeout-1.3.3
collected 48 items / 41 deselected / 7 selected
tests\test_api_good.py .......                                             [100%]
==================== 7 passed, 41 deselected in 0.15 seconds ====================
```
With `pytestmark = (pytest.mark.api, pytest.mark.good)`:
```
==================================== ERRORS =====================================
____________________ ERROR collecting …
```
> Fix pytestmark syntax in reference.rst

- changelog/4980.feature.rst
- src/_pytest/monkeypatch.py
- src/_pytest/pytester.py
- testing/python/collect.py
- testing/test_assertrewrite.py
- testing/test_monkeypatch.py
- testing/test_pluginmanager.py
Without the patch the test fails as follows:
monkeypatch.syspath_prepend("world")
>       import ns_pkg.world
E       ModuleNotFoundError: No module named 'ns_pkg.world'
> monkeypatch.syspath_prepend: call fixup_namespace_packages

- testing/acceptance_test.py
- testing/deprecated_test.py
- testing/logging/test_reporting.py
- testing/python/collect.py
- testing/python/fixtures.py
- testing/test_assertrewrite.py
- testing/test_cacheprovider.py
- testing/test_capture.py
- testing/test_collection.py
- testing/test_config.py
- testing/test_doctest.py
- testing/test_nose.py
- testing/test_runner.py
- testing/test_skipping.py
- testing/test_tmpdir.py
- testing/test_unittest.py
For strings fnmatch_lines converts it into a Source objects, splitted on
newlines.  This is not necessary here, and it is more consistent to use
lists here in the first place.
> tests: fnmatch_lines: use list

- .travis.yml
- azure-pipelines.yml
- testing/test_assertrewrite.py
This appears to break some tests, which we should fix.
Ref: https://github.com/pytest-dev/pytest/pull/4846#issuecomment-467949008
> ci: PYTEST_ADDOPTS=-vv

- changelog/4988.bugfix.rst
- src/_pytest/logging.py
See https://github.com/pytest-dev/pytest/pull/4981/commits/92ffe42b45973bce478f25bb8acbb5e8e791aafa / #4981 for more information.
TODO:
It means that coverage with src/_pytest/capture.py is likely not flaky anymore, but decreases - it was only accidentally covered.
> logging: close log_file_handler

- src/_pytest/hookspec.py
> Docs: modules implementing pytest_cmdline_parse can be early-loaded

- changelog/4975.bugfix.rst
- doc/en/builtin.rst
- src/_pytest/assertion/util.py
- src/_pytest/cacheprovider.py
- src/_pytest/fixtures.py
- src/_pytest/logging.py
- testing/test_terminal.py
With `-qq` `bool(config.getoption("verbose"))` is True; it needs to be
checked for `> 0`.
Found via `rg 'if .*verbose[^<>=]*$' `.
> Fix usages of "verbose" option

- changelog/4978.bugfix.rst
- src/_pytest/assertion/util.py
- testing/test_assertion.py
It is annoying if `q` does not work.
> Do not swallow outcomes.Exit in assertrepr_compare

- doc/en/usage.rst
> doc: fix note about output capturing with pdb

- src/_pytest/skipping.py
This is for "short summary".
I've started looking into making the format there configurable, to support e.g. "fname:lineno" instead of nodeids.
> skipping: factor out _get_pos, pass only config to _get_report_str

- src/_pytest/pytester.py
- testing/test_config.py
- testing/test_pluginmanager.py
Also done in test_pluginmanager, although no resource warnings are
there at least.
Fixes https://github.com/pytest-dev/pytest/issues/4355.
> tests: ensure cleanup with configs via get_config()

- changelog/4965.trivial.rst
- src/_pytest/config/__init__.py
- src/_pytest/hookspec.py
- src/_pytest/reports.py
- testing/test_reports.py
Add `pytest_report_serialize` and `pytest_report_unserialize` experimental hooks.
Our intention is to keep this code closer to the core, given that it
might break easily due to refactorings.
Having it in the core might also allow to improve the code by moving
some responsibility to the "code" objects (ReprEntry, etc) which
are often found in the reports.
The actual job is done by `_to_json` and `_from_json` of `TestReport` and `CollectReport` (this methods were moved from xdist (ca03269)).
These hooks will be used by `pytest-xdist`, `pytest-subtests`, and the replacement for `resultlog` to serialize and customize reports.
> Serialization hooks

- changelog/4993.feature.rst
- src/_pytest/stepwise.py
Related: https://github.com/pytest-dev/pytest/issues/4992
> stepwise: report status via pytest_report_collectionfinish

- changelog/5008.feature.rst
- src/_pytest/config/findpaths.py
- testing/test_config.py
Helps with migrating existing plugins, e.g. https://github.com/astropy/pytest-openfiles/pull/20.
> setup.cfg: use existing [tool:pytest] (ignoring [pytest])

- changelog/4935.doc.rst
- doc/en/mark.rst
- doc/en/writing_plugins.rst
- src/_pytest/mark/structures.py
- src/_pytest/pytester.py
- testing/python/fixtures.py
- testing/python/integration.py
- testing/python/metafunc.py
- testing/test_capture.py
- testing/test_conftest.py
- testing/test_mark.py
- tox.ini
This pull request is designed to make #4935 much smaller and easier to work on (or review).  The four commits each make a helpful change that is also worth doing independently.
- Typo fixes should be clear.
- `pytester` was using an unregistered marker - adding it to the help is both useful for users and will avoid making usage a warning later.
- We needed to document how a mark could be registered, so I've done that and linked to it from the section on `--strict` and marks.
- Our test suite already uses both `mark.issue` and `mark.issueNNN`; standardising on the former makes selecting issue-relevant tests uniform - and means we won't need to register every number.
I'm targeting `features` so that I can rebase #4935 as soon as this is merged :smile:
> Pre-PR for warnings on unknown markers

- changelog/4826.feature.rst
- doc/en/mark.rst
- src/_pytest/mark/__init__.py
- src/_pytest/mark/structures.py
- src/_pytest/warning_types.py
- tox.ini
Being an updated version of #4933.
One of the most common problems I see, and help debug, is typos in `@pytest.mark.whatever` decorators.  Just recently we've had #4639 and #4814, and I've read three sets of unrelated docs in the last week that explicitly point out the spelling of `mark.parametrize` (not `parameterize`!).
The `--strict` argument helps, but is clearly insufficient by default.  On the other hand, it can't be an error until a major version bump.  This PR emits a warning every time an unknown name is used as an attribute of `pytest.mark`, and therefore closes #4826.
TODO: tests, if people otherwise like the approach.
> Emit warning on unknown marks via decorator

- src/_pytest/config/__init__.py
- src/_pytest/terminal.py
- testing/test_config.py
- testing/test_pluginmanager.py
No changelog, since this is meant to be internal/private?  (rename to `_essential_plugins` maybe?)
> Split out list of essential plugins

- changelog/4942.trivial.rst
- src/_pytest/capture.py
Ref: https://github.com/pytest-dev/pytest/issues/4942
> capture: do not set logging.raiseExceptions = False

- changelog/4854.feature.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
> pdb: add option to skip `pdb.set_trace()`

- changelog/5039.bugfix.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
Fixes https://github.com/pytest-dev/pytest/issues/5039.
> pdb: try to import --pdbcls in pytest_configure only

- src/_pytest/main.py
- testing/test_pdb.py
- testing/test_runner.py
The condition for `initstate <= 2` was always True, after https://github.com/pytest-dev/pytest/pull/4145.
/cc @cacoze
No changelog.
> wrap_session: restore old behavior for initstate=1

- changelog/5035.feature.rst
- doc/en/cache.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
> Support glob argument with ``--cache-show``

- changelog/5026.feature.rst
- src/_pytest/assertion/util.py
- testing/test_assertion.py
> Display number of different items with sequence/dict comparisons

- testing/conftest.py
- testing/test_modimport.py
- tox.ini
This uses pytest_collection_modifyitems for pytest's own tests to order
them, preferring faster ones via quick'n'dirty heuristics only for now.
> Add a conftest to prefer faster tests

- changelog/5059.feature.rst
- changelog/5059.trivial.rst
- src/_pytest/pytester.py
- testing/test_pytester.py
This makes it more flexible to use `testdir.run` / `testdir.popen`.
> pytester: allow passing in stdin to run/popen

- AUTHORS
- changelog/4907.feature.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
> Show XFail reason as part of JUnitXML message field

- changelog/5068.feature.rst
- doc/en/usage.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
> Add support for reportchars=A (`-rA`)

- changelog/5092.bugfix.rst
- src/_pytest/deprecated.py
- src/_pytest/mark/structures.py
- src/_pytest/outcomes.py
- src/_pytest/python_api.py
- testing/test_mark.py
> Produce a warning when unknown arguments are passed to pytest.param()

- changelog/5098.bugfix.rst
- src/_pytest/monkeypatch.py
- src/_pytest/pytester.py
- testing/test_monkeypatch.py
This was done with testdir only, and uses the fixed monkeypatch method
there now.
Fixes https://github.com/pallets/flask/issues/3151.
> monkeypatch.syspath_prepend: invalidate import cache

- testing/test_runner.py
Fixes https://github.com/pytest-dev/pytest/issues/5088.
> test_pytest_exit_returncode: ignore ResourceWarnings

- src/_pytest/terminal.py
- get the list of reports for teardown sections only once
- do not check option in loop
> terminal: revisit summary_failures

- changelog/5108.feature.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
This displays passes (with output, `-rP`) before the short summary, and
before any other output from other plugins also.
TODO:
> terminal summary: display passes after warnings

- src/_pytest/reports.py
- src/_pytest/terminal.py
Ref: https://github.com/pytest-dev/pytest/issues/5047#issuecomment-483109956
Should become more flexible with regard to other properties also, this is just a request for comments.
> terminal/reports: use get_verbose_word method

- doc/en/skipping.rst
One of the `pytest.mark.skipif` blocks in `docs/skipping.rst` does not use the `reason` kwarg:
```python
pytestmark = pytest.mark.skipif(sys.platform == "win32", "tests for linux only")
```
This causes an error during setup of test:
```
Failed: you need to specify reason=STRING when using booleans as conditions.
```
This PR fixes the typo by adding `reason=`.
```diff
-pytestmark = pytest.mark.skipif(sys.platform == "win32", "tests for linux only")
+pytestmark = pytest.mark.skipif(sys.platform == "win32", reason="tests for linux only")
```
Note: I did not make an associated Issue or Changelog entry for this PR because of how trivial it is. If that's needed, please let me know.
> [Docs] Fix typo in skipping.rst

- src/_pytest/mark/__init__.py
There is no need to iterate over all items always, if `-k` is not
specified.
> deselect_by_keyword: skip without expression

- AUTHORS
- changelog/5139.bugfix.rst
- src/_pytest/config/__init__.py
- src/_pytest/nodes.py
- src/_pytest/python.py
- src/_pytest/reports.py
- testing/test_config.py
> Fix dependencies on 'terminal' plugin

- changelog/5144.bugfix.rst
- src/_pytest/main.py
- testing/acceptance_test.py
Previously it would be 0.  Setting it to the expected outcome
(EXIT_USAGEERROR) here already helps `pytest_sessionfinish` hooks.
TODO:
> pytest_sessionfinish: preset exitstatus with UsageErrors

- tox.ini
> Workaround for editable installs with pip 19.1

- changelog/4854.feature.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
This reverts commit e88aa957aed7ee9dc3649e88052f548f5ffd0911, reversing
changes made to 1410d3dc9a61001f71b74ea800b203e92a25d689.
I do not think it warrants an option anymore, and there is a way to
achieve this via `--pdbcls` if needed.
> Revert "Merge pull request #4854 from blueyed/pdb-skip"

- src/_pytest/config/__init__.py
- testing/test_config.py
Thanks to https://github.com/pytest-dev/pytest/pull/5138.
No changelog.
> Terminal plugin is not semi-essential anymore

- changelog/5172.feature.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
> --lf now skips colletion of files without failed tests

- changelog/5182.trivial.rst
- src/_pytest/deprecated.py
Unused now that `MarkInfo` objects no longer exist.
> Removed unused warning message

- doc/en/example/simple.rst
> Add note about pytest_load_initial_conftests working only from plugins

- changelog/5113.bugfix.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
This is required to report deselected items from other hookwrappers.
> terminal: use pytest_collection_finish for reporting

- doc/en/assert.rst
- doc/en/cache.rst
- doc/en/capture.rst
- doc/en/customize.rst
- doc/en/deprecations.rst
- doc/en/example/markers.rst
- doc/en/example/simple.rst
- doc/en/fixture.rst
- doc/en/historical-notes.rst
- doc/en/logging.rst
- doc/en/mark.rst
- doc/en/parametrize.rst
- doc/en/reference.rst
- doc/en/skipping.rst
- doc/en/tmpdir.rst
- doc/en/usage.rst
- doc/en/warnings.rst
- doc/en/writing_plugins.rst
- doc/en/yieldfixture.rst
Remove version references to pytest 2 and 3.
Just like Python 3 no longer has references to Python 2, I think
we should follow the same approach in pytest.
> Remove all version references to obsolete pytest versions

- changelog/5177.feature.rst
- doc/en/warnings.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/cacheprovider.py
- src/_pytest/config/__init__.py
- src/_pytest/junitxml.py
- src/_pytest/mark/structures.py
- src/_pytest/python.py
- src/_pytest/warning_types.py
- src/pytest.py
- testing/test_warnings.py
- tox.ini
> Warning subclasses

- src/_pytest/debugging.py
This is useful/clearer in case of errors / tracebacks - i.e. you see
clearly that it is coming from pytest.
No changelog.
> debugging: rename internal wrapper for pdb.Pdb

- src/_pytest/main.py
- src/_pytest/terminal.py
`Session.startdir` and `TerminalReporter.startdir` appear to be
redundant given `Config.invocation_dir`.
Keep them for backward compatibility reasons, but use
`config.invocation_dir` for them.
No changelog.
> Use config_invocation_dir for startdirs

- changelog/5188.doc.rst
- src/_pytest/skipping.py
As per 528eea7:
> The help for the '--runxfail' flag is incorrect. The default behaviour is to run tests marked as 'xfail' but to ignore the results. This flag alters that behaviour in two ways:
>
> 1. *Only* tests marked 'xfail' are run.
> 2. The results of these tests are reported as if they weren't marked 'xfail'.
>
> This commit updates the help to describe point 1 above; point 2 is implied.
> Improve help for --runxfail flag

- AUTHORS
- changelog/5171.doc.rst
- src/_pytest/hookspec.py
by changing it from str to py.path.local
(#5171)
> doc: fix hooks 'path' parameter doc type

- azure-pipelines.yml
Hi there, PM from Azure Pipelines here. We recently added `pypy2` and `pypy3` as versions for the `UsePythonVersion` task. That means you no longer have to special-case PyPy versions in your build matrix.
> Remove special-case for PyPy CI

- .pre-commit-config.yaml
- CONTRIBUTING.rst
- README.rst
> Black, your uncompromising #Python code formatter, was a project
> created with the community in mind from Day 1. Today we moved it under
> the PSF umbrella. It's now available on GitHub under
> https://github.com/python/black/ . You install and use it just like
> before.
https://twitter.com/llanga/status/1123980466292445190
> Update Black URLs

- changelog/5202.trivial.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
`property` elements cannot be children of `testsuite` according to the schema, so it is incompatible with xunit2
Related to #5202
cc @danilomendesdias
> Emit a warning for record_property when used with xunit2

- doc/en/deprecations.rst
- doc/en/getting-started.rst
- src/_pytest/python_api.py
> Add links to pytest.raises `message` workaround

- src/_pytest/python_api.py
Fix #5208.
Document explicit behavior of `match` and brief note on how to handle matching a string that may contain special re chars.
>  Clarify docs for pytest.raises `match`.

- tox.ini
> Restore usedevelop=True now that pip 19.1.1 restored the old behavior

- testing/test_assertrewrite.py
- [x ] Add yourself to `AUTHORS` in alphabetical order;
> Skip test_source_mtime_long_long on 32bit and lower platforms

- bench/empty.py
- doc/en/example/assertion/failure_demo.py
- doc/en/example/reportingdemo.rst
- src/_pytest/_code/code.py
- src/_pytest/assertion/rewrite.py
- src/_pytest/python_api.py
- src/_pytest/recwarn.py
- testing/code/test_source.py
- testing/test_assertrewrite.py
Apparently this has always worked, and I just assumed that six was providing the shim for a good reason 🤷‍♂ 
```console
$ ./bin/python1.0.1 
Python 1.0.1 (May  6 2019)
Copyright 1991-1994 Stichting Mathematisch Centrum, Amsterdam
>>> x = {}
>>> exec('y = 5', x)
>>> x['y']
5
```
> Use exec directly

- changelog/5220.feature.rst
- src/_pytest/python.py
- testing/python/fixtures.py
Fix #5220
Screenshots:
```
$ pytest --fixtures 
```
```
$ pytest --fixtures -v
```
> Show fixture scopes with ``--fixtures``, except for "function" scope

- changelog/5229.bugfix.rst
- setup.py
Pluggy 0.10.0 introduced a new dependency `importlib-metadata` but that package cannot be imported when installed as an egg and that is causing problems for users relying on `setup.py` to install packages present in `test_require`. This change was quickly reverted in pluggy 0.11.0.
See https://github.com/pytest-dev/pluggy/issues/205
> Require pluggy>=0.11

- AUTHORS
- changelog/5214.feature.rst
- src/_pytest/logging.py
- testing/logging/test_reporting.py
We improve the following things in the logging format:
* Show module name instead of just the filename
* show level of logging as the first thing
* show lineno attached to module:file details
Thanks to @blueyed who suggested this on the github issue.
It's my first contribution and I have added myself to AUTHORS.
I also added to a changelog file.
Fix #5214
> logging: improve default logging format (issue5214)

- doc/en/Makefile
- doc/en/builtin.rst
- doc/en/cache.rst
- doc/en/example/markers.rst
- doc/en/example/parametrize.rst
- doc/en/example/reportingdemo.rst
- doc/en/example/simple.rst
- doc/en/skipping.rst
- doc/en/usage.rst
- doc/en/warnings.rst
Given that our examples use a lot of custom marks, they end up generating a lot of warnings which are only noise in the documentation.
> Ignore PytestUnknownMark warning when generating docs

- changelog/5239.trivial.rst
- setup.py
Make sure we don't update to pluggy 1.0 automatically, as there are planned breaking
changes in the 1.0 release.
Follow up to https://github.com/pytest-dev/pytest/pull/5229#issuecomment-490648714.
> Pin pluggy to <1.0

- changelog/5235.bugfix.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
Fixes https://github.com/pytest-dev/pytest/issues/5235.
> pdb: only use outcomes.exit via do_quit

- .pre-commit-config.yaml
- README.rst
- TIDELIFT.rst
As discussed in the ML, adding a document describing how we plan to split the funds, and how maintainers can start/stop receiving funding.
A quick draft, so suggestions on the docs are very welcome!
@asottile and @blueyed can already start their subscription process. Payments occur at the end of each month.
@RonnyPfannschmidt would you also like to join right now?
---
I created @pytest-dev/tidelift-admins to list the people which can make changes to Tidelift. What do you folks think?
cc @kszu
> Add Tidelift management docs and blurb on README, as discussed in the ML

- changelog/5202.feature.rst
- doc/en/reference.rst
- doc/en/usage.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
This exposes the functionality introduced in fa6acdc as a session-scoped fixture.
Plugins that want to remain compatible with the `xunit2`
standard should use this fixture instead of `record_property`.
Fix #5202
@Zac-HD Hypothesis might want to use this fixture to produce `xunit2`-compatible reports according to #5202.
cc @danilomendesdias
> Introduce record_testsuite_property fixture

- tox.ini
Remove ``--no-use-pep517``, which appears to not be supported anymore,
and PyInstaller works without it by now.
Example build failure: https://travis-ci.org/pytest-dev/pytest/jobs/532103481#L220
> ci: tox: fix py37-freeze

- AUTHORS
- changelog/5250.doc.rst
- doc/en/monkeypatch.rst
This is a documentation update for `monkeypatch` to include an example of `setenv` and `delenv`. Targeting the `master` branch since it is documentation, `tox -e docs` builds locally for me and I've set my RST hard-wrapping at 88 based on guidance from `black` defaults. Will push the commit for the changelog shortly referencing this PR number.
File changes:
- docs/en/monkeypatch.rst: added a new example section related to environment variables.
- AUTHORS: added myself in alphabetical order
> Documentation: add setenv/delenv examples to monkeypatch docs

- changelog/5257.bugfix.rst
- src/_pytest/capture.py
- testing/test_capture.py
> Remove 'b' from sys.stdout.mode

- .github/PULL_REQUEST_TEMPLATE.md
From: https://github.com/pytest-dev/pytest/pull/5273#issuecomment-493076587
> Make it clear that small typos in docs don't require a CHANGELOG entry

- azure-pipelines.yml
- scripts/upload-coverage.bat
Disabling pypy2 and pypy3 for now on Azure so we can get green PRs again (#5279)
> Disable PyPy on Azure

- changelog/5256.bugfix.rst
- src/_pytest/terminal.py
No tests for this because we don't test with Jython currently.
Fix #5256
> Handle lone surrogate unicode character not being representable in Jython

- src/_pytest/_code/code.py
- src/_pytest/python_api.py
Clarify that `pytest.raises(match=...)` uses `re.search` and not `re.match`.
> Fix documentation of pytest.raises(match=...)

- doc/en/contents.rst
- doc/en/tidelift.rst
As commented in:
https://github.com/pytest-dev/pytest/pull/5240#issuecomment-494175451
> Add link to tidelift to the main docs

- AUTHORS
- changelog/5286.bugfix.rst
- src/_pytest/python.py
- testing/python/metafunc.py
> Fix `disable_test_id_escaping_and_forfeit_all_rights_to_community_support` option when using a list of test IDs

- changelog/5278.bugfix.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/config/__init__.py
- src/_pytest/fixtures.py
- src/_pytest/python.py
- testing/test_config.py
Ref: https://github.com/pytest-dev/pytest/issues/5277
> Allow disabling of python plugin

- changelog/5269.feature.rst
- src/_pytest/outcomes.py
- testing/test_skipping.py
This can provide useful information, e.g.
> could not import 'pyrepl.readline': curses library not found
TODO:
> importorskip: display/include ImportError

- testing/test_pdb.py
It was not really testing what it was supposed to test (e.g. the inner
test was not run in the first place).
> tests: fix test_trace_after_runpytest

- changelog/4908.bugfix.rst
- src/_pytest/capture.py
- src/_pytest/debugging.py
- testing/test_pdb.py
This is required for pytest-pdb to be called with `--pdb`.
TODO:
> pdb: trigger pytest_enter_pdb hook with post-mortem

- changelog/5091.feature.rst
- src/_pytest/helpconfig.py
Do not cut long help texts, but wrap them the same way as argparse wraps
the other help items.
TODO:
> Improve output of ini options in --help

- src/_pytest/terminal.py
- testing/test_terminal.py
No changelog, followup to #5068.
Have not really checked if this is sane yet, but "P" means to provide the output of the passed tests, and "p" to include it in the summary - where it should come first also then.
> reportopts: A: put "Pp" in front

- doc/en/py27-py34-deprecation.rst
> Update docs about py27 and py34 support plans

- changelog/2064.bugfix.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
Fixes https://github.com/pytest-dev/pytest/issues/2064.
> pdb: import pdbcls lazily

- testing/conftest.py
- tox.ini
Pulled out of https://github.com/pytest-dev/pytest/pull/5313 - is this something we want to have?
> conftest: add uses_pexpect mark

- testing/conftest.py
> tests: conftest: run slowest tests actually

- changelog/5311.feature.rst
- src/_pytest/logging.py
- testing/logging/test_reporting.py
A method _create_formatter was introduced that is used for both the
log_cli_formatter and the log_formatter.
Consequences of this commit are:
* Captured logs that are output for each failing test are formatted
using the ColoredLevelFromatter.
* caplog.text now contains ansi escape sequences.
* The formatter used for writing to a file still uses the non-colored
logging.Formatter class.
> Use same code for setting up cli/non-cli formatter

- changelog/5333.bugfix.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
> Fix regression with --lf and non-selected failures

- changelog/4559.feature.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
Closes #4559 by adding the junit_log_passing_tests ini flag which can be turned off to disable logging test output and logging for passing tests in the junit XML report.
> Add the junit_log_passing_tests ini flag to skip logging output for passing tests.

- src/_pytest/pytester.py
> pytester: remove unused winpymap

- .travis.yml
- changelog/5333.bugfix.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
- testing/test_pdb.py
- tox.ini
Sorry, again for https://github.com/pytest-dev/pytest/pull/5306.
> Merge master into features

- changelog/4956.feature.rst
- src/_pytest/pytester.py
- testing/test_pytester.py
Followup to https://github.com/pytest-dev/pytest/issues/4956.
> pytester: use temporary HOME with spawn

- .travis.yml
Ref: https://github.com/pytest-dev/pytest/pull/5334
Ref: https://github.com/pytest-dev/pytest/issues/5317
> ci: Travis: add pypy3 to allowed failures temporarily

- changelog/5312.feature.rst
- src/_pytest/logging.py
- testing/logging/test_formatter.py
This PR improves the formatting of captured and live log messages.
```
LOGGER.info("test1\nasdfdf")
LOGGER.warning("test2\nasdfkkk")
LOGGER.warning("single line")
````
Before this PR:
```
INFO     test_multiline:test_multiline.py:11 test1
asdfdf
WARNING  test_multiline:test_multiline.py:12 test2
asdfkkk
WARNING  test_multiline:test_multiline.py:13 single line
```
With this PR:
```
INFO     test_multiline:test_multiline.py:11 test1
asdfdf
WARNING  test_multiline:test_multiline.py:12 test2
asdfkkk
WARNING  test_multiline:test_multiline.py:13 single line
```
> logging: Improve formatting of multiline message

- doc/en/py27-py34-deprecation.rst
> Docs: Fix link anchor

- changelog/5354.bugfix.rst
- src/_pytest/mark/structures.py
- testing/test_mark.py
> Fix `pytest.mark.parametrize` when the argvalue is an iterator

- changelog/5354.bugfix.rst
- src/_pytest/mark/structures.py
- testing/test_mark.py
> [4.6] Fix `pytest.mark.parametrize` when the argvalue is an iterator

- changelog/5358.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
> Fix all() unroll for non-generators/non-list comprehensions

- .travis.yml
This reverts commit 5ac498ea9634729d3281d67a8cd27d20a34cf684.
The idea is that maybe https://github.com/pytest-dev/pytest/pull/5360
fixes the failures here also.
> Revert "ci: Travis: add pypy3 to allowed failures temporarily"

- HOWTORELEASE.rst
I'm going to run these and make sure they make sense
> Update release instructions for 4.6-maintenance

- changelog/5335.bugfix.rst
- src/_pytest/logging.py
- testing/logging/test_formatter.py
The reason why I've added support for truncated fixed with alignment of the levelname is saving horizontal space by using, e.g., '%(levelname).1s'.
> logging: Extend LEVELNAME_FMT_REGEX

- changelog/5358.bugfix.rst
- changelog/5370.bugfix.rst
- changelog/5371.bugfix.rst
- changelog/5372.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
Resolves #5370 
Resolves #5371
Resolves #5372
> Revert unrolling of `all()`

- .travis.yml
This reverts commit a6dc283133c6ee3a3fdedacf5d363d72b58ffa88.
Did not notice that master started to fail with it again - which is likely the reason for codecov getting confused also even more.
I'd remove it completely until proven to be fixed, but allow-failure is better already.
> Revert "Revert "ci: Travis: add pypy3 to allowed failures temporarily""

- changelog/5370.bugfix.rst
- changelog/5371.bugfix.rst
- changelog/5372.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
Revert unrolling of `all()`
I had to manually resolve conflicts and apply the patch to `visit_Call_legacy` as well
> [4.6] Merge pull request #5373 from asottile/revert_all_handling

- doc/en/reference.rst
This PR fixes https://github.com/pytest-dev/pytest/issues/4560
> Add a new Exceptions section in documentation and document UsageError

- CHANGELOG.rst
- doc/en/announce/index.rst
- doc/en/announce/release-4.6.2.rst
- doc/en/example/simple.rst
Preparing release version 4.6.2
> [release notes] Merge pull request #5379 from asottile/release-4.6.2

- changelog/5315.doc.rst
- doc/en/monkeypatch.rst
Following up on #5250 I've added another expansion to the `monkeypatch` documentation:
1. Included the reference output from `pytest --fixtures` for `monkeypatch` to list methods.
2. All Python code-blocks are in `code-block` RST sections across the file.
3. Added conceptual scenarios for the major functions to the intro.
4. Modified the "simple example" to include broader explanatory comments.
5. Added "Monkeypatching returned objects: building mock classes" section.
6. Added "Monkeypatching dictionaries" section.
7. Applied changes from the `blacken-docs` `pre-commit` hook.
> Documentation: expansion of Monkeypatch to include mocked classes and dictionaries

- .travis.yml
Remove --recreate from .travis.yml
> [4.6] Remove --recreate from .travis.yml (#5384)

- changelog/5389.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_config.py
For some Python packages the `files` attribute of a `importlib_metadata.PathDistribution` is `None` (see e.g ros2/ros2_documentation#271). In that case the code modified in #5358 and released in 4.6 fails with the stacktrace mentioned in the referenced ticket.
This patch certainly fixes the exception (trying to iterate `None`). I am not certain if it is the right way to address the issue though.
> fix logic if importlib_metadata.PathDistribution.files is None [breaks pytest 4.6.0|1|2]

- changelog/5390.bugfix.rst
- src/_pytest/unittest.py
- testing/test_unittest.py
> item.obj is again a bound method on TestCase function items

- changelog/5390.bugfix.rst
- src/_pytest/unittest.py
- testing/test_unittest.py
item.obj is again a bound method on TestCase function items
> [4.6] Merge pull request #5393 from nicoddemus/unittest-self-5390

- testing/conftest.py
Without this, `testing/test_pdb.py` (already without pexpect) will cause
missing test coverage afterwards (for the same process).
https://bugs.python.org/issue37011
> tests: restore tracing function

- .travis.yml
This reverts commit 6d393c5dc8bfc9e437f85dae83914004409b1bc2.
It should not be necessary, because we have it via other jobs already.
> Revert "Enable coverage for 'py37' environment"

- testing/conftest.py
Without this, `testing/test_pdb.py` (already without pexpect) will cause
missing test coverage afterwards (for the same process).
> [4.6] tests: restore tracing function

- changelog/5383.bugfix.rst
- src/_pytest/logging.py
- testing/logging/test_reporting.py
> Fix verbosity bug in --collect-only

- changelog/5402.removal.rst
- src/_pytest/warnings.py
- testing/python/fixtures.py
- testing/test_warnings.py
> Turn PytestDeprecationWarning into error

- src/_pytest/assertion/util.py
- src/_pytest/outcomes.py
- testing/io/test_saferepr.py
- testing/python/fixtures.py
- testing/python/raises.py
- testing/test_pytester.py
- testing/test_tmpdir.py
mypy is very far from passing, but it did point out a few small cleanups that were doable
> small mypy fixes

- AUTHORS
- changelog/5416.doc.rst
- doc/en/example/simple.rst
The example implementation of a `--runslow` option results in
a `PytestUnknownMarkWarning`. Include registering the custom
mark in the example, based on the documentation in markers.rst.
> Add `slow` marker in run/skip option example.

- changelog/5412.removal.rst
- src/_pytest/_code/code.py
- testing/code/test_excinfo.py
> Remove ExceptionInfo.__str__, falling back to __repr__

- .travis.yml
Ref: https://github.com/pytest-dev/pytest/issues/5317#issuecomment-499019928
> ci: Travis: remove pypy3 job for now

- src/_pytest/deprecated.py
As commented in https://github.com/pytest-dev/pytest/issues/3974#issuecomment-499870914
> Link deprecation docs pytest.raises 'message' warning

- src/_pytest/deprecated.py
> [4.6] Link deprecation docs pytest.raises 'message' warning

- .travis.yml
- azure-pipelines.yml
- tox.ini
- tox: use twisted as dep only
- Azure: move twisted/numpy to main py37 job
- Travis: move twisted to main py37 build
> ci: optimize twisted/numpy related jobs

- .travis.yml
I pushed a workaround into importlib-metadata which avoids the call causing the ResourceWarning
https://gitlab.com/python-devs/importlib_metadata/merge_requests/75
Resolves #5317
> re-enable pypy3

- changelog/4488.deprecation.rst
- doc/en/deprecations.rst
- src/_pytest/deprecated.py
- testing/deprecated_test.py
As we did not provide an alternative yet, it is better to postpone
the actual removal until we have provided a suitable and stable
alternative.
Related to #4488
> Postpone removal of --result-log to pytest 6.0

- doc/en/nose.rst
> Add missing 'e' to test_mod(e).

- src/_pytest/config/__init__.py
The function has been deprecated for ages and the `PLUGIN_MANAGER_ADDHOOKS` constant doesn't even exist since 3.0.
Because the function is clearly broken, this change doesn't even require a `CHANGELOG`.
> Remove broken/unused PytestPluginManager.addhooks

- changelog/5404.bugfix.rst
- src/_pytest/doctest.py
- testing/test_doctest.py
Closes #5080.
@RonnyPfannschmidt - I'm unconvinced that we should do anything more than close the issue, but if you want a fix I think this is it.
> Emit warning for broken object

- changelog/5452.feature.rst
- src/_pytest/warning_types.py
- testing/test_warning_types.py
When we configure warnings as errors, users see error messages like this:
```
def test():
>       warnings.warn(pytest.PytestWarning("some warning"))
E       _pytest.warning_types.PytestWarning: some warning
```
This is a problem because suggests the user should use `_pytest.warning_types.PytestWarning` to configure
their warning filters, which is not nice.
This commit changes the message to:
```
def test():
>       warnings.warn(pytest.PytestWarning("some warning"))
E       pytest.PytestWarning: some warning
```
I noticed we already do this for some exceptions, marking them as from the `builtins` module to make their tracebacks shorter.
> Make pytest warnings show as from 'pytest' module instead of '_pytest.warning_types'

- changelog/5444.bugfix.rst
- src/_pytest/stepwise.py
- testing/test_stepwise.py
> Fix stepwise crash when first collected module fails

- changelog/5404.bugfix.rst
- src/_pytest/doctest.py
- testing/test_doctest.py
> [4.6] Backport unwrapper PR

- changelog/1403.bugfix.rst
- changelog/2761.bugfix.rst
- changelog/5078.bugfix.rst
- changelog/5432.bugfix.rst
- changelog/5433.bugfix.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/main.py
- src/_pytest/pathlib.py
- src/_pytest/pytester.py
- testing/acceptance_test.py
- testing/test_assertion.py
- testing/test_assertrewrite.py
- testing/test_pathlib.py
Resolves #1403
Resolves #2761
Resolves #5078
Resolves #5432
Resolves #5433
> Switch from deprecated imp to importlib

- src/_pytest/terminal.py
`-ra` / `-rA` will include "w" also.  This does not explicitly mention
it (allowing for change the behavior), but makes it a) clearer that "w"
is a recognized reportchar, and b) less confusing that `-ra
--disable-warnings` still displays them.
Code ref: https://github.com/blueyed/pytest/blob/01a094cc4316a2840254a66f829367f3d67fd442/src/_pytest/terminal.py#L151-L166
> minor: clarify help with reportchars

- changelog/5440.feature.rst
- doc/en/reference.rst
- doc/en/usage.rst
- src/_pytest/config/__init__.py
- src/_pytest/deprecated.py
- src/_pytest/faulthandler.py
- testing/deprecated_test.py
- testing/test_faulthandler.py
* Add pytest-faulthandler files unchanged
* Adapt imports and tests
* Add code to skip registration of the external `pytest_faulthandler`
to avoid conflicts
Fix #5440
> Integrate pytest-faulthandler into the core

- AUTHORS
- changelog/5482.bugfix.rst
- src/_pytest/mark/structures.py
- testing/python/metafunc.py
> Pickup addition positional args passed to _parse_parametrize_args

- CONTRIBUTING.rst
rst file format seems to be enforced by pre-commit hooks but not specified in the contribution guide.
> Clarify changelog entries should be rst files

- changelog/1149.removal.rst
- extra/get_issues.py
- scripts/release.py
- src/_pytest/config/argparsing.py
- testing/acceptance_test.py
- testing/example_scripts/perf_examples/collect_stats/generate_folders.py
- testing/test_capture.py
- testing/test_parseopt.py
- testing/test_pastebin.py
This was previously allowed where the ArgumentParser thought it was unambiguous, because this could be incorrect due to delayed parsing of options for plugins.
Fixes #1149, fixes #3413, and fixes #4009 - it's been a known problem for quite a while, but this fix is only available on Python 3.5+... which means we can finally do it!  Replaces #5467, in that it *also* defines `MyOptionParser._parse_optional`, in order to work around [an upstream bug that disables combining short options, such as `-vv`](https://bugs.python.org/issue26967).  
**We should avoid merging this until python/cpython#14316 is merged** and we know that we don't need to do our conditional backport on 3.8.
> Disallow abbreviated command-line options

- changelog/1671.bugfix.rst
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
All credits go to @asottile! Just wanted to make a small contribution before calling it a day.
Fix #1671
> Include pytest version in the cached pyc tags

- src/_pytest/assertion/rewrite.py
Resolves #5488
I couldn't find a good way to reproduce this in a test, so here's my "minimal reproduction":
```console
$ tree
.
├── setup.py
└── x
├── basic_c_module.c
├── __init__.py
└── y.py
1 directory, 4 files
$ find -type f | xargs tail -n 99
==> ./setup.py <==
from setuptools import setup, Extension
setup(
name='foo',
packages=['x'],
ext_modules=[Extension('x.basic_c_module', ['x/basic_c_module.c'])],
entry_points={'pytest11': ['x=x.y']},
)
==> ./x/basic_c_module.c <==
#include <Python.h>
static PyObject* _hello_world(PyObject* self) {
return PyUnicode_FromString("hello world");
}
static struct PyMethodDef methods[] = {
{"hello_world", (PyCFunction)_hello_world, METH_NOARGS},
{NULL, NULL}
};
#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef module = {
PyModuleDef_HEAD_INIT, …
```
> Do not attempt to rewrite non-source files

- changelog/5260.bugfix.rst
- src/_pytest/assertion/util.py
- testing/test_assertion.py
> Improve comparison of byte strings (supersedes #5267)

- changelog/5497.trivial.rst
- src/_pytest/assertion/rewrite.py
> Fix typo replace `circuting` with `circuiting`.

- changelog/466.deprecation.rst
- doc/en/deprecations.rst
- src/_pytest/compat.py
- src/_pytest/deprecated.py
- src/_pytest/fixtures.py
- testing/python/fixtures.py
- testing/python/metafunc.py
But leave the helper until 5.1, so that the error message can be helpful and suggest using the modern form.  Closes #4676.
This is a direct replacement for #5476, targeting master instead of features.
> Deprecate funcargnames alias for fixturenames

- changelog/5505.bugfix.rst
- src/_pytest/nodes.py
- testing/test_config.py
> Fix crash when discovery fails while using `-p no:terminal`

- changelog/5505.bugfix.rst
- src/_pytest/nodes.py
- testing/test_config.py
> [4.6] Fix crash when discovery fails while using `-p no:terminal`

- changelog/3457.trivial.rst
- setup.py
- src/_pytest/assertion/rewrite.py
- testing/test_assertrewrite.py
Resolves #5510
This is a little different approach than using `astor` in that it reproduces the original assertion source expression directly
I could make this even simpler by including the whole line of the original assertion (then the indentation would be preserved as well???) what do you think of that?
> Remove astor and reproduce the original assertion expression

- src/_pytest/doctest.py
head-fork: AmirElkess/pytest
compare: refactor
base-fork: pytest-dev/pytest
base: master
> Refactoring doctests

- CHANGELOG.rst
- changelog/5404.bugfix.rst
- changelog/5444.bugfix.rst
- changelog/5482.bugfix.rst
- changelog/5505.bugfix.rst
- doc/en/announce/index.rst
- doc/en/announce/release-4.6.4.rst
figured I might as well release 4.6.x while I'm at it :D
> Preparing release version 4.6.4

- changelog/5517.doc.rst
- doc/en/writing_plugins.rst
I wrote my first plugin hooks today and since I found the documentation somewhat lacking, I extended it somewhat, so other people will have an easier time. :)
Would be great if someone with a better understanding of the subject could double check if I didn't make any mistakes.
> doc(plugin_hooks): Improve documentation for writing plugin hooks.

- .travis.yml
- changelog/5523.bugfix.rst
- src/_pytest/config/argparsing.py
Hopefully by Python 3.9 this will be fixed upstream, if not we will
need to bump the version again.
Fix #5523
> Apply workaround for multiple short options for Python <= 3.8

- doc/en/example/nonpython.rst
- doc/en/example/nonpython/conftest.py
- doc/en/example/nonpython/test_simple.yaml
This is a small doc fix for 
https://github.com/pytest-dev/pytest/issues/5533
Resolves #5533
> Substituted 'yml' to '.yaml' in relevant files

- OPENCOLLECTIVE.rst
- TIDELIFT.rst
- doc/en/_templates/globaltoc.html
- doc/en/contents.rst
- doc/en/sponsor.rst
- doc/en/tidelift.rst
Give an overview of how we as an organization will use the donated money,
as well as show this information more prominently in the docs.
> Add docs about Tidelift and OpenCollective

- changelog/5478.bugfix.rst
- src/_pytest/_code/code.py
- testing/python/raises.py
> Fix pytest.raises handling of unicode exceptions in Python 2

- changelog/5547.bugfix.rst
- src/_pytest/stepwise.py
- testing/test_stepwise.py
> Handle xfail(strict=True) properly in --step-wise mode

- changelog/5523.bugfix.rst
- changelog/5537.bugfix.rst
- setup.py
- src/_pytest/compat.py
- src/_pytest/config/__init__.py
- src/_pytest/config/argparsing.py
- testing/acceptance_test.py
- testing/test_assertion.py
- testing/test_config.py
- testing/test_entry_points.py
Fixes https://github.com/pytest-dev/pytest/issues/5537
I'm still running tox locally, there are some 3.8 failures, not yet sure if related.
> Replace importlib_metadata with importlib.metadata on Python 3.8+

- CHANGELOG.rst
- changelog/5479.bugfix.rst
- changelog/5517.doc.rst
- changelog/5523.bugfix.rst
- changelog/5547.bugfix.rst
- doc/en/announce/index.rst
- doc/en/announce/release-5.0.1.rst
- doc/en/assert.rst
- doc/en/cache.rst
- doc/en/capture.rst
- doc/en/doctest.rst
- doc/en/example/markers.rst
- doc/en/example/nonpython.rst
- doc/en/example/parametrize.rst
- doc/en/example/pythoncollection.rst
- doc/en/example/reportingdemo.rst
- doc/en/example/simple.rst
- doc/en/fixture.rst
- doc/en/getting-started.rst
- doc/en/index.rst
- doc/en/parametrize.rst
- doc/en/skipping.rst
- doc/en/tmpdir.rst
- doc/en/unittest.rst
- doc/en/usage.rst
- doc/en/warnings.rst
- doc/en/writing_plugins.rst
Mostly to get #5523 out the door. 👍
> Preparing release version 5.0.1

- testing/deprecated_test.py
- tox.ini
This might cause problems during collection with pytest-xdist; we
didn't see any so far mostly by luck I think.
Shame on me for letting that slip in. 😓
> Sort parametrize params to test_external_plugins_integrated

- doc/en/_themes/flask/slim_searchbox.html
- doc/en/_themes/flask/static/flasky.css_t
- doc/en/conf.py
This PR improves the layout of the sidebar:
- Move the search field to the top (should be easily accessible without the need to scroll).
- Reduce the heading font size so that "Table Of Contents" is not wrapped.
Here's a screenshot of the change (left: before, right: after):
> Improve docs sidebar layout

- .gitignore
- .pre-commit-config.yaml
- bench/bench.py
- setup.cfg
- src/_pytest/_argcomplete.py
- src/_pytest/_code/code.py
- src/_pytest/_code/source.py
- src/_pytest/assertion/rewrite.py
- src/_pytest/capture.py
- src/_pytest/debugging.py
- src/_pytest/fixtures.py
- src/_pytest/mark/__init__.py
- src/_pytest/mark/structures.py
- src/_pytest/nodes.py
- src/_pytest/outcomes.py
- src/_pytest/python_api.py
- src/_pytest/reports.py
- src/_pytest/tmpdir.py
- testing/code/test_excinfo.py
- testing/python/raises.py
- testing/test_compat.py
- testing/test_pdb.py
(This PR is currently an RFC, I will discuss it in issue #3342).
Add a very lax mypy configuration, add it to tox -e linting, and
fix/ignore the few errors that come up. The idea is to get it running
before diving in too much.
This enables:
- Progressively adding type annotations and enabling more strict
options, which will improve the codebase (IMO).
- Annotating the public API in-line, and eventually exposing it to
library users who use type checkers (with a py.typed file).
Though, none of this is done yet.
Refs #3342.
> Add rudimentary mypy type checking

- changelog/5578.bugfix.rst
- src/_pytest/outcomes.py
- testing/test_runner.py
- testing/test_skipping.py
> Improve type-checking in OutcomeException

- changelog/5564.feature.rst
- src/_pytest/config/__init__.py
- testing/test_config.py
These attributes can be used to access the unchanged arguments passed
to `pytest.main()`.
The intention is to use these attributes to initialize workers in
the same manner as the master node is initialized in pytest-xdist (https://github.com/pytest-dev/pytest-xdist/pull/448).
> Introduce Config.invocation_params

- .gitignore
- .pre-commit-config.yaml
- bench/bench.py
- setup.cfg
- src/_pytest/_argcomplete.py
- src/_pytest/_code/code.py
- src/_pytest/_code/source.py
- src/_pytest/assertion/rewrite.py
- src/_pytest/capture.py
- src/_pytest/debugging.py
- src/_pytest/fixtures.py
- src/_pytest/mark/__init__.py
- src/_pytest/mark/structures.py
- src/_pytest/nodes.py
- src/_pytest/outcomes.py
- src/_pytest/python_api.py
- src/_pytest/reports.py
- src/_pytest/tmpdir.py
- testing/code/test_excinfo.py
- testing/python/raises.py
- testing/test_compat.py
- testing/test_pdb.py
> [cherry-pick to master] Add rudimentary mypy type checking

- AUTHORS
- changelog/5576.feature.rst
- doc/en/doctest.rst
- src/_pytest/doctest.py
- testing/test_doctest.py
When enabled, floating-point numbers only need to match as far as the
precision you have written in the expected doctest output. This avoids
false positives caused by limited floating-point precision, like this:
Expected:
0.233
Got:
0.23300000000000001
This is inspired by Sébastien Boisgérault's [numtest] but the
implementation is a bit different:
* This implementation edits the literals that are in the "got"
string (the actual output from the expression being tested), and then
proceeds to compare the strings literally. This is similar to pytest's
existing ALLOW_UNICODE and ALLOW_BYTES implementation.
* This implementation only compares floats against floats, not ints
against floats. That is, the following doctest will fail with pytest
whereas it would pass with numtest:
>>> math.py  # …
> doctest: Add +NUMBER option to ignore irrelevant floating-point differences

- changelog/5524.bugfix.rst
- src/_pytest/cacheprovider.py
- src/_pytest/pathlib.py
- testing/test_tmpdir.py
> Fix rmtree to remove directories with read-only files

- src/_pytest/pathlib.py
> Fix typos in a docstring

- changelog/5565.removal.rst
- src/_pytest/nose.py
- src/_pytest/runner.py
- src/_pytest/unittest.py
- testing/test_unittest.py
- tox.ini
[unittest2](https://pypi.org/project/unittest2) is a backport for Python <=3.2, so we no longer need
to support it (last release was in 2015). 
I suspect it has not been used at all by users after 5.0 has been released.
> Drop unittest2 support

- changelog/5477.bugfix.rst
- src/_pytest/junitxml.py
- testing/test_junitxml.py
One thing that is not clear to me yet is if the attributes defined in the schema (`name`, `title`, etc) are optional:
```xsd
<xs:element name="testsuites">
<xs:complexType>
<xs:sequence>
<xs:element ref="testsuite" minOccurs="0" maxOccurs="unbounded" />
</xs:sequence>
<xs:attribute name="name" type="xs:string" />
<xs:attribute name="time" type="SUREFIRE_TIME"/>
<xs:attribute name="tests" type="xs:string" />
<xs:attribute name="failures" type="xs:string" />
<xs:attribute name="errors" type="xs:string" />
</xs:complexType>
```
Judging from the other attributes elsewhere which are defined in the schema but are not written (for example, `testsuite`'s `timestamp` attribute), it seems those are optional.
Fix #5477
@nazariyv @jhunkeler @nazariydolfin 
Would appreciate if you folks could help …
> Include <testsuites> root tag in generated XML

- doc/en/example/fixtures/test_fixtures_order.py
- doc/en/fixture.rst
A case with a fixture use both as an autouse and explititly
was raised. This case sounds too narrow to add to documentation
(and could be misleading for people learning pytest with explicitely
using an autouse fixture). At the same time there was no documentation
on the autouse vs regular fixture order, therefore this commit adds
such an information. Code sample grew and it was extracted to the file.
> Add autouse fixture order information (#3404).

- AUTHORS
- doc/en/_themes/flask/static/flasky.css_t
This PR improves some aspects of the documentation layout.
- Links are now colored #606413, a muted version of the green logo color #C9D22A.
- Hovered links are now colored with the blue logo color #009de0.
before:
after:
- Links in the sidebar do not have dotted underlines. This gives a more clean look. The color itself should be indication enough that this is not normal text. Highlighting and underline on hover is kept.
before: ![image](https://user-images.githubusercontent.com/2836374/61185939-56361680-a65f-11e9-99ca-e63d660b6fa7.png) after: ![image](https://user-images.githubusercontent.com/2836374/61186505-951b9a80-a666-11e9-9544-55de2e49b713.png)
- The same hold for the links in the Reference TOC:
before: ![image](https://user-images.githubusercontent.com/2836374/61185959-9bf2df00-a6 …
> Improve CSS layout

- CONTRIBUTING.rst
- doc/en/_themes/flask/static/flasky.css_t
Followup to #5602.
1. Fixes a regresssion from #5602. The contents list items unintendedly got a margin in between. This        is removed again (before/after):
2. Removed the header backlinks in the section "Contributing". The main motivation is to not style the headings like links. While this could also be overridden with additional CSS, I decided to just remove the backlinks. Since most of the other pages do not have TOCs, headings in the pytest docs usually do not have backlinks. Additionally, IMHO the semantics of a heading backlink is not quite intuitive (clicking on a heading brings you to the TOC which is only structurally but not sematically related to the section); and I don't think the actual action "Go to TOC" is really needed here.
before:
after:
> More CSS fine-tuning

- testing/python/integration.py
No longer make sense given that `unittest.mock` is part of the stdlib for all Python versions we support now.
> Remove obsolete "importorskip('unittest.mock')" calls

- .pre-commit-config.yaml
> Remove language_version specification in black hooks

- doc/en/fixture.rst
> de-emphasize request.addfinalizer Fixes #5587

- changelog/5603.trivial.rst
- src/_pytest/_io/saferepr.py
- testing/io/test_saferepr.py
Remove some dead code and make it easier to type-check.
The PR is split to commits.
> Simplify SafeRepr a bit

- src/_pytest/_code/code.py
- src/_pytest/outcomes.py
- src/_pytest/python_api.py
- src/_pytest/recwarn.py
- testing/code/test_excinfo.py
- testing/python/raises.py
- testing/test_recwarn.py
- tox.ini
To kickstart the plan laid out in https://github.com/pytest-dev/pytest/issues/3342#issuecomment-509253652, this adds type annotations to some of the more well-known pytest APIs.
The PR is split into commits for easier reviewing.
For `pytest.raises`, there are two approaches, one is more precise but a bit more complex, requiring generics. I first implement the simple approach, then switch to the more complex approach in the last commit, so that it can be more easily dropped if wanted.
I guess at this point the pytest devs will want to chime in on whether they want to go down the static typing path :)
> Type-annotate pytest.{exit,skip,fail,xfail,importorskip,warns,raises}

- CHANGELOG.rst
- doc/en/_templates/globaltoc.html
- doc/en/_themes/flask/static/flasky.css_t
- doc/en/reference.rst
- src/_pytest/mark/structures.py
- src/_pytest/python_api.py
- Changed layout of parameters sections
- Don't indent by the width of "Parameters". Parameter documentation is less cramped.
- Haning indent for parameter docs: Better overview where the next parameter starts.
- Draw a vertical line along all parameters: The parameters section is easy to distinguish from other parts of the docstring
before/after:
- Draw a vertical line along class docstrings. Class docstrings can be quite long. The line makes it obvious that the attribute/method definitions therein are not toplevel but belong to a class.
before/after:
- Some spacing adjustments to give the text more space to breathe.
Fixed two indentation issues in docstrings, which resulted in incorrect formatting of the rendered API reference.
- "Changelog history" -> "Changelog":
A changelog is by …
> CSS changes to the API reference

- .pre-commit-config.yaml
- changelog/5615.removal.rst
- src/_pytest/_code/code.py
- src/_pytest/outcomes.py
- src/_pytest/python.py
- src/_pytest/runner.py
Please see each commit for an explanation.
> Improve mypy setup + a few minor type fixes and removals

- tox.ini
- path.local/path.readlines is not used anymore
- enhance doc for "invalid escape sequence" filter
> tox.ini: clean up filterwarnings

- testing/test_pytester.py
> [4.6] #5636 Fix ordering of sys modules snapshot

- changelog/5606.bugfix.rst
- src/_pytest/compat.py
- testing/python/integration.py
>  use identity checks for the mock sentinels

- changelog/5634.bugfix.rst
- src/_pytest/unittest.py
- testing/test_unittest.py
This is required for pytest to stop when using "quit" in pdb, and should
get honored/handled in general.
> unittest: handle outcomes.Exit

- src/_pytest/config/__init__.py
- src/_pytest/helpconfig.py
- testing/test_config.py
Added in https://github.com/pytest-dev/pytest/pull/5564.
> Replace internal config._origargs with invocation_params.args

- changelog/5650.bugfix.rst
- src/_pytest/config/findpaths.py
- testing/test_config.py
Before this change, a config file with a syntax error (like a missing section header) produces a rather intimidating stacktrace:
```
File ".venv/bin/pytest", line 11, in <module>
load_entry_point('pytest', 'console_scripts', 'pytest')()
File "/home/florian/proj/pytest/src/_pytest/config/__init__.py", line 55, in main
config = _prepareconfig(args, plugins)
File "/home/florian/proj/pytest/src/_pytest/config/__init__.py", line 200, in _prepareconfig
pluginmanager=pluginmanager, args=args
File "/home/florian/tmp/ini/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/home/florian/tmp/ini/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
return …
```
> Improve output when parsing an ini configuration fails

- doc/en/example/parametrize.rst
- doc/en/fixture.rst
The previous example was failing with:
```
================================== ERRORS ==================================
_____________________ ERROR collecting test_yield3.py ______________________
ImportError while importing test module '$REGENDOC_TMPDIR/test_yield3.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_yield3.py:7: in <module>
from .utils import connect
E   ImportError: attempted relative import with no known parent package
!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!
========================= 1 error in 0.12 seconds ==========================
```
> Fix fixture example and regendocs

- CHANGELOG.rst
> Make ExceptionInfo.repr change more prominent

- changelog/5664.trivial.rst
- testing/test_stepwise.py
Previously, the test failed when the directory was not present,
which could have been caused for example by invoking the tests
with PYTHONDONTWRITEBYTECODE=1.
Fixes https://github.com/pytest-dev/pytest/issues/5664
> In test_xfail_handling, only remove __pycache__ if it exists

- AUTHORS
- src/_pytest/terminal.py
- testing/test_terminal.py
Fix the confusing different names of `fulltrace` showed in `pytest --help` (#5647)
Since this is a small fix, and I don't think this needs to create a changelog, please let me know if needed.
> Fix the confusing different names of `fulltrace`

- doc/en/mark.rst
- src/_pytest/config/argparsing.py
- testing/code/test_excinfo.py
- testing/test_junitxml.py
- testing/test_mark.py
- testing/test_nose.py
Fixed typos in comments:
shouldnt -> shouldn't
wasnt -> wasn't
didnt -> didn't
programatically -> programmatically
surpressing -> suppressing
Found with: https://github.com/ss18/grep-typos
> Fix some typos

- .travis.yml
- changelog/5650.bugfix.rst
- src/_pytest/config/findpaths.py
- testing/test_config.py
Backport of https://github.com/pytest-dev/pytest/pull/5650
> [4.6] Improve output when parsing an ini configuration fails (#5650)

- .travis.yml
setuptools-scm needs all tags to guess the version correctly
(cherry-pick from https://github.com/pytest-dev/pytest/pull/5652)
> Disable shallow cloning because of setuptools-scm

- changelog/5516.trivial.rst
- src/_pytest/nodes.py
https://github.com/pytest-dev/pytest/issues/5516
On a large number of tests, collection time can take over 2 minutes for 20k of tests. 60% of the time is spent on splitting nodes, so caching nodesplit results will improve performance considerably.
> Cache splitnode results to improve tests collection time

- src/_pytest/pathlib.py
- testing/test_tmpdir.py
Ref: https://github.com/pytest-dev/pytest/issues/5626
> Handle only known functions in rm_rf

- doc/en/usage.rst
Relates to:
1. [pytest#5125](https://github.com/pytest-dev/pytest/issues/5125)
2. [pytest#5420](https://github.com/pytest-dev/pytest/pull/5420)
Better visibility on usage of exitcodes.
> Added info to access exitcodes directly

- changelog/5684.trivial.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/pathlib.py
- testing/test_assertrewrite.py
> Use OSError subclasses instead of handling errno

- src/_pytest/pathlib.py
- testing/test_tmpdir.py
Backport of #5627
Conflicts:
- 	src/_pytest/pathlib.py
Also had to adapt:
- PermissionError into OSError with appropriate errno
- Change keyword-only argument to `**kwargs`
- Remove type annotations
> [4.6] Handle only known functions in rm_rf (#5627)

- changelog/4344.bugfix.rst
- src/_pytest/main.py
- testing/test_collection.py
Fixes https://github.com/pytest-dev/pytest/issues/4344.
> Fix RuntimeError when trying to collect package with "__init__.py" only

- testing/python/collect.py
> fix grammar in test_collect_functools_partial docstr

- doc/en/assert.rst
- doc/en/builtin.rst
- doc/en/cache.rst
- doc/en/capture.rst
- doc/en/deprecations.rst
- doc/en/doctest.rst
- doc/en/example/attic.rst
- doc/en/example/markers.rst
- doc/en/example/parametrize.rst
- doc/en/example/pythoncollection.rst
- doc/en/example/simple.rst
- doc/en/example/special.rst
- doc/en/existingtestsuite.rst
- doc/en/fixture.rst
- doc/en/funcarg_compare.rst
- doc/en/getting-started.rst
- doc/en/goodpractices.rst
- doc/en/logging.rst
- doc/en/monkeypatch.rst
- doc/en/plugins.rst
- doc/en/pythonpath.rst
- doc/en/reference.rst
- doc/en/skipping.rst
- doc/en/tmpdir.rst
- doc/en/unittest.rst
- doc/en/usage.rst
- doc/en/warnings.rst
- doc/en/writing_plugins.rst
- doc/en/xunit_setup.rst
ran [pyupgrade-docs](https://github.com/verhovsky/pyupgrade-docs/blob/master/pyupgrade_docs.py) (it's just a copy of [asottile/blacken-docs](https://github.com/asottile/blacken-docs/blob/master/blacken_docs.py) but with pyupgrade instead) with `--py3-only` 
then I labeled all the unlabeled code blocks I could find (except the ones in `/doc/en/announce`) as python/text/bash because pyupgrade-docs and blacken-docs don't pick up unlabeled `code-block`s
then I re-ran pyupgrade and also blacken-docs
> pyupgrade docs to Python 3

- changelog/5095.trivial.rst
- setup.py
- testing/example_scripts/junit-10.xsd
- testing/test_junitxml.py
> Validate xunit2 files against the schema

- src/_pytest/python.py
Fixes https://github.com/pytest-dev/pytest/issues/5253.
> Remove unused function CallSpec2.setall

- doc/en/reference.rst
- doc/en/skipping.rst
- src/_pytest/outcomes.py
- Link function docstring in description.
- Document return value.
- Add example usage to docstring.
> Improve docs of pytest.importorskip

- changelog/5669.doc.rst
- src/_pytest/pytester.py
> 5669: pytester: add docstrings for Testdir.copy_example

- changelog/5707.improvement.rst
- src/_pytest/pytester.py
- src/_pytest/terminal.py
- testing/logging/test_reporting.py
- testing/test_pytester.py
- testing/test_terminal.py
> Show session duration in human-readable format

- src/_pytest/assertion/rewrite.py
`ast.parse("None")` was added/used in 3e6f1fa2d for differences between
Python 2/3, but we do not support py2 anymore.
> assertion.rewrite: use ast.NameConstant(None) directly

- testing/test_pastebin.py
Likely to fix flaky coverage due to requests failing sometimes.
Ref: https://codecov.io/gh/pytest-dev/pytest/compare/f7e81dab9aa8d57498511e1b5655b53cbfbed0d0...83a1f4bd668fe337d42f909cc2ef2d8d986e9748/changes
> test_non_ascii_paste_text: mock call to urlopen

- src/_pytest/assertion/util.py
- testing/test_assertrewrite.py
Previously it would say:
> assert '123456789012...901234567890A' == '1234567890123...901234567890B'"
This makes it look like the "3" might be different already.
This is clearer, and it is OK to have potentially one less char in the
right one:
> assert '123456789012...901234567890A' == '123456789012...901234567890B'"
> assertrepr_compare: prefer same maxsize

- .travis.yml
- scripts/publish_gh_release_notes.py
- tox.ini
I tested this in my fork and it published https://github.com/nicoddemus/pytest/releases/tag/4.99.5 successfully. 👍 
Using an after_deploy script so the release doesn't fail in case there's a problem with the script.
Fix #2933
> Publish GitHub release notes after deployment

- src/_pytest/pytester.py
"pexpect" can be imported on Windows, but does not have "pexpect.spawn"
then.
Ref: https://github.com/pexpect/pexpect/blob/a803933ed53/pexpect/__init__.py#L73-L76
> pytester: spawn: skip without pexpect.spawn

- scripts/publish_gh_release_notes.py
I was doing final tests on the script today, and forgot to change
the hardecoded "pytest-dev/pytest", which ended up publishing a
`4.99.10` release to the main repository by mistake, as my token
has access to both my fork and main repository. 🤕 
I deleted the tag immeditely just a few seconds later, so hopefully
this won't cause major problems.
This change makes it safer to test this in the future, never publishing
to the main repository by mistake (as long as the tags are pushed to the
right repositories of course).
> Use TRAVIS_REPO_SLUG instead of hard-coding pytest-dev/pytest

- changelog/5115.bugfix.rst
- src/_pytest/config/__init__.py
- testing/test_warnings.py
Before it led to an internal error
Ref: #5115 
Not sure how to validate that the warning is emitted, tho :(
> Do not treat warnings as errors during ``pytest_configure``.

- changelog/5734.bugfix.rst
- src/_pytest/compat.py
- src/_pytest/python.py
- testing/acceptance_test.py
- testing/test_compat.py
> warn for async generator functions

- src/_pytest/python.py
- testing/acceptance_test.py
> Async result warn

- doc/en/example/parametrize.rst
I found myself reading this sentence multiple times to understand it. I think splitting it makes more sense.
> reword a parametrize example sentence

- codecov.yml
The only benefit for me is to get notified about finished builds, but
that might happen to early anyway.  Apart from that they are rather big
and distract from actual comments.
> ci: add codecov.yml to turn comments off

- .coveragerc
- testing/python/fixtures.py
This will allow for "raise NotImplementedError" to indicate code not to
be covered in tests etc.
> .coveragerc: add report section

- changelog/5056.trivial.rst
- src/_pytest/config/argparsing.py
- testing/test_config.py
`argparse.HelpFormatter` looks at `$COLUMNS` only, falling back to a default of 80.
`py.io.get_terminal_width()` is smarter there, and could even work better with https://github.com/pytest-dev/py/pull/219.
This ensures to use a consistent value for formatting the ini values etc.
1: https://github.com/pytest-dev/py/pull/219
TODO:
> Inject width via pylib to argparse formatter

- src/_pytest/assertion/rewrite.py
- testing/test_assertion.py
Ref: https://github.com/pytest-dev/pytest/issues/5754
> test_assertion_location

- doc/en/talks.rst
Since there was only one participant signed up, unfortunately the workshop was cancelled.
> Remove cancelled training

- src/_pytest/_code/code.py
- src/_pytest/_code/source.py
- src/_pytest/assertion/__init__.py
- src/_pytest/assertion/rewrite.py
- src/_pytest/assertion/util.py
- src/_pytest/config/__init__.py
- src/_pytest/config/argparsing.py
- src/_pytest/config/findpaths.py
- src/_pytest/mark/evaluate.py
- src/_pytest/mark/structures.py
- src/_pytest/nodes.py
- src/_pytest/reports.py
- src/_pytest/runner.py
`check_untyped_defs = True` instructs mypy to also check bodies of functions which are not annotated ([doc](https://mypy.readthedocs.io/en/latest/config_file.html#untyped-definitions-and-calls)).
I would like to enable this option because it provides some internal dogfooding of the type annotations as they are added. For example, we added type annotations for `pytest.raises`, but since all of the tests are untyped, the tests weren't checked against it. With `check_untyped_defs = True`, there is at least some basic coverage (number of parameters, parameter names, etc.).
There are a few hundred such errors, mostly mypy complaining that it can't infer the type of empty containers, but some other minor stuff as well. This PR fixes the error for a first batch of modules. Each commit handles a …
> 1/X Fix check_untyped_defs = True mypy errors

- .pre-commit-config.yaml
- .travis.yml
- changelog/5751.bugfix.rst
- src/_pytest/_code/code.py
- src/_pytest/compat.py
- src/_pytest/python_api.py
- src/_pytest/recwarn.py
- testing/python/raises.py
The typing module on these versions have these issues:
- `typing.Pattern` cannot appear in a Union since it is not considered a
class.
- `@overload` is not supported in runtime. (On the other hand, mypy
doesn't support putting it under `if False`, so we need some runtime
hack).
Fix  #5751
Fix  #5770
> Fix TypeError when importing pytest on Python 3.5.0 and 3.5.1

- CHANGELOG.rst
- changelog/5751.bugfix.rst
- doc/en/announce/index.rst
- doc/en/announce/release-5.1.1.rst
- doc/en/assert.rst
- doc/en/builtin.rst
- doc/en/cache.rst
- doc/en/capture.rst
- doc/en/doctest.rst
- doc/en/example/markers.rst
- doc/en/example/nonpython.rst
- doc/en/example/parametrize.rst
- doc/en/example/pythoncollection.rst
- doc/en/example/reportingdemo.rst
- doc/en/example/simple.rst
- doc/en/example/special.rst
- doc/en/fixture.rst
- doc/en/getting-started.rst
- doc/en/index.rst
- doc/en/parametrize.rst
- doc/en/skipping.rst
- doc/en/tmpdir.rst
- doc/en/unittest.rst
- doc/en/usage.rst
- doc/en/warnings.rst
- doc/en/writing_plugins.rst
@nicoddemus how do we fund you a better computer, mine's from 2015 and twice as fast :'(
> Preparing release version 5.1.1

- .travis.yml
- azure-pipelines.yml
- scripts/publish_gh_release_notes.py
- tox.ini
Backport of the following PRs: #5723, #5740, and #5750.
> [4.6] Publish GitHub release notes after deployment

- AUTHORS
- changelog/5764.feature.rst
- src/_pytest/pastebin.py
- testing/test_pastebin.py
We find that the `--pastebin` option to `pytest` sometimes fails with "HTTP Error 400: Bad Request". We're still investigating the exact cause of these errors, but in the meantime, a failure to upload to the pastebin service should probably not crash pytest and cause a test failure in the continuous-integration.
This patch catches exceptions like `HTTPError` that may be thrown while trying to communicate with the pastebin service, and reports them as a "bad response", without crashing with a backtrace or failing the entire test suite.
> Gracefully handle HTTP errors from pastebin

- changelog/5786.bugfix.rst
- src/_pytest/reports.py
- testing/code/test_code.py
- testing/code/test_excinfo.py
- testing/conftest.py
- testing/test_reports.py
This PR fixes serialization/deserialization of report objects, which fixes it for `pytest-xdist` (where #5786 originated).
* Moved the contents of `BaseReport._to_json/_from_json` to free functions as they were getting quite large. More importantly, I refactored the code so it can be reused for chained exceptions.
* Move `TWMock` class to a fixture so it can be more easily reused in other test modules. `test_code` was importing it using a relative import, which is not very nice.
Fix #5786
cc @oliveira-esss @prusse-martin
> Serialize/deserialize chained exceptions 

- AUTHORS
- changelog/570.bugfix.rst
- src/_pytest/fixtures.py
- testing/python/fixtures.py
> Fix the scope behavior with indirect fixtures

- .travis.yml
I've tried to reproduce the issue, but it seems to only happen sporadically on Linux.
Mark it is flaky now to avoid people wasting time on PRs when they encounter this problem.
Related to #5795
> Mark flaky test as xfail on Python 3.5.0

- AUTHORS
- changelog/2270.bugfix.rst
- src/_pytest/fixtures.py
- testing/python/fixtures.py
This fixes an old issue #2270 that was closed at the time without a fix. That issue has more info, but basically function scope fixtures in a class (not a test class) are given a reference to the test class, not their own class, as `self`. This causes problems when that fixture tries to access attributes on its class.
> Fix self reference in function scoped fixtures

- changelog/5806.bugfix.rst
- src/_pytest/pastebin.py
- testing/test_pastebin.py
Closes #5806 
Since this is a followup to #5764, I'm basing this on the `features` branch instead of `master`.
> Fix "lexer" being used when uploading to bpaste.net

- AUTHORS
- doc/en/goodpractices.rst
- doc/en/pythonpath.rst
The anchor tag from the note in the ["Tests outside application code"](http://doc.pytest.org/en/latest/goodpractices.html#tests-outside-application-code) section of the Good Practices doc points to the Pythonpath doc but doesn't focus on the section about "Invoking pytest versus python -m pytest". This PR changes the link to point directly to the right section.
> Fix pythonpath anchor

- testing/test_pdb.py
We don't yet know if 3.10 or 4.0 will follow Python 3.9, but whichever it is, it will probably happen in [2020 when Python 3.9 reaches beta](https://www.python.org/dev/peps/pep-0596/#schedule) and work begins on Python 3.9+1.
This will be false for Python 4:
```python
"""
Test that supports breakpoint global marks on Python 3.7+ and not on
CPython 3.5, 2.7
"""
if sys.version_info.major == 3 and sys.version_info.minor >= 7:
assert SUPPORTS_BREAKPOINT_BUILTIN is True
```
---
Found using https://github.com/asottile/flake8-2020:
```console
$ pip install -U flake8-2020
...
$ flake8 --select YTT
./testing/test_pdb.py:856:44: YTT204 `sys.version_info.minor` compared to integer (python4), compare `sys.version_info` to tuple
```
---
- [n/a] Target the `features` branch for new features, …
> Fix for Python 4: replace unsafe PY3 with PY2

- .travis.yml
This causes flaky test failures (crashes).
Closes https://github.com/pytest-dev/pytest/issues/5795.
> ci: Travis: do not test with 3.5.0

- changelog/5807.bugfix.rst
- src/_pytest/capture.py
pypy3.6 on windows doesn't have an `_io.WinConsoleIO`
> Fix pypy3.6 on windows

- doc/en/reference.rst
Remove reference to the `message` argument in the docs as it was deprecated in #4539
> Update doc regarding pytest.raises

- AUTHORS
- changelog/5819.bugfix.rst
- src/_pytest/config/__init__.py
- src/_pytest/pathlib.py
- testing/test_conftest.py
This PR reverts #5792 to introduce a simpler fix: instead of changing all conftest paths to a unique representation, which unfortunately introduced #5819, it only uses a resolved `Path` object as key to the avoid importing `conftest` files more than once.
I would have taken the commits from #5823 (Sorry @Oberon00!), but unfortunately the fork seems to be gone, so I introduced the changes manually: a new test and the CHANGELOG. 
Supersedes #5823.
> Fix regression due to different cases on Windows

- changelog/5811.bugfix.rst
- src/_pytest/nodes.py
- testing/code/test_excinfo.py
This changes `_repr_failure_py` to use `tbfilter=False` always.
TODO:
> Handle --fulltrace with pytest.raises

- AUTHORS
- changelog/1682.deprecation.rst
- changelog/1682.feature.rst
- doc/en/example/costlysetup/conftest.py
- doc/en/fixture.rst
- src/_pytest/deprecated.py
- src/_pytest/fixtures.py
- testing/python/fixtures.py
This is an attempt to implement the dynamic scope feature described in #1682.
> Implemented the dynamic scope feature.

- doc/en/_templates/layout.html
As discussed in the mailing list, pytest will join the
digital strike for the climate on Sep 20th. This will show
a closable banner on the docs until the date, and when the date
comes the banner will become a (closable) full page.
I will also pin an issue saying that the developers won't be
available on Sep 20th.
Code taken from https://github.com/fightforthefuture/digital-climate-strike
> Show banner/full page for the Digital Climate Strike

- doc/en/logging.rst
A tiny fix in the docs that caught me out... Just validating my debugging here:
```
ipdb> record = caplog.records[0]
ipdb> dir(record)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'args', 'created', 'exc_info', 'exc_text', 'filename', 'funcName', 'getMessage', 'levelname', 'levelno', 'lineno', 'message', 'module', 'msecs', 'msg', 'name', 'pathname', 'process', 'processName', 'relativeCreated', 'stack_info', 'thread', 'threadName']
ipdb> record.levelno
10
```
> Fix logging doc: change x.level to x.levelno

- scripts/report-coverage.sh
Recently sometimes Azure has failed with:
```
++ curl -s https://codecov.io/bash
bash: /dev/fd/63: No such file or directory
```
This attempts to fix this by modifying report-coverage.sh slightly.
> Change report-coverage.sh in attempt to fix Azure

- testing/test_parseopt.py
> Do not call python directly but use sys.executable. Fixes #5872

- changelog/5884.bugfix.rst
- src/_pytest/runner.py
- testing/conftest.py
- testing/python/setup_only.py
- testing/python/setup_plan.py
> Fix --setup-only and --setup-show for custom pytest items

- src/_pytest/pytester.py
> Fix attribute docs in _pytest.pytester

- doc/en/reference.rst
I built the docs locally and confirmed that section now renders as expected
> Fix doc typo

- src/_pytest/assertion/util.py
- src/_pytest/compat.py
- src/_pytest/mark/structures.py
- testing/test_assertion.py
attrs 19.2 deprecated cmp in favor of the dataclass-ish eq/order duo.
This causes deprecation warnings that in turn break some of the cool new deep
object comparisons. Since we at attrs expected this to be a problem, it shipped
with helpers to write backward and forward compatible code.
This PR uses that and avoids changed to minimal versions.
As for your checklist, I think this qualifies as a trivial bug fix. Let me know if you need anything more.
Fixes #5901
> Fix warnings with attrs 19.2 and fix object assertions

- src/_pytest/debugging.py
- testing/acceptance_test.py
Noticed this with tests for pdb++.
> Allow for "pdb" module to be rewritten

- changelog/5914.feature.rst
- src/_pytest/pytester.py
- testing/acceptance_test.py
- testing/code/test_excinfo.py
- testing/logging/test_fixture.py
- testing/logging/test_reporting.py
- testing/python/collect.py
- testing/python/fixtures.py
- testing/python/setup_only.py
- testing/python/show_fixtures_per_test.py
- testing/test_assertion.py
- testing/test_assertrewrite.py
- testing/test_cacheprovider.py
- testing/test_capture.py
- testing/test_collection.py
- testing/test_conftest.py
- testing/test_doctest.py
- testing/test_junitxml.py
- testing/test_pytester.py
- testing/test_runner.py
- testing/test_runner_xunit.py
- testing/test_skipping.py
- testing/test_terminal.py
- testing/test_unittest.py
The current idiom is to use:
```python
assert re.match(pat, result.stdout.str()) is None
```
Or 
```python
assert line not in result.stdout.str()
```
But this does not really give good results when it fails.
Those new functions produce similar output to ther other match lines functions.
> Introduce no_fnmatch_line/no_re_match_line in pytester

- testing/test_meta.py
> Add test to ensure _pytest is warning-clean on import

- changelog/5924.feature.rst
- src/_pytest/assertion/util.py
- testing/test_assertion.py
Massage text input for difflib when comparing pformat output of
different line lengths.
Also do not strip ndiff output on the left, which currently already
removes indenting for lines with no differences.
Before:
E   AssertionError: assert ['version', '...version_info'] == ['version', '...version', ...]
E     Right contains 3 more items, first extra item: ' '
E     Full diff:
E     - ['version', 'version_info', 'sys.version', 'sys.version_info']
E     + ['version',
E     +  'version_info',
E     +  'sys.version',
E     +  'sys.version_info',
E     +  ' ',
E     +  'sys.version',
E     +  'sys.version_info']
After:
E   AssertionError: assert ['version', '...version_info'] == ['version', '...version', ...]
E     Right contains 3 more items, first extra item: ' '
E     Full diff:
E …
> Improve full diff output for lists

- doc/en/py27-py34-deprecation.rst
https://github.com/pytest-dev/pytest/pull/5941 made me realize the technical aspects of 4.6 maintenance are not as visible as they can be.
> Add link to technical aspects issue to the py27-py34 docs

- doc/en/projects.rst
> Documentation update to project examples

- scripts/report-coverage.sh
Fetching this URL is very flaky, even after adding retries. I found a possible explanation here: https://github.com/python-trio/trio/issues/1231, let's try it!
> Workaround curl bug which makes retries of fetching codecov.io/bash not work

- codecov.yml
The only benefit for me is to get notified about finished builds, but
that might happen to early anyway.  Apart from that they are rather big
and distract from actual comments.
(cherry picked from commit d50198a3ff1458b6b175cb9ae274a5a98be965ab)
> [4.6] ci: add codecov.yml to turn comments off

- doc/en/doctest.rst
- doc/en/fixture.rst
- doc/en/usage.rst
- src/_pytest/config/__init__.py
- src/_pytest/fixtures.py
- src/_pytest/hookspec.py
- src/_pytest/main.py
Notice some features since 5.0 were not being properly
marked in which version they have been added/changed.
> Add missing version added/changed markers to docs

- doc/en/announce/release-5.2.0.rst
I got mentioned twice in the `5.2.0` release notes - once by full name and once by the username. I've removed the username mention.
> Remove redundant mention from 5.2.0 release notes.

- tox.ini
Ref: https://github.com/pytest-dev/pytest/issues/5974
> tests: filterwarnings: do not crash with "(rm_rf)" warning

- src/_pytest/terminal.py
Note that the style with help texts is not consistent, but this appears to be the one used in most cases.
> help: display default verbosity

- src/_pytest/config/__init__.py
Related to https://github.com/pytest-dev/pytest/issues/4445#issuecomment-543180101 and https://github.com/pytest-dev/pytest/issues/4445#issuecomment-543287636. The code that could trigger the execution of _issue_warning_captured was removed with a7e4016.
> Remove unreachable code from config._prepareconfig

- doc/en/example/parametrize.rst
nullcontext has been backported in `contextlib2==0.6.0`
> Update doc to use contextlib2.nullcontext

- src/_pytest/_code/code.py
> ExceptionInfo.from_current: pass through exprinfo

- src/_pytest/runner.py
- testing/test_runner.py
It shouldn't have literal newlines in it.
> Improve/revisit CallInfo.__repr__

- changelog/6008.improvement.rst
- src/_pytest/config/__init__.py
- testing/test_config.py
This avoids mutating the original list to reflect on InvocationParams,
which is supposed to be an immutable snapshot of the state of pytest.main()
at the moment of invocation (see pytest-dev/pytest-xdist#478).
> Make InvocationParams.args a tuple

- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
noticed this while poking around, makes `cat .pytest_cache/.gitignore` work slightly better
> Ensure .pytest_cache file has a newline at the end

- AUTHORS
- changelog/5906.bugfix.rst
- src/_pytest/setuponly.py
- testing/python/setup_only.py
resolve #5906 
Thanks for @blueyed  @asottile for the great help.
Really appreciate it.
> setuponly: remove printing out/err from capman

- testing/python/setup_only.py
Follow-up to https://github.com/pytest-dev/pytest/pull/6009.
No changelog.. ;)
> tests: remove unnecessary test, clarify

- changelog/5206.bugfix.rst
- src/_pytest/cacheprovider.py
- testing/test_cacheprovider.py
Caveat: does not forget about old nodeids
Fixes https://github.com/pytest-dev/pytest/issues/5206
> cache: NFPlugin: keep known nodeids

- src/_pytest/setuponly.py
- src/_pytest/warnings.py
> Minor: help / direct usage of config

- src/_pytest/pytester.py
This gets done in `parseconfig` already.
> pytester: parseconfigure: remove duplicate config._ensure_unconfigure

- changelog/5061.feature.rst
- src/_pytest/terminal.py
- testing/test_pdb.py
- testing/test_terminal.py
Ref: https://github.com/pytest-dev/pytest/issues/5060
This is quite a hack, and should probably go with better support in py itself, or some more generic wrapping.
TODO:
> Multiple colors with terminal summary_stats

- .pre-commit-config.yaml
- src/_pytest/recwarn.py
Changelogs:
- http://mypy-lang.blogspot.com/2019/09/mypy-730-released.html
- http://mypy-lang.blogspot.com/2019/10/mypy-0740-released.html
New errors:
```
src/_pytest/recwarn.py:77: error: Missing return statement
src/_pytest/recwarn.py:185: error: "bool" is invalid as return type for "__exit__" that always returns False
src/_pytest/recwarn.py:185: note: Use "typing_extensions.Literal[False]" as the return type or change it to "None"
src/_pytest/recwarn.py:185: note: If return type of "__exit__" implies that it may return True, the context manager may swallow exceptions
src/_pytest/recwarn.py:185: error: Return type "bool" of "__exit__" incompatible with return type "None" in supertype "catch_warnings"
src/_pytest/recwarn.py:230: error: "bool" is invalid as return type for "__exit__" that …
```
> Update mypy 0.720 -> 0.740

- changelog/4901.trivial.rst
- src/_pytest/pytester.py
- testing/test_pytester.py
> Show the mnemonic of pytest.ExitCode in RunResult's repr

- src/_pytest/pytester.py
- testing/test_config.py
- testing/test_runner.py
This avoids having a trailing empty lines always.
> pytester: runpytest_inprocess: use splitlines()

- src/_pytest/assertion/rewrite.py
- src/_pytest/cacheprovider.py
- src/_pytest/capture.py
- src/_pytest/doctest.py
- src/_pytest/logging.py
- src/_pytest/nodes.py
- src/_pytest/terminal.py
- src/_pytest/warnings.py
- testing/test_capture.py
- testing/test_doctest.py
Fixes for some more `check_untyped_defs` errors from mypy.
The first commit required a small refactoring (see commit message).
Continuation of #5673.
> 2/X Fix check_untyped_defs = True mypy errors

- changelog/6044.bugfix.rst
- src/_pytest/pathlib.py
- testing/test_tmpdir.py
Also improved the message when we are passed an unknown function.
> Review rm_rf handling of FileNotFoundErrors

- .travis.yml
- changelog/5936.feature.rst
- src/_pytest/assertion/util.py
- testing/test_assertrewrite.py
Ref: https://github.com/pytest-dev/pytest/issues/3962
TODO:
> assertrepr_compare: use safeformat with -vv

- changelog/6044.bugfix.rst
- src/_pytest/pathlib.py
- testing/test_tmpdir.py
Backport of #6044
Conflicts:
src/_pytest/pathlib.py
testing/test_tmpdir.py
> [4.6] Review rm_rf handling of FileNotFoundErrors 

- README.rst
- doc/en/_templates/globaltoc.html
- doc/en/contents.rst
- doc/en/index.rst
- doc/en/sponsor.rst
- doc/en/tidelift.rst
Tidelift has launched a new marketing campaign as outlined here:
* https://forum.tidelift.com/t/task-enhancement-marketing-the-tidelift-subscription-to-your-users/321
This PR splits the previous "sponsor" information into two, Open Collective
and Tidelift (as they have very different target audiences).
Also took the opportunity to reorder some items at the end of
the contents page in a manner that I believe make more sense.
> Update Tidelift docs with latest campaign

- changelog/6026.improvement.rst
- src/_pytest/pytester.py
- testing/test_pytester.py
This is important for using another match_nickname, e.g. "re.match".
TODO:
> pytester: align prefixes

- changelog/6057.feature.rst
- src/_pytest/python_api.py
- testing/python/approx.py
Adds a tolerance indicator to `pytest.approx` when the expected value is a complex number. This should make it easier to reason about how complex number approximations are handled by pytest.
Relates to #6057.
> 6057 tolerance on complex approx

- changelog/4730.feature.rst
- src/_pytest/assertion/rewrite.py
- src/_pytest/compat.py
- testing/test_assertrewrite.py
> Support sys.pycache_prefix on py38

- src/_pytest/_code/code.py
- src/_pytest/logging.py
- src/_pytest/pytester.py
- src/_pytest/reports.py
- testing/test_capture.py
- testing/test_resultlog.py
- testing/test_terminal.py
In Python3, `py.io.TextIO` is just an alias to `io.StringIO`. Remove the indirection.
> Replace py.io.TextIO with io.StringIO

- src/_pytest/mark/__init__.py
Avoids comments for ignored typing.
> mark: move pytest_cmdline_main.tryfist into decorator

- testing/test_capture.py
Failed for me due to different indent (?) - not reproducible:
>   ???
E   Failed: nomatch: 'E           TypeError: write() argument must be str, not bytes'
…
E       and: '>   def mode(self):'
E       and: 'E   TypeError: write() argument must be str, not bytes'
…
E   remains unmatched: 'E           TypeError: write() argument must be str, not bytes'
> tests: fix testing/test_capture.py::test_typeerror_encodedfile_write

- AUTHORS
- changelog/5990.improvement.rst
- src/_pytest/main.py
- src/_pytest/terminal.py
- testing/acceptance_test.py
- testing/python/collect.py
- testing/python/fixtures.py
- testing/test_assertrewrite.py
- testing/test_capture.py
- testing/test_collection.py
- testing/test_doctest.py
- testing/test_mark.py
- testing/test_runner_xunit.py
- testing/test_skipping.py
- testing/test_stepwise.py
- testing/test_terminal.py
- testing/test_warnings.py
Fixes #5989 .
I presume this is small enough that I shouldn't add it to the changelog (or myself to the authors), but please do let me know if I should.
> Plurality matching

- .travis.yml
This removes xdist there (not compatible with the pexpect tests), but it
is better to have one job less, although slower due to not using xdist.
> ci: Travis: include pexpect in main py37 job

- changelog/4488.feature.rst
- doc/en/contents.rst
- doc/en/deprecations.rst
- doc/en/report_log.rst
- doc/en/usage.rst
- src/_pytest/config/__init__.py
- src/_pytest/hookspec.py
- src/_pytest/report_log.py
- src/_pytest/reports.py
- testing/test_report_log.py
- testing/test_reports.py
**EDIT**:
This should now be ready for final review.
**OLD**:
Started working on this, before progressing further I want to gather opinions if the direction is right.
Given this simple test file:
```python
def test_ok():
pass
def fail():
assert 0
def test_failure():
fail()
```
Here is the file produced:
```json
{"nodeid": "", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "test_foo.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "test_foo.py::test_ok", "location": ["test_foo.py", 0, "test_ok"], "keywords": {"test_ok": 1, "test_foo.py": 1, ".tmp": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], …
```
> Introduce --report-log 

- changelog/6099.bugfix.rst
- src/_pytest/debugging.py
- testing/test_pdb.py
I'm not sure if this is the correct / best way to fix so please check
critically when reviewing
Without this, the second time it tries to stop in a parametrized
function it raises instead:
`ValueError: --trace can't be used with a fixture named func!`
Also lift the restriction that was disallowing `--trace` on tests with a parameter named `func`
> Fix --trace for parametrized tests

- src/_pytest/_io/saferepr.py
- src/_pytest/assertion/util.py
Annotate a couple more leaf modules.
While annotating, I found some dead code in the `_diff_text` function (see second commit). I included it in this PR since the next commit depends on it.
> Add type annotations to _pytest._io.saferepr and _pytest.assertion.util._diff_text

- src/_pytest/assertion/util.py
First off thank you for providing great open source pytest. Wanted to make a small bug fix. I see your reassigning a variable `explanation = explanation` then using it below that. Didn't make logically sense. So I thought would be nice to send a bug fix.
> Removing variable being reassigned

- changelog/6097.improvement.rst
- src/_pytest/terminal.py
- testing/test_terminal.py
Fixes https://github.com/pytest-dev/pytest/issues/6097.
> Color percentage indicator

- AUTHORS
- changelog/5515.feature.rst
- doc/en/reference.rst
- src/_pytest/logging.py
- testing/logging/test_formatter.py
Allow selective auto-indentation of multiline log messages.
Supports command line option ``--log-auto-indent [value]``
and config option ``log_auto_indent`` to set the default for all logging.
Supports passing kwarg ``extra={"auto_indent": [value]}`` to
calls to ``log.log()`` to specify auto-indentation behavior for
a specific entry in the log.
``[value]`` can be:
* True or On - Dynamically auto-indent multiline log messages
* False or Off or 0 - Do not auto-indent multiline log messages
* [integer] - auto-indent multiline log messages by [integer] spaces
``extra`` kwarg overrides the value specified on the command line or in the config.
Implements feature request https://github.com/pytest-dev/pytest/issues/5515
> Add log-auto-indent option to control multiline formatting

- src/_pytest/nodes.py
Via https://github.com/blueyed/pytest/pull/42.
> FSCollector: keep/use given fspath

- changelog/2548.bugfix.rst
- src/_pytest/skipping.py
- src/_pytest/terminal.py
- testing/test_skipping.py
The original fix in https://github.com/pytest-dev/pytest/pull/2548 was
wrong, and was likely meant to fix the use with decorators instead,
which this does now (while reverting 869eed9898).
> terminal: fix line offset with skip reports

- AUTHORS
- changelog/5830.bugfix.rst
- src/_pytest/python.py
- testing/test_skipping.py
Issue #5830 
Fix fail skipping the first test in package marked as ``skip``
> fix bug with nonskipped first test in package

- tox.ini
This would prevent TOXENV=py37-pexpect-… from running on e.g. FreeBSD.
And even on Windows it is pytest's job of skipping the tests then.  This
was probably still from when the pexpect env was only running
pexpect-based tests.
> [RDY] tox: remove platform restriction, only used for pexpect

- src/_pytest/assertion/util.py
- testing/test_assertion.py
Follow-up to 946434c61 (#5924).
Before this patch the test would look like this:
{'env': {'sub...s wrapped'}}}} == {'env': {'sub...}}}, 'new': 1}
Omitting 1 identical items, use -vv to show
Right contains 1 more item:
{'new': 1}
Full diff:
{
'env': {'sub': {'long_a': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
-                  'sub1': {'long_a': 'substring '
+                  'sub1': {'long_a': 'substring that gets wrapped'}}},
?                                                +++++++++++++++++ ++++
+  'new': 1,
-                                     'that '
-                                     'gets '
-                                     'wrapped'}}},
}
> assert: fix _compare_eq_iterable: re-format both sides

- src/_pytest/main.py
Via https://github.com/blueyed/pytest/pull/42.
> Session: collect: keep/use already parsed initialpart

- changelog/6047.bugfix.rst
- src/_pytest/_io/saferepr.py
- testing/code/test_excinfo.py
- testing/io/test_saferepr.py
- testing/test_session.py
Ref: https://github.com/pytest-dev/pytest-django/pull/776
This causes INTERNALERRORs within pytest-django, which uses `pytest.fail` to prevent DB access, and that is derived from BaseException.
> saferepr: handle BaseExceptions

- src/_pytest/main.py
- testing/acceptance_test.py
Harden one test where it is tested.
All tests testing this:
testing/acceptance_test.py:184(TestGeneralUsage::test_not_collectable_arguments)
testing/acceptance_test.py:373(TestGeneralUsage::test_direct_addressing_notfound)
testing/acceptance_test.py:403(TestGeneralUsage::test_issue134_report_error_when_collecting_member[test_fun.py::test_a])
testing/acceptance_test.py:420(TestGeneralUsage::test_report_all_failed_collections_initargs)
testing/test_config.py:1309(test_config_blocked_default_plugins[python])
(via https://github.com/blueyed/pytest/pull/88)
> _perform_collect: remove comment about untested code

- src/_pytest/_code/source.py
- src/_pytest/pytester.py
- src/_pytest/warning_types.py
Some more annotations. `pytester` doesn't make sense in terms of progression, but I got to it somehow (only did about a half).
> Add type annotations to _pytest.{warning_types,_code.source,pytester}

- changelog/6074.bugfix.rst
- src/_pytest/pathlib.py
- testing/test_tmpdir.py
Ref: https://github.com/pytest-dev/pytest/pull/6044/files#r339321752
> on_rm_rf_error: ignore os.open (no warning)

- src/_pytest/assertion/__init__.py
Previously it was an alias, which makes it unnecessary hard to find
all implementations (either by IDE or using a simple search).
> Explicitly implement pytest_assertrepr_compare in assertion plugin

- src/_pytest/mark/structures.py
- testing/test_mark.py
Please see the commit messages.
> Two minor tweaks in MarkDecorator's implementation

- AUTHORS
- changelog/6152.improvement.rst
- src/_pytest/python.py
- testing/test_mark.py
`pytest.mark.parametrize` will currently use the name of a function or class as the parameter "id" by default. This PR extends this behavior to modules (or other objects defining `__name__`) as well.
An alternative implementation would have been to add an (`or inspect.ismodule(var)`) to the existing case, but I thought perhaps there may be other objects with `__name__` as well that could benefit from this behavior.
A concrete use case where I wanted these was for some tests that parametrize using different numerical array modules with matching API (NumPy and CuPy). It is preferable for the name of the module to show up in the id rather than "module0" or similar.
- [ x ] Target the `features` branch for new features, improvements, and removals/deprecations.
- [ x ] Include new tests or …
> use __name__ attribute in the parametrize id for modules as well

- src/_pytest/helpconfig.py
> showversion: no need for `py.path.local`

- src/_pytest/assertion/util.py
- testing/test_assertion.py
This fixes/removes the previous hack of re-trying with minimum width,
which fails short when it splits strings.
This inherits from `pprint.PrettyPrinter` to override `_format` in a
minimal way to always dispatch, regardless of the given width.
Code ref: https://github.com/python/cpython/blob/5c0c325453a175350e3c18ebb10cc10c37f9595c/Lib/pprint.py#L170-L178
> _compare_eq_iterable: use AlwaysDispatchingPrettyPrinter

- src/_pytest/compat.py
- src/_pytest/nodes.py
- testing/test_compat.py
This is a useful utility to abstract the caching property idiom.
It is in compat.py since eventually it will be replaced by
functools.cached_property.
Fixes #6131.
> Add a @cached_property implementation

- tox.ini
This comes via hypothesis:
```
% COLUMNS=80 p testing/python/metafunc.py::TestMetafunc::test_idval_hypothesis -vv --tb=short
============================= test session starts ==============================
platform linux -- Python 3.7.4, pytest-3.1.4.dev721+g3367bf03b.d20191112, py-1.8.1.dev11+g34f716fe, pluggy-0.13.1.dev8+ga5130ac.d20191103 -- …/Vcs/pytest/.venv/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('…/Vcs/pytest/.hypothesis/examples')
rootdir: …/Vcs/pytest, inifile: tox.ini
plugins: forked-1.1.3, hypothesis-4.44.1, cov-2.8.1, coverage-pytest-plugin-0.1, enhancements-0.0.5.dev1-gf361636-dirty, xdist-1.30.0
collected 1 item
testing/python/metafunc.py::TestMetafunc::test_idval_hypothesis FAILED   [100%] …
```
> filterwarnings: ignore DeprecationWarning from nose

- doc/en/reference.rst
> Delineate syntactically that the 'match' argument to 'raises' is keyword-only

- testing/python/metafunc.py
It currently fails with a TypeError, and was not updated since 2013 -
therefore it can be assumed that it is not important to support it.
```
____________________ ERROR collecting test_nested_marks.py _____________________
…/Vcs/pluggy/src/pluggy/hooks.py:286: in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
…/Vcs/pluggy/src/pluggy/manager.py:93: in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
…/Vcs/pluggy/src/pluggy/manager.py:337: in traced_hookexec
return outcome.get_result()
…/Vcs/pluggy/src/pluggy/manager.py:335: in <lambda>
outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
…/Vcs/pluggy/src/pluggy/manager.py:87: in <lambda>
firstresult=hook.spec.opts.get("firstresult") if hook.spec else False, …
```
> tests: remove test_nested_marks (xfail)

- changelog/6181.improvement.rst
- doc/en/usage.rst
- src/_pytest/terminal.py
- testing/test_collection.py
- testing/test_terminal.py
Via https://github.com/blueyed/pytest/pull/108.
> terminal: report ``session.shouldfail`` reason (``-x``)

- changelog/6176.improvement.rst
- src/_pytest/pytester.py
- testing/test_assertion.py
Before:
def assertoutcome(self, passed: int = 0, skipped: int = 0, failed: int = 0) -> None:
realpassed, realskipped, realfailed = self.listoutcomes()
assert passed == len(realpassed)
>       assert skipped == len(realskipped)
E       assert 1 == 0
E        +  where 0 = len([])
After:
>       reprec = testdir.inline_run(testpath, "-s")
E       AssertionError: ([], [], [<TestReport 'nodeid' when='call' outcome='failed'>])
E       assert {'failed': 1, 'passed': 0, 'skipped': 0} == {'failed': 0, 'passed': 0, 'skipped': 1}
> pytester: Hookrecorder: improve assertoutcome

- changelog/6183.bugfix.rst
- src/_pytest/python.py
- testing/python/metafunc.py
> Show a better message when 'request' is used in parametrize

- doc/en/example/simple.rst
Instead of giving an example of using `sys` and then, at the end, advising to not use `sys`, just give a preferred example. This is especially helpful since mypy 0.740 has started (correctly) complaining about `sys._called_from_test` not being present.
> Update advice about _called_from_test.

- .github/PULL_REQUEST_TEMPLATE.md
- [n/a, small docs fix] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
---
* The "(please delete...)" text is redundant and can be removed; it's inside comments so won't be shown anyway.
* Replace the semicolon with a fullstop. It's not necessary here, you don't use them at the end of a sentence; they would only go in the middle of a sentence, a bit like a comma.
> Update text in PR template

- changelog/6179.deprecation.rst
- doc/en/deprecations.rst
- src/_pytest/deprecated.py
- src/_pytest/junitxml.py
- testing/deprecated_test.py
> Issue a warning to prepare change of 'junit_family' default value

- AUTHORS
- changelog/6194.bugfix.rst
- changelog/6197.bugfix.rst
- src/_pytest/python.py
- testing/test_collection.py
- testing/test_skipping.py
> Fix incorrect discovery of non-test `__init__.py` files.

- src/_pytest/assertion/rewrite.py
- src/_pytest/config/__init__.py
- testing/test_assertrewrite.py
- testing/test_config.py
- testing/test_conftest.py
- testing/test_junitxml.py
This is important for `isinstance` checks etc.
TODO:
~~- [ ] after #6192 (conflicts there, https://github.com/pytest-dev/pytest/pull/6192/files#diff-af40f12336a069d7f9538cf71a4010ecL2)~~
> Import Path from _pytest.pathlib for py35

- CHANGELOG.rst
resolves #6135
Thanks for giving the change for my first PR in pytest!
I checked the contribution guide and the description in the issue and think directly modifying the changelog in 3.9.0 instead of adding a new one may be more reasonable.
Comments are welcome.
@Zac-HD
> changelog: #3985 also introduce `tmp_path_factory`

- changelog/6206.improvement.rst
- src/_pytest/cacheprovider.py
``json.dump`` is slower since it iterates over chunks [1].
For 100 ``cache.set`` calls this saved ~0.5s (2.5s => 2s), using a dict
with 1500 entries, and an encoded size of 500kb.
Python 3.7.4.
1: https://github.com/blueyed/cpython/blob/1c2e81ed00/Lib/json/__init__.py#L177-L180
> cacheprovider: set: use json.dumps + write

- .pre-commit-config.yaml
- src/_pytest/config/__init__.py
- src/_pytest/config/argparsing.py
- src/_pytest/pytester.py
- testing/python/fixtures.py
- testing/python/raises.py
- testing/test_collection.py
- testing/test_mark.py
- testing/test_skipping.py
- testing/test_tmpdir.py
- testing/test_unittest.py
This brings https://github.com/psf/black/pull/826, which helps with
https://github.com/psf/black/issues/601.
> pre-commit: upgrade black

- .pre-commit-config.yaml
- src/_pytest/config/__init__.py
- src/_pytest/python_api.py
- src/_pytest/recwarn.py
- testing/deprecated_test.py
- testing/python/fixtures.py
- testing/test_collection.py
- testing/test_mark.py
- testing/test_recwarn.py
- testing/test_skipping.py
- testing/test_tmpdir.py
- testing/test_unittest.py
https://github.com/pytest-dev/pytest/pull/6208 for 4.6.
> [4.6] Upgrade black

- src/_pytest/_code/code.py
- src/_pytest/_code/source.py
- src/_pytest/assertion/rewrite.py
- src/_pytest/compat.py
- src/_pytest/fixtures.py
- src/_pytest/python.py
- src/_pytest/python_api.py
- src/_pytest/recwarn.py
- testing/code/test_code.py
- testing/code/test_excinfo.py
- testing/code/test_source.py
- testing/test_capture.py
This PR starts with some small prerequisite commits, and then adds type annotations to `_pytest.compat` and `_pytest._code.code`.
Let me know if this is too big for one PR, and I will split it. Note that some part of the diff is just adding `-> None` to some test functions, so that mypy will check them without `check_untyped_defs = True` (which needs more work).
> Add type annotations to _pytest.compat and _pytest._code.code

- testing/test_cacheprovider.py
- Setting PYTHONDONTWRITEBYTECODE in the environment does not change it
for the current process.
- Revisit tests in general, mainly formatting.
> tests: revisit test_cacheprovider

- src/_pytest/python.py
This makes it easier to read `pytest_generate_tests`.
> Factor out _validate_parametrize_spelling

- src/_pytest/python.py
- testing/python/metafunc.py
> Metafunc: remove hack for DefinitionMock

- setup.cfg
This allows for checking files inside of "testing" without having
"src/…" as an argument also.
Related: https://github.com/python/mypy/issues/7967, https://github.com/python/mypy/issues/7968.
> mypy: config: use mypy_path=src

- AUTHORS
- changelog/2049.bugfix.rst
- src/_pytest/setupplan.py
- testing/python/setup_plan.py
This PR fixes #2049 by setting the `fixturedef` cache key in the dummy fixture result used when `--setup-plan` runs (the current implementation does not). This makes the printing of the `SETUP`/`TEARDOWN` messages obey the fixture lifetimes as expected (and as already correctly happens with `--setup-show`).
I added two tests, but they're both rather crude. One just sets up a simple class-scoped fixture and checks that the correct number of messages appear. The other checks that the printed output of `--setup-show` and `--setup-plan` agree on the ordering and number of messages. I don't know if there any good idioms for this kind of thing in the test suite already. Happy to make changes if they're not up to snuff!
> Fix --setup-plan fixture lifetimes

- AUTHORS
- changelog/6189.bugfix.rst
- src/_pytest/python.py
- testing/test_collection.py
> Fix incorrect result of getmodpath method.

- .travis.yml
- azure-pipelines.yml
`tox -vv` is too verbose, and was only used as a hack to get the output
of durations.
As for information in logs `-v` could be used maybe still, but I've
decided to revert it for now.
This reverts commit 56cec5fa79106c0e8c02eb34bd8e5768ec52044d.
> Revert "ci: use tox -vv"

- src/_pytest/python.py
Added in 79927428d initially, but never used.
> python: remove unused pytest_make_parametrize_id hookimpl

- changelog/6231.improvement.rst
- src/_pytest/mark/structures.py
- src/_pytest/python.py
- testing/python/metafunc.py
- there is no need to do this with `--strict-markers`
- it can be done when looking up marks, instead of for every generated
test
TODO:
> Improve check for misspelling of parametrize

- .github/PULL_REQUEST_TEMPLATE.md
- changelog/README.rst
This makes easier for contributors to get the CHANGELOG entry
right the first time.
> Improve instructions on how to write CHANGELOG entries

- CHANGELOG.rst
- doc/5934.feature.rst
Apparently the version of sphinx that rtd uses is a little more strict about whether an anonymous `code-block` can happen
> Fix rendering of Before/After in changelog

- changelog/5914.bugfix.rst
- src/_pytest/pytester.py
- testing/test_pytester.py
This is necessary for when using e.g. `no_fnmatch_line` after it.
Factor it out into `_fail`.
(cherry picked from commit aade7ed0045ba32557ef8565cbab28a2c91053a7)
Ref: https://github.com/pytest-dev/pytest/pull/5914#issuecomment-549182242
> pytester: reset log output in _match_lines

- changelog/1857.improvement.rst
- changelog/759.improvement.rst
- src/_pytest/mark/structures.py
- src/_pytest/python.py
- testing/python/metafunc.py
Fixes https://github.com/pytest-dev/pytest/issues/759
Via https://github.com/blueyed/pytest/pull/105.
> parametrized: ids: support generator/iterator

- src/_pytest/pytester.py
Follow-up to 2228ccb (gone lost in resolving the conflict).
> pytester: LineMatcher: __tracebackhide__ with _fail

- CHANGELOG.rst
- doc/en/announce/release-2.0.0.rst
- doc/en/announce/release-2.0.1.rst
- doc/en/announce/release-2.2.0.rst
- doc/en/announce/release-2.3.0.rst
- doc/en/announce/release-2.3.4.rst
- doc/en/announce/release-2.4.0.rst
- doc/en/announce/release-2.7.0.rst
- doc/en/announce/release-2.9.0.rst
- doc/en/conf.py
- doc/en/fixture.rst
- doc/en/projects.rst
- doc/en/talks.rst
- scripts/release.py
- tox.ini
Fixes #1722 by checking all links in documentation during the release process.
Should only be merged after all broken links are fixed (https://github.com/pytest-dev/pytest/pull/5613)
It's running during release in release.py or can be triggered manually by executing `tox -e docs-checklinks`.
False positives can be added to list `linkcheck_ignore` in `doc/en/conf.py`.
> Added link checking to tox and release.py

- src/_pytest/_argcomplete.py
- src/_pytest/config/__init__.py
- src/_pytest/config/argparsing.py
- testing/test_parseopt.py
The first commit cleans up some old feature that slightly interfered with the types. The second commit adds annotations to the argument parsing code.
> Add type annotations to _pytest.config.argparsing and corresponding Config code

- .gitignore
- CONTRIBUTING.rst
From: https://github.com/pytest-dev/pytest/pull/6244
> Add develop instructions to CONTRIBUTING

- AUTHORS
- changelog/6255.bugfix.rst
- src/_pytest/runner.py
- testing/test_runner.py
Existing code in the test runner clears the `sys.last_traceback`, `sys.last_type` and `sys.last_exc` attributes by setting them to `None`. This PR changes that code to delete these attributes using `del` instead.
Rationale:
- In the (presumably common and desirable) case that there were no exceptions, this ensures that the state of this particular part of `sys` module is unchanged by the test run. (Going from the attribute not existing to it existing but being `None` is a change, albeit a fairly benign one.)
- This better matches the behaviour of the Python standard library: in the (very) few places where CPython clears these attributes, it uses `del`.
- In general, we want to restrict the possible states of `sys.last_traceback` (for example) to just two: either the attribute doesn't …
> Remove sys.last_traceback attribute using del instead of setting to None

- .pre-commit-config.yaml
- doc/en/conf.py
This configures the default role for interpreted text (single
backticks), avoiding the need to check for / enforce double backticks.
Fixes also one instance in the existing changelog:
- Detect `pytest_` prefixed hooks using the internal plugin manager since
``pluggy`` is deprecating the ``implprefix`` argument to ``PluginManager``.
(`#3487 <https://github.com/pytest-dev/pytest/issues/3487>`_)
> docs: configure default_role=literal

- changelog/6257.improvement.rst
- src/_pytest/main.py
- testing/test_main.py
Fixes https://github.com/pytest-dev/pytest/issues/6257.
Via https://github.com/blueyed/pytest/pull/132.
> main: wrap_session: handle exit.Exception with notify_exception

- changelog/6254.bugfix.rst
- src/_pytest/terminal.py
Use `dict.keys()` to work around `__iter__` not working with a
multiprocessing DictProxy.
Ref: https://github.com/python/cpython/pull/17333
Fixes https://github.com/pytest-dev/pytest/issues/6254.
Ref: https://github.com/browsertron/pytest-parallel/issues/36
> terminal: _get_main_color: help pytest-parallel

- changelog/6082.bugfix.rst
- src/_pytest/doctest.py
- testing/test_doctest.py
For #6082. Doctest itself does not take into account `@property`. Overriding the line detection method with an additional condition on `isdatadescriptor` helped.
> Fix line detection for properties in doctest tests

- AUTHORS
- changelog/4445.bugfix.rst
- changelog/5928.bugfix.rst
- changelog/5984.improvement.rst
- src/_pytest/config/__init__.py
- src/_pytest/hookspec.py
- src/_pytest/mark/structures.py
- src/_pytest/warnings.py
- testing/test_warnings.py
This pull requests aims to add the acceptance tests mentioned in #4445. The main intention is to check whether a specific warning emitted by `_issue_warning_captured` points to a reasonable location and, depending on the context, not a location deep inside pytest's internals that may confuse users.
> Add acceptance tests for "config warnings" stacklevel (#4445)

- changelog/5975.deprecation.rst
- doc/en/deprecations.rst
- doc/en/example/nonpython/conftest.py
- doc/en/example/py2py3/conftest.py
- src/_pytest/deprecated.py
- src/_pytest/doctest.py
- src/_pytest/main.py
- src/_pytest/nodes.py
- src/_pytest/pytester.py
- src/_pytest/python.py
- src/_pytest/unittest.py
- testing/deprecated_test.py
- testing/python/collect.py
- testing/python/integration.py
- testing/python/metafunc.py
- testing/test_collection.py
- testing/test_mark.py
- testing/test_pluginmanager.py
this pr experiments  with introducing a `Node.from_parent` api that is to replace the smart constructors eventually
it will take a while manifest this experiment
> Node from parent
