pytest-dev/pytest

src/_pytest/python.py

It might be worth including the error there, but it gets chained, so it's
ok I assume.

_idval: remove trailing newline from exception

---

tox.ini

`--keep-going` makes sense with `-W` to see all warnings/errors.
`{posargs:}` is useful for passing in custom args.

tox: docs: --keep-going and posargs

---

CHANGELOG.rst

As per https://github.com/pytest-dev/pytest/pull/5914#issuecomment-556063975

Add link to testdir fixture in CHANGELOG entry

---

src/_pytest/pytester.py
testing/test_pdb.py
testing/test_terminal.py

Sets `PY_COLORS=0` in the environment by default, which is used by pylib.
Via https://github.com/blueyed/pytest/pull/58

pytester: use no colors with inline runs by default

---

CHANGELOG.rst
changelog/5914.bugfix.rst
changelog/6082.bugfix.rst
changelog/6231.improvement.rst
changelog/6254.bugfix.rst
changelog/6255.bugfix.rst
changelog/6257.improvement.rst
doc/en/announce/index.rst
doc/en/announce/release-5.3.1.rst
doc/en/example/parametrize.rst
doc/en/example/reportingdemo.rst
doc/en/example/simple.rst
doc/en/getting-started.rst

Preparing release version 5.3.1

---

changelog/4639.feature.rst
src/_pytest/assertion/rewrite.py
testing/test_warnings.py

Revert "A warning is now issued when assertions are made for `None`"

---

changelog/6290.bugfix.rst
src/_pytest/cacheprovider.py
testing/test_cacheprovider.py

Ensure cache supporting files still exist after --cache-clear

---

.pre-commit-config.yaml
src/_pytest/_code/code.py
src/_pytest/_code/source.py
src/_pytest/assertion/rewrite.py
src/_pytest/compat.py
src/_pytest/recwarn.py

Release notes:
https://mypy-lang.blogspot.com/2019/11/mypy-0.html
Can remove existing workarounds, but unfortunately need to add some new ones.

Update mypy 0.740 -> 0.750

---

doc/en/reference.rst

This PR fixes a minor typo in the documentation of the `capfd` fixture.

Fix typo in documentation of capfd fixture

---

changelog/6301.bugfix.rst
src/_pytest/config/__init__.py
testing/test_config.py

Fix assertion rewriting module detection for egg dists

---

CHANGELOG.rst
changelog/5477.bugfix.rst
changelog/6044.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-4.6.7.rst
doc/en/example/simple.rst

Release version 4.6.7

---

doc/en/backwards-compatibility.rst

we have a number of structural changes ahead in Node Structure, fixture internals, as well as many other detail api's
as such i wanted to propose a update to our deprecation policy that enables sorting those out in a coordinated way when transitional apis are not sustainable.

Deprecation policy - insert considerations for breaking changes

---

README.rst
doc/en/index.rst

Fixes #6326: Typo in the Security section docs home page.

---

AUTHORS
changelog/4597.feature.rst
doc/en/capture.rst
src/_pytest/capture.py
src/_pytest/compat.py
testing/acceptance_test.py
testing/test_capture.py

- Thanks for submitting a PR, your contribution is really appreciated!
- Here is a quick checklist that should be present in PRs.
- Unless your change is trivial or a small documentation fix (e.g., a typo or reword of a small section) please:
Add tee-stdio capture mechanism to allow both live printing and capturing of test output.

#4597: tee-stdio capture method

---

changelog/5471.feature.rst
src/_pytest/junitxml.py
testing/test_junitxml.py

Add hostname and timestamp to JUnit XML testsuite tag
Conflicts:
testing/test_junitxml.py
Requested from https://github.com/pytest-dev/pytest/issues/5471#issuecomment-563500493

[4.6] Add hostname and timestamp to JUnit XML testsuite tag (#5692)

---

AUTHORS
changelog/5430.bugfix.rst
src/_pytest/junitxml.py
testing/test_junitxml.py

This PR fixes a bug that does not allow logs for failed test to be passed to junit report in case the test fails during the `call` phase.

Bugfix 5430 pass logs to junit report

---

changelog/6334.bugfix.rst
src/_pytest/terminal.py
testing/test_terminal.py

@RonnyPfannschmidt do you remember why `-r` supports both `s/S` and `f/F`? I can't really trace it back in the Git history as the related code has been moved around quite a bit.
Fix #6334

Make 'S' and 'F' aliases to 's' and 'f' respectively

---

changelog/6340.trivial.rst
setup.py

On Dec 6, 2019 colorama released version 0.4.2 which dropped Python 3.4 support. This trivial change ensures the colorama version used is <=0.4.1, the last version that supports Python 3.4.
This targets the `4.6-maintenance` branch instead of `master`, because the newer versions of pytest don't need to worry about dependencies dropping Python 3.4 support.
I think the change is trivial?

Ensure colorama version is no newer than 0.4.1

---

src/_pytest/deprecated.py

Improve warning about incoming change to 'junitxml_family' default

---

AUTHORS
changelog/6350.trivial.rst
src/_pytest/python.py

While using pytest-repeat, I noticed the previous implementation is slow
for a large number of duplicate test ids. To optimize, this commit
reduces the amount of data copied and avoids using `in` with List
(unhashable type, and therefore is very slow for many elements).

Optimized renaming of test parameter ids 

---

changelog/3238.deprecation.rst
doc/en/deprecations.rst
src/_pytest/deprecated.py
src/_pytest/logging.py
testing/deprecated_test.py

Deprecated the --no-print-logs option.
Added 2 unit tests, for ini and command line.
Added 3238.deprecation.rst file.
Updated the deprecations.rst doc.
--Recreated PR as i messed up the old one

Deprecate no print logs

---

doc/en/pythonpath.rst

The order of invocations 'python -m pytest' and 'pytest' are different in the header and the explanation. Me being lazy reading about the behaviour of 'former' looked up quickly the title and rushed to implementation to discover it actually works the other way - as stated in the documentation. So I propose to switch the order in the title to achieve consistent ordering and not confusing somebody like me again! :)

invocation in last section 'pythonpath.rst' title swapped

---

.github/workflows/main.yml

This includes our current full matrix (windows, linux and macos), for evaluting
purposes.
We should disconsider failures when evaluating PRs.
TODO:
- deploy
- coverage
- github release notes
Even with the above missing, I still believe it would be nice to merge
this and have GitHub actions working in parallel so we can evaluate performance
and usability from now on.
Unfortunately due to the way GitHub actions work, the jobs are not triggered until GitHub actions are enabled on `master`, but the results of this build can be seen here:
https://github.com/nicoddemus/pytest/pull/11

Add GitHub actions for CI

---

changelog/6301.bugfix.rst
src/_pytest/config/__init__.py
testing/test_config.py

Backport fix for #6301 to 4.6-maintenance branch.

[4.6] Fix assertion rewriting module detection for egg dists

---

testing/test_runner.py

Hi! 
As you are removing the Python 2.7 support I think this check isn't necessary any more.
This is my first PR submitted to `pytest` so if you need me to do something just tell me. :)

delete inspect.getargspect() as is deprecated since Python 3.0

---

doc/en/warnings.rst

* Rearrange section about context manager to be in order
* Link to `pytest.warns` and `recwarn` since a reader going top to bottom won't have seen about those yet.

Improve warnings docs

---

azure-pipelines.yml

---
Python 3.8 has just been added to Azure Pipelines
* https://github.com/microsoft/azure-pipelines-image-generation/issues/1317#issuecomment-551965427
Does this go in `master` or `features`? I guess it's an improvement, so `features`.
Does this need a changelog file? I guess not, but let me know if otherwise.

Azure Pipelines: Test on Python 3.8

---

changelog/6532.bugfix.rst
src/_pytest/pytester.py
testing/test_pytester.py

- Fix error introduced on #5990 
Fixes: #6352

pytester: quick fix error introduced in #5990

---

src/_pytest/config/__init__.py

Done in a02310a140 (likely automatic), but loses information of the
comment obviously.

Revert black formatting of essential_plugins

---

.pre-commit-config.yaml
src/_pytest/_code/source.py
src/_pytest/assertion/__init__.py
src/_pytest/doctest.py
src/_pytest/pytester.py
src/_pytest/recwarn.py
src/_pytest/reports.py
src/_pytest/runner.py
testing/code/test_source.py

This fixes some type: ignores due to typeshed update.
Newer mypy seem to ignore unannotated functions better, so add a few
minor annotations so that existing correct type:ignores make sense.

Update mypy 0.750 -> 0.761

---

changelog/6532.bugfix.rst
src/_pytest/pytester.py
testing/test_pytester.py

/cc @mulatinho
follow-up to #6353 (for #6352)

Fix `RunResult.parseoutcomes` (follow-up to #6353)

---

CHANGELOG.rst
changelog/6301.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-4.6.9.rst

Shall we do the last core-supported python 2.x release?

Preparing release version 4.6.9

---

doc/en/py27-py34-deprecation.rst

I've updated the text and incorporated the topics from #5275, so this
can now be part of the official docs, and #5275 can be closed/unpinned.
Closes #5275

Update py27/py34 deprecation docs

---

changelog/6404.trivial.rst
src/_pytest/_code/source.py
testing/code/test_source.py

Besides unused, it uses the (deprecated in Python 3.9) parser module
Fix #6404

Remove unused _pytest.code.Source.isparseable function

---

changelog/6404.trivial.rst
src/_pytest/_code/source.py

Backport: https://github.com/pytest-dev/pytest/pull/6407

[4.6] Remove usage of parser module, deprecated in Python 3.9

---

changelog/6404.trivial.rst
src/_pytest/_code/source.py
testing/code/test_source.py

Remove usage of parser module (deprecated in Python 3.9)

---

.pre-commit-config.yaml

Should the black version be the same as that is being in use by the black hook?

Unifying black version in pre-commit config file

---

changelog/5971.bugfix.rst
src/_pytest/reports.py
testing/test_reports.py

Tracebacks coming from remote processes crated by the multiprocess module
will contain "RemoteTracebacks" which don't have a 'reprcrash' attribute.
I've made sure to test this fixes in xdist.
Fix #5971

Fix serialization of 'None' reprcrashes

---

src/_pytest/cacheprovider.py
testing/test_cacheprovider.py

Noticed this with https://github.com/pytest-dev/pytest/pull/6409, where `items` is stored/used as-is when there are no "deselected" stats yet.

cacheprovider: pytest_collection_modifyitems: copy items

---

doc/en/changelog.rst
doc/en/reference.rst

Both references were referencing links from Python because of our intersphinx
mapping in `conf.py`:
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
Because Python's docs explicitly define both references, Sphinx fallbacks to
them instead of generating implicit references as was expected.
Found the two references in this PR by commenting the line above in `conf.py`.
Fix #6397

Fix wrong 'changelog' and 'reference' links in docs

---

changelog/449.improvement.rst
src/_pytest/terminal.py
testing/test_terminal.py

Closes https://github.com/pytest-dev/pytest/issues/449.

terminal: use "yellow" with any "xpassed" tests

---

.pre-commit-config.yaml
src/_pytest/_code/code.py
src/_pytest/assertion/__init__.py
src/_pytest/assertion/rewrite.py
src/_pytest/compat.py
src/_pytest/doctest.py
src/_pytest/pytester.py
src/_pytest/reports.py
src/_pytest/runner.py
testing/code/test_source.py

This makes it easier to use the same (current) mypy across branches.

[WIP/RFC] master: update mypy 0.740 -> 0.761

---

.travis.yml
src/_pytest/compat.py
testing/python/raises.py

Python 3.5.0 caused flaky failures before
(https://github.com/pytest-dev/pytest/issues/5795), hopefully this is
more stable.
This is pulled out of https://github.com/pytest-dev/pytest/pull/6435,
which adds code specific for Python < 3.5.2, and therefore it makes
sense to test it.

ci: Travis: Python 3.5.1 via Trusty

---

.pre-commit-config.yaml
setup.py
tox.ini

This is different from what pre-commit (in "linting") runs in that it
uses our config (alone), and stubs from dependencies.
It would make sense to run this on CI additionally (since there is no
"pre-commit --skip mypy", and a separate config is not worth it).
Currently it triggers a false positive though anyway
(https://github.com/erikrose/more-itertools/pull/374).

tox: add mypy toxenv

---

changelog/2780.bugfix.rst
src/_pytest/terminal.py
testing/test_terminal.py

Fixes https://github.com/pytest-dev/pytest/issues/2780.

terminal: summary_passes: handle teardown sections

---

testing/test_compat.py

Via https://github.com/pytest-dev/pytest/pull/6435.

tests: cover safe_getattr

---

AUTHORS
changelog/6436.bugfix.rst
src/_pytest/fixtures.py
testing/python/fixtures.py

Closes #6436 
Turns out the root cause was because fixtures were only considering the fixtures requested in their argnames when trying to find out where to register their finalizers at execute time. They weren't considering autouse fixtures, so when this was combined with parameterization, this resulted in fixtures not being torn down when a parameterized, autouse fixture was being torn down to go from one param set to the next.
This also resulted in fixtures being torn down out of order in extreme cases. You can see an example of this in the test that I added (if you run it without this fix).
The solution ultimately required me to have fixtures register their finalizers with all fixtures that came before them in the stack. This list of fixtures came from using `request.fixturenames` in …

Fixtures now register finalizers with all fixtures before them in the stack

---

AUTHORS
changelog/6469.feature.rst
doc/en/reference.rst
src/_pytest/junitxml.py
testing/acceptance_test.py
testing/test_junitxml.py

The purpose for this PR is enabling user to set what should be contained in generated xml file since for some (me included) this file is used only for report generation, hence log/out/err are not always welcome, and can take lots of space.
User can pick between no|log|system-out|system-err|out-err|all in order to put selected output in xml file.

Allow user to select if he wants log, std-out/err in junit capture xml file, and respect his decision

---

.coveragerc
doc/en/conf.py
src/_pytest/_code/code.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/config/findpaths.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/nodes.py
src/_pytest/outcomes.py
src/_pytest/pytester.py
src/_pytest/python_api.py
src/_pytest/recwarn.py
src/_pytest/runner.py
src/_pytest/warning_types.py

This allows for e.g. Jedi to infer types.
It was only used to support Python 3.5.0/3.5.1, where this is available
in `typing_extensions`.
Ref: https://github.com/davidhalter/jedi/issues/1472
TODO:

Use TYPE_CHECKING instead of False

---

testing/test_reports.py

Somehow in Python 3.5 on Windows this test fails with:
File "c:\hostedtoolcache\windows\python\3.5.4\x64\Lib\multiprocessing\connection.py", line 302, in _recv_bytes
overlapped=True)
OSError: [WinError 6] The handle is invalid
This only happens in this platform and Python version, decided to use
a dummy traceback as originally done in #6412.
(cherry picked from commit b9c136b809a33009ad514672666c515953957b33)

[master] Use a dummy RemoteTraceback for test in Python 3.5 Windows

---

doc/en/customize.rst

Ref: https://github.com/pytest-dev/pytest/issues/6376
(had this in a stash from looking at it the other day)

doc: revisit section about rootdir

---

AUTHORS
changelog/6384.improvement.rst
src/_pytest/_code/code.py
testing/test_terminal.py

Enable showing local variables when asked to do so in the short
traceback mode.
Fixes #494
Looks like this in practice:
```
$ python3 -mpytest scipy/_lib/tests/test__util.py --tb=short -l
...
================================ FAILURES =================================
___________________________ test__aligned_zeros ___________________________
scipy/_lib/tests/test__util.py:49: in test__aligned_zeros
check(shape, dtype, order, align)
align      = 1
check      = <function test__aligned_zeros.<locals>.check at 0x7f866a141560>
dtype      = <class 'numpy.uint8'>
j          = 0
n          = 0
niter      = 10
order      = 'C'
shape      = 0
scipy/_lib/tests/test__util.py:22: in check
assert dtype is None
E   AssertionError: assert <class 'numpy.uint8'> is None
align      = 1
dtype      = <class …
```

Make --showlocals work together with --tb=short

---

.travis.yml

GitHub actions already should deploy.
This is a stop gap while we figure out why coverage dropped
when removing Travis builds in #6470

Drop deploy from Travis in favor of GitHub actions

---

src/_pytest/pytester.py

~~Waiting on https://github.com/davidhalter/jedi/issues/1472.~~
Blocked by https://github.com/pytest-dev/pytest/pull/6435.

pytester: typing for `spawn`/`spawn_pytest`

---

scripts/release.py

Happens with newer pyflakes (https://github.com/pytest-dev/pytest/pull/6483).

scripts/release.py: lint: fix F999

---

testing/test_capture.py

Ignore warnings from e.g. hypothesis.

tests: fix test_crash_on_closing_tmpfile_py27

---

.travis.yml

This helps with regard to slowness until
https://github.com/pytest-dev/pytest/pull/6470 is resolved.

ci: Travis: remove non-coverage jobs

---

testing/code/test_excinfo.py

This might fail unnecessarily with a (wrong) determined version of e.g.
"4.7.dev307+ge98176cf5" (no patch version).
Ref: https://github.com/pytest-dev/pytest/pull/6506

tests: test_excinfo: remove unused pytest_version_info

---

src/_pytest/_code/code.py
src/_pytest/runner.py

Ref: https://github.com/blueyed/pytest/pull/163
TODO:

typing: fix _TracebackStyle

---

src/_pytest/_code/code.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/nodes.py
testing/code/test_excinfo.py

Taken out of https://github.com/pytest-dev/pytest/pull/6449.

typing: minor improvements

---

src/_pytest/config/argparsing.py
src/_pytest/config/findpaths.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/nodes.py
testing/python/collect.py

This is in preparation for adding type stubs to `py`. See https://github.com/pytest-dev/py/pull/232.
These changes make mypy clean both before and after.

Fix type errors after adding types to the `py` dependency

---

src/_pytest/_code/code.py
src/_pytest/_code/source.py
src/_pytest/recwarn.py
src/_pytest/reports.py
testing/code/test_source.py
testing/test_pytester.py
testing/test_recwarn.py
testing/test_runner.py

The first two commits mostly finish annotating `_pytest/code/`.
The other commits fix `check_untyped_defs` errors in a few test files. This discovered a couple of problems in the annotations, which are fixed.
Most of the diff is adding `-> None` to test functions. Also, because of a deficiency in mypy, exceptions defined on functions e.g. `pytest.fail.Exception` don't work, so I replace them with the direct classes instead.

Some type annotation & check_untyped_defs fixes

---

src/_pytest/config/argparsing.py
src/_pytest/config/findpaths.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/nodes.py
testing/python/collect.py
testing/test_nose.py

This reverts commit 930a158a6a4d58ceb37aff97fa476215a68c915e (pr #6510).
Fixes #6517.
The assert is failing on a real test suite. Basically, I was sure the assert was safe because the  `_node_location_to_relpath` cache that the value is passed into is only designed to work with `py.path.local`s, not `str`s, and code-wise if given an `str`, it would fail. *Or so I thought*. Turns out several less-than-nice things combined to mislead me:
1. The `py.path.local` function `bestrelpath` is wrapped in a giant `try...except AttributeError` which masks any wrong types.
2. `py.path.local` has an `__eq__` implementation that can compare true with an `str`: `py.path.local('/foo') == '/foo'` is true.
3. The cache seems to always be warmed up with a `py.path.local`, so the `bestrelpath` code actually …

Fix internal assert failure regression in 5.3.4

---

.github/workflows/main.yml

Following jobs get aborted on failure.
Ref: https://github.com/pytest-dev/pytest/pull/6530

ci: GHA: remove unnecessary check for `success()`

---

testing/test_cacheprovider.py

Ref: https://github.com/pytest-dev/pytest/pull/6296

--cache-clear: add test for keeping non-supporting files

---

tox.ini

This allows for `tox -e doctesting-coverage`, which would otherwise not
use the "doctesting" testenv.

tox: move doctesting into main testenv

---

src/_pytest/pytester.py
testing/test_pytester.py

Without restoring the cwd, successive tests might fail to parse the
config (via `_pytest.config._prepareconfig()`, for when `--lsof` is
used).
And it is good practice to restore the cwd in any case anyway.

tests: fix test_cwd_snapshot

---

src/_pytest/main.py

Also rename the variable to convey its intent better

Clear node collection cache after collection is done

---

src/_pytest/main.py

Pulled out of https://github.com/pytest-dev/pytest/pull/6491.

typing: Session.__init__

---

testing/test_junitxml.py

`-rv` is not a recognized reportchar.  Probably `-v` was meant, but is
not necessary to check there are no warnings.
Followup to 2018cf12b (https://github.com/pytest-dev/pytest/pull/3360).

tests: fix/harden test_record_property

---

testing/python/collect.py
testing/test_assertion.py
testing/test_cacheprovider.py
testing/test_junitxml.py
testing/test_pluginmanager.py

Warnings are enabled by default, which is tested by `test_getreportopt`.
Ref: https://github.com/pytest-dev/pytest/pull/6524

tests: remove unnecessary `-rw` option

---

src/_pytest/compat.py
src/_pytest/config/argparsing.py
src/_pytest/config/findpaths.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/python.py
testing/test_nose.py

This should probably get transferred into a `pytest.fail` really, but
tests/documents the current behavior.

tests: improve test for `nose.raises`

---

.pre-commit-config.yaml
src/_pytest/_code/code.py
src/_pytest/_io/__init__.py
src/_pytest/cacheprovider.py
src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/reports.py
testing/code/test_excinfo.py
testing/logging/test_formatter.py

This also imports `TerminalWriter` explicitly, allowing for easier
phasing out / replacing of it (via the import, which then could go
through the `_pytest.compat` module).
Note to self:
```
pick b34f07360 config: typing for create_terminal_writer
pick 443335426 Import TerminalWriter from `py.io`
```

config: typing for create_terminal_writer, re-export TerminalWriter

---

.github/workflows/main.yml
.travis.yml
scripts/report-coverage.sh

This would help with debugging missing coverage when removing Travis
jobs.

ci: codecov: add flag for GHA

---

.github/workflows/main.yml

It helps to know upfront that e.g. linting failed, and makes finding the
error easier.

ci: GHA: separate jobs for linting, docs, doctesting

---

.github/workflows/main.yml

This allows for more control, e.g. `-X fix` with codecov-bash, and it has all the coverage-calls we need already etc.

ci: GHA: use scripts/report-coverage.sh

---

.travis.yml

This is handled by GHA already, and not affected/required for coverage.

ci: Travis: removing linting,docs,doctesting

---

testing/python/fixtures.py

This is a regression test for part of
https://github.com/pytest-dev/pytest/issues/6492, testing one of the
fixes in https://github.com/pytest-dev/pytest/pull/6551.

tests: add test_fixture_arg_ordering

---

doc/en/fixture.rst

This is considered to be best practice, and should be used in docs
therefore.

doc/en/fixture.rst: chdir back to previous directory

---

AUTHORS
changelog/6557.bugfix.rst
src/_pytest/capture.py
testing/test_capture.py

Stream write() methods should/may return the number of characters or bytes written. Encoded file needlessly discarded the value returned from the wrapped stream write.
Fixes #6557

Make EncodedFile.write() return the return value from inner write()

---

src/_pytest/main.py
testing/test_collection.py

Previously, `_initialparts` was a list whose first item was a
`py.path.local` and the rest were `str`s. This is not something that
mypy is capable of modeling. The type `List[Union[str, py.path.local]]`
is too broad and would require asserts for every access.
Instead, make each item a `Tuple[py.path.local, List[str]]`. This way
the structure is clear and the types are accurate.

Refactor Session._initialparts to have a more explicit type

---

codecov.yml

The changes status is quite buggy, remove it for now.
This just uses "comment: off" then.

ci: codecov: only use "comment: off"

---

src/_pytest/main.py

Mypy complains about this once the function is typed:
```
src/_pytest/main.py:85: error: "_addoption" of "OptionGroup" does not return a value
src/_pytest/main.py:133: error: "addoption" of "OptionGroup" does not return a value
```

Remove a couple of redundant commas

---

testing/test_config.py

Ref: https://github.com/pytest-dev/pytest/pull/6443

tests: add test_plugin_loading_order

---

scripts/report-coverage.sh

While it might not help with the following, it certainly might happen as
well.
```
+ curl -S -L --connect-timeout 5 --retry 6 -s https://codecov.io/bash -o codecov-upload.sh
curl: (16) Error in the HTTP2 framing layer
```

ci: codecov: use `--retry-connrefused` with curl

---

testing/logging/test_reporting.py

Might be slow on CI.
Ref: https://github.com/pytest-dev/pytest/pull/6570/checks?check_run_id=408752475#step:6:109

tests: test_collection_collect_only_live_logging: allow for 1+s

---

changelog/6566.bugfix.rst
src/_pytest/capture.py
testing/test_capture.py

This is implemented by IOBase already, which additionally checks if the
stream is not closed, and calls `write` per line.
Ref/via: https://github.com/pytest-dev/pytest/pull/6558#issuecomment-578210807
TODO:

Fix `EncodedFile.writelines`

---

src/_pytest/_code/code.py

Fixes:
> src/_pytest/_code/code.py:83: error: Incompatible types in assignment
>   (expression has type "str", variable has type "local")  [assignment]

typing: fix Code.path

---

src/_pytest/python_api.py

Fixed in https://github.com/erikrose/more-itertools/pull/374.
Verified that `mypy --warn-unused-ignores src/_pytest/python_api.py` with
more-itertools master catches it (i.e. states that it is not required anymore).

typing: ignore false positive with more-itertools

---

src/_pytest/main.py

Previously, this cache was used with 3 different and mutually exclusive key-type -> value-type combinations. Mypy can't properly type this. It's also quite confusing.
Split to 3 different dicts instead.

Split Session._collection_node_cache to 3 mutually exclusive parts

---

.github/workflows/main.yml

This often might be causing for jobs to take longer than 10 minutes,
which is a timeout Codecov uses to wait for successful CI.
Also it is good in general to have CI finish faster, of course.

ci: GHA: run less jobs with coverage

---

testing/test_pytester.py

Ref: https://github.com/pytest-dev/pytest/pull/6578#discussion_r371035867

pytester: test for _makefile joining an absolute path

---

changelog/6454.bugfix.rst
changelog/6454.feature.rst
doc/en/usage.rst
src/_pytest/terminal.py
testing/test_terminal.py

Fixes https://github.com/pytest-dev/pytest/issues/6454

terminal: default to `fE` with `-r` (reportchars)

---

doc/en/getting-started.rst

From the description it seemed to me as if just prefixing your methods with ``test_`` was enough, but you also need to prefix your class with ``Test``. Of course, in the reference material this is clearly stated, but I think it makes sense to mention it here as well, since you also mention the part about the methods' prefix.

doc: getting-started.rst: mention "Test" prefix for classes

---

changelog/6597.bugfix.rst
src/_pytest/python.py
testing/python/collect.py

I went with `features` as this changes the node ids -- I could target master instead if this is desirable as a bugfix.
partially fixes #6597

Fix node ids which contain a parametrized empty-string variable

---

testing/test_terminal.py

Taken out of https://github.com/pytest-dev/pytest/pull/6599.

tests: harden test_teardown_many_verbose

---

testing/code/test_code.py
testing/code/test_source.py

It should be in `test_code` when testing `_pytest._code.getfslineno`,
not to be confused with `_pytest._code.source.getfslineno`.
Adds an extra assert (via https://github.com/pytest-dev/pytest/pull/6590).

tests: move test_getfslineno

---

changelog/5975.deprecation.rst
src/_pytest/doctest.py
src/_pytest/nodes.py
src/_pytest/python.py
testing/python/collect.py
testing/test_nodes.py

Fix 6341 disallow session config in fromparent

---

scripts/publish-gh-release-notes.py

- [n/a] Include documentation when adding new features.
- [n/a] Include new tests or update existing tests when applicable.
- [n/a?] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
--- …

Docs: Don't wrap the markdown for GitHub releases

---

testing/code/test_code.py
testing/code/test_source.py

Reverts https://github.com/pytest-dev/pytest/pull/6610.
The tested `getfslineno` is `src/_pytest/_code/source.py` actually,
exported via `src/_pytest/_code/__init__.py`.
I've confused it with the one in `src/_pytest/compat.py` apparently.

tests: move test_getfslineno back

---

src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/python.py

Package: typing, cleanup

---

doc/en/fixture.rst

I stumbled over the wording here a bit, and I thought this would make it read a little easier.
I'm not sure if I need a `changelog` entry for this. Obviously, there is no issue to attribute it to. Let me know if that is necessary.

Reword fixture docs for clarity

---

scripts/report-coverage.sh

Not known with `curl` on Travis at least.
Reverts https://github.com/pytest-dev/pytest/pull/6573.
This reverts commit df1f43ee28d38350542a23acb27647feab46f473.

Revert "ci: codecov: use `--retry-connrefused` with curl"

---

src/_pytest/assertion/__init__.py
src/_pytest/hookspec.py
src/_pytest/logging.py
src/_pytest/main.py
src/_pytest/terminal.py
src/_pytest/warnings.py

Not included in https://github.com/pytest-dev/pytest/pull/6556, but conflicts (trivially).

typing: pytest_collection

---

src/_pytest/fixtures.py

This gets typically used always (via `getfixtureinfo`).

fixtures: move import of ParameterSet to top level

---

tox.ini

`-fE` is the default in `features` now [1], but the idea is to add `X`
also to it in the long run, so let's dogfood it ourselves.
1: https://github.com/pytest-dev/pytest/pull/6524
2: https://github.com/pytest-dev/pytest/pull/6524#issuecomment-577650703

tests: use `-rfEX`

---

doc/en/fixture.rst
scripts/publish-gh-release-notes.py
scripts/report-coverage.sh
src/_pytest/assertion/__init__.py
src/_pytest/compat.py
src/_pytest/fixtures.py
src/_pytest/hookspec.py
src/_pytest/logging.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/python.py
src/_pytest/terminal.py
src/_pytest/warnings.py
tox.ini

Part of #6571 transition plan. I am doing this merge so that the *reverse* merge (coming up shortly) is clean.

Merge master to features - one last time

---

changelog/6637.breaking.rst
src/_pytest/hookspec.py

This hook has been deprecated for more than 10 years (https://github.com/pytest-dev/pytest/commit/a2fe6714f860dfffb657d423355d6c644ccb7550) and has not even
being called by pytest in a long time.

Remove deprecated 'pytest_itemstart' hook

---

src/_pytest/python.py

`Function` creates a `_fixtureinfo` already:
https://github.com/pytest-dev/pytest/blob/fed535694/src/_pytest/python.py#L1392-L1395

PyCollector._genfunctions: use already created fixtureinfo

---

doc/en/reference.rst

(Sorry, I seem to have mistaken the commit message box for the pull request message box, so you might want to reword the commit message.)
At least in Debian's pytest (4.6.9), only the pytestmark form works.

DOC: it's called pytestmark, not pytest_mark

---

src/_pytest/python.py

`Generator` was removed in 7eb28f9eb, and this pleases mypy to correctly
complain that `FunctionMixin` has no `config` (within
`_prunetraceback`).

Inline FunctionMixin with Function

---

.github/PULL_REQUEST_TEMPLATE.md

This way we don't need to ask everytime, and users who for some reason
would not like us to squash their commits can uncheck the box then.

Explicitly state on the PR template that we can squash commits

---

changelog/6646.bugfix.rst
src/_pytest/assertion/__init__.py
src/_pytest/config/__init__.py
src/_pytest/config/plugin.py
testing/test_assertion.py

This fixes the hook(s) not being used after `testdir.runpytest` etc.
TODO:

assertion: save/restore hooks on item

---

testing/acceptance_test.py
testing/conftest.py
testing/test_helpconfig.py
testing/test_junitxml.py
testing/test_terminal.py

Fixes https://github.com/pytest-dev/pytest/pull/4518.

testing/conftest.py: testdir: set PYTEST_DISABLE_PLUGIN_AUTOLOAD=1

---

src/_pytest/python.py

Ref: https://github.com/pytest-dev/pytest/pull/2575

Use inspect.getdoc to massage fixture docstrings

---

src/_pytest/_code/code.py
src/_pytest/_code/source.py
src/_pytest/compat.py
src/_pytest/fixtures.py
src/_pytest/mark/structures.py
src/_pytest/nodes.py
src/_pytest/python.py
testing/code/test_source.py

Everything was using `_pytest.compat.getfslineno` basically, which
wrapped `_pytest._code.source.getfslineno`.
This moves the extra code from there into it directly, and uses the
latter everywhere.
This helps to eventually remove the one in compat eventually, and also
causes less cyclic imports.

internal: clean up getfslineno

---

AUTHORS
changelog/5712.feature.rst
doc/en/example/parametrize.rst
src/_pytest/fixtures.py
src/_pytest/python.py
testing/python/collect.py
testing/python/metafunc.py

Hi, 
that's my first PR, ref. issue #5712 
The purpose of this is to enforce that every argument used in `parametrize` is explicitly declared either by corresponding test function or via `indirect` list. The example of how this is intended to work is given in documentation (added few lines to *doc/en/example/parametrize.rst*)
I target master branch because I consider it a small change/bugfix.

[parametrize] enforce explicit argnames declaration

---

changelog/6660.bugfix.rst
src/_pytest/main.py
testing/test_main.py

Similar to a7268aa (https://github.com/pytest-dev/pytest/pull/6258).

Handle `Exit` exception in `pytest_sessionfinish`

---

src/_pytest/capture.py
testing/test_capture.py

This started by looking at how to get the current test item in general,
and then I noticed that it is not necessary for the capture plugin to
track it manually in the first place.
Changes the API for `CaptureManager.*_fixture` methods (does not take item
anymore).  This could be kept / ignored if required.

capture: cleanup item fixture handling

---

testing/test_parseopt.py

Fixes collection error with Python 3.5.3 (Travis):
testing/test_parseopt.py:2: in <module>
import distutils.spawn
.tox/py35-coverage/lib/python3.5/distutils/__init__.py:4: in <module>
import imp
.tox/py35-coverage/lib/python3.5/imp.py:33: in <module>
PendingDeprecationWarning, stacklevel=2)
E   PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Build log: https://travis-ci.org/blueyed/pytest/builds/648305304

test_argcomplete: remove usage of `distutils.spawn`

---

src/_pytest/fixtures.py

Not used since 4f0879ff9b3e7ad0da1839131c35b4e6412b972f.

Remove unused field FixtureManager._arg2finish

---

src/_pytest/helpconfig.py
src/_pytest/runner.py
src/_pytest/terminal.py

Fix mypy errors:
```
src/_pytest/runner.py:36: error: "addoption" of "OptionGroup" does not return a value  [func-returns-value]
src/_pytest/helpconfig.py:64: error: "addoption" of "OptionGroup" does not return a value  [func-returns-value]
src/_pytest/terminal.py:67: error: "_addoption" of "OptionGroup" does not return a value  [func-returns-value]
src/_pytest/terminal.py:75: error: "_addoption" of "OptionGroup" does not return a value  [func-returns-value]
```

Remove some redundant commas

---

src/_pytest/mark/structures.py

This class was both added and became unused during the development of a PR: https://github.com/pytest-dev/pytest/pull/3317

Remove unused NodeMarkers

---

doc/en/reference.rst
doc/en/usage.rst
src/_pytest/config/__init__.py
src/_pytest/main.py
src/_pytest/pytester.py
src/_pytest/terminal.py
src/pytest/__init__.py
testing/acceptance_test.py
testing/python/collect.py
testing/test_assertrewrite.py
testing/test_cacheprovider.py
testing/test_capture.py
testing/test_collection.py
testing/test_config.py
testing/test_conftest.py
testing/test_helpconfig.py
testing/test_main.py
testing/test_mark.py
testing/test_pluginmanager.py
testing/test_pytester.py
testing/test_runner.py
testing/test_session.py
testing/test_setuponly.py
testing/test_terminal.py
testing/test_unittest.py

ExitCode is used in several internal modules and hooks and so with type
annotations added, needs to be imported a lot.
_pytest.main, being the entry point, generally sits at the top of the
import tree.
So, it's not great to have ExitCode defined in _pytest.main, because it
will cause a lot of import cycles once type annotations are added (in
fact there is already one, which this change removes).
Move it to _pytest.config instead.
_pytest.main still imports ExitCode, so importing from there still
works, although external users should really be importing from `pytest`.

Move ExitCode's definition from _pytest.main to _pytest.config

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/main.yml
.pre-commit-config.yaml
.travis.yml
CONTRIBUTING.rst
RELEASING.rst
doc/en/development_guide.rst
doc/en/py27-py34-deprecation.rst

This RFC proposes changes to pytest's git workflow, with the aim of streamlining development.
There are two branches, `master` and `features`.
CONTRIBUTING.md and the pull request template instruct contributors to
- Target `master` for bug fixes/doc changes/trivial changes.
- Target `features` for new features/improvements/functionality changes/removals/deprecations.
Patch releases are made by branching from `master`, making the release and merging back to `master` in the release PR.
Minor releases are made by branching from `features`, merging `master`, making the release and merging back to `master` in the release PR.
Occasionally, changes that pile up in `master` are merged back into `features` with a "Merge master into features" PR.
Contributors need to make a choice to target either …

RFC: Streamlining pytest's git workflow

---

src/_pytest/capture.py

Follow-up to https://github.com/pytest-dev/pytest/pull/6663.

doc for _capturing_for_request

---

testing/python/approx.py

Was globbed for Python 2 before (57c448991).

tests: test_unicode_plus_minus: use unicode sign directly

---

changelog/6737.breaking.rst
src/_pytest/fixtures.py
src/_pytest/hookspec.py
src/_pytest/setuponly.py

Previously `cached_result` was either set or deleted. Type annotations cannot handle this, so use `None` for the non-set state instead.

Don't delete FixtureDef.cached_result, set it to None instead

---

src/_pytest/_code/code.py
src/_pytest/reports.py

This helps with skipping "private" properties there.

reports: use attr.asdict with serialize_repr_{crash,traceback}

---

src/_pytest/cacheprovider.py
src/_pytest/warnings.py
testing/test_cacheprovider.py
testing/test_warnings.py

Allows for filtering of PytestCacheWarning.
Using `_issue_warning_captured` is not necessary here, and was probably
only used because the cacheprovider misses warnings during
`pytest_sessionfinish`, which is also fixed here.
I think the usage of `_issue_warning_captured` can be removed/reduced
further, but also that this is good enough for now.
Ref: https://github.com/pytest-dev/pytest/issues/6681.

cacheprovider: use warnings directly

---

.coveragerc
src/_pytest/runner.py

Using getattr doesn't work with typing, and also breaks grep. It took me a while to find where these hooks are called.

Avoid getattr when dispatching pytest_runtest_* hooks

---

changelog/6742.doc.rst
doc/en/fixture.rst

I would like to hyperlink just the first word, "Fixtures", but I don't think this is possible with RST  given that there is a pre-existing link target called "fixtures".

Expand first sentence on fixtures into a paragraph

---

src/_pytest/doctest.py
src/_pytest/nodes.py
src/_pytest/python.py

Every Item must implement this method (called on all items collected in a session). Add a stub for typing and clarity.

Add Item.runtest stub implementation

---

src/_pytest/compat.py
src/_pytest/python.py
testing/python/metafunc.py

Type annotate Metafunc

---

doc/en/writing_plugins.rst

Follow-up to b09762d (#6705).
Ref: https://github.com/pytest-dev/pytest/pull/6705#discussion_r379819573

doc: fix test with link to `python_files`

---

testing/test_cacheprovider.py

It was not previously checking for the line number also (02aa8ad), and this is
obviously wrong (affected by changes to the file).
Unblocks https://github.com/pytest-dev/pytest/pull/6448.

Do not use fixed line number with test_cache_failure_warns

---

changelog/310.bugfix.rst
src/_pytest/doctest.py
testing/test_doctest.py

Fixes using `pytest.xfail()` and `pytest.importorskip()` in doctests.

doctest: handle any OutcomeException

---

AUTHORS
doc/en/skipping.rst

Based on the discussions linked in [open issue #6289 ](https://github.com/pytest-dev/pytest/issues/6289#issuecomment-559775183), I added an additional example to the `xfail` documentation.

#6289: Add new example to XFAIL documentation

---

src/_pytest/terminal.py

Ref: https://github.com/blueyed/pytest/commit/cf0cac3b7#r37373455
I think this makes it clear that `writer` is preferred (for internal use).
Not removing `_tw` for now unnecessarily.

terminal: remove confusing comment about `_tw`

---

src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/outcomes.py
src/_pytest/reports.py
testing/python/collect.py
testing/python/metafunc.py
testing/test_pytester.py
testing/test_recwarn.py
testing/test_runner.py

Mypy currently is unable to handle assigning attributes on function: https://github.com/python/mypy/issues/2087.
pytest uses this for the outcome exceptions -- `pytest.fail.Exception`, `pytest.exit.Exception` etc, and this is the canonical name by which they are referred.
Initially we started working around this with type: ignores, and later by switching e.g. `pytest.fail.Exception` with the direct exception `Failed`. But this causes a lot of churn and is not as nice. And I also found that some code relies on it, in skipping.py:
```py
def pytest_configure(config):
if config.option.runxfail:
import pytest
old = pytest.xfail
config._cleanup.append(lambda: setattr(pytest, "xfail", old))
def nop(*args, **kwargs):
pass
nop.Exception = xfail.Exception
setattr(pytest, "xfail", nop)
...
```
So it …

Use a hack to make typing of pytest.fail.Exception & co work

---

changelog/5301.bugfix.rst
src/_pytest/cacheprovider.py
src/_pytest/config/__init__.py
testing/test_cacheprovider.py

Fixes https://github.com/pytest-dev/pytest/issues/5301
Two subplugins are necessary due to limitations in pluggy (https://github.com/pytest-dev/pluggy/pull/246).
TODO:

LFPlugin: use sub-plugins to deselect during collection

---

src/_pytest/capture.py
testing/test_capture.py

Especially for `_old`, which was still used unchecked in `__repr__`.

capture: do not delete attributes

---

src/_pytest/cacheprovider.py

Fixes:
> Argument 1 to "Path" has incompatible type "Union[local, Any]";
> expected "Union[str, _PathLike[str]]"  [arg-type]
Ref: https://github.com/pytest-dev/py/pull/232#pullrequestreview-349549522

cacheprovider: fix typing with Path(py.path.local)

---

testing/test_faulthandler.py

Use a longer timeout on CI - seen a failure with it with GHA (Windows).

tests: fix flaky test_timeout

---

src/_pytest/main.py

Ref: https://github.com/pytest-dev/pytest/issues/6751

help: --deselect: mention that this uses node id prefixes

---

src/_pytest/config/__init__.py
testing/acceptance_test.py

Passing in a tuple crashes in `_prepareconfig`:
def test_invoke_with_tuple(self):
>       pytest.main(("-h",))
src/_pytest/config/__init__.py:82: in main
config = _prepareconfig(args, plugins)
src/_pytest/config/__init__.py:229: in _prepareconfig
return pluginmanager.hook.pytest_cmdline_parse(
…
src/_pytest/helpconfig.py:98: in pytest_cmdline_parse
config = outcome.get_result()  # type: Config
src/_pytest/config/__init__.py:808: in pytest_cmdline_parse
self.parse(args)
src/_pytest/config/__init__.py:1017: in parse
self._preparse(args, addopts=addopts)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
def _preparse(self, args: List[str], addopts: bool = True) -> None:
…
if addopts:
ini_addopts = self.getini("addopts")
if ini_addopts:
> …

main: `args` must be a list, not tuple

---

src/_pytest/python_api.py

doc: `pytest.raises`: remove mention of removed `message`

---

changelog/6752.bugfix.rst
src/_pytest/python_api.py
testing/python/raises.py

TODO:
Fixes https://github.com/pytest-dev/pytest/issues/6752.

Handle `match` with `pytest.raises()`

---

src/_pytest/hookspec.py
src/_pytest/main.py

It should only return `True` when something is to be ignored, not
`False` otherwise typically.
This caused e.g. bad interaction with the cacheprovider (before
https://github.com/pytest-dev/pytest/pull/6448).

Fix pytest_ignore_collect hooks: do not return False

---

src/_pytest/capture.py
testing/test_capture.py

Ref: https://github.com/pytest-dev/pytest/pull/6671#issuecomment-588408992
TODO:

capture: factor out _get_multicapture

---

testing/test_config.py

Originally added in a2891420d (with `TestRootdir`), but then
accidentally moved to `TestOverrideIniArgs` in 802755cee.

tests: test_config: move tests

---

src/_pytest/pytester.py

Last usage was removed in 22dc47d9f.

Remove unused `pytester.getdecoded`

---

doc/en/plugins.rst

The pytest-konira plugin has not seen an update since 2011, moreover
the "project description" on PyPI points to a dubious website that
does not actually correspond to the project and instead redirects to
advertising content.

Remove reference to old konira plugin from docs

---

src/_pytest/config/__init__.py

Last usage of it was removed in ba17363d7.
TODO:

Remove unused `setns`

---

doc/en/_templates/globaltoc.html
doc/en/conf.py

docs: generate index and add it to globaltoc sidebar

---

changelog/6795.improvement.rst
src/_pytest/config/__init__.py
testing/test_config.py

This started from fixing the test, where `"xdist_strict True"` was used
as a single argument, although you typically would see `["xdist_strict",
"True"]`.
Improves the error message to mention the option that caused the error.

Improve UsageError with invalid `-o` style

---

README.rst

Currently reported as failing, but that appears to be a temporary problem on their end (i.e. a rebuild should fix it).
https://readthedocs.org/projects/pytest/builds/10523470/

Add Read The Docs badge to README

---

CONTRIBUTING.rst
changelog/README.rst
tox.ini

This will use the same directory as `make -C doc/en` then, and reflects
the default location that Sphinx uses.

docs: use doc/en/_build/html for html output

---

src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/python.py

Previously this was implemented both on `Session` and `Package`, where
the extra code in `Package._collectfile` was not covered/used.

Move _collectfile to FSCollector

---

src/_pytest/config/__init__.py
src/_pytest/faulthandler.py
src/_pytest/junitxml.py
src/_pytest/mark/__init__.py
src/_pytest/nodes.py
src/_pytest/pastebin.py
src/_pytest/resultlog.py
src/_pytest/skipping.py
src/_pytest/store.py
src/_pytest/unittest.py
testing/test_junitxml.py
testing/test_resultlog.py
testing/test_store.py

[Resubmission of #6789 -- see previous discussion there.]
pytest has several instances where plugins set their own attributes on
objects they receive in hooks, like nodes and config. Since plugins are
detached from these object's definition by design, this causes a problem
for type checking because these attributes are not defined and mypy
complains.
Fix this by giving these objects a "store" which can be used by plugins
in a type-safe manner.
Currently this mechanism is private. We can consider exposing it at a
later point.

Add a typing-compatible mechanism for ad-hoc attributes on various objects

---

.github/workflows/release-on-comment.yml
RELEASING.rst
scripts/release-on-comment.py
tox.ini

This PR introduces preparing releases by creating a new issue or commenting on existing issues.
The comment is in the format:
```
@pytestbot please prepare release from BRANCH
```
Where `BRANCH` can be `master` or one of the maintenance branches.
Here are two examples of issues that generating appropriate PRs:
* https://github.com/nicoddemus/pytest/issues/31
* https://github.com/nicoddemus/pytest/issues/32

Automate release by comment notifications

---

changelog/6834.feature.rst
src/_pytest/terminal.py
testing/example_scripts/warnings/test_group_warnings_by_message_summary.py
testing/test_warnings.py

summarize warning summaries if the number of locations is high

---

src/_pytest/_code/code.py
src/_pytest/reports.py
src/_pytest/runner.py

Follow-up to https://github.com/pytest-dev/pytest/pull/6732.

Use attrs with all Repr classes

---

CODE_OF_CONDUCT.md

remove myself from the list of coc handlers

---

.gitblameignore

Updates to/for it should be collected / accumulated here then maybe for the future to be committed in batches.
List of revisions that can be ignored with git-blame(1).
See `blame.ignoreRevsFile` in git-config(1) to enable it by default, or
use it with `--ignore-revs-file` manually with git-blame.
To "install" it:
git config --local blame.ignoreRevsFile .gitblameignore
703e4b11ba76171eccd3f13e723c47b810ded7ef
eaa882f3d5340956beb176aa1753e07e3f3f2190
a91fe1feddbded535a4322ab854429e3a3961fb4
afc607cfd81458d4e4f3b1f3cf8cc931b933907e
8c49561470708761f7321504f5e8343811be87ac
9aacb4635e81edd6ecf281d4f6c0cfc8e94ab301
5f95dce95602921a70bfbc7d8de2f7712c5e4505
75d0b899bbb56d6849e9d69d83a9426ed3f43f8b
c9df77cbd6a365dcb73c39618e4842711817e871

Add .gitblameignore

---

changelog/6802.bugfix.rst
src/_pytest/pytester.py
testing/test_pytester.py

Use `request.node.name` instead of `request.function.__name__`:
`request.function` is `None` with `DoctestItem`s.
TODO:

Fix usage of pytester with doctests

---

src/_pytest/python.py

https://github.com/pytest-dev/pytest-twisted/tree/v1.12#ensuredeferred
[pytest-twisted](https://github.com/pytest-dev/pytest-twisted) supports `async def` test functions and fixtures as well as `async def`/`yield` fixtures.

Add pytest-twisted to list of async def handling plugins

---

src/_pytest/mark/legacy.py

Also added type hinting.
Noticed this while taking a look at https://github.com/pytest-dev/pytest/issues/6822.

Use attrs in KeywordMapping

---

src/_pytest/assertion/__init__.py
src/_pytest/assertion/rewrite.py
src/_pytest/mark/evaluate.py
src/_pytest/store.py
testing/test_store.py

Continuation of #6836.
One is the `AssertionState` used by the assertion rewriter, second is the mark expression evaluation cache.
There is also a commit to add `setdefault` to `Store` which I then use.

Convert a couple of places to use config store

---

src/_pytest/python.py

When it was introduced in 8adac2878f183e2250d1ed53457b60f19e7316f9 it seems to have had some use, but now it doesn't.

Inline PyobjContext

---

pyproject.toml
src/_pytest/fixtures.py
testing/test_capture.py
testing/test_config.py

This is meant to avoid having trailing commas after `**kwargs`, which
only works in Python 3.5.2+.
Ref: https://github.com/pytest-dev/pytest/commit/2e756d698, https://github.com/pytest-dev/pytest/pull/5611
Might make more sense to add config for it: https://github.com/blueyed/pytest/pull/275

pre-commit: black: --target-version py35

---

src/_pytest/capture.py

Remove wrong docstring: it might actually return bytes.
Replace it with a type annotation which is clear enough.

doc: internal: fix `MultiCapture.readouterr`

---

src/_pytest/config/__init__.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/python.py
src/_pytest/runner.py

Mostly avoid unnecessary usage of `sys.exc_info()`. Since Python3, exception objects themselves have all that's needed. They are also easier to type.

Simplify some exception handling code

---

.github/workflows/release-on-comment.yml

Issue events don't contain a 'comment' entry:
https://developer.github.com/v3/issues/events/#response-2
Issue comments also contain the original issue body:
https://developer.github.com/v3/activity/events/types/#issuecommentevent
That's why it was triggering even for comments on the issue.
Also changed to startsWith because there's no need to support
the command anywhere in the body IMO.
Fix #6895

Fix bot trigger event

---

changelog/6903.breaking.rst
src/_pytest/capture.py
testing/test_capture.py

The commit which added the checks for os.dup a15afb5e4879d68033a723129e6 suggests it was done for Jython. But pytest doesn't support Jython anymore (Jython is Python 2 only).
Furthermore, it looks like the faulthandler plugin (bundled in pytest and enabled by default) uses os.dup() unprotected and there have not been any complaints.
So seems better to just remove these checks, and only add if someone with a legitimate use case complains.

Assume os.dup is always available

---

changelog/6910.bugfix.rst
src/_pytest/resultlog.py
testing/test_resultlog.py

Noticed that the pytest_report_teststatus of reportlog was not properly
handling unknown statuses while taking a look at:
https://github.com/pytest-dev/pytest-rerunfailures/issues/103

Handle unknown stats in pytest_report_teststatus hook

---

changelog/6910.bugfix.rst
src/_pytest/resultlog.py
testing/test_resultlog.py

Btw should we follow the protocol for 4.6 releases of using the `needs backport` labels?

[Backport #6910] Handle unknown stats in pytest_report_teststatus hook

---

changelog/6909.bugfix.rst
doc/en/example/parametrize.rst
src/_pytest/fixtures.py
src/_pytest/python.py
testing/python/collect.py
testing/python/metafunc.py

This reverts commit 9e262038c84a99d1353551e8cbb32f46362b58b4.
Fix #6909

Revert "[parametrize] enforce explicit argnames declaration (#6330)"

---

scripts/release-on-comment.py

Unfortunately this is really getting in the way of the releases not because
of broken links, but because it is very flaky.
Related: #6894

Skip link checks when doing releases through the bot

---

changelog/6909.bugfix.rst
changelog/6910.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-5.4.1.rst
doc/en/changelog.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/6915#issuecomment-598720944.
can be released by pushing a tag `5.4.1` to this repository.

Prepare release 5.4.1

---

src/_pytest/capture.py
testing/test_capture.py

I tried to understand what the `safe_text_dupfile()` function and `EncodedFile` class do. Outside tests, `EncodedFile` is only used by `safe_text_dupfile`, and `safe_text_dupfile` is only used by `FDCaptureBinary.__init__()`. I then started to eliminate always-true conditions based on the single call site, and in the end nothing was left except of a couple workarounds that are still needed.

Remove safe_text_dupfile() and simplify EncodedFile

---

src/_pytest/mark/legacy.py

#6822  `KeywordMapping` returns a bool on lookup which when passed to eval
fail on certain operations such as index access and attribute access.
Check has been added to raise a UsageError if such operations are passed
to -k

Check invalid operations for -k

---

changelog/6871.bugfix.rst
src/_pytest/capture.py
testing/test_capture.py

Closes #6880 by replacing that PR with some modifications as described in https://github.com/pytest-dev/pytest/pull/6880#pullrequestreview-373899475 (step 2).
---
Previously, writing to sys.stdout/stderr in text-mode (e.g.
`print('foo')`) while a `capsysbinary` fixture is active, would crash
with:
/usr/lib/python3.7/contextlib.py:119: in __exit__
next(self.gen)
E   TypeError: write() argument must be str, not bytes
This is due to some confusion in the types. The relevant functions are
`snap()` and `writeorg()`. The function `snap()` returns what was
captured, and the return type should be `bytes` for the binary captures
and `str` for the regular ones. The `snap()` return value is eventually
passed to `writeorg()` to be written to the original file, so it's input
type should correspond to …

Fix crash when printing while capsysbinary is active

---

.github/workflows/main.yml
.travis.yml
scripts/append_codecov_token.py
scripts/report-coverage.sh
tox.ini

This PR solves https://github.com/pytest-dev/pytest/issues/6821 by fixing the Travis CI which was borked, and adding GitHub actions to test some of the other environments and operating systems not being tested in Travis anymore. Also makes sure coverage is 💚.

Fix travis config and coverage report.

---

doc/en/example/simple.rst
doc/en/flaky.rst
doc/en/reference.rst
src/_pytest/runner.py

This changes the link anchors in "reference.html", from e.g.
`reference.html#pytest-current-test` to
`reference.html#envvar-PYTEST_CURRENT_TEST`, but I think that is OK, and
not worth adding labels for the old anchors.

doc: use `envvar` directive for environment variables

---

testing/test_warnings.py

Recently merged https://github.com/pytest-dev/pytest/pull/6782 has broken linting, probably due to a change in the version of `black`.
I intend to merge this as soon as CI passes, let me know otherwise.

Fix linting

---

src/_pytest/assertion/rewrite.py

This was changed unintentionally in 45c4a8fb3 (pytest 5.3.0), but only
EnvironmentErrors might have `errno`.
Since that is not really guaranteed and it is good to have more
information this uses the string representation of the exc in the trace
message.
TODO:

assertion: rewrite: only catch EnvironmentError

---

doc/en/example/assertion/failure_demo.py
doc/en/example/reportingdemo.rst
doc/en/monkeypatch.rst
src/_pytest/_code/source.py
src/_pytest/assertion/rewrite.py
src/_pytest/cacheprovider.py
src/_pytest/capture.py
src/_pytest/config/findpaths.py
src/_pytest/fixtures.py
src/_pytest/pathlib.py
testing/acceptance_test.py
testing/test_argcomplete.py
testing/test_assertrewrite.py
testing/test_capture.py
testing/test_tmpdir.py

Since Python 3.3, these are aliases for OSError:
https://docs.python.org/3/whatsnew/3.3.html#pep-3151-reworking-the-os-and-io-exception-hierarchy

Change EnvironmentError, IOError to OSError - they are aliases

---

doc/en/skipping.rst

As per https://github.com/pytest-dev/pytest/pull/6957/files#r399564043

Quick doc fix on xfail reason parameter

---

changelog/6951.bugfix.rst
src/_pytest/deprecated.py
src/_pytest/terminal.py
testing/deprecated_test.py

fix #6951: allow to write TerminalReporter.writer

---

changelog/6981.deprecation.rst
src/_pytest/compat.py
src/_pytest/deprecated.py
src/pytest/__init__.py
src/pytest/collect.py
testing/deprecated_test.py

 deprecate the pytest.collect module

---

changelog/6924.bugfix.rst
src/_pytest/python.py
testing/example_scripts/pytest.ini
testing/example_scripts/unittest/test_unittest_asyncio.py
testing/test_unittest.py

fixes #6924 
opting out of the warning+skip revealed that the generators currently don't execute, while on 5.3 they do by accidennt

running stdlib asyncio unittests again

---

changelog/6871.bugfix.rst
src/_pytest/capture.py
testing/test_capture.py

Backport of 1fda86119055f7a5db8a30d867b26e802f6067ab from master.

[5.4.x] Fix crash when printing while capsysbinary is active

---

changelog/6925.bugfix.rst
src/_pytest/_code/code.py
testing/code/test_code.py

pytest-xdist assumes `ExceptionChainRepr` is hashable.
Fixes https://github.com/pytest-dev/pytest/issues/6925.
Fixes https://github.com/pytest-dev/pytest-xdist/issues/515.

Fix TerminalRepr instances to be hashable

---

doc/en/cache.rst
doc/en/example/index.rst
doc/en/faq.rst

It creates odd wording otherwise. Keep the reference, update the title
using Sphinx notation.
For example, [in the cache section](https://docs.pytest.org/en/latest/cache.html#the-new-config-cache-object) it reads: 
>  Here is a basic example plugin which implements a pytest fixtures: explicit, modular, scalable which re-uses previously created state across pytest invocations:
With this change it reads:
> Here is a basic example plugin which implements a fixture which re-uses previously created state across pytest invocations:
This PR doesn't address all the references to fixtures (I checked them all!), because in some other situations it does read fine.

docs: Do not use automatic title in fixture reference

---

changelog/6925.bugfix.rst
src/_pytest/_code/code.py
testing/code/test_code.py

pytest-xdist assumes `ExceptionChainRepr` is hashable.
Fixes https://github.com/pytest-dev/pytest/issues/6925.
Fixes https://github.com/pytest-dev/pytest-xdist/issues/515.
(cherry picked from commit 20f6331afd3cf5af1d708f77aede08ad1a9d8661)

[5.4.x] Fix TerminalRepr instances to be hashable (#6988)

---

testing/test_assertion.py
testing/test_reports.py

Use `testdir.syspathinsert()` with multiprocessing tests:
- `test_chained_exceptions_no_reprcrash`
- `test_exception_handling_no_traceback`
This only works currently because `_importtestmodule` changes `sys.path`
as a side-effect.
It appears to be only required on Windows though - likely due to the
multiprocessing method used there.

Fix tests: use explicit syspathinsert

---

src/_pytest/fixtures.py

Unused since 1e80a9cb34c73066cc8fa232be9b20fe284b8ae9.

Remove unused defaultfuncargprefixmarker

---

src/_pytest/hookspec.py
testing/test_terminal.py

This hook has some functionality to provide explicit markup for the test status. It seemed unused and wasn't tested, so I was tempted to remove it, but I found that the pytest-rerunfailures plugin uses it, so document it and add a test instead.

Document the pytest_report_teststatus hook better and test uncovered functionality

---

testing/test_faulthandler.py

This might help fix some flakiness.
Let's say it Fixes #7022 and reopen if not.

Increase test_faulthandler.py::test_timeout sleep duration on CI

---

doc/en/assert.rst

Ref: 9c5da9c (https://github.com/pytest-dev/pytest/pull/5184)
Fixes https://docs.pytest.org/en/latest/assert.html#disabling-assert-rewriting.

doc: fix/remove leftovers from removing `versionadded`

---

testing/test_runner.py

Tried to write a test using `--boxed`, but it fails due to
https://github.com/pytest-dev/pytest-forked/issues/30.

Remove TestExecutionForked - xdist.boxed has gone since long

---

doc/en/writing_plugins.rst
src/_pytest/hookspec.py

It was surprising that `tryfirst=True` would not result in lines being
added to the beginning with `pytest_report_header`.
This is due to lines being reversed, and therefore the same applies to
`pytest_report_collectionfinish`.

doc: document inversed lines with terminal report hooks

---

src/_pytest/runner.py
testing/acceptance_test.py

Fixes #7024.
`TestDurations` tests the `--durations=N` functionality which reports N slowest tests, with durations <= 0.005s not shown by default.
The test relies on real `time.sleep()` (in addition to the code which uses `time.perf_counter()`) which makes it flaky and inconsistent between platforms.
Instead of trying to tweak it more, make it use fake time instead. The way it is done is a little hacky but seems to work.

Fix flaky TestDurations test

---

testing/test_faulthandler.py

Reverts pytest-dev/pytest#7030 - didn't fix the problem.

Revert "Increase test_faulthandler.py::test_timeout sleep duration on CI"

---

testing/test_collection.py
testing/test_mark.py

It fails when trying to run it actually:
> TypeError: test_has_inherited() takes 0 positional arguments but 1 was given

tests: fix TypeError with test_mark_closest

---

testing/test_capture.py

Instantiating `FDCapture` creates a file descriptor already.  Use "no"
to not leak a fd here.

Fix FD leak in test__get_multicapture

---

src/_pytest/mark/structures.py

Mostly I wanted to get rid of mentions of "MarkItem" which is something that no longer exists, but I improved a little beyond that and annotated some simple types.

Slightly improve Mark and MarkDecorator documentation

---

src/_pytest/faulthandler.py

It should happen as late as possible before the test runs.
Ref: https://github.com/pytest-dev/pytest/issues/7022

faulthandler: trylast=True

---

testing/test_meta.py

This would result in an SyntaxError with `import _pytest.async`.

Fix test_no_warnings to handle e.g. `_pytest.async`

---

changelog/6992.bugfix.rst
src/_pytest/tmpdir.py

Reverts pytest-dev/pytest#6767
closes #6987
closes pytest-dev/pytest-xdist#510
unfortunately the cleanup also removes the structural escape hatch `pytest-xdist` uses to ensure correct `tmpdir` setup
until that can be fixed, we have to return to the old way

Revert "tmpdir: clean up indirection via config for factories"

---

testing/test_faulthandler.py

It occasionally crashes on CI, the reason seems out of our control, or at least we can't figure it out.
Refs #7022.

Skip flaky test test_faulthandler.py::test_timeout[True]

---

testing/test_monkeypatch.py

Presumably it used to test old-style vs. new-style classes, but in the Python 3 conversion `SampleNew` and `SampleOld` became the same.

Remove Python 2 compat check in test_monkeypatch.py

---

testing/test_assertrewrite.py

The `_pytest._code._reprcompare` that was referred to previously doesn't
exist -- it was moved to other places but wasn't update.
This regressed in f423ce9c016aff0d84c4a68f6d972833d032181e.

Remove broken _reprcompare disabling fixture in test_assertrewrite.py

---

doc/en/deprecations.rst
src/_pytest/deprecated.py
testing/deprecated_test.py

doc: more docs for from_parent

---

changelog/6924.bugfix.rst
src/_pytest/python.py
testing/example_scripts/pytest.ini
testing/example_scripts/unittest/test_unittest_asyncio.py
testing/test_unittest.py

backport of #6927
part of #7001

backport #6927: run async testcase methods

---

changelog/6992.bugfix.rst
src/_pytest/tmpdir.py

backport of #6992
part of #7001

backport #6992 to 5.4.x - restores tmpdir indirection

---

TIDELIFT.rst

As per: https://mail.python.org/pipermail/pytest-dev/2020-April/004939.html
I will contact the Tidelift people about the change as well.

Remove myself from tidelift

---

AUTHORS
changelog/4583.bugfix.rst
src/_pytest/mark/legacy.py
testing/test_mark.py

Hello pytest devs, great project thanks and I look forward to growing my contributions, tho its quite the code base to understand!  from #4583 this provides a nicer error message to the user when invoking eval() for marker expressions does not go quite successfully, raising a USAGE_ERROR rather than the crash/INTERNAL_ERROR at present.
Thank you very much for taking your time to review my PR, look forward to addressing any feedback, have a great day.

Gracefully handle eval() failure(s) for marker expressions

---

src/_pytest/pytester.py

Good morning, I'm just getting started with contributing so i thought i would go after some low hanging fruit, when doing some plugin development the pytest plugin (while cool was kind of new to me, checking out --fixtures for it yielded the following:
```
linecomp
.tox/py37/lib/python3.7/site-packages/_pytest/pytester.py:355: no docstring available
LineMatcher
.tox/py37/lib/python3.7/site-packages/_pytest/pytester.py:360: no docstring available
testdir
.tox/py37/lib/python3.7/site-packages/_pytest/pytester.py:365: no docstring available
```
So this PR adds some brief documentation to the fixture docstrings for those 3 empty ones.  Maybe it was intentional not to have any as its the 'pytester' plugin, but they are shown to end users so I think its a worthwhile improvement
Thanks for your …

Document pytester fixtures so --fixtures makes more sense

---

src/_pytest/faulthandler.py

I think it is available in all Python versions we support, but at least
since Python 3.7 the docs[0] say:
Changed in version 3.7: This function is now always available.
so let's just remove the note.
[0] https://docs.python.org/3/library/faulthandler.html#faulthandler.dump_traceback_later

Remove note saying faulthandler_timeout is not available on Windows

---

tox.ini

`pypy` refers to Pypy 2 which implements Python 2 which pytest no longer supports. Keep only `pypy3`.

Remove pypy (2) environment from tox.ini

---

src/_pytest/assertion/__init__.py
src/_pytest/freeze_support.py

This has been merged into the (only) assertrewrite mode.

doc: internal: remove references to old "newinterpret" module

---

testing/acceptance_test.py

Currently this test issues a warning which is displayed in the warning summary (of pytest's own test suite):
```
testing/acceptance_test.py::TestGeneralUsage::test_early_skip
/tmp/pytest-of-ran/pytest-396/test_early_skip0/conftest.py:2: PytestDeprecationWarning: The pytest_collect_directory hook is not working.
Please use collect_ignore in conftests or pytest_collection_modifyitems.
def pytest_collect_directory():
```
I think the filter was meant to be `ignore` in the first place, and not `always` which is not a valid action AFAIK.

testing: avoid pytest_collect_directory message in warning summary

---

changelog/7097.deprecation.rst
doc/en/deprecations.rst
src/_pytest/deprecated.py
src/_pytest/fixtures.py
src/_pytest/python.py
testing/deprecated_test.py
testing/python/fixtures.py
testing/python/integration.py

This function is exposed and kept alive for the oejskit plugin which is abandoned and no longer works with recent plugins, so let's prepare to completely remove it.
Replaces #7097 with just the deprecation.

fixtures: deprecate pytest._fillfuncargs function

---

testing/test_cacheprovider.py

Remove this message from the warning summary of pytest's own testsuite:
testing/test_cacheprovider.py::TestNewAPI::test_cache_writefail_cachfile_silent
testing/test_cacheprovider.py:40: PytestCacheWarning: could not create cache path /tmp/pytest-of-ran/pytest-2/test_cache_writefail_cachfile_silent0/.pytest_cache/v/test/broken
cache.set("test/broken", [])

testing: fix warning issued by test_cache_writefail_cachfile_silent

---

src/_pytest/cacheprovider.py
testing/test_cacheprovider.py

The code used an O(n^2) loop. Replace list with set to make it O(n).
For backward compatibility the filesystem cache still remains a list.
On this test:
import pytest
@pytest.mark.parametrize("x", range(5000))
run with `pytest --collect-only`:
Before: 0m1.251s
After:  0m0.921s

cacheprovider: speed up NFPlugin when --nf is not enabled

---

src/_pytest/config/__init__.py

As part of the effort to remove uses of `py`.

config: replace usage of py.io.dupfile

---

.github/workflows/main.yml
changelog/7110.bugfix.rst
src/_pytest/compat.py
src/_pytest/python.py
src/_pytest/unittest.py
testing/example_scripts/unittest/test_unittest_asyncio.py
testing/example_scripts/unittest/test_unittest_asynctest.py
testing/test_unittest.py
tox.ini

Instead of trying to handle unittest-async functions in `pytest_pyfunc_call`,
let the `unittest` framework handle them instead.
This lets us remove the hack in `pytest_pyfunc_call`, with the upside that
we should support any unittest-async based framework.
Also included `asynctest` as test dependency for `py37-twisted`, and renamed
`twisted` to `unittestextras` to better reflect that we install `twisted` and
`asynctest` now instead of only `twisted`.
This also fixes the problem of cleanUp functions not being properly called for async functions.
Fix #7110
Fix #6924

Let unittest frameworks deal with async functions

---

.github/workflows/main.yml
changelog/7110.bugfix.rst
src/_pytest/compat.py
src/_pytest/python.py
src/_pytest/unittest.py
testing/example_scripts/unittest/test_unittest_asyncio.py
testing/example_scripts/unittest/test_unittest_asynctest.py
testing/test_unittest.py
tox.ini

[5.4] Merge pull request #7144 from nicoddemus/async-testcase-7110

---

doc/en/deprecations.rst
src/_pytest/deprecated.py

From discussion in #6178
cc @bittner

Improve docs about junit_family warning message

---

changelog/6947.bugfix.rst
src/_pytest/debugging.py
src/_pytest/unittest.py
testing/test_unittest.py

Fix cleanup functions not being invoked on test failures

---

TIDELIFT.rst

@blueyed is no longer a member of the pytest-dev organization.

Remove blueyed from TIDELIFT

---

AUTHORS
src/_pytest/pytester.py
testing/test_assertrewrite.py

Fixes #7018
No changelog as it's trivial, but happy to add if you like. 
e.g.
"Replace usage of py.path.local.make_numbered_dir with version from _pytest.pathlib"

7018: Use internal version of make_numbered_dir

---

src/_pytest/capture.py
src/_pytest/compat.py
testing/test_capture.py

Pulled out of https://github.com/pytest-dev/pytest/pull/6671

Refactor Capture classes: move/rename CaptureIO classes

---

src/_pytest/cacheprovider.py
src/_pytest/compat.py
src/_pytest/fixtures.py
src/_pytest/nodes.py
src/_pytest/python.py
src/_pytest/terminal.py

Collectively, on this benchmark run with `--collect-only`:
```py
import pytest
@pytest.mark.parametrize("x", range(50000))
```
Before:
```
============================ no tests ran in 11.37s ============================
23775445 function calls (22920574 primitive calls) in 11.648 seconds
```
After:
```
============================ no tests ran in 10.51s ============================
21725509 function calls (20870638 primitive calls) in 10.931 seconds
```
The first commit utilizes the fact that dicts are insertion-order preserving on Python>=3.7 to avoid  OrderedDict overhead when possible.
The second and third commits apply some micro optimizations to Node.
The fourth applies some minor optimizations to `PythonCollector.collect`.

Some easy micro optimizations to collection

---

src/_pytest/_code/__init__.py
src/_pytest/_code/code.py
src/_pytest/_code/source.py
src/_pytest/fixtures.py
src/_pytest/mark/structures.py
src/_pytest/nodes.py
src/_pytest/python.py

These two files were really intertwined. Make it so code.py depends on source.py without a reverse dependency.
No functional changes.

code: fix import cycles between code.py and source.py

---

changelog/7145.bugfix.rst
src/_pytest/_io/saferepr.py
testing/io/test_saferepr.py

Fix #7145
Credit goes to @bluetech. 👍

'saferepr' handles classes with broken __getattribute__

---

changelog/7122.breaking.rst
doc/en/example/markers.rst
src/_pytest/mark/expression.py
src/_pytest/mark/legacy.py
testing/test_mark.py
testing/test_mark_expression.py

Previously, the expressions given to the `-m` and `-k` options were evaluated with `eval`. This causes a few issues:
- Python keywords cannot be used.
- Constants like numbers, None, True, False are not handled correctly.
- Various syntax like numeric operators and `X if Y else Z` is supported
unintentionally.
- `eval()` is somewhat dangerous for arbitrary input.
- Can fail in many ways so requires `except Exception`.
The format we want to support is quite simple, so change to a custom parser. This fixes the issues above, and gives us full control of the format, so can be documented comprehensively and even be extended in the future if we wish.
Fixes #1141.
Fixes #3573.
Fixes #5881.
Fixes #6822.
Fixes #7112.

Stop using Python's eval() for -m and -k

---

testing/test_mark.py

Mostly trying to debug an odd CI failure in `test_keyword_option_custom` with `1 or 2` expression.

testing: clean up parametrization in test_mark.py

---

.github/workflows/main.yml
setup.cfg
testing/code/test_source.py
tox.ini

Resolves #7161
- the text of `SyntaxError`s changed as part of the PEG parser rewrite ([bpo-40334](https://bugs.python.org/issue40334))
- `inspect.getsource` improved in python3.9 (utilizing the `ast` and `__qualname__`) ([bpo-35113](https://bugs.python.org/issue35113))

Fix tests for python3.9

---

changelog/7180.bugfix.rst
src/_pytest/doctest.py
testing/test_doctest.py

Fix _is_setup_py for files encoded differently than locale

---

changelog/7180.bugfix.rst
src/_pytest/doctest.py
testing/test_doctest.py

Fix _is_setup_py for files encoded differently than locale

[5.4] Merge pull request #7186 from asottile/is_setup_py_encoding_agnostic

---

.github/workflows/main.yml
.github/workflows/release-on-comment.yml

Hoping this will fix the "rerun jobs" option which currently always fails.
Changelogs:
- https://github.com/actions/checkout#whats-new
- https://github.com/actions/setup-python#whats-new (note: says "Ability to download, install and set up Python packages from actions/python-versions that do not come preinstalled on runners " -- maybe relevant for #7161)
Also remove the top comment which I think is entirely outdated.

ci: update github action versions, remove outdated comment

---

changelog/4375.improvement.rst
setup.cfg
src/_pytest/config/__init__.py
src/pytest/__init__.py
src/pytest/__main__.py
testing/acceptance_test.py

Running `pytest | head -1` and similar causes an annoying error to be
printed to stderr:
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
(or possibly even a propagating exception in older/other Python versions).
The standard UNIX behavior is to handle the SIGPIPE silently. To
recommended method to do this in Python is described here:
https://docs.python.org/3/library/signal.html#note-on-sigpipe
It is not appropriate to apply this recommendation to `pytest.main()`,
which is used programmatically for in-process runs. Hence, change
pytest's entrypoint to a new `pytest.console_main()` function, to be
used exclusively by pytest's CLI, and add the SIGPIPE code there.
Fixes #4375.

Handle SIGPIPE/BrokenPipeError in pytest's CLI

---

AUTHORS
changelog/6870.feature.rst
doc/en/py27-py34-deprecation.rst
src/_pytest/config/__init__.py
testing/test_config.py

This change was first introduced in https://github.com/pytest-dev/pytest/pull/5564 but, logically, only since the `5.1.x` version. I'm back-porting it into the `4.6.x` branch since many people still use it in the meantime they migrate to Python 3.
I was also able to test this backport to be working successfully locally.

BACKPORT: Introduction of Config.invocation_args

---

src/_pytest/fixtures.py
testing/python/fixtures.py

The dynamic scope feature added in 10bf6aac76d5060a0db4a94871d6dcf0a1 necessitated some wrangling of arguments in pytest.fixture(). In particular, it deprecated positional arguments in favor of keyword-only arguments, while keeping backward compatibility.
The way it did this avoided some code duplication but ended up being quite hard to follow and to annotate with types.
Replace it with some straightforward code, which is not very DRY but is simple and easy to remove when the time comes.

Simplify positional arguments compatibility code in pytest.fixture()

---

changelog/6871.bugfix.rst
changelog/6924.bugfix.rst
changelog/6925.bugfix.rst
changelog/6947.bugfix.rst
changelog/6951.bugfix.rst
changelog/6992.bugfix.rst
changelog/7110.bugfix.rst
changelog/7143.bugfix.rst
changelog/7145.bugfix.rst
changelog/7180.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-5.4.2.rst
doc/en/changelog.rst
doc/en/writing_plugins.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/7192.
can be released by pushing a tag `5.4.2` to this repository.

Prepare release 5.4.2

---

TIDELIFT.rst

@asottile want to add yourself back as well?
@RonnyPfannschmidt @bluetech please also consider adding yourselves.
I plan to contact Tidelift next week, so it would be nice if we everyone who wants to join do so until then. 👍

Add myself to TIDELIFT

---

changelog/7210.deprecation.rst
src/_pytest/deprecated.py
src/_pytest/mark/__init__.py
testing/deprecated_test.py

The `-k '-expr'` syntax is an old alias to `-k 'not expr'`. It's also not very convenient to have syntax that start with `-` on the CLI. Deprecate it and suggest replacing with `not`.
---
The `-k 'expr:'` syntax discards all items until the first match and keeps all subsequent, e.g. `-k foo` with
test_bar
test_foo
test_baz
results in `test_foo`, `test_baz`. That's a bit weird, so deprecate it without a replacement. If someone complains we can reconsider or devise a better alternative.

mark: deprecate a couple undocumented -k syntaxes

---

.pre-commit-config.yaml
extra/get_issues.py
src/_pytest/_code/code.py
src/_pytest/capture.py
src/_pytest/compat.py
src/_pytest/config/argparsing.py
src/_pytest/config/findpaths.py
src/_pytest/logging.py
src/_pytest/main.py
src/_pytest/mark/legacy.py
src/_pytest/nodes.py
src/_pytest/outcomes.py
src/_pytest/python.py
src/_pytest/python_api.py
src/_pytest/runner.py
src/_pytest/unittest.py
testing/code/test_excinfo.py
testing/test_error_diffs.py
testing/test_setupplan.py

~~[flake8 3.8.0 is not released yet, only an alpha -- marked WIP until it is released officially.]~~
The new flake8 (or more correctly the pyflakes version it uses) fixes several issues that come up a lot with type annotations, so I'm eager to update so I can stop typing all of those noqa's :)

pre-commit: update flake8 3.7.7 -> 3.8.1

---

doc/en/nose.rst

The docs for Nose-style tests say that some types/parts of `yield`-based tests are supported:
https://github.com/pytest-dev/pytest/blob/master/doc/en/nose.rst#supported-nose-idioms
but the changelog for 4.1.0 is unambiguous that `yield`-based tests are entirely deprecated:
https://docs.pytest.org/en/latest/changelog.html#pytest-4-1-0-2019-01-05
and that's what I've found while using pytest: `yield`-based tests do not work and must be upgraded.  I've therefore deleted the `yield` entry in the "supported" subsection and made the `yield` entry in "unsupported" more unequivocal, with phrasing taken from the above-linked changelog entry for simplicity's sake.
I didn't bother adding a changelog entry or myself to AUTHORS.  Please let me know if you'd like me to do either.
By the way, I just got …

Make docs reflect that `yield`-based tests are now completely unsupported

---

AUTHORS
changelog/7126.bugfix.rst
src/_pytest/setuponly.py
testing/test_setuponly.py

Fix for #7126
I added a special case for bytes only as `saferepr` adds quotes to pure string literals. A bunch of tests depend on the original behavior, so I was not comfortable changing it globally. Scrapping `saferepr` output to match the original behavior doesn't sound as a trouble-proof solution too. Please correct me if it was a wrong idea.
Thank you for your time reviewing the PR 🙏

Issue 7126 - "saferepr" to avoid BytesWarning when using --setup-show

---

AUTHORS
changelog/6240.bugfix.rst
src/_pytest/logging.py
testing/test_capture.py

#6240
All credit goes to @blueyed in:
https://github.com/pytest-dev/pytest/issues/6240#issuecomment-558402301
Should I add a testcase to test this specific behaviour?

Create LogCaptureHandler if necessary (closes #6240) 

---

changelog/6909.bugfix.rst
doc/en/example/parametrize.rst
src/_pytest/fixtures.py
src/_pytest/python.py
testing/python/collect.py
testing/python/metafunc.py

I realize now that I should have done the other way around: revert the original PR on `master`, and then backport to `5.4.x`.
Either way, what should we do with the CHANGELOG on backports like this one?

[Backport #6914] Revert "[parametrize] enforce explicit argnames declaration (#6330)"

---

src/_pytest/config/__init__.py
testing/test_config.py

This removes the `KeyError` traceback from the chain when an conftest fails to import:
```
return self._conftestpath2mod[key]
E   KeyError: WindowsPath('D:/projects/pytest/.tmp/root/foo/conftest.py')
During handling of the above exception, another exception occurred:
...
raise RuntimeError("some error")
E   RuntimeError: some error
During handling of the above exception, another exception occurred:
...
E   _pytest.config.ConftestImportFailure: (local('D:\\projects\\pytest\\.tmp\\root\\foo\\conftest.py'), (<class 'RuntimeError'>, RuntimeError('some error',), <traceback object at 0x000001CCC3E39348>))
```
By slightly changing the code, we can remove the first chain, which is often confusing to users and doesn't help with anything.
Also while at it, simplified the string representation of …

Remove extraneous traceback and simplify string repr of ConftestImportFailure

---

changelog/7224.breaking.rst
doc/en/deprecations.rst
src/_pytest/deprecated.py
src/_pytest/logging.py
testing/deprecated_test.py
testing/logging/test_fixture.py
testing/logging/test_reporting.py

While looking at optimizing the logging plugin (since it shows up in profiles), and also at some issues and open PRs, I collected some simplifications and cleanups. I think they make the file a little cleaner and easier to understand and modify, and also a little faster, though this isn't the goal of this PR.
<details>
<summary>Benchmark</summary>
On this benchmark
```py
import pytest
@pytest.mark.parametrize("x", range(5000))
```
Before:
============================ 5000 passed in 13.66s =============================
13345882 function calls (12431103 primitive calls) in 14.054 seconds
After:
============================ 5000 passed in 12.53s =============================
11271238 function calls (10716458 primitive calls) in 12.938 seconds
</details>
It is better to …

logging: some simplifications/cleanups

---

testing/test_assertrewrite.py

The tests came via c629f6b18 and c61ff31ffa1.
The fixes from there are kind of obsoleted by 4cd08f9 (moving to importlib),
but it makes sense to keep them as integration tests in general.

tests: revisit tests for removed load_module

---

changelog/7035.trivial.rst
src/_pytest/python.py
testing/python/collect.py

Ref: 1a79137d0 (added `originalname`, but only via `Metafunc._calls`)

Function: use `originalname` in `_getobj` and make it default to `name`

---

doc/en/capture.rst
doc/en/getting-started.rst

[Some people](https://stackoverflow.com/questions/49738081/) and me as well were a bit confused about the `[...%]` indicators in stout. Since I didn't find a specific mention that it's not the code/test _coverage_, how about to add it here?
I hope my rst syntax is correct. GitHub at least rendered it OK, but I didn't re-build the docu locally. Can do that in the next few days if needed.

doc: highlight difference between progress percentage & code coverage

---

src/_pytest/python.py

It doesn't save much code but adds indirection which makes it a bit harder to follow and to type.

Remove pyobj_property helper, inline it instead

---

src/_pytest/logging.py
testing/logging/test_fixture.py

Previously, a LoggingCaptureHandler was instantiated for each test's setup/call/teardown which turns out to be expensive.
Instead, only keep one instance and reset it between runs.
(Previously in #7214. Now I'm pretty sure it will interact well with the other PRs).
<details>
<summary>Benchmark</summary>
```py
import pytest
@pytest.mark.parametrize("x", range(5000))
```
Before:
```
============================ 5000 passed in 11.87s =============================
10866808 function calls (10313462 primitive calls) in 12.163 seconds
```
After:
```
============================ 5000 passed in 11.25s =============================
10431870 function calls (9878523 primitive calls) in 11.541 seconds
````
</details>

logging: reuse LoggingCaptureHandler instance since it's expensive to create

---

changelog/7226.breaking.rst
src/_pytest/python.py
testing/python/collect.py

Noticed while documenting `Function.__init__` in https://github.com/pytest-dev/pytest/pull/7035.

Remove unused Function.__init__ 'args' parameter

---

testing/code/test_source.py

Unlike `inspect.getsource` it does not unwrap functions.

Test behavior of Source with regard to decorators

---

changelog/6817.improvement.rst
src/_pytest/assertion/__init__.py
src/_pytest/cacheprovider.py
src/_pytest/config/argparsing.py
src/_pytest/helpconfig.py
src/_pytest/mark/__init__.py
testing/test_helpconfig.py

This makes a difference for e.g. pytest-xdist:
Before:
```
--dist=distmode       set mode for distributing tests to exec environments. …
available environment. loadscope: …
grouped by file to any available environment.
(default) no: …
```
After:
```
--dist=distmode       set mode for distributing tests to exec environments.
each: send each test to all available environments.
load: load balance by sending any pending test to …
…
(default) no: run tests inprocess, don't distribute.
```
This might also result in unexpected changes (hard wrapping), when line 
endings where used unintentionally, e.g. with:
``` help="""
some long
help text
"""
```
But the benefits from that are worth it, and it is easy to fix, as will be
done for the internal `assertmode` option.
TODO:

Keep explicit newlines with help texts

---

changelog/7040.breaking.rst
changelog/7040.improvement.rst
src/_pytest/mark/__init__.py
src/_pytest/python.py
testing/test_collection.py
testing/test_mark.py

Fixes https://github.com/pytest-dev/pytest/issues/7040.

Do not include the root session with `-k`

---

AUTHORS
doc/en/getting-started.rst

As indicated on pypi and in the README pytest supports python version 3.8 and 3.9. The documentation should match.
This is my first pull request to a big repo like this one. I saw the wrong information on the [getting started page](https://docs.pytest.org/en/latest/getting-started.html). I read the contributing guidelines and hope this is fine.

Updated compatible python versions

---

changelog/6433.feature.rst
src/_pytest/logging.py
testing/logging/test_reporting.py

Fixes #6433.
Currently, a bad logging call, e.g.
logger.info('oops', 'first', 2)
triggers the default logging handling, which is printing an error to
stderr but otherwise continuing.
For regular programs this behavior makes sense, a bad log message
shouldn't take down the program. But during tests, it is better not to
skip over such mistakes, but propagate them to the user.

logging: propagate errors during log message emits

---

changelog/7091.improvement.rst
src/_pytest/capture.py
testing/test_capture.py

The `FDCapture`/`FDCaptureBinary` classes, used by `capfd`/`capfdbinary`
fixtures and the `--capture=fd` option (set by default), redirect FDs
1/2 (stdout/stderr) to a temporary file. To do this, they need to save
the old file by duplicating the FD before redirecting it, to be restored
once finished.
Previously, if this duplicating (`os.dup()`) failed, most likely due to
that FD being invalid, the FD redirection would silently not be done. The
FD capturing also performs python-level redirection (monkeypatching
`sys.stdout`/`sys.stderr`) which would still be done, but direct writes
to the FDs would fail.
This is not great. If pytest is run with `--capture=fd`, or a test is
using `capfd`, it expects writes to the FD to work and be captured,
regardless of external circumstances.
So, instead …

Perform FD capturing even if the FD is invalid

---

src/_pytest/config/__init__.py
src/_pytest/nodes.py
src/_pytest/outcomes.py
src/_pytest/terminal.py

A few tiny micro-optimizations/simplifications

---

changelog/7150.bugfix.rst
src/_pytest/debugging.py
testing/test_debugging.py

@asottile the PR I mentioned in #7150. Let me know if I missed something. Thanks for your patience and your help on this, I really appreciate it!

Prevent hiding underlying exception when ConfTestImportFailure is raised

---

AUTHORS
changelog/7233.doc.rst
doc/en/reference.rst

As discussed in #7233, I added a note to references stating the preference for `--strict-markers`.
@nicoddemus I hope I did not forget anything and the proposed note is sufficient. Let me know if I need to change something.

Add note about --strict and --strict-markers to references

---

changelog/7150.bugfix.rst
src/_pytest/debugging.py
testing/test_debugging.py

Prevent hiding underlying exception when ConfTestImportFailure is raised
(cherry picked from commit 45f53266e6fa1539b702df315847cfbce3e3f19e)

[5.4.x] Merge pull request #7244 from DahlitzFlorian/fix-issue-7150

---

src/_pytest/capture.py
src/_pytest/pytester.py
testing/test_capture.py

These are some simple cleanups to capture. I have more complex changes planned, but will send them separately.
The changes are split into independent commits. One of the commits reorders sections which makes the PR diff not very readable.

capture: some initial cleanups

---

changelog/6956.bugfix.rst
src/_pytest/nodes.py
testing/python/collect.py
testing/test_reports.py

Closes: #6956 
@asottile I was not able to satisfy mypy so I added `# type: ignore` to the two lines. Let me know what you think :)

Prevent pytest from printing ConftestImportFailure traceback

---

changelog/6956.bugfix.rst
src/_pytest/nodes.py
testing/python/collect.py
testing/test_reports.py

Prevent pytest from printing ConftestImportFailure traceback
(cherry picked from commit b3db440d4c41c91dd761dee98d7014149e1d7c08)

[5.4.x] Merge pull request #7257 from DahlitzFlorian/fix-issue-6956

---

src/_pytest/_code/code.py

`str(self.path)` can't raise at all, so it can just be removed.
https://github.com/pytest-dev/pytest/blob/b3db440d4c41c91dd761dee98d7014149e1d7c08/src/_pytest/_code/code.py#L74-L90

code: remove last usage of py.error

---

changelog/7215.bugfix.rst
src/_pytest/unittest.py
testing/test_unittest.py

Do not call TestCase.tearDown for skipped tests

---

changelog/6428.bugfix.rst
src/_pytest/nodes.py
testing/test_nodes.py

Fixes #6428
Supersedes https://github.com/pytest-dev/pytest/pull/6429

Use abspath for errors when cwd changes during testing

---

changelog/7215.bugfix.rst
src/_pytest/unittest.py
testing/test_unittest.py

[5.4] Do not call TestCase.tearDown for skipped tests (#7236)

---

changelog/7255.feature.rst
doc/en/reference.rst
src/_pytest/deprecated.py
src/_pytest/hookspec.py
src/_pytest/terminal.py
src/_pytest/warnings.py
testing/test_warnings.py

As per https://github.com/pytest-dev/pytest/issues/4049, introduce a new hook named `pytest_warning_recorded` to replace `pytest_warning_captured`.
Parameter choice was determined by comments left on https://github.com/pytest-dev/pytest-xdist/issues/341.
Testing was accomplished via `tox -e py37`
PR Checklist:

Add new hook pytest_warning_recorded

---

changelog/7264.improvement.rst
setup.py
src/_pytest/_io/terminalwriter.py
src/_pytest/_io/wcwidth.py
src/_pytest/terminal.py
testing/io/test_wcwidth.py
testing/test_terminal.py

`TerminalWriter`, imported recently from `py`, contains its own incomplete wcwidth (`char_with`/`get_line_width`) implementation. The `TerminalReporter` also needs this, but uses the external `wcwidth` package.
This commit brings the `TerminalWriter` implementation up-to-par with `wcwidth`, moves the implementation to a new file `_pytest._io.wcwidth` module which is used everywhere, and removes the dependency.
The differences compared to the `wcwidth` package are:
- Normalizes the string before counting.
- Uses Python's `unicodedata` instead of vendored Unicode tables. This means the data corresponds to the Python's version Unicode version instead of the `wcwidth`'s package version.
- Applies some optimizations.

Improve our own wcwidth implementation and remove dependency on wcwidth package

---

AUTHORS
changelog/6755.bugfix.rst
src/_pytest/pathlib.py
testing/test_pathlib.py

Allow tmpdir to be removed in cases where the creation of files does not exceed the length of MAX_PATH, but adding garbage + UUID does exceed the length of path. Fixes https://github.com/pytest-dev/pytest/issues/291

Fix removal of very long paths on Windows

---

codecov.yml

Adjust codecov: only patch statuses, wait for CI to pass

---

doc/en/capture.rst

Rename ``capfsysbinary`` to ``capsysbinary`` as the former does not exist as far as i can see.

Fix typo in capture.rst documentation

---

AUTHORS
changelog/6856.feature.rst
src/_pytest/config/__init__.py
src/_pytest/main.py
testing/test_config.py

Implementation of https://github.com/pytest-dev/pytest/issues/6856. 
Changes:
- Show a warning when an invalid `INI` key is read from a config ini file.
- Add the `--strict-config` which forces warnings to become errors

Output a warning to stderr when an invalid key is read from an INI config file

---

doc/en/deprecations.rst
src/_pytest/hookspec.py
src/_pytest/warnings.py

This covers some loose ends from #7255 and fixes the issue reported later in #4049.

warnings: fix missing None in existing hook & add some docs

---

changelog/6428.bugfix.rst
changelog/6755.bugfix.rst
changelog/6956.bugfix.rst
changelog/7150.bugfix.rst
changelog/7215.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-5.4.3.rst
doc/en/changelog.rst
doc/en/example/parametrize.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/7300.
can be released by pushing a tag `5.4.3` to this repository.

Prepare release 5.4.3

---

src/_pytest/config/__init__.py
testing/test_config.py

Otherwise this relies on the dictionary order of `config.inicfg`, which
is insertion order in py36+ but "random" order in py35.
This lead to an unrelated failure in https://github.com/pytest-dev/pytest/pull/7247/checks?check_run_id=732077801.

Show invalid ini keys sorted

---

testing/test_runner.py

It is slated to be [removed](https://github.com/pytest-dev/pluggy/pull/147) in pluggy 1.0.

testing: change a test to not use deprecated pluggy __multicall__ protocol

---

changelog/7291.trivial.rst
setup.py
src/_pytest/config/findpaths.py
src/_pytest/pytester.py

7291: Replace py.iniconfig with iniconfig

---

changelog/6334.bugfix.rst
changelog/7310.bugfix.rst
src/_pytest/terminal.py
testing/test_terminal.py

This is a backport of #6337 (by @nicoddemus) with an extra change
note on top of it. It fixes #7310 and ~supersedes~ closes #7311 (as an
alternative to a smaller patch as suggested by @RonnyPfannschmidt).

[4.6.x][backport of PR #6337] Make 'S' and 'F' aliases to 's' and 'f' respectively

---

changelog/7253.bugfix.rst
src/_pytest/fixtures.py

pytest.fixture() can be used either as
@pytest.fixture
def func(): ...
or as
@pytest.fixture()
def func(): ...
or (while maybe not intended)
func = pytest.fixture(func)
so it needs to inspect internally whether it got a function in the first positional argument or not.
Previously, there were was an oddity. In the following,
func = pytest.fixture(func, autouse=True)
func = pytest.fixture(func, parms=['a', 'b'])
The result is as if `func` wasn't passed.
There isn't any reason for this special that I can understand, so remove it.

fixtures: remove special cases when deciding when pytest.fixture() is a direct decoration

---

src/_pytest/mark/expression.py
testing/test_mark_expression.py

Fixes #7322.
See the issue and added code comment for a description of the issue. It is rejected by Python debug builds and possibly future regular builds.

mark/expression: prevent creation of illegal Python identifiers

---

.gitignore
changelog/1556.feature.rst
doc/en/customize.rst
doc/en/example/pythoncollection.rst
doc/en/example/simple.rst
doc/en/reference.rst
pyproject.toml
setup.cfg
src/_pytest/config/__init__.py
src/_pytest/config/findpaths.py
src/_pytest/pytester.py
src/_pytest/terminal.py
testing/test_config.py
testing/test_findpaths.py
testing/test_terminal.py
tox.ini

Add pyproject.toml support

---

changelog/5965.breaking.rst
changelog/5965.bugfix.rst
src/_pytest/capture.py
src/_pytest/config/__init__.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/pathlib.py
testing/acceptance_test.py
testing/test_collection.py
testing/test_conftest.py
testing/test_link_resolve.py

Note that I didn't change all the `Path.resolve()` occurrences on `pytest`, only the ones related to getting the current directory.
Fix #5965
Fix #7333
Close #6733

Fix issue where working dir becomes wrong on subst drive on Windows. Fixes #5965

---

AUTHORS
changelog/7133.improvement.rst
doc/en/logging.rst
src/_pytest/logging.py
testing/logging/test_fixture.py

Rebased #7139 on `master` as I have no permission to push to the fork.
cc @ruaridhw @thisch
Closes #7139

Allow tests to override "global" `log_level` (rebased)

---

doc/en/start_doc_server.sh

In #7321 , I forgot to add a note about the utility script `start_doc_server` in the contrubuting.rst.
This add it back..  
cc: @nicoddemus

Remove start_doc_server.sh script

---

changelog/4675.bugfix.rst
changelog/4675.improvement.rst
src/_pytest/assertion/util.py
testing/example_scripts/dataclasses/test_compare_recursive_dataclasses.py
testing/test_assertion.py

I extracted the equality check in its own function and I call it from the dataclass comparison function to get recursive comparisons.
It could also be used for dict comparison, but the issue mentioned there was already some mechanism for dicts (I didn't see it in the code though).
Fixes #4675.

Make dataclasses/attrs comparison recursive, fixes #4675

---

changelog/5456.bugfix.rst
src/_pytest/pathlib.py
testing/test_pathlib.py

Suppress errors while removing tmpdir's lock files

---

changelog/7356.trivial.rst
doc/en/announce/release-2.3.5.rst
doc/en/announce/release-2.6.1.rst
doc/en/changelog.rst
doc/en/funcarg_compare.rst
src/_pytest/cacheprovider.py
src/_pytest/junitxml.py
src/_pytest/pastebin.py
src/_pytest/reports.py
src/_pytest/resultlog.py
testing/test_junitxml.py
testing/test_resultlog.py

See #7344, https://github.com/pytest-dev/pytest-xdist/issues/234, https://github.com/pytest-dev/pytest-xdist/pull/541.
CC @RonnyPfannschmidt

Finish deprecation of "slave"

---

src/_pytest/_code/code.py
src/_pytest/assertion/rewrite.py
src/_pytest/cacheprovider.py
src/_pytest/capture.py
src/_pytest/config/__init__.py
src/_pytest/config/findpaths.py
src/_pytest/debugging.py
src/_pytest/hookspec.py
src/_pytest/junitxml.py
src/_pytest/logging.py
src/_pytest/main.py
src/_pytest/mark/structures.py
src/_pytest/monkeypatch.py
src/_pytest/nodes.py
src/_pytest/python.py
src/_pytest/resultlog.py
src/_pytest/terminal.py
testing/acceptance_test.py
testing/test_assertrewrite.py
testing/test_config.py
testing/test_monkeypatch.py

Please see the commits, but here's a summary:
- Remove unused type: ignores
- Add type annotations to `MonkeyPatch`
- Add type annotations to `pytest_keyboard_interrupt` and `pytest_internalerror` hooks
- Fix type errors when running with typed `py.path.local`
- Fix type errors when running with typed `packaging`

More type annotations, fix some typing bugs

---

AUTHORS
changelog/6471.feature.rst
src/_pytest/terminal.py
testing/test_terminal.py

This pull request implements suggested approach for issue #6471.
Fix #6471.

Issue 6471 - Introduce new option to skip header and summary

---

changelog/7245.feature.rst
doc/en/goodpractices.rst
doc/en/pythonpath.rst
src/_pytest/_code/code.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/pathlib.py
src/_pytest/python.py
testing/acceptance_test.py
testing/python/collect.py
testing/python/fixtures.py
testing/test_collection.py
testing/test_compat.py
testing/test_conftest.py
testing/test_pathlib.py
testing/test_pluginmanager.py

This introduces --import-mode=importlib, which uses fine-grained facilities
from importlib to import test modules and conftest files, bypassing
the need to change sys.path and sys.modules as side-effect of that.
I've also opened #7245 to gather feedback on the new import mode.
Fix #5821

Introduce --import-mode=importlib

---

src/_pytest/config/__init__.py

I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …

Fix exception causes in config/__init__.py

---

src/_pytest/runner.py

[This is more of an RFC/question in a form of a PR, at least ATM.]
---
While working on improving the documentation of the runtest hooks, I came up with this text for `pytest_runtest_setup`:
> Called to perform the setup phase of the test item.
>
> The default implementation runs ``setup()`` on item and all of its parents (which haven't been setup yet). This includes obtaining the values of fixtures required by the item (which haven't been obtained yet).
But upon closer inspection, I noticed this line at the start of `SetupState.prepare` (which is what does the actual work for `pytest_runtest_setup`):
https://github.com/pytest-dev/pytest/blob/ab6dacf1d1e1ff0c5be70a3c5f48e63168168721/src/_pytest/runner.py#L411-L417
which implies that the setup phase of one item might trigger teardowns of …

RFC: runner: don't try to teardown previous items from pytest_runtest_setup

---

changelog/7357.trivial.rst
setup.cfg

See https://github.com/pytest-dev/py/blob/1.8.2/CHANGELOG#L4.
Fixes #7357.

Require py>=1.8.2 so we can rely on correct hash() of py.path.local n Windows

---

.pre-commit-config.yaml
changelog/7346.feature.rst
doc/en/reference.rst
src/_pytest/config/__init__.py
testing/test_config.py

Closes https://github.com/pytest-dev/pytest/issues/7346
Add in the ability to specify versioning information for the `required_plugins` INI key

Allow users to provide version information to the required_plugins INI key

---

doc/en/py27-py34-deprecation.rst

The final Python 2.7 release (2.7.18) was indeed in April 2020, on the 20th.
https://mail.python.org/archives/list/python-dev@python.org/thread/OFCIETIXLX34X7FVK5B5WPZH22HXV342/#OFCIETIXLX34X7FVK5B5WPZH22HXV342
---
Whilst we're here, it's now mid-2020. Does the following need any update (and the info about maintenance of 4.6.X versions in general), or is it okay to keep it as is for a while longer?
> The core team will be happy to accept those patches, and make new 4.6.X releases **until mid-2020** (but consider that date as a ballpark, after that date the team might still decide to make new releases for critical bugs).

Docs: Update tense, the final Python 2.7 was released in April

---

changelog/6505.breaking.rst
src/_pytest/pytester.py
testing/python/fixtures.py
testing/test_pytester.py

As discussed in #6505, this changes `assertoutcomes` to always work with the plural form of the nouns.
Fix #6505
Close #6905
cc @altendky

assertoutcomes() only accepts plural forms

---

doc/en/changelog.rst
doc/en/reference.rst
src/_pytest/hookspec.py
src/_pytest/logging.py
src/_pytest/reports.py
src/_pytest/terminal.py
src/pytest/collect.py

Here's a summary of each commit:
Type annotations:
- Type annotate the `pytest.collect` backward-compat module (only to satisfy typing coverage)
- Fix return type annotation of `pytest_runtest_makereport`
- Type annotate `pytest_runtest_log{start,finish}`
Docs:
- Refer to function public names instead of internal _pytest names
- Add `CollectReport` to the API reference
- Improve the `pytest_runtest_*` hooks documentation, including a complete layout of the runtest protocol
- Move "Collection hooks" before "Test running hooks" in the API reference

Some type annotations, doc improvements

---

changelog/7360.bugfix.rst
src/_pytest/mark/evaluate.py
testing/test_mark.py

As per https://github.com/pytest-dev/pytest/issues/7360

Disable caching when evaluating expressions in marks

---

src/_pytest/config/__init__.py
testing/test_config.py

The warning/error output of invalid plugins introduced here: https://github.com/pytest-dev/pytest/pull/7286 ( sorry ) does not properly respect ini keys defined in `conftest.py`. This change fixes that, and adds a test case that catches this bug.
I didn't add a changelog entry, since the feature still isn't released: https://github.com/pytest-dev/pytest/blob/master/changelog/6856.feature.rst
Closes https://github.com/pytest-dev/pytest/issues/7383

Don't treat ini keys defined in conftest.py as invalid

---

src/_pytest/mark/structures.py

These marks are some of the most used user-facing APIs in pytest, but because they are marks, which accept any arguments and are evaluated dynamically, there aren't any places to type them like regular functions.
This PR does a little cheating by special-casing them inside `MarkGenerator`. This is a gross breach of abstraction and other bad stuff, in particular it is not generalizable to 3rd-party marks (at least, if accessed through `pytest.mark`). However, due to the pervasiveness of these marks I think it is worth it, until/if we find a better solution.
I typed the marks as complete functions, i.e. building "partial" marks (like `get_empty_parameterset_mark` in the diff does) is not allowed. I think that's fine for these marks at least.

Type annotate pytest.mark.{skip,skipif,xfail,parametrize}

---

AUTHORS
changelog/7383.bugfix.rst
src/_pytest/_code/source.py
src/_pytest/config/__init__.py
src/_pytest/config/argparsing.py
src/_pytest/config/findpaths.py
src/_pytest/debugging.py
src/_pytest/fixtures.py
src/_pytest/logging.py
src/_pytest/monkeypatch.py
src/_pytest/python.py
src/_pytest/warnings.py
testing/test_config.py
testing/test_runner.py

This is a continuation of #7351

Fix exception causes all over the codebase

---

src/_pytest/nodes.py

This mistake was introduced in 7259c453d6c1dba6727cd328e6db5635ccf5821c.

nodes: fix string possibly stored in Node.keywords instead of MarkDecorator

---

src/_pytest/_code/__init__.py
src/_pytest/_code/code.py
src/_pytest/config/__init__.py
src/_pytest/helpconfig.py
src/_pytest/hookspec.py
src/_pytest/logging.py
src/_pytest/pathlib.py
src/_pytest/pytester.py
src/_pytest/tmpdir.py
testing/acceptance_test.py
testing/code/test_excinfo.py
testing/test_config.py

This improves the typing around `_pytest.config`, and also makes pytest completely clean with regards to the py typings in https://github.com/pytest-dev/py/pull/232.

config: improve typing

---

changelog/7385.improvement.rst
src/_pytest/junitxml.py
testing/test_junitxml.py

Add details to error message for junit

---

doc/en/example/markers.rst

Fix typo in examples/markers.rst

---

CONTRIBUTING.rst

The got out of date with the actual ones we use.

CONTRIBUTING: sync changelog types

---

testing/test_stepwise.py

This happens a lot recently, for example https://github.com/pytest-dev/pytest/runs/800088944. I tried a bit to find the underlying cause but failed.
Use the same workaround as used previously in test_runner.py.

testing: fix flaky tests on pypy3 due to resource warnings in stderr

---

changelog/6906.feature.rst
src/_pytest/_io/terminalwriter.py
src/_pytest/config/__init__.py
src/_pytest/terminal.py
testing/io/test_terminalwriter.py

Closes #6906 
code-highlight has default value to True, this value is used in `TerminalWriter`
in order to control highlighting of the code.

Fix-6906: Added code-highlight option to disable highlighting optionally

---

changelog/7418.breaking.rst
src/_pytest/fixtures.py
src/_pytest/freeze_support.py
src/_pytest/hookspec.py
src/_pytest/main.py
src/_pytest/python.py
src/_pytest/python_api.py
src/_pytest/recwarn.py
src/_pytest/reports.py
src/_pytest/terminal.py
src/_pytest/unittest.py
testing/example_scripts/issue_519.py
testing/python/approx.py
testing/python/fixtures.py
testing/test_doctest.py
testing/test_pathlib.py
testing/test_recwarn.py

This PR covers almost all of the holes mentioned in https://github.com/pytest-dev/pytest/issues/3342#issuecomment-648301701.
The PR is split to standalone commits, which should be easier to review (except `hookspec: improve typing of some remaining hooks` which is a bit messy).
Also note the commit `hookspec: remove unused hookspec pytest_doctest_prepare_content` which removes a hookspec -- in case someone knows that it is used in some way that I missed.

More typing work

---

src/_pytest/assertion/__init__.py
src/_pytest/runner.py

When scrolling through #7338 I noticed that the `item.ihook` property is called fairly often. There are two place where this access can be cached with trivial changes. When running [`empty.py`](https://github.com/pytest-dev/pytest/blob/master/bench/empty.py) calls to ihook are reduced from 14039 to 13039. While this doesn't result in significant performance gains I think it might still be useful to include since it doesn't increase code complexity.

Reduce calls to item.ihook

---

changelog/7159.improvement.rst
src/_pytest/logging.py
testing/logging/test_fixture.py

Replaces #7159.
Setting log_level via the CLI or .ini will control the log level of the report that is dumped upon failure of a test.
If caplog modified the log level during the execution of that test, it should not impact the level that is displayed upon failure in the "captured log report" section.
Changes I made:
- rebased
- reused handler
- changed store keys also to "caplog_handler_*"
- added changelog
all bugs are mine :)

logging: use unique handlers for caplog and reports

---

src/_pytest/junitxml.py

Closes https://github.com/pytest-dev/pytest/issues/7439
Use the `Match` in `Typing` instead of `re.Match` for junitxml.py to fix mypy error

fix mypy issue by using typing Match instead of re.Match

---

src/_pytest/mark/structures.py
src/_pytest/python.py
testing/python/metafunc.py

This PR contains a few code cleanups/improvements. Please see the commits.

python: a few cleanups

---

testing/acceptance_test.py

They sometime leak into other test's warnings and cause them to fail.

testing: fix flaky tests due to "coroutine never awaited" warnings

---

src/_pytest/pytester.py

Just a little leftover from trying to hunt down `ResourceWarnings` a few weeks ago.
No semantic changes intended.

pytester: slightly clean up LsofFdLeakChecker

---

changelog/7438.breaking.rst
src/_pytest/_code/__init__.py
src/_pytest/_code/source.py
src/_pytest/skipping.py
testing/code/test_code.py
testing/code/test_excinfo.py
testing/code/test_source.py

These commits clean up the  `_pytest._code.source` module, particularly removing a bunch of code we don't need.
I think it's a good idea to remove stuff we don't use because it reduces the amount of code we need to maintain and understand.

code/source: some cleanups

---

changelog/3342.feature.rst
setup.cfg

Fixes #3342. All of the relevant TODOs outlined in https://github.com/pytest-dev/pytest/issues/3342#issuecomment-648301701 are covered now so I think we're good to go.

Publish our types

---

changelog/7392.bugfix.rst
src/_pytest/skipping.py
testing/test_skipping.py

Fix reported location of skip when --runxfail is used

---

changelog/7464.feature.rst
doc/en/assert.rst
doc/en/changelog.rst
doc/en/conf.py
doc/en/deprecations.rst
doc/en/example/markers.rst
doc/en/example/pythoncollection.rst
doc/en/fixture.rst
doc/en/plugins.rst
doc/en/reference.rst
doc/en/skipping.rst
doc/en/warnings.rst
doc/en/writing_plugins.rst

This introduces a new role, `:globalvar:`, so we can mark/reference variables like `pytest_plugins`, `pytestmark`, etc. This besides being useful also makes the documentation look more consistent.
Also uses proper references in the CHANGELOG for #7466 as commented in https://github.com/pytest-dev/pytest/pull/7466#discussion_r452798085.

New doc role: globalvar for special variables

---

src/_pytest/mark/structures.py

This fixes #7473.
It seems that pylint doesn't understand TYPE_CHECKING and/or the type comments, and thinks `parametrize` and friends are `None`, and then complains that they are not callable.
The solution is a little uglier but seems to do the trick. On Python 3.6 we can use the nice syntax, which I also tested and will work.

mark/structure: fix pylint complaining that builtin marks are not callable

---

changelog/7389.trivial.rst
doc/en/fixture.rst
src/_pytest/fixtures.py

Remove package scope experimental status

---

changelog/7467.improvement.rst
src/_pytest/logging.py
testing/logging/test_reporting.py

Creates subdirectories if they do not exist for both --log-file and appropriate log_file ini marker for the log file.
closes #7467

Create subdirectories if they do not exist when specified for log file

---

src/_pytest/_io/terminalwriter.py
testing/io/test_terminalwriter.py

terminalwriter: bring back handling of printing characters not supported by stdout

---

src/_pytest/mark/structures.py

mark: fix typing for `@pytest.mark.xfail(raises=...)`

---

src/_pytest/skipping.py
testing/test_skipping.py

Fixes #7486.
If a test runtest phase (not setup) dynamically adds a `pytest.mark.xfail` mark to the item, it should be respected, but it wasn't. This regressed in 3e6fe92b7ea3c120e8024a970bf37a7c6c137714 (not released).
Fix it by just always refreshing the mark if needed. This is mostly what was done before but in a more roundabout way.
I also sneaked in a trivial style commit I noticed.

 skipping: fix dynamic xfail mark added in runtest not respected

---

src/_pytest/fixtures.py
src/_pytest/mark/structures.py
src/_pytest/python.py
testing/typing_checks.py

Fixes #7494.
There is also a commit which adds a `testing/typing_check.py` file whose purpose is only to not have any mypy errors.

 Fix typing of params ids callable form 

---

changelog/7491.bugfix.rst
src/_pytest/pathlib.py
testing/test_pathlib.py

Inaccessible lock files now imply temporary directories can't be removed

---

doc/en/doctest.rst

Clarify 'getfixture' needs to access fixtures by normal means

---

doc/en/goodpractices.rst
doc/en/reference.rst
doc/en/requirements.txt

Previously was restricted to >=1.8.2,<2.1, but newer versions have some nice improvements I'd like to be able to use in upcoming changes.
Changelog: https://www.sphinx-doc.org/en/master/changes.html#release-3-1-0-released-jun-08-2020
There are two issues that came up:
1. `highlightlang` is deprecated for `highlight`.
2. Doesn't like having two `automethod` generated for the same `Metafunc.parametrize` method. Gives this warning:
`pytest/doc/en/reference.rst:846: WARNING: duplicate object description of _pytest.python.Metafunc.parametrize, other instance in reference, use :noindex: for one of them`
To work around this I make `pytest.mark.parametrize` link to `Metafunc.parametrize` instead of repeating it.

docs: support Sphinx>=3.1 and require it

---

AUTHORS
changelog/7441.doc.rst
doc/en/getting-started.rst

Closes #7441 . Updated documentation to add a note about usage of `-q`in getting started guide as mentioned in the issue. Please review and let me know if anything is needed to be changed. Thank you.

docs: Add a note about -q option used in getting started guide

---

doc/en/parametrize.rst

Fix #7514 by augmenting Note with behaviour when parametrized values are mutated
(changes are reflected in subsequent test-case calls).

doc: note about mutation of parametrized values

---

testing/test_parseopt.py

Fixes #7518.
This fixes CI on Windows since GitHub Actions started installing WSL on their images which apparently installs some wrapper `bash` which does not run actual bash.

testing: use a tighter check if `bash` is available

---

doc/en/skipping.rst

* Change from "A xfail" to "An xfail".

Fix "A xfail" typo

---

changelog/7517.bugfix.rst
src/_pytest/capture.py
testing/test_capture.py

Preserve newlines when captured with capfd

---

doc/en/changelog.rst

doc: mention mypy<0.750 doesn't work in typing changelog

---

changelog/5584.breaking.rst
doc/en/reference.rst
doc/en/warnings.rst
src/_pytest/fixtures.py
src/_pytest/hookspec.py
src/_pytest/mark/__init__.py
src/_pytest/warning_types.py
src/_pytest/warnings.py
src/pytest/collect.py
testing/acceptance_test.py
testing/conftest.py
testing/deprecated_test.py
testing/example_scripts/fixtures/custom_item/conftest.py
testing/example_scripts/issue88_initial_file_multinodes/conftest.py
testing/python/collect.py
testing/test_collection.py
testing/test_junitxml.py
testing/test_skipping.py
testing/test_warnings.py

@RonnyPfannschmidt: I updated some tests which didn't use `from_parent`.
@bluetech: I had to suppress the MINUS_K_COLON and MINUS_K_DASH warnings because they would turn into errors in 6.0, and we want to make them into errors in 7.0 only, given they were added too recently; we should reintroduce the warnings in 6.1 ( (https://github.com/pytest-dev/pytest/issues/7361). 
Closes #5584

Change pytest deprecation warnings into errors for 6.0 release

---

changelog/7534.bugfix.rst
src/_pytest/_code/code.py
testing/code/test_code.py

This PR ammends #7274, undoing an incidental change to the output string and therefore fixes #7534.
cc @nicoddemus @hroncok

Revert change to traceback repr

---

RELEASING.rst
scripts/release-on-comment.py

Noticed this while trying to generate release 6.0.0 (#7547)

Support generating major releases using issue comments

---

scripts/release.minor.rst
scripts/release.patch.rst

The links were still pointing to the latest version (instead of stable) and also took the opportunity to update the text a bit.

Update text and links in announce templates

---

changelog/7558.bugfix.rst
src/_pytest/mark/structures.py

Fixes #7558, Refs #7473. Previous attempt: #7476.
Apparently the previous fix c1ca42b5c264b4ea1b4591bc12e0 didn't work. Hopefully this time I'm testing this correctly.

mark: fix pylint not-callable error on pytest.mark.parametrize(...), again

---

.pre-commit-config.yaml
changelog/7536.trivial.rst
src/_pytest/junitxml.py
testing/test_junitxml.py

This PR has a couple preparatory commits and then the conversion.
Part of the effort to reduce dependency on the py library.
Besides that, py.xml implements its own XML serialization which is pretty scary.
I tried to keep the code with minimal changes (though it could use some cleanups). The differences in behavior I have noticed are:
- Attributes in the output are not sorted.
- Some unneeded escaping is no longer performed, for example escaping `"` to `&quot;` in a text node.
Fixes #4970.
Fixes #1218.
Refs #7259.

junitxml: convert from py.xml to xml.etree.ElementTree

---

src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/pathlib.py
src/_pytest/python.py
testing/python/fixtures.py
testing/test_collection.py
testing/test_conftest.py

The first commit stops using `py.path.local`, we only need a very simple subset of it.
The second commit replaces `os.listdir()` with `os.scandir()` which is faster and reduces the amount of `stat` calls. This might help when running on very large directory trees, but mostly eclipsed by other overhead (except maybe on network drives and such...).

pathlib: stop using py.path.local.visit(), use os.scandir

---

src/_pytest/mark/structures.py

Fixup to #7565 found after merge by @graingert.

mark: fix extraneous spaces in dummy type-checking marks

---

changelog/7558.bugfix.rst
src/_pytest/mark/structures.py

[6.0.x] mark: fix pylint not-callable error on pytest.mark.parametrize(...), again

---

src/_pytest/logging.py
testing/logging/test_fixture.py

Fixes #7569.
This probably regressed in fcbaab8.

logging: fix capture handler level not reset on teardown after caplog.set_level()

---

changelog/7559.bugfix.rst
src/_pytest/reports.py
testing/test_runner.py

Fix TestReport.longreprtext when TestReport.longrepr is not a string

---

doc/en/tmpdir.rst

Added warning about deletion of data in the documentation of the base temporary directory
Fix #7554

Warn about --basetemp removing the entire directory

---

changelog/7394.bugfix.rst
changelog/7558.bugfix.rst
changelog/7559.bugfix.rst
changelog/7569.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-6.0.1.rst
doc/en/changelog.rst
doc/en/getting-started.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/7583.
can be released by pushing a tag `6.0.1` to this repository.

Prepare release 6.0.1

---

changelog/7587.trivial.rst
setup.cfg
src/_pytest/fixtures.py
src/_pytest/python_api.py
src/_pytest/terminal.py
testing/python/raises.py

We barely use it; the couple places that do are not really worth the extra dependency, I think the code is clearer without it.
Also simplifies one (regular) itertools usage.
Also improves a check and an error message in `pytest.raises`.

Stop using more-itertools

---

setup.cfg
src/_pytest/_code/__init__.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/mark/__init__.py
src/_pytest/python.py
testing/python/collect.py
testing/python/fixtures.py
testing/python/integration.py
testing/python/metafunc.py
testing/test_mark.py

In Python, if module A defines a name `name`, and module B does `import name from A`, then another module C can `import name from B`.
Sometimes it is intentional -- module B is meant to "reexport" `name`.
But sometimes it is just confusion/inconsistency on where `name` should be imported from.
mypy has a flag `--no-implicit-reexport` which puts some order into this. A name can only be imported from a module if
1. The module defines the name
2. The module's `__all__` includes the name
3. The module imports the name as `from ... import .. as name`.
This flag is included in mypy's `--strict` flag.
I like this flag, but I realize it is a bit controversial, and in particular item 3 above is a bit unfriendly to contributors who don't
know about it. So I didn't intend to add it to pytest.
But …

typing: set no_implicit_reexport

---

doc/en/xunit_setup.rst

Fixed location of double-backquote for verbatim text.
(Thanks for pytest, y'all!)

Minor formatting fix in xunit_setup.rst

---

setup.cfg
src/_pytest/_code/code.py
src/_pytest/assertion/rewrite.py
src/_pytest/cacheprovider.py
src/_pytest/debugging.py
src/_pytest/fixtures.py
src/_pytest/hookspec.py
src/_pytest/main.py
src/_pytest/mark/structures.py
src/_pytest/nodes.py
src/_pytest/outcomes.py
src/_pytest/python.py
src/_pytest/python_api.py
src/_pytest/recwarn.py
src/_pytest/reports.py
src/_pytest/runner.py
src/_pytest/setuponly.py
src/_pytest/setupplan.py
src/_pytest/terminal.py
src/_pytest/unittest.py
testing/python/metafunc.py
testing/test_assertion.py
testing/test_terminal.py

Fixes #7599 (presumably; I didn't actually test the described setup)
This prevents referring to a generic type without filling in its generic type parameters.
The `FixtureDef` typing might need some more refining in the future.

typing: set disallow_any_generics

---

.readthedocs.yml
pyproject.toml
setup.py

@RonnyPfannschmidt locally this doesn't seem to work, `pip list` says `pytest 0.0.0` is installed after running `pip install -e .`. Any hints?

Configure setuptools_scm using pyproject.toml

---

doc/en/changelog.rst
doc/en/deprecations.rst
doc/en/reference.rst

This is a follow up to 3f8200676f12846b74289f9b2e35747623fc768a which didn't
make it clear that log_print is also removed in the changelog and didn't remove
it from the reference docs.
Closes #7612

Properly remove log_print

---

doc/en/example/markers.rst

Closes #7546. 
To be honest, I'm not sure if this description is the best, I would be happy if you can modify it freely.

Better document -k partial matching

---

RELEASING.rst

Add docs for releasing major/release candidates

---

setup.cfg
src/_pytest/_code/code.py
src/_pytest/assertion/__init__.py
src/_pytest/assertion/rewrite.py
src/_pytest/capture.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/config/findpaths.py
src/_pytest/debugging.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/junitxml.py
src/_pytest/monkeypatch.py
src/_pytest/outcomes.py
src/_pytest/pathlib.py
src/_pytest/python.py
src/_pytest/python_api.py
src/_pytest/reports.py
src/_pytest/terminal.py
src/_pytest/tmpdir.py
testing/code/test_source.py
testing/test_assertrewrite.py
testing/test_monkeypatch.py
testing/test_pytester.py

This makes mypy raise an error whenever it detects code which is statically unreachable, e.g.
```py
x: int
if isinstance(x, str):
... # Statement is unreachable  [unreachable]
```
This is really neat and finds quite a few logic and typing bugs.
Sometimes the code is intentionally unreachable in terms of types, e.g. raising TypeError when a function is given an argument with a wrong type. In these cases a `type: ignore[unreachable]` is needed, but I think it's a nice code hint.

typing: set warn_unreachable

---

src/_pytest/junitxml.py
src/_pytest/pytester.py
src/_pytest/reports.py
src/_pytest/resultlog.py
src/_pytest/runner.py
src/_pytest/terminal.py
testing/test_reports.py
testing/test_resultlog.py

The first two commits are in service of the third, which type annotates the `TestReport`/`CollectRepor` (and related) `longrepr` fields. That would have caught #7559.
The type of `longrepr` is a union with 5 possibilities, which is not great IMO. Perhaps one day we can clean it up, at least this should make it a little easier.

typing: resultlog, pytester, longrepr

---

testing/test_unittest.py

Fix test_plain_unittest_does_not_support_async on pypy3

---

extra/get_issues.py
src/_pytest/_code/code.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/config/findpaths.py
src/_pytest/fixtures.py
src/_pytest/pathlib.py
src/_pytest/python.py
src/_pytest/resultlog.py
testing/acceptance_test.py
testing/test_config.py
testing/test_findpaths.py
testing/test_pathlib.py

The first commit adds analogues of `py.path.local`'s `bestrelpath` and `common` functions to `_pytest.pathlib`.
The second commit converts `_pytest.config.findpaths` to use pathlib.
The third commit coverts some random places to pathlib.

Some py.path -> pathlib conversions

---

src/_pytest/capture.py
testing/test_capture.py

Add type annotations to `CaptureFixture` and related classes, which are now parametrized by `str`/`bytes`.
In order to do this I needed to change `CaptureResult` from a namedtuple to a regular class, since mypy does support generic namedtuples (or regular tuples) currently (see first commit). I tried to keep it compatible with namedtuple to a reasonable level, so I don't consider it a breaking change, just adds some boilerplate. `CaptureResult` is pretty central to the `CaptureFixture` API so I didn't want to leave it untyped.

capture: add type annotations to CaptureFixture

---

README.rst

Currently the badge encourages you to set it up now. :)

Replace inactive Azure Pipelines badge with GHA

---

doc/en/warnings.rst

and include a demo of toml 'literal strings', which tripped me up: https://github.com/toml-lang/toml/issues/80#issuecomment-667617263

document toml use of filterwarnings

---

.coveragerc
src/_pytest/_code/code.py
src/_pytest/_code/source.py
src/_pytest/compat.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/mark/structures.py
src/_pytest/monkeypatch.py
src/_pytest/nodes.py
src/_pytest/pytester.py
src/_pytest/python_api.py
src/_pytest/recwarn.py
src/_pytest/reports.py

We used it as a shortcut for avoiding coverage, but pylint has a special interpretation of it as an abstract method which we don't want.
Refs #7591 (fixes the `get_closest_marker` case but not the others).

Don't use NotImplementedError in `@overload`s

---

changelog/7638.bugfix.rst
src/_pytest/config/findpaths.py
testing/test_findpaths.py

get_dirs_from_args handles paths with invalid syntax

---

changelog/7628.bugfix.rst
src/_pytest/main.py
testing/acceptance_test.py
testing/test_collection.py
testing/test_main.py
testing/test_terminal.py

Fix Module.name from full path without drive letter

---

changelog/7591.bugfix.rst
changelog/7648.deprecation.rst
src/_pytest/deprecated.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/python.py
testing/deprecated_test.py

This fixes #7591 where pylint complains about missing implementations of abstract methods in subclasses of `File` which only override `collect()` (as they should).
It is also cleaner and makes sense, these methods really don't need to be overridden.
The previous methods defined directly on `FSCollector` and `Package` are deprecated, to be removed in pytest 7.
See commits e2934c3f8c03c83469f4c6670c207773a6e02df4 and f10ab021e21a44e2f0fa2be66660c4a6d4b7a61a for reference.

Only define gethookproxy, isinitpath on Session

---

changelog/7148.bugfix.rst
src/_pytest/capture.py
testing/test_capture.py

The `CaptureManager.global_and_fixture_disabled()` context manager (and `CaptureFixture.disabled()` which calls it) did `suspend(); ...; resume()` but if the capturing was already suspended, the `resume()` would resume it when it shouldn't.
This caused caused some messages to be swallowed when `--log-cli` is used because it uses `global_and_fixture_disabled` when capturing is not necessarily resumed.

capture: fix disabled()/global_and_fixture_disabled() enabling capturing when it was disabled

---

src/_pytest/hookspec.py
src/_pytest/main.py

Make it a bit more accurate and use the same format that `pytest_runtest_protocol` uses.

hookspec: improve collection phase documentation a bit

---

src/_pytest/doctest.py
src/_pytest/hookspec.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/python.py

Collection starts in `Session.perform_collect()`. I am trying to understand what it does, but it's very complex (in the cyclomatic complexity sense) and hard to follow. This PR starts to try and reveal the inner beauty of the code :)
The PR is split into commits, each doing one refactoring. Most of them are straightforward (except for `Revert "Move common code between Session and Package to FSCollector"` perhaps) and should be easier to follow than reading the full diff.
The end result is that most of the logic is localized in the `Session.collect()` instead of being spread around many places. The next step would be to figure out what all of the caches and special cases do, and either simplify and document them, or (I suspect) plain remove them if they're not serving a purpose.

Start simplifying collection code in Session

---

doc/en/index.rst
doc/en/talks.rst

- Remove past webinar
- Add new open training
- Add some talks/webinars by Oliver Bestwalter and by me - I'm sure there have been more talks than those, but I don't have the time to go through years of conferences, so I just added the ones I remember
- Remove some stale link targets
Also, what do you think about moving the "Next Open Trainings" sidebar from the talks page to the main page? Right now it's quite hard to find the talks/tutorials page (and the training announcement) because it's also not part of the sidebar menu yet (I think it was with the old theme?).
IMHO it'd be nice to show it on the main page instead (since it's often only around for a couple of weeks/months anyways) to give those trainings a bit more visiblity - but since I'm probably the main person benefiting from …

Update talks/trainings page

---

changelog/7686.bugfix.rst
src/_pytest/python.py
testing/python/metafunc.py

Fixes #7686.
In ff8b7884e8f1019f60f270eab2c4909ff557dd4e `NOTSET` was changed to a singleton enum, which ended up unexpectedly triggering a code path in ID generation which checks for `isinstance(Enum)`.
Add an explicit case for it, which is not too bad anyway.

python: fix empty parametrize() leading to "NotSetType.token" id

---

changelog/7671.trivial.rst
src/_pytest/python.py
testing/python/collect.py

When a Python object (module/class/instance) is collected, for each name in `obj.__dict__` (and up its MRO) the `pytest_pycollect_makeitem` hook is called for potentially creating a node for it.
These Python objects have a bunch of builtin attributes that are extremely unlikely to be collected. But due to their pervasiveness,
dispatching the hook for them ends up being mildly expensive and also pollutes `PYTEST_DEBUG=1` output and such.
Let's just ignore these attributes.
On the pandas test suite commit 04e9e0afd476b1b8bed930e47bf60e, collect only, irrelevant lines snipped, about 5% improvement:
Before:
```
51195095 function calls (48844352 primitive calls) in 39.089 seconds
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
226602/54    0.145    0.000   38.940    0.721 …
```

RFC: python: skip work pytest_pycollect_makeitem work on certain names

---

doc/en/reference.rst
src/_pytest/nodes.py

Add missing File reference to the docs

---

src/_pytest/python.py
testing/python/collect.py

Inline `_makeitem()` so that `self.ihook` (which is moderately expensive) can be called only once.
Note: the removed test "test_makeitem_non_underscore" comes from an old behavior of skipping names that start with `_` which has since been generalized, making the test no longer relevant.

python: small optimization in PyCollector.collect()

---

src/_pytest/fixtures.py

I think the straight code is easier to understand.

fixture: remove `@scopeproperty`

---

changelog/6681.improvement.rst
src/_pytest/assertion/rewrite.py
src/_pytest/config/__init__.py
src/_pytest/faulthandler.py
src/_pytest/main.py
src/_pytest/warnings.py
testing/test_config.py
testing/test_warnings.py

Warnings are a central part of Python, so much that Python itself has
command-line and environtment variables to handle warnings.
By moving the concept of warning handling into Config, it becomes natural to
filter warnings issued as early as possible, even before the "_pytest.warnings"
plugin is given a chance to spring into action. This also avoids the weird
coupling between config and the warnings plugin that was required before.
Fix #6681
Fix #2891
Fix #7620
Fix #7626
Close #7649

Integrate warnings filtering directly into Config

---

changelog/7707.bugfix.rst
src/_pytest/_code/code.py
testing/code/test_excinfo.py

Fix handle of exceptions in ReprEntry with tb=line 

---

changelog/7685.improvement.rst
doc/en/customize.rst
src/_pytest/cacheprovider.py
src/_pytest/config/__init__.py
src/_pytest/fixtures.py
src/_pytest/logging.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/pathlib.py
src/_pytest/terminal.py
testing/test_main.py
testing/test_terminal.py

The first commit is a small doc improvement to make the Config info in the API reference more complete.
The second commit adds two new attributes to Config, `rootpath` and `inipath`, which are the `Path` equivalents of `rootdir` and `inifile`, and moves `rootdir` and `inifile` to properties. For now the new attributes are not documented, and the documentation still refers to the old attributes. I can change this if it seems like a good idea.
The third commit converts some code internally from the old attributes to the new. There is always a chance of some subtle change in behavior here; I tried to be careful but we'll have to live and see...

config: start migrating Config.{rootdir,inifile} from py.path.local to pathlib

---

changelog/7148.bugfix.rst
src/_pytest/capture.py
testing/test_capture.py

[6.0.x] capture: fix disabled()/global_and_fixture_disabled() enabling capturing when it was disabled

---

scripts/release-on-comment.py

The release-on-comment script is always executed on *master*, so we should
execute the `release.py` script using tox to ensure we create the
right environment.
Also fixed errors in the error handling code.

Use tox to execute release script

---

doc/en/reference.rst

Before, `PluginManager` was a copy of the pluggy doc, and `PytestPluginManager` was documented separately.
pytest users only really need to know about `PytestPluginManager`, so instead of splitting, have the `PytestPluginManager` documentation include all of `PluginManager` members and remove `PluginManager` from the reference (it is still shown as the base class).

doc/reference: include PluginManager in PytestPluginManager and remove it

---

doc/en/fixture.rst
doc/en/reference.rst
doc/en/usage.rst
src/_pytest/hookspec.py

When a name is exported from `pytest`, prefer to refer to it by that rather than its `_pytest` import path. It is shorter and more appropriate in user-facing documentation (although that's not really visible).
Our plan is to expose more names for typing purposes, in which can this could be more comprehensive.

doc: prefer to reference by public name when possible

---

changelog/7667.feature.rst
doc/en/usage.rst
src/_pytest/runner.py

Enables users to use custom values for the threshold used to determine slow tests.

Make min duration configurable for slowest tests

---

AUTHORS
doc/en/example/pythoncollection.rst

PR reference: https://twitter.com/pytestdotorg/status/1302444196842725376?s=20
This example page seemed to be the best location.  Anywhere else you recommend?

Add example for __test__

---

CONTRIBUTING.rst

- be more vague about "packaging metadata" over explicitly mentioning `setup.py`
(such that `pyproject.toml`-based distributions are allowed)
- drop extensions on `README.txt` / `LICENSE.txt` (it's more common to have `.md`
/ `.rst` / no extension)
- remove duplicate mention of license packaging metadata

Update pytest-dev requirements

---

changelog/7148.bugfix.rst
changelog/7672.bugfix.rst
changelog/7686.bugfix.rst
changelog/7707.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-6.0.2.rst
doc/en/changelog.rst
doc/en/getting-started.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/7718#issuecomment-687405508.
can be released by pushing a tag `6.0.2` to this repository.

Prepare release 6.0.2

---

changelog/1953.bugfix.rst
src/_pytest/fixtures.py
testing/python/fixtures.py

Allow ovewriting a parametrized fixture while reusing the parent fixture's value

---

changelog/7742.bugfix.rst
src/_pytest/_code/code.py
testing/code/test_excinfo.py

Fix INTERNALERROR when accessing locals / globals with faulty `exec`

---

.github/workflows/main.yml

should be a noop (despite the major version bump) -- I rewrote the action to be more stable and need fewer security updates

Update to deadsnakes/action@v2.0.0

---

doc/en/reference.rst
doc/en/usage.rst

Add full command-line flags to the reference docs

---

doc/en/mark.rst

There's no hyphen in the word.

Mistyped was mistyped

---

changelog/4984.bugfix.rst
src/_pytest/assertion/rewrite.py
testing/test_collection.py

Fixes #4984.
Note: interesting change in the 2nd commit, first one is just preparation.
For decorated functions, the lineno of the FunctionDef AST node points to the `def` line, not to the first decorator line. On the other hand, in code objects, the `co_firstlineno` points to the first decorator line.
Assertion rewriting inserts some imports to code it rewrites. The imports are inserted at the lineno of the first statement in the AST. In turn, the code object compiled from the rewritten AST uses the lineno of the first statement (which is the first inserted import).
This means that given a module like this,
```py
@foo
@bar
def baz(): pass
```
the lineno of the code object without assertion rewriting (`--assertion=plain`) is 1, but with assertion rewriting it is 3.
And *this* causes some …

assertion/rewrite: fix internal error on collection error due to decorated function

---

changelog/7572.improvement.rst
src/_pytest/config/__init__.py
testing/test_config.py

Before:
```
File "./.tox/py38/bin/pytest", line 33, in <module>
sys.exit(load_entry_point('pytest', 'console_scripts', 'pytest')())
File "/home/florian/proj/pytest/src/_pytest/config/__init__.py", line 180, in console_main
code = main()
File "/home/florian/proj/pytest/src/_pytest/config/__init__.py", line 136, in main
config = _prepareconfig(args, plugins)
File "/home/florian/proj/pytest/src/_pytest/config/__init__.py", line 313, in _prepareconfig
config = pluginmanager.hook.pytest_cmdline_parse(
File "/home/florian/proj/qutebrowser/git/.tox/py38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/home/florian/proj/qutebrowser/git/.tox/py38/lib/python3.8/site-packages/pluggy/ …
```

Improve output for missing config keys

---

CONTRIBUTING.rst

From https://github.com/pytest-dev/pytest/pull/7723#issuecomment-693310439
cc @The-Compiler @bluetech @RonnyPfannschmidt @asottile

Add guidelines section about backporting

---

.github/workflows/main.yml
pyproject.toml
src/_pytest/config/__init__.py
src/_pytest/python.py
testing/plugins_integration/.gitignore
testing/plugins_integration/README.rst
testing/plugins_integration/bdd_wallet.feature
testing/plugins_integration/bdd_wallet.py
testing/plugins_integration/django_settings.py
testing/plugins_integration/pytest.ini
testing/plugins_integration/pytest_anyio_integration.py
testing/plugins_integration/pytest_asyncio_integration.py
testing/plugins_integration/pytest_mock_integration.py
testing/plugins_integration/pytest_qt_integration.py
testing/plugins_integration/pytest_trio_integration.py
testing/plugins_integration/pytest_twisted_integration.py
testing/plugins_integration/simple_integration.py
testing/test_assertrewrite.py
testing/test_config.py
tox.ini

This aims to create a tox environment that tests that installation of
popular plugins does not break pytest.
Related to https://github.com/pytest-dev/pytest-cov/issues/430

Smoke tests for assorted plugins

---

RELEASING.rst

The previous order is not really possible to perform -- before merging there is no release commit in the `MAJOR.MINOR.x` branch.

RELEASING: ~~first merge PR, then tag~~ clarify where to push the tag 

---

doc/en/fixture.rst

Add docs about reusing fixtures from other projects

---

changelog/7780.improvement.rst
src/_pytest/_code/code.py
src/_pytest/_io/terminalwriter.py
src/_pytest/cacheprovider.py
src/_pytest/capture.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/config/argparsing.py
src/_pytest/config/exceptions.py
src/_pytest/fixtures.py
src/_pytest/logging.py
src/_pytest/main.py
src/_pytest/mark/structures.py
src/_pytest/monkeypatch.py
src/_pytest/pytester.py
src/_pytest/python.py
src/_pytest/python_api.py
src/_pytest/recwarn.py
src/_pytest/reports.py
src/_pytest/runner.py
src/_pytest/terminal.py
src/_pytest/tmpdir.py
src/_pytest/warning_types.py

Some work toward #7469.
This ([ref](https://docs.python.org/3/library/typing.html#typing.final)) indicates at least for people using type checkers that these classes are not designed for inheritance and we make no stability guarantees when inheriting from them.
Currently this doesn't show up in the docs. Sphinx does actually support `@final`, however it only works when imported directly from `typing`, while we import from `_pytest.compat`.
In the future there might also be a `@sealed` decorator which would cover some more cases.

Mark some public and to-be-public classes as `@final`

---

AUTHORS
doc/en/writing_plugins.rst

1. Renamed the  sample hook declaration file to "sample_hook.py" from "hooks.py".
2. Added the @hookimpl decorator to example functions.
3. Added name to AUTHORS.
closes #7706

Improved 'Declaring new hooks' section in docs.

---

doc/en/writing_plugins.rst

Improve docs about plugin discovery/loading at startup

---

.github/workflows/main.yml
changelog/7802.trivial.rst
setup.cfg
src/_pytest/_code/code.py
src/_pytest/assertion/util.py
src/_pytest/compat.py
testing/test_assertion.py
testing/test_meta.py
testing/test_unittest.py
tox.ini

This allows us to remove the `ATTRS_EQ_FIELD` thing which is causing some annoyance.

Bump attrs requirement from >=17.4.0 to >=19.2.0

---

changelog/7807.bugfix.rst
src/_pytest/config/findpaths.py
testing/test_config.py

Fixes #7807.
When switching from py.path.local to pathlib (70f3ad1c1f31b35d4004f92), `local.parts(reverse=True)` was translated incorrectly, leading to the wrong rootdir being determined in some non-trivial cases where parent directories have config files as well.

findpaths: fix regression causing incorrect rootdir to be determined

---

changelog/7807.bugfix.rst
src/_pytest/config/findpaths.py
testing/test_config.py

[6.1.x] findpaths: fix regression causing incorrect rootdir to be determined

---

doc/en/doctest.rst

Make minor grammar changes in doctest.rst

---

doc/en/builtin.rst
doc/en/tmpdir.rst
setup.cfg
src/_pytest/pathlib.py
src/_pytest/tmpdir.py

py36+: remove pathlib2 compatibility shim

---

src/_pytest/compat.py
testing/acceptance_test.py
testing/test_collection.py
testing/test_doctest.py

py36+: remove _pytest.compat.MODULE_NOT_FOUND_ERROR

---

doc/en/skipping.rst
src/_pytest/capture.py
src/_pytest/compat.py
testing/acceptance_test.py
testing/test_capture.py
testing/test_compat.py

py36+: miscellaneous (3, 6) cleanup

---

src/_pytest/mark/__init__.py
src/_pytest/mark/structures.py
src/_pytest/python.py

py36+: replace typing.X with X

---

src/_pytest/_code/code.py
src/_pytest/python_api.py
src/_pytest/recwarn.py

py36+: remove workaround for Union[Pattern/Match] bug

---

testing/conftest.py
testing/test_terminal.py

py36+: remove requires_ordered_markup

---

changelog/7814.bugfix.rst
src/_pytest/pathlib.py
src/_pytest/terminal.py
testing/test_terminal.py

Regressed in 6.1.0 in 62e249a.
The `x` is an `str` but is expected to be a `pathlib.Path`. Not caught by mypy because `config.getini()` returns `Any`.
Fix by just removing the `bestrelpath` call:
- testpaths are always relative to the rootdir, it thus would be very unusual to specify an absolute path there.
- The code was wrong even before the regression: `py.path.local`'s `bestrelpath` function expects a `py.path.local`, not an `str`. But it had some weird `try ... except AttributeError` fallback which just returns the argument, i.e. it was a no-op. So there is no behavior change.
- It seems reasonable to me to just print the full path if that's what the ini specifies.
The two other commits are related improvements.

terminal: fix crash in header reporting when absolute testpaths is used

---

changelog/7814.bugfix.rst
src/_pytest/terminal.py
testing/test_terminal.py

Backport of commit 61f80a783a38441040c5999a4033af8004ee4c6b from #7817.

[6.1.x] terminal: fix crash in header reporting when absolute testpaths is used

---

changelog/7780.doc.rst
doc/en/conf.py

Continuation to #7780, makes the `final class` also show up in the API Reference.
Thanks to @domdfcoding for code & assistance.
Compared to @domdfcoding's code, I made it less accurate (just accepts any `@final` as an indicator, disregarding where it's imported from), but simpler and hopefully more robust against changes in Sphinx. Since it's only scoped to pytest it shouldn't be a problem.
We also have a similar issue with `@overload`, but that should take care of itself after #7811 is merged (as confirmed by the RTD build of that PR).

doc: patch Sphinx to detect our `@final` for marking classes as `final`

---

src/_pytest/assertion/rewrite.py
src/_pytest/compat.py

py36+: remove _pytest.compat.fspath

---

src/_pytest/mark/structures.py
testing/test_assertion.py

py36+: resolve py36 TODOs

---

src/_pytest/_code/code.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/debugging.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/mark/structures.py
src/_pytest/nodes.py
src/_pytest/outcomes.py
src/_pytest/pytester.py
src/_pytest/python.py
src/_pytest/python_api.py
src/_pytest/recwarn.py
src/_pytest/reports.py
src/_pytest/runner.py
src/_pytest/skipping.py
src/_pytest/unittest.py
src/_pytest/warning_types.py
testing/test_config.py
testing/test_monkeypatch.py
testing/test_runner.py

py36+: from typing import Type: no longer need guard

---

tox.ini

This adds pytest-rerunfailures to the plugin smoke tests.
**It will currently fail**, because of the 6.1.0 removals: https://github.com/pytest-dev/pytest-rerunfailures/issues/128, which has affected at least pip (https://github.com/pypa/pip/issues/8925) and matplotlib (https://github.com/matplotlib/matplotlib/issues/18593).
But once it's been fixed, this can be merged and hopefully catch the _next_ removals.

Smoke test pytest-rerunfailures

---

src/_pytest/_code/code.py
src/_pytest/_code/source.py
src/_pytest/assertion/rewrite.py
src/_pytest/compat.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/mark/structures.py
src/_pytest/monkeypatch.py
src/_pytest/nodes.py
src/_pytest/pytester.py
src/_pytest/python_api.py
src/_pytest/recwarn.py

py36+: remove _pytest.compat.overload

---

pyproject.toml
src/_pytest/_io/saferepr.py
src/_pytest/_io/terminalwriter.py
src/_pytest/compat.py
src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/mark/__init__.py
src/_pytest/mark/structures.py
src/_pytest/pathlib.py
src/_pytest/pytester.py
src/_pytest/python.py
src/_pytest/python_api.py
src/_pytest/recwarn.py
src/_pytest/reports.py
src/_pytest/terminal.py

py36+: update the target version of black to py36

---

changelog/7807.bugfix.rst
changelog/7814.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-6.1.1.rst
doc/en/changelog.rst
doc/en/getting-started.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/7843#issuecomment-703150391.
can be released by pushing a tag `6.1.1` to this repository.

Prepare release 6.1.1

---

src/_pytest/fixtures.py
src/_pytest/nodes.py
testing/python/fixtures.py

fixtures: some type annotations, remove cyclic dependency

---

changelog/7815.doc.rst
src/_pytest/deprecated.py
src/_pytest/fixtures.py
src/pytest/__init__.py
testing/deprecated_test.py
testing/python/fixtures.py

@Zac-HD Yes, this is related to the issue #7815. I could come up with a better format for the warning if it is needed.

Add alias clarification to deprecation warning

---

src/_pytest/cacheprovider.py
src/_pytest/compat.py
src/_pytest/fixtures.py
src/_pytest/terminal.py

py36+: remove _pytest.compat.order_preserving_dict

---

changelog/7872.doc.rst
src/_pytest/config/__init__.py
src/_pytest/config/argparsing.py
testing/test_config.py

Document that Parser.addini() can take, and defaults to, 'string'

---

AUTHORS
src/_pytest/terminal.py

Use `collections.Counter` instead of a `dict` in `terminal.py` Closes #7868

Use collections.Counter instead of a dict - Closes #7868

---

CONTRIBUTING.rst
changelog/7878.doc.rst

closes #7878
In the contribution guidelines (https://github.com/charlesaracil-ulti/pytest/blob/master/CONTRIBUTING.rst#long-version), section 8 asks to commit, and then offers add a changelog and edit the authors file. So following those guideline verbatim will have those last two items excluded from the push.
I might be better to ask for commit after changelog and authors file edit.

ask for commit after changelog and authors file edit in contributing

---

.github/dependabot.yml
testing/plugins_integration/requirements.txt
tox.ini

Here's an idea.
This moves the smoke test deps from https://github.com/pytest-dev/pytest/pull/7721 into a `requirements.txt` so they can pinned.
Then, https://dependabot.com can be added to monitor this new `requirements.txt` and send a new PR when there's a new plugin release. Add `/testing/plugins_integration` as the Directory:
That means we get a trigger when new plugins are released, which increases confidence that current master works with each plugin.
For example, see https://github.com/hugovk/pytest/pull/6 and https://github.com/hugovk/pytest/pull/7 on a similar branch on my fork.
Upsides:
* Triggers a build on plugin releases
* Always smoke test latest plugin version (as before)
Downsides:
* More PRs.
* If they're too frequent, the update schedule could be changed from live to …

Put smoke test deps in requirements.txt for Dependabot

---

changelog/7425.feature.rst
doc/en/reference.rst
src/_pytest/pytester.py
src/_pytest/warning_types.py
testing/acceptance_test.py
testing/test_doctest.py
testing/test_pytester.py

New pytester fixture with same functionality as testdir, but dealing
with pathlib.Path objects.
Also:
* Change Testdir to be a thin wrapper which only delegates to PyTester.
* Convert test_doctest to use test_path and tmp_path.
* Removed some str() calls now unnecessary given py35 support has been dropped.
* Use test_path in test_no_brokenpipeerror_message: it uses a private method
which I don't think we should expose in Testdir for now.
Replaces #7425.

New pytester fixture

---

AUTHORS
doc/en/example/markers.rst

Add example for registering multiple custom mark

---

doc/en/reference.rst
src/_pytest/pytester.py

Also include docstrings pointing to the counterparts in Pytester.
Fix #7892

List Testdir members in the docs

---

doc/en/reference.rst
doc/en/writing_plugins.rst

Added note to writing_plugins.rst

---

changelog/7758.bugfix.rst
src/_pytest/cacheprovider.py
testing/test_cacheprovider.py

Fixes #7758. There are several reports in there, I only checked the one from #7894, but let's hope it also fixes the pandas report.
`--lf` has an optimization where it skips collecting Modules (python files) which don't contain failing tests. The optimization works by getting the paths of all cached failed tests and skipping the collection of Modules whose path is not included in that list.
In pytest, Package nodes are Module nodes with the fspath being the file `<package dir>/__init__.py`. Since it's a Module the logic above triggered for it, and because it's an `__init__.py` file which is unlikely to have any failing tests in it, it is skipped, which causes its entire directory to be skipped, including any Modules inside it with failing tests.
Fix by special-casing Packages to never …

cacheprovider: fix some files in packages getting lost from --lf

---

changelog/7758.bugfix.rst
src/_pytest/cacheprovider.py
testing/test_cacheprovider.py

[6.1.x] cacheprovider: fix some files in packages getting lost from --lf

---

.github/workflows/main.yml

We don't have any jobs that should go beyond that, so let's be nicer to
the CI host and quicker to report the failure.

ci: decrease job timeout from 6 hours to 30 minutes

---

doc/en/reference.rst

Fix small typo in reference.rst

---

doc/en/tmpdir.rst

The "os" imports in the `tmp_path` and `tmpdir` fixture examples are
unused and thus have been removed to prevent confusion.

doc: Remove unused imports in examples

---

bench/xunit.py
src/_pytest/python.py

Refs #4824 (as mentioned below there is still some slowness we should look at, so not closing)
Since commit 0f918b1a9dd14a2d046 pytest uses auto-generated autouse pytest fixtures for the xunit fixtures `{setup,teardown}_{module,class,method,function}`. All of these fixtures were given the same name.
Unfortunately, pytest fixture lookup for a name works by grabbing all of the fixtures globally declared with a name and filtering to only those which match the specific node. So each xunit-using item iterates over a list (of fixturedefs) of a size of all previous same-xunit-using items, i.e. quadratic.
Fixing this properly to use a better data structure is likely to take some effort, but we can avoid the immediate problem by just using a different name for each item's autouse fixture, so it …

python: fix quadratic behavior in collection of items using xunit fixtures

---

src/_pytest/hookspec.py

Hey, very minor adjustment - was reading through hookspecs to build my understanding and noticed the `triple` term used in place of `tuple`, thought I should make that technically correct.
Thanks - have a wonderful weekend 👍

Replace term 'triple' with 'tuple' in hookspec docstrings

---

changelog/4824.bugfix.rst
src/_pytest/fixtures.py
src/_pytest/nodes.py
testing/python/fixtures.py
testing/test_nodes.py

Fixes #4824. This contains 3 commits which optimize the slow parts of xunit/autouse fixtes, the last commit fixes the remaining quadratic behavior (continuation of #7929). Please see the commit messages for details.
On the bench/xunit.py benchmark, `--collect-only`, before:
```
51895636 function calls (51265006 primitive calls) in 25.618 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000   25.101   25.101 main.py:320(pytest_collection)
1    0.000    0.000   25.101   25.101 main.py:567(perform_collect)
80560/556    0.020    0.000   24.472    0.044 {method 'extend' of 'list' objects}
85001/15001    0.148    0.000   24.468    0.002 main.py:785(genitems)
10002    0.044    0.000   23.705    0.002 …
```

fixtures: fix quadratic behavior in the number of autouse fixtures

---

changelog/7913.bugfix.rst
src/_pytest/pytester.py
testing/test_assertrewrite.py
testing/test_debugging.py
testing/test_pytester.py
testing/test_runner.py
testing/test_terminal.py

This fixes #7913 (hopefully). There are some other commits I made to testing while debugging this but they are not critical.

testing: fix pexpect hang

---

testing/conftest.py

testdir uses pytester so this applies to it as well, but now includes pytester as well.

testing: make conftest stuff check for pytester not testdir

---

testing/test_mark.py
testing/test_warning_types.py

Good afternoon, This PR refactors `test_mark.py` & `test_warning_types.py` to use the newer `pytester` fixture in place of testdir.
Some type hinting was problematic, as was `pytester.tmpdir` / `basename`
relates to #7942

Refactor test_warning_types.py & test_mark.py to use pytester 

---

AUTHORS
testing/test_skipping.py

Converts test_skipping.py from testdir to pytester. All tests are passing locally.

Migrate test_skipping.py from testdir to pytester

---

changelog/7758.bugfix.rst
changelog/7815.doc.rst
changelog/7911.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-6.1.2.rst
doc/en/changelog.rst
doc/en/getting-started.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/7957.
can be released by pushing a tag `6.1.2` to this repository.
Closes #7957.

Prepare release 6.1.2

---

testing/test_assertrewrite.py

Converts test_assertrewrite.py from testdir to pytester

Migrate test_assertrewrite.py from testdir to pytester

---

testing/test_setuponly.py

Converts `test_setuponly.py` from testdir to pytester

Migrate test_setuponly.py from testdir to pytester

---

.pre-commit-config.yaml
setup.cfg
tox.ini

We run mypy through pre-commit, and we don't keep duplicate targets in tox for all of the other linters. Since this adds some (small) maintenance overhead, remove it.

tox: remove checkqa-mypy environment

---

.pre-commit-config.yaml

Otherwise, mypy doesn't know about them and their types are considered `Any`.

pre-commit: install typed dependencies in the mypy target

---

changelog/7938.improvement.rst
src/_pytest/stepwise.py
testing/test_stepwise.py

Hi team, hope you are all keeping well.  While trying to advance my knowledge of the project I have been understanding plugins a little bit.  Here is a small PR to tidy up some of the stepwise plugin code for consistency.  Some of the most important changes are:
- Stop registering the plugin if stepwise itself is not active (rather than these constant is_active checks inside hooks).
- Adding a --sw-skip shorthand option to mirror that of --sw itself
- Added a pytest_sessionfinish hook to stepwise (this is because --cache-clear was always outputting the [] now, I wanted to keep --cache-clear accurate in such circumstances and claim the cache is 'empty' ? However (imo) this should be handled in pytest_unconfigure and when --sw is not present, stepwise is always writing the [] upfront.  - …

#7938 - [Plugin: Stepwise][Enhancements] Refactoring, smarter registration & --sw-skip functionality

---

testing/test_error_diffs.py

Converts test_error_diffs.py from testdir to pytester

Migrate test_error_diffs.py from testdir to pytester

---

changelog/7981.bugfix.rst
src/_pytest/pathlib.py
testing/test_collection.py

pathlib: fix symlinked directories not followed during collection

---

AUTHORS
changelog/7527.improvement.rst
src/_pytest/assertion/util.py
testing/test_assertion.py

Add support to display field names in namedtuple diffs.

---

AUTHORS
changelog/7951.bugfix.rst
src/_pytest/pathlib.py
testing/test_collection.py
testing/test_pathlib.py

When pytest was run on a directory containing a recursive symlink it failed
with ELOOP as the library was not able to determine the type of the
direntry:
src/_pytest/main.py:685: in collect
if not direntry.is_file():
E   OSError: [Errno 40] Too many levels of symbolic links: '/home/florian/proj/pytest/tests/recursive'
This is fixed now by handling ELOOP.
Fixes #7951

Fix handling recursive symlinks

---

bench/unit_test.py
src/_pytest/unittest.py

This is similar to 50114d4731876dae; I missed that unittest does the same thing.

unittest: fix quadratic behavior in collection of unittests using setUpClass/setup_method

---

AUTHORS
testing/test_session.py

This PR does the following things:
1. Migrates ```test_session.py``` from ```testdir``` to ```Pytester```.
2. Adds name to ```AUTHORS```.

#7942 test_session.py migrate from testdir to Pytester

---

pyproject.toml

Fixes #7991.
This causes some tests to fail when using these older versions.

testing: silence deprecation warning from older pyparsing releases

---

changelog/7530.deprecation.rst
doc/en/deprecations.rst
src/_pytest/config/__init__.py
src/_pytest/deprecated.py
src/_pytest/main.py
src/_pytest/mark/structures.py
testing/deprecated_test.py

Deprecate --strict

---

doc/en/example/markers.rst
doc/en/example/simple.rst

Only 3 upper case character. But because the docs are so perfect already.

Capitalize headlines

---

pyproject.toml

The test suite passes without it being ignored. The absence of this warning cost me some head-scratching time, so enable it again.

testing: don't ignore "Module already imported so cannot be rewritten" warning

---

src/_pytest/cacheprovider.py
src/_pytest/capture.py
src/_pytest/logging.py
src/_pytest/monkeypatch.py
src/_pytest/pytester.py
src/_pytest/terminal.py
src/_pytest/tmpdir.py

Don't import `pytest` from within some `_pytest` modules since an upcoming commit will import from them into `pytest`.
It would have been nice not to have to do it, so that internal plugins look more like external plugins, but with the existing layout this seems unavoidable.

Stop importing `pytest` to avoid upcoming import cycles

---

changelog/7981.bugfix.rst
doc/en/changelog.rst
src/_pytest/pathlib.py
testing/test_collection.py

Backport #7978.
Backport #7982.

[6.1.x] Two backports

---

AUTHORS
changelog/7951.bugfix.rst
src/_pytest/pathlib.py
testing/test_collection.py
testing/test_pathlib.py

[6.1.x] Fix handling recursive symlinks

---

changelog/7701.improvement.rst
doc/en/example/nonpython.rst
doc/en/example/parametrize.rst
doc/en/example/pythoncollection.rst
doc/en/fixture.rst
src/_pytest/terminal.py
testing/logging/test_reporting.py
testing/python/metafunc.py
testing/test_cacheprovider.py
testing/test_terminal.py

Hey,
This PR intends to improve on the output of the summary stats line when using the `--collection-only`. I wrote it a bit "hackishly" because I was discovering the codebase so any feedback on improving the code, or the behavior, would be greatly appreciated. I also took the liberty of updating the existing tests to match this new behavior.
I tried to make the behavior similar to what was requested in #7701 and it results in something similar to:
```
==== 114 selected, 2891 deselected, no tests ran in 1.50s ====
```
Additionally, I noticed that in the examples found in the documentation, it only displays contexts where only "no tests ran in (...)s" happens...would it make sense to add more examples of different outputs?
Closes #7701.
Let me know how you feel about this.
Thanks!

Improve summary stats when using '--collect-only'

---

changelog/8006.feature.rst
doc/en/reference.rst
src/_pytest/monkeypatch.py
src/pytest/__init__.py
testing/test_monkeypatch.py

We want to export `pytest.MonkeyPatch` for the purpose of type-annotating the `monkeypatch` fixture. For other fixtures we export in this way, we also make direct construction of them (e.g. `MonkeyPatch()`) private. But unlike the others, `MonkeyPatch` is also widely used directly already, mostly because the `monkeypatch` fixture only works in `function` scope (issue #363), but also in other cases. So making it private will be annoying and we don't offer a decent replacement yet.
So, let's just make direct construction public & documented.

Export MonkeyPatch as pytest.MonkeyPatch

---

changelog/8016.bugfix.rst
src/_pytest/main.py
testing/test_doctest.py

Fixes #8016. Closes #8015.
When `--doctest-modules` is used, an `__init__.py` file is not a `Package` but a `DoctestModule`, but some collection code assumed that `__init__.py` implies a `Package`. That code caused only a single test to be collected in the scenario in the subject.
Tighten up this check to explicitly check for `Package`. There are better solutions, but for another time.
Report & test by @gatesn.

main: fix only one doctest collected on pytest --doctest-modules __init__.py

---

.gitignore

GitHub Codespaces automatically create a pythonenv folder. For example: `pythonenv3.8/` which containts a virtual environment. This should not be commited by default.

Add pythonenv* to gitignore

---

changelog/8014.trivial.rst
src/_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

Python 3.7 changed the pyc format by adding a flags word: https://www.python.org/dev/peps/pep-0552/. Even though it is not necessary for us to match it, it is nice to be able to read pyc files we emit with standard tools for debugging the rewriter.
Update our custom pyc files to use that format. We write flags==0 meaning we still use the mtime+size format rather than the newer hash format.

assertion/rewrite: write pyc's according to PEP-552 on Python>=3.7

---

.github/workflows/main.yml

First commit fixes this message:
> The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Second commit updates the cache action: https://github.com/actions/cache/releases/tag/v2.0.0
Third commit updates the py39 job to use the final release.

ci: fix deprecation message & couple updates

---

src/_pytest/pytester.py

only reference `nextline` inside the while loop of `LineMatcher._match_lines` rather than set it to None upfront needlessly.

stop assigning nextline if its potentially not used

---

src/_pytest/python_api.py
src/_pytest/recwarn.py
testing/conftest.py

AFAIK it's good practice to only `import pytest` and not individual functions (`from pytest import raises`).
Therefore code examples should have the context managers prefixed with the module name.

Prefix contextmanagers with module name in doc examples

---

AUTHORS
doc/en/nose.rst

This change was initiated after a discussion found [here](https://github.com/pytest-dev/pytest/discussions/8024#discussioncomment-127351).
The section currently features the `nose2pytest` tool with plans to expand
on some of the common gotchas when performing such migrations.
Questions for reviewers:
- Should I update the the CHANGELOG - I think it's not necessary.
- Should I add myself to AUTHORS - the change seems pretty small so I'll leave it for now.

Add small section on migrating from nose to pytest.

---

doc/en/nose.rst

Follow-up to #8048 which seems to have been merged without the suggested changes.
cc @nicoddemus @mickeypash

Fix nose documentation

---

doc/en/assert.rst
doc/en/skipping.rst
doc/en/warnings.rst
src/_pytest/recwarn.py

This will help users to get additional information on the functions if needed.

DOC: Link mentioned functions instead of using literals

---

changelog/7615.improvement.rst
src/_pytest/nodes.py
testing/test_nodes.py

Hi all, as per #7615 This pr enabled the item `node.warn` to handle any subclass of Warning rather than be explicitly locked to instances / subclass of PytestWarning.  I am not entirely sure on the 'use-case' for this but I'm just working on contributions and came across the issue.  Normally I wouldn't be a fan of isinstance checking and raising a ValueError under such scenario(s) but I kept the same internals as previously here because otherwise a generic TypeError is raised which offers little benefit to the  caller.
Thanks!

permit node to warn with any warning type, not just PytestWarning

---

changelog/1265.improvement.rst
doc/en/reference.rst
src/_pytest/pytester.py
testing/test_pytester.py

Added `__str__` method to LineMatcher class.
The `LineMatcher` class is used in the `RunResult` class, which has the `stdout` attribute, which is an instance of `LineMatcher`. `result.stdout.str()` is used 66 times in the codebase. The use of the `str()` function is mentioned [here](https://github.com/pytest-dev/pytest/blob/8ea8cdb36d031206742e609975ba0393533db92c/src/_pytest/pytester.py#L512-L517) as well. If I should make any other changes. Since `.str()` is used throughout the codebase, changing everything to `str(matcher)` seems pointless.
If you think a test should be added, let me now, however it is implicitly tested in the `Pytester` tests.
Closes #1265

Add str() support to LineMatcher

---

changelog/7425.feature.rst
changelog/7527.improvement.rst
changelog/7710.improvement.rst
changelog/7911.bugfix.rst
changelog/7913.bugfix.rst
changelog/8023.improvement.rst
changelog/8032.improvement.rst

While adding links to https://github.com/pytest-dev/pytest/pull/8052, noticed
a few more missing.

Add links to some CHANGELOG entries

---

src/_pytest/timing.py

Digging through the repo, apologies for nit picking :) came across a small typo for the fixture that resides in `testing/conftest.py` and corrected it.

fix mock_timing fixture name (typo) in timing.py

---

AUTHORS
testing/acceptance_test.py

Partial fix for https://github.com/pytest-dev/pytest/issues/7942
This PR does the following things:
- Refactors acceptance_test.py from using testdir to using pytester.
- Add myself to AUTHORS

Refactor acceptance_test to use pytester

---

AUTHORS
doc/en/reference.rst

[Issue](https://github.com/pytest-dev/pytest/issues/8020) stated that ordering of multiple custom markers is from inside - out. Following are the changes in this PR:
1. Added explanation to use multiple custom markers.
2. Added python code samples for the same in the documentation. 
Please let me know for further changes / concerns.

Custom multiple marker execution order

---

testing/test_nose.py

This PR does the following:
* Refactors test_nose.py from testdir to pytester

Migrate test_nose.py from testdir to pytester

---

testing/test_parseopt.py

This PR does the following:
* Refactors test_parseopt.py from testdir to pytester

Migrate test_parseopt.py from testdir to pytester

---

changelog/7469.deprecation.rst
changelog/7469.improvement.rst
doc/en/reference.rst
src/_pytest/cacheprovider.py
src/_pytest/capture.py
src/_pytest/config/__init__.py
src/_pytest/deprecated.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/logging.py
src/_pytest/pytester.py
src/_pytest/pytester_assertions.py
src/_pytest/python.py
src/_pytest/recwarn.py
src/_pytest/tmpdir.py
src/pytest/__init__.py
testing/deprecated_test.py
testing/python/fixtures.py
testing/test_cacheprovider.py
testing/test_recwarn.py
testing/test_tmpdir.py

The first commit is a hack to fix the issue discussed here: https://github.com/pytest-dev/pytest/issues/7469#issuecomment-723304224
The second commit is a partial fix for #7469 -- only for the fixture types. If this is accepted I will work on the other items on the list, but the fixtures are the most urgent so I'm starting with them.
Please see the commit messages for the approach I took, particularly the "privacy" mechanism in the second commit.

Export types of builtin fixtures for type annotations

---

changelog/5299.feature.rst
doc/en/reference.rst
doc/en/usage.rst
src/_pytest/config/__init__.py
src/_pytest/pytester.py
src/_pytest/threadexception.py
src/_pytest/unraisableexception.py
src/_pytest/warning_types.py
src/pytest/__init__.py
testing/acceptance_test.py
testing/test_threadexception.py
testing/test_unraisableexception.py

Fixes #5299. 
Please see the added documentation for details. The first two commits just fix a couple of issues this found in our own testsuite.
While the two plugins are very similar, I chose to keep them separate because I think it's cleaner and so they may be disabled separately.
Performance-wise this adds about 3% to the pure pytest overhead, which seems fine.

Add unraisableexception and threadexception plugins

---

src/_pytest/tmpdir.py

Explanation: The default handling of these lifetimes is done in
`tmpdir.TempPathFactory.getbasetemp`, which passes `keep=3` to
`pathlib.make_numbered_dir_with_cleanup`.
GH Issue: #8036

Docs: Note lifetime of temporary directories

---

testing/python/approx.py
testing/test_capture.py
testing/test_config.py
testing/test_terminal.py

Partial fix for #7942, included:
* ~`testing/test_config.py`~ - reverting this helped to address the build failure described below
* `testing/test_config.py`
* `testing/test_terminal.py` - migrated it to `pytester` as well to see if it would make any difference with the failure described below (it didn't)
* `testing/python/approx.py`
**EDIT:** Issue fixed in 009e04c. Migrated `testing/test_config.py` as well.
Don't have much context, but could the issue described below hint that `pytester` leaks fd more than `testdir` - https://github.com/pytest-dev/pytest/runs/1513744446?check_suite_focus=true ? Note - reverting `test_config.py` to `testdir` helped. 
24 similar errors from `testing/test_terminal.py` (test_summary_stats, test_skip_counting_towards_summary), like:
```
______ ERROR at setup …
```

Migrate to pytester: test_capture.py, test_terminal.py, approx.py

---

.github/workflows/main.yml
pyproject.toml
setup.cfg
tox.ini

Proposal for #8117 
@bluetech - I pinned the min versions for some of the packages to the current latest in `tox.ini` (so pip will resolve them sooner). Builds are running faster now ([ubuntu-py37-pluggy](https://github.com/pytest-dev/pytest/runs/1532409214?check_suite_focus=true) ~2min).

infrastructure: Stricter tox dependensies

---

changelog/7695.feature.rst
src/_pytest/hookspec.py
src/_pytest/skipping.py
testing/test_skipping.py

This is same as #7695 but rebased, one tiny style issue and changed from testdir -> pytester.
Closes #7695
---
Add a new hook , `pytest_markeval_namespace` which should return a dictionary.
This dictionary will be used to augment the "global" variables available to evaluate skipif/xfail/xpass markers.
Pseudo example
``conftest.py``:
```py
def pytest_markeval_namespace():
return {"color": "red"}
```
``test_func.py``:
```py
@pytest.mark.skipif("color == 'blue'", reason="Color is not red")
def test_func():
assert False
```

Add `pytest_markeval_namespace` hook.

---

tox.ini

Causes some [trouble in CI](https://github.com/pytest-dev/pytest/issues/8101#issuecomment-743780316) and not really needed as old pip should still work.

tox: remove requires: pip>=20.3.1

---

tox.ini

The env var effects all of the pip installs, including regendoc which
also uses setuptools-scm, so it gets the wrong version, and fails to
install with the new pip resolver:
ERROR: Requested regendoc from https://files.pythonhosted.org/packages/a8/5d/206e4951420bf5bbe1475c66eb06ec40d9177035e223858fee890eed0188/regendoc-0.6.1.tar.gz#sha256=db1e8c9ae02c1af559eae105bfd77ba41ed07fc8ca7030ea59db5f3f161236a4 has different version in metadata: '6.2.0'

tox: use pip legacy resolver for regen job

---

src/_pytest/terminal.py
testing/test_terminal.py

Avoid showing the `()` in a line like
x.py::test_4 XPASS ()   [100%]
which looks funny.

terminal: when the skip/xfail is empty, don't show it as "()"

---

doc/en/fixture.rst

pytest-pygments doesn't yet recognize the skip reason in summary line added recently. Workaround it until we get to updating it.
Ref: https://github.com/asottile/pygments-pytest/issues/28

doc: temporary workaround for pytest-pygments lexing error

---

src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/python.py
testing/python/fixtures.py
testing/test_collection.py
testing/test_config.py
testing/test_conftest.py
testing/test_pluginmanager.py

- Some conftest related functions
- `Config._confcutdir`
- Allow arbitrary `os.PathLike[str]` in `gethookproxy`.

Some py.path.local -> pathlib.Path

---

changelog/7678.bugfix.rst
src/_pytest/pathlib.py
testing/test_pathlib.py

On Windows, os.path.samefile returns false for paths mounted in UNC paths which
point to the same location.
I couldn't reproduce the actual case reported, but looking at the code it seems
this commit should fix the issue.
Fix #7678
Fix #8076

Compare also paths on Windows when considering ImportPathMismatchError

---

src/_pytest/pytester.py
testing/python/collect.py
testing/python/fixtures.py
testing/python/integration.py
testing/python/metafunc.py
testing/python/raises.py
testing/python/show_fixtures_per_test.py

Another batch of fixes for #7942 - migrated everything under `testing/python/` dir.
***-py37-pluggy** builds are timing out due to the new pip resolver (see the [logs](https://github.com/pytest-dev/pytest/runs/1528787469?check_suite_focus=true)) - perhaps dependencies versions have to be defined stricter.

tests: Migrate testing/python to pytester fixture

---

changelog/8144.feature.rst
src/_pytest/assertion/rewrite.py
src/_pytest/config/argparsing.py
src/_pytest/fixtures.py
src/_pytest/hookspec.py
src/_pytest/main.py
src/_pytest/monkeypatch.py
src/_pytest/nodes.py
src/_pytest/pathlib.py
src/_pytest/python.py
src/_pytest/terminal.py
testing/test_assertrewrite.py
testing/test_main.py
testing/test_nodes.py
testing/test_terminal.py

The first commit is just some scattered `py.path.local` -> `pathlib.Path` conversions.
The second commit adds `pathlib.Path` parameters to all hooks which take `py.path.local`, to allow hook implementers to convert to pathlib. Along with @RonnyPfannschmidt's work on the nodes (#8037) this should enable pytest itself to entirely move away from py.path internally, allowing for eventual deprecation.

hookspec: add pathlib.Path alternatives to py.path.local parameters in hooks

---

changelog/8132.bugfix.rst
src/_pytest/python_api.py
testing/python/approx.py

This treats objects that expose an ndarray via the `__array__` interface the
same as direct subclasses of ndarray. Fixes #8132.

python_api: handle array-like args in approx()

---

.github/workflows/prepare-release-pr.yml
scripts/prepare-release-pr.py
tox.ini

Unfortunately this is untested because the workflow must first be merged
to master in order to be available for triggering.
Fix #7507
I intend to leave the other workflow in place until we can test this workflow and are satisfied with it.

Use manual trigger to prepare release PRs

---

changelog/8152.bugfix.rst
src/_pytest/outcomes.py
src/_pytest/terminal.py
testing/test_terminal.py

Noticed this issue in the new 6.2 feature. The following test when run with `pytest -v`
```py
import pytest
def test_it():
pytest.skip()
```
would show
```
x.py::test_it SKIPPED (<Skipped instance>)                [100%]
```

terminal: fix "(<Skipped instance>)" skip reason in test status line

---

README.rst
scripts/append_codecov_token.py
scripts/publish-gh-release-notes.py
tox.ini

Since we stopped testing Python 3.5, we no longer use Travis.

Remove Travis references

---

setup.cfg

One of the main reasons I hit up a project's PyPI page is to get to its changelog. Adding a changelog in the sidebar gets a nice present icon, see e.g. https://pypi.org/project/pytest-randomly/

Add Changelog to setup.cfg

---

.github/workflows/main.yml
.github/workflows/prepare-release-pr.yml
.github/workflows/release-on-comment.yml

Fix for  #8170 to address CI builds failure (will revert it once underlying issue is fixed)
*EDIT:* `setup-python` fix is out -  https://github.com/actions/setup-python/pull/172 (perhaps, we could update to new syntax too)

infra: Temporary pin setup-python GH action to v2.1.4

---

.github/workflows/main.yml
src/_pytest/nodes.py
src/_pytest/python.py
testing/deprecated_test.py
testing/test_cacheprovider.py
testing/test_collection.py
testing/test_debugging.py
testing/test_junitxml.py
testing/test_link_resolve.py
testing/test_main.py
testing/test_parseopt.py
testing/test_pytester.py
testing/test_unittest.py

This should take care of #7942  completely, with a few exceptions: 
* `testing/test_pytester.py` - two tests were not migrated, they seem to be needed for the time being:
* [testing/test_pytester.py::test_pytester_addopts_before_testdir](https://github.com/pytest-dev/pytest/blob/bd894e3065ba6fa13327ad5dfc94f2b6208cf0ff/testing/test_pytester.py#L618)
* [testing/test_pytester.py::test_testtmproot](https://github.com/pytest-dev/pytest/blob/bd894e3065ba6fa13327ad5dfc94f2b6208cf0ff/testing/test_pytester.py#L814)
Other `testdir` tests were renamed/updated to use pytester (code coverage could drop for Testdir proxy functions).
* `testing/test_collection.py` - removed `testdir` usages and added `py.path.local` conversion where required. I should be easy to fix as part of `py.path.local` -> …

tests: Migrate to pytester - final update

---

changelog/7469.deprecation.rst
changelog/7469.feature.rst
doc/en/reference.rst
src/_pytest/fixtures.py
src/_pytest/mark/structures.py
src/pytest/__init__.py
testing/test_mark.py

This is part of #7469, please see details there. Similar to previous PR #8017 that went in 6.1; haven't seen any complaints about it yet.

mark: expose Mark, MarkDecorator, MarkGenerator under pytest for typing purposes

---

doc/en/fixture.rst
doc/en/requirements.txt

Reverts #8129.
@asottile added support in pytest-pygments 2.2.0.
Tested with `tox -e regen && tox -e docs`.

Revert "doc: temporary workaround for pytest-pygments lexing error"

---

changelog/8174.trivial.rst
src/_pytest/_code/code.py
src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/main.py
src/_pytest/nodes.py
src/_pytest/pathlib.py
src/_pytest/python.py
src/_pytest/terminal.py
testing/code/test_excinfo.py
testing/code/test_source.py
testing/test_cacheprovider.py
testing/test_collection.py
testing/test_config.py
testing/test_doctest.py
testing/test_helpconfig.py
testing/test_nodes.py
testing/test_pathlib.py

After this there's not a lot left, mostly the nodes' `fspath` and some `tmpdir`'s in testing.
I tried to split the changes to standalone commits, the last commit however is a bit larger.

More py.path -> pathlib conversions

---

changelog/7469.deprecation.rst
changelog/7469.feature.rst
doc/en/deprecations.rst
doc/en/funcarg_compare.rst
doc/en/reference.rst
src/_pytest/nodes.py
src/_pytest/python.py
src/_pytest/runner.py
src/pytest/__init__.py
testing/python/metafunc.py

Export pytest.Metafunc and pytest.Callinfo, hide NodeKeywords

---

src/_pytest/helpconfig.py
testing/test_helpconfig.py

Previously:
```
-V, --version         display pytest version and information about plugins.When given twice, also
display information about plugins.
```

Add missing space in '--version' help message

---

AUTHORS
changelog/8061.bugfix.rst
src/_pytest/compat.py
testing/python/fixtures.py

Fixes #8061 
[inspect.getattr_static()](https://docs.python.org/3/library/inspect.html#inspect.getattr_static) (since python 3.2) seem to work better than `cls.__dict__.get()` here (if i don't miss anything).

Fix failing staticmethod tests if they are inherited

---

CONTRIBUTING.rst
doc/en/writing_plugins.rst

In https://docs.pytest.org/en/stable/reference.html#testdir, it is
suggested:
> New code should avoid using testdir in favor of pytester.
Multiple spots in the documents still use testdir and they can be quite
confusing (especially the plugin writing guide).

DOC: Update multiple references to testdir to pytester

---

AUTHORS
changelog/8192.bugfix.rst
src/_pytest/pytester.py
testing/test_pytester.py

Add dot prefix if file makefile extension is invalid for pathlib

---

doc/en/reference.rst

Pytest document currently does not index the top-level package name
`pytest`, which causes some trouble when building documentation that
cross-refers to the pytest package via ``:mod:`pytest` ``.
Reference: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-mod

DOC: Mark pytest module

---

doc/en/index.rst

Together with Python Academy I've just extended the early bird deadline in a last effort to get another couple of sign-ups - only one sign-up so far unfortunately...
Should be trivial to review at least :slightly_smiling_face: 
Preview: https://pytest--8225.org.readthedocs.build/en/8225/

doc: Add note about training early bird discount

---

doc/en/skipping.rst

Add missing import into example script in documentation

---

src/_pytest/skipping.py
src/_pytest/unittest.py
testing/test_unittest.py

Closes #7393
**EDIT:** we're preserving the original behavior - unexpected success in `@unittest.expectedFailure` should have `FAILED` outcome. See discussion in https://github.com/pytest-dev/pytest/issues/7393
----------
~Learning pytest internals more and decided to give it a shot. Let me know if there is a better, pytest way of implementing that.~ 
~Behaviour chages:~
* ~unuttest unexpected success is `XPASS` (exit 0) when not strict (was: `FAIL`, exit: 1)~ 
* ~twisted trial unexpected success is `XPASS` (exit 0) when not strict (was: `FAIL`, exit: 1)~

unittest: cleanup unexpected success handling

---

changelog/8242.deprecation.rst
doc/en/deprecations.rst
src/_pytest/deprecated.py
src/_pytest/runner.py
testing/deprecated_test.py

It is not very clear why this code exists -- we are not running any unittest or nose code during collection, and really these frameworks don't have the concept of collection at all, and just raising these exceptions at e.g. the module level would cause an error. So unless I'm missing something, I don't think anyone is using this.
Deprecate it so we can eventually clear up this code and keep unittest more tightly restricted to its plugin.

Deprecate raising unittest.SkipTest to skip tests during collection

---

doc/en/example/parametrize.rst

Fix pep8 import order in docs

---

AUTHORS
changelog/8249.bugfix.rst
src/_pytest/faulthandler.py
testing/test_faulthandler.py

Hi again,
this patch resolves #8249.
The background on this is that the Twisted Logger will return an invalid file descriptor since it is not backed by an FD. It will make `pytest` croak and hang when invoked through `pytest --capture=no` on teardown.
The solution is to also forward this to the same code path as with `pytest-xdist`, where the code already has special handling for.
Hereby, I humbly ask for further guidance in order to bring in this patch. Please let me know
- if you prefer this mitigation to be handled differently.
- if you think the respective test case should be adjusted.
With kind regards,
Andreas.

Fix faulthandler for Twisted Logger when used with "--capture=no"

---

src/_pytest/fixtures.py
src/_pytest/runner.py
testing/python/fixtures.py
testing/test_runner.py

This PR refactors `SetupState` which handles the setting up and tearing down of nodes as they are executed. I believe it makes the code simpler and easier to understand, and also stricter. I also added a docstring trying to explain how it works a bit.
You can read the commits, if you want to see the progression and justification for each step, or just read the PR diff for the final result (though maybe use patience diff, the github diff somewhat botches it).
Because this makes things stricter, in particular the requirements that finalizers be added only once a node is present in the stack, this may introduce some regressions in plugins which do tricky stuff, or even user code (though in this case I don't think so). Of course I am ready to handle them on a case by case basis if they occur.

runner: refactor SetupState

---

changelog/8152.bugfix.rst
changelog/8249.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-6.2.2.rst
doc/en/changelog.rst
doc/en/example/parametrize.rst
doc/en/getting-started.rst

Created automatically from manual trigger.
can be released by pushing a tag `6.2.2` to this repository.

Prepare release 6.2.2

---

doc/en/index.rst
doc/en/reference.rst

When the declaration stays in reference.rst, it creates duplicated
"pytest" symbols such as `pytest.pytest.mark.filterwarnings`.
Resolves https://github.com/pytest-dev/pytest/pull/8220#issuecomment-767363725

Doc: Move the module declaration to index.rst

---

changelog/8258.bugfix.rst
src/_pytest/faulthandler.py
testing/test_faulthandler.py

It seems the code that would not install pytest's faulthandler support if it was already enabled is not really needed at all, and even detrimental when using `python -X dev -m pytest` to run Python in "dev" mode.
Also simplified the plugin by removing the hook class, now the hooks will always be active so there's no need to delay the hook definitions anymore.
Fix #8258
@thomascobb would you mind testing this branch? I've already tested with the example you posted in #8258, but it would be great if you could make sure this works with your real use case.
You can install this branch locally using:
```
pip install git+https://github.com/nicoddemus/pytest.git@faulthandler-mode-X-8258
```

Always handle faulthandler stderr even if already enabled

---

src/_pytest/pytester.py

The document of the stdin parameter in `pytester.run` is confusing. Also
added some aesthetic updates along the way.

Doc: Clarify pytester.run

---

doc/en/monkeypatch.rst

See the "for convenience" part here: https://docs.pytest.org/en/stable/reference.html#pytest.MonkeyPatch.setattr
Prompted by https://stackoverflow.com/questions/44660196/attributeerror-while-using-monkeypatch-of-pytest/44666743?noredirect=1#comment116593794_44666743

doc: Point out two-argument form of monkeypatch.setattr

---

doc/en/fixture.rst

* Fix various typos in fixture docs
* Add basic emaillib for tests in fixture.rst
This will be used to power regendoc runs for later tests
* Add regendoc runs for emaillib tests in fixture
Also update these tests ensure they pass.
This addresses #8213
-----
I've run `regendoc` locally to ensure the added tests pass, but the resulting diff was rather large (and included some bad whitespace) so I've left it out. What might be best here? I was thinking of just commiting the results of the added tests.

Add regendoc runs for fixture docs

---

src/_pytest/pytester.py

Hopefully these will help document readers understand pertinent methods
and constants better.
Following up #8294

Type annotation polishing for symbols around Pytester.run

---

changelog/8315.deprecation.rst
doc/en/deprecations.rst
src/_pytest/config/argparsing.py
src/_pytest/deprecated.py

Prepare for removing this in the next major pytest release.

config/argparsing: use proper deprecations instead of ad-hoc DeprecationWarning

---

doc/en/fixture.rst

There is no previous `test_ehlo` example (it follows much later) - and the same thing is described further down in ""Requesting" fixtures" already.

doc: Remove confusing fixture sentence

---

changelog/8248.trivial.rst
src/_pytest/python.py

as PyObjMixin is always supposed to be mixed in the mro
before nodes.Node the behavior doesn't change,
but all the typing information carry over to help mypy.
extracted from #8037

alter the PyObjMixin to carry over typing information from Node

---

setup.cfg

I am assuming that `>=>=` is a typo. If it's not then I am sorry to bother you with this. Also, I have not scanned the current PRs to see whether this has already been addressed.

Remove duplicate '>=' in setup.cfg

---

doc/en/assert.rst

head-fork: maskypy40/pytest
compare: patch-1
base-fork: pytest-dev/pytest
base: master
Removes 2 empty, redundant lines in the code-block of test_asser2.py in assert.rst.

Removes 2 empty lines from example code

---

doc/en/fixture.rst

doc This paragraph looks like it is a more verbose version of the sentence right above it.  Removing it doesn't reduce the amount of information here but does make the section flow a little better.

Remove a redundant paragraph

---

changelog/8367.bugfix.rst
src/_pytest/python.py
testing/test_collection.py

Similarly to #7143, at work we have a project with a custom pytest.Class
subclass, adding an additional argument to the constructor.
All from_parent implementations in pytest accept and forward *kw, except
Class (before this change) and DoctestItem - since I'm not familiar with
doctest support, I've left the latter as-is.
cc @bytinbit @MatthiasGabriel

Allow Class.from_parent to forward custom parameters to the constructor

---

changelog/8317.bugfix.rst
src/_pytest/tmpdir.py
testing/test_tmpdir.py

closes #8317.  It is possible that `getpass.getuser()` can be illegal characters not appropriate for a directory name (platform dependent etc).  This PR addresses that by attempting it normally and backing off to use the default `-of-unknown` when it occurs.  This is consistent when `getuser()` is not Truthy.
Appreciate the feed back, thanks again.

Fixed an issue where `getpass.getuser()` contained illegal characters for file directories

---

src/_pytest/python.py

change istestfunction to use `callable(obj)`. closes #7378

use callable(obj) in istestfunction

---

testing/code/test_source.py
testing/python/collect.py
testing/python/integration.py
testing/test_collection.py
testing/test_conftest.py

Some more cleanup of `tmpdir` from the test suite
* Remove some unused 'tmpdir's
* Replace some 'tmpdirs' with 'tmp_path' in makepyfile calls
* Rename variables 'tmpdir'->'tmp_path'
Rename this variables reflecting the migrations made e.g. with 3bcd316f0
and ed658d682
Following this, the remaining usages (trying to ignore `from _pytest.tmpdir import ...`) look like:
```
$ git grep --word-regexp --perl-regexp --count '(?<!from _pytest\.)tmpdir' -- testing/
testing/example_scripts/tmpdir/tmpdir_fixture.py:3
testing/python/fixtures.py:9
testing/test_tmpdir.py:15
```
I think there are some more usages in `testing/python/fixtures.py` that could possibly be replace, but the others all look to be explicitly testing `tmpdir`

Remove tmpdir from tests

---

changelog/8394.bugfix.rst
src/_pytest/python.py
src/_pytest/unittest.py
testing/test_nose.py
testing/test_unittest.py

The problem was that the fixtures generated for unittest/xunit/nose were no longer starting with an underscore, and were always listed with `--fixtures`. This broke a unit-test that checked that all the fixtures we wrote have a docstring (because the auto-genned fixtures do not). See #8394 .
- Followed the approach suggested by @nicoddemus in #8394 of just adding an underscore to the name templates where I found them: one for unittest and four for xunit/nose.
- I wrote a bunch of tests for each case separately and committed the (failing) tests first, followed by the commit that fixes them.

closes #8394 Generated fixture names for unittest/xunit/nose should start with underscore

---

changelog/8411.trivial.rst
testing/example_scripts/issue_519.py
testing/examples/test_issue519.py

fix bug in test for issue 519

---

doc/en/fixture.rst
testing/test_assertrewrite.py

Committed via https://github.com/asottile/all-repos
(I felt that these were slightly better than the previous code, if not -- feel free to close 😄)

clean up mkdtemp usage

---

doc/en/_templates/globaltoc.html
doc/en/contents.rst

Reordered items in:
* _templates/globaltoc.html
* contents.rst

Moved documentation topics to group them by theme.

---

changelog/8421.feature.rst
src/_pytest/python_api.py
testing/python/approx.py

closes #8421 
The tests are pretty bare, I could add assertions with eg. Decimal `rel`, and assertions failing because the values are not close enough. I don't know how relevant these assertions would be :O I will gladly add them if you think it's necessary :)
I'm not all that proud of the "fix" either. It's not clear to me where to best do the check against Decimal :\

Approx decimal sequence mapping

---

changelog/7469.deprecation.rst
changelog/7469.feature.rst
doc/en/how-to/assert.rst
doc/en/reference/reference.rst
src/_pytest/_code/code.py
src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/fixtures.py
src/_pytest/nodes.py
src/_pytest/python_api.py
src/_pytest/unittest.py
src/pytest/__init__.py
testing/test_unittest.py

This is some work per comment https://github.com/pytest-dev/pytest/issues/8405#issuecomment-791933432.
The first commit removes the `_` from the TypeVars.
The third commit exposes `ExceptionInfo` (cc #7469). I still need to figure out how to get sphinx to use the public names but ran out of time for today (I also opened some sphinx issues).

Remove `_` prefix from TypeVars, expose ExceptionInfo

---

doc/en/conf.py

This configures Sphinx autodoc to include the type annotations
along with the description of the function/method, instead of including
it into the signature.
Fix #8405

Add type annotations to the description instead of signature

---

setup.cfg

Warnings like this:
```
python3.9/site-packages/setuptools/dist.py:634: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
```

setup.cfg: fix setuptools dash-separator warnings

---

doc/en/how-to/tmpdir.rst
doc/en/reference/reference.rst

Emphasize tmp_path/tmp_path_factory and just note the legacy ones.

doc/tmpdir: significantly reduce space dedicated to tmpdir/tmpdir_factory

---

doc/en/builtin.rst
doc/en/example/assertion/test_failures.py
doc/en/example/multipython.py
doc/en/example/simple.rst
doc/en/getting-started.rst
doc/en/reference/doctest.rst
doc/en/reference/reference.rst
doc/en/reference/unittest.rst
src/_pytest/pytester.py
src/_pytest/tmpdir.py
testing/example_scripts/tmpdir/tmp_path_fixture.py
testing/example_scripts/tmpdir/tmpdir_fixture.py
testing/python/fixtures.py
testing/test_collection.py
testing/test_config.py
testing/test_parseopt.py
testing/test_pytester.py
testing/test_tmpdir.py

As discussed in https://github.com/pytest-dev/pytest/pull/8251#issuecomment-796852908 I am trying to find remaining py.path usages by completely removing it and seeing what breaks. These are the simple cases I found, mostly in the docs and tests. No user-facing changes.

Remove/replace some unneeded usages of py.path

---

src/_pytest/python_api.py
testing/python/approx.py

Hello!
A static code analyzer informed us that the wrong variable is used for the "relative tolerance can't be negative" error message in `pytest.approx`.
I don't know how to best write a test for this, since error messages usually aren't covered by tests.
A reproducer:
```
from pytest import approx
0 == approx(1, rel=-3)
```
gives:
```
ValueError: relative tolerance can't be negative: 1e-12
```
but should give:
```
ValueError: relative tolerance can't be negative: -3
```
(There's also no documentation; I don't think this is docs-worthy.)

Fix value in error message about negative relative tolerance

---

changelog/7259.feature.rst
doc/en/example/nonpython/conftest.py
doc/en/reference/reference.rst
src/_pytest/cacheprovider.py
src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/main.py
src/_pytest/pytester.py
src/_pytest/python.py
testing/acceptance_test.py
testing/conftest.py
testing/example_scripts/collect/package_infinite_recursion/conftest.py
testing/example_scripts/fixtures/custom_item/conftest.py
testing/example_scripts/issue88_initial_file_multinodes/conftest.py
testing/python/collect.py
testing/python/fixtures.py
testing/test_cacheprovider.py
testing/test_collection.py
testing/test_conftest.py
testing/test_junitxml.py
testing/test_skipping.py
testing/test_terminal.py

The first commit adds `cache.mkdir`, a replacement for the py.path-returning `cache.makedir`.
Second commit makes `collect_ignore` agnostic to `py.path`.
Third commits are some random replacements of py.path uses with the pathlib equivalents.

More py.path removal work

---

changelog/8456.bugfix.rst
src/_pytest/config/__init__.py
testing/test_config.py

Fix required_plugins with prereleases

---

.github/PULL_REQUEST_TEMPLATE.md

Setting the pull requests template to link to main rather than master.  Had a look at: https://github.com/pytest-dev/pytest/pull/8462 which appears to omit this file.  @RonnyPfannschmidt would you prefer I target this to the `fixup` branch instead of pytest `main` directly?

rename master to main in PULL_REQUEST_TEMPLATE.md

---

src/_pytest/hookspec.py

Hi all, In reference to (closes #8287) I had a look into the pluggy machinery with regards to both root and sub `conftest.py` files, using the following setup:
```python
def test_cmdline_main(pytester: Pytester) -> None:
pytester.makeconftest(
"""
def pytest_cmdline_main(config) -> None:
print("I AM IN A ROOT CONFTEST!")
"""
)
sub = pytester.mkdir("testing")
sub.joinpath("conftest.py").write_text(
textwrap.dedent(
"""\
def pytest_cmdline_main(config) -> None:
print("I AM IN A SUB CONFTEST!")
"""
))
sub.joinpath("test_foobar.py").write_text(
textwrap.dedent(
"""
def test_something():
assert True
"""
)
)
result = pytester.runpytest("-v", "-s")
result.stdout.fnmatch_lines(["I AM IN A SUB CONFTEST!", "I AM IN A ROOT CONFTEST!"])
```
As a result at first inspection, both plugins in the …

Remove note on conftest.py files as part of pytest_cmdline_main hookspec

---

changelog/8403.improvement.rst
doc/en/how-to/usage.rst
doc/en/reference/plugin_list.rst
scripts/update-plugin-list.py
src/_pytest/_io/saferepr.py
src/_pytest/assertion/__init__.py
src/_pytest/assertion/rewrite.py
src/_pytest/assertion/util.py
testing/io/test_saferepr.py
testing/test_assertrewrite.py

This helps with the problem described in #6682.
~~Decided to go with `-vvv` and `-vvvv` because I believe they are rarely used, so this should really affect users that want to disable truncation, but would like to hear opinions.~~
As discussed in #8403, changed the verbosity to 2400 for `-v`, and unlimited for `-vv` and up.
Fix #6682
Fix #8403

Increase truncation threshold with -v, disable with -vv

---

testing/test_pathlib.py

This set of tests works by checking the expected result, and checking that py.path gets the same result.
Remove the latter part, as preparation for deprecating py.path.

testing: stop relying on comparing to py.path in fnmatcher tests

---

src/_pytest/reports.py

fix some formatting in the TestReport / CollectReport, and reword the description about the 'sections' attribute
this is what it looks like currently: https://docs.pytest.org/en/stable/reference.html#pytest.reports.TestReport.sections
The CollectReport one maybe didn't render at all due to bunk formatting (?)
- "which needs to marshallable" does not make a lot of sense (presumably means json serializable?) but is unnecessary anyway since the type is already annotated as `List[Tuple[str, str]]` which will be marshallable.  Also I think I just now got the joke of why [marshmallow](https://marshmallow.readthedocs.io/en/stable/) project is named so...  😄 
- `(str, str)` just duplicated the existing type annotation so I changed it to `(heading, content)` to better indicate how each string in …

tweak documentation of report's sections attribute

---

doc/en/reference/plugin_list.rst
scripts/update-plugin-list.py

Last time I "fixed" this, I left a `\` at the start of the string to avoid an initial newline, but didn't realize it was a raw string.
This should fix it now for good (the extra newline at the start doesn't really hurt).

Fix plugin-list label in the docs

---

changelog/8503.trivial.rst
src/_pytest/monkeypatch.py

This is just a draft PR. Do we want this? Or should we handle missing `pkg_resources` from `monkeypatch.syspath_prepend()` instead?

 monkeypatch.syspath_prepend: Skip fixup_namespace_packages if pkg_resources not imported

---

changelog/8414.bugfix.rst
src/_pytest/pathlib.py
src/_pytest/pytester.py
src/_pytest/tmpdir.py
testing/test_tmpdir.py

[6.2.x] Fix minor temporary directory security issue

---

AUTHORS
changelog/7856.bugfix.rst
changelog/7856.feature.rst
doc/en/explanation/goodpractices.rst
doc/en/explanation/pythonpath.rst
src/_pytest/config/__init__.py
src/_pytest/doctest.py
src/_pytest/main.py
src/_pytest/pathlib.py
src/_pytest/python.py
testing/code/test_excinfo.py
testing/code/test_source.py
testing/python/fixtures.py
testing/test_config.py
testing/test_conftest.py
testing/test_pathlib.py
testing/test_pluginmanager.py

Fix error with --import-mode=importlib and modules containing dataclasses or pickle

---

.pre-commit-config.yaml
doc/en/deprecations.rst
src/_pytest/config/__init__.py
src/_pytest/config/compat.py
src/_pytest/deprecated.py
src/_pytest/main.py
src/_pytest/python.py
src/_pytest/terminal.py
testing/deprecated_test.py

address #8361 - introduce hook caller wrappers that enable backward compat

---

doc/en/changelog.rst

fix pytest 6.2.3 #8414 changelog entry grammar

---

AUTHORS
changelog/8539.bugfix.rst
src/_pytest/assertion/rewrite.py

Fixes https://github.com/pytest-dev/pytest/issues/8539
This seems to have been the result of https://bugs.python.org/issue43798

Fix assertion rewriting on Python 3.10

---

doc/en/index.rst

The training is sold out with 10 people (yay!), so there's a second date for it now.
Is there a better way we can keep pytest.org up to date with those changes? From what I understand, it only gets updated when we make a new release from `main`, which hasn't happened this year so far? It's kinda troublesome we still advertise a training from February (with "Early-bird discount available until January 15th.") there... 
I struggle to think of a better solution though... Can we (and do we want to) reconfgure RTD so it shows "latest" by default instead, or would that be too confusing if we had breaking changes?

doc: Update open trainings

---

doc/en/index.rst

Next I plan to:
- Set the `6.2.x` branch as an active version on RTD (like `4.6.x` already is)
- Set the `6.2.x` version as default instead of `stable`
- Make a reminder to revert back to `stable` once we have a new release out
I don't see a way to tell RTD to use the latest `6.*.*` branch, but that's as close as we can get.
Does that seem right?

Backport training update

---

doc/en/changelog.rst
scripts/release-on-comment.py
src/_pytest/capture.py
src/_pytest/doctest.py
src/_pytest/store.py
testing/logging/test_reporting.py
testing/python/metafunc.py

Fix some typos, remove redundant words.
Remove redundant escapes from a regex.

Fix some typos, remove redundant words and escapes

---

doc/en/how-to/logging.rst

Small PR to fix reference to `LogCaptureFixture` from https://docs.pytest.org/en/stable/logging.html#caplog-fixture

Logging docs: fix reference to pytest.LogCaptureFixture.

---

setup.cfg

The `Sphinx-PyPI-upload` tool the section corresponds to hasn't been updated since 2009, and the new (c. 2018) PyPI doesn't support documentation uploads anyway.
Therefore I think the section is redundant and safe to remove.

Remove "upload_sphinx" section from setup.cfg

---

src/_pytest/_code/code.py
testing/code/test_excinfo.py

I am trying to investigate a bug in Setuptools, and I ran into this internal error in pytest:
```
INTERNALERROR>   File "/home/pviktori/dev/setuptools/.tox/py310/lib/python3.10/site-packages/_pytest/_code/code.py", line 798, in repr_traceback_entry
INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR>   File "/home/pviktori/dev/setuptools/.tox/py310/lib/python3.10/site-packages/_pytest/_code/code.py", line 727, in get_source
INTERNALERROR>     lines.append(space_prefix + source.lines[line_index].strip())
INTERNALERROR> IndexError: list index out of range
```
<details>
<summary>Full traceback...</summary>
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/pviktori/dev/setuptools/.tox/py310/lib/python3.10/site-packages …
```

Make code.FormattedExcinfo.get_source more defensive

---

setup.cfg
tox.ini

Tests in test_terminalwriter depend on pygments being installed to work, so it should be installed with the `testing` extras.

Make pygments part of 'testing' extras

---

AUTHORS
changelog/8509.bugfix.rst
changelog/8509.improvement.rst
src/_pytest/nodes.py
testing/test_nodes.py

Fix for issue #8509 and improve `iterparentnodeids`to consume `/` parts until the first `::`

Improve `iterparentnodeids` to consume `/` parts until the first `::`

---

changelog/8539.bugfix.rst
doc/en/announce/index.rst
doc/en/announce/release-6.2.4.rst
doc/en/changelog.rst
doc/en/getting-started.rst

Created automatically from https://github.com/pytest-dev/pytest/issues/8631.
can be released by pushing a tag `6.2.4` to this repository.
Closes #8631.

Prepare release 6.2.4

---

AUTHORS
README.rst

Close https://github.com/pytest-dev/pytest/issues/8619.

doc: plugin link on readme.rst fixed

---

pyproject.toml
testing/acceptance_test.py
testing/python/collect.py
testing/python/metafunc.py
testing/test_collection.py
testing/test_config.py
testing/test_pytester.py
testing/test_skipping.py
testing/test_terminal.py
testing/test_threadexception.py
testing/test_unraisableexception.py
testing/test_warnings.py

Potential alternative to #8553. Fixes the Python 3.10 tests for me, without #8540. See #8546, though I wouldn't close it yet, as we might want to change the enum reprs instead?

Fix Python 3.10 test issues

---

src/_pytest/python_api.py

docfix: tolerance setting in unittest.TestCase.assertAlmost

---

doc/en/example/simple.rst

This shows how to pass more detailed error messages back to the user when
they've provided an incorrect value for a custom command line option.

Expand command line argument examples with validation examples

---

changelog/7259.feature.rst
src/_pytest/config/__init__.py
src/_pytest/config/argparsing.py
testing/test_config.py

Part of issue #7259, specifically https://github.com/pytest-dev/pytest/issues/7259#issuecomment-826610939.

argparsing: support parser.addini(type="paths") which returns pathlib.Paths

---

.github/workflows/main.yml
.github/workflows/prepare-release-pr.yml
.github/workflows/release-on-comment.yml
.github/workflows/update-plugin-list.yml
scripts/prepare-release-pr.py
scripts/release-on-comment.py
scripts/upload-coverage.sh

This fixes #8599, and couple other improvements -- please see the commits.
This is entirely untested, and probably would require debugging until nothing breaks, so marking as draft for now, but would appreciate others taking a look.
If the second commits looks good, we should change the default permissions in the repo settings from read-write to read-only.
If the third commit looks good, we should remove the `chatops` and `release_notes` secrets in the repo settings.

ci: few security/permissions improvements

---

AUTHORS
changelog/8645.improvement.rst
doc/en/how-to/capture-warnings.rst
src/_pytest/deprecated.py
src/_pytest/recwarn.py
testing/deprecated_test.py
testing/test_recwarn.py
testing/test_tmpdir.py

Catch any warning on warns with no arg passed

---

src/_pytest/_code/code.py

Given a `RecursionError` traceback, the `Traceback.recursionindex()`
method returns the index of the frame which started the recursion
(repeated set of frames). To do so it attempts to check whether two
frames are equivalent. Just checking the function/line is not enough
because the recursion variable(s) might differ (e.g. imagine the numeric
value in a recursive factorial implementation). So it also compares the
`f_locals` (local variables) of each frame for equivalence.
For some reason, the locals comparison is wrapped in an `eval` whose
purpose is to evaluate the comparison in one of the compared frame's
context (locals + globals in scope). However, I can not think of any way
in which the global scope could affect the evaluation. It would have an
affect when the locals are bound but …

code: remove unneeded comparison eval wrapper

---

changelog/7259.feature.rst
changelog/7469.deprecation.rst
changelog/7469.feature.rst
changelog/8315.deprecation.rst
doc/en/deprecations.rst
doc/en/reference/reference.rst
src/_pytest/config/__init__.py
src/_pytest/config/argparsing.py
src/_pytest/hookspec.py
src/pytest/__init__.py
testing/test_parseopt.py

`Parser` is used by many plugins and custom hooks. `OptionGroup` is
exposed by the `parser.addgroup` API.
The constructors of both are marked private, they are not meant to be
constructed directly.
Refs #7469.

argparsing: export Parser and OptionGroup for typing purposes

---

doc/en/explanation/goodpractices.rst

It makes more sense to not link to the section itself, which causes a confusing cycle.

Fix cyclic links in goodpractices.rst

---

AUTHORS
doc/en/getting-started.rst

In the "Getting Started" doc, the test class instance example for
instance sharing doesn't actually demonstrate anything about the
reinstantiation of the class. This change shows clearly how the instance
data isn't retained between test runs.

Make the test class instance behaviour clearer

---

doc/en/reference/reference.rst

The section refers to tmpdir_factory, but the sentence mentionned
tmp_path_factory.

Fix a typo in documentation about tmpdir_factory

---

doc/en/contact.rst

As discussed in https://github.com/orgs/pytest-dev/teams/contributors/discussions/3
Preview: https://pytest--8722.org.readthedocs.build/en/8722/contact.html
Also taking the freedom to remove pytest-commit, since that [seems to be broken](https://mail.python.org/pipermail/pytest-commit/) since January 2019 and nobody complained so far.

Switch to irc.libera.chat

---

src/_pytest/_code/code.py

This reverts commit 67af623d9e25716cf7bb91dd6ce7354991197954, reversing
changes made to aead41e449b07d00c958b938d899841f304dc2fa.
(partial revert, I left the test in)
this is now passing again after the regression in the python3.10 alphas has been fixed

Revert "Merge pull request #8227 from encukou/defensive-get_source"

---

doc/en/fixture.rst

Example referenced the wrong function name

Fix typo in fixture.rst

---

src/_pytest/logging.py

The underlying logging API accepts the log level both as int and
as string.

updated type hints for caplog.at_level to match caplog.set_level

---

doc/en/how-to/capture-warnings.rst
src/_pytest/tmpdir.py
testing/test_recwarn.py

Since #2908, the user doesn't need to set warning filters to capture
`DeprecationWarning` with `pytest.warns`.
Fix #8666

Remove outdated docs about pytest.warns and DeprecatedWarning

---

doc/en/warnings.rst
src/_pytest/tmpdir.py
testing/test_recwarn.py

[6.2.x] Merge pull request #8754 from nicoddemus/fix-deprecation-docs

---

changelog/8761.feature.rst
doc/en/reference/reference.rst
src/_pytest/__init__.py
src/pytest/__init__.py
testing/test_helpconfig.py

This adds `pytest.version_tuple`, which makes it simpler for users to do something depending on the pytest version, such as declaring hooks which are introduced in later versions.
This feature was added originally in https://github.com/pypa/setuptools_scm/pull/475.
Followup to https://github.com/pytest-dev/pytest/pull/7605.

Add pytest.version_tuple

---

setup.cfg

This is a backport from main. Fedora's tooling is confused by the typo:
```
Handling setuptools>=>=42.0 from get_requires_for_build_wheel
...
ValueError: Unknown character in version: >=42.0.
```

[6.2] Remove duplicate '>=' in setup.cfg

---

testing/test_nodes.py

Otherwise, if e.g. /outside is used for a Docker container, the test will fail:
```
>       assert nodes._check_initialpaths_for_relpath(session, outside) is None
E       AssertionError: assert '' is None
```

tests: Use less conflicting name for directory

---

testing/test_cacheprovider.py

When running in docker, for whatever reason, directories are still writable after a `chmod(0)`. Thus, check if the directory is really unwritable, which replaces the current check for a Windows OS.
Also, move the repetitive cache directory code into a fixture.

Improve cache test and fix it in Docker

---

AUTHORS
doc/en/how-to/capture-warnings.rst

I noticed a few places where a leading `:` was missing for the `:func:` sphinx directive which caused the link to the corresponding API docs to not render correctly. This PR adds the leading `:` to ensure links are rendered. 
Current rendering:
With the changes in this PR:

Fix API links in 'How to capture warnings' documentation page

---

changelog/8447.deprecation.rst
doc/en/deprecations.rst
src/_pytest/main.py
src/_pytest/nodes.py
testing/test_nodes.py

issue a warning when Item and Collector are used in diamond inheritance

---

.github/workflows/prepare-release-pr.yml
scripts/prepare-release-pr.py

Unfortunately untested, as it is only available once it lands on `main`.
Fix #7551

Allow prereleases from prepare-release workflow

---

doc/en/how-to/usage.rst

Fix https://github.com/pytest-dev/pytest/issues/8790

doc: Adding exit code for pytest usage examples (#8790)

---

scripts/prepare-release-pr.py

We don't need to access the output in the script, and if we capture it,
we don't get any output on CI, so no way to see why a release failed.
Failing release here: https://github.com/pytest-dev/pytest/runs/2931408672?check_suite_focus=true#step:6:35
I deleted the 7.0.x maint branch I had created again, so we don't need to backport this (it's only been around for a couple of minutes). Will recreate once it's in.

scripts: Don't capture output in prepare-release-pr.py

---

doc/en/index.rst

The "external plugins" link was pointing to a deprecated Heroku app. This PR uses the correct plugin link to save the reader an extra click.

Fix "external plugins" link

---

.github/workflows/prepare-release-pr.yml

See #8599, follow-up to #8681
The token is needed so we can use `git push`.

ci: Persist git credentials for prepare-release-pr

---

changelog/8246.breaking.rst
src/_pytest/helpconfig.py
testing/test_config.py
testing/test_helpconfig.py

[pytest 7.0] Make --version write to stdout rather than stderr 

---

doc/en/changelog.rst
testing/test_recwarn.py

Other than the ones tackled in #8826 already.

Update remaining 7.0 references

---

.pre-commit-config.yaml
AUTHORS
changelog/8789.feature.rst
setup.cfg
src/_pytest/config/findpaths.py
testing/test_findpaths.py

Closes https://github.com/pytest-dev/pytest/issues/8789

Support TOML v1.0.0 syntax in `pyproject.toml`

---

setup.cfg

the best practice is to only `<` when you know something is broken, and even then prefer `!=` assuming it will be fixed upstream for maximum compatibility

Remove upper pinning on tomli

---

doc/en/builtin.rst
doc/en/how-to/monkeypatch.rst
src/_pytest/monkeypatch.py

The [`monkeypatch` docs](https://docs.pytest.org/en/6.2.x/reference.html?highlight=monkeypatch#pytest.monkeypatch.monkeypatch) show an example of passing `prepend=False` to `monkeypatch.setenv`. However, the [`monkeypatch.setenv` docs](https://docs.pytest.org/en/6.2.x/reference.html?highlight=monkeypatch#pytest.MonkeyPatch.setenv) clearly state that `prepend` is of type `str` or `None`. This PR fixes the `monkeypatch` docs.

Docs: monkeypatch.setenv does not accept bool

---

testing/python/metafunc.py
testing/test_pytester.py

I don't think a changelog fragment is necessary: It changes tests only, no chnagelog fragment was even in the original commit that introduced the conditional.
Alternative to https://github.com/pytest-dev/pytest/pull/8895

Revert "Adjust enum reprs for Python 3.10"

---

doc/en/deprecations.rst
src/_pytest/deprecated.py
src/_pytest/fixtures.py
src/_pytest/nodes.py
testing/python/fixtures.py
testing/test_collection.py

It is not clear yet how we should proceed with this deprecation
because `pytest.Item.reportinfo` is public API and returns a `py.path` object,
and also how plugins and our examples should handle that.
Reverting just the deprecation aspect of #8251 so we can get a 7.0.0 release out.
We will reintroduce the deprecation later once we have a clear path moving forward with replacing `reportinfo`.
Closes #8445
Closes #8821

Revert fspath deprecation

---

changelog/8432.doc.rst
changelog/8432.trivial.rst
src/_pytest/python.py
testing/test_skipping.py

Update error message for module level skip to include 'allow_module_level'

---

doc/en/contents.rst
doc/en/getting-started.rst
doc/en/how-to/index.rst
doc/en/how-to/tmp_path.rst
doc/en/reference/reference.rst

rename tmpdir.rst to tmp_path.rst

---

.pre-commit-config.yaml

This is a Windows only dependency, so the problem only shows up when trying to commit on Windows.

Add types-atomicwrites to mypy's pre-commit configuration

---

doc/en/contact.rst

Ported from #8932
My mistake, didn't realize the original PR was not targeting `main`.

contact.rst: Added github discussions

---

changelog/7124.bugfix.rst
src/_pytest/doctest.py
testing/example_scripts/doctest/main_py/__main__.py
testing/example_scripts/doctest/main_py/test_normal_module.py
testing/test_doctest.py

Hi, hope you are all doing well.  Been a bit busy as of lately but I am hoping to start contributing again, here is an issue outlined in:
#7124
whereby when ``--doctest-modules`` was being passed, `ImportError` on `__main__.py` was raised, causing a crash.  I have added a special case for `__main__.py` here, similarly to `setup.py`, would welcome any feed back on this approach or if you can guide me to another one if this is incorrect.
- adds `__main__.py` specific checks for the `doctest` plugin `collect_item` hook implementation
- unit / integration tests

#7124: Fix `--doctest-modules` crashing when `__main__.py` is present

---

doc/en/how-to/writing_hook_functions.rst

slightly incorrect import in the example of writing & registering user define hooks.

Fix small typo in pluggy writing hook functions docs

---

AUTHORS
doc/en/how-to/parametrize.rst

This PR add examples of the parametrize in classes definition.
Closes #8947

Add examples of parametrizing classes and all tests in a module

---

src/_pytest/config/__init__.py

`os.PathLike` is now `@runtime_checkable` in typeshed, so it is my understanding we no longer need to suppress `os.PathLike` isinstance checks.
https://github.com/python/typeshed/blob/e1b9ab33727ddbb2bab21c0a1c161d9a0b2c7c2f/stdlib/os/__init__.pyi#L311-L313
```py
@runtime_checkable
class PathLike(Protocol[_AnyStr_co]):
def __fspath__(self) -> _AnyStr_co: ...
```

typeshed `os.PathLike` is now `@runtime_checkable`, remove mypy ignore

---

changelog/8592.deprecation.rst
doc/en/deprecations.rst
src/_pytest/deprecated.py
src/_pytest/hookspec.py
testing/deprecated_test.py
testing/test_assertrewrite.py

Hi all, I think this is how we handle these hook deprecations.
- officially deprecates the `pytest_cmdline_preparse` hook
Can I follow up by removing the `pytest_warning_captured` hook altogether? not sure when it was officially deprecated.

Deprecate pytest_cmdline_preparse

---

changelog/8953.feature.rst
src/_pytest/pytester.py
src/_pytest/pytester_assertions.py
testing/test_nose.py
testing/test_pytester.py

Evening all, while investigating some other areas I noticed `pytester` cannot actually assert outcomes on `warnings=` so I've decided to bolt that on, I'm not sure if there is a good reason why this wasen't already a feature, maybe because of shadowing the builtin `warnings` module with it's naming or so? or it might create a bit of unpredictability in our tests?
Might have some test fallout, will have a look as soon as
edit: Actually there might be a very good use-case why this is **NOT** the default..
edit2: Reopening as it _might_ be an ok feature?
closes #8953

expose `warnings=` to pytester `assert_outcomes()`

---

changelog/8913.trivial.rst
src/_pytest/fixtures.py
src/_pytest/mark/structures.py
src/_pytest/python.py
src/_pytest/scope.py
src/_pytest/setuponly.py
src/_pytest/unittest.py
testing/python/metafunc.py
testing/test_scope.py

This replaces the internal use of string literals and "scopenum"
to a proper Scope enum, which also centralizes indexes, getting
higher scopes, get next scope in the order, etc. Another benefit
is that it helps the type checker by introducing a proper type,
and improve readability (IMHO).
This is _mostly_ an internal change, however due to historical
reasons, the API of the following _internal_ objects has
changed slightly:
* `CallSpec2`: `_arg2scopenum` renamed to `_arg2scope` for consistency.
* `FixtureRequest`:
Previously contained a `scope: str` attribute.
Changed attribute to `_scope: Scope`, with a backward compatible read-only property `scope -> str`.
This one might cause some confusion, because the internal attribute has a different type
than the public property of the same name. …

Refactor internal scope handling by introducing Scope enum

---

changelog/8983.bugfix.rst
src/_pytest/mark/expression.py
testing/test_mark_expression.py

Fixes #8983. I see two options for how to treat backslashes (besides rejectign them), as escape characters or literal identifier characters. I went with the latter; please see the test docstring for the rationale.

mark/expression: allow backslash characters in identifiers

---

AUTHORS
changelog/8803.improvement.rst
doc/en/how-to/logging.rst
src/_pytest/logging.py

This PR adds the possibility to color custom log levels on the CLI:
Not sure how this can be unit tested or where to add documentation. Please comment.
Closes #8803.

logging: Make it possible to add cli colors to custom log levels 

---

AUTHORS
changelog/7132.feature.rst
doc/en/reference/customize.rst
doc/en/reference/reference.rst
src/_pytest/_io/terminalwriter.py
testing/test_terminal.py

This patchs allows users to set two environment variables (*PYTEST_THEME* and *PYTEST_THEME_MODE*) to customize the pygments theme to use. It fixes #7132
I know some people were interested in [rich](https://github.com/willmcgugan/rich) and suggested to wait and see, but this solution is so easy and unintrusive I think it might be worth right now.
What do you think?

pygments themes are customizable

---

doc/en/how-to/assert.rst

> *Deprecated since version 3.2:* `assertRegexpMatches` and `assertRaisesRegexp` have been renamed to `assertRegex()` and `assertRaisesRegex()`.
https://docs.python.org/3/library/unittest.html#deprecated-aliases

Docs: refer to non-deprecated unittest alias

---

doc/en/index.rst

Europython is done (went quite well!), and the date for the Python Academy one is known now (though we ended up going for Q1/2022 instead).

doc: Update trainings

---

testing/test_assertrewrite.py

This is a simple fix for testing on Solaris, where (similarly to Windows) cwd cannot be removed.

Fix cwd removal on Solaris

---

doc/en/changelog.rst
doc/en/conf.py
doc/en/explanation/goodpractices.rst
doc/en/explanation/pythonpath.rst
doc/en/getting-started.rst
doc/en/how-to/capture-warnings.rst
doc/en/how-to/doctest.rst
doc/en/how-to/failures.rst
doc/en/how-to/fixtures.rst
doc/en/how-to/unittest.rst
doc/en/how-to/xunit_setup.rst
doc/en/reference/customize.rst
doc/en/reference/reference.rst

This PR replaces hardcoded links to docs.python.org by intersphinx crossrefs where possible. The only URL that was left hardcoded is in `how-to/unittest.rst`, since the referenced section in stdlib docs ([link](https://docs.python.org/3/library/how-to/unittest.html#load-tests-protocol)) doesn't have any label.

use intersphinx crossrefs to stdlib docs where possible instead of hardcoded URLs

---

doc/en/index.rst

We talked about cancelling it because we originally only had 4 signups, but then apparently two Swiss people found it on the pytest website and another one elsewhere, so we ended up being 7 (plus me) :tada:

Remove finished open training

---

README.rst
doc/en/contact.rst

Short and sweet; adds a discord badge into the readme and updates the contacts docs to reference the **pytest-dev** discord server.
(Not sure on what is best for the text on these; so feel free to recommend any changes :) was a best guess!)
edit: It is possible to make a more 'interactive' discord badge; stating how many users online etc but it might require some admin permissions on the discord server itself - if anyone wants to pursue that

adding contact and badge for pytest-dev discord server

---

AUTHORS
changelog/4320.doc.rst
doc/en/how-to/writing_plugins.rst

Improved docs for `pytester.copy_example` to provide better context on the usual usage observed in the `pytest` repo. I considered updating the code to reflect that, but I think a simple snippet like that does its job. I'm open to any suggestions though!
I'm not sure whether the change is significant enough to require a changelog entry – I'll remove it if deemed unnecessary.
Closes #4320.

Improved docs for `pytester.copy_example`

---

changelog/9077.bugfix.rst
src/_pytest/fixtures.py
testing/python/fixtures.py

Introduced in 12de92cd2b818906d342dbdfaf96999887bc9658 / #7698

Fix non-sensical error message
