pytest-dev/pytest

.travis.yml
README.rst
tox.ini

so they will be built in parallel vs serial, as it is ATM

split travis jobs

---

AUTHORS
CHANGELOG
_pytest/junitxml.py
testing/test_doctest.py

Closes #713 (which happens because `ReprFailDoctest` doesn't have a reprcrash)

Handle reports that don't have a reprcrash

---

.travis.yml
AUTHORS
CHANGELOG
_pytest/junitxml.py
_pytest/resultlog.py
testing/test_junitxml.py
testing/test_resultlog.py
tox.ini

Credits for the fix go to @curzona. :smile:
Only created this PR to solve some conflicts when #783 was rebased to `pytest-2.7`.
With this PR I noticed that `pytest-2.7` was actually broken on Travis since we moved to GitHub; in order to make it work again, I cherry-picked some of @bubenkoff's commits from `master`, but I also had to remove `py27-subprocess` from the test environments that run on Travis as the feature tested by it (inprocess tests by default) has been introduced in `master` only. 
We must be careful when merging this back into `master` to not merge the commented out environment.

Automatically create directories for junit-xml and resultlog

---

AUTHORS
CHANGELOG
_pytest/junitxml.py
_pytest/resultlog.py
testing/test_junitxml.py
testing/test_resultlog.py

rebased #782 onto `pytest-2.7`
`py.test --junit-xml=results/results.xml` fails if results directory has not already been created.

Automatically create directory for results

---

CHANGELOG
_pytest/skipping.py
_pytest/unittest.py
testing/test_skipping.py
testing/test_unittest.py

Fix #114: when using `pytest.mark.skipif`
Fix #748: when using `unittest.SkipTest`

Skip reports refer to pytest code instead of original test functions

---

.travis.yml

It seems #pytest-dev is quite dead. Also I set it to only send notifications on
changes (i.e. success -> failure and vice-versa).

Adjust IRC notifications to use #pytest.

---

CHANGELOG
_pytest/python.py
testing/python/raises.py

Fix issue where pytest.raises() doesn't always return Exception instance in py26

---

README.rst

Using SVGs improves the appearance of badges on high resolution displays (see diff below). In addition, both of the build status badges are already SVGs, so this standardizes all of the badges.

Use SVGs for all README badges

---

.coveragerc

Improving coverage score by removing files known to generate bogus reports.
**Note**: Can we remove `oldreinterpret.py` altogether? It seems to be used for python versions pre-2.6, but we no longer support those.

Improve coverage score by tweaking options

---

testing/test_conftest.py

The test creates a conftest.py with "assert 0" which never should be loaded.
However, if it were loaded, the test would still pass as it never checks if it
was loaded or not.
See #799.

Check conftest.py is not loaded with --confcutdir.

---

CHANGELOG
_pytest/config.py
_pytest/main.py
testing/test_conftest.py

~~Pushing this *work-in-progress* PR because I'd appreciate some help.~~
I want to add a `--noconftest` option to not load any `conftest.py` files (which is useful when using things like `pytest-{pep8,flakes,mccabe,...}` and not wanting the dependencies imported in the `conftest.py` file).
~~I now implemented the option and a test (`test_no_conftest`) but not the feature itself, i.e. I'd expect that test to fail. However, it passes! Why is that?~~
It's inspired by the test above (`test_conftest_confcutdir`) where a `conftest.py` with `assert 0` is created as well to ensure it shouldn't get loaded.

Add a --noconftest option.

---

AUTHORS
CHANGELOG
_pytest/recwarn.py
testing/test_recwarn.py

See https://github.com/pytest-dev/pytest/pull/802 Rebased on branch pytest-2.7
Added test and data in AUTHORS and CHANGELOG

deprecated_call does not revert warning functions back to original v2

---

AUTHORS
CHANGELOG
_pytest/junitxml.py
testing/test_junitxml.py

This adds the `file` and `lineno` attributes to the junit-xml output
which can be used by tooling to identify where tests come from. This can be
used for many things such as IDEs jumping to failures and test
runners evenly balancing tests among multiple executors.

Add `file` and `line` attributes to junit-xml output.

---

testing/test_junitxml.py

This tests fails consistently on Windows due to a small time
difference:
```
>       assert float(val) >= 0.03
E       assert 0.0299999713898 >= 0.03
E        +  where 0.0299999713898 = float('0.0299999713898')
```
Windows time.time() function is not as accurate as linux's,
so relaxed the test a bit.

Fix flaky test_timing_function in Windows

---

_pytest/config.py
doc/en/writing_plugins.txt
testing/acceptance_test.py

PyCharm depends on `get_plugin_manager()` for its pytest runner.
Using the pytest runner in PyCharm as of `2.8.0.dev4` raises this exception:
```
File "D:\Programming\PyCharm\helpers\pycharm\pytestrunner.py", line 60, in <module>
main()
File "D:\Programming\PyCharm\helpers\pycharm\pytestrunner.py", line 30, in main
_pluginmanager = get_plugin_manager()
File "D:\Programming\PyCharm\helpers\pycharm\pytestrunner.py", line 20, in get_plugin_manager
from _pytest.core import PluginManager
ImportError: No module named '_pytest.core'
```
The related code in `PyCharm\helpers\pycharm\pytestrunner.py` is:
```python
def get_plugin_manager():
try:
from _pytest.config import get_plugin_manager
return get_plugin_manager()
except ImportError:
from _pytest.core import …
```

Reintroduce get_plugin_manager() for backward-compatibility

---

_pytest/python.py
doc/en/announce/index.txt
doc/en/capture.txt
doc/en/customize.txt
doc/en/doctest.txt
doc/en/fixture.txt
doc/en/funcarg_compare.txt
doc/en/monkeypatch.txt
doc/en/parametrize.txt
doc/en/projects.txt
doc/en/recwarn.txt
doc/en/release.txt
doc/en/skipping.txt
doc/en/status.txt
doc/en/usage.txt
doc/en/writing_plugins.txt

- Add explicit "code-block" for sessions without syntax highlight
- Moved Metafunc documentation to the class docstring and reused that in the
docs;
- Other minor fixes (add 2.7.2 to the release notes, updated howtorelease with git commands, etc.)

Add syntax highlighting to missing snippets in the documentation and other fixes

---

tox.ini

It has been announced that mock>=1.1 will be supported for python 2.7+ only.

Pinning mock module to < 1.1 fo py26

---

CHANGELOG
_pytest/config.py
_pytest/main.py
doc/en/customize.txt
doc/en/goodpractises.txt
testing/test_collection.py

As discussed in #694, but not exactly as described in there. Usually projects have a well defined location for tests (pytest for example is `testing`), so an option to specify which directories to look for tests when executing pytest without arguments from the root directory seems useful.

Add new testdirs ini option

---

CHANGELOG
_pytest/config.py
testing/test_config.py

Print inifile and rootdir when there's usage errors

---

CHANGELOG
_pytest/python.py
testing/python/fixture.py

Fix: --fixtures only shows fixtures from first file

---

CHANGELOG
_pytest/pytester.py
_pytest/tmpdir.py
doc/en/tmpdir.txt
testing/python/fixture.py
testing/test_conftest.py
testing/test_tmpdir.py

While looking at `tmpdir` for #844, I decided to refactor `tmpdir` a bit to change `TempdirHandler` into a fixture. 
Advantages:
1. New session-scoped fixture `tmpdir_handler` which can be used by other fixtures with scopes other than `"function"` to create temporary directories (`tmpdir` being function-scoped can only be used by function-scoped fixtures). 
Disadvantages:
2. A few plugins might make use of the undocumented `config._tmpdir_handler` attribute (`pytest-xdist` I'm looking at you).
Opening this PR for discussion if it is worth to merge this; if we decide yes, I will write the missing pieces like documentation, CHANGELOG, etc, and also open a PR for `pytest-xdist`.

Introduce tmpdir_factory session fixture

---

CHANGELOG
_pytest/tmpdir.py
tox.ini

Fix for #105 
Using a sub-directory as root in the `TEMP` directory speeds up `make_numbered_dir` calls, because it will loop over all files to find an unused directory name.
```python
import pytest
pytest_plugins = 'pytester'
@pytest.mark.parametrize('i', range(10))
def test_foo(i, testdir):
print(str(testdir.tmpdir))  
```
**before**:
```
========================== slowest 3 test durations ===========================
0.46s setup    test_foo.py::test_foo[0]
0.00s setup    test_foo.py::test_foo[7]
0.00s teardown test_foo.py::test_foo[5]
```
**after**:
```
========================== slowest 3 test durations ===========================
0.00s setup    test_foo.py::test_foo[0]
0.00s setup    test_foo.py::test_foo[7]
0.00s teardown test_foo.py::test_foo[5]
```
The speed-up depends on the …

Use a subdirectory in the TEMP directory to speed up tmpdir creation

---

_pytest/python.py
testing/python/collect.py

Fix for issue #811.
I feel the current implementation is hackish and might break in some corner-cases.
Perhaps it would be better to don't support tests created by `functools.partial` objects at all, and issue a warning during collection and add a note to the documentation?

Collect functools.partial objects

---

.travis.yml

Allow py35 to fail on Travis until it is properly supported (fix2)

---

CHANGELOG
_pytest/skipping.py
testing/test_skipping.py

Report correct reason when using multiple skip/xfail markers

---

tox.ini

Because we are currently using "nighly" python for travis, which
uses python 3.6 as the default interpreter. This breaks the environments
listed above because "inspect.getargspec" has been removed in py36.

Fix basepython for tox envs "doctesting" and "coveralls"

---

CHANGELOG
_pytest/runner.py
testing/test_runner.py

Previously, having a 'dev' version installed (or other version with a non-integer version string) would break `importorskip`.
This PR uses `pkg_resources.parse_version` to parse version strings. This can handle 'dev', 'rc', alpha and beta version strings, among others.

Allow non-integer version strings in `importorskip`

---

testing/conftest.py
testing/test_capture.py

This bug fails the entire pytest suite when executed with the
`--lsof` option in Python 2 on Windows.
Related to this bug: https://bitbucket.org/pytest-dev/py/issues/66

Workaround for cmdexec bug on Windows

---

CHANGELOG
_pytest/config.py
testing/acceptance_test.py

Make passing plugins as str objects a more obvious failure

---

.travis.yml

This is PR #875, but reissued against the pytest-2.7 branch.
According to the docs, it looks like this should work:
http://docs.travis-ci.com/user/languages/python/
I've explicitly specified beta 3, so it will need updating when future betas come out. You could instead specify '3.5-dev', which would give less need to update, but then it's less clear whether a change in status is due to a change in pytest or in Python itself.

Re-enable Python 3.5 testing on Travis

---

CHANGELOG
_pytest/config.py
doc/en/customize.txt
testing/test_conftest.py

Avoid detecting conftest files upwards from setup.cfg/pytest.ini/tox.ini by default

---

_pytest/standalonetemplate.py
testing/test_genscript.py

test_gen in testing/test_genscript.py failed because of its expects setuptools to be installed.
Made genscript fails cleanly when setuptools is not installed.

setuptools not present issue deprecating gentest

---

_pytest/capture.py
testing/test_capture.py

otherwise that exception (and all following output) end up in /dev/null

reset capture even if readouterr throws

---

doc/en/parametrize.txt
testing/python/collect.py

Document and test stacking of parametrize.

---

_pytest/tmpdir.py
testing/test_tmpdir.py

Before tmpdir_factory, pytest used to create a link named "pytest-$user" to the current numbered directory. Use
a different name so there's no conflict when running different pytest versions.
Fix #894

Use pytest-of-$user as base directory for tmpdir_factory

---

doc/en/fixture.txt

`merlinux.eu` seems to be down, so I changed to `smtp.gmail.com` which should prove much more reliable.
Also fixed examples in py3 that where showing the wrong message:
```
TypeError: Type str doesn't support the buffer API
```

Use smtp.gmail.com server for examples and fixes examples for python 3

---

doc/en/assert.txt

This was changed after EuroPython 2014, now both the message and the
introspection is presented.

Update docs to represent reality

---

HOWTORELEASE.rst

`docs/en` -> `doc/en`, so it reflects a real name

fix docs folder name in HOWTORELEASE

---

_pytest/recwarn.py
testing/test_recwarn.py

This ensures that if tests for warnings are run more than once,
the warning is still raised as expected.

Warnings always raised in WarningsRecorder

---

_pytest/python.py
testing/python/metafunc.py

> One day I'll fork py.test and call it "parametrise".
-- @flub ([on Twitter](https://twitter.com/flubdevork/status/626019628741996545))
I saw the "misspelling" check for "parameterize", so I thought why not add "parametrise" and "parameterise" as well to make it a bit easier for `en_GB` users :wink:
(All of them seem to be valid spellings, depending on whom you ask)

Alert user about other parametrize spellings.

---

CHANGELOG
_pytest/python.py
testing/python/metafunc.py

I noticed my tests were generating default IDs for those, so I thought why not make pytest a bit smarter :wink:

Generate parametrize IDs for enum/re/class objects.

---

CHANGELOG
_pytest/python.py
testing/test_nose.py

Fix for https://github.com/pytest-dev/pytest/issues/562

Issue #562 - Ensure @nose.tools.istest is respected

---

doc/en/example/simple.rst

Change docs to use hookwraper instead of __multicall__

---

AUTHORS
CHANGELOG
_pytest/python.py
testing/python/collect.py
testing/python/fixture.py

Don't skip fixtures that are substrings of params

---

CHANGELOG
_pytest/doctest.py
doc/en/doctest.rst
testing/test_doctest.py

Code and option copied from the [nltk](https://github.com/nltk/nltk) project.
Fixes #710.
cc @jaraco

New ALLOW_UNICODE doctest option

---

.travis.yml
AUTHORS
CHANGELOG
_pytest/main.py
_pytest/terminal.py
testing/acceptance_test.py
testing/python/collect.py
testing/test_assertrewrite.py
testing/test_capture.py
testing/test_collection.py
testing/test_config.py
testing/test_conftest.py
testing/test_helpconfig.py
testing/test_junitxml.py
testing/test_pluginmanager.py
testing/test_runner.py
testing/test_session.py
testing/test_terminal.py
testing/test_unittest.py
tox.ini

return non-zero exit code if no tests are collected

---

AUTHORS
CHANGELOG
_pytest/junitxml.py
doc/en/_getdoctarget.py
doc/en/usage.rst
testing/test_junitxml.py

Continuing from #952 
* Tweaked docs a bit
* Using warnings system to warn about the experimental feature
* Unrelated, `getdoctarget` was failing on my system, I applied a quickfix.
cc @dajose22
Fixes #951

Record xml property

---

CHANGELOG
_pytest/config.py
testing/test_config.py
testing/test_parseopt.py

Paths after normal options are now properly used to discover rootdir and ini files

---

CHANGELOG
_pytest/assertion/__init__.py
testing/test_assertion.py

Fix #934
cc @RonnyPfannschmidt

Show a few diff lines when truncating string diffs

---

_pytest/config.py
testing/test_parseopt.py

Sorry about that, for some reason it didn't occur to me that `parse_known_args` was part of the public API. :sweat_smile: 
Fix #973

Fix regression caused by changing the signature for parse_known_args

---

_pytest/python.py
testing/python/fixture.py

Fixes #979, see #926.
/cc @untitaker

Fix overriding of fixtures with parametrization.

---

_pytest/monkeypatch.py

Note that calling `undo()` is generally not needed, and describe the "gotcha" discovered in #981.

Add notes to docstring of `monkeypatch.undo()`

---

CHANGELOG
_pytest/pytester.py
_pytest/terminal.py
testing/test_config.py
testing/test_terminal.py

Rename "warnings" to "pytest-warnings" in terminal output

---

CHANGELOG
_pytest/doctest.py
testing/test_doctest.py

Make doctest SKIP option register doctests as SKIPPED rather than PASSED

---

_pytest/config.py
_pytest/helpconfig.py
_pytest/hookspec.py
_pytest/main.py
testing/test_pluginmanager.py

this will replay all early warnings using the pytest_logreport hook
that way warnings no longer can get lost (happens for the planned early cache warnings)

replay initial warnings when terminalreporter is loaded

---

doc/en/usage.rst

It is possible to run a single test method in a class, but the syntax is not glaringly obvious and I think a bit of documentation would help people out.

Document single-method usage

---

_pytest/tmpdir.py
testing/test_tmpdir.py

Make tmpdir more resilient in case environment variables required by getpass are missing

---

_pytest/python.py
testing/python/metafunc.py
testing/test_runner.py

`inspect.getargspec` raises `DeprecationWarning` on Python 3.5.  It turns out that all of the uses of `getargspec` in `py.test` can be safely replaced with `getfullargspec`, when available.
In `astropy`, we run our tests with `DeprecationWarnings` converted to exceptions to make sure we are on top of any API changes in Python or third-party dependencies.  Since `py.test` now raises `DeprecationWarnings` as a matter of course on Python 3.5, this is a bit of a problem.

Use getfullargspec if available

---

_pytest/junitxml.py
doc/en/usage.rst
testing/test_junitxml.py

According to [1], custom properties should be listed inside of
properties element instead of being testcase attributes.
[1] http://help.catchsoftware.com/display/ET/JUnit+Format

junitxml: align custom properties with junit format

---

_pytest/tmpdir.py
testing/test_tmpdir.py

Previously, the tmpdir fixture would fail if the current process's user id does not correspond to a valid user (e.g. running pytest in a Docker container with 'docker run -u').

Make tmpdir resiliant to user ids that do not exist

---

CONTRIBUTING.rst

At PyCon we realised that the virtualenv created in the make file wasn't
used in the subsequent steps in CONTRIBUTING.rst. This change removes the
reference the make and suggesting installing tox directly.
Also changed the explanation that follows to make more sense with this
change

contributing: Add instructions from PyCon

---

doc/en/assert.rst

This makes the example make more sense, because now Foo(1) == Foo(1) is
true. Fixes #411

Add __eq__ method to assertion comparison example

---

CHANGELOG
_pytest/python.py
testing/python/metafunc.py
testing/test_cache.py

Just added the test to see what was going on. This is the value of the `lastfailed` attribute when it fails:
```python
{'test_cache_param.py::test_fail[\xac\x10\x02G]': True}  
```
I thought `nodeids` would always be a "well formed" string, was I wrong or perhaps this is a bug? @RonnyPfannschmidt or @hpk42?
Committing directly to pytest repository to get feedback from others on how to proceed (and contribute directly to this branch).
Related to #1030

Parametrized values containing non-ascii bytes break cache

---

doc/en/fixture.rst

It certainly wasn't clear to me that the variable assigned by
pytest.mark.usefixtures should also be called pytestmark,
so I was confused when::
foo = pytest.mark.usefixtures('fixture_bar')
wasn't behaving as expected; correct usage is of course::
pytestmark = pytest.mark.usefixtures('fixture_bar')
I assume this is by design, otherwise that's a separate issue, at
least current behaviour should be documented.

Docs: Fixtures page - clarify usage of module-level pytestmark.

---

CHANGELOG
_pytest/junitxml.py
doc/en/usage.rst
testing/test_junitxml.py

Wrong xml report when used with pytest-xdist

---

doc/en/cache.rst
doc/en/contents.rst
doc/en/plugins.rst

Change the organization in a more logical way to a newcomer. 
Changed the order of the documents that are displayed in the page, plus small caps adjustment in one title or another for consistency Here's the top-level titles of the end result:
* Getting started basics
* Usages and Examples
* Installing and Using plugins
* Cache: working with cross-testrun state
* Contribution getting started
* List of Third-Party Plugins
* Talks and Tutorials
* pytest-2.3: reasoning for fixture/funcarg evolution
* Release announcements
I feel that *pytest-2.3: reasoning for fixture/funcarg evolution* should be placed somewhere else? It is mostly historic at this point, and it takes some space in the "Contents" page, which arguably gets a lot of traffic from new users.

Reorganize "Contents" page

---

.travis.yml
appveyor.yml
tox.ini

* Update `trial`, `pexpect` and `xdist` to use `py35`
* Test py35 on AppVeyor
* Test `py27-xdist` and `py35-xdist` on AppVeyor

Use py35 as preferred py3 interpreter for special test environments

---

CHANGELOG
_pytest/recwarn.py
testing/test_recwarn.py

The first commit ensures `deprecated_call` now looks for PendingDeprecationWarnings, as it did previously but was broken by #897. Fixes #1037. Also added a test so this does not happen again.
I realized that before 2.8.0, `deprecated_call` would be fine with any warning being raised, not just a DeprecationWarning or PendingDeprecationWarning. The second commit ensures that other warnings do not suffice.

`deprecated_call` detects pending warnings again

---

_pytest/config.py
testing/test_pluginmanager.py

Otherwise KeyError: 'nodeid' gets thrown, killing pytest. This may fix issue #1034, but the details and it may be caused by something similar somewhere else.

Add missing nodeid on pytest_logwarning call in addhook.

---

_pytest/capture.py
_pytest/runner.py

This will make `Item.add_report_sect` more usable for plugins.
See https://github.com/eisensheng/pytest-catchlog/pull/7

Don't hardcode 'std' for captured stdout/stderr.

---

_pytest/helpconfig.py
doc/en/cache.rst
doc/en/plugins.rst

After discussion in #1029
I suggest we start to advise people who are having problems related to `cache` to use this trick so it doesn't affect their use of `pytest-2.8` and force them to pin down to `pytest-2.7.X`.

Add docs on how to disable cache provider

---

doc/en/example/simple.rst

Change the code snippet in the documentation on [skipping tests based on cli options](http://pytest.org/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option).
The code now features a ``skipif`` marker that directly looks up whether the ``--runslow`` option has been set. If so, the test runs as usual otherwise it will be skipped.
*Please note that I did not recreate the tracebacks*.
Resolve #536 :bow:

Update docs skip with cli option

---

_pytest/python.py

This addresses two issues:
1. A typo I just noticed in my original submission (assignment instead of comparison).
2. I also noticed that the note was moved from where originally placed in #1106. I think that it serves the users much better where originally placed. By moving it below, you miss the context (hah!) of the section in the docs that it addresses. Also in moving it out-of-band, should someone find the section on context managers, they will generally not continue reading once the docs move into other usages (at least that's what I'd do ;)) and so the change of missing this note entirely is increase.
I realize that point 2 is subjective, so won't be put off (too much ;)) if rejected.

typo fix, changed position of context manager notes

---

CHANGELOG
_pytest/python.py
testing/python/collect.py

Fix for https://github.com/pytest-dev/pytest/issues/1035
Have confirmed the test fails on Python 2.6 without the fix.
Appreciate feedback as to whether the python.py bit should be tidied away into a function?

Issue1035 getattr

---

CHANGELOG
_pytest/doctest.py
testing/test_doctest.py

The problem was that `DoctestModule` was setting up fixtures before forwarding a `getfixture` function to the doc-tests; the correct approach is to actually let each `DoctestItem` configure its own fixtures during its `setup` phase.
Took the opportunity to add a lot of tests with all possible scopes to ensure all of them work properly.
Fix #1100 
Fix #1057 
Probably also fixes #943

Fix autouse fixtures and doctest modules

---

doc/en/assert.rst

In this file, the indentation of code block is not consistent.  But in this case the indentation of the python code in unusual.

[doc] Fixed indentation

---

AUTHORS
CHANGELOG
_pytest/python.py
testing/python/collect.py

Fixes issue 331
previously to this change the collection code would issue a warning for
when ever it encountered a variable that looked like a test but wasn't a
function saying that it wouldn't collect it because it wasn't a function.
This fixes the logic so that if that warning is issued it really isn't
collected.
However previously special cases existed to support tests that were
created using functools.wraps and functools.partial. So the condition for
issuing that warning has been updated to take that in to account

Prevent non-function callables from being collected

---

CHANGELOG
_pytest/python.py
testing/python/collect.py

Found a reproducible case. :smile:
Fix #1133

Fix situation where a traceback entry "path" returns a str object

---

_pytest/main.py

Unused since 2012, and the docstring syntax is incorrect with
four quotes.

Remove commented out extrainit

---

AUTHORS
CHANGELOG
_pytest/terminal.py

I'm proposing this small enhancement because it is sometimes difficult, especially when using verbose tests output, to immediately spot which tests are failing in the middle of all the tracebacks and other output messages. I believe by highlighting the separator line containing the test name which is failing in red would allow developers to quickly spot the failed test and target where his next action should be.

Color highlight on the name of the failed tests

---

_pytest/assertion/rewrite.py

Fixes #1143.
I'm afraid I have no idea how to write a test for this, but I'd guess the existing tests already fail on OS X El Capitan.
@hannes-ucsc any chance you could test it, by doing something like this (or putting this URL in your `tox.ini`)?
`pip install git+https://github.com/The-Compiler/pytest.git@elcapitan-sip`

Handle EPERM when writing rewritten bytecode.

---

doc/en/goodpractises.rst

I've found [pytest-runner](https://pypi.python.org/pypi/pytest-runner) module to be an easier way for setuptools integration. So here's an update to the docs.

Use pytest-runner for setuptools integration

---

AUTHORS
CHANGELOG
_pytest/unittest.py
testing/test_unittest.py

Supersedes #1170
CC @LeeKamentsky

Allow @unittest.skip decorators in Python 2.7

---

AUTHORS
CHANGELOG
_pytest/unittest.py
testing/test_unittest.py

Hi all,
I am not sure if this is the best fix, but it does make it possible to use @unittest.skip on a testcase method. In any case, I have a test for #1169 which demonstrates the bug and that itself is useful.
--Lee

Fixes #1169

---

doc/en/talks.rst

Hi there!
Earlier this year, I shared the awesomeness that is Pytest at PyCon SG here in Singapore. The video is online and I thought it would be nice to add it to the list in Pytest's documentation.
This PR adds the talk video to the docs. I'm assuming the links are in reverse chronological order, so I added mine near the top.

Add 'Improve your testing with Pytest and Mock' video from PyCon SG 2015

---

CHANGELOG
_pytest/recwarn.py
testing/test_recwarn.py

`deprecated_call` now uses monkey patching strategy to capture warnings
similar to what we had in 2.7, with a few enhancements
Fix #1190
cc @hunse

Make deprecated_call() use monkey-patching again 

---

CHANGELOG
_pytest/python.py
testing/python/collect.py

When an object has a custom `__getattr__` which always returns a non-int, we
tried to get `compat_co_firstlineno` from it and checked it was a integer, which
caused an exception if such a class is mistakenly collected.
If we still mistakenly collect such a class (which is likely to be something
other than a test), we now skip it with a warning (because it probably has an
`__init__`) instead of producing an error.
See #1204.

Fix getting line number with nasty __getattr__.

---

_pytest/python.py
testing/python/integration.py

When we have a metaclass which returns something truthy (like a method) in its
`__getattr__`, we collected the class because pytest thought its `__test__`
attribute was set to True.
We can work around this to some degree by assuming `__test__` will always be set
to an explicit True if that's what the user has intended, and if it's something
other than that, this is probably a mistake.
Fixes #1204.

Don't collect classes with truthy __getattr__.

---

CHANGELOG
_pytest/terminal.py
testing/test_terminal.py

This finally annoyed me enough to open a PR after noticing it for dozen of times :wink:
Before:
```
====  in 0.00 seconds ====
```
After:
```
==== no tests run in 0.00 seconds ====
```

Fix terminal output if no tests were run.

---

doc/en/writing_plugins.rst

xdist is now hosted on GitHub.

Update xdist newhooks.py link; BitBucket -> GitHub

---

doc/en/customize.rst
doc/en/faq.rst
doc/en/goodpractises.rst

Fixed #1134 and took opportunity to review and reorganize `goodpractises` a little.
* Moved "Conventions for Python test discovery"  and "Choosing test layout" to the top
* Moved deprecated genscript method to the bottom and added a `.. deprecated:` directive;
* Removed detailed session about setuptools and `genscript` integration, since the latter is deprecated anyway;
* Merged `tox` and `virtualenv` sessions: Nowadays virtualenv's usage is pretty standard so we don't need to devote a how-to section in pytest's docs

Goodpractises docs reorganization/review

---

doc/en/recwarn.rst

Add a note about how DeprecationWarning and PendingDeprecationWarning are treated differently

---

CHANGELOG
_pytest/junitxml.py
testing/test_junitxml.py

i started by running yapf on junitxml to get my ide warning-free
did the same on its tests and will simplify the test api a bit (i want the xml api out of the picture)
Fix #1074
Fix #641

fix issue 1074 and clean up junitxml

---

AUTHORS
CHANGELOG
_pytest/runner.py
_pytest/skipping.py
_pytest/terminal.py
testing/test_terminal.py

`-rP` is an alternative to `-s` for viewing the output of passing tests.
This causes the captured stdout/stderr of passing tests to be output in
the same way as that of failing tests.
`-rp` adds a simple one-line-per-test summary for passing tests.
Neither option is included by `-ra`.
~~Additional changes to `pytest_capturelog` and `pytest_catchlog` are
needed for this option to also output captured logs: They must be
changed to use `rep.sections.add` instead of `rep.longrepr.addsection`,
and to add these additional sections even if the test passes, since
passing tests don't seem to have a `longrepr` at report time.~~

Add -rp and -rP options to report passing tests.

---

_pytest/hookspec.py

Noticed that this hook was still marked as experimental since 2.4 while working on pytest-dev/pytest-faulthandler#14

Remove experimental status from pytest_exception_interact

---

CHANGELOG
_pytest/junitxml.py
testing/test_junitxml.py

this allows double node id usage for file based items

fixes #1259 - take finalized nodes out of the mapping

---

doc/en/overview.rst

"index" is already displayed in the main docs, repeating it here breaks the reading flow.
From [contents](http://pytest.org/latest/contents.html):
* Getting started basics
* pytest: helps you write better programs  <-- this link will be removed
* Installation and Getting Started
* Usage and Invocations
* Good Integration Practices
* Project examples
* Some Issues and Questions

Remove "index" entry from overview.rst

---

AUTHORS
CHANGELOG
_pytest/capture.py

This implements a workaround to a bug that's been dogging me for a long time.  When using py.test with the `--pdb` option on Windows, file descriptor capture enabled, and pyreadline installed, as soon as the pdb prompt is dropped into pyreadline starts bugging out.
Part of the problem is pyreadline, which doesn't work well when standard I/O handles have been redirected.  It does some import-time setup that attaches itself to whatever handles standard I/O have been redirected to, and blows up if stdout is no longer a TTY.  I'm working on addressing this issue in pyreadline.
A simple workaround, that should work for the vast majority of cases in the context of pytest, is to just make sure to `import readline` before any redirection is done.  This way pyreadline still connects correctly to …

Prevent pyreadline from bugging out in --pdb mode with capture

---

CHANGELOG

Added an extra *Changes* section as suggested by @RonnyPfannschmidt.
Also replace section titles from `---` to `===`, and changed sections to then use `---`. With sections, this looks better IMO. 
Fix #1275

Separate 2.9.0 CHANGELOG into sections

---

README.rst

* Show pytest logo
* Show assertion introspection in the example
* Use separate sections for change-log, docs, license, etc.
Borrowed some ideas from [awesome-readme](https://github.com/matiassingers/awesome-readme).
Please see [my fork](https://github.com/nicoddemus/pytest/tree/readme-changes-logo) to checkout how it looks.

Add logo and some readme changes

---

README.rst

Please take a look [at my fork](https://github.com/nicoddemus/pytest/tree/pyversions-badge) to see how it looks like.

Add badge of supported python versions to README

---

CHANGELOG
_pytest/monkeypatch.py
testing/test_monkeypatch.py

Previously `monkeypatch` assumed that any `ImportError` was caused by
a mistake in the specified import path. However this assumption is false 
in case the import target itself causes an `ImportError`.
Fixes: #900

Make monkeypatch differentiate ImportError sources

---

CHANGELOG
_pytest/terminal.py
testing/test_terminal.py

pytest warnings emitted during ``pytest_terminal_summary`` are now properly displayed.

---

doc/en/example/markers.rst

I found this inconsistency while writing platform specific tests at https://github.com/nibrahim/cpslib/commit/fe4dfc3b893af24cbb57722e2c6afce297c223cc#diff-484462fced51d1a06b1d93b4a44dd535

Correct platform name osx -> darwin

---

AUTHORS
_pytest/pdb.py
testing/test_pdb.py

Fixed stdout/stderr capture when using pdb

---

CHANGELOG
_pytest/doctest.py
testing/test_doctest.py

My initial approach to fix this was to correct how we were opening the file:
```diff
--- a/_pytest/doctest.py
+++ b/_pytest/doctest.py
@@ -81,7 +81,9 @@ class DoctestItem(pytest.Item):
reprlocation = ReprFileLocation(filename, lineno, message)
checker = _get_unicode_checker()
REPORT_UDIFF = doctest.REPORT_UDIFF
-            filelines = py.path.local(filename).readlines(cr=0)
+            import io
+            with io.open(str(filename), 'rU', encoding='UTF-8') as f:
+                filelines = [x.rstrip('\n') for x in f.readlines()]
lines = []
if lineno is not None:
i = max(test.lineno, max(0, lineno - 10)) # XXX?
```
But assuming that the file was in `utf-8` let me uneasy.
Studying the code a little more I realized that the `DocTest` object already contained the docstring that resulted …

Fix decode error in Python 2.7 when docstrings contain a non-ascii character

---

CHANGELOG.rst
_pytest/assertion/__init__.py
testing/test_assertion.py

When you don't get enough information with a test running on a CI, it's quite
frustrating, for various reasons:
- It's more likely to be a flaky test, so you might not be able to reproduce
the failure.
- Passing -vv is quite bothersome (creating a temporary commit and reverting
it)
For those reasons, if something goes wrong on CI, it's good to have as much
information as possible.

Always show full comparison output if on CI.

---

doc/en/parametrize.rst

Using `input` is confusing because it's also the name of a Python built-in function. So we use `test_input` instead. Fix #1321

Change `input` to `test_input` in docs for clarity

---

README.rst
doc/en/getting-started.rst
doc/en/goodpractices.rst
doc/en/index.rst
doc/en/overview.rst
doc/en/writing_plugins.rst

From the "Usage" section of http://www.oxforddictionaries.com/definition/english/practice:
> Practice is the correct spelling for the noun in both British and US English and it is also the spelling of the verb in US English. However, in British English the verb should be spelled practise.
I generated the doc locally and it looks fine AFAICT. Not sure what your workflow is for checking documentation changes. If needed I can upload it to my github.io.

Fix practise -> practice typo in documentation

---

.travis.yml
appveyor.yml
tox.ini

I don't know how I did not realize before that we can use [chocolatey](https://chocolatey.org/) to install PyPy... :sweat_smile: 
Also following the same logic as discussed in pytest-dev/pytest-xdist#43, run all tox environments in AppVeyor.
* Install pypy using chocolatey
* Running coveralls environment in AppVeyor
* Suggest maintaining build matrix in .travis.yml by using "tox --listenvs"
Note: I created the PR in a branch directly in pytest-dev instead of my fork because I'm using pytestbot's encryption key to encrypt the coveralls secret.
Fix #1254

Test with pypy and enable coveralls in AppVeyor

---

CHANGELOG
_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

Fix for https://github.com/pytest-dev/pytest/issues/1290
Support `ast.MatMult` when it's present. And add a test that runs on Python 3.5+. See [PEP 465](http://legacy.python.org/dev/peps/pep-0465/) -- A dedicated infix operator for matrix multiplication

Fix #1290: Py3.5's @ operator/assertion rewriting.

---

_pytest/config.py
_pytest/skipping.py
doc/en/skipping.rst
testing/test_config.py
testing/test_skipping.py

* Add bool type to `addini`
* I reviewed `skipping.rst` while adding the new docs, I think it is easier to use it as a reference while staying true to its original "tutorial" intent (a crude rendering can be seen [here](https://gist.github.com/nicoddemus/b2964b1ee65258885043)).
* I didn't mention anything about future plans of changing the default value of the `strict` parameter from `False` to `True`. Not sure if we want to do that or not.
Fix #1355

Add a "strict" parameter to xfail

---

CHANGELOG.rst
doc/en/cache.rst
doc/en/parametrize.rst
doc/en/skipping.rst
doc/en/writing_plugins.rst

Noticed [this docs typo](https://pytest.org/latest/writing_plugins.html#writing-your-own-plugin) (you get italics because \`single backticks\` are rendered as \<cite\> tags):
Fixed ([links here](https://pytest.org/latest/plugins.html#builtin-plugins)):
Had a look for other accidental \<cite\> tags, which make up the rest of this PR.
For convenience in reviewing this, here's the diff of the generated docs https://github.com/tomviner/pytest/commit/5c79745c2f28a3f39001e505ad1436fe97c702b2 (I made a new branch off master, committed the doc/en/_build directory, cherry-picked this PR, and committed doc/en/_build again - this final commit is linked.)
Wasn't sure if this warranted a changelog entry?

Fix usage of backticks in ReStructured Text files

---

LICENSE
README.rst
doc/en/_templates/globaltoc.html
doc/en/index.rst
doc/en/license.rst

Hi there :bow: 
Referring to the terms that pytest is released under is even more important now that we are running a funding campaign.
In the long run we may want to to include **LICENSE** from the repo root instead of having a separated reStructured text file in the docs (a relative include is obnoxious with in this particular case though).
Resolve #1328

Add license section to homepage

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.rst

As discussed in the mailing list, making use of this new GH feature
Also added the blank entries on the `CHANGELOG` to avoid merge conflicts.

Add issue and PR GitHub templates

---

doc/en/example/simple.rst

This is a very minor tweak to the documentation to change `--junit-xml` → `--junitxml`.

Correct JUnit test invocation example

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/test_runner.py

This is a followup to #1003 which simplifies the test using a monkeypatch.

catch IndexError exceptions when getting exception source location

---

_pytest/mark.py

The docstring for `mark.MarkGenerator` imports `py` and then uses `pytest.mark`, this PR changes the import to `pytest`.

Fix a typo in the docstring for mark.MarkGenerator

---

CHANGELOG.rst
doc/en/usage.rst

Fix [traceback style docs](https://pytest.org/latest/usage.html#modifying-python-traceback-printing
) to describe all of the available options (auto/long/short/line/native/no), with `auto` being the default since [pytest v2.6](https://pytest.org/latest/announce/release-2.6.0.html#id1)

Fix docs on traceback styles

---

AUTHORS
CHANGELOG.rst
_pytest/junitxml.py
testing/test_junitxml.py

It might happen that test can be affected by two or more bugs.
I need to be able to track them all.
Fix #1422

junit: allow multiple properties with same name

---

AUTHORS
CHANGELOG.rst
_pytest/doctest.py
doc/en/doctest.rst
testing/test_doctest.py

This resolves #1047 by introducing a new fixture `doctest_namespace`. This fixture can be used to inject names into the namespace in which your doctests run. The basic usage is described in `doctest.rst` but it works like:
```python
import numpy
@pytest.fixture(autouse=True)
def add_np(doctest_namespace):
doctest_namespace['np'] = numpy
```
which can then be used in your doctests directly::
```python
def arange():
"""
>>> a = np.arange(10)
>>> len(a)
10
"""
pass
```
This is my first contribution to pytest so I welcome any feedback on style etc.

Add a new doctest_namespace fixture

---

CHANGELOG.rst
_pytest/junitxml.py
testing/test_junitxml.py

Fix for https://github.com/pytest-dev/pytest/issues/469
A Node ID with all the components looks like this:
`testing/test_skipping.py::TestSkipif::()::test_skipif_reporting_multiple[param-data-maybe-a-some-colons-::]`
This PR:
- Split the nodeid by `[`, before splitting by `::`
- remove `.py` only when at end of file path

issue469: add fix junit double colon split issue

---

CHANGELOG.rst
testing/test_junitxml.py

Additional test as recommend before https://github.com/pytest-dev/pytest/pull/1431 was merged :-)
Also added name to the changelog entry. And repositioned the rst link definition.
While I'm here couple comments on the changelog:
- ~~we're in risk of the `(#469_)` numbers referencing both issues and pull requests clashing (both are up to around 1400 now). Obviously all links are explicitly defined, but could be confusing. rst-lint will error on duplicate definitions, but if someone forgets the 2nd definition, it would silently reference the first. Maybe reference PRs as `(PR#469_)` and keep `(#469_)` for issues?~~
- minor point, but all the trailing whitespace makes editing the changelog difficult as my editor strips it. Would someone be happy stripping it? Or maybe my editor settings are …

issue469: junit parsing nodeid, add method test

---

CHANGELOG.rst
_pytest/_code/_py2traceback.py
testing/code/test_code.py
testing/python/collect.py

This happens only in Python 2, as in Python 3 we receive
the "badline" in the exception is already properly encoded
Fix #578

Fix decoding issue while formatting SyntaxErrors during collection

---

CHANGELOG.rst
_pytest/python.py
_pytest/runner.py
testing/test_runner.py

Fix #1178
(oops, sent the branch to `pytest`'s repository by accident, sorry)

pytest.fail with non-ascii characters raises an internal pytest error

---

CHANGELOG.rst
_pytest/config.py
testing/test_pluginmanager.py

Currently when a plugin fails to load, pytest will display only the bare import error message, which might be difficult to diagnose the problem depending on the number of plugins installed  
For example, suppose we have a broken installation of `pytest_cov` which is missing the plugin module `pytest_cov.plugin`, the error message given by `py.test` is:
```
$ py.test -p pytestqt.plugin -p pytest_cov.plugin -p pytest_timeout ...
<... long traceback ...>
No module named 'plugin'
```
This PR just adds the full name of the plugin module which py.test is attempting to load to the exception message:
```
$ py.test -p pytestqt.plugin -p pytest_cov.plugin -p pytest_timeout ...
<... long traceback ...>
Error importing plugin "pytest_cov.plugin": No module named 'plugin'
```
I encountered this …

Improve error message when a plugin fails to import

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/python/fixture.py

When defining a fixture in the same module as where it is used, the
function argument shadows the fixture name, which a) annoys pylint and
b) can lead to bugs where you forget pull a fixture into a test method.
This allows one to define fixtures with a custom name override,
bypassing that problem.
I felt a little weird about thanking myself in the changelog.

Allow custom fixture names for fixtures

---

AUTHORS
_pytest/hookspec.py

Pointed out in https://github.com/pytest-dev/pytest-django/issues/300#issuecomment-194565905.
Not adding a changelog entry for this; but/and it should get "backported" probably.

doc: fix argument order for pytest_load_initial_conftests

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
doc/en/builtin.rst
testing/python/approx.py

This pull request adds a convenience class to assert that two floating-point numbers (or two sets of numbers) are equal to each other within some margin.  You give the class the number you're expecting to get, and the class overrides the "==" operator to do the comparison behind the scenes with a reasonable margin for error.    Most unit testing frameworks have some sort of  ``assertAlmostEqual()`` function to provide this functionality, but to my knowledge ``pytest`` doesn't have anything of the sort.  I think this pull request provides a useful feature in a way that dovetails nicely with the way ``pytest`` deconstructs assert statements.
Tests and documentation are included.  I ran all the tests on python2.7 and python3.4, but I'm a little worried that the way I use unicode in …

Add a convenience function for floating-point comparisons

---

AUTHORS
CHANGELOG.rst
_pytest/main.py
testing/test_mark.py

This PR solves the problem specified in Issue #649.
I added the test to test_mark but i am not so sure that is the right place.

Specify paramterized node in command line - Issue #649

---

AUTHORS
CHANGELOG.rst
_pytest/junitxml.py
doc/en/usage.rst
testing/test_junitxml.py

The commit allow users to add a properties node in testsuite level see
example below:
```xml
<testsuite errors="0" failures="0" name="pytest" skips="1" tests="1"
time="11.824">
<properties>
<property name="ARCH" value="PPC"/>
<property name="OS" value="RHEL 7.2"/>
<property name="TestPlanURL" value="https://url.."/>
<property name="Automated" value="True"/>
</properties>
<testcase classname="git.....>
</testcase>
</testsuite>
```
The current situation is that properties node can be added to every
testcase node. However, sometimes we need some global properties that
applies to all testcases and give better description for the testsuite
itself.

junitxml: add properties node in testsuite level

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

This pull request is allowing the user to pass None as a specific test id of parametrize. If a test id is None the specific test id will be automatically calculated.
import pytest
@pytest.mark.parametrize(("a,b"), [(1,1), (1,1), (1,2)],
ids=["basic", None, "advanced"])  
def test_function(a, b):
assert a == b
This will result in the following tests:
- test_function[basic]
- test_function[1-1]
- test_function[advanced]
As a side effect of this PR i noticed that when you pass the same test id we recieve a duplicate test:
import pytest
@pytest.mark.parametrize("a,b", [(1,2), (3,4)], ids=["a", "a"])
def test_a(a,b):
pass
Currently result in the test:
- test_a[a]
- test_a[a]
After this change the result will be:
- test_a[0a]
- test_a[1a]
Same as when a ids callable return the same value.

None in paramtrized test id will use automatically generated id

---

AUTHORS
CHANGELOG.rst
_pytest/skipping.py
testing/test_skipping.py

This targets master since it's a bug, but no CHANGELOG or AUTHORS since I'm only sending a xfail test. Should I still do something to one of those files?

Fix pytest.mark.skip mark when used in strict mode

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

As @RonnyPfannschmidt mentioned in pull request #1468 the name selection in case of duplicate ids had some problems.
Let's take for example:
import pytest
@pytest.mark.parametrize("a", [1,2,3,4,5,6], ids=["a", "a", "b", "c", "b", "l"])
def test_a(a,b):
pass
Before this change the tests names would be:
- test_a[0a]
- test_a[1a]
- test_a[2b]
- test_a[3c]
- test_a[4b]
- test_a[5l]
After this change:
- test_a[a0]
- test_a[a1]
- test_a[b0]
- test_a[c]
- test_a[b1]
- test_a[l]

Improve idmaker name selection in case of duplicate ids in parametrize

---

_pytest/mark.py
testing/acceptance_test.py

This solves the following bug.
Given and example test mod `test_name_filter.py`:
```python
def test_4x4():                
pass                       
if __name__ == '__main__':     
import pytest              
pytest.main(["-k not 4x4"])
```
Running from an IPython shell:
```python
In [26]: run ./test_name_filter.py                                                                           
================================================= test session starts =======================================
platform linux2 -- Python 2.7.11, pytest-2.9.0, py-1.4.31, pluggy-0.3.1
rootdir: /home/tyler/pytest_bugs, inifile: 
plugins: interactive-0.1.1, ordering-0.4, instafail-0.3.0
collected 1 items 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File …
```

Always lstrip() keyword expression

---

AUTHORS
CHANGELOG.rst
_pytest/_code/code.py
doc/en/assert.rst
testing/code/test_excinfo.py

Implement ExceptionInfo.match() method

---

AUTHORS
CHANGELOG.rst
_pytest/_code/code.py
_pytest/runner.py
testing/code/test_excinfo.py

The change fixes #138. Exception chain is printed according to [PEP-3134](https://www.python.org/dev/peps/pep-3134/).  
The tracebacks of each exception in the chain are the same as tracebacks of non-chained exceptions in py.test. The tracebacks are delimited by `The above exception was the direct cause of the following exception:` or `During handling of the above exception, another exception occurred:` messages, depending on `__cause__` or `__context__` respectively.  If an exception has both `__cause__` and `__context__`, `__cause__` takes priority. The messages are yellow-colored as it looks better than cyan delimiters:

Fix issue #138 (targeted to features branch)

---

AUTHORS
CHANGELOG.rst
_pytest/_code/code.py
testing/code/test_excinfo.py

Properly handle errors with unicode messages (could cause unicode decode errors when converting to `str`).
Added test to check if different encodings in raised error will not cause the code to fail.

Fix `repr_traceback` to work with unicode errors

---

doc/en/example/pythoncollection.rst

LaTeX doesn't like those particular unicode chars, so let's avoid them so the
PDF builds easily.

doc: Use ascii chars for file tree

---

_pytest/_code/code.py

The TracebackItem class does not exist, but it seems the docstrings refer to
TracebackEntry.

Fix TracebackItem documentation in pytest.code

---

CHANGELOG.rst
_pytest/_code/code.py
doc/en/example/simple.rst
testing/code/test_excinfo.py

When `__tracebackhide__` gets set to an exception type or list/tuple of exception types, only those exceptions get filtered, while the full traceback is shown if another exception (e.g. a bug in a assertion helper) happens.

Filter selectively with __tracebackhide__

---

AUTHORS
CHANGELOG.rst
_pytest/config.py
testing/test_config.py

Issue description:
Under `win32` machine:
```
import pytest
get_ini_path = from_some_other_func
pytest.main("-c " + get_ini_path)
```
Look at the ``shlex.split`` signature:
```
shlex.split(str, posix=True)
```
the ``posix`` default value is ``True``, once I passed a `win32` path (e.x. `D:\tests\pytest.ini`) into `shlex.split`, it will output as `Dtestspytest.ini`. This PR will check the platform firstly before applying the `win32` path into `shlex.split`.

Fix a small issue about shlex.split not working well with win32 path

---

CHANGELOG.rst
_pytest/python.py
testing/acceptance_test.py
testing/python/collect.py
testing/test_collection.py
testing/test_session.py
testing/test_terminal.py

A few tests are still failing and need to be fixed. I will do that and adapt the `CHANGELOG` if the change makes sense.
I honestly don't see much point in fixing #1426 (but did it because it looked simple enough).
One of the reasons for failing to import the test module is invalid Python
identifiers in the full package path of the test module.
fix #1426

Raise CollectError if import test module fails

---

CHANGELOG.rst
_pytest/hookspec.py
_pytest/python.py
doc/en/writing_plugins.rst
testing/python/metafunc.py

This PR is implementing @nicoddemus suggestion in issue #930.

pytest_make_parametrize_id hook

---

_pytest/python.py

Documentation for FixtureRequest.scope should say "class" instead of "cls".

Fix typo in doc

---

CHANGELOG.rst
doc/en/announce/release-2.9.0.rst
doc/en/bash-completion.rst
doc/en/example/simple.rst
doc/en/links.inc
doc/en/nose.rst
doc/en/projects.rst
doc/en/writing_plugins.rst
setup.py

As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified. One was not modified - `http://media.readthedocs.org/epub/pytest/latest/pytest.epub` - since it doesn't work on `readthedocs.io`.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

testing/test_mark.py

this pr ads a xfailing test for #1540 based on the bug report
fixing it is dependent on #1534 and followups

Document #1540

---

AUTHORS
CHANGELOG.rst
_pytest/unittest.py
testing/test_unittest.py

__test__ needs to be checked for methods of a class too. Earlier,
this was not done, and all methods in a class was assumed to be
a test. This commit adds the appropriate condition to ensure that
if the __test__ is set to False, it does not collect that method.
Fixes https://github.com/pytest-dev/pytest/issues/1558

unittest.UnitTestCase: Allow __test__ for methods

---

CHANGELOG.rst
_pytest/main.py
doc/en/customize.rst
testing/test_collection.py

Fix for https://github.com/pytest-dev/pytest/issues/1544
I've put the new `dist` and `build` strings near the front of the list as I figure these are more common than directory names like `CVS` and `_darcs`.

Issue 1544: norecursedirs build & dist dirs

---

_pytest/config.py

This fixes the bug inserted by accident in #1523
@RonnyPfannschmidt this is why your #1554 is failing on Windows... not sure how that passed the first time on `master`, as the logic for the `posix` argument was wrong. :confused:

Fix shell argument split in win32

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

this might need to go to features
also we might want to consider using a xfail marker with run=False instead of skip

fix #510 by adding a describing skip marker on empty parameterize

---

CHANGELOG.rst
_pytest/skipping.py
testing/test_skipping.py

Fix for https://github.com/pytest-dev/pytest/issues/1496 Xfail does not work with condition keyword argument.
We were only looking at `args`, despite [the docs saying](https://pytest.org/latest/skipping.html#xfail-signature-summary):
> Here’s the signature of the xfail marker, using Python 3 keyword-only arguments syntax:
> `def xfail(condition=None, *, reason=None, raises=None, run=True, strict=False):`

issue 1496 - xfail with condition keyword

---

CHANGELOG.rst
_pytest/python.py
testing/python/fixture.py

Hi 😄 
When inspecting available fixtures in a test suite via ``--fixtures`` and there are multiple fixtures with the same name, currently only one will be shown on stdout.
The reason for this is ``fixturedef = fixturedefs[-1]`` in the current implementation (last touched by @hpk42 in 37965657 from 2012), which discards all but the last fixture def for a fixture name. I am not sure about why this is - I might not understand all the implications.
If there are no objections, I'd like to iterate over all of the found fixture defs. Tox is green for me and I've added a new test to cover the desired behaviour.
Please let me know your thoughts! 🙇 
Raphael
----

Fix showfixtures for multiple fixturedefs

---

doc/en/writing_plugins.rst

Realized that after providing an answer in #1570

Remove "experimental" status from hookwrapper

---

CONTRIBUTING.rst
tox.ini

This will work for Travis and AppVeyor because both start tox using Python 3

Use same python which invoked tox for "doctesting" env

---

doc/en/example/simple.rst

https://pytest.org/latest/writing_plugins.html#_pytest.config.Config says config.option is deprecated and one should use config.getoption() instead.

Docs: config.option is deprecated

---

AUTHORS
CHANGELOG.rst
_pytest/_code/code.py
_pytest/main.py
testing/code/test_excinfo.py

This contains only a small fix for the bug mentioned in #1235, so it should go to master.

Fix cwd explosion

---

AUTHORS
CHANGELOG.rst
_pytest/main.py
testing/test_runner.py

When the method argument is missing on teardown_method, the traceback is
100% internal to pytest, which with default options get pruned. Then
that traceback is empty, leading to a new exception as a traceback shall
not be empty.
This PR fixes that issue by pushing back the last stack on the
traceback, when the stacktrace is empty after pruning. Then the output
is still pruned, but gives meaningful information with the item where it
failed on the stack.
* fixes issue #1604

Fixed issue shadowing error when missing argument on teardown_method

---

CHANGELOG.rst
_pytest/python.py
doc/en/example/costlysetup/conftest.py
doc/en/example/simple.rst
doc/en/fixture.rst
doc/en/yieldfixture.rst
testing/python/fixture.py

Did a quick experiment to see how hard would it be to implement #1461 to suggest working on it during the sprint... astonished to find out it was way too easy. :astonished: 
Just ignore the `yieldctx` parameter and decide on the spot if we are a "yield fixture" based on whether or not the function is a generator does the trick nicely.
Almost all of the changes are related only to change the tests of `yield_fixture` to also test with plain `fixture` to prove this is working.
Missing:
* Clean up the code (remove the need to pass `yieldctx` around);
* Update docs and CHANGELOG;
Opening the PR to discuss if we should move this forward or not. @RonnyPfannschmidt, @hpk42, @The-Compiler what you guys think?

Make normal fixtures work with "yield"

---

CHANGELOG.rst
_pytest/python.py
testing/python/show_fixtures_per_test.py

New cli flag ``--fixtures-per-test`` that shows which fixtures are being used for each selected test item. Features doc strings of fixtures by default. Can also show where fixtures are defined if combined with ``-v``.
This feature is going to help understand how pytest fixture injection works as to where it gets the fixtures from. Sometimes users get confused if a test suite contains a number of conftest.py files that define fixtures but also test modules which have their own. This gets particularly complex if fixtures share a name.
Example output for ``--fixtures-per-test -v``:
```text
-------- fixtures used by test_value_error_if_key_missing_in_context --------
--------------------- from tests/replay/test_dump.py:50 ---------------------
remove_replay_dump -- …
```

Show fixtures per test

---

AUTHORS
_pytest/main.py

The inner function and the explanatory comment it makes necessary can
all be removed if we switch to an if/else rather than try/except for
this condition.
Perhaps this bit comes from my fondness for C, but I think I would
find this style clearer and easier to understand even if it weren't
for the Python 2 quirk that makes the other style require us to add an
unnecessary-looking function abstraction.  In any case, given that the
alternative does require that abstraction this is definitely simpler.
-----
In the handy PR checklist:
> - [ ] Add yourself to `AUTHORS`
> - [ ] Add a new entry to the `CHANGELOG` (choose any open position to avoid merge conflicts with other PRs) 
I've skipped these as this small refactor isn't user-visible (so I imagine doesn't belong in `CHANGELOG`) and seems …

Simplify default pytest_runtestloop

---

testing/test_terminal.py

This appears to have been unused since commit
320835d "split out pytest-xdist related reporting to the plugin"
in July 2010.  It's the only caller outside of _pytest/runner.py
of the `call_and_report` helper function there, so cutting it out
makes that more of a pure helper function and makes it slightly
easier to understand the code in _pytest/runner.py .

Cut a dead test helper function

---

AUTHORS
CHANGELOG.rst
_pytest/main.py
testing/acceptance_test.py

This PR supersedes #1568 and addresses the problem highlighted in #1567 and in part #478.
See #1568 for the description of the test setup.
Unlike #1568, this PR does not attempt to emulate the import machinery to determine the filename of a  package or directory, delegating instead most of the work to the ``pkgutil`` module of the standard library.
**NB** In case of a non-top-level module or package, ``pkgutil.find_loader`` *will* import the parent package or packages.

Ensure that a module within a namespace package can be found by --pyargs

---

CHANGELOG.rst
_pytest/python.py
doc/en/assert.rst
testing/python/raises.py

This PR change pytest.raises to accept custom made message that will be raised if no exception was raised. For example:
```py
with pytest.raises(KeyError, message="I am expecting a KeyError to be raised"):
pass
Failed: I am expecting a KeyError to be raised
```
The use case behind this feature is as follows:
```py
for i in random.shuffle(["a", "b", "c"]):
with pytest.raises(KeyError):
if i == "b":
raise KeyError
```
As you can see in this example I can't know at which ``input`` I have failed from the result of the test. The new message will allow me to change the test as follows:
```py
for input in random.shuffle(["a", "b", "c"]):
with pytest.raises(KeyError, message="Key error was not raised for input {}".format(i)):
if input == "b":
raise KeyError
```
Now I can know the exact ``input`` …

Pytest.raises custom error message

---

_pytest/pytester.py

This should prevent errors from pyenv:
pyenv: python2.6: command not found
The `python2.6' command exists in these Python versions:
2.6.9
While the pyenv wrapper explicitly returns 127, I think it is better to
just check for non-zero?!

tests: getexecutable: call `--version` on all Pythons

---

AUTHORS
CHANGELOG.rst
_pytest/main.py
testing/acceptance_test.py
testing/test_collection.py
testing/test_doctest.py
testing/test_resultlog.py
testing/test_terminal.py

Exit pytest on collection error (without executing tests)

---

AUTHORS
CHANGELOG.rst
_pytest/assertion/__init__.py
_pytest/assertion/rewrite.py
testing/test_assertrewrite.py
testing/test_config.py

This change now makes rewrites assertions in `conftest.py` files so they can benefit from assertion rewriting. 
Fixes #1619
cc @flub @sober7

Issue 1619 conftest assert rewrite

---

testing/test_collection.py

`test_pytest_collect_file` fails if you run the tests using `--testmon`,
because pytest-testmon will put its DB there as `.testmondata`.

Ignore hidden files (.testmondata) in test_pytest_collect_file

---

_pytest/python.py

Trivial change discussed during the sprint to give the user the name, where the assertion fails.

help the user in the rare case this assertion actually fails

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/python/fixture.py

Fix for https://github.com/pytest-dev/pytest/issues/460
Raise helpful failure message, when requesting parametrized fixture at runtime, e.g. with ``request.getfuncargvalue``.
This now fails before getting to `AttributeError: 'SubRequest' object has no attribute 'param'`.
**BACKWARD INCOMPAT**: Previously these params were simply never defined. So a fixture decorated like `@pytest.fixture(params=[0, 1, 2])` only runs once. Now a failure is raised.

Issue 460: Fail on getfuncargvalue(<fixture with params>)

---

CHANGELOG.rst
_pytest/assertion/util.py
testing/test_assertion.py

Fix for https://github.com/pytest-dev/pytest/issues/1553
By default [Python's splitlines method](https://docs.python.org/2/library/stdtypes.html#str.splitlines) splits so "a terminal line break does not result in an extra line". This means that comparing strings that differ only in whether they contain a terminal newline, results in a bad diff.
This PR sets splitlines' `keepends=True`, which keeps all newlines when splitting.

Issue 1553: Include terminal newlines in diffs

---

AUTHORS
doc/en/cache.rst

The "Inspecting Cache content" section was showing --cache-clear command,
but should actually be using --cache-show command.
Also; update AUTHORS

cache.rst: Fix wrong command used

---

AUTHORS
CHANGELOG.rst
_pytest/config.py
testing/test_parseopt.py

``_pytest.config.OptionGroup.addoption()`` didn't care about adding the same options twice. Only ``argparse`` library was later complaining about the doubled options. That made it quite difficult to find the actual root cause of issue #1618, because you couldn't get any information from the exception traceback why the doubled option adding happened. Now you can track down such issues very easily.

added check for already existing option names to OptionGroup.addoption()

---

CHANGELOG.rst
_pytest/doctest.py
_pytest/python.py
doc/en/genapi.py
testing/code/test_excinfo.py
testing/python/fixture.py
testing/python/metafunc.py
testing/test_genscript.py
testing/test_pdb.py

Fix for https://github.com/pytest-dev/pytest/issues/1625
`getfuncargvalue` will be deprecated but will still be supported for the moment.

issue1625, rename getfuncargvalue to getfixturevalue

---

CHANGELOG.rst
_pytest/assertion/util.py
testing/test_assertrewrite.py

Always include full assertion explanation. The previous behaviour was hiding sub-expressions that happened to be False, assuming this was redundant information. Fixes #1503.
At first glance it may seem that the additional explanation is redundant, closer inspection demonstrates value in this detail. For an example see #1503 where the reporter covers their use case.

Fixes #1503 no longer collapse false explanations

---

_pytest/config.py
testing/test_config.py

This was added in b2d66b9 but is a bad idea. When a plugin can't be imported, commandline options (optionally set in pytest.ini) could be undefined, which means pytest bails out much earlier before showing the warning, which is hard to debug.
Fixes #1479, also see #1307 and #1497

Don't ignore ImportError when importing setuptools plugins

---

_pytest/config.py
testing/test_parseopt.py

I have came across this when noticing that universal-ctags fails to parse
this correctly (https://github.com/universal-ctags/ctags/issues/997).

Simplify Argument.__repr__

---

CHANGELOG.rst
_pytest/python.py
testing/test_junitxml.py
testing/test_resultlog.py
testing/test_runner.py
testing/test_session.py
testing/test_skipping.py
testing/test_terminal.py

I'll add the `CHANGELOG` and documentation once I get some feedback if this is correct.
This change effectively disables using `pytest.skip` at module level (even as a normal function not only as a decorator) because that is how I understand issue #607 .
@nicoddemus:
>> @nicoddemus @hpk should we issue a pytest_warning if pytest.skip happens outside of the runtestprotocol?
> Sounds good, but as we commented before, the current warnings system could use some improvements.
@nicoddemus:
> On second thought I think this should actually fail the collection of that module.
This earlier comment by @hpk42 is also an option:
> What about making pytest.skip fail when a function object is passed and point to "pytest.mark.skipif" and the docs?
I tried checking the type of the `msg` parameter in …

Raise CollectError if pytest.skip() is called during collection

---

AUTHORS
CHANGELOG.rst
_pytest/config.py
_pytest/helpconfig.py
testing/test_config.py

support for "--overwrite-ini ININAME=INIVALUE" to overrides ini values from the command line
so that one can do e.g. "-o xfail_strict=True".

Add --overwrite-ini ININAME=INIVALUE cli option

---

CHANGELOG.rst
setup.py

These entry points were not documented, so no doc changes are necessary.

Remove all py.test-X* entry points.

---

CHANGELOG.rst
_pytest/assertion/rewrite.py
testing/test_assertion.py

This PR adds a warning for assertions on tuples. The warning is issued by the assertion rewriter, as suggested by @RonnyPfannschmidt, so it will only be shown if the asserts are being rewritten (which is the default in most cases).
Checklist:

Add warning for assertions on tuples #1562

---

CHANGELOG.rst
_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

Tries put subexpression into brackets. Checks in the assertion rewriting in one operator is a expression itself and put it in brackets
Fixes #925

Improve of the test output for logical expression with brackets.

---

testing/test_mark.py

xfailing test for #568

---

doc/en/usage.rst

Target: master
Even though catch is a Python keyword, 'catched' just looks terrible in text.
If the text was supposed to reference the keyword, then 'catched' should be changed to "'catch'ed".

catched -> caught

---

CHANGELOG.rst
README.rst
doc/en/index.rst
setup.py
testing/code/test_source.py

drop python 3.0-3.2 support code from setup.py

---

doc/en/new-docs/user/parametrize.rst

Making the suggested change from https://github.com/pytest-dev/pytest/pull/1646#discussion_r68103355.

Correctly reference values from the example in parametrize docs

---

appveyor.yml
tox.ini

Some of our builds have been timing out (over 1 hour) on AppVeyor

Split AppVeyor test runs in multiple jobs to avoid timeout issues

---

doc/en/talks.rst

- Fixed some of the links which were broken
- Removed some of the links which didn't work anymore and I couldn't find them on google
Fix #1696

Fix links and removed 404 links from talks.rst

---

CHANGELOG.rst

- Merged 3.0 and 2.10 as much stuff from the sprint went to the 2.10
section.
- Cleaned up mixture of link/text blocks
- Moved some entries to "Bug Fixes" and "Incompatible changes"
- Stop doing "Fixes (#123) ..." because it looks weird
- Add some new empty points for all sections

Clean up changelog

---

CHANGELOG.rst
_pytest/assertion/__init__.py
_pytest/fixtures.py
_pytest/monkeypatch.py
_pytest/pytester.py
_pytest/python.py
_pytest/tmpdir.py
testing/acceptance_test.py
testing/code/test_excinfo.py
testing/code/test_source.py
testing/python/collect.py
testing/python/fixture.py
testing/python/integration.py
testing/python/metafunc.py
testing/test_assertion.py
testing/test_junitxml.py
testing/test_mark.py
testing/test_monkeypatch.py
testing/test_pdb.py
testing/test_runner.py
testing/test_runner_xunit.py
testing/test_skipping.py
testing/test_terminal.py
testing/test_unittest.py

Deprecating both `yield tests` and `pytest_funcarg__` prefix for declaring fixtures.
* Added deprecation warnings when one of the features is used;
* Removed `pytest_funcarg__` and `yield tests`  usages from core;
Closes #16
Closes #1324
Fixes #1684

Deprecate yield tests funcarg prefix

---

AUTHORS
CHANGELOG.rst
_pytest/debugging.py
testing/test_pdb.py

This obviates the need for plugins such as `pytest-ipdb`; instead one can simply call `py.test --pdbcls=IPython.core.debugger:Pdb`
A test is missing, advice as to how to best implement one would be appreciated.

Allow passing a custom Pdb subclass via --pdbcls.

---

CHANGELOG.rst

Tried to improve overall consistency and formatting of the CHANGELOG for 3.0. Suggestions are welcome!
Rules I tried to follow:
* Use past or imperative tense ("removed", "add");
* Reference issue ids at the end of the item;
* Finish all items with `.`;

Improve overall CHANGELOG formatting and consistency for 3.0

---

_pytest/fixtures.py

This is targeted for "features", since the code is not in master yet.

Add punctuation to funcarg_prefix_warning

---

_pytest/fixtures.py
testing/acceptance_test.py

Followup to https://github.com/pytest-dev/pytest/pull/1718.

funcarg_prefix_warning: remove newline

---

CHANGELOG.rst
_pytest/config.py
testing/acceptance_test.py

Deprecate support for passing command-line as string to pytest.main()

---

testing/acceptance_test.py

This attempts to fix CI which broke because of this test.
Other warnings introduced in the future could break
this test.

Make assert in test_str_args_deprecated more resilient

---

CHANGELOG.rst
_pytest/python.py
doc/en/xunit_setup.rst
testing/test_runner.py
testing/test_runner_xunit.py

setup_module, setup_function and setup_method extra argument are now optional and may be omitted.
Fix #1728

setup_* and teardown_* functions argument now optional

---

doc/en/backwards-compatibility.rst
doc/en/contents.rst

There is no open issue for this but it is part of the [plan for the 3.0 release](https://github.com/pytest-dev/pytest/wiki/pytest-3.0-checklist). 
Together with the introduction of showing internal deprecation warnings by default and the possibility to explicitly silence them it completes the plan for having a transparent way of dealing with backwards incompatible changes.

Add backwards compatibility docs

---

CHANGELOG.rst
_pytest/config.py

also documents the implementation quality
fixes #457

optparse compatibility - add float and complex

---

CHANGELOG.rst
_pytest/main.py
testing/test_session.py

by implementing `--exitfirst` in terms of a `store_const`
we gain the ability to let a following `--maxfail=N` override it

allow --exitfirst/-x to be overridden by a following --maxfail

---

AUTHORS
CHANGELOG.rst
_pytest/config.py
testing/test_conftest.py

We had problems at the office debugging a conftest error, so I am submitting this patch to close #1516

Making conftest import failures easier to debug

---

AUTHORS
CHANGELOG.rst
_pytest/doctest.py
doc/en/doctest.rst
testing/test_doctest.py

Here is a first pull request, as it is my first contribution, I may have done incorrect things according to pytest standards, please let me know whatever I should do more or differently.

Doctest report format option (#1749)

---

AUTHORS
testing/python/fixture.py

I wasn't able to replicate the problem with the current master and the latest version (2.9.2). The test case was not present though so I created one.
pytest will raise a ValueError "Duplicate '<fixture_name>'" when overriding an autouse fixture w/ a parametrized fixture in a subdirectory's conftest.py
The related issue is #1601 
Cheers

Testcase for overriding autouse fixture with a parametrized fixture.

---

CHANGELOG.rst
_pytest/helpconfig.py
testing/python/fixture.py
testing/test_config.py

Should be minor.
I've used it as a test field for fixes to https://github.com/hynek/vim-python-pep8-indent a while back already.

Followup to #1718: style/formatting

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

Improved message when not using parametrized variable

---

AUTHORS
CHANGELOG.rst
_pytest/main.py
testing/test_runner.py

Fix for https://github.com/pytest-dev/pytest/issues/1210
Previously, calls to `pytest.exit(msg)` during startup, for example in `pytest_configure` swallowed the `msg`. Now it gets printed to stderr.

Fix #1210 display msg for early calls to exit

---

CHANGELOG.rst
_pytest/main.py

Consider this my after-the-fact review for #1763 :wink:
cc @tomviner @JonathonSonesen

Cleanups for #1763

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/python/collect.py

Fixed collection of classes with custom ``__new__`` method. Fixes #1579.

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/acceptance_test.py
testing/test_capture.py

Add an 'E' to the first line of error messages from FixtureLookupErrorRepr.
Fixes #717.

Start first line of FixtureLookupErrorRepr messages with an 'E'

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

Hello, this is my initial approach to solve #634
I'm not very familiar with pytest codebase, so I'll appreciate any help here.
Thank you
P.S. Also #684 #661 #896 #531 are probably related to this issue

Fixed scope override inside metafunc.parametrize. Fixes #634

---

AUTHORS
CHANGELOG.rst
_pytest/config.py
_pytest/main.py
doc/en/example/pythoncollection.rst
testing/python/collect.py
testing/python/metafunc.py

When using `pytest --skip-duplicates`:
- ignores duplicate tests on the basis of the `purebasename`;
- take into account only the first one;

Drop duplicated tests by default #1609

---

README.rst
doc/en/contents.rst
doc/en/getting-started.rst
doc/en/index.rst

Fix pdf links in docs and point to docs.pytest.org in README

---

CHANGELOG.rst

I sorted the link references when merging `master` into `features`, so I'm doing the same for the current `master`.
I think we could start asking people to add those link references always sorted, what you guys think?

Sort link refs in CHANGELOG

---

AUTHORS
CHANGELOG.rst
_pytest/_code/code.py
testing/code/test_excinfo.py

Highlight the path of file location in error report

---

_pytest/python.py
testing/python/fixture.py

While [running regedocs for pytest 3.0 earlier today](https://github.com/pytest-dev/pytest/pull/1780) I noticed that invocation scoped fixtures appear more than once with `--fixtures`.

invocation-scoped fixtures show up once with --fixtures

---

CHANGELOG.rst
_pytest/terminal.py
testing/test_terminal.py

this addresses #1372 - we pretend we know the deselection reason from internal plugins and ignore 3rd party/local reasons

terminal: dont pretend to know the deselection reason

---

CHANGELOG.rst
_pytest/fixtures.py
testing/python/fixture.py

Another small issue uncovered when running `regendoc`. :grin:

Sort fixture names when a fixture lookup error occurs

---

_pytest/assertion/__init__.py
_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

I investigated this some more and found the problem:
The assertion-rewrite hook is installed very early on, during the construction of the `Config` object. After installing the hook and still during `Config`'s construction, plugins and `conftest` files are also imported and are rewritten if `AssertionRewriteHook._should_rewrite` returns `True`. 
Now the problem with the example posted in #1784 is that it imports `test_foocompare` at the top-level of the `conftest.py` file which is loaded very early, when the `session` object has not even been created yet (much less set on the hook), so it doesn't try to rewrite that module.
Looking at the code I noticed that the code block that should handle this, the `for pat in self.fnpaths` loop, doesn't really depend on `self.session` at all except …

Rewrite asserts in test-modules loaded very early in the startup

---

_pytest/config.py
doc/en/customize.rst
testing/test_collection.py
testing/test_config.py

Fix determining rootdir from common_ancestor

---

_pytest/junitxml.py
_pytest/python.py
_pytest/runner.py
doc/en/writing_plugins.rst
testing/python/collect.py
testing/test_runner.py

Fixes related to #1790:
* Add `longreprtext `, `capstdout` and `capstderr` attributes to `TestReport`
* Add `originalname` attribute to Function
* Improve `TestReport.sections` docs
One issue which I could not figure out a good solution was about `xfail`, because the report object is decorated by the `skipping` plugin, which extends the terminal with this logic:
```python
def pytest_report_teststatus(report):
if hasattr(report, "wasxfail"):
if report.skipped:
return "xfailed", "x", "xfail"
elif report.failed:
return "xpassed", "X", ("XPASS", {'yellow': True})
```
Suggestions on how to improve this are welcome.
cc @fabioz

Internal adjustments for easier integration with IDEs

---

_pytest/hookspec.py
_pytest/terminal.py
testing/test_terminal.py

This is useful to know if a testrun has been interrupted
(EXIT_INTERRUPTED).

Pass exitstatus to pytest_terminal_summary hook

---

CHANGELOG.rst
_pytest/python.py
testing/python/fixture.py

Fixes https://github.com/pytest-dev/pytest/issues/717.
Follow-up to https://github.com/pytest-dev/pytest/pull/1762.

Improve display of continuation lines with multiline errors

---

CHANGELOG.rst
_pytest/main.py
testing/test_config.py

The line numbers in `node.location` seem to be zero-based?!

Fix off-by-one error with lines from request.node.warn

---

CHANGELOG.rst
_pytest/deprecated.py
_pytest/resultlog.py
doc/en/usage.rst
testing/deprecated_test.py

Deprecate --resultlog cmdline option

---

CHANGELOG.rst
_pytest/config.py
_pytest/deprecated.py
_pytest/helpconfig.py
doc/en/customize.rst
doc/en/example/pythoncollection.rst
doc/en/goodpractices.rst
doc/en/xdist.rst
testing/deprecated_test.py
testing/test_config.py

Also deprecate `[pytest]` usage in `setup.cfg` files
Fix #567

Support [tool:pytest] in setup.cfg files

---

tox.ini

Not sure why this is turned off, works on my computer.

Enable py35-trial testenv on Windows

---

CHANGELOG.rst
_pytest/skipping.py
testing/python/metafunc.py
testing/test_config.py
testing/test_junitxml.py
testing/test_skipping.py
testing/test_unittest.py

I am not entirely sure if this is the right way to do it.
This is very much **WIP** as the tests will be failing.
Can anybody help me out with this one, please 😃 
Resolves #1546

WIP Change outcome to 'passed' for xfail unless it's strict

---

CHANGELOG.rst

Those are both already mentioned in the breaking changes at the top.
@nicoddemus can we get this into 3.0 please? :wink:

Remove duplicate CHANGELOG messages

---

AUTHORS
CHANGELOG.rst
doc/en/customize.rst

This covers issue #1435: if ``args`` is not explicitly given, custom pytest commandline arguments are misleading pytest's rootdir discovery, if they point to an existing file/folder.
Target: `master` (as an addition to PR #1621 )

Documentation update for rootdir discovery

---

CHANGELOG.rst
_pytest/python.py
_pytest/runner.py
testing/test_runner.py

Fix regression when using importorskip at module level

---

CHANGELOG.rst
_pytest/python.py
doc/en/announce/release-2.6.3.rst
testing/test_skipping.py

Ref: http://idioms.thefreedictionary.com/outside+of

Fix spelling: s/outside a/outside of a/

---

AUTHORS
CHANGELOG.rst
_pytest/main.py
testing/acceptance_test.py

Importer loader error 

---

doc/en/example/layout1/setup.cfg

Noticed it's not using the new `[tool:pytest]` header as changed in #567, can't find any reference to it or `testfilepatterns`. It was added in b1e430145706556cc676e7cbe49d625b7540088e 6 years ago, there don't seem to have ever been references to it.

Delete unreferenced setup.cfg from docs

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

Many thanks to @Kingdread for providing the initial solution; I just added a few more tests and refactored the code a little bit.
Fix #1832

Fix code which guesses parametrized scope based on arguments

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

Fix internal error when parametrizing using and empty list of ids()

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

Improve error message when passing non-string ids to pytest.mark.parametrize

---

AUTHORS
CHANGELOG.rst
_pytest/capture.py
testing/test_capture.py

Python 3 added a `buffer` attribute to `sys.stdin`. Simply accessing this attribute doesn't imply the program has read from `stdin`, as such this attribute should behave similarly to the stubbed input presently. This PR will add this property and return `self` such that attempting to read the buffer will raise exceptions the same as had you read from `stdin`.

Add buffer attribute to DontReadFromInput

---

AUTHORS
CHANGELOG.rst
_pytest/_code/code.py
testing/test_assertion.py

- [v] Target: for bug or doc fixes, target `master`; for new features, target `features`;
- [v] Make sure to include one or more tests for your change;
- [v] Add yourself to `AUTHORS`;
- [v] Add a new entry to `CHANGELOG.rst`
* The pytest team likes to have people to acknowledged in the `CHANGELOG`, so please add a thank note to yourself ("Thanks @user for the PR") and a link to your GitHub profile. It may sound weird thanking yourself, but otherwise a maintainer would have to do it manually before or after merging instead of just …

Fix UnicodeEncodeError when string comparison with unicode has failed.

---

doc/en/monkeypatch.rst

This is a leftover when invocation-scoped fixtures were pulled back.
Fix #1872

Remove example of "monkeypatch" used in session scope

---

_pytest/debugging.py

I really like the pytest 3.0 command line option`--pdb --pdbcls=IPython.core.debugger:Pdb`, which directly allows to drop into the IPython debugger. That's great news!
I tried that with IPython 5.1 and it works fine, however tab completion is deactivated. Using the command line option `--pdb --pdbcls=IPython.terminal.debugger:TerminalPdb` will also activate tab completion.

pdbcls ipython example with tab completion

---

CHANGELOG.rst
_pytest/assertion/__init__.py
_pytest/config.py
testing/test_assertion.py

Unfortunately due to a small bug on how the `pytest_plugins` variable was handled, we are currently rewriting assertions in much more modules than we initially thought:
```python
pytest_plugins = 'setuptools.tests.fixtures'
```
The code that handles that in `config.py` was expecting `pytest_plugins` to be a `list[str]` only:
```python
def consider_module(self, mod):
plugins = getattr(mod, 'pytest_plugins', [])
self.rewrite_hook.mark_rewrite(*plugins)
self._import_plugin_specs(plugins)
```
So it would end up marking each letter in `"setuptools.tests.fixtures"` as an individual module, which basically means rewriting every module which starts with `s`, `e`, `t`, `u` and so on. 
Coupling that with some advanced bootstrapping done in `setuptools` between each test and a lot of tests were …

Fix issue pytest_plugins as string was marking wrong modules for rewrite

---

AUTHORS
CHANGELOG.rst
_pytest/unittest.py
doc/en/unittest.rst
testing/test_pdb.py

Assuming pytest is used to run a GUI test unittest suite. Typically GUI tests close the GUI in the unittest tearDowns or cleanup methods.
These tests cannot be easily post mortem debugged (`pytest --pdb`), as unittests tearDown and cleanup (which close the GUI) are called on an exception before the post mortem debugger jumps into place. Therefore, the GUI is closed and no direct interaction is possible any more.
A work around when running the unittest via the unittest runner is to add the following line to ~/.pdbrc: `!import unittest; unittest.TestCase.run = lambda self,*args,**kw: unittest.TestCase.debug(self)`, start the tests with `python -m pdb test.py` and hit continue.
This pull request accomplishes the same within the pytest unittest compatibility layer. It is solely activated if …

unittest runner: avoid tearDown and cleanup to ease post mortem debugging

---

HOWTORELEASE.rst

As discussed recently on the testing-in-python mailing list, people have asked 
to restrict the amount of announcements there only to major/minor 
pytest releases

Send only minor/major release announces to TIP mailing list

---

_pytest/mark.py

Should be 
> Example: -k 'test_method or test_other' matches all test functions and classes whose name contains 'test_method' or 'test_other'. "

Fix keyword docs

---

CHANGELOG.rst

It helps mentioning this explicitly in the changelog.
Fixes #1871.

Mention register_assert_rewrite explicitly

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

The "ids" argument to "parametrize" again accepts unicode strings in Python 2

---

_pytest/assertion/util.py
_pytest/python.py
testing/python/raises.py

We used to have this when we where patching the real Python
AssertionError for use with reinterpret, but reinterpret is now
gone so we no longer need this as it is not used by rewrite.
This was never public so I don't believe this needs a changelog mention.

Remove BuiltinAssertionError

---

doc/en/_templates/links.html

Fix link to PDF docs

---

CHANGELOG.rst
_pytest/config.py
testing/test_assertion.py

Fixed assertion rewriting for plugins in development mode

---

AUTHORS
CHANGELOG.rst
_pytest/config.py

Pkg resources bugfix

---

_pytest/compat.py
_pytest/main.py
_pytest/mark.py
_pytest/skipping.py
testing/test_mark.py

this pr makes the internals of markers a more consistent structure to use as a base for future enhancements
currently the new mark type is not exposed,
but it is a intent to remove usages of MarkInfo/MarkDecorator in favor of Mark objects and potentially collections/views over them later on

use consistent inner repressentation for marks

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/test_assertion.py

AttributeError chaining bug #1944 fix

---

_pytest/_code/code.py
_pytest/_code/source.py
_pytest/assertion/util.py
_pytest/python.py

I am investigating a migration to Python 3, and to facilitate this we are using the -3 flag as decribed here:
https://docs.python.org/3/howto/pyporting.html#prevent-compatibility-regressions . When using this flag.  
Running through some of my tests with the `-3` flag in python2.7 however I encountered some errors within py.test itself.  This fixes those errors so we can use py.test in order to identify problems with our code as we transition to Python 3.

Fix `DeprecationWarnings` found when running py.test in Python 2.7 with the -3 flag.

---

_pytest/_code/source.py

`__getslice__` has been Deprecated since Python 2.0 and is removed in Python 3.  See
https://docs.python.org/2/reference/datamodel.html#object.__getslice__
Unfortunately, Python 2 will still dispatch to `__getslice__` over `__getitem__`, See
http://bugs.python.org/issue2041, which causes Warnings when running with `-3` in 2.7.

Remove implementation of `__getslice__`

---

_pytest/debugging.py
testing/test_pdb.py

fixes #1948 
i tried to add a final test for using `pdb.set_trace()`, but couldn't get it to work. any advice appreciated
```python
def test_pdb_custom_cls_with_settrace(self, testdir, custom_pdb_calls):
testdir.makepyfile(custom_pdb="""
class CustomPdb:
def __init__(self, *args, **kwargs):
called.append("init")
def reset(self):
called.append("reset")
def interaction(self, *args):
called.append("interaction")
""")
p1 = testdir.makepyfile("""
import pytest
def test_foo():
pytest.set_trace()
""")
child = testdir.spawn_pytest("--pdbcls=custom_pdb:CustomPdb %s" % str(p1))
child.expect("interaction")
child.send('c\n')
child.sendeof()
if child.isalive():
child.wait()
assert custom_pdb_calls == ["init", "reset", "interaction"]
```

Pdbcls without pdb on fail

---

tox.ini

Related to HypothesisWorks/hypothesis-python#368

Pin hypothesis to 3.5.0 because 3.5.1 breaks the test suite

---

_pytest/helpconfig.py

Fix for https://github.com/pytest-dev/pytest/issues/1981

Fix #1981, improve ini-options help text

---

doc/en/monkeypatch.rst

Add note about not monkey-patching builtins

---

.github/PULL_REQUEST_TEMPLATE.md

I think because we have a checklist in place folks might think it necessary to add CHANGELOG entries for simple doc fixes.

Mention small doc fixes don't need tests/changelog entries in PR template

---

CHANGELOG.rst
_pytest/python.py
testing/acceptance_test.py
testing/python/collect.py
testing/test_collection.py
testing/test_terminal.py

Fixes #1976.
Here's the output:
**master**
```
______________________ ERROR collecting .tmp/test_foo.py ______________________
ImportError while importing test module 'C:\pytest\.tmp\test_foo.py'.
Original error message:
'cannot import name 'non_existing''
Make sure your test modules/packages have valid Python names.
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
```
**this PR**
```
______________________ ERROR collecting .tmp/test_foo.py ______________________
ImportError while importing test module 'C:\pytest\.tmp\test_foo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_foo.py:1: in <module>
import foo
foo.py:1: in <module>
from bar import non_existing
E   ImportError: cannot import name 'non_existing' …
```

Show traceback during collection

---

CHANGELOG.rst
_pytest/compat.py
_pytest/config.py
testing/test_pluginmanager.py

Handle import errors with non-ascii messages when importing plugins

---

doc/en/usage.rst

string args got deprecated due to the insane amount of edge-cases wrt splitting on windows vs posix

docs: remove mention of string args to main

---

doc/en/goodpractices.rst

Related to [this comment](https://github.com/pytest-dev/pytest/issues/1723#issuecomment-254855795).

Remove example of obsolete pytest.main usage with string

---

.travis.yml

Better disable `py35-trial` temporarily than to keep marking PRs as failed. ☹️

Disable py35-trial while #1989 is not fixed

---

CHANGELOG.rst
_pytest/config.py
testing/test_parseopt.py

While fixing this I noticed pytest's own `--override-ini` help is wrong:
```
-o [OVERRIDE_INI [OVERRIDE_INI ...]], --override-ini=[OVERRIDE_INI=[OVERRIDE_INI=...]]
``` 
With this PR:
```
-o [OVERRIDE_INI [OVERRIDE_INI ...]], --override-ini=[OVERRIDE_INI [OVERRIDE_INI ...]]
```
Fix #2004

Fix cmdline help message for custom options with two or more metavars

---

_pytest/pytester.py
testing/test_pdb.py

This series of patches makes pexpect tests viable on macOS. After applying the patches, here's the output of a test run (apparently confirming the report in #985).
```
$ python -m tox -e py35-pexpect                                         
GLOB sdist-make: /Users/jaraco/Dropbox/code/public/pytest/setup.py
py35-pexpect create: /Users/jaraco/Dropbox/code/public/pytest/.tox/py35-pexpect
py35-pexpect installdeps: pexpect
py35-pexpect inst: /Users/jaraco/Dropbox/code/public/pytest/.tox/dist/pytest-3.0.4.dev0.zip
py35-pexpect installed: pexpect==4.2.1,ptyprocess==0.5.1,py==1.4.31,pytest==3.0.4.dev0
py35-pexpect runtests: PYTHONHASHSEED='369771295'
py35-pexpect runtests: commands[0] | pytest -rfsxX test_pdb.py test_terminal.py test_unittest.py
=========================================== test …
```

Restore pexpect tests on macOS. Fixes #2022.

---

_pytest/python.py
_pytest/recwarn.py
appveyor.yml
tox.ini

* Fix doctests
* List one env per line in tox.ini
* "doctesting" tox env now also tests docstrings using doctest

Re-enable docstring testing of _pytest modules on CI

---

CHANGELOG.rst
_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

It would be great if @flub could review this. 😁 
Fix #2005

Fix false-positive warnings from assertion rewrite hook

---

AUTHORS
CHANGELOG.rst
_pytest/capture.py

Hello,
I suggest changing the exception raise by `capture.DontReadFromInput.fileno()` from `ValueError` to `io. UnsupportedOperation` which derives from both `ValueError` and `OSError`. In this way the method confirms with `IOBase.fileno()` that should raise an `OSError` if there is no file descriptor while maintaining backward compatibility. 
Best regards,
Vlad

Change exception raised by capture.DontReadFromInput.fileno()

---

AUTHORS
CHANGELOG.rst
_pytest/terminal.py
testing/test_terminal.py

Until now, teardown stdout/stderr output was not reported upon test failure.
However such output is sometime necessary to understand the failure.
fix #442

Report teardown output on test failure

---

CHANGELOG.rst
_pytest/recwarn.py
doc/en/recwarn.rst
testing/test_recwarn.py

turn RecordedWarning into a namedtuple

---

CHANGELOG.rst
_pytest/junitxml.py
testing/test_junitxml.py

* The pytest team likes to have people to acknowledged in the `CHANGELOG`, so please add a thank note to yourself ("Thanks @user for the PR") and a link to your GitHub profile. It may sound weird thanking yourself, but otherwise a maintainer would have to do it manually before or after merging instead of just using GitHub's merge button. This makes it easier on the maintainers to merge PRs. 
It was "test setup failure" even error …

Fix teardown error message in generated xUnit XML

---

CHANGELOG.rst
_pytest/_code/code.py
testing/code/test_excinfo.py
testing/test_assertion.py

Properly handle exceptions in multiprocessing tasks

---

AUTHORS
CHANGELOG.rst
_pytest/unittest.py
testing/test_unittest.py

Fix [#1649](https://github.com/pytest-dev/pytest/issues/1649)
Users of unittest style TestCases will create expensive objects
in setUp. We should clean up TestCase instances that are lying
around so that they don't fill up memory.

Clean up unittest TestCase objects after tests are complete (#1649).

---

AUTHORS
CHANGELOG.rst
_pytest/_code/code.py
_pytest/python.py
testing/python/raises.py

Checklist:
This fixes the memory leak locally (#1965) but I had a lot of problems when running the tests. I hope I don't waste too much of your CI ressources if I use the PR to run the tests.

Fix memory leak with pytest.raises by using weakref

---

README.rst
tox.ini

While adding the same check for tox I realized we don't do the same for pytest.

Check README.rst with rst-lint

---

.travis.yml
appveyor.yml

Instead of commenting out jobs, allow them to fail in CI. 
This seems like a better strategy because at least they will appear in the job list, as a constant reminder for us to take a look or even better, start to get green again because of an upstream change.
Related to #1989 and #1963

Allow problematic jobs to fail instead of commenting them out

---

MANIFEST.in
scripts/check-manifest.py
tox.ini

Wrapper script is necessary because we are not under version when testing the package directly using `devpi test`.
Related to comment in #2051

Use a wrapper script to bypass check-manifest if not under git

---

MANIFEST.in
appveyor.yml
scripts/install-pypy.bat

Some time ago when we first added support for testing pytest on AppVeyor,
jobs in a build would not start immediately one after the other, as if AppVeyor
would schedule jobs from other builds (projects) in its VMs. So it made sense
at the time to reduce the number of jobs.
I have noticed in other projects that this behavior has changed, and jobs
in a build now start one after the other. Having a separate list then improves
visibility when the build fails, because we can see at a glance the failing(s)
tox environment(s).

Use one job for each tox env on AppVeyor

---

doc/en/talks.rst

Hi,
Talks section extended with my latest overview talk on pytest. 
This one is in Russian. Formatted after Holger's talk in German.

Docs: Added pytest promotional talk in Russian

---

_pytest/assertion/__init__.py
_pytest/assertion/truncate.py
testing/test_assertion.py

This addresses ref https://github.com/pytest-dev/pytest/issues/1954.
The current truncation logic for assertion explanations does not deal with long lines
properly:
- Previously if lines were too long it would display a "-n more lines"
message.
- 999e7c65417f1e97fc89bf66e0da4c5cd84442ec introduced a bug where long lines can
cause index errors if there are < 10 lines.
Extract the truncation logic into its own file and ensure it can deal with
long lines properly.

Restructure truncation of assertion messages

---

AUTHORS
CHANGELOG.rst
_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

Don't fail if imp can't find the source for a .pyc file. #2038

---

appveyor.yml
scripts/call-tox.bat

Just noticed that the "coveralls" env was being execute after each env, making builds for pytest's own branches take unnecessarily long.
This was introduced by mistake in #2056

Only execute "coveralls" toxenv once on AppVeyor

---

tox.ini

Related to pypa/setuptools#861
Remove the pin when we have a new setuptools release

Pin setuptools to < 29 because of AppVeyor failures

---

AUTHORS
CHANGELOG.rst
_pytest/main.py

- [ master ] Target: for bug or doc fixes, target `master`; for new features, target `features`;
Tried  to resolve 3 way merge (with help) but it kept recurring, subsequently accidentally closed previous pull request in process of trying to resolve.
Same as [Pull #2081 ](https://github.com/pytest-dev/pytest/pull/2081)

Add hint of Issue #478 to error text

---

doc/en/goodpractices.rst

Clarify test discovery docs.

---

AUTHORS
CHANGELOG.rst
doc/en/recwarn.rst

Closes https://github.com/pytest-dev/pytest/issues/297.
[Greetings from Zagreb!](https://www.meetup.com/Python-Hrvatska/events/235507740/)

Add `:ref:` targets to `recwarn.rst`.

---

CONTRIBUTING.rst

Add documentation building note.

---

testing/test_junitxml.py

Something to move the conversation on #595 along.
@davidszotten said in #595:
> 6954363 changed junitxml to include captured output for passing and skipped tests in the output by default.
So far as I can tell, my test shows that the output of a skipped test is not captured by default.
Is this already fixed or I missed something?

Add test case for #595.

---

AUTHORS
CHANGELOG.rst
_pytest/main.py

Issue 2034

---

CHANGELOG.rst
_pytest/config.py
_pytest/junitxml.py
_pytest/main.py
testing/test_junitxml.py

Changes to add to the conversation in https://github.com/pytest-dev/pytest/issues/2089.
Something which may not be acceptable is the reduced specificity of the error messages. For example, the validation function `filename` can't refer to `--junit-xml` in the error message.
Let me know what you think @nicoddemus.

Add `type` validation.

---

CHANGELOG.rst
_pytest/compat.py
_pytest/python.py
testing/test_collection.py

Closes #2007.
Not sure if the test is in the right place?

Add missing `__test__` check for discovery

---

AUTHORS
CHANGELOG.rst
_pytest/doctest.py
_pytest/pytester.py
doc/en/doctest.rst
testing/test_doctest.py

I added a command line option to specify the encoding of doctest (*.txt/*.rst) files.
This should fix the error described in #540 which I am also having on my windows machine.

Added doctest encoding command line option

---

CHANGELOG.rst
_pytest/_code/source.py

This code leaves `None` in sys.modules as a side effect but is no longer needed in the Python 3 versions we support, it seems.
Fix #2103

Remove support code for earlier Python 3 version in Source.compile

---

CHANGELOG.rst
_pytest/config.py
_pytest/helpconfig.py
testing/test_config.py

Add warning for incorrect passing args to `-o`.

---

CHANGELOG.rst
_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

pytest would emit false-positive warnings about assertion-rewrite when a module appears multiple times in plugins which depend on other plugins using the `pytest_plugins` mechanism.
Here's the output of the test added by this PR on `master`:
```
self = <test_assertrewrite.TestRewriteOnImport instance at 0x000000000430A208>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch instance at 0x000000000401FF88>
def test_rewrite_warning_using_pytest_plugins(self, testdir, monkeypatch):
testdir.makepyfile(**{
'conftest.py': "pytest_plugins = ['core', 'gui', 'sci']",
'core.py': "",
'gui.py': "pytest_plugins = ['core', 'sci']",
'sci.py': "pytest_plugins = ['core']",
'test_rewrite_warning_pytest_plugins.py': "def test(): pass",
})
testdir.chdir()
result = testdir.runpytest_subprocess()
> …
```

Fix false-positive assert rewrite warnings when using 'pytest_plugins'

---

CHANGELOG.rst
_pytest/main.py
_pytest/pytester.py
testing/test_conftest.py
testing/test_pluginmanager.py

Fixes #2016 
@hpk42 I would appreciate if you could take a look as you probably know the most about that part of the code. [This comment](https://github.com/pytest-dev/pytest/issues/2016#issuecomment-261940763) contains the full description of my diagnosis of the problem.
cc @d-b-w

Remove hook proxy cache 

---

CHANGELOG.rst
_pytest/python.py
testing/python/approx.py

Use a simple ``+-`` ASCII string in the string representation of pytest.approx In Python 2

---

CHANGELOG.rst

Used [this Gist](https://gist.github.com/nicoddemus/8fd168e1e6897864d8f22a9340709a7a) in case others want to use it.
Fix #721

Add release dates to CHANGELOG entries

---

AUTHORS
CHANGELOG.rst
_pytest/recwarn.py
testing/test_recwarn.py

The error message contains the expected type of warning and the
warnings that were captured. Add tests.
You could argue that having the stderr is good enough but in my original use case, either the stderr was very noisy or I managed to miss it completely. I reckon it does not hurt to have a clearer error message anyway.
The line of the error message is very long now. Let me know if you would rather have me split it manually or you have better ways to deal with it.
Simple snippet:
```py
import warnings
import pytest
def test():
with pytest.warns(RuntimeWarning):
warnings.warn('user', UserWarning)
warnings.warn('import', ImportWarning)
```
master:
```
======================================================== test session starts ======================================================== …
```

Improve error message when pytest.warns fail

---

.travis.yml
appveyor.yml

While I agree this is *far* from ideal, IMHO It is better to ignore them for now otherwise we hamper contributors with unrelated errors.
We should fix this before the next release.
Related to #1989

Allow trial environments to fail on CI for now

---

setup.py

Setuptools is used in `_pytest/config.py` but was not explicitly listed as requirement. This led to an error when creating a Conda package for pytest since setuptools is not necessarily installed by default in Conda envs.

Explicitly add setuptools to install_requires

---

.travis.yml
_pytest/compat.py
testing/test_doctest.py
tox.ini

This tests originally checked for ImportError. Since Python 3.6
ModuleNotFoundError is raised in this context instead, the test didn't work
as it is text based (so exception inheritance does not save the day).
The test now simply checks for any *Error, which makes it less specific,
but still valuable.
Fixes https://github.com/pytest-dev/pytest/issues/2132
I consider this a trivial fix (I realize it's not in documentation, but it's in tests, so I think the same logic applies).

Tests: Check for ModuleNotFoundError on Python 3.6+

---

doc/en/fixture.rst
doc/en/goodpractices.rst
doc/en/writing_plugins.rst

Fixes three broken links in the docs (one is just a broken anchor on Wikipedia, but still)
Cheers, and thanks for the tool!

Fix broken links

---

CHANGELOG.rst
_pytest/python.py
testing/python/metafunc.py

I had recently an issue with a complex parametrized test with a callable `ids`. The `ids` function was wrong but it took me sometime to notice as pytest was silently swallowing any errors when it was called.
I changed the code necessary so this won't happen anymore and modified/created some tests.
One more thing though, a question for you, guys: I tried to do some kind of `raise...from` with a better exception with fixture name but the meta-function information doesn't propagate up to ids function (unlike the `config` object, which happens to be available there, though it isn't mandatory). If the meta-function got there it'd probably be possible to be way clearer about error, what do you think about this?

No longer silently ignore errors in parametrize callable ids

---

CHANGELOG.rst
_pytest/recwarn.py
testing/test_recwarn.py

This makes it more similar to pytest.raises. Fixes #2151.

pytest.warns checks for subclass relationship rather than class equality

---

AUTHORS
_pytest/monkeypatch.py
testing/test_monkeypatch.py

If you're open to merging this, let me know if I should target a different branch than master and I'll amend the commit to include updates to changelog/authors

Switch monkeypatch fixture to yield syntax

---

AUTHORS
CHANGELOG.rst
_pytest/_argcomplete.py
_pytest/assertion/__init__.py
_pytest/cacheprovider.py
_pytest/capture.py
_pytest/config.py
_pytest/debugging.py
_pytest/fixtures.py
_pytest/main.py
_pytest/mark.py
_pytest/monkeypatch.py
_pytest/pytester.py
_pytest/runner.py
_pytest/skipping.py
_pytest/terminal.py
_pytest/tmpdir.py
_pytest/vendored_packages/pluggy.py

Added (object) to the end of class names as discussed in #2147. I searched the pytest package folder with the regex "class [A-Z]\w*(?<!\():" and added (object) before the colon of each class. The tests passed as expected. Thoughts?

Refactored old style classes to new style classes

---

CHANGELOG.rst
_pytest/config.py
testing/test_assertrewrite.py
testing/test_config.py

Consider plugins loaded by PYTEST_PLUGINS for assertion rewrite

---

doc/en/assert.rst
doc/en/faq.rst

Remove mention of --assert=reinterp in documentation

---

AUTHORS
CHANGELOG.rst
_pytest/pytester.py
testing/test_pytester.py

Currently if the terminal report of testdir.runpytest() is missing,
assert_outcomes() on its output fails because parseoutcomes()
returns an unexpected value (None).
It's better to fail parseoutcomes() directly.

Fail assert_outcomes() on missing terminal report

---

CHANGELOG.rst
_pytest/config.py
testing/test_assertion.py

Assert statements of the pytester plugin again benefit from assertion rewriting

---

.travis.yml
CHANGELOG.rst
_pytest/pytester.py
appveyor.yml

There's a little hack on `pytester` that deletes modules from `sys.modules` that were imported during inline runs and it included a little nugget that prevented `zope.interface` from being deleted; apparently `zope.interface` keeps some internal state that can't just be deleted from `sys.modules`.
I guess at some point `zope.interface` was split into internal modules and the condition no longer had any effect. causing things to blow up spectacularly. 🔥 
At first glance this seems like an internal testing issue and I wasn't going to add a `CHANGELOG` entry, but then realized that `pytester` is part our public API so it warrants an entry.
Fix #1989

Fix pytester internal plugin to work correctly with latest versions of zope.interface

---

tox.ini

due to a devpi bug, we always get a sdist install which in turn triggers
the pytest issue #2042 / #726
going for pyargs and a changed folder, it should no longer happen
(and will be tested further after rebasing the release branch)

fix devpi test for doctesting env

---

AUTHORS
CHANGELOG.rst
_pytest/hookspec.py
_pytest/python.py
testing/python/metafunc.py

* Allow `make_parametrize_id()` to return an empty string as id name
Bug: the doc states that "Return None if the hook doesn’t know about val" however. This should facilitate the hook function returning an empty string for a parameter's ID name. However, due to the `if return_value:` conditional a `None` value would skip the branch and therefore an automatic ID name would be generated.
* Pass parameter name to `make_parametrize_id` hook function
Feature: passing the parameter name into the hook function can be useful in some circumstances to control the name generation behaviour.

Enhancement to `make_parametrize_id`hook function

---

doc/en/unittest.rst

After some discussion @nedbat on IRC - he simply don't believe TestCase are bad :stuck_out_tongue_winking_eye:

Discourage users from using unittest support somewhat

---

CHANGELOG.rst
_pytest/python.py
testing/python/raises.py
testing/test_recwarn.py

`pytest.raises` can now assert that the error message contains a certain text.
Example:
```python
with raises(ValueError, match_info='must be 0'):
raise ValueError("value must be 0 or None")
```
This is a more compact and IMHO cleaner way of doing it like this:
```python
with raises(ValueError) as exc_info:
raise ValueError("value must be <= 10")
assert "value must be <= 10" in str(exc_info.value)
```

add matching the error message to pytest.raises

---

AUTHORS
CHANGELOG.rst
_pytest/fixtures.py
testing/python/collect.py

Previously, properties such as in the added test case were triggered
during collection, possibly executing unintended code. Let's skip them
instead.
We should probably skip all custom descriptors, however I am not sure
how to do this cleanly, so for now just skip properties.
Fixes #2234.

ignore property errors when parsing fixure factories

---

doc/en/talks.rst

I think this should target master?
I also notice that HOWTORELEASE.rst does not seem to mention how to publish the new documentation.

Mention next training event.

---

doc/en/writing_plugins.rst

As discussed in #2246
Closes #2246

Improve pytest_plugins docs

---

CHANGELOG.rst
_pytest/main.py
doc/en/customize.rst

venv (without a dot) is commonly used as a name for a virtualenv directory, and
we don't want to collect that.

Add venv to the default norecursedirs

---

CHANGELOG.rst
_pytest/config.py
testing/test_config.py

--override-ini now correctly overrides some fundamental options like "python_files"

---

_pytest/hookspec.py

Document pytest_report_header and conftest behavior

---

CHANGELOG.rst
_pytest/junitxml.py
testing/test_junitxml.py

In the xml report we now have two occurrences for the system-out tag if
the testcase writes to stdout both on call and teardown and fails in
teardown.
This behaviour is against the xsd.
This patch makes sure that the system-out section exists only once per testcase.
How to reproduce:
```python
@pytest.fixture(scope="function")
def setup_test(request):
print("I am in setup")
yield
print("I am in teardown")
raise Exception("test teardown Exception!")
def test_1(setup_test):
print("I am in call")
```
Gives output:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="1" failures="0" name="pytest" skips="0" tests="2" time="0.017">
<testcase classname="test.test2" file="test/test2.py" line="11" name="test_1" time="0.000563859939575">
<system-out>
I am in setup
I am in call …
```

junitxml: Fix double system-out tags per testcase

---

AUTHORS
CHANGELOG.rst
_pytest/capture.py
_pytest/compat.py
_pytest/pytester.py
testing/test_capture.py

Replay of  #2265 against origin/features

Make capsys more like stdio streams in python3. Resolves #1407.

---

doc/en/fixture.rst

Improve docs for yield-fixture and with statement a bit

---

AUTHORS
CHANGELOG.rst
_pytest/assertion/rewrite.py

Target: master
Addresses the issue here: https://github.com/pytest-dev/pytest/issues/2248
I'm not sure how to test this but am happy to add tests

Fix importing anydbm within pytest

---

CHANGELOG.rst
_pytest/junitxml.py
testing/test_junitxml.py

This patch is a solution to https://github.com/pytest-dev/pytest/issues/2228

Change junitxml.py to produce results that comply with Junitxml schema

---

.travis.yml

Allow py37-nightly to fail on Travis

---

AUTHORS
CHANGELOG.rst
_pytest/capture.py
testing/test_capture.py

@metasyn took the liberty of rebasing your commit on `master` now that `3.0.7` is out and moved tweaked the `CHANGELOG` a bit.
Supersedes #2311

Dont read from input exceptions

---

doc/en/goodpractices.rst
tox.ini

Attempt to clarify the confusion regarding __init__ files and unique test names

---

_pytest/recwarn.py
testing/test_recwarn.py

Since we dropped 2.5, we can now use warnings.catch_warnings to do the
"catch warnings" magic for us, simplifying the code a bit.
This is the refactoring I mentioned in #2298, which will ultimately be useful to finish #2072.

Refactor recwarn to use warnings.catch_warnings instead of custom code

---

AUTHORS
doc/en/usage.rst

Added small 'Possible exit codes' section to documentation.
Fixes #2239.
---
Please feel free to suggest any changes, especially to the status code 'explanation' as I was basing them only on the variable name and the place where they were invoked.

Added 'Possible exit codes' section to docs (#2239)

---

CHANGELOG.rst
_pytest/mark.py
_pytest/python.py
doc/en/parametrize.rst
testing/python/metafunc.py
testing/test_mark.py

this pr introduces a actual real type to separate parameter values and marks
this enables having functions as parameters with marks
it currently mirrors the broken mark overriding of the nested mark extraction code in place
documentation and examples upcoming

introduce pytest.Marked as holder for marked parameter values

---

CHANGELOG.rst
_pytest/compat.py
_pytest/python.py
testing/python/collect.py

Fix exception formatting while importing test modules

---

doc/en/requirements.txt

As discussed in rtfd/readthedocs-sphinx-ext#25, pinning to 1.4 to get correct search results back.
I pushed to pytest's repo instead of my own fork so I could test the results on RTD and it works:
https://docs.pytest.org/en/fix-search-docs/search.html?q=pytest_addoption&check_keywords=yes&area=default
Fix #2302

Pin sphinx to 1.4 when generating docs to workaround search issues on RTD

---

_pytest/fixtures.py

Corrected "or or" typo in docstring (and made indentation consistent).

Corrected documentation typo in fixtures.py

---

AUTHORS
CHANGELOG.rst
_pytest/cacheprovider.py
testing/test_cache.py

When using both --last-failed/--lf and --failed-first/--ff pytest would
run all tests with failed tests first (as if --lf was not provied). This
patch changes it so that when using both flags, only the last failed
tests are run. This makes it easier to set --ff as the default behavior
via the config file and then selectively use --lf to only run the last
failed tests.

Changed behavior if --lf and --ff are both used.

---

_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

In a recent refactoring (#2316) I enabled all `__future__` features in all pytest modules, but that has the unwanted side effect of propagating those features to compile()'d modules inside assertion rewriting, unless we pass `dont_inherit=False` to `compile()`:
> The optional arguments flags and dont_inherit control which future statements (see PEP 236) affect the compilation of source. If neither is present (or both are zero) the code is compiled with those future statements that are in effect in the code that is calling compile. If the flags argument is given and dont_inherit is not (or is zero) then the future statements specified by the flags argument are used in addition to those that would be used anyway. If dont_inherit is a non-zero integer then the flags argument is it – the …

Ensure rewritten modules don't inherit __future__ flags from pytest

---

_pytest/_code/code.py
_pytest/compat.py

This way they do not have to be recomputed at runtime.
I fixed them through out the file which showed the problem in #2343 – but there are may more places through out the whole code base which do these version checks.

Fix #2343: Replace version checks by constants.

---

CHANGELOG.rst
_pytest/config.py
_pytest/main.py
_pytest/pytester.py
_pytest/terminal.py
testing/acceptance_test.py
testing/test_helpconfig.py

Verify hooks after collection completes

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/python/collect.py

Fixes #2369.
Any hints on how to write a test for this?

Try not to assume a module's file extension is .py

---

CHANGELOG.rst
_pytest/assertion/__init__.py
_pytest/compat.py
_pytest/config.py
_pytest/debugging.py
_pytest/fixtures.py
_pytest/freeze_support.py
_pytest/hookspec.py
_pytest/main.py
_pytest/mark.py
_pytest/monkeypatch.py
_pytest/nose.py
_pytest/python.py
_pytest/recwarn.py
_pytest/runner.py
_pytest/skipping.py
_pytest/unittest.py
doc/en/writing_plugins.rst
pytest.py
testing/test_modimport.py

reopening of the prior pr #2280

remove pytest internal usage of the namespace hook

---

.travis.yml

Now that Python 3.6 is official, test against the official release.

Test against py36 official release for consistency with other python versions

---

AUTHORS
CHANGELOG.rst
_pytest/python.py
testing/test_mark.py

Show the correct error message when collect "parametrize" func with wrong args and add test to this case

Issue #2383 - AssertionError with wrong number of parametrize arguments

---

_pytest/pytester.py

After updating to twisted 17.1.0, again the trial tests started to fail; didn't investigate too deep, decided to just no longer delete `zope` modules when cleaning up after pytester because it seems more modules keep global state that shouldn't be discarded

Fix py35-trial environment

---

HOWTORELEASE.rst
MANIFEST.in
tasks/__init__.py
tasks/generate.py
tasks/release.minor.rst
tasks/release.patch.rst

As discussed in the mailing list, introducing [invoke](https://pypi.org/project/invoke/) tasks to simplify development and release process.
I started with a task to generate the AUTHORS file from git history but because pytest has a very old history, a lot of the names (60+) are not in a proper "name" format, a few examples:
```
famousgarkin
fijal
foxx
gabriel.reis
getxsick
```
I realized that finding the proper names would be a ton of work and not really worth the trouble, given that the AUTHORS file is updated during PRs and not during the release process.
This is the perfect place to introduce a task to update the CHANGELOG (#2390) IMO. 😁

Introduce a task to generate the announcement file for releases

---

CHANGELOG.rst
_pytest/config.py

this pr is to make the plugin manager run consider_module on all modules registred as plugin
this is supposed to address #2391 in a more general manner
however after moving the trigger i get a lot of errors that are hard to comprehend because pytest-spagetti

Consider all modules

---

AUTHORS
CHANGELOG.rst
_pytest/junitxml.py
doc/en/usage.rst
testing/test_junitxml.py

It can be used to specify `<testsuite>`'s `name` attribute in JUnit XML report. Resolves #533.

Add `junit_suite_name` ini option	

---

HOWTORELEASE.rst
doc/en/Makefile
doc/en/parametrize.rst
doc/en/unittest.rst
doc/en/warnings.rst
tasks/generate.py
tasks/requirements.txt
tox.ini

Automate most pre-release steps into invoke tasks, except for the CHANGELOG.
Follow up of #2410, without the actual changes made for a pre-release.

Automate pre release steps

---

doc/en/talks.rst

As asked on the mailing list by @okken.

Add a reference to Python testing book to talks docs

---

doc/en/example/simple.rst

Target: master
trivial documentation fix (e.g.,  a typo or reword of a small section)
Fix taken from http://stackoverflow.com/questions/25188119/test-if-code-is-executed-from-within-a-py-test-session

small fix in an example from the docs

---

CHANGELOG.rst
_pytest/_argcomplete.py
_pytest/assertion/__init__.py
_pytest/cacheprovider.py
_pytest/capture.py
_pytest/config.py
_pytest/debugging.py
_pytest/fixtures.py
_pytest/main.py
_pytest/mark.py
_pytest/monkeypatch.py
_pytest/pytester.py
_pytest/runner.py
_pytest/skipping.py
_pytest/terminal.py
_pytest/tmpdir.py

As discussed in the mailing list, unfortunately this might break APIs
due to the subtle differences between new and old-style classes (see #2398).
This reverts commit d4afa1554b225d11565d5fb81136edea51c54b0d from PR #2179.
After this is merged, we should re-open #2147.

Revert refactor of old-style to new-style classes

---

_pytest/cacheprovider.py
doc/en/cache.rst

This makes sure things don't jump around in the regenerated docs.

Make --cache-show output deterministic

---

CHANGELOG.rst
_pytest/compat.py
_pytest/warnings.py
testing/test_warnings.py

Correct warnings that contains Unicode message

---

CHANGELOG.rst
doc/en/warnings.rst
tox.ini

Related to discussion in #2430

Warn that warning-capture can break existing suites in the docs and CHANGELOG

---

CHANGELOG.rst
_pytest/doctest.py
testing/test_doctest.py

Fix unicode issue while running doctests in Python 2

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.rst
MANIFEST.in
changelog/2390.doc
changelog/2434.bugfix
changelog/2436.bugfix
changelog/_template.rst
pyproject.toml
scripts/check-manifest.py
scripts/check-rst.py
tasks/generate.py
tasks/requirements.txt
tox.ini

fixes #2390 but still needs to integrate towncrier into release drafting

initial addition of towncrier

---

_pytest/recwarn.py
changelog/2441.bugfix
testing/test_recwarn.py

pytest.deprecated_call now captures PendingDeprecationWarning in context manager form

---

_pytest/warnings.py
changelog/2390.doc
changelog/2430.bugfix
doc/en/warnings.rst
testing/test_recwarn.py
testing/test_warnings.py
tox.ini

In the end it was possible to actually fix the existing behavior. I checked and it no longer breaks SQLAlchemy test suite which was the original post on #2430.
As a downside/side-effect, this no longer automatically captures deprecation warnings because we want to play safe and don't try to mess the existing filters, but I believe we can review this in the future if we like.
Fix #2430

No longer override existing warning filters during warnings capture

---

CHANGELOG.rst
changelog/2390.doc
changelog/2430.bugfix
changelog/2434.bugfix
changelog/2436.bugfix
changelog/2441.bugfix
changelog/_template.rst
doc/en/announce/index.rst
doc/en/announce/release-3.1.1.rst
doc/en/warnings.rst

devpi builds:
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.8)
- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/237692120)
Must say the automated pre-release worked very well @RonnyPfannschmidt . 👍

Release 3.1.1

---

_pytest/assertion/rewrite.py
changelog/2121.bugfix
setup.py
testing/test_assertrewrite.py

This PR solves #2121.
Before merging this, https://github.com/pytest-dev/py/pull/99 and a new release of `py` is required.

Handle python_files correctly in assertion rewrite

---

AUTHORS
_pytest/config.py
_pytest/helpconfig.py
changelog/1999.bugfix
testing/test_conftest.py

This works by adding an argparse Action that will raise an exception in
order to skip the rest of the argument parsing. This prevents argparse
from quitting due to missing required arguments, similar to the way that
the builtin argparse --help option is implemented by raising SystemExit.
Fixes: #1999
P.S. I failed to run the tests on Python 3.6 due to https://github.com/pytest-dev/py/issues/103
- [V] Add a new news fragment into the changelog folder
* Make …

Fix --help with required options

---

_pytest/capture.py
changelog/103.bugfix

Python 3.6 implemented unicode console handling for Windows. This works by reading/writing to the raw console handle using ``{Read,Write}ConsoleW``.
The problem is that we are going to ``dup2`` over the stdio file descriptors when doing ``FDCapture`` and this will ``CloseHandle`` the handles used by Python to write to the console. Though there is still some weirdness and the console handle seems to only be closed randomly and not on the first call to ``CloseHandle``, or maybe it gets reopened with the same handle value when we suspend capturing.
The workaround in this case will reopen stdio with a different fd which also means a different handle by replicating the logic in "Py_lifecycle.c:[initstdio](https://github.com/python/cpython/blob/aead53b6ee27915de248b07de509529174aaad21/Python/pyl …

[WIP] A workaround for Python 3.6 WindowsConsoleIO breaking with FDCapture

---

_pytest/config.py
_pytest/hookspec.py
_pytest/vendored_packages/pluggy.py
changelog/2331.doc
doc/en/writing_plugins.rst

**Fixes: https://github.com/pytest-dev/pytest/issues/2331** 
head-fork: ApaDoctor/pytest
compare: docs-fixes
base-fork: pytest-dev/pytest
base: master          # if it's a bugfix

docs: Create links for objects to show the api

---

_pytest/warnings.py
changelog/2463.bugfix
testing/test_warnings.py

I agree with @dwaynebailey in that it is not pytest's job to issue a warning about this, specially because it might be out of the user's control and the standard library does not prohibit it anyway.
Fix #2463

Remove UnicodeWarning from pytest warnings

---

_pytest/_code/code.py
changelog/2459.bugfix
testing/code/test_excinfo.py

Fix internal error when a recursion error occurs and frames contain objects that can't be compared

---

_pytest/hookspec.py
changelog/2493.doc
doc/en/writing_plugins.rst

Docs: clarify when hooks stop after the first non-None result

---

LICENSE
README.rst
changelog/2499.trivial
doc/en/index.rst
doc/en/license.rst

Update license dates

---

_pytest/fixtures.py
changelog/2440.bugfix
testing/python/fixture.py

Should resolve https://github.com/pytest-dev/pytest/issues/2440 by following a similar procedure as `SetupState._callfinalizers()`.

Handle exceptions in subrequest finalizers

---

_pytest/doctest.py
changelog/2434.bugfix
testing/test_doctest.py

Fix decode error in Python 2 for doctests in docstrings

---

_pytest/main.py
_pytest/terminal.py
changelog/2464.bugfix
testing/acceptance_test.py
testing/test_collection.py
testing/test_runner.py
testing/test_terminal.py

It turns out pytest was triggering the `pytest_collectreport` hook when collecting the nodes in order to find the item specified in the command-line, but this is incorrect given that those nodes might not end up in the final list of items that will actually be run.
As a bonus this now only reports the exact number of items that will be executed:
```python
class TestClass(object):
def test_main(self):
assert 1
def test_bla(self):
assert True
```
```
$ pytest .tmp\test_foo.py::TestClass::test_main
============================= test session starts =============================
platform win32 -- Python 3.6.0, pytest-2.0.1, py-1.4.33, pluggy-0.4.0
rootdir: C:\pytest, inifile: tox.ini
plugins: hypothesis-3.7.0
collected 1 item
.tmp\test_foo.py .
========================== 1 passed in 0.01 …
```

Fix incorrect "collected items" report when specifying tests on the command-line

---

changelog/_template.rst

This unfortunately no longer supports multiple entries with the same text,
but this is worth the improved readability and navigation IMO

Add issue links in the CHANGELOG entries

---

doc/en/fixture.rst

fixture docs: highlight difference between yield and addfinalizer methods

---

_pytest/_code/code.py
changelog/2486.bugfix
testing/code/test_excinfo.py

Fix internal error when trying to detect the start of a recursive traceback

---

_pytest/recwarn.py
changelog/2469.bugfix
testing/test_recwarn.py

This normalizes the context-manager and function form of `deprecated_call` by using the exact same implementation.
I also updated the docs to mention the context-manager form first.
Fix #2469

deprecated_call context manager captures warnings already raised

---

_pytest/deprecated.py
_pytest/mark.py
_pytest/python.py
changelog/2516.feature
testing/test_mark.py

Mark expose nontransfered marks via pytestmark property

---

changelog/_template.rst
pyproject.toml

I think it might sense to display in the CHANGELOG internal or
trivial changes because they might trip users between releases.
For example, a note about an internal refactoring (like
moving a class between modules) is useful for a user
that has been using the internal API. Of course
we are not breaking anything because it was an internal API, but no
reason not to save time for users who did use it.

Show "trivial" category in CHANGELOG

---

changelog/2474.trivial
tasks/__init__.py
tasks/vendoring.py

Vendoring tasks

---

changelog/2147.removal

This note at least makes that official, given that it is difficult/nearly impossible to add warnings to the code for them.
Related to #2147

Add changelog entry explicitly deprecating old-style classes from pytest API

---

AUTHORS
_pytest/python.py
changelog/2528.feature
testing/python/collect.py

Allow a class method decorated `@staticmethod` to be collected as a test function
(if it meets the usual criteria).
Fixes #2528 
----

Allow staticmethods to be detected as test functions

---

_pytest/main.py
changelog/2475.bugfix

For some legacy reason, I have a container copying source to '/' directly. 
From there `rootdir='/'` and paths gathered by pytest have 3 leading /. 
the condition https://github.com/pytest-dev/pytest/pull/2475/files#diff-5b415004cf343fc3c36aebb8aad93882L178
is checking the following and it doesn't match: 
```
if "///endpoints/test/test_api.py" in [local('/endpoints/test')]
```
This pr simply format the path the way the excludepath is formatted
----
* Make …

[wip] Fix ignore_path condition

---

_pytest/main.py
changelog/2444.trivial
doc/en/example/markers.rst
testing/test_skipping.py

Change --strict help message to clarify it deals with unregistered markers

---

_pytest/hookspec.py
changelog/2539.doc

Clarify pytest_configure hook call order

---

_pytest/cacheprovider.py
changelog/2543.feature
doc/en/cache.rst
doc/en/customize.rst
testing/test_cache.py

cache_dir ini option for setting cache directory ( issue #2543 )

cache_dir ini option for setting cache directory

---

_pytest/compat.py
_pytest/python.py
changelog/2533.trivial

Rename _escape_strings to _ascii_escaped

---

_pytest/main.py
changelog/2518.feature
doc/en/customize.rst
testing/test_collection.py

This should address / close ticket #2518.  The behaviour implemented is as follows:
1.  During collection, if pytest detects that the directory it is considering is `sys.prefix`, the directory and any tests it contains will be ignored and a helpful warning will be issued.
2.  If `--collect-in-virtualenv` (a new CLI flag) is passed, pytest will collect anyways.
3.  If the relevant path is explicitly ignored; i.e. `--ignore=./.env` or what have you, the warning is silenced.
I tried to write a test but couldn't quite figure out how to effectively mock `sys.prefix`; I'd appreciate some help there.  Other feedback is also totally welcome.

Detect and warn/ignore local python installations

---

_pytest/python.py
changelog/2562.trivial
testing/deprecated_test.py

Emit the yield test deprecation warning only once per generator, rather than for each generated function.
This is important when porting old projects with a large number of legacy yield tests --- you don't want to have the warning repeated 10000+ times in the output.
Addresses #2562 (apart from the fact that these warnings cannot be ignored via filterwarnings)

Make YIELD_TEST warning less spammy

---

_pytest/main.py

Add docs for Item.add_report_section in the docs

---

_pytest/terminal.py
changelog/2571.trivial

We sometimes would see the following line:
**``collected 1 item s``**
just because previous write to the terminal includes number of characters greater than 'collected 1 item'.

Ensure final collected line doesn't include artifacts of previous write

---

AUTHORS
_pytest/python.py
changelog/2574.bugfix
testing/python/fixture.py

#2574 Options --fixtures and --fixtures-per-test keep indentation of docstrings

---

_pytest/mark.py

remove the MARK_INFO_ATTRIBUTE warning until we can fix internal usage

---

_pytest/runner.py
changelog/2583.feature
doc/en/customize.rst
doc/en/example/simple.rst
doc/en/usage.rst
testing/test_runner.py
tox.ini

Introduce new `PYTEST_CURRENT_TEST` environment variable (#2583).
While looking at the docs I decided to improve the section about selecting tests because `PYTEST_CURRENT_TEST` is all about `nodeid`s and I didn't find a good explanation about that.
Also improve the docs on how `PYTEST_ADDOPTS` and `addopts` interact to create the final command-line.

Introduce new PYTEST_CURRENT_TEST environment variable

---

changelog/971.doc
doc/en/writing_plugins.rst

Extend pytester docs for testing plugin code

---

AUTHORS
_pytest/compat.py
changelog/2375.trivial
testing/test_capture.py

Fixes patching sys.stdout.encoding when using Capsys fixture on Python 2.
Fix #2375

Provides encoding attribute on CaptureIO

---

_pytest/compat.py
testing/test_capture.py

A recent `hypothesis` release seems to have added a "logging" import to the top-level,
which breaks test_logging_initialized_in_test

Fix: do not load hypothesis during test_logging_initialized_in_test

---

_pytest/warnings.py
changelog/2598.feature
doc/en/warnings.rst
testing/test_warnings.py

Introduces `@pytest.mark.filterwarnings` that can override warnings filter per item.

Introduce filter-warnings mark

---

CONTRIBUTING.rst
changelog/2375.bugfix
changelog/2375.trivial
changelog/2533.trivial
changelog/2562.trivial
changelog/2574.bugfix
changelog/2581.trivial
changelog/2582.trivial
testing/code/test_excinfo.py
testing/code/test_source.py
testing/code/test_source_multiline_block.py
testing/test_capture.py
testing/test_conftest.py
testing/test_runner.py
tox.ini

As discussed in #2582, adding a small tox env to make it easy to fix linting errors.

Add "fix-lint" tox environment 

---

_pytest/mark.py
changelog/2540.feature
testing/test_mark.py

this extracts the bit about adding params and exposes it in a unconditional way

fix #2540, introduce mark.with_args

---

_pytest/python_api.py
tox.ini

I *think* this fixes an issue that came up in #2599 -- where certain `approx` comparisons with numpy arrays trigger a DeprecationWarning -- by simplifying how approx interfaces with numpy arrays.
Previously, approx used inheritance to guarantee that it's `__eq__` operator was called rather than the numpy array's.  This worked most of the time, but the DeprecationWarning in #2599 was due to a shortcoming of this approach.  (It think it also would've choked on comparisons with subclasses of `np.ndarray`, but I never tested this.)
It turns out that there's a better way to make sure that `approx.__eq__` gets called, and that's to set `approx.__array_priority__` to a large number.  Whenever anything is compared to an array, numpy checks for this attribute and gives priority to whichever object …

Make approx more compatible with numpy

---

.travis.yml
changelog/2588.trivial
testing/python/collect.py
testing/python/metafunc.py
testing/python/setup_only.py
testing/test_mark.py
testing/test_recwarn.py
testing/test_unittest.py
testing/test_warnings.py
tox.ini

This fixes #2588 
When I started working on this I noticed I needed to control warnings on a per-test level, hence #2598 in which this branch is built on. We should review and consider merging this only if #2598 is.
As a test, I reverted 62556bada660ca209e7e83bc775559d9039f31b1 locally to see if this change would catch the regression, and indeed 25 tests failed so this seems to do the trick.

Turn warnings into errors WIP, waiting #2598

---

_pytest/config.py
doc/en/cache.rst
doc/en/contents.rst
doc/en/customize.rst
doc/en/example/index.rst
doc/en/nose.rst
doc/en/pythonpath.rst
doc/en/usage.rst
doc/en/writing_plugins.rst

- Also minor adjustments in the docs (wording, formatting, links, etc).
Fix #2589

Clarify PYTHONPATH changes and ``rootdir`` roles

---

_pytest/capture.py
changelog/2510.bugfix
changelog/2611.bugfix

I have had it print ANSI escapes without stripping or conversion. With https://github.com/tartley/colorama/pull/131 it captures the wrong default terminal attributes so that the default text color is black (colorama doesn't check for errors).
Importing colorama in a conftest.py should reproduce this.

Early import colorama so that it get's the correct terminal

---

_pytest/doctest.py
changelog/2610.bugfix
testing/test_doctest.py

This is to fix [pytest-sugar#122](https://github.com/Frozenball/pytest-sugar/issues/122) issue.

Report lineno from doctest

---

_pytest/skipping.py
changelog/2548.bugfix
testing/test_skipping.py

The line number is 0-based here, so add 1.
I've done similar fixes before, and asked already before if this should be fixed more upwards in the end, since it seems to cripple down everywhere?!

Fix lineno offset in show_skipped

---

_pytest/pytester.py
changelog/2023.bugfix

The debugging.py calls post_mortem() on error and pdb will drops an
interactive debugger when the stdin is a readable fd.

Avoid interactive pdb when pytest tests itself - fix #2023

---

_pytest/capture.py
changelog/2555.bugfix
testing/test_capture.py

Fixes https://github.com/pytest-dev/pytest/issues/2555.

capture: ensure name of EncodedFile being a string

---

AUTHORS
changelog/2620.trivial
changelog/_template.rst

Restores the functionality removed in PR #2488.

Show multiple issue links in CHANGELOG entries

---

_pytest/hookspec.py
_pytest/terminal.py
changelog/2622.feature
doc/en/writing_plugins.rst
testing/test_terminal.py

Introduce new pytest_report_collectionfinish hook

---

_pytest/cacheprovider.py
changelog/2621.feature
testing/test_cache.py

When introducing a delicate change to a large code base (2000+ tests), I often run all tests (using xdist) to see what has been affected, then ooops, 400 broken tests.
I would like to go fixing module by module to get everything green again.
What happens currently is this:
1. Run all tests: `pytest tests`. BOOM, 400 failures. Oh boy. 
1. Run tests from the first module with failures: `pytest tests/core --lf`. Fix all failures, get a green run.
1. Run tests from the next module with failures: `pytest tests/controller --lf`. At this point the cache plugin forgets the previous failures, running *all* tests found in `test/controller` again, regardless if they have failed before or not.
Because of this, I often find myself copying/pasting the list of failed modules somewhere so I can run them …

Make cache plugin cumulative

---

_pytest/cacheprovider.py
_pytest/hookspec.py
testing/test_cache.py

Using the new `pytest_report_collectionfinish` hook it is now possible to accurately report the items which will be rerun.
Should be reviewed only after #2621 is merged.

Fix --last-failed reported items in terminal

---

AUTHORS
_pytest/fixtures.py
changelog/920.bugfix
doc/en/getting-started.rst
setup.py
testing/python/fixture.py
tox.ini

fixtures.reorder_items is non-deterministic because it reorders based
on iteration over an (unordered) set.  Change the code to use an
OrderedDict instead, so that we get deterministic behaviour.
The xdist issue in #920 is a red-herring.  Fixture collection is non-deterministic across pytest invocations full stop if hash randomisation is on.
For example, consider the following test file:
```python
import pytest
@pytest.fixture(scope="module",
params=["A",
"B",
"C"])
def A(request):
return request.param
@pytest.fixture(scope="module",
params=["DDDDDDDDD", "EEEEEEEEEEEE", "FFFFFFFFFFF", "GGGGGGGGGGGG"])
def B(request, A):
return request.param
def test_foo(B):
assert True
```
```sh
$pytest test_foo.py --collect-only
============================================================================= …
```

Fix nondeterminism in fixture collection order

---

AUTHORS
_pytest/_code/code.py
changelog/2631.feature
testing/code/test_excinfo.py

PEP-415 states that `exception.__context__` should be suppressed
in traceback outputs, if `exception.__suppress_context__` is
`True`.
Now if a ``raise exception from None`` is caught by pytest,
pytest will no longer chain the context in the test report.
The algorithm in `FormattedExcinfo` now better matches the one
in `traceback.TracebackException`.
`Exception.__suppress_context__` is available in all of the
versions of Python 3 that are supported by pytest.
Fixes #2631.

Support PEP-415's Exception.__suppress_context__

---

_pytest/fixtures.py
_pytest/main.py
_pytest/outcomes.py
_pytest/python.py
_pytest/python_api.py
_pytest/recwarn.py
_pytest/runner.py
_pytest/skipping.py
_pytest/unittest.py
changelog/580.feature
doc/en/builtin.rst
pytest.py
testing/test_runner.py

Test Outcomes as BaseException - fix #580

---

AUTHORS
_pytest/python_api.py
changelog/2003.feature
changelog/2003.removal
testing/python/approx.py

This PR changes the current behavior of `approx` to raise `NotImplementedError` for all comparisons but `__eq__` as discussed in #2003 
Note: I thought about adding a warn that this is currently not supported like: 
```bash 
warnings.warn("Currently not supported")
raise NotImplementedError
```
But we found #2452 mentioning that `pytest.config.warn` should be deprecated. Also, I was not sure how to use this in approx, as it is not a fixture and the `config` object is not available out of the box. Can we just use the `warnings` module there? Or is mentioning this in the docs enough?

#2003 Change behavior of `approx.py` to only support `__eq__` comparison

---

_pytest/config.py
_pytest/main.py
changelog/2236.removal
pytest.py

by removing preinit we remove loading the initial plugin list
this is no longer needed, since we no longer use pytest-namespace for pytest itself
the followup for this one is to deprecate the pytest-namespace hook alltogether

remove preinit, its no longer needed

---

CHANGELOG.rst

Tiny rst syntax fix

---

_pytest/pytester.py
_pytest/runner.py
changelog/2644.bugfix
testing/acceptance_test.py

Properly escape test names when setting PYTEST_CURRENT_TEST environment variable

---

_pytest/terminal.py
changelog/2579.bugfix
testing/test_terminal.py

Fix small terminal glitch when collecting a single test item

---

changelog/2626.doc
doc/en/mark.rst
doc/en/skipping.rst
doc/en/unittest.rst
doc/en/usage.rst

Document which pytest features work with `unittest`

---

AUTHORS
_pytest/config.py
changelog/2591.bugfix
testing/test_config.py

Removed os.sep as it behaves differently linux and windows
* on linux it is '/'
* on windows it is '\\\\'

Fixed#2591: Replaced os.sep with '/' as it behaves differently on linux and windows.

---

_pytest/capture.py
changelog/2666.bugfix
testing/test_capture.py

Fix windows console workaround error with non-standard io-streams

---

changelog/2653.doc
doc/en/example/simple.rst

Hi! I recently faced the same issue as in #472 when trying to reuse the `slow` marker and it took me a while to understand why that was failing. I figured that having this note would be useful. If someone agrees, I can go through the checklist to make it a proper PR.
Question: in a similar issue (#1688) @nicoddemus said that "using `pytest.config` is discouraged". Is its use discouraged in that specific case or there is a better way to use the configs in general?
Thanks!
---
* Make sure to use full sentences with correct case …

Add note on sharing the `slow` marker in the basic examples

---

_pytest/fixtures.py
changelog/2681.bugfix

Use the correct stacklevel for getfuncargvalue() deprecation warning.

---

_pytest/mark.py
_pytest/python.py
changelog/2672.removal
changelog/2675.removal
testing/python/metafunc.py

this ensures we don't override in that area
the final parts of the transfer are still broken, but with the list, we at least have a chance to do better in future
this is also base to fix #1540 in future

ensure callspecs contain the list of marks

---

.travis.yml
appveyor.yml
scripts/call-tox.bat
tox.ini

This should be reviewed after #2685 as it builds on the commit of that PR.

Use 3.6 as preferred Python 3 interpreter for CI 

---

AUTHORS
_pytest/skipping.py
changelog/2549.feature
testing/test_skipping.py

Hi!
Address #2549
Current check based on `keywords` dict. Maybe better solution will be to introduce additional `keywords` entry for tests, skipped because of global `pytestmark` variable. What do you think?
===

Fold skipped tests with global pytestmark variable

---

changelog/2691.trivial
doc/en/goodpractices.rst

When initializing with `pytest_args = []`, if no arguments are passed, `shlex.split` fails parsing the empty list.
It can be easily fixed by initializing with `pytest_args = ''`.
---

Fixed error in 'Good Practices' code snippet

---

_pytest/python_api.py

Also update the text to recommend using the context-manager
over the callable/string forms.

Update docs: ``match`` keyword was introduced in 3.1

---

doc/en/assert.rst

This PR modifies the regular expressions and custom messages of raises to include `match` parameter in `pytest.raises` according to its docstring documentation.

[DOC] update raises documentation regarding regex match

---

_pytest/compat.py
changelog/2707.bugfix
testing/test_compat.py

Hey, all!
Today I've spent few hours by tracking strange error after update to 3.2.1
`git blaming` showed that it was caused by 06a49338b2b1be8daed89f779439459a2cb4cbc7 from #2490 (that is fix for #580 ) particularly inheritance from `BaseException`
@nicoddemus  @RonnyPfannschmidt 
This is quite hard to provide minimal steps to reproduce our case, in general it is caused by https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/plugin.py#L615 throws `fail`
We're doing some work during class initialization (in descriptors), thus before database is unblocked and it was fine before this commit: upon collecting it wasn't fail and during the tests, fixtures were created without errors.
1. We're creating descriptor that is trying to create object in database when we're accessing …

Catch BaseException in safe_getattr

---

_pytest/_code/code.py
changelog/2731.bugfix
testing/code/test_code.py

The class `_pytest._code.code.ReprFuncArgs` crashes with `UnicodeDecodeError` when trying to write args with mixed `unicode` and `utf-8` strings.
Fixes #2731.

2731.bug Fix ReprFuncArgs with mixed unicode and utf-8 args.

---

_pytest/compat.py
_pytest/fixtures.py
changelog/2699.bugfix
testing/python/collect.py
testing/python/fixture.py

Allow tests declared as @staticmethod to use fixtures

---

_pytest/recwarn.py
changelog/2708.feature
doc/en/warnings.rst
testing/test_recwarn.py

fixes #2708 providing warns with `message` and `match` parameters (similarly to `pytest.raises`. see #2227)

[MRG][feature] Change warns signature to mimic the raises call

---

_pytest/mark.py
changelog/2758.bugfix
testing/test_mark.py

Fix https://github.com/pytest-dev/pytest/issues/2758

[bugfix] Checking MarkDecorator equality returns False for non-MarkDecorator object

---

doc/en/skipping.rst

add warning to skipping docs re marker inheritance

---

changelog/1548.doc
doc/en/parametrize.rst

Fix https://github.com/pytest-dev/pytest/issues/1548
I wanted to add some code to demonstrate but afraid it would be an overkill and make the doc too verbose.

Update documentation on multiple calls of metafunc.parametrize

---

changelog/2722.trivial
testing/code/test_source.py
tox.ini

Set xfail_strict=True in pytest's own test suite

---

HOWTORELEASE.rst
doc/en/contents.rst
doc/en/development_guide.rst

I started writing about which types of labels we use on our issues because this just grew organically, and realized that we don't have a development guide so I turned it into that.
It is not exhaustive, but at least it will get the ball rolling for further additions.
**also**, I propose we do the following:
* It is clear that labels also have a type/category associated to them. I noticed some projects (like [pip](https://github.com/pypa/pip/labels) and [tox](https://github.com/tox-dev/tox/labels)) use a prefix, and I suggest we adopt this idea as well. Then the classification is much clearer IMHO.
* Some labels are duplicated or don't seem to have a clear purpose; I propose to just remove them.

Add development guide to docs

---

_pytest/_argcomplete.py
changelog/2748.bugfix
testing/test_argcomplete.py

Fixes #2748. This fixes the crash without altering the existing behavior.

Fix crash in FastFilesCompleter with no prefix

---

tox.ini

This also has the benefit of working around Travis recent failures
in Python 3.5 environments.

Change to py36 as main environment for Python 3 environments in tox

---

CONTRIBUTING.rst

Just noticed this while stealing the contributors docs.

fix tox documentation link

---

_pytest/python.py
changelog/2788.bugfix
testing/python/show_fixtures_per_test.py

fixes #2788
Simplest possible way of making that error go away. I have obviously no idea what I am doing though.

Don't crash if an item has no _fixtureinfo attribute

---

_pytest/config.py
_pytest/debugging.py
_pytest/helpconfig.py
_pytest/pastebin.py
_pytest/skipping.py
_pytest/terminal.py
changelog/2803.removal

Deprecate TerminalReporter._tw

---

_pytest/compat.py
_pytest/python.py
_pytest/warnings.py
changelog/2809.bugfix
testing/test_warnings.py

Fix warning about non-ascii warnings even when they are ascii

---

CHANGELOG.rst
changelog/1442.doc
changelog/1548.doc
changelog/2722.trivial
changelog/2748.bugfix
changelog/2758.bugfix
changelog/2765.trivial
changelog/2788.bugfix
doc/en/announce/index.rst
doc/en/announce/release-3.2.3.rst
doc/en/parametrize.rst
doc/en/skipping.rst

- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.24)
- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/282946088)

Preparing release version 3.2.3

---

changelog/1997.doc
doc/en/skipping.rst

Handle https://github.com/pytest-dev/pytest/issues/1997:
- Explain `xpass` in the context of `xfail`
- Update example of `-r` option to include `X` of xpassed tests
- Point users to refer to the help text for further info on the `-r` option
I don't think `xpass` is something worth a separate entry in the TOC but just some explicit mention to clear any doubts for those who don't figure it out from the test summary.
* Make sure to use full sentences with …

Add mention of xpass in skip/xfail documentation

---

_pytest/fixtures.py
changelog/2819.bugfix
testing/test_mark.py

Previously only this worked:
`@pytest.mark.parametrize("A", argvalues=[(A1, ), (A2, )])`
Now argnames can be specified explicitly:
`@pytest.mark.parametrize(argnames="A", argvalues=[(A1, ), (A2, )])`

Fix pytest.parametrize when argnames are specified as kwarg

---

_pytest/capture.py
_pytest/debugging.py
_pytest/setuponly.py
changelog/1993.bugfix
changelog/2709.bugfix
testing/test_capture.py

Fix #2709
Also refactor some names for better understanding and consistency, and although they are all internal I'm targeting `features`. Those renames are in a separate commit and we can drop it if we wouldn't like to touch the names.

Allow fixtures to use capsys and capfd 

---

.travis.yml
_pytest/compat.py
appveyor.yml
changelog/2812.removal
setup.py
tox.ini

Nomore py26

---

.coveragerc
AUTHORS
README.rst
_pytest/_argcomplete.py
_pytest/_code/source.py
_pytest/assertion/__init__.py
_pytest/assertion/rewrite.py
_pytest/fixtures.py
_pytest/pytester.py
_pytest/python_api.py
doc/en/example/multipython.py
doc/en/getting-started.rst
doc/en/index.rst
doc/en/skipping.rst
setup.py
testing/acceptance_test.py
testing/code/test_excinfo.py
testing/code/test_source.py
testing/python/approx.py
testing/python/collect.py
testing/test_assertrewrite.py
testing/test_config.py
testing/test_parseopt.py
testing/test_unittest.py

Follow on from https://github.com/pytest-dev/pytest/pull/2822 and for https://github.com/pytest-dev/pytest/issues/2812 and removes some other code for old unsupported versions. 
---

 Remove code for unsupported Python versions

---

AUTHORS
_pytest/outcomes.py
_pytest/skipping.py
changelog/2808.feature
doc/en/skipping.rst
testing/test_skipping.py

Work-in-progress fix for https://github.com/pytest-dev/pytest/issues/2805
I need to update the PR with all contributing guideline recommendations, but a initial feedback would be good.
--//--

Allow module level skip

---

doc/en/example/parametrize.rst

Fix typo in parametrization doc

---

doc/en/fixture.rst

I may be wrong but it looks like `self` shouldn't appear in the fixture signature if it's a not a class method.

Fix auto-use fixture doc

---

AUTHORS
_pytest/doctest.py
changelog/502.feature
testing/test_doctest.py

Addresses https://github.com/pytest-dev/pytest/issues/502

ignore valid setup.py during --doctest-modules

---

_pytest/mark.py

Spelling Fix

---

_pytest/config.py
changelog/2824.feature
testing/test_config.py

While it works to pass `-o cache_dir=/somewhere` as command line arguments or set the option in the `setup.cfg` file I tried to achieve the same by setting the environment variable `PYTEST_ADDOPTS="-o cache_dir=/somewhere"`.  This doesn't work atm since the variable is only being considered after [Config._initini](https://github.com/pytest-dev/pytest/blob/46e30435ebad1796e54d99572d43a5b6a1961a19/_pytest/config.py#L1005) has been called which e.g. decides on the `override_ini`.
To enable this use case this patch moves the call to `Config._initini` behind getting the environment variable `PYTEST_ADDOPTS`. I didn't see any negative side effects of this change but I am new to `pytest` so might be missing something.
I haven't added a test for this since I thought getting feedback in the patch …

get PYTEST_ADDOPTS before calling _initini

---

changelog/538.doc
doc/en/fixture.rst

Clarify the documentation of fixture scopes

---

_pytest/main.py
changelog/2845.bugfix
testing/test_collection.py
testing/test_terminal.py

As I explained in the issue #2832, I'm not sure that the behavior is incorrect by itself, but have sense both options, interrupt return, and failed return. Anyway, I prefer to have failed return and leave "interrupt" to explicit user interruptions, like Ctrl-C.

Adding Failed exception to manage maxfail behavior

---

AUTHORS
_pytest/compat.py
_pytest/fixtures.py
changelog/2267.feature
setup.py
testing/python/fixture.py

*This is not finished*.  I'm opening the PR now because I need to ask questions about implementation details.
The specific detail I'm looking at right now is that getfuncargnames's handling of functions with arguments with defaults or keyword-only arguments and arguments bound with functools.partial is distinctly... odd, and arguably buggy.  Here's an example of functools.partial without any Python 3 features:
```python
>>> def f0(b, c=0, *a, **k): print(b, c, a, d, k)
...
>>> g0 = functools.partial(f0, 2)
>>> def h0(b=2, c=0, *a, **k): print(b, c, a, k)
>>> _pytest.compat.getfuncargnames(f0)
('b',)
>>> _pytest.compat.getfuncargnames(g0)
('c',)
>>> _pytest.compat.getfuncargnames(h0)
()
>>> inspect.signature(f0)
<Signature (b, c=0, *a, **k)>
>>> inspect.signature(g0)
<Signature (c=0, *a, …
```

Use funcsigs and inspect.signature to do function argument analysis

---

doc/en/warnings.rst

Small typo in docs which leads to syntax error

Remove typo @ in assignment

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.rst

As brought to attention by in [this comment](https://github.com/pytest-dev/pytest/pull/2864#issuecomment-338790369) by @bilderbuchi.

Make CONTRIBUTING and PR template more consistent regarding doc contributions

---

AUTHORS
_pytest/fixtures.py
_pytest/junitxml.py
_pytest/main.py
_pytest/nodes.py
_pytest/terminal.py
changelog/2836.bug
testing/test_collection.py
testing/test_fixtures.py
testing/test_nodes.py

Attempted fix for #2836.
The existing handling of 'nodeid' when determining what fixtures are visible is overly simplistic - it considers 'tests/food' to be a 'child' node of 'tests/foo', when in fact they are sibling nodes. This causes fixtures from 'tests/foo/conftest.py' to be used in tests like 'tests/food/test_food.py'.
This PR makes the hanlding more sophisticated - splitting the node id into components and then ensuring the base node id parts fully match the target node id's initial parts. This is still a little imperfect, in that would treat `foo/bar::Baz::()` as if it was the same as `foo/bar/Baz/()`. That seems a somewhat unlikely situation...
I'm not super keen on having `_splitnode` and `_ischildnode` as members of FixtureManager, but I don't really see any obvious other place …

Issue 2836 fixture collection bug

---

_pytest/mark.py
changelog/2856.bugfix
testing/test_mark.py

Strip whitespace from markers in INI config

---

changelog/1505.doc
doc/en/assert.rst
doc/en/fixture.rst
doc/en/plugins.rst
doc/en/writing_plugins.rst

Also reorganize conftest-related content a bit.
Closes #1505, closes #1770.
Btw, @nicoddemus, your PR template and CONTRIBUTING file are not consistent about if doc changes trigger/warrant an inclusion into the AUTHORS file.

Introduce a dedicated section about conftest.py

---

_pytest/config.py
changelog/2491.bugfix
testing/test_pluginmanager.py

bugfix for issue #2491

---

_pytest/assertion/rewrite.py
testing/test_assertrewrite.py

Some bytecode tests are expected to fail in Python 3.7.0a1 and 3.7.0a2, because there was a [bug](https://bugs.python.org/issue31845) that prevented some environ vars from having effect. It was fixed in https://github.com/python/cpython/commit/d7ac061.
Resolves #2818.

Adapt the Python 3.7 AST changes

---

doc/en/example/pythoncollection.rst
doc/en/skipping.rst

None of the decorators are sufficient to skip an entire file, for
example if the file contain invalid code for a given Python version.
Simply link to details about customizing the collector.

doc: Include collector config in the skip doc

---

AUTHORS
_pytest/capture.py
changelog/2879.feature
testing/test_capture.py

Return stdout/stderr capture results as a `namedtuple`,
so `out` and `err` can be accessed by attribute.
Includes tests for the `capsys` fixture, and for the context manager class.
Closes #2879

Capture result namedtuple

---

_pytest/doctest.py
changelog/2882.bugfix
testing/test_doctest.py

If the linenumber of a failing doctest is < 9, the failure/error report is wrong.

Fix context output handling for doctests

---

testing/test_assertrewrite.py
tox.ini

The `filter_traceback` function was not filtering the frames
that belonged to the pytest internals.
"filter_traceback" was receiving *relative* paths when running with
xdist, and full paths in non-distributed runs; for this reason
the traceback function did not consider the received path to be
relative to the pytest internal modules:
https://github.com/pytest-dev/pytest/blob/111d640bdb69a0bba25f86e5c265ab02415698c3/_pytest/python.py#L48-L49
`py.path.local(entry.path)` will create a full path using `cwd` because `entry.path` is relative, and `cwd` would point to the `testdir` directory (as it should).
I debugged up until `Code.__init__`:
https://github.com/pytest-dev/pytest/blob/111d640bdb69a0bba25f86e5c265ab02415698c3/_pytest/_code/code.py#L19-L28
And I verified that the …

Change directory for py27 xdist-related envs

---

_pytest/mark.py
_pytest/python.py
changelog/2877.trivial

move responsibility for parameterset extraction into parameterset class

---

changelog/2893.doc
doc/en/proposals/parametrize_with_fixtures.rst

This change slightly modifies the language of the proposal document around use of fixture as parameters of pytest.mark.parametrize.
When looking for documentation around this, I very quickly scrolled through this document and landed on the last paragraph thinking it was documenting a real function. This change attempts to make it less likely for this to happen.

Clarify language of proposal for fixtures parameters

---

doc/en/parametrize.rst

I spent some time today figuring out why PR #2881 was not showing up
on `doc/parametrize`... then after some digging even on readthedocs
wondering if the last documentation build had failed, I realized the
docs I was looking for was in `doc/example/parametrize` instead.
The section that mentions this is very easy to miss, this makes it a
full fledged title and easier to find.

Make the "examples" section more prominent in the docs for parametrize

---

_pytest/fixtures.py
changelog/2910.trivial

switch a special case in scope node lookup to a general one

---

_pytest/fixtures.py

This implicit definition really tripped me while debugging #2127,
unfortunately hidden as it was in the middle of all the variable
declarations.
I think the explicit definition is much easier for the eyes and IDEs
to find.

Make SubRequest.addfinalizer an explicit method

---

setup.py

As discussed in pytest-dev/py#165

Pin py<1.5 as 1.5 drops py26 and py33 support

---

changelog/2922.trivial
setup.py

Prevent pip from installing pytest in unsupported Python versions

---

CHANGELOG.rst
changelog/2836.bug
changelog/2926.bugfix
doc/en/announce/index.rst
doc/en/announce/release-3.2.5.rst
setup.py

Going ahead and opening this PR as a possible solution to #2926.

Release 3.2.5

---

_pytest/deprecated.py
_pytest/python.py
changelog/2876.trivial
testing/deprecated_test.py

Deprecate metafunc.addcall

---

_pytest/capture.py
changelog/2934.feature
doc/en/capture.rst
testing/test_capture.py

`capsysbinary` works like `capsys` but produces bytes for `readouterr()`.
See #2934 #2923 #2925

Add capsysbinary fixture

---

doc/en/backwards-compatibility.rst

We should replace the wiki document to a link to this document now: https://github.com/pytest-dev/pytest/wiki/Deprecation-Roadmap
Rationale: the Wiki is not really used by us so I doubt users look at it, plus deprecation always involves code so it makes sense to update the document in the same PR.

Add Deprecation Roadmap to backward compatibility document

---

_pytest/assertion/rewrite.py
changelog/2939.bugfix
testing/test_assertion.py

Fix #2939
@hroncok, I managed use your reproducer to verify that the fix works:
```
{env36} X:\setuptools [master]>python -m pytest -k test_unicode_filename_in_sdist -v --tb=line
============================= test session starts =============================
platform win32 -- Python 3.6.0, pytest-3.2.5, py-1.5.2, pluggy-0.4.0 -- X:\setuptools\.env36\Scripts\python.exe
cachedir: .cache
rootdir: X:\setuptools, inifile: pytest.ini
plugins: virtualenv-1.2.11, shutil-1.2.11, flake8-0.9.1
collected 391 items
setuptools/tests/test_easy_install.py::TestEasyInstallTest::test_unicode_filename_in_sdist FAILED
================================== FAILURES ===================================
<frozen importlib._bootstrap>:960: RecursionError: maximum recursion depth exceeded
============================ …
```

Fix assertion rewrite to match module names correctly

---

_pytest/mark.py
changelog/2942.bugfix
testing/test_mark.py

Handle marks without description

---

_pytest/pytester.py
_pytest/terminal.py
changelog/2657.feature
doc/en/customize.rst
setup.py
testing/acceptance_test.py
testing/python/fixture.py
testing/python/metafunc.py
testing/python/setup_only.py
testing/test_assertion.py
testing/test_capture.py
testing/test_terminal.py

Still needs tests, docs and some cleanup, I'm opening this to gather some feedback.
This works in "normal" mode (including xdist), still needs work with `-v`.
Please see comments below.

Console progress output

---

doc/en/Makefile
doc/en/assert.rst
doc/en/builtin.rst
doc/en/cache.rst
doc/en/capture.rst
doc/en/doctest.rst
doc/en/example/markers.rst
doc/en/example/nonpython.rst
doc/en/example/parametrize.rst
doc/en/example/pythoncollection.rst
doc/en/example/reportingdemo.rst
doc/en/example/simple.rst
doc/en/example/special.rst
doc/en/fixture.rst
doc/en/getting-started.rst
doc/en/index.rst
doc/en/parametrize.rst
doc/en/skipping.rst
doc/en/tmpdir.rst
doc/en/unittest.rst
doc/en/warnings.rst

Using the default for non-atty terminals (80) so the new
progress indicator aligns correctly.

Remove gendoc normalization for '=' and '_' headers

---

CONTRIBUTING.rst
changelog/2949.trivial

Apparently, some time ago label was renamed from bug to "type:bug"
=====

Update github "bugs" link

---

CHANGELOG.rst
_pytest/assertion/rewrite.py
_pytest/config.py
_pytest/pytester.py
doc/en/announce/release-2.7.0.rst
doc/en/writing_plugins.rst
testing/test_assertion.py

This also fixes "can not" to "cannot" in the "Module already imported so
cannot be rewritten" assertion error.

Fix spelling: s/re-writ/rewrit/g

---

_pytest/warnings.py
changelog/2956.bugfix
testing/test_warnings.py

Only escape str-like arguments passed to warnings

---

CHANGELOG.rst

Noticed the word `err` in the release notes wasn't showing up correctly:
Turns out there was a non-breaking space in there.

replace non-breaking space with space

---

_pytest/runner.py
changelog/2957.bugfix
testing/acceptance_test.py

Always escape null bytes when setting PYTEST_CURRENT_TEST

---

AUTHORS
_pytest/config.py
changelog/2920.bugfix
changelog/2949.trivial
testing/test_config.py

fix issue #2920

---

_pytest/fixtures.py

Improve getscopeitem assertion message

---

_pytest/python.py
changelog/2976.trivial
testing/python/metafunc.py

I want to parametrize over factory functions, which I believe is a valid use-case. At the moment, the autogenerated id for the test name is then based on the argument name, plus counter to disambiguate (e.g. feature_factory0, feature_factory1, etc.). With this PR, the default behavior for functions will be the same as for classes: return the `__name__`. I think this is a more sensible default behaviour.
Semi-pseudocode example:
```
def factory_IP(T, Kernel): return do_something_with(T, Kernel)
def factory_FF(T, Kernel): return do_something_else(T, Kernel)
pytest.mark.parametrize('feature_factory,kernel_class', [
(factory_IP, Kernel1),
(factory_IP, Kernel2),
(factory_FF, Kernel1),
(factory_FF, Kernel3),
])
def test_my_model(feature_factory, kernel_class):
"""test code"""
```
As Kernel1, …

Extend _pytest.python._idval to return __name__ of functions as well

---

CHANGELOG.rst

Add CHANGELOG entry about pytest.fixture "params" being now immutable

---

_pytest/terminal.py
changelog/2971.bugfix
testing/test_terminal.py

This can easily happen with pytest-testmon.

Fix ZeroDivisionError with 0 collected tests

---

_pytest/terminal.py
changelog/2984.bugfix
testing/deprecated_test.py

Bring back TerminalReporter.writer as an alias to TerminalReporter._tw

---

_pytest/config.py
changelog/3004.bugfix
testing/deprecated_test.py

This is the older plugin before pytest-catchlog was around. Apparently there are
people still using it.
Fixes #3004

Also blacklist pytest-capturelog plugin

---

CHANGELOG.rst
changelog/2920.bugfix
changelog/2949.trivial
changelog/2956.bugfix
changelog/2957.bugfix
changelog/2963.doc
changelog/2971.bugfix
changelog/2984.bugfix
changelog/3004.bugfix
doc/en/announce/index.rst
doc/en/announce/release-3.3.1.rst

Builds: 
- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/311588611)
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.30)

Preparing release version 3.3.1

---

_pytest/pytester.py
changelog/3015.trivial
testing/acceptance_test.py
testing/test_conftest.py
testing/test_pdb.py
testing/test_pytester.py
tox.ini

Code cleanup done while working on another pull request and extracted here so it would not cloud up the original pull request.

Code cleanup

---

_pytest/assertion/rewrite.py
_pytest/pytester.py
changelog/2995.bugfix
testing/test_assertrewrite.py

See #2995.
-----
[already there]

Respect PYTEST_DONT_REWRITE for plugins too.

---

_pytest/hookspec.py
doc/en/writing_plugins.rst

Also mention which hook to use instead of the deprecated
pytest_cmdline_preparse
Fix #3022

Add param annotations and types to hookspec

---

AUTHORS
_pytest/main.py
changelog/2985.bugfix
testing/acceptance_test.py

The conversion of pyargs to paths is improved here:
- patch pkgutil to fix issue #2985 in python2.7.
Note that this might not fix the issue in python 3.0-3, as ``pkgutil.find_loader`` still worked like in python2.7 but as it is not supported I did not look into it.
I couldn't just use the backport of importlib, as it does not have importlib.find_loader or importlib.util.find_spec which is what is needed. The current (3.4+) pkgutil.find_loader uses importlib.util.find_spec under the hood, instead of parts of pkgutil.

Improve handling of pyargs

---

_pytest/logging.py

The logger parameter of catching_logs is not used anywhere. The main
motivation for removing the logger parameter is that it removes the
logger = logger or logging.getLogger(logger)
line. IMO there are too many occurrences of the string 'logg' ;)
Unless your change is a trivial or a documentation fix (e.g.,  a typo …

Remove logger parameter from catching_logs

---

_pytest/fixtures.py
changelog/2981.bugfix
testing/acceptance_test.py

The leak was caused by the (unused) `FixtureRequest._fixture_values`
cache.
This was introduced because the `partial` object (created to call
FixtureDef.finish() bound with the Request) is kept alive
through the entire session when a function-scoped fixture depends
on a session-scoped (or higher) fixture because of the nested
`addfinalizer` calls.
FixtureDef.finish() started receiving a request object in order to
obtain the proper hook proxy object (#2127), but this does not seem
useful at all in practice because `pytest_fixture_post_finalizer`
will be called with the `request` object of the moment the fixture value
was *created*, not the request object active when the fixture value
is being destroyed. We should probably deprecate/remove the request
parameter from …

Fix memory leak caused by fixture values never been garbage collected

---

testing/acceptance_test.py

`os.symlink` might fail on Windows because it requires a special policy
to allow normal users to create symlinks (argh).
This is not a problem on AppVeyor because the user logged in there has admin privileges, 
but will be surprising for Windows users running pytest's test suite in their computer.

Check if symlink does have privileges on Windows for test_cmdline_python_package_symlink

---

_pytest/pytester.py
changelog/3016.bugfix
testing/acceptance_test.py
testing/deprecated_test.py
testing/test_pytester.py

Internal pytest test suite improvements:
- cleaned up `Testdir` taking snapshots & restoring global Python state - extracted to new `CwdSnapshot`, `SysModulesSnapshot` & `SysPathsSnapshot` classes, each saving the state they are interested in on instantiation and restoring it in its `restore()` method
- fixed restoring Python state after in-process pytest runs
- now each in-process pytest run saves a snapshot of important global Python state and restores it after the test completes, including the list of loaded modules & the Python path settings
- previously only the loaded package data was getting restored, but that was also reverting any loaded package changes done in the test triggering the pytest runs, and not only those done by the pytest runs themselves
- updated acceptance tests …

Clean up state after in process pytest runs

---

_pytest/pytester.py
changelog/2784.bugfix

pytester: ignore files used to obtain current user metadata

---

AUTHORS
_pytest/skipping.py
changelog/3074.bugfix

Assume not skipped by mark if attribute missing

---

changelog/3092.doc
doc/en/projects.rst
doc/en/tmpdir.rst

- Requests URL using https instead of http
- Avoids unnecessary redirect of `*.rtfd.org` -> `*.readthedocs.io`
`*.rtfd.org` exists as a means for pasting short URLs, which doesn't much apply for links in documentation.
Unless your change is a trivial or a documentation fix (e.g.,  a typo or reword of a small section) …

Prefer https://*.readthedocs.io over http://*.rtfd.org

---

AUTHORS
setup.py

Ref pypa/pipenv#1229.
Setuptools added a new syntax in 36.2.1 for conditional requirements. This is recommended in the [documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies), and works better with dependency resolution tools that do not actually install the package.
I’m having trouble deciding whether this should be a bugfix or feature. Any suggestions?
---
Unless your change …

Add support for new environment marker usages

---

_pytest/python.py
tox.ini

The problem is described/discussed in #3061
Ideally this should be a temporary solution until we find a proper one
which gets rid of the warning

Ignore ImportWarnings regarding package resolution

---

_pytest/hookspec.py
_pytest/runner.py
changelog/3101.feature
doc/en/writing_plugins.rst
testing/test_runner.py

With the new hook I have been able to easily fix #3088 locally.
After this is merged, I will open the appropriate PR in `pytest-xdist` to trigger the new hook.
Fix #3101

Add new pytest_runtest_logfinish hook

---

doc/en/example/simple.rst

I have trouble using third party plugins in my frozen program and discovered 
that other people have experienced it as well:
https://mail.python.org/pipermail//pytest-dev/2015-June/003015.html
The problem is that the mechanism for plugin discovery used by pytest
(setupttools entry points) doesn't work with frozen executables so pytest
can't find any plugins. The solution seems to be to import the third party 
plugins explicitly as shown here:
https://mail.python.org/pipermail//pytest-dev/2015-June/003018.html
This is not mentioned anywhere in the documentaion.
* if you don't have an issue_id change it to the pr id …

Update Freezing pytest description in simple.rst

---

_pytest/hookspec.py
doc/en/writing_plugins.rst

Document bootstrap and initialization hooks

---

_pytest/terminal.py
changelog/3088.bugfix
testing/test_terminal.py

Fix progress report when tests fail during teardown

---

_pytest/config.py
_pytest/mark.py
changelog/2953.trivial
testing/test_mark.py

If we use expressions in -k option we get an error if this expression wrong of has python keywords:
> -k "foo or import"
`AttributeError: Python keyword 'import' not accepted in expressions passed to '-k'`
> -k "foo or"
`AttributeError: Wrong expression passed to '-k': foo or`

#2953 show a simple and easy error when keyword expressions trigger a syntax error

---

AUTHORS
_pytest/logging.py
changelog/3117.feature
doc/en/logging.rst
testing/logging/test_fixture.py

This is a fix for the problem seen here: https://github.com/eisensheng/pytest-catchlog/issues/37
I would like to validate some logs globally for the entire test suite. The problem is that caplog gives you one bucket of logs for the phase you're currently in, but I want to check the 'call' bucket when I'm in 'teardown'. This change makes it possible to access all the buckets from all the other.

Access captures logs in teardown

---

_pytest/hookspec.py
changelog/2423.doc

Document hooks (defined with historic=True) which cannot be used with hookwrapper=True

---

changelog/2022.bugfix
testing/test_pdb.py

use flush in order to avoid hanging on mac

---

AUTHORS
_pytest/cacheprovider.py
changelog/3138.feature
changelog/3150.feature
testing/test_cache.py

Hi all. This should deal with the issue discussed in #3138. I've basically done the following:
- Change the `v` folder to `pytest_values`
- Change the `cache/lastfailed` directory/file to just `lastfailed` inside the `pytest_values` directory
- Change the tests accordingly.
----
Unless your change is a trivial or a …

Change cache directory structure to include `pytest`

---

_pytest/mark.py
_pytest/python.py
changelog/2527.feature
doc/en/customize.rst
testing/python/metafunc.py
testing/test_mark.py

empty parameterset - enable opt to xfail

---

AUTHORS
_pytest/fixtures.py
changelog/3107.feature

I've precached a map of fixtures to items that allows us to avoid iterating over the entire list of items for each fixture.  It also reduces the number of lists created.  On my project with a few thousand parametrized fixtures, test collection now takes ~2 seconds instead of ~20 seconds.

Optimize reorder_items in fixtures.py

---

AUTHORS
_pytest/junitxml.py
changelog/3130.feature
doc/en/usage.rst
testing/test_junitxml.py

Allows insertion of new xml attributes on `<testcase>` elements, or overwriting their default values.

implement #3130 - add record_xml_attribute fixture

---

_pytest/logging.py
changelog/3142.feature
testing/logging/test_formatter.py

I propose to prettify the default output of the live logs a bit by colorizing the levelnames. 
A screenshot paints a thousand words:

Colorize live-log levelnames

---

_pytest/mark.py
_pytest/python.py
changelog/3166.trivial

_From the authors that brought you the controversial #3159..._
Change the naming of `for_parameterize` to `for_parametrize` in order to comply with the current convention on naming. This should make the whole codebase as of now have the `parametrize` spelling.
🐍 
_Now in theaters close to your location_

Switch `for_parameterize` to `for_parametrize`

---

testing/test_recwarn.py

In previous Python versions, the list of warnings when `pytest.warns` fails appears like:
```
... list of emitted warnings is: [UserWarning('user',)].
```
In Python 3.7 apparently the string representation has been improved to:
```
... list of emitted warnings is: [UserWarning('user')].
```
Fix #3011
I would recommend to leave py37 in the "allowed failures" section for now, at least until py37 releases its first beta.

Fix test for py37

---

changelog/985.bugfix
testing/test_pdb.py

skip failing pdb/doctest test on mac

---

_pytest/debugging.py
changelog/1810.bugfix

If we fail to import doctest.UnexpectedException during postmortem, fail quietly

---

.travis.yml
setup.py

Python 3.7.0b1 has been released:
https://www.python.org/downloads/release/python-370b1/
Fix #3168

Support py37 officially

---

AUTHORS
_pytest/logging.py
changelog/3189.feature
testing/logging/test_reporting.py

Additionally handle logstart and logfinish hooks

---

_pytest/fixtures.py
changelog/3161.bugfix
testing/python/fixture.py

https://github.com/pytest-dev/pytest/pull/3108 introduced a regression in test ordering that resulted in excess fixture creation.  This should fix that and order tests as they were before PR 3108.

Fix ordering of tests to minimize fixture creating

---

_pytest/logging.py
changelog/3190.feature
testing/logging/test_reporting.py

Expose `log_cli` as a CLI parser option.

---

_pytest/terminal.py
changelog/1478.feature
changelog/1478.trivial
doc/en/capture.rst
testing/test_terminal.py

Task #1478 
How it works:
We have a test:
```
def test_one():
print('This is stdout!')
assert 0
```
Run pytest:
```
pytest --tb=short
```
We got this:
```
tests/test_one.py F                                                                                                                                                                     [100%]
=================================================================================== short test summary info ===================================================================================
FAIL tests/test_one.py::test_one
========================================================================================== FAILURES =========================================================================================== …
```

#1478 Added --no-stdout option

---

_pytest/python_api.py
changelog/3202.doc.rst
changelog/3202.trivial.rst

I've been using pytest for years and never noticed either of these until this week!

Add Sphinx parameter docs for `match` and `message` args to `pytest.raises()`

---

_pytest/compat.py
changelog/3206.bugfix.rst
testing/python/integration.py

If pypi `mock` package is installed and imported at any time during test run, it's impossible to use Python 3 `@unittest.mock.patch(...)` decorator. Mock object argument is not recognized by pytest with error like this:
```
@unittest.mock.patch("os.path.abspath")
def test_hello(self, abspath):
E       fixture 'abspath' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```
It's often not possible to go with `unittest.mock` only, as pypi `mock` can be implicitly pulled by one of project dependencies. In my case, it's `moto` package.

Fix mock patchings detection when both mock and unittest.mock are present

---

AUTHORS
_pytest/debugging.py
changelog/3052.bugfix
testing/test_pdb.py

Added printing of captured stdout before entering pdb

---

_pytest/logging.py
testing/logging/test_reporting.py

This is a fix for the feature PR https://github.com/pytest-dev/pytest/pull/3189 where we'd always get 2 new lines between each log message on the finish section.

Fix issue where a new line was always written for the live log finish section

---

_pytest/logging.py
changelog/3184.bugfix
testing/logging/test_reporting.py

Don't traceback on unkown sections.

---

_pytest/terminal.py
changelog/3213.feature
testing/test_cacheprovider.py
testing/test_terminal.py

Show deselection count before tests are executed

---

_pytest/doctest.py
changelog/985.bugfix
testing/test_pdb.py

... to avoid losing reference to stdout. Fixes #985.
This patch implements the [change proposed](https://github.com/pytest-dev/pytest/issues/985#issuecomment-357541238), but encapsulates the workaround and documents it with a docstring.

Disable output capturing in doctest

---

_pytest/fixtures.py
changelog/3228.trivial.rst
setup.py

Update minimal attrs library to v17.4.0

---

.travis.yml
HOWTORELEASE.rst
changelog/3060.trivial.rst
tasks/generate.py
tasks/requirements.txt

Implement deploying to PyPI by pushing a tag

---

_pytest/python_api.py
changelog/3247.bugfix.rst
testing/python/approx.py

Fixes #3247
Added python_api.ApproxDecimal to handle with Decimal numbers.

Fix approx default tolerances for Decimal

---

AUTHORS
_pytest/deprecated.py
_pytest/junitxml.py
_pytest/nodes.py
_pytest/runner.py
changelog/2770.feature
changelog/2770.removal.rst
doc/en/builtin.rst
doc/en/example/simple.rst
doc/en/usage.rst
testing/test_junitxml.py

This PR changes the ``record_xml_property`` function with a more generic ``record_property`` that is compatible with xdist, markers, and any other reporter other than the JUnit reporter.
The implementation adds a list of ``user_properties`` to the item object, and can be modified anytime after its creation during the test lifecycle. When the test has finished, the user properties are passed to the TestReport object, which is shared with any reporter, and in particular serialized and sent to the master in xdist, and then the reporter are free to plot this properties as they want.
Currently, to maintain the functionality, the JUnit adds those properties to the XML report.
In addition, this allows markers to modify (add, delete) user properties as desired. This is documented in this PR and a …

Make record_xml_property generic and compatible with xdist and markers.

---

doc/en/writing_plugins.rst

`getplugin()` is deprecated in favor of `get_plugin()`.
https://github.com/pytest-dev/pytest/blob/dd97c940359079fd874795a731d54d1abb7d4c8e/_pytest/config.py#L261

Correct docs to config.pluginmanager.get_plugin()

---

AUTHORS
_pytest/fixtures.py
changelog/3249.bugfix.rst
testing/python/fixture.py

Hi there! Apologies in advance for the long-winded description!
I was working on a talk for a local Python meetup on reference cycles in Python and noticed that a reference cycle was generated from within pytest which was causing test failures in my example code.
Here's the fixture I was running:
```python
import pytest
import gc
@pytest.fixture(autouse=True)
def garbage_detect(request):
gc.set_debug(0)
gc.collect()
gc.set_debug(gc.DEBUG_SAVEALL)
yield
gc.collect()
garbage_expected = request.node.get_marker('garbage')
if not garbage_expected:
assert len(gc.garbage) == 0
```
The fixture is checking that garbage is not generated by the code under test. I was hitting test failures due to a reference cycle generated by the insertion of the `request` fixture into `garbage_detect`.
Here's an …

Fix PseudoFixtureDef reference cycle.

---

_pytest/terminal.py
changelog/3203.bugfix.rst
changelog/3203.trivial
testing/test_terminal.py

Fixes #3203 
Removed progress statistic when capture option is 'no'

#3203 Remove progress when no-capture

---

AUTHORS
_pytest/doctest.py
changelog/3149.feature
doc/en/doctest.rst
testing/test_doctest.py

Here is try two of the attempt to fix #3149.  This is targeting the features branch instead of master.  The pdb timeout issue should be resolved and the feature is turned on only when the --doctest-continue-on-failure is set.  Otherwise the behavior should be the same as the original.  The code is somewhat more streamlined as well.

Continue on doctest failure

---

_pytest/mark/evaluate.py
changelog/3236.trivial.rst
testing/test_skipping.py

Per https://github.com/pytest-dev/pytest/issues/3236 I've gone ahead and added the ability to use platform in pytest.mark statements.

#3236 Use platform module in pytest.mark

---

_pytest/hookspec.py
_pytest/skipping.py
_pytest/terminal.py
changelog/3255.feature.rst
testing/test_skipping.py

Currently when using `-ra` the "short test summary info" is shown *before* the full list of tracebacks and errors:
```
.tmp\test_fail.py::test FAILED                       [ 50%]
.tmp\test_fail.py::test_s SKIPPED                    [100%]
================= short test summary info =================
FAIL .tmp\test_fail.py::test
SKIP [1] C:\pytest\.tmp\test_fail.py:8: skipping
======================== FAILURES =========================
__________________________ test ___________________________
def test():
>       assert 0
E       assert 0
.tmp\test_fail.py:4: AssertionError
=========== 1 failed, 1 skipped in 0.04 seconds ===========
```
When you have a large test suite and a lot of tests fail, the short summary test info easily gets lost amidst the huge number of lines printed by all the …

Show "short test summary info" after tracebacks and warnings

---

_pytest/config.py
changelog/3260.bugfix
changelog/3260.bugfix.rst
testing/test_config.py

Fixes #3260 
Bugfix: When you pass option "-c custom_config.cfg" section [tool:pytest] is now parses. And print warning if there is [pytest] section.

#3260 fix pytest section

---

_pytest/python_api.py
changelog/3265.trivial.rst
setup.py

As I was searching through the code for a completely different purpose, I stumbled across this pattern, which I've seen many times before:
```
if variable is a singleton -> do one thing
otherwise if it's an iterable -> do the thing across each item
```
This common pattern is the reason I created [always_iterable](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.always_iterable), as it allows looping over the items even if there's just one.
Using this technique, along with [filterfalse](https://docs.python.org/3/library/itertools.html#itertools.filterfalse), the code is more concise, less nested, and in my opinion, more directly conveys the intention. One slightly awkward aspect is that the for loop is abruptly terminated if it fails the isclass test, but that was …

Consolidate behavior by using filterfalse and always_iterable

---

_pytest/config.py
_pytest/deprecated.py
changelog/3268.trivial
testing/deprecated_test.py

Added warning when "[pytest]" section is used in a ".cfg" file passed with "-c"

---

_pytest/cacheprovider.py
changelog/3034.feature
doc/en/cache.rst
testing/test_cacheprovider.py

Fixes #3034
Added new option --new-first
How it works:
Create different test files:
tests
|- test_one.py
\- test_two.py
Every file contains two tests:
```
def test_1():
assert 1
def test_2():
assert 1
```
run command 
```
pytest tests -v
```
result:
```
tests/test_one.py::test_1 PASSED
tests/test_one.py::test_2 PASSED
tests/test_two.py::test_1 PASSED
tests/test_two.py::test_2 PASSED
```
run command 
```
pytest tests -v --nf
```
result:
```
tests/test_two.py::test_1 PASSED
tests/test_two.py::test_2 PASSED
tests/test_one.py::test_1 PASSED
tests/test_one.py::test_2 PASSED
```
Order changed to modifyed files first
Add new test to test_two.py file and then modify test_one.py file
run command 
```
pytest tests -v --nf
```
result:
```
tests/test_two.py::test_3 PASSED
tests/test_one.py::test_1 …
```

#3034 Added new option "--new-first"

---

_pytest/main.py
changelog/3241.bugfix.rst

As suggested in #3241 `exists` should rather be `isdir`. 
If we want a test here, pleas let me know. I actually tried to write a test against this but failed miserably - would anyone outline how to let `exist` fail but `isdir` pass in this specific case?

Use `isdir` instead of `exists`

---

_pytest/python_api.py
changelog/3265.trivial.rst
setup.py

This was merged on master but really should be on features: we should not
add new dependencies in bug-fix releases
This reverts commits:
* cfaf3600c1d9ea2b45d9b801a47379304fd7e455
* 14a9b1ec838fc1b2bb530458757c0bb9a67f164d

Revert introduction of more_itertools on master

---

changelog/3245.trivial.rst
tox.ini

Resolve the test failures that are caused by calling `pytest` against the root directory due to the inclusion of running tests in the doc directory.

3245: Add doc to norecursedirs in tox.ini

---

_pytest/monkeypatch.py

Typo in example, os.getcwd does not take any parameter.

---

_pytest/main.py
_pytest/mark/structures.py
_pytest/nodes.py
_pytest/terminal.py
changelog/3291.feature
changelog/3291.trivial.rst
testing/test_resultlog.py

@nicoddemus i had some local failures wrt progress display on xdist, if that shows up on travis as well please have a look

move some code and make nodeid computed early

---

AUTHORS
_pytest/logging.py
changelog/3297.bugfix.rst
testing/logging/test_fixture.py

Fix #3297 where ``caplog.clear()`` did not clear text, just records.  
Fix by @thisch that re-installs a new ``StringIO`` on the handler as suggested in https://stackoverflow.com/questions/4330812/how-do-i-clear-a-stringio-object#4330829
+ Actually work delegated to a new `reset()` method on the handler, used also on `caplog` construction .
+ Added TC demonstrating failure.

Fix #3297 where caplog.clear() did not clear text, just records

---

_pytest/terminal.py
changelog/3296.feature
changelog/3296.trivial

based on https://github.com/pytest-dev/pytest/issues/3294#issuecomment-372190084
we really shouldnt have N options we post mortem hack together to determine verbosity
this change starts by unifying the data, we still need to handle deprecation/removal of config.quiet

unify cli verbosity handling

---

_pytest/config.py
changelog/3304.trivial

remove CmdOptions since we can use argparse.Namespace()

---

_pytest/capture.py
changelog/2370.bugfix.rst
testing/test_capture.py

Suppress ``IOError`` when closing the temporary file used for capturing streams in Python 2.7

---

_pytest/capture.py
_pytest/logging.py
changelog/3314.bugfix.rst
testing/test_capture.py

Allow DontReadFromInput to produce iterator without error.

---

_pytest/python_api.py
changelog/3312.feature
testing/python/approx.py

Add support for `pytest.approx` comparisons between array and scalar

---

_pytest/cacheprovider.py
changelog/3139.feature
doc/en/cache.rst
testing/test_cacheprovider.py

implemented --last-failed-no-failures

---

_pytest/config.py
_pytest/deprecated.py
changelog/3084.removal
doc/en/plugins.rst
doc/en/writing_plugins.rst
testing/deprecated_test.py

deprecate pytest_plugins in non-top-level conftest

---

_pytest/fixtures.py
changelog/2405.feature.rst
doc/en/fixture.rst
testing/acceptance_test.py
testing/python/fixture.py

This is a stab at fixing #2405. 
This fixes the reproducible example posted by @jaraco:
```python
import pytest
data = {}
@pytest.fixture(scope='module')
def clean_data():
data.clear()
pytestmark = pytest.mark.usefixtures('clean_data')
class TestDataValues:
@pytest.fixture(scope='class', autouse=True)
def add_data(cls):
data.update(value=True)
def test_value(self):
assert data.get('value')
```
And also this one which I used to debug the problem:
```python
import pytest
data = {}
@pytest.fixture(scope='module')
def clean_data():
data.clear()
@pytest.fixture(autouse=True)
def add_data():
data.update(value=True)
@pytest.mark.usefixtures('clean_data')
def test_value():
assert data.get('value')
```
All tests pass (which is encouraging), but given that this might alter the order of evaluation …

Instantiate fixtures by scope order in test function requests

---

AUTHORS
_pytest/logging.py
changelog/3307.feature.rst
testing/logging/test_reporting.py

When doing log capturing we need to temporary change the level of the root logger to be at least
of the log level that the handler used for log capturing has (log_level), so that we 'll be able to capture such  logs.
If root logger level has smaller numeric value than `log_level` parameter we should not enforce root logger level to `log_level` because we might miss important logs from root logger gathered by other handlers.

logging.py: Don't change log level of the root logger to bigger numeric value

---

_pytest/python_api.py
changelog/3348.bugfix.rst
testing/python/raises.py
testing/test_recwarn.py

Per https://github.com/pytest-dev/pytest/issues/3348, I've gone ahead and updated pytest.raises to raise a TypeError if an invalid keyword argument is passed.
In addition, I fixed an issue of a test case in pytest that was passing an invalid keyword argument to pytest.raises.

3348: raise error on unknown arguments to raises

---

_pytest/mark/__init__.py
doc/en/example/reportingdemo.rst
doc/en/fixture.rst
doc/en/warnings.rst

Add docs about using pytest.param in parametrized fixtures

---

_pytest/assertion/util.py
_pytest/compat.py
_pytest/mark/structures.py
changelog/3339.trivial

This fixes the deprecation warnings from Python 3.7 related to importing abcs from the collections module, mentioned in issue #3339 
I couldn't fix the same for using the deprecated ``imp`` module, there's a bit too much wizardry going on with it in _pytest/assertion/rewrite.py ...

change collections.abc import to fix deprecation warnings on python 3.7

---

_pytest/hookspec.py
doc/en/reference.rst

And TIL once upon a time there was a `Session.main()` function. 😛

Add reference docs for pytest_sessionstart/finish and update their docstrings

---

CHANGELOG.rst
setup.py
tox.ini

Correct the requirement `more_itertools` to `more-itertools`.  Pip does not differentiate between `-` and `_` but Conda does.

Use correct spelling for "more-itertools"

---

doc/en/writing_plugins.rst

I think the current comment `will show "setting up"` here will be wrong by default (the print output will be captured). Would it be better for this sample code to say no-capture so the print statement actually shows up when users run it?

no-capture in sample code demo'ing plugin

---

doc/en/development_guide.rst

The descriptions have been moved directly to GitHub's new label description
slot.

Remove label descriptions from development guide

---

AUTHORS
_pytest/python_api.py
changelog/3372.bugfix.rst
testing/python/raises.py

Add bugfix and test for #3372: Exception classes may have a type that looks iterable which caused problems with ``pytest.raises``.
Unfortunately, I wasn't able to use ``base_type`` as proposed by Ronny: ``pytest.raises`` is passed an exception **class** and I didn't find a way around calling ``issubclass``.
Only tested in py3.6.
----
Not a regular contributer, so I hope everything is up to speed and in accordance with your guidelines.

Fix issue #3372

---

_pytest/deprecated.py
_pytest/fixtures.py
_pytest/mark/evaluate.py
_pytest/mark/structures.py
_pytest/nodes.py
_pytest/python.py
_pytest/skipping.py
_pytest/warnings.py
changelog/3317.feature
doc/en/example/markers.rst
doc/en/example/simple.rst
doc/en/mark.rst
doc/en/reference.rst
doc/en/usage.rst
doc/en/warnings.rst
testing/python/fixture.py
testing/python/metafunc.py
testing/test_mark.py

as part of this i will deprecate markinfo,
there will be much to change about the internals, 
but the find_markers api that from now on will work across all node level instead of just function will sort out some of the biggest issues

introduce a distinct searchable non-broken storage for markers

---

doc/en/mark.rst

This will help make users more understanding if their code breaks under the
new implementation.

Add the list of issues fixed by the new marker implementation to the docs

---

setup.py

According to:
https://packaging.python.org/tutorials/distributing-packages/#project-urls
Those URLs are displayed in the project page in Warehouse (new PyPI).
From [this article](https://lwn.net/SubscriberLink/751458/81b2759e7025d6b9/):
> ... and support for multiple project URLs (e.g., for a homepage and a repo) on a project's PyPI page.

Add additional project urls to setup.py

---

tox.ini

Also took the opportunity to:
* Use more cores for py*-xdist environments
* Update freeze test to use py36

Simplify tox to avoid repetition

---

_pytest/runner.py
changelog/2798.bugfix.rst
testing/acceptance_test.py
testing/test_runner.py

Fixes #2798. Not entirely because I was not able to remove the cyclic references which seem to be caused by the traceback objects being kept around; those cycles will be eventually be claimed by the garbage collector, at least (with the previous code that was not even possible).

Reset reference to failed test frame before each test executes

---

_pytest/assertion/rewrite.py
changelog/3008.bugfix.rst
changelog/3008.trivial.rst
setup.py
testing/test_assertrewrite.py

This uses of the `atomicwrites` library.
This is very hard to create a reliable test for.
Fix #3008

Attempt to solve race-condition which corrupts .pyc files on Windows

---

_pytest/helpconfig.py
_pytest/python.py
changelog/3398.trivial.rst
doc/en/builtin.rst
doc/en/fixture.rst
doc/en/getting-started.rst
doc/en/test/plugin/terminal.rst

I've added the corresponding text in a number of places, basically the ones that a text search for `--fixtures` brought up.
I didn't change the printout of `FixtureLookupError`, that would IMO be too much spamming and would have required changes to the tests.

Mention omission of fixtures with leading '_', closes #3398

---

_pytest/monkeypatch.py
changelog/3290.bugfix
changelog/3290.feature
doc/en/monkeypatch.rst
testing/test_monkeypatch.py

Fixes #3290.
```
To handle #2180, we could just import open and other builtins explicitly at the module level of rewrite.py to shield us from users tampering with it.
```
I added to `rewrite.py` (not in this PR)
```
from builtins import open
```
but it has no effect :(

#3290 improve monkeypatch

---

_pytest/logging.py
changelog/3406.doc.rst
doc/en/builtin.rst

Updated the caplog fixture documentation per the bug found in issue #3406 .

Fix typo in caplog fixture documentation: Issue #3406

---

README.rst
changelog/3431.trivial.rst
doc/en/_templates/links.html
doc/en/announce/release-2.3.5.rst
doc/en/announce/release-2.4.0.rst
doc/en/development_guide.rst
doc/en/example/nonpython.rst
doc/en/example/parametrize.rst
doc/en/example/simple.rst
doc/en/faq.rst
doc/en/fixture.rst
doc/en/getting-started.rst
doc/en/goodpractices.rst
doc/en/links.inc
doc/en/plugins.rst
doc/en/projects.rst
doc/en/proposals/parametrize_with_fixtures.rst
doc/en/test/plugin/cov.rst
doc/en/test/plugin/oejskit.rst
doc/en/test/plugin/xdist.rst
doc/en/unittest.rst
doc/en/usage.rst
doc/en/writing_plugins.rst

For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html

Update all pypi.python.org URLs to pypi.org

---

changelog/3317.feature
doc/en/contents.rst
doc/en/mark.rst

Also changed the title in the docs because the previous title had
the same level as the title, making it appear in a separate entry
in `contents.rst`

Improve changelog note about markers

---

_pytest/debugging.py
_pytest/runner.py
changelog/3299.feature.rst
doc/en/usage.rst
testing/test_pdb.py

--pdb treats KeyboardInterrupt as exception

---

_pytest/mark/legacy.py
changelog/3441.bugfix
testing/test_mark.py

Fix #3441 let mark expressions be populated from the modern marker storage

---

_pytest/assertion/util.py
changelog/3443.bugfix.rst
testing/test_assertion.py

Fix #3443
Here's how it looks:
```
def test_stuff():
a = u'\r\n'
>       assert a == u'\n'
E       AssertionError: assert '\r\n' == '\n'
E         Strings contain only whitespace, escaping them using repr()
E         - '\r\n'
E         ?  --
E         + '\n'
.tmp\test_rn.py:4: AssertionError
```

Escape whitespace only strings when diffing them on failed assertions

---

testing/python/fixture.py

This test sometimes fails on AppVeyor with:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.0 = <listiterator object at 0x0549DC50>
leaked_types = sum(1 for _ in gc.garbage
>                   if 'PseudoFixtureDef' in str(_))
E   UnicodeEncodeError: 'ascii' codec can't encode character u'\u263a' in position 23: ordinal not in range(128)
test_request_garbage.py:19: UnicodeEncodeError
====================== 1 passed, 1 error in 1.39 seconds ======================
```
Use our internal "safe_repr" function to handle Encode errors: who knows
what objects are in garbage after all.
Example of a recent failure: https://ci.appveyor.com/project/pytestbot/pytest/build/1.0.4327/job/yfunwupo1bo3rvdc

Attempt to fix flaky test on Python 2

---

CHANGELOG.rst
_pytest/_code/source.py
_pytest/capture.py
_pytest/compat.py
_pytest/doctest.py
_pytest/fixtures.py
_pytest/main.py
_pytest/mark/structures.py
_pytest/outcomes.py
_pytest/python.py
doc/en/announce/release-2.3.4.rst
doc/en/announce/release-2.6.1.rst
doc/en/example/parametrize.rst
doc/en/goodpractices.rst
doc/en/reference.rst
testing/code/test_excinfo.py
testing/python/fixture.py
testing/test_assertion.py
testing/test_capture.py
testing/test_conftest.py
testing/test_nose.py

Spelling and grammar fixes

---

testing/python/metafunc.py
tox.ini

* Increase hypothesis deadline
The current deadline being reached is pretty close to the new default that will come out in
future hypothesis versions, which is generating a deprecation error
on CI.
Using a loose deadline because CI boxes are not reliable in how much
CPU power they have available
* Use a more recent hypothesis version on CI

Attempt to fix CI problems related to Hypothesis

---

_pytest/config.py
changelog/3487.trivial.rst

`pluggy` is deprecating the `implprefix` argument in the next major
release so implement this detection in our derived plugin manager.
Relates to pytest-dev/pluggy#145

Detect `pytest_` prefixed hooks

---

AUTHORS
_pytest/compat.py
_pytest/python_api.py
changelog/3497.trivial.rst

Related to https://github.com/pytest-dev/pytest/issues/3339
Fixes a DeprecationWarning on Python 3.7
Adds Mapping to compat

Import Mapping and Sequence from compat in python_api::approx

---

_pytest/fixtures.py
_pytest/python.py
_pytest/unittest.py
changelog/3498.bugfix
testing/test_unittest.py

fix #3498 - correctly consider marks on unittest classes

---

_pytest/junitxml.py
changelog/3491.bugfix.rst
testing/test_junitxml.py

Before this commit. stdout and stderr were being logged twice in the junitxml report.
This change fixes the issue so that stdout and stderr are now only logged once:
```
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="1" tests="1" time="0.062">
<testcase classname="test" file="test.py" line="3" name="test_fail" time="0.0">
<skipped message="expected test failure"></skipped>
<system-out>XFAIL This is stdout
</system-out>
<system-err>XFAIL This is stderr
</system-err>
</testcase>
</testsuite>
```

3491 - Fixed a bug where stdout and stderr were logged twice by junitxml for xfail tests.

---

doc/en/goodpractices.rst
doc/en/nose.rst

This is a mini-mini fix, so no changelog entry or anything else is necessary, I guess.

Fix tox spelling (all lower case).

---

.pre-commit-config.yaml
README.rst
doc/en/bash-completion.rst
doc/en/capture.rst
doc/en/example/attic.rst
doc/en/example/simple.rst
doc/en/fixture.rst
doc/en/goodpractices.rst
doc/en/index.rst
doc/en/logging.rst
doc/en/mark.rst
doc/en/monkeypatch.rst
doc/en/proposals/parametrize_with_fixtures.rst
doc/en/reference.rst
doc/en/skipping.rst
doc/en/tmpdir.rst
doc/en/usage.rst
doc/en/warnings.rst
doc/en/writing_plugins.rst

Hi friends, I made a terrific (terrible? terrifying?) thing.
First commit is manual changes:
- tabs to spaces
- needed to add some `...`s in a few places to make valid syntax
Second commit is automated!
Using the new thing I made today: https://github.com/asottile/blacken-docs
Heavily inspired by #3525.  See also ambv/black#292, ambv/black#294.  CC @blueyed

blacken docs

---

changelog/3530.trivial.rst
testing/test_assertrewrite.py

Fixes https://github.com/pytest-dev/pytest/issues/3530

Module docstrings in 3.7 are not part of Module node anymore

---

changelog/3461.doc.rst
doc/en/fixture.rst

Close https://github.com/pytest-dev/pytest/issues/3461
Not sure if this is the best place to put this, but it seemed somewhat reasonable.

Add factory fixture example to documentation.

---

doc/en/reference.rst

Small typo `xdisst` -> `xdist` in the documentation for the `PYTEST_PLUGINS` env variable.
I thought this was too small to warrant an issue + changelog, but I'll be happy to do those if requested.

Fix typo in plugin list example

---

setup.py

Remove setup.py test now that it's broken

---

changelog/3549.doc.rst
doc/en/mark.rst

Also remove Mark api from mark.rst: Feels out of place in there, plus the reference documentation already contains the reference API to all mark-related classes.
Fix #3459

Add documentation blurb for --strict

---

changelog/3554.bugfix
src/_pytest/runner.py
testing/test_runner.py

As discussed in #3560, this should not go to master because this breaks
the API.
Reverts commits:
1a7dcd73cf38f07ccaa4bd19c476750a1c678cbc
198e993969ddf9ecb137150760565fccc773f11c
Follow up of https://github.com/pytest-dev/pytest/pull/3560#pullrequestreview-127388483

Revert change of Callinfo.result default value

---

testing/python/fixture.py

~~Related to #3564~~
~~At least avoid breaking AppVeyor on Windows until we can get to the bottom of why this test is flaky.~~
Fix #3564
Initially I marked the test as flaky, but taking another look at the traceback I think I found a proper fix.

Attempt to fix test_request_garbage on Windows

---

CONTRIBUTING.rst

Small improvements to the CONTRIBUTORS guide

Improve contributing instructions regarding black/linting

---

doc/en/assert.rst

Fixing three spaces instead of four in assert.rst

Fix three spaces instead of four in docs

---

changelog/3555.bugfix.rst
src/_pytest/mark/structures.py
src/_pytest/nodes.py
testing/python/integration.py
testing/test_mark.py
tox.ini

fix addmarker - extract mark from markdecorator

---

AUTHORS
changelog/3579.feature.rst
src/_pytest/logging.py
testing/logging/test_fixture.py

This is a PR for issue #3579 per @nicoddemus suggestion.
I added the `versionadded` marker for 3.7, assuming that it would not be in before that; I can correct that if needed.
It passes all the Travis checks for me except sending to coveralls, presumably because I don't have an account setup with coveralls.

Add `messages` property to `caplog` fixture.

---

testing/example_scripts/README.rst
testing/example_scripts/issue_519.py
tox.ini

this pr simply adds a script thats demonstrating issue #519
as far as i can tell by now it shows that the issue is no more
this is also a starting point for adding verbatim acceptance tests to the folder tree in order to execute py.test directly on those (in order to get direct feedback and better debugging)
opinions by @nicoddemus and @The-Compiler appreciated

add example scripts for issue #519

---

src/_pytest/python_api.py
src/_pytest/recwarn.py

Currently I get greeted on each test run with this:
```
py36 runtests: commands[0] | coverage run --parallel -m pytest
/Users/hynek/Projects/attrs/.tox/py36/lib/python3.6/site.py:165: DeprecationWarning: 'U' mode is deprecated
f = open(fullname, "rU")
/Users/hynek/Projects/attrs/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
/Users/hynek/Projects/attrs/.tox/py36/lib/python3.6/site-packages/_pytest/recwarn.py:118: DeprecationWarning: invalid escape sequence \d
"""
/Users/hynek/Projects/attrs/.tox/py36/lib/python3.6/site-packages/_pytest/python_api.py:604: DeprecationWarning: invalid escape sequence \d
```
The imp warning is probably …

Fix 2 DeprecationWarnings about invalid escape seq

---

changelog/3583.bugfix.rst
src/_pytest/doctest.py
testing/test_doctest.py

This fixes #3583.  This fix was suggested by Stack Overflow user phd in
<https://stackoverflow.com/a/50863820/744178>.

Fix encoding error with `print` statements in doctests

---

tox.ini

This is how `tox-dev/tox` invokes this and can often reduce the number of round trips for a PR by showing the changes in the output.

Use --show-diff-on-failure for pre-commit CI invocation

---

changelog/3598.trivial.rst
src/_pytest/python.py

I noticed this while taking a look at the parametrized code.

Remove unused attribute and parameter in CallSpec2

---

.travis.yml
appveyor.yml

Travis and AppVeyor were executing "py35-freeze", which does not actually
exist in tox.ini.

Fix reference to py36-freeze in travis and appveyor

---

changelog/3609.trivial.rst
src/_pytest/mark/structures.py

[`functools.reduce` was added in python2.6 to aid in porting](https://docs.python.org/2/library/functools.html#functools.reduce)

Silence usage of `reduce` warning in python 2

---

AUTHORS
testing/test_mark.py

From Python 3.3 is mock part of python standard library in unittest namespace

Prefer unittest.mock before mock

---

appveyor.yml
setup.py
src/_pytest/cacheprovider.py
src/_pytest/compat.py
src/_pytest/paths.py
testing/test_cacheprovider.py

warning logging got broken by detanglement from config

[WIP] port cache plugin internals to pathlib

---

doc/en/announce/release-2.4.0.rst
doc/en/fixture.rst

For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html

Update pypi.python.org URLs to pypi.org

---

AUTHORS
changelog/3593.bugfix.rst
src/_pytest/python_api.py
testing/python/approx.py

If the user pass as a expected value a numpy array created like
numpy.array(5); it will creates an array with one element without shape,
when used with approx it will raise an error
'TypeError: iteration over a 0-d array'

Bug fix #3593 - approx repr in a 0-d numpy array

---

changelog/3623.feature.rst
doc/en/example/reportingdemo.rst
doc/en/writing_plugins.rst
src/_pytest/experiments.py
src/_pytest/pytester.py
testing/acceptance_test.py
testing/example_scripts/conftest_usageerror/conftest.py
testing/example_scripts/issue88_initial_file_multinodes/conftest.py
testing/example_scripts/issue88_initial_file_multinodes/test_hello.py
testing/examples/test_issue519.py
tox.ini

this starts to make use of the example dir in testing

Pytester runexamples

---

appveyor.yml

We don't deploy anything on tags with AppVeyor, we use Travis instead, so we
might as well save resources

Skip AppVeyor builds on tag pushes

---

src/_pytest/reports.py
src/_pytest/runner.py
testing/test_junitxml.py
testing/test_runner.py

this pr brings builtin serialization and replay/record of reports

move report classes to own file to prepare for serialisazion

---

AUTHORS
changelog/2220.bugfix.rst
src/_pytest/fixtures.py
src/_pytest/python.py
testing/python/collect.py

A fix for https://github.com/pytest-dev/pytest/issues/2220.

Make test parametrization override indirect fixtures

---

changelog/3631.bugfix.rst
src/_pytest/mark/structures.py
testing/test_mark.py

fix #3631 - don't store legacy markinfo when its impossible

---

src/_pytest/monkeypatch.py

`delenv` is incorrectly documented; yes, this is trivial.

Fix monkeypatch doc

---

.pre-commit-config.yaml
CHANGELOG.rst
doc/en/announce/release-2.9.0.rst
doc/en/example/markers.rst
doc/en/goodpractices.rst
doc/en/mark.rst

I know I make this mistake all the time, let's see if pre-commit can't help prevent it :)
if this pygrep hook works well for pytest, I'm eventually planning to collect up a bunch of them and put them in a more centralized place.  I have a few that I've copied from project-to-project myself and feel it would better to share!

Correct code blocks in docs

---

changelog/2319.trivial.rst
src/_pytest/_code/source.py
testing/python/raises.py
testing/test_assertrewrite.py
testing/test_capture.py

Remove obsolete __future__ imports

---

src/_pytest/compat.py
src/_pytest/config/__init__.py
testing/test_assertrewrite.py
testing/test_pytester.py

This was partially automated with https://github.com/asottile/yesqa
_with a few caveats_:
- it was run under python2 (chosen arbitrarily, when run under python3 other
things were changed)
- I used `git checkout -p` to revert the removal of `noqa` comments from
`cmp()` lines.

Remove some extraneous `# noqa` comments

---

changelog/2220.bugfix.rst
changelog/3576.feature.rst
changelog/3610.feature.rst
changelog/3623.feature.rst
changelog/README.rst
changelog/_template.rst

Some small tweaks on the text I noticed while reviewing the changelog for the upcoming 3.7 release.
Also pushed a tweak to our changelog rendering: now it writes the issue link first:
```
- `#3623 <https://github.com/pytest-dev/pytest/issues/3623>`_: Introduce ``pytester.copy_example`` as helper to do acceptance tests against examples from the project.
```
I want to be able to use a new feature from towncrier 18.6 which no longer wraps lines automatically, which allows us to use multi-line entries, including coding samples which can be very handy for new features. The issue link at the end was a problem because it did appear right after the line in a multi-line string.
Here's a local draft I did of dummy issues using this feature:
```rst
- `#3665 …
```

Small tweaks to the changelog entries

---

src/_pytest/pytester.py
testing/example_scripts/fixtures/fill_fixtures/test_conftest_funcargs_only_available_in_subdir/sub1/conftest.py
testing/example_scripts/fixtures/fill_fixtures/test_conftest_funcargs_only_available_in_subdir/sub1/test_in_sub1.py
testing/example_scripts/fixtures/fill_fixtures/test_conftest_funcargs_only_available_in_subdir/sub2/conftest.py
testing/example_scripts/fixtures/fill_fixtures/test_conftest_funcargs_only_available_in_subdir/sub2/test_in_sub2.py
testing/example_scripts/fixtures/fill_fixtures/test_extend_fixture_conftest_conftest/conftest.py
testing/example_scripts/fixtures/fill_fixtures/test_extend_fixture_conftest_conftest/pkg/conftest.py
testing/example_scripts/fixtures/fill_fixtures/test_extend_fixture_conftest_conftest/pkg/test_spam.py
testing/example_scripts/fixtures/fill_fixtures/test_extend_fixture_conftest_module/conftest.py
testing/example_scripts/fixtures/fill_fixtures/test_extend_fixture_conftest_module/test_extend_fixture_conftest_module.py
testing/example_scripts/fixtures/fill_fixtures/test_extend_fixture_module_class.py
testing/example_scripts/fixtures/fill_fixtures/test_funcarg_basic.py
testing/example_scripts/fixtures/fill_fixtures/test_funcarg_lookup_classlevel.py
testing/example_scripts/fixtures/fill_fixtures/test_funcarg_lookup_modulelevel.py
testing/example_scripts/fixtures/fill_fixtures/test_funcarg_lookupfails.py
testing/python/fixture.py

this is a initial move of various things to example scripts as well as a removal of formatting strings to test files
the main benefit of having the actual test examples in text files is that we can run them directly and debug pytest directly
it also eases adding extracted examples of breakages to the testsuite, just copy in a folder an write a minimal testcase just taking and running it

[RFC] Fixturetest examples - move test contents to use example scripts for contents

---

src/_pytest/mark/structures.py
src/_pytest/python.py

Extract the parametrize() block of code into methods for better
readability and add some docs
Suggestions about the name of the functions and the docs are welcome!

Refactor parametrize() code for readability

---

.github/labels.toml
doc/en/development_guide.rst

Using: https://github.com/hackebrot/labels
This will make it easier to manage labels in bulk than using the GitHub's interface. The `labels.toml` file being committed was fetch from the current labels unchanged.

Manage GH labels using the new 'labels' tool

---

changelog/3635.trivial.rst
src/_pytest/mark/structures.py

Fixes #3635.
------
Checklist:

Replace broken type annotations with type comments

---

AUTHORS
changelog/980.bugfix.rst
src/_pytest/_code/code.py
src/_pytest/nodes.py
testing/code/test_excinfo.py

This PR aims at fixing #980.
I am not sure if this counts as _trivial_ change or not -- I've updated the `AUTHORS` file but have no problem with removing myself from there in case this work is not sufficient :)

Fix truncated locals in verbose mode

---

doc/en/fixture.rst

Fix a few typos.
Didn't do the following. Don't think it's necessary for these small changes.

Fix fixture.rst typos & grammar

---

doc/en/mark.rst

Fix minor typos and grammar in the documentation.

Fix mark.rst typos & grammar

---

src/_pytest/fixtures.py

Because it seems #3705 will take longer than I would like, as commented in https://github.com/pytest-dev/pytest/pull/3705#pullrequestreview-139292328 here are some commits with small refactorings so we can get this in.

Small refactorings

---

changelog/3661.removal.rst
src/_pytest/compat.py
src/_pytest/deprecated.py
src/_pytest/fixtures.py
src/_pytest/pytester.py
testing/deprecated_test.py
testing/example_scripts/tmpdir/tmpdir_fixture.py
testing/python/fixture.py
testing/python/metafunc.py
testing/test_assertion.py
testing/test_conftest.py
testing/test_tmpdir.py

The 3 first commits are small refactorings that I felt doing while implementing the actual task, so I recommend reading the commits separately.
I had to use a "wrapper" around the original fixture function to issue a warning, and one difficulty I had was to make this work reliably in Python 2 because `@itertools.wraps` doesn't preserve the signature. I believe this is fine though, because we probably will drop Python 2 by the time we release `4.0`.
Surprisingly, we had a few tests in our test suite which did call fixture functions directly, I just fixed those while keeping the same semantics.
Fix #3661

 Deprecate calling fixture functions directly
