pytest-dev/pytest

tox.ini
please don't merge yet - checking first
=> pass coveralls env

README.rst
The old one from pypip.in seems to always be broken as of late
=> Use pypi version badge from shields.io

README.rst
All badges then will have a similar look
=> Use shields.io badge for coveralls

setup.cfg
the just released devpi-client-2.3.0 reads from setup.cfg FYI.
=> configure a plain "devpi upload" to create sdist and universal wheel

CHANGELOG, _pytest/assertion/rewrite.py, testing/test_assertrewrite.py
=> Add support for PEP302 get_data API

CHANGELOG, _pytest/doctest.py, testing/test_doctest.py
=> Consider session fixtures for doctest docstrings in modules

CHANGELOG, _pytest/mark.py, testing/test_mark.py
=> Make sure marks in subclasses don't change marks in superclasses

appveyor.yml, appveyor/install.ps1, appveyor/run_with_env.cmd
Porting appveyor support from `master` into `pytest-2.7`.
=> Appveyor py 2.7

.travis.yml, CHANGELOG, _pytest/assertion/newinterpret.py, _pytest/assertion/rewrite.py, _pytest/main.py, tox.ini
Porting #744 fixes to `pytest-2.7` branch.
=> Py35fix port

CHANGELOG, _pytest/python.py, testing/test_unittest.py
=> Fix autouse fixtures defined in a TestCase subclass

CHANGELOG, _pytest/config.py, _pytest/genscript.py, _pytest/helpconfig.py, _pytest/mark.py, _pytest/pastebin.py, _pytest/pdb.py, _pytest/python.py, _pytest/terminal.py, testing/python/fixture.py
=> Consider --color option in more places which deal with TerminalWriters

testing/test_recwarn.py
=> Move WarningsChecker import in test to a local import to workaround flakes issue

_pytest/config.py, testing/acceptance_test.py
=> Reintroduce hasplugin to PytestPluginManager

_pytest/terminal.py, testing/test_terminal.py
* include versions
* don't double print a distribution
=> Adapt plugin name printing

doc/en/mark.rst
=> Add note that using marks on fixtures is not supported

AUTHORS, _pytest/terminal.py, testing/test_skipping.py
Fixes #960 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
=> Added fix for specifying every option for reporting using 'a'

_pytest/hookspec.py
=> Add warning about implementing pytest_addoption in conftest files

doc/en/goodpractises.rst
Is this all that is needed to close Issue 766?
=> Remove references to distutils as per Issue 766.

_pytest/python.py
Fixed #1027 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
=> Added minor documentation change in python.py

_pytest/cacheprovider.py
=> Add docstring to cache fixture

doc/en/getting-started.rst
I found pytest to be very sweet, however I spent many unnecessary hours trying to understand how to use it. For example, something as simple as how to run multiple tests was not clear. Yes, the text was there, but buried at the end of a long paragraph at the end of a long section. I had to visit other websites until I understood this.
I think how to run multiple tests is important enough to have its own section, which I what I added to the doc. I hope you folks agree.
=> Documentation clarification

_pytest/cacheprovider.py
=> fix docstring for cache fixture regarding ``/`` on keys

_pytest/python.py
=> Add a note about usage of the context manager

CHANGELOG, _pytest/config.py, testing/test_config.py
=> tests of (and fixes for) Config.fromdictargs (2)

doc/en/unittest.rst
=> Add link to unittest2pytest

doc/en/example/pythoncollection.rst
=> Write docs on ignore cli option

_pytest/terminal.py, testing/test_terminal.py
Thanks to `dude-x` in IRC, who catched this a few minutes after the PR was merged :wink:
=> Fix spelling mistake in #1207.

CHANGELOG, _pytest/pastebin.py, testing/test_pastebin.py
Supersedes #1202 
* Decode `urlopen` response from `bytes`.
* Add CHANGELOG entry
Thanks @mehdy for the initial patch! :smile:
=> Pastebin py3

CHANGELOG, _pytest/pastebin.py, testing/test_pastebin.py
=> Fix pastebin when captured output contains non-ascii characters

doc/en/skipping.rst
=> Fix inconsistency in skipif example

CHANGELOG, _pytest/recwarn.py, testing/test_recwarn.py
=> Fix deprecated_call regression introduced in 2.8.4

AUTHORS, CHANGELOG, _pytest/doctest.py, doc/en/doctest.rst, testing/test_doctest.py
=> Multiple --doctest-glob arguments

CHANGELOG, _pytest/monkeypatch.py
=> Make monkeypatch calls O(1)

CHANGELOG, _pytest/doctest.py, doc/en/doctest.rst, testing/test_doctest.py
As requested in #1287
CC @jaraco
=> Doctest bytes literals

.travis.yml, CHANGELOG.rst, CONTRIBUTING.rst, MANIFEST.in, appveyor.yml, doc/en/changelog.rst, tox.ini
=> Changelog now in rst format (2.9.0 and onward) and add rst-lint check

_pytest/cacheprovider.py
Closed #1344 so I can specify the `features` branch as a base.
=> Add explicit flag names for failed first and last failed

doc/en/announce/sprint-funding-2016.txt
a draft so we go for funding.  What is missing:
- deadline for providing funding.  Mid march?
- which platform to use?  I'd think indiegogo but am open to other suggestions. We can also do a paypal, bitcoin address and i mention the invoicing to merlinux possibility  i.e. we don't need to just use one platform.  I plan to contact some companies where i had previous testing related consultings/trainings with.
=> sprint funding draft

doc/en/_templates/layout.html, doc/en/_templates/links.html
i deployed a generated variant to http://ronnypfannschmidt.de/pytest-build/_build/html/ for viewing
=> add links for the funding campaign in the header and sidebar

CHANGELOG.rst, _pytest/assertion/util.py, testing/test_assertion.py
=> Fix formatting utf-8 error explanation

doc/en/_templates/layout.html
i choose a color instead of inverting, 
since restructuring the css to readable links on inverted color quickly ate too much time
=> give the founding header contrast

CHANGELOG.rst, _pytest/skipping.py, testing/python/collect.py, testing/test_skipping.py
Thank goodness I noticed this right away... oh my this would be an embarrassing bug! :grin:
=> Fix bug in strict xfail: test was not being actually called

CHANGELOG.rst, _pytest/terminal.py, testing/test_terminal.py
=> Display collect progress only when in a terminal

CONTRIBUTING.rst
Move sections around (from easiest to hardest) and added howto for repository transfers
#1282
=> Contributions to CONTRIBUTING.rst

doc/en/contents.rst
=> Add reference to some builtin fixtures in "contents"

_pytest/skipping.py, testing/python/collect.py, testing/test_skipping.py
cc @The-Compiler @MichaelAquilina
Fix #1412
=> Fix skip/xfail markers in parametrized arguments

doc/en/announce/sprint2016.rst
=> Add company name sprint doc

_pytest/hookspec.py
As discussed in #1427
cc @philandstuff @hpk42
=> Mention that pytest_addoption may be used from conftest files

doc/en/writing_plugins.rst
As discussed in the mailing list and in pypa/warehouse#542.
=> Mention Pytest::Framework PyPI classifier on docs

extra/get_issues.py
This is a small helper script that someone uses to print all open issues to the console. Since it was easy to adapt I simply did it.
Possibly the script is no longer needed and could be deleted instead...? It was last updated in Feb 2015.
Anyway now it works with GitHub. Simply execute to try it out.
Since this is only an *internal* script no CHANGELOG entry is required.
=> Adapt get_issues.py script for GitHub (instead of Bitbucket)

doc/en/announce/sprint2016.rst
=> Update sprint2016.rst :)

AUTHORS, _pytest/junitxml.py, testing/test_junitxml.py
Fixes https://github.com/pytest-dev/pytest/issues/1549
test_junitxml.py has been updated to ensure test counting tests pass
=> Fixes Issue 1549

tox.ini
As discussed in #1554
* https://bitbucket.org/hpk42/tox/issues/332/
* pypa/pip#3667
=> Move comment in tox.ini due to recent bug in pip

CONTRIBUTING.rst
=> CONTRIBUTING.rst: spelling fixes

CHANGELOG.rst
=> fix changelog links

testing/python/fixture.py
Add test for the changed assertion as suggested by @The-Compiler
=> Add test for change in pull request #1631

CHANGELOG.rst
I accidentally opened a branch in this repo, whoops. Whatever, will clean up after it's merged.
=> Add changelog entry for #1564

AUTHORS, doc/en/new-docs/user/commandlineuseful.rst
=> Added documentation with examples to the useline commands

doc/en/fixture.rst
I wouldn't have even attempted what I did to cause #1688 if this had
been there.
=> Document the interaction of autouse scopes

CHANGELOG.rst
=> Docs: De-404 links in changelog

doc/en/contents.rst, doc/en/nose.rst
Also add nose doc to the root toctree
Closes #1716
cc @pchampin
=> Document limitations for yield-tests in nose

CHANGELOG.rst, _pytest/assertion/__init__.py, _pytest/assertion/rewrite.py, _pytest/config.py, _pytest/pytester.py, testing/test_assertion.py, testing/test_assertrewrite.py, testing/test_config.py
=> Rewrite plugins

doc/en/writing_plugins.rst
=> Document the re-writing of plugins

_pytest/pytester.py
This PR accumulates match/nomatch output from `LineMatcher` into an internal stream and only displays this text if the matching fails. I think this makes it easier to see why a test using `testdir` failed because:
1. The output appears as part of the error, next to the `fnmatch_lines*` call.
2. It doesn't get mixed up with the rest of the output (this is specially a problem if during the test someone else also writes to `stderr`).
3. It should look better in CI reports such as Jenkins (I think, didn't test it).
Could others try out the patch and give their opinions? 
Here's the output from a failing test:
```
============================= test session starts =============================
platform win32 -- Python 3.5.0, pytest-2.10.0.dev1, py-1.4.31, pluggy-0.3.1
rootdir: X:\pytest, …
```
=> Log LineMatcher output in a stream instead of stderr

AUTHORS, CHANGELOG.rst, _pytest/capture.py, _pytest/junitxml.py, _pytest/monkeypatch.py, _pytest/python.py, _pytest/tmpdir.py
=> Uppercase first word in docstrings. Change to an imperative form.

_pytest/main.py
@nicoddemus I missed to change the help line, sorry :( Here's the fix.
=> fix keep-duplicates help line.

_pytest/__init__.py
For a long time now we've considering the next version to be 3.0.0
=> Set version to 3.0.0.dev1

_pytest/fixtures.py, _pytest/python.py, testing/python/fixture.py
=> Strip invocation-scope suffix when displaying fixture lookup error

doc/en/assert.rst, doc/en/cache.rst, doc/en/capture.rst, doc/en/example/markers.rst, doc/en/example/multipython.py, doc/en/example/parametrize.rst, doc/en/example/simple.rst
After more fixes on `features`, I think this PR contains possibly the final regendocs for 3.0. :grin:
=> Regendoc take 2

CHANGELOG.rst, _pytest/config.py, doc/en/customize.rst, testing/test_collection.py, testing/test_config.py
=> Fix rootdir common ancestor

AUTHORS, CHANGELOG.rst, _pytest/compat.py, _pytest/fixtures.py, _pytest/junitxml.py, _pytest/main.py, _pytest/python.py, _pytest/skipping.py, testing/python/fixture.py, testing/python/metafunc.py, testing/test_config.py, testing/test_junitxml.py, testing/test_skipping.py, testing/test_unittest.py, tox.ini
Preparing for the 3.0 release! :smile: :boom: 
Also fixed #1815 while at it.
=> Merge master into features

doc/en/builtin.rst, doc/en/example/pythoncollection.rst, doc/en/example/reportingdemo.rst, doc/en/example/simple.rst
=> Run regendoc for 3.0 release

CHANGELOG.rst
It's in https://github.com/pytest-dev/pytest/pull/1826/files#diff-de0a9b67ffe2874a076b5fdb15bad484R288 already.
=> Remove duplicate entry for #717 in CHANGELOG

_pytest/runner.py
Ref: https://github.com/pytest-dev/pytest/pull/1823#commitcomment-18714490
=> minor: s/no pkg_resources/pkg_resources/

AUTHORS
=> Remove duplicated name

doc/en/writing_plugins.rst
=> Fix documentation

doc/en/monkeypatch.rst
=> Fix reference docs for monkeypatch

doc/en/parametrize.rst
=> Remove duplicated for Metafunc members on docs

doc/en/unittest.rst
better doc for #1890, as suggested in #1932 (https://github.com/pytest-dev/pytest/issues/1932#issuecomment-247765597).
=> better doc for #1890 based on #1932

AUTHORS, CHANGELOG.rst, _pytest/fixtures.py, _pytest/python.py, testing/python/fixture.py, testing/python/metafunc.py
Might be a bit friendlier for newbs and typos.
=> Explain a bad scope value to the user

appveyor.yml
=> Disable pypy on AppVeyor until #1963 gets fixed

tox.ini
=> Use hypothesis >= 3.5.2

_pytest/python.py, testing/test_skipping.py
=> Pytest skip message

doc/en/talks.rst
Only 4 spots left currently, but hey, why not add that instead of a training which is already over :wink:
=> Update "Next Open Trainings"

CHANGELOG.rst, _pytest/config.py, testing/test_config.py
=> Show an error if --confcutdir is not a valid directory

CHANGELOG.rst, _pytest/python.py, testing/python/approx.py
=> Fix error in approx's repr with complex numbers

tox.ini
Related to pypa/setuptools#861
=> Remove setuptools pin now that upstream has been fixed

README.rst, doc/en/index.rst
`inc` reads better, also fixed the line separators so they have the same size
=> Use "inc" instead of "func" in the snipped on README

CHANGELOG.rst, doc/en/fixture.rst
=> Improved description of functionality for Issue #687

doc/en/goodpractices.rst
=> Fix minor typo

doc/en/fixture.rst
=> Also update yield teardown for Issue #687

doc/en/fixture.rst
=> Fix fixture/parametrize override example.

.travis.yml, AUTHORS, setup.py, tox.ini
=> Add py36 classifier & Add py37 to travis

CHANGELOG.rst, _pytest/python.py
=> Replace 'raise StopIteration' usages in the code by 'return's in accordance to PEP-479

doc/en/assert.rst
=> assert.rst: typographical correction

doc/en/usage.rst
=> Clarify that record_xml_property is experimental, not junitxml

CHANGELOG.rst, _pytest/config.py, testing/acceptance_test.py
Added unicode (in py2) as valid type for specifying plugins
=> added option to unicode plugin name

doc/en/assert.rst
=> Document PYTEST_DONT_REWRITE

README.rst
Adds a badge with the version of the pytest package in @conda-forge, which I'm a maintainer and update every time we make a new release.
(fixed the indentation of the other badges which were slightly incorrect)
=> Add badge for anaconda package version

doc/en/parametrize.rst
- Fix a few small grammar mistakes
- Rewrite a few sentences to make them shorter and easier to read
- [ x] Target: for bug or doc fixes, target `master`; for new features, target `features`;
- [x ] Make sure to include one or more tests for your change;
- [ x] Add yourself to `AUTHORS`;
- [ x] Add a new entry to `CHANGELOG.rst`
* The pytest team likes to have people to acknowledged in the `CHANGELOG`, so please add a thank note to …
=> Clarify opening paragraph of parameterization docs

doc/en/talks.rst
Leaving the sidebar as an example for in the future.
=> Remove past training

_pytest/config.py
While working on another issue, I performed some refactoring on the code in order to better understand it and to add documentation. I believe these changes add value to the project, so I'm proposing them here for inclusion.
I tried to make each change stable and minimally invasive with a useful description, so you may find it easier to review the changes in order rather than as a whole. These changes are entirely about readability and code structure and are intended to cause no behavioral change.
I won't be offended if you choose not to adopt these changes, though of course I would be delighted if you do.
=> Refactor config

CHANGELOG.rst, doc/en/announce/index.rst, doc/en/announce/release-3.1.0.rst, doc/en/cache.rst, doc/en/example/parametrize.rst, doc/en/example/simple.rst, doc/en/talks.rst, doc/en/unittest.rst, doc/en/warnings.rst
Builds:
* [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/234185151)
* [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.6)
=> Release 3.1

changelog/810.doc, doc/en/skipping.rst
Also did a general review of the document to improve the flow
Fix #810
=> Make it clear that pytest.xfail stops the test

CHANGELOG.rst, changelog/2434.bugfix, changelog/2440.bugfix, changelog/2464.bugfix, changelog/2469.bugfix, changelog/2474.trivial, changelog/2475.bugfix, changelog/2486.bugfix, changelog/2493.doc, changelog/2499.trivial, doc/en/announce/index.rst, doc/en/announce/release-3.1.3.rst, doc/en/assert.rst, doc/en/doctest.rst, doc/en/example/markers.rst, doc/en/example/parametrize.rst, doc/en/fixture.rst, doc/en/getting-started.rst, doc/en/index.rst, doc/en/tmpdir.rst, doc/en/warnings.rst, tasks/requirements.txt
Builds:
* [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/249818859)  [![Build status](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest.svg?branch=master)](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest)
* [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.11)  [![Build Status](https://ci.appveyor.com/api/projects/status/v0ls4w1qniyd32yu?svg=true)](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest)
This also fixes #2509
=> Release 3.1.3

doc/en/_templates/globaltoc.html
It is important enough that it should be easier to find
=> Add a link to our backwards compatibility policy to our side-bar

_pytest/python.py, changelog/2546.trivial
=> [RFC] Improve error message for CollectError with skip/skipif

CONTRIBUTING.rst
=> Revisit CONTRIBUTING.rst

_pytest/main.py, _pytest/pytester.py
@nicoddemus those are some relatively small changes, im wondering if they warrant a note (i#d use a non-printed one but we did away wit that)
=> small code cleanups

CHANGELOG.rst, changelog/2579.bugfix, changelog/2591.bugfix, changelog/2626.doc, changelog/2644.bugfix, changelog/2666.bugfix, doc/en/announce/index.rst, doc/en/announce/release-3.2.1.rst, doc/en/example/simple.rst
- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/262421454)
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.20)
=> Release 3.2.1

.travis.yml, appveyor.yml
=> Use tox release candidates in CI

_pytest/deprecated.py, changelog/2739.trivial, doc/en/usage.rst, testing/deprecated_test.py
=> Improve user guidance regarding ``--resultlog`` deprecation

_pytest/pytester.py, changelog/2738.bugfix, testing/test_pytester.py
=> Encode utf-8 byte strings in pytester's makefile

AUTHORS, changelog/2604.doc, doc/en/example/markers.rst
Fix https://github.com/pytest-dev/pytest/issues/2604
=> [DOC] Add examples for mark.with_args

CHANGELOG.rst, changelog/2604.doc, changelog/2653.doc, changelog/2681.bugfix, changelog/2691.trivial, changelog/2699.bugfix, changelog/2707.bugfix, changelog/2721.trivial, changelog/2731.bugfix, changelog/2739.trivial, doc/en/announce/index.rst, doc/en/announce/release-3.2.2.rst, doc/en/example/markers.rst, doc/en/example/reportingdemo.rst
- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/272684020)
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.22)
=> Preparing release version 3.2.2

changelog/911.doc, doc/en/pythonpath.rst, doc/en/usage.rst
See [request for documentation](https://github.com/pytest-dev/pytest/issues/911#issuecomment-332883333). Does this look as desired @nicoddemus ?
=> Add documentation about python -m pytest invocation.

_pytest/runner.py
=> remove unused _pytest.runner.NodeInfo class

CHANGELOG.rst, changelog/1505.doc, changelog/1997.doc, changelog/2658.doc, changelog/2775.bugfix, changelog/2819.bugfix, changelog/2856.bugfix, changelog/2882.bugfix, changelog/2893.doc, changelog/2903.doc, changelog/538.doc, changelog/911.doc, doc/en/announce/index.rst, doc/en/announce/release-3.2.4.rst, doc/en/example/pythoncollection.rst, doc/en/example/reportingdemo.rst, doc/en/skipping.rst
- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/301590688)
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.27)
=> Preparing release version 3.2.4

doc/en/writing_plugins.rst, setup.py
So we get the round of bug-fixes in 0.5.
=> Update pluggy pin to 0.5.*

changelog/2963.doc, doc/en/projects.rst
The plugin has since moved to pytest-dev
=> Fix broken link to project

changelog/3021.trivial, tasks/generate.py
Minor code tweaks extracted to not pollute other pull requests.
=> Code cleanup

_pytest/logging.py
logging_using_handler is only used in catching_logs. Therefore it makes
sense to remove one of the many (nested) context managers from the logging
plugin.
=> Integrate logging_using_handler into catching_logs

_pytest/logging.py
I've accidentally pushed two WIP commits to pytest master. Sry about that. This PR reverts those two commits.
=> Revert accidental push

CONTRIBUTING.rst
This is just a proposal.  Feel free to discuss the intent or wording or add whatever thoughts you might have.
=> [proposal] Add section about how you become a committer

testing/code/test_excinfo.py, testing/test_runner.py, testing/test_skipping.py
Commit automated with https://github.com/asottile/yesqa
=> Remove unnecessary `# noqa` comments.

CHANGELOG.rst, changelog/2784.bugfix, changelog/2981.bugfix, changelog/2985.bugfix, changelog/2995.bugfix, changelog/3001.doc, changelog/3015.trivial, changelog/3018.trivial, changelog/3021.trivial, doc/en/announce/index.rst, doc/en/announce/release-3.3.2.rst, doc/en/example/simple.rst
- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/321542122)
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.32)
=> Preparing release version 3.3.2

CHANGELOG.rst
The PR was changed after I wrote the blurb and I did not update it. Apologies. Thanks for getting the release out, that's very helpful!
=> Fix issue 2985 blurb in changelog

_pytest/_code/code.py, _pytest/_code/source.py, changelog/3067.trivial, doc/en/example/assertion/failure_demo.py, doc/en/example/reportingdemo.rst, extra/get_issues.py, testing/acceptance_test.py, testing/code/test_excinfo.py, testing/code/test_source.py, testing/python/collect.py, testing/python/metafunc.py, testing/test_argcomplete.py, testing/test_assertrewrite.py, testing/test_cache.py, testing/test_collection.py, testing/test_config.py, testing/test_conftest.py, testing/test_parseopt.py, testing/test_pluginmanager.py, testing/test_recwarn.py, testing/test_runner.py, testing/test_terminal.py
=> Replace py.std with stdlib imports

_pytest/hookspec.py, changelog/2698.doc
=> Clarify a possible confusion when using pytest_fixture_setup with fixture functions that return None

_pytest/_argcomplete.py, _pytest/assertion/__init__.py, _pytest/cacheprovider.py, _pytest/capture.py, _pytest/config.py, _pytest/debugging.py, _pytest/fixtures.py, _pytest/main.py, _pytest/mark.py, _pytest/monkeypatch.py, _pytest/pytester.py, _pytest/runner.py, _pytest/terminal.py, _pytest/tmpdir.py, changelog/2147.removal, testing/acceptance_test.py, testing/python/collect.py, testing/python/fixture.py, testing/python/metafunc.py, testing/test_capture.py, testing/test_pytester.py, testing/test_terminal.py
=> All classes now subclass object for better py3 compatibility

doc/en/writing_plugins.rst
=> Mention outcome.force_result() and add link to pluggy's docs

changelog/3246.trival.rst, testing/test_terminal.py
=> remove addcall in the terminal tests

testing/test_pdb.py
Implement the test from #3210, which was not merged yet, because the PR was
abandoned in favor or #3234.
=> Add pdb test with disabled logging plugin

doc/en/getting-started.rst
=> Fix broken links in getting-started

_pytest/logging.py, _pytest/main.py, _pytest/python_api.py, changelog/3209.doc.rst, changelog/3241.bugfix.rst, changelog/3265.trivial.rst, doc/en/plugins.rst, setup.py
Follow-up of #3278, reintroducing `more_itertools` and merging with latest master.
=> Re-Introduce more_itertools

changelog/3308.trivial.rst, doc/en/usage.rst
https://github.com/pytest-dev/pytest/issues/3308
=> issue #3308: fix example in documentation

README.rst
Just noticed that conda-forge has its own badge so let's use that
=> Use conda-forge badge instead of anaconda's

_pytest/freeze_support.py, _pytest/pytester.py, doc/en/cache.rst, doc/en/example/pythoncollection.rst
=> #dropthedot

AUTHORS, changelog/3303.doc.rst, doc/en/conf.py
=> change doc copyright year to range and auto update year

doc/en/logging.rst
=> fix typo in docs

CHANGELOG.rst
=> Correct issue number in changelog

changelog/3545.trivial.rst, src/_pytest/terminal.py, testing/test_terminal.py
- display the location first
- display hint about --fulltrace in parenthesis
=> Improve display of hint about --fulltrace with KeyboardInterrupt

changelog/3567.trivial.rst, doc/en/mark.rst
=> Fix typo in documentation

AUTHORS, changelog/3569.bugfix.rst, src/_pytest/runner.py, testing/test_runner.py
=> Continue to call finalizers in the stack when a finalizer raises an exception

changelog/3525.trivial.rst, doc/en/fixture.rst
Updating fixture.rst parens type in a small section.
Connected to #3525
=> 3525 typo fixture docs

pyproject.toml
this makes the file valid and prepares for https://github.com/pypa/pip/issues/5416 and https://github.com/pypa/pip/pull/5512
=> add build-system section to pyproject.toml

changelog/3630.bugfix.rst, src/_pytest/logging.py, testing/logging/test_reporting.py
Fixes #3630
- **(not applicable)** Target the `features` branch for new features and removals/deprecations.
- **(not applicable)** Include documentation when adding new features.
- **(trivial change)** Add yourself to `AUTHORS` in alphabetical order;
=> Fixes #3630

changelog/3653.trivial.rst, src/_pytest/mark/structures.py
=> Switch to new API

.travis.yml
Borrowed from https://github.com/tox-dev/tox/pull/877
Thanks for the tip @gaborbernat 👍
=> Skip deploy stage entirely unless we have a tag

changelog/742.bugfix.rst, src/_pytest/pytester.py, testing/test_pytester.py
Resolves #742 
I was triaging old issues and I though, hey, I can fix this one!
let me know if I should rebase this on `features` :)
=> Use -mpytest when invoking pytest in pytester

.travis.yml, appveyor.yml
=> Test with Python 3.7 on Travis and AppVeyor

changelog/3745.bugfix, src/_pytest/cacheprovider.py, testing/test_cacheprovider.py
=> fix #3745 - display absolute cache_dir if necessary

changelog/3746.doc.rst, src/_pytest/python.py
=> Unhide documentation for metafunc.config

doc/en/talks.rst
Thanks for the remainder @pfctdayelise!
=> Add pytest Quick Start Guide to the books section in the docs

.travis.yml
Otherwise it will fail as there's no coverage data to combine/publish.
=> Disable coverage during deployment stage

CHANGELOG.rst, changelog/3251.feture.rst
*Someone* made a typo when creating the CHANGELOG entry. 😅
=> Amend CHANGELOG with missing #3251

doc/en/getting-started.rst
=> Include Python 3.7 on getting started doc

doc/en/example/simple.rst, doc/en/reference.rst
Stumbled with that way more than I thought 😄 
Fixes #4062 .
=> Add pytest.freeze_includes() to reference

doc/en/announce/release-3.6.3.rst, doc/en/announce/release-3.7.3.rst
Fixing my name in annoucements.
=> Renamed Victor to full name.

testing/test_pytester.py
=> Correct timing in test_pytester.test_testdir_run_with_timeout()

.github/PULL_REQUEST_TEMPLATE.md
=> Use full link to changelog's README in PR template

setup.cfg
=> Fix metadata url quotes

changelog/4177.bugfix.rst, pyproject.toml, setup.py
=> fix #4177 - pin setuptools>=40.0

doc/en/fixture.rst
Changed to pypi address of lib.
Fix #4254
=> changed address to pytest-data-dir

changelog/4272.trivial.rst, src/_pytest/cacheprovider.py
=> cacheprovider: display cachedir also in non-verbose mode if customized

tox.ini
Ref: https://github.com/pytest-dev/pytest/pull/4415#discussion_r234452144
Found by @asottile.
=> tox.ini: remove additionally missed mock deps

doc/en/capture.rst, doc/en/example/markers.rst, doc/en/example/special.rst, doc/en/fixture.rst, doc/en/funcarg_compare.rst, doc/en/getting-started.rst, doc/en/writing_plugins.rst, extra/get_issues.py, testing/acceptance_test.py, testing/python/fixture.py, testing/python/integration.py, testing/python/raises.py, testing/test_capture.py, testing/test_junitxml.py, testing/test_mark.py, testing/test_nose.py, testing/test_runner_xunit.py, testing/test_terminal.py, testing/test_unittest.py
=> Fix formatting of print() calls

doc/en/requirements.txt
I'm still not quite sure what I fixed, but this seemed to make rtfd work in my fork 🤷‍♂️
=> Bump pygments-pytest

scripts/appveyor-retry.cmd, scripts/upload-coverage.bat
=> [skip travis] Use retry script on AppVeyor

doc/en/mark.rst
=> Rectified typo

AUTHORS, changelog/4483.feature.rst, doc/en/usage.rst, src/_pytest/junitxml.py, testing/test_junitxml.py
Implements https://github.com/pytest-dev/pytest/issues/4483
Please review and let me know if docs/changelog update is required for this simple change.
attn @MuchkoM
=> Add --junittime=call option

testing/test_junitxml.py
=> Use mocking to make test_junit_duration_report deterministic

doc/en/goodpractices.rst
Fix #4625
@dogweather would appreciate your feedback as well. 👍
=> Mention PYTHONPATH semantics in goodpractices.rst

.github/config.yml
Part of the configuration necessary for https://github.com/apps/rtd-helper
=> Add rtd-bot configuration file

src/_pytest/_code/code.py, src/_pytest/assertion/rewrite.py, src/_pytest/fixtures.py, src/_pytest/junitxml.py, src/_pytest/python.py, src/_pytest/reports.py, src/_pytest/resultlog.py, src/_pytest/terminal.py, testing/python/metafunc.py, testing/test_resultlog.py, testing/test_runner.py, testing/test_session.py, testing/test_terminal.py
- I wrote a thing: https://github.com/asottile/dead
- wanted to try it out, there's lots of false positives and I didn't look
through all the things it pointed out but here's some
=> Remove some dead code

CHANGELOG.rst
=> Update changelog to reflect spelling change of xfail

changelog/4700.bugfix.rst, src/_pytest/unittest.py, testing/example_scripts/unittest/test_setup_skip.py, testing/example_scripts/unittest/test_setup_skip_class.py, testing/example_scripts/unittest/test_setup_skip_module.py, testing/test_unittest.py
=> Fix setUpClass being called in subclasses that were skipped

src/_pytest/logging.py
Change the indentation in _setup_cli_logging by moving the
self._log_cli_enabled check outside of the _setup_cli_logging method.
=> Refactor _setup_cli_logging code

pyproject.toml, tox.ini
As per the excellent article by @gaborbernat:
https://www.bernat.tech/pep-517-518/
=> Use isolated_build option in tox.ini

doc/en/assert.rst
=> Clarify pytest_assertrepr_compare docs per #4759

.travis.yml, appveyor.yml, tox.ini
https://github.com/tox-dev/tox/issues/706 has been fixed.
=> tox: use deps for pluggymaster testenvs

changelog/4698.feature.rst, src/_pytest/terminal.py, testing/acceptance_test.py, testing/deprecated_test.py
=> Remove py27 py34 deprecation warning

src/_pytest/nodes.py
=> Fix code-block in Node docstring

.travis.yml
Ref: https://github.com/pytest-dev/pytest/pull/4789#issuecomment-464135675
=> Travis: remove cron_only stage, use conditional job

.travis.yml
=> ci: Travis: use single install section

.travis.yml
The current commit on features has 50+ uploads already:
https://codecov.io/gh/pytest-dev/pytest/commit/c7bbb2a78873a63b9df9df08f8dc77cde30debd3/build
=> ci: Travis: skip coverage with cron runs

changelog/4861.bugfix.rst, src/_pytest/capture.py, testing/test_capture.py
Fixes https://github.com/pytest-dev/pytest/issues/4861.
=> Validate type with writing to captured output like without

changelog/4913.trivial.rst, testing/test_collection.py
Fixes https://github.com/pytest-dev/pytest/issues/4913
=> Fix pytest tests invocation with custom PYTHONPATH

changelog/4912.trivial.rst, doc/en/conf.py
Partial solution for https://github.com/pytest-dev/pytest/issues/4912
=> Remove deprecated Sphinx directive add_description_unit()

changelog/4912.trivial.rst, doc/en/requirements.txt
Fixes https://github.com/pytest-dev/pytest/issues/4912
=> Pin sphinx-removed-in to >= 0.2.0 to support Sphinx 2.0

src/_pytest/mark/__init__.py
Includes an example of multiple expressions
=> Add example for k flag

testing/test_warnings.py
Ref: https://github.com/pytest-dev/pytest/pull/4981
=> test_as_errors: use subprocess with `-W`

src/_pytest/helpconfig.py
=> showhelp: move tw.fullwidth out of the loop

src/_pytest/terminal.py
Avoids ini lookups.
No changelog.
=> terminal: store console_output_style in _show_progress_info

src/_pytest/terminal.py
No changelog.
Good candidate for https://github.com/pytest-dev/pytest/issues/5057 btw.
=> terminal: console_output_style: document "count" with help

src/_pytest/reports.py
This is helpful with derived classes.
=> TestReport: use class name in repr

src/_pytest/assertion/rewrite.py
This makes it easier / possible to grep.
=> assertion rewriting: use actual helper name

testing/conftest.py
=> conftest: use a hookwrapper with sorting faster tests first

src/_pytest/capture.py, testing/test_capture.py
=> capture: store _suspended state

AUTHORS, changelog/5089.bugfix.rst, src/_pytest/_code/code.py, src/_pytest/_io/saferepr.py, testing/code/test_excinfo.py, testing/test_session.py
=> Fix handle repr error with showlocals and verbose output

doc/en/doctest.rst
* Add pytest.skip() example
* Add blurb about Sybil
* Create a subsection for doctest-options
* Create a subsection for pytest-specific features
* Fix examples
cc @cjw296
=> Review doctest docs

doc/en/deprecations.rst
=> Add quick note about accessing config through session or item objects

azure-pipelines.yml
=> Unify pypy

.travis.yml
The basic `pypy` and `pypy3` now point to the latest PyPy releases: 
* https://travis-ci.community/t/add-pypy-7-support/2228/6?u=hugovk
---
Is this needed? If so, which type?
- [n/a] Target the `features` branch for new features and removals/deprecations.
- [n/a] Include documentation when adding new features.
- [n/a] Include new tests or update existing tests when applicable.
=> Upgrade PyPy to 7.1.1

changelog/5023.feature.rst, doc/en/example/markers.rst, doc/en/mark.rst, doc/en/reference.rst, src/_pytest/main.py, src/_pytest/mark/structures.py, testing/code/test_excinfo.py, testing/code/test_source.py, testing/python/fixtures.py, testing/python/integration.py, testing/python/metafunc.py, testing/test_capture.py, testing/test_conftest.py, testing/test_mark.py, testing/test_recwarn.py, testing/test_stepwise.py, testing/test_tmpdir.py, testing/test_unittest.py, testing/test_warnings.py, tox.ini
=> Further "unknown marks warning" improvements

doc/en/monkeypatch.rst
Do i really need to create issue and changelog record for such a small fix?
=> Fixed double `be` word on monkeypatch docs page.

CHANGELOG.rst
=> Fix one misspelling in changelog

testing/test_assertion.py
=> tests: harden test_nonascii_text

changelog/5330.bugfix.rst, src/_pytest/python.py, testing/python/collect.py
=> Show test module in the PytestCollectionWarning message

.travis.yml
=> Allow pypy3 failures again

CHANGELOG.rst, changelog/5383.bugfix.rst, changelog/5389.bugfix.rst, changelog/5390.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-4.6.3.rst
figured we should get these bugfixes out, it costs us basically nothing to release :man_shrugging:
=> Preparing release version 4.6.3

src/_pytest/compat.py
=> fix safe_str docstring

doc/en/talks.rst
Added talk about pytest in PyBCN June 2019
=> Added talk about pytest in PyBCN June 2019

doc/en/talks.rst
Two upcoming trainings in Switzerland I plan to do :wink:
=> Add upcoming trainings

src/_pytest/python.py, testing/python/metafunc.py
those are random clean-ups i did while tinkering in the direction of function definition
=> Various cleanups in src/_pytest/python.py

doc/en/talks.rst
Europython is over! The training went surprisingly well, especially considering that it was only @obestwalter and me with ~60 participants. :tada:
=> Remove Europython training

doc/en/talks.rst
I will be offering a three day hands-on workshop about pytest, tox and devpi in Leipzig in October.
=> Add info about open training in Leipzig

testing/test_pytester.py
=> Fix ordering of sys modules snapshot

changelog/5634.bugfix.rst, testing/test_unittest.py
Followup to https://github.com/pytest-dev/pytest/pull/5634.
=> Followup: unittest: handle outcomes.Exit

src/_pytest/mark/structures.py
The MarkInfo class no longer exists
=> Update MarkDecorator docs

doc/en/monkeypatch.rst
=> fix docs about syspath_prepend

AUTHORS, doc/en/fixture.rst, doc/en/index.rst
=> Doc fix: delete useless.

doc/en/monkeypatch.rst
=> fix setenv prepend docs

doc/en/example/markers.rst
=> Doc fix: remove redundant parentheses.

doc/en/usage.rst
=> Mention pytest-custom_exit_code in the docs

doc/en/example/pythoncollection.rst
you missed a spot in https://github.com/pytest-dev/pytest/pull/5557
=> trivial doc change

tox.ini
=> Forward $TRAVIS_REPO_SLUG for GH publish notes

doc/en/py27-py34-deprecation.rst
pytest 4.6.0 was released in June 2019.
* https://pypi.org/project/pytest/#history
- [n/a] Target the `features` branch for new features, improvements, and removals/deprecations.
- [n/a] Include documentation when adding new features.
- [n/a] Include new tests or update existing tests when applicable.
- [n/a] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [n/a] Add yourself to `AUTHORS` in alphabetical order;
=> Docs: update tense

changelog/5801.trivial.rst, src/_pytest/pastebin.py, src/_pytest/pytester.py, testing/acceptance_test.py, testing/python/raises.py, testing/test_monkeypatch.py, testing/test_pastebin.py, testing/test_warnings.py
Detected using [flake8-2020](https://github.com/asottile/flake8-2020)
=> [4.6] fixes for python4

doc/en/_templates/layout.html
This reverts commit c8cf748c49e9e02e5f714d5ab60a5c4f1bfc75ba, reversing
changes made to 702acdba4658ad0a7e732059d18b22b185c79e5c.
=> Revert "Show banner/full page for the Digital Climate Strike (#5861)"

scripts/report-coverage.sh
This should result in retries of 1+2+4+8+16+32 = 63s.
Ref: https://github.com/pytest-dev/pytest/pull/5869#issuecomment-534235437
=> ci: codecov: use 6 retries with curl

doc/en/customize.rst
=> Update doc: pytest section in setup.cfg

testing/test_runner.py
=> Fix spurious ResourceWarning stderr in testsuite again

CHANGELOG.rst, changelog/5523.bugfix.rst, changelog/5537.bugfix.rst, changelog/5801.trivial.rst, changelog/5806.bugfix.rst, changelog/5902.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-4.6.6.rst, doc/en/example/reportingdemo.rst, doc/en/example/simple.rst, doc/en/getting-started.rst, tox.ini
I also cherry-picked 065773aa97a02731e5eec05e29204b50850d9248 and 1c5efffd904e0068a3e7b4090d94bbe589be66bf for this release.
=> Release 4.6.6

CHANGELOG.rst
Ref: https://github.com/pytest-dev/pytest/pull/5952#issuecomment-541801883
=> changelog: #5523 was fixed in 5.0.1 already

setup.py, testing/python/fixtures.py
Ref: https://github.com/pytest-dev/pytest/pull/5950#discussion_r335254774
=> tests: keep numpy being optional

testing/test_pdb.py
Ref: https://github.com/pytest-dev/pytest/pull/5306#issuecomment-495690643
=> tests: debugging: disable pdb++ within inner tests

.travis.yml, azure-pipelines.yml
This will display durations, and is useful in logs in general.
=> ci: use tox -vv

src/_pytest/capture.py
Ref: https://github.com/pytest-dev/pytest/pull/4996#issuecomment-479686487
(initially added in https://github.com/pytest-dev/pytest/commit/177637bfb91f2e586f43d812c428783fdc877273)
=> Remove (rejected) comment from DontReadFromInput

testing/test_pdb.py
=> Fix test_doctest_set_trace_quit on features

testing/test_meta.py
This moves it to the end of tests during collection.  Takes ~7s for me.
=> tests: mark test_meta as slow

changelog/6069.improvement.rst, src/_pytest/pytester.py
Fixes https://github.com/pytest-dev/pytest/issues/6069
Reverts https://github.com/pytest-dev/pytest/commit/0852e84d9f27823e0cd40651bc3836b378c1239c
=> pytester: spawn: do not skip FreeBSD

src/_pytest/pathlib.py, src/_pytest/tmpdir.py
These files are mostly straightforward to annotate.
=> Add type annotations to _pytest.pathlib and _pytest.tmpdir

testing/conftest.py
This handles e.g. the faulthandler tests then.
=> tests: conftest: handle tests using runpytest_subprocess as "slowest"

testing/test_terminal.py
Remove the `--fulltrace` arg from the `Option` fixture used in several
tests, but not checked for.  Only use it with `test_keyboard_interrupt`.
(removes 8 tests, coverage not affected)
=> test_terminal: reduce number of tests (single --fulltrace param)

testing/test_cacheprovider.py, tox.ini
Fixes https://github.com/pytest-dev/pytest/issues/5974.
Via https://github.com/pytest-dev/pytest/issues/5974#issuecomment-549822509.
=> Fix rm_rf tests

testing/test_faulthandler.py
=> tests: speed up test_faulthandler.test_timeout

changelog/6148.improvement.rst, setup.py, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
Fixes https://github.com/pytest-dev/pytest/issues/6147
=> Use atomicrewrites only on Windows

changelog/6116.improvement.rst, src/_pytest/main.py, testing/test_collection.py
=> add --co option to collect-only

src/_pytest/python.py
=> Metafunc: remove unused _ids

changelog/5477.bugfix.rst, src/_pytest/junitxml.py, testing/test_junitxml.py
From: https://github.com/pytest-dev/pytest/pull/5550#issuecomment-558797460
=> [4.6] Include <testsuites> root tag in generated XML (#5550)

setup.cfg, src/pytest/__init__.py, src/pytest/__main__.py
As discussed in https://github.com/pytest-dev/pytest/issues/3342, this is the first step to make pytest fully support static typing.
Had a few minutes on my hands so decide to tackle this.
=> Convert pytest.py into a package

changelog/4639.improvement.rst
An improvement seems more adequate here.
=> Change 4639 from feature to improvement

README.rst, doc/en/announce/release-2.3.0.rst, doc/en/announce/release-2.5.0.rst, doc/en/announce/release-2.7.0.rst, doc/en/changelog.rst, doc/en/historical-notes.rst, doc/en/index.rst, doc/en/py27-py34-deprecation.rst, doc/en/sponsor.rst
Hi! I fixed some typos, if you want to keep something as-is for "historical reasons" just tell me or commit.
Thanks in advance!
-----
=> fix typos in docs

CONTRIBUTING.rst
Added one line to Contributing.rst instructing people to indicate they are working on an issue as a comment to that issue
Resolves #6378
=> Added how to reserve an issue to yourself when contributing

changelog/5686.improvement.rst, src/_pytest/tmpdir.py, testing/test_tmpdir.py
this is to  fix #5686 
@nicoddemus , please help to review
=> tmpdir_factory.mktemp now fails given absolute and non-normalized paths.

README.rst
Corrects grammar error in "Support pytest" section.
=> Fix grammar in README

AUTHORS, changelog/6469.feature.rst, doc/en/reference.rst, src/_pytest/junitxml.py, testing/acceptance_test.py, testing/test_junitxml.py
Improving the docs/changelog a bit, unfortunately could not push this to the original PR (no permission to push to the fork).
=> junit_logging options (follow up to #6469)

.travis.yml
After https://github.com/pytest-dev/pytest/pull/6502.
=> [features] ci: Travis: drop deploy and non-coverage jobs

tox.ini
Taken out of https://github.com/pytest-dev/pytest/pull/6486.
This allows for experimenting with it locally already, before adding it to CI then maybe.
=> tox: add mypy-diff testenv

setup.cfg
Any other options to add already?
/cc @bluetech @Zac-HD
=> mypy: show_error_codes=True

doc/en/example/simple.rst
The incremental marker is adapted to handle properly test classes with parametrize defined at class level.
=> extend the incremental marker for parametrize

doc/en/announce/index.rst, doc/en/announce/release-5.3.5.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/reportingdemo.rst, doc/en/example/simple.rst, doc/en/getting-started.rst, src/_pytest/config/argparsing.py, src/_pytest/config/findpaths.py, src/_pytest/doctest.py, src/_pytest/fixtures.py, src/_pytest/main.py, src/_pytest/nodes.py, testing/python/collect.py, testing/test_nose.py
Ref: https://github.com/pytest-dev/pytest/issues/6517
Fix: #6596
=> Preparing release version 5.3.5

doc/en/announce/index.rst, doc/en/announce/release-5.3.5.rst, doc/en/changelog.rst
(cherry picked from commit fd1a51a23fa687cf344f3506dff6cde0166faf2c)
=> doc: release-5.3.5

src/_pytest/pytester.py
(cherry picked from commit 92d884f9f29584ead68b233f80777b85273d17b8)
=> pytester: clarify _makefile signature

src/_pytest/junitxml.py
=> Remove incorrect choices comment.

src/_pytest/capture.py
Gone wrong during review of https://github.com/pytest-dev/pytest/pull/6663.
=> Fix CaptureManager.__repr__

.travis.yml
Ref: https://github.com/jaraco/zipp/issues/40
=> ci: Travis: 3.5.1: upgrade pip, setuptools, virtualenv for zipp update

changelog/6575.bugfix.rst, src/_pytest/faulthandler.py, testing/test_faulthandler.py
=> Fix crash when faulthandler starts initialized

src/_pytest/assertion/util.py, testing/test_assertion.py
Helpful when working with `assertrepr_compare`.. ^^
=> assertrepr_compare: provide more info (location) with exceptions

doc/en/writing_plugins.rst
Ref: https://github.com/pytest-dev/pytest/issues/6377
Ref: https://github.com/blueyed/pytest/pull/145
=> doc: link to `python_files` from "Assertion Rewriting"

testing/test_terminal.py
Ref: https://github.com/pytest-dev/pytest/pull/6599
=> tests: harden test_xdist_verbose

src/_pytest/capture.py
This better reflects the inheritance / smartness with regard to raw or
encoded.
- FDCaptureBinary
- FDCapture
- SysCaptureBinary
- SysCapture
- TeeSysCapture
=> capture: re-order classes

testing/test_runner.py
=> tests: runner: improve/ignore coverage

testing/test_terminal.py
Ref: https://github.com/pytest-dev/pytest/pull/6394
=> tests: harden/improve test_itemreport_subclasses_show_subclassed_file

doc/en/fixture.rst
Documentation fix for:
https://github.com/pytest-dev/pytest/issues/6783
=> Updated Dynamic Scopes Documentation

AUTHORS, changelog/6696.doc.rst, doc/en/cache.rst, doc/en/changelog.rst, doc/en/conf.py, doc/en/fixture.rst, doc/en/reference.rst
=> doc: add list of fixtures to start of fixture chapter

changelog/6801.bugfix.rst, src/_pytest/doctest.py, testing/test_doctest.py
=> doctest: strip newlines with unexpected exceptions

changelog/6779.deprecation.rst, doc/en/deprecations.rst, src/_pytest/terminal.py, testing/deprecated_test.py
=> Deprecate TerminalReporter.writer

src/_pytest/assertion/rewrite.py
It implements the required methods. This is useful for typing but also a
nice indicator.
=> Mark AssertionRewritingHook as implementing importlib.abc.Loader

doc/en/projects.rst, doc/en/talks.rst
* pydanny is fixed
* https://www.theautomatedtester.co.uk/blog/2011/pytest_and_xdist_plugin.html awaits reply on https://twitter.com/ossronny/status/1237676934399655936
addresses issues from #6892
=> fix urls that fail linkcheck

doc/en/announce/index.rst, doc/en/announce/release-5.4.1.rst, doc/en/changelog.rst
Not sure, but I think we don't need to wait for approval for this kind of PR?
=> Cherry pick CHANGELOG from 5.4.1

doc/en/reference.rst
first open source PR ever! woo hoo! this is a very trivial documentation link fix, so i didn't find it appropriate to add either a changelog or myself to AUTHORS
Fixes #6883.
=> Fix reference to the cache fixture

README.rst
315+ plugins -> 850+ plugins
quite a significant bump
=> update available plugin count

.pre-commit-config.yaml, setup.py, src/_pytest/python_api.py, src/_pytest/recwarn.py, src/_pytest/reports.py, src/_pytest/terminal.py
Release notes: https://mypy-lang.blogspot.com/2020/03/mypy-0770-released.html
=> Upgrade mypy 0.761 -> 0.770

CONTRIBUTING.rst
The main unclear part was that "to contribute changes" read in two
different ways; I've reworded it so it reads only one way.
=> CONTRIBUTING: Grammatical clarification and minor typo fixes

testing/test_warnings.py
Remove it where not used / overwritten, and use its reference otherwise,
which makes it clear that it is used actually.
=> test_warnings: clean up usage of pyfile_with_warnings

doc/en/reference.rst, doc/en/skipping.rst
=> Better document xfail(condition)

doc/en/reference.rst
=> Fix documentation typo

testing/test_assertion.py
=> Remove some no-longer-needed compat code in test_assertion

AUTHORS, changelog/6285.feature.rst, src/_pytest/fixtures.py, src/pytest/__init__.py, testing/example_scripts/fixtures/fill_fixtures/test_conftest_funcargs_only_available_in_subdir/sub1/conftest.py, testing/python/fixtures.py
=> Add _pytest.fixtures.FixtureLookupError to top level import

testing/test_junitxml.py
=> Remove Python 2 compat code in test_juintxml.py

changelog/6951.bugfix.rst, src/_pytest/deprecated.py, src/_pytest/terminal.py, testing/deprecated_test.py
=> backport #6986: writable TerminalWriter.writer for deprecation

src/_pytest/nodes.py
=> Fixes #7077: Added & improved docs for repr_failure() in Node & Collector

.pre-commit-config.yaml, src/_pytest/capture.py, src/_pytest/mark/__init__.py, src/_pytest/monkeypatch.py, src/_pytest/pytester.py, testing/acceptance_test.py, testing/logging/test_reporting.py, testing/test_capture.py
I was looking at updating flake8 (separate PR), and thought I'd update these as well.
=> pre-commit: update some tool revisions

doc/en/doctest.rst
Resolves https://github.com/pytest-dev/pytest/issues/7116
Small doc fix.
=> update doctests.rst regarding issue #7116

changelog/7143.bugfix.rst, src/_pytest/nodes.py, testing/test_collection.py
=> [Backport] Merge pull request #7143 from nicoddemus/file-from-parent

src/_pytest/mark/evaluate.py, testing/test_assertrewrite.py
It's called `__bool__` in Python 3.
=> Remove a couple Python 2 __nonzero__ definitions

src/_pytest/hookspec.py
Would make sense to use its return value etc, but this helps for now.
=> [WIP] doc: pytest_collection: has to set `session.items`

src/_pytest/terminal.py, testing/test_config.py
=> testing: fix lint after merge of old branch

changelog/7145.bugfix.rst, src/_pytest/_io/saferepr.py, testing/io/test_saferepr.py
=> [5.4] Merge pull request #7168 from nicoddemus/saferepr-getattr-fail-7145

src/_pytest/warnings.py
When setting up the warnings capture, filter strings (with the general form `action:message:category:module:line`) are collected from the cmdline, ini and item and applied. This happens for every test and other cases.
To apply a string it needs to be parsed into a tuple, and it turns out this is slow. Since we already vendor the parsing code from Python's warnings.py, we can speed it up by caching the result. After splitting the parsing part from the applying part, the parsing is pure and is straightforward to cache.
An alternative is to parse ahead of time and reuse the result, however the caching solution turns out cleaner and more general in this case.
On this benchmark:
```py
import pytest
@pytest.mark.parametrize("x", range(5000))
```
Before:
``` …
```
=> warnings: speed up work done in catch_warnings_for_item()

setup.cfg, testing/code/test_source.py, tox.ini
=> [4.6] Merge pull request #7179 from asottile/py39

CONTRIBUTING.rst
=> remove incorrect note about requiring admin install

testing/deprecated_test.py
It did not actually test that the attribute gets set.
=> Fix test_terminal_reporter_writer_attr

doc/en/example/parametrize.rst
=> #7138 Docs improvement: Apply indirect on particular arguments

scripts/release-on-comment.py
#6911 , Earlier pytest-bot would only print out the exception in cases of
failure but did not provide context on failing command and error from
command. This patch adds the errors from the command to the exception
message.
`Command` provides abstraction over the command to run and helps
in collecting errors from the first failing command only.
With this, we don't need to check `returncode` from each command that
we run, we can run all the commands and will have access to the error
from the first command that failed. This pattern was taken from Go.
Please refer: https://blog.golang.org/errors-are-values
=> Fix-6911(pytest-bot): Added error from commands that are run

scripts/release-on-comment.py
Somehow I've missed the failures while merging, totally my fault.
=> Fix errors introduced by #6911

doc/en/getting-started.rst
brief documentation to outline that tests inside classes do not leak/persist/share the same class instance but instead, they create a new one.  closes #6900
=> document class instantiation for tests inside classes

.github/workflows/main.yml, .github/workflows/release-on-comment.yml
According to https://github.com/actions/checkout/releases/tag/v2.2.0 this should work now.
=> ci: use fetch-depth: 0 instead of fetching manually

src/_pytest/junitxml.py, src/_pytest/pytester.py, src/_pytest/runner.py, src/_pytest/terminal.py, src/_pytest/timing.py, testing/acceptance_test.py, testing/conftest.py, testing/test_junitxml.py
Conflicts:
src/_pytest/pytester.py
src/_pytest/runner.py
src/_pytest/terminal.py
testing/acceptance_test.py
=> [5.4.x] Merge pull request #7242 from nicoddemus/fix-flaky-test

.pre-commit-config.yaml, setup.cfg, setup.py
- also ran `pre-commit autoupdate`
- https://github.com/asottile/setup-py-upgrade
- https://github.com/asottile/setup-cfg-fmt
Supersedes #7316 
Closes #7316
=> Run setup-py-upgrade and setup-cfg-fmt

doc/en/customize.rst
As per comment:
https://github.com/blueyed/pytest/commit/37d836d754eb8e20540ff1a16da76edee9a7adda#commitcomment-37463196
=> Fix mention using --rootdir mention inside pytest.ini (not supported)

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.rst
Closes https://github.com/pytest-dev/pytest/issues/7334
Add documentation on how to deal with closing raised issues
=> Add documentation on closing issues

.github/workflows/main.yml
=> cache the pre-commit environment

doc/en/talks.rst
Let's hope for enough sign-ups despite COVID ~~-20~~ -19, but we'll see how things turn out!
=> Add open training at Workshoptage 2020

doc/en/talks.rst
More shameless self promotion - I thought it'd take longer until things are set up, but turns out it was ready shortly after my previous PR, sorry for that!
=> Add webinar to open trainings

testing/test_config.py
Also cleaned up the parametrized list using `pytest.param` to assign ids
and removed some redundant cases.
Follow up to #7459
=> Make test_missing_required_plugins xdist-independent

doc/en/changelog.rst
- Grammar fixes
- Moved a few sections from Features to Improvements
- Used internal doc links when appropriate
=> Small fixes/updates to the 6.0.0rc1 CHANGELOG

changelog/7422.doc.rst, doc/en/reference.rst
=> Clarify usage of usefixtures mark in hooks

testing/test_parseopt.py
Address post-merge comments in #7520 from @graingert and @The-Compiler.
=> testing: improve bash check

doc/en/example/markers.rst
Trivial fix: extra colon to make code block render correctly
=> Trivial fix: extra colon to make code block render correctly.

changelog/7569.bugfix.rst
Was supposed to be included in #7571 but I accidentally forgot to git add it.
=> Add missing changelog for issue 7569

changelog/7569.bugfix.rst
=> [6.0.x] Add missing changelog for issue 7569 

testing/example_scripts/unittest/test_unittest_plain_async.py, testing/test_unittest.py
Related to pytest-dev/pytest-asyncio#180
=> Demonstrate that plain unittest does not support async tests

doc/en/mark.rst
This should improve the ease of transitioning to `pyproject.toml`.
=> Document registering markers in pyproject.toml

doc/en/example/nonpython.rst
The correct name is visible in [the Bitbucket link](http://bitbucket.org/aafshar/pytest-yamlwsgi/src/tip/pytest_yamlwsgi.py).
=> Fix typos in Ali Afshar's name

changelog/7631.trivial.rst
Address https://github.com/pytest-dev/pytest/pull/7631#issuecomment-671467323.
=> Add changelog for PR #7631

changelog/7707.bugfix.rst, src/_pytest/_code/code.py, testing/code/test_excinfo.py
Fix handle of exceptions in ReprEntry with tb=line
=> [6.0] Merge pull request #7708 from nicoddemus/repr-line-7707

doc/en/reference.rst, src/_pytest/nodes.py
=> [6.0.x] Add missing File reference to the docs

doc/en/index.rst
=> doc: Remove Workshoptage training

CONTRIBUTING.rst
=> remove unused bitbucket link

CONTRIBUTING.rst
=> permit tox config in non-tox.ini files for pytest-dev member projects

changelog/7572.improvement.rst, src/_pytest/config/__init__.py, testing/test_config.py
Partial-of: https://github.com/pytest-dev/pytest/pull/7572
=> Improve output for missing required plugins

README.rst, doc/en/index.rst
@gnikonorov now can you take a look into this PR? I've made suggested change.
=> [Docs] remove semi-colon punctuation mark

src/_pytest/junitxml.py
=> Warning about record_testsuite_property not working with xdist

src/_pytest/junitxml.py
=> [6.0.x] Warning about record_testsuite_property not working with xdist

.github/workflows/main.yml, pyproject.toml, src/_pytest/python.py, testing/plugins_integration/.gitignore, testing/plugins_integration/README.rst, testing/plugins_integration/bdd_wallet.feature, testing/plugins_integration/bdd_wallet.py, testing/plugins_integration/django_settings.py, testing/plugins_integration/pytest.ini, testing/plugins_integration/pytest_anyio_integration.py, testing/plugins_integration/pytest_asyncio_integration.py, testing/plugins_integration/pytest_mock_integration.py, testing/plugins_integration/pytest_trio_integration.py, testing/plugins_integration/pytest_twisted_integration.py, testing/plugins_integration/simple_integration.py, testing/test_assertrewrite.py, testing/test_config.py, tox.ini
Co-authored-by: Bruno Oliveira <nicoddemus@gmail.com>
Co-authored-by: Thomas Grainger <tagrain@gmail.com>
Co-authored-by: Kyle Altendorf <sda@fstab.net>
=> [6.0.x] Smoke tests for assorted plugins (#7721)

doc/en/fixture.rst
Co-authored-by: Ran Benita <ran@unusedvar.com>
=> [6.0.x] Add docs about reusing fixtures from other projects (#7772)

tox.ini
=> Use new pip resolver in plugins tox env

tox.ini
=> [6.0.x] Merge pull request #7784 from nicoddemus/use-new-pip-solver-7783

scripts/release-on-comment.py
No need for the fullstop and quote at the end of https://github.com/pytest-dev/pytest/issues/7703#issuecomment-699523002:
> Found features or breaking changes in `6.1.x`, and feature releases can only be
> created from `master`.":
> 
> * `5585.breaking.rst`
> * `7667.feature.rst`
=> Fix typos in pytestbot

doc/en/writing_plugins.rst
=> [6.1.x] Improve docs about plugin discovery/loading at startup

src/_pytest/_code/code.py, src/_pytest/assertion/rewrite.py, src/_pytest/cacheprovider.py, src/_pytest/compat.py, src/_pytest/config/__init__.py, src/_pytest/config/findpaths.py, src/_pytest/logging.py, src/_pytest/main.py, src/_pytest/monkeypatch.py, src/_pytest/nodes.py, src/_pytest/pathlib.py, src/_pytest/pytester.py, src/_pytest/reports.py, src/_pytest/terminal.py, src/_pytest/tmpdir.py, testing/python/fixtures.py, testing/test_assertrewrite.py, testing/test_collection.py, testing/test_config.py, testing/test_conftest.py, testing/test_findpaths.py, testing/test_junitxml.py, testing/test_main.py, testing/test_pathlib.py, testing/test_reports.py, testing/test_terminal.py, testing/test_tmpdir.py
=> py36+: remove rexport of Path and PurePath

src/_pytest/python_api.py
=> DOC Update link to numpy

doc/en/reference.rst
=> Update reference.rst informing the default junit_family

scripts/release-on-comment.py
As suggested in https://github.com/pytest-dev/pytest/issues/7843#issuecomment-703180482.
=> release-on-comment: add "Closes <release issue number>" to release PR

.pre-commit-config.yaml, setup.cfg, src/_pytest/cacheprovider.py, src/_pytest/capture.py, src/_pytest/compat.py, src/_pytest/config/findpaths.py, src/_pytest/pytester.py, src/_pytest/python_api.py, src/_pytest/runner.py, testing/test_assertrewrite.py, testing/test_capture.py, testing/test_debugging.py, testing/test_doctest.py, testing/test_pastebin.py
=> Update mypy 0.782 -> 0.790, iniconfig typing

README.rst, doc/en/getting-started.rst, doc/en/index.rst, pyproject.toml, src/_pytest/assertion/rewrite.py, src/_pytest/capture.py, src/_pytest/python_api.py, testing/code/test_excinfo.py, testing/python/raises.py, testing/test_reports.py
=> py36+: Remove redundant Python 2.7 and 3.5 code, update docs and comments

testing/test_compat.py
Converts test_compat.py from testdir to pytester
=> Migrate test_compat.py from testdir to pytester

testing/test_assertion.py
Converts test_assertion.py from testdir to pytester
=> Migrate test_assertion.py from testdir to pytester

testing/test_stepwise.py
refactor `test_stepwise.py` after my other PR merged with refactoring of the plugin.
relates to #7942
=> #7942 refactor stepwise tests to utilize pytester

AUTHORS, testing/test_runner_xunit.py
migrating test_runner_xunit.py from testdir to pytester.
I'm new to contributing and am eager to learn so please let me know if I've done anything wrong (or right).
=> pytest-dev#7942 test_runner_xunit.py

doc/en/changelog.rst
=> Manually add the remaining 4.6.x release notes to the changelog

doc/en/reference.rst, src/_pytest/python.py
=> Add FunctionDefinition to the reference docs

src/_pytest/_code/code.py, src/_pytest/_code/source.py, src/_pytest/python.py, testing/code/test_code.py, testing/code/test_excinfo.py, testing/code/test_source.py, testing/test_assertrewrite.py
Just a few minor code-level cleanups/improvements. Please see the commits.
=> code: a few minor improvements

AUTHORS, testing/test_setupplan.py
=> #7942 test_setupplan.py migrate from testdir to Pytester

src/_pytest/pytester.py, testing/test_collection.py
This PR does the following things:
1. Migrates test_collection.py from testdir to Pytester.
2. Some tests cannot migrated currently. They were just annotated.
Tests which were not migrated:
1. test_pytest_collect_file
- Reason
https://github.com/pytest-dev/pytest/blob/30287b49cd02b6a14ade1bbe9adf9711c3d1259e/src/_pytest/config/argparsing.py#L148-L157
This function expects py.path.local
2. test__in_venv
- Reason
https://github.com/pytest-dev/pytest/blob/30287b49cd02b6a14ade1bbe9adf9711c3d1259e/src/_pytest/main.py#L346-L360
This function expects py.path.local and uses function specific to py.path
3. test_fscollector_from_parent
- Reason
https://github.com/pytest-dev/pytest/blob/30287b49cd02b6a14ade1bbe9adf9711c3d1259e/src/_pytest/nodes.py#L486-L501
This function …
=> test_collection.py migrate from testdir to Pytester

src/_pytest/terminal.py
A bit shorter and a better name, IMHO.
=> Rename _make_plural to pluralize

.github/ISSUE_TEMPLATE/2_feature_request.md
This is more of an RFC, the wording is based on https://github.com/jazzband/pip-tools/blob/master/.github/ISSUE_TEMPLATE/feature-request.md but I'm completely open to completely change/remove the wording, I just think there should be *something* here
=> expand feature request issue template

changelog/8023.improvement.rst, doc/en/reference.rst, src/_pytest/main.py
=> Add 'node_modules' to norecursedirs

testing/test_faulthandler.py
=> Migrate from testdir to pytester

testing/test_conftest.py, testing/test_recwarn.py, testing/test_tmpdir.py
I tried creating a pull request but previous commits were showing so i forced push but the authors one still showed up, do sorry about that
=> #7942 migrate from tempdir to pytester

AUTHORS, changelog/8032.improvement.rst, src/_pytest/unittest.py, testing/test_unittest.py
Fixes #8032 
Pytest already supports doCleanups; I added tests for this.
=> Call Python 3.8 doClassCleanups

testing/test_runner.py
This is a clean cherry-pick of d9ac2efbcdee123f73edf1829c8bd6a91be3b6d2
=> [4.6] testing: python 3.10 fix

AUTHORS, changelog/7429.doc.rst, doc/en/doctest.rst
_clarify documentation about skipping of doctests_
=> Add more info about skipping doctests

testing/test_pastebin.py
This PR does the following:
* Refactors test_pastebin.py from testdir to pytester
=> Migrate test_pastebin.py from testdir to pytester

doc/en/doctest.rst
As per https://github.com/pytest-dev/pytest/discussions/8088
=> List pytest-doctestplus in doctest docs

changelog/2044.improvement.rst, src/_pytest/terminal.py, testing/test_terminal.py
I've implemented functionality proposed in #2044. 
Fixes #2044.
=> Issue 2044 - show skipping reason in verbose mode

changelog/8152.bugfix.rst, src/_pytest/outcomes.py, src/_pytest/terminal.py, testing/test_terminal.py
=> [6.2.x] terminal: fix "(<Skipped instance>)" skip reason in test status line

.github/workflows/main.yml, .github/workflows/prepare-release-pr.yml, .github/workflows/release-on-comment.yml
Reverts pytest-dev/pytest#8171
=> Use new pypy3 github actions syntax

README.rst
See #8186
We can remove the GA `linting` target when happy!
=> Add badge for pre-commit.ci

doc/en/fixture.rst
Add missing fixture in argument list.
=> Add missing fixture

testing/code/test_excinfo.py, testing/test_argcomplete.py
migrating some tests from tmpdir to tmp_path fixture.
=> pytest-dev#8204 migrate some tests to tmp_path fixture

testing/code/test_source.py
=> pytest-dev#8204 migrate tests on testing/code/test_source to tmp_path

src/_pytest/fixtures.py, src/_pytest/nose.py, src/_pytest/python.py, src/_pytest/reports.py, testing/python/integration.py, testing/test_terminal.py
These are few small commits with misc improvements, adding type annotations and such, that I gathered while looking at other stuff. Please see the commits.
=> Misc small code improvements

src/_pytest/fixtures.py, src/_pytest/nose.py, src/_pytest/outcomes.py, src/_pytest/reports.py, src/_pytest/skipping.py, src/_pytest/unittest.py
Continuing to clean up some things that I notice. Please see the individual commits. The last commit adds a new (private) field to the  `Skipped` exception.
=> Minor code improvements in nose, unittest, skipping

src/_pytest/runner.py
This is a small continuation to #8219 which I noticed after the fact.
SetupState maintains its own state, so it can store the exception itself, instead of using the node's store, which is better avoided when possible.
This also reduces the lifetime of the reference-cycle-inducing exception objects which is never a bad thing.
=> runner: avoid using node's store in SetupState

doc/en/getting-started.rst
=> Mention that class variables are shared between tests

changelog/8192.bugfix.rst
=> changelog: fix missing tick

src/_pytest/cacheprovider.py, src/_pytest/monkeypatch.py, src/_pytest/pytester.py, src/_pytest/python.py, src/_pytest/python_api.py, testing/example_scripts/unittest/test_unittest_asyncio.py, testing/test_assertrewrite.py
Due to the recent upgrade to mypy 0.800.
=> Remove some no longer needed type-ignores

doc/en/index.rst
For the curious, it ended up as quite a success with 6 people (though obviously remote-only) :smile:
=> doc: Remove past training

.github/workflows/update-plugin-list.yml
Every day seems a bit excessive lately, let's make it a bit less frequent.
=> Update plugin-list every Sunday instead of everyday

src/_pytest/fixtures.py, src/_pytest/hookspec.py, src/_pytest/runner.py, testing/python/fixtures.py, testing/test_runner.py
(Previously: #8219 , #8272).
Please see the commits messages. I think that's about it for `SetupState`  for now :)
=> runner: a few more tweaks to SetupState

doc/en/index.rst
According to the source, there are 801 plugins now!
=> Update number of plugins

doc/en/changelog.rst
=> Fix typo in changelog

doc/en/index.rst
See the [enterPy website](https://www.enterpy.de/lecture_compact1.php?id=12713) for details :slightly_smiling_face:
=> Add enterPy training

doc/en/_templates/globaltoc.html
=> doc: fix broken links in left-hand TOC

src/_pytest/fixtures.py, src/_pytest/main.py, src/_pytest/nodes.py, src/_pytest/pathlib.py, src/_pytest/pytester.py, src/_pytest/python.py, src/_pytest/reports.py, src/_pytest/terminal.py, testing/python/collect.py, testing/test_nodes.py, testing/test_reports.py
=> More more py.path removals

CHANGELOG.rst, CONTRIBUTING.rst, README.rst, RELEASING.rst, scripts/prepare-release-pr.py, scripts/release-on-comment.py, src/_pytest/assertion/__init__.py
=> port the rest of the scripts/docs over to the main branch

changelog/8414.bugfix.rst, src/_pytest/pathlib.py, src/_pytest/pytester.py, src/_pytest/tmpdir.py, testing/test_tmpdir.py
Fixes #8414. This PR has been reviewed out-of-band by @nicoddemus. A backport to 6.2.x will be posted shortly.
=> Fix minor temporary directory security issue

doc/en/reference/reference.rst
Add the methods of tmp_path_factory to the docs.
Currently, only the class description appears in the docs.
=> Add tmp_path_factory methods to the docs

AUTHORS, changelog/8464.bugfix.rst, doc/en/reference/customize.rst, src/_pytest/config/findpaths.py, testing/test_config.py
Fix for https://github.com/pytest-dev/pytest/issues/8464 including a doc update
@nicoddemus  let me know your thoughts and feedback
=> fix #8464 wrong root dir when -c is passed

CONTRIBUTING.rst
I noticed some minor comma and grammar errors and figured I leave a pull request for your convenience.
=> Fix typos & missing commas in CONTRIBUTING.rst

CONTRIBUTING.rst, doc/en/announce/release-2.1.0.rst, doc/en/announce/release-2.1.1.rst, doc/en/announce/release-2.1.2.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/conf.py, doc/en/contact.rst, doc/en/explanation/flaky.rst, doc/en/explanation/goodpractices.rst, doc/en/getting-started.rst, doc/en/how-to/failures.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/monkeypatch.rst, doc/en/how-to/output.rst, doc/en/how-to/plugins.rst, doc/en/how-to/xunit_setup.rst, doc/en/projects.rst, doc/en/talks.rst, src/_pytest/cacheprovider.py, src/_pytest/recwarn.py, testing/test_pathlib.py
Found with
```
urli-fix . -a http: -i pytest
```
(https://github.com/nschloe/urli)
=> "fix" a couple of http -> https redirects

AUTHORS, doc/en/explanation/fixtures.rst
Allow maintainers to push and squash when merging my commits.
closes #8625 
* Corrected Grammar in "Fixtures: Sharing Test Data".
=> 8625 - Small grammar fix (Fixtures: Sharing Test Data)

AUTHORS, changelog/8539.bugfix.rst, src/_pytest/assertion/rewrite.py
=> [6.2.x] Merge pull request #8540 from hauntsaninja/assert310 

changelog/8539.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-6.2.4.rst, doc/en/changelog.rst, doc/en/getting-started.rst
Prepare release 6.2.4
(cherry picked from commit 15a45388fa272fde7b2b58254ca32c4998cb84f0)
=> cherry-pick release notes from 6.2.4

.github/workflows/main.yml
See #7443
[before](https://github.com/pytest-dev/pytest/runs/2501796486?check_suite_focus=true#step:5:66):
[after](https://github.com/pytest-dev/pytest/pull/8633/checks?check_run_id=2502024810#step:5:67):
=> ci: Force colors on

.github/workflows/main.yml, .pre-commit-config.yaml, changelog/8494.feature.rst, pyproject.toml, setup.cfg, testing/acceptance_test.py, testing/python/collect.py, testing/python/metafunc.py, testing/test_collection.py, testing/test_config.py, testing/test_pytester.py, testing/test_skipping.py, testing/test_terminal.py, testing/test_threadexception.py, testing/test_unraisableexception.py, testing/test_warnings.py, tox.ini
=> [6.2.x] Backport Python 3.10 support (PRs #8494 and #8555)

src/_pytest/doctest.py
* Remove unnecessary else clause in repr_failure()
=> Remove unnecessary else clause in repr_failure()

testing/test_unittest.py
Fixes https://github.com/pytest-dev/pytest/issues/8663
=> Ignore DeprecationWarnings in test_trial_error

src/_pytest/doctest.py, src/_pytest/fixtures.py, src/_pytest/main.py, src/_pytest/python_api.py
* Replace for loop using the `in` operator
* Replace for loop with a generator expression inside any()
* Replace for loop with a dictionary comprehension
* Use list comprehension"
* Simplify arguments for range()
=> Replace some for loops, and other minor changes

.github/workflows/main.yml, .github/workflows/release-on-comment.yml, scripts/release-on-comment.py, scripts/report-coverage.sh
Backport of #8681. Need to backport before we can change the repo settings and remove the secrets as discussed in #8681.
cherry picked from commit ff6d29717c96c64e108581ddc7ead862f8d2398a
Conflicts:
.github/workflows/main.yml
.github/workflows/prepare-release-pr.yml
.github/workflows/update-plugin-list.yml
scripts/prepare-release-pr.py
scripts/report-coverage.sh
=> [6.2.x] ci: few security/permissions improvements

changelog/7469.feature.rst, doc/en/builtin.rst, doc/en/how-to/writing_plugins.rst, doc/en/reference/customize.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, src/_pytest/config/argparsing.py, src/_pytest/fixtures.py, src/_pytest/hookspec.py, src/_pytest/pytester.py, src/_pytest/python.py, src/pytest/__init__.py
=> config: expose Config and PytestPluginManager for typing purposes

doc/en/index.rst
Preview: https://pytest--8701.org.readthedocs.build/en/8701/
=> doc: Remove training sidebar

doc/en/index.rst
Preview: https://pytest--8702.org.readthedocs.build/en/8702/
=> [6.2.x] doc: Remove training sidebar

doc/en/example/simple.rst
=> Fix typo (setupttools -> setuptools)

doc/en/fixture.rst
=> Typo fixed

doc/en/contents.rst, doc/en/history.rst
Based on #8667 - thanks @pfctdayelise for suggesting to add it to the docs!
Preview: https://pytest--8784.org.readthedocs.build/en/8784/history.html
=> doc: Add history page

doc/en/index.rst
Preview: https://pytest--8793.org.readthedocs.build/en/8793/
=> doc: Add new open trainings

doc/en/index.rst
(cherry picked from commit 61336bb3857555bfa951e461484ec221542687d6)
See #8793
=> [6.2.x] doc: Add new open trainings

src/_pytest/mark/__init__.py
Minor change but probably worth getting into 7.0 to be technically correct :sweat_smile:
=> Adjust fixme comments

doc/en/how-to/skipping.rst
=> Opt-out from regendoc for problematic example

doc/en/how-to/usage.rst
Fixing the missing import statement in usage.rst file
=> doc: Adding the missing sys import (#8819)

doc/en/contact.rst
Trival change: Added github discussions to contact.rst
=> contact.rst: Added github discussions.

README.rst
=> Fix Dead link in README for 'assert statements'

doc/en/index.rst
=> [6.2.x] doc: Update trainings

doc/en/reference/fixtures.rst
=> Fix typo in fixture.rst

doc/en/index.rst
=> [6.2] Remove finished open training

src/_pytest/python.py
This type is semi-private; not documented but many plugins access it through `item.callspec`. However, plugins access the public fields and almost none try to construct or monkeypatch it. So we should be allowed to clean it up some.
- Convert to attrs, add slots and frozen
- Instead of doing `new = old.copy(); new.setmulti2()`, do `new = old.setmulti()`. This is cleaner and faster.
- Remove the `metafunc` attribute. This causes a reference cycle (multifunc._calls -> callspec -> multifunc) for no good reason -- neither pytest itself nor plugins access this attribute, so let's not keep the Metafunc objects alive past their due.
- Some comments.
I would have also like to make the dicts and lists themselves immutable, however some plugins mess with those so that should be done separately, if …
=> python: refactor CallSpec2

src/_pytest/_code/code.py, src/_pytest/cacheprovider.py, src/_pytest/config/__init__.py, src/_pytest/fixtures.py, src/_pytest/main.py, src/_pytest/mark/__init__.py, src/_pytest/mark/expression.py, src/_pytest/pytester.py, src/_pytest/skipping.py, src/_pytest/terminal.py, src/_pytest/tmpdir.py, src/_pytest/warning_types.py, testing/code/test_excinfo.py
It's nicer to read without the attr.ib noise.
=> Use attr.s(auto_attribs=True) in more places

src/_pytest/mark/structures.py
This saves 2-3s from pandas collection time.
=> mark/structures: micro-optimize item.keywords/NodeKeywords

src/_pytest/nodes.py, src/_pytest/python.py, testing/deprecated_test.py
This reduces pandas collection time by a couple of seconds  (94081513 function calls -> 88398561 function calls).
=> nodes: micro-optimize _imply_path

.github/workflows/main.yml
=> ci: remove linting job - covered be pre-commit.ci

changelog/7469.feature.rst, doc/en/reference/reference.rst, src/_pytest/hookspec.py, src/_pytest/reports.py, src/pytest/__init__.py
=> Export CollectReport and TestReport

src/_pytest/logging.py
and take advantage of dict unpacking operator.
=> Inline PercentStyleMultiline._update_message

doc/en/reference/reference.rst
=> Remove space inside of dotted attribute

changelog/9351.trivial.rst, doc/en/example/special.rst
This PR closes #9351.
It's a very minor typo :-)
=> Fix output of example test method in special.rst

scripts/release.py
Something minor I noticed in #9371. I'd say let's keep it in the release if nothing else comes up, too minor.
=> Don't thank pytest bot

scripts/prepare-release-pr.py, scripts/release.pre.rst, scripts/release.py
* scripts: Use release branch for changelog URL
With a prerelease, /stable won't show the correct changelog.
* [pre-commit.ci] auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
(cherry picked from commit 21a186bbda5ce2407af6a626023879c8c5809431)
=> [7.0.x] scripts: Use release branch for changelog URL (#9380)

doc/en/deprecations.rst
(cherry picked from commit b691d31897fae46fda0cf0445f5386c54460f09a)
=> [7.0.x] fix typo

changelog/9355.bugfix.rst
(cherry picked from commit 7ae23ff8ae6acdca4862e728bf7187c30d076d6c)
=> [7.0.x] fix python version in changelog message (#9390)

testing/test_session.py
Nothing tests this currently. Make sure it doesn't regress if/when the complex code in `Session.collect` is cleaned up.
=> testing/test_session: add a regression test for an old bug

src/_pytest/_code/code.py
(cherry picked from commit fcef7e49fd9696c6649876067d70366afd13c8f2)
=> [7.0.x] Backport "code: accept any `os.PathLike[str]` in `Traceback.cut`"

src/_pytest/legacypath.py, src/pytest/__init__.py
(cherry picked from commit 69da199f6ed415b1aa609df8b5518951fffb2f2d)
=> [7.0.x] Backport "pytest: bring back direct imports of TempdirFactory, Testdir"

src/_pytest/python.py, src/_pytest/reports.py, testing/test_collection.py
=> Optimizations/fixes around Function `keywords`

doc/en/example/fixtures/test_fixtures_order_autouse_flat.svg, doc/en/reference/fixtures.rst
Adds in the missing flattened graph for autouse fixture order
Closes #9523
=> Autouse linearization graph

.github/workflows/main.yml
macOS apparently can be slow, https://github.com/pytest-dev/pytest/runs/4965510831 for #9556 got cancelled at 91%
=> ci: Bump up timeout

changelog/9355.bugfix.rst, changelog/9396.bugfix.rst, changelog/9404.doc.rst, changelog/9488.deprecation.rst, changelog/9505.doc.rst, changelog/9521.trivial.rst, doc/en/announce/index.rst, doc/en/announce/release-7.0.0.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/getting-started.rst
* Prepare release version 7.0.0
* Add note to changelog
Co-authored-by: pytest bot <pytestbot@gmail.com>
Co-authored-by: Florian Bruhin <me@the-compiler.org>
(cherry picked from commit e37fbe5685d330cbe7819c5a08d0a524df7299bf)
=> Cherry pick 7.0.0 (#9598)

doc/en/index.rst
Only commenting out as I expect to add trainings at PyConDE and possibly PyConIT soon.
Training went well for the curious, with 5 people on-site plus 6 people remotely!
=> doc: Hide done training

testing/test_doctest.py
=> work around test pollution caused by new setuptools mutating global logger level

.github/workflows/update-plugin-list.yml
We don't need this to run for forks (e.g. https://github.com/hugovk/pytest/actions/workflows/update-plugin-list.yml) or create PRs on forks (e.g. https://github.com/hugovk/pytest/pull/1 https://github.com/hugovk/pytest/pull/2 https://github.com/hugovk/pytest/pull/3 https://github.com/hugovk/pytest/pull/5 https://github.com/hugovk/pytest/pull/7 https://github.com/hugovk/pytest/pull/8).
=> CI: Only update the plugin for upstream

.pre-commit-config.yaml, src/_pytest/python.py, src/_pytest/python_api.py, testing/code/test_source.py
This automatically removes the unused imports, and also unusued variables.
=> Add autoflake to pre-commit configuration

AUTHORS, doc/en/talks.rst
Added new edition of book and added myself to AUTHORS.
=> Add the latest book edition of 'Python Testing with pytest'

src/_pytest/python_api.py
=> [style]: fix typo in docstring

AUTHORS, changelog/9726.bugfix.rst, src/_pytest/python_api.py, testing/python/approx.py
=> Remove unnecessary numpy import

CONTRIBUTING.rst
The [status: easy](https://github.com/pytest-dev/pytest/labels/status%3A%20easy) issues are a good place for beginners to start, let's include them in the contrib guide.
Those could fall under either "Fix bugs" or "Implement features", but they tend to be bugs so I put it in that section.
=> Docs: link to easy issues in contributing guide

changelog/9726.bugfix.rst, changelog/9820.bugfix.rst, changelog/9869.bugfix.rst, changelog/9871.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-7.1.2.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/getting-started.rst
Co-authored-by: pytest bot <pytestbot@gmail.com>
(cherry picked from commit df9df5574913b2e7753b8cf6ebbf06ed9fbde10d)
=> Cherry-pick: 7.1.2 (#9881)

doc/en/example/attic.rst, doc/en/example/markers.rst, doc/en/example/parametrize.rst, doc/en/example/simple.rst, doc/en/how-to/assert.rst, doc/en/how-to/cache.rst, doc/en/how-to/capture-warnings.rst, doc/en/how-to/doctest.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/logging.rst, doc/en/how-to/skipping.rst, doc/en/how-to/unittest.rst, doc/en/how-to/usage.rst, doc/en/how-to/writing_hook_functions.rst, doc/en/how-to/writing_plugins.rst, doc/en/how-to/xunit_setup.rst
Found because I was curious what https://pypi.org/project/shed/ does with pytest.
=> doc: Reformat/Modernize some code

doc/en/how-to/logging.rst
=> Add link to python docs on logging levels

changelog/9873.improvement.rst
Didn't realize it was missing before merging #9875. 😓
=> Add CHANGELOG for #9873

src/_pytest/python_api.py
=> Mention use of re_assert for strings in approx docs

AUTHORS, doc/en/how-to/writing_plugins.rst
=> Clarify writing_plugins naming instructions

doc/en/example/parametrize.rst, testing/python/raises.py
=> update does_not_raise docs now that pytest is 3.7+ only

doc/en/reference/reference.rst
=> Fix cross-reference in reference/reference docs

src/_pytest/config/argparsing.py
Related to https://github.com/pytest-dev/pytest/issues/7469
=> Fix partially unknown type

pyproject.toml
See the commit messages for details.
=> Two minor cleanups in pyproject.toml and setup.cfg

doc/en/how-to/plugins.rst
Just simple change after discussion #10284
=> Add allure-pytest to the popular plugins list

doc/en/index.rst
online now: https://www.enterpy.de/veranstaltung-15409-se-0-professionelles-testen-fuer-python-mit-pytest.html
=> doc: Add link for enterPy training

doc/en/explanation/flaky.rst
=> doc: Fix 404 'identify flaky test' link (#10244)

doc/en/index.rst
First day has sold out :sparkles:
=> doc: Add second day for enterPy training

.github/workflows/test.yml
Upgrade actions in `test.yml` workflow:
* `actions/checkout@v3`
* `actions/setup-python@v4`
* `codecov/codecov-action@v3`
=> Bump actions in test.yml

doc/en/explanation/goodpractices.rst
From user https://github.com/pypa/hatch/issues/547
=> Fix packaging example

.github/workflows/backport.yml, .github/workflows/deploy.yml, .github/workflows/prepare-release-pr.yml, .github/workflows/update-plugin-list.yml
=> Update used GitHub Actions to latest versions

doc/en/changelog.rst
Fix some typos, and consolidate two entries for the same feature into one.
Didn't get around to taking a look until now.
=> Edit changelog for 7.2.0

.github/workflows/deploy.yml
=> [2.7.x] Use specific tag in the gh-action-pypi-publish action

.github/dependabot.yml, AUTHORS
Signed-off-by: Ashish Kurmi <akurmi@stepsecurity.io>
=> Update dependabot for GitHub Actions

doc/en/index.rst
Another 20 people who know more about pytest now! :sparkles:
=> Remove done trainings

doc/en/how-to/tmp_path.rst, src/_pytest/tmpdir.py
Some follow-up documentation update for the new `tmp_path` configuration https://github.com/pytest-dev/pytest/pull/10442.
=> Documentation update for the tmp_path configurations

src/_pytest/_argcomplete.py, src/_pytest/_py/path.py, src/_pytest/assertion/rewrite.py, src/_pytest/pathlib.py
Closes https://github.com/pytest-dev/pytest/issues/10547.
=> Use os.sep instead of os.path.sep.

AUTHORS, doc/en/how-to/capture-warnings.rst
Signed-off-by: mvashishtha <mahesh@ponder.io>
Closes #10687
=> DOCS-#10687: Add a note about -W vs filterwarnings.

src/_pytest/hookspec.py, src/_pytest/nodes.py, src/_pytest/reports.py, testing/test_runner.py
* Document that `lineno` is 0-based
* Document that path can be relative, and relative to what.
=> Document the location tuple

doc/en/index.rst
We decided to go remote-only, as we only had one on-site sign-up.
=> Update open training

doc/en/example/fixtures/test_fixtures_order_dependencies.py, doc/en/reference/fixtures.rst
updated the `c` fixture to be a little more consistent with other fixtures in [the corresponding image](https://github.com/pytest-dev/pytest/blob/534d174fd24f8066518e396fbdd559eb7cf7b5a9/doc/en/example/fixtures/test_fixtures_order_dependencies.svg). for example both `e` and `g` both have edges connected with the fixtures that they explicitly depend on
=> made minor updates to fixtures docs

changelog/10782.doc.rst, doc/en/explanation/goodpractices.rst
Closes #10782 
I realize that the change is so small that it may not have required a new file in the `changelog` folder, so feel free to delete it.
=> Fix example in the documentation (#10782)

doc/en/index.rst
Keeping the source as a comment, as I might add the Europython one soon-ish.
Went great again, with 10 people now having three days worth of pytest knowledge :)
=> doc: Remove done training

AUTHORS, doc/en/reference/reference.rst, src/_pytest/helpconfig.py
I noticed that the help section only mentions `pytest.ini`, `tox.ini`, and `setup.cfg`, so I updated it to include `pyproject.toml` as well.
=> Include `pyproject.toml` in help section that lists out config files with ini-options

changelog/10226.improvement.rst, changelog/10525.feature.rst, changelog/10658.improvement.rst, changelog/10669.trivial.rst, changelog/10710.improvement.rst, changelog/10727.improvement.rst, changelog/10743.bugfix.rst, changelog/10755.feature.rst, changelog/10765.bugfix.rst, changelog/10782.doc.rst, changelog/10840.improvement.rst, changelog/1904.bugfix.rst, changelog/6267.improvement.rst, changelog/7431.feature.rst, changelog/8141.feature.rst, doc/en/announce/index.rst, doc/en/announce/release-7.3.0.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/reportingdemo.rst, doc/en/getting-started.rst
(cherry picked from commit cec5bfe0588adaa2ca36c72c724378982db6410a)
=> Cherry pick 7.3.0 release notes

changelog/10169.bugfix.rst, changelog/10987.bugfix.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, testing/test_collection.py, testing/test_conftest.py
(cherry picked from commit 76d15231f5749ca26a180df02ef2e5c138aaefc8)
=> [7.3.x]  Consider testpaths for initial conftests

.github/workflows/stale.yml
Opening this PR to test/tweak the "close stale issues" workflow.
=> Tweak close stale issues

doc/en/changelog.rst, doc/en/conf.py, doc/en/reference/reference.rst, src/_pytest/capture.py, src/_pytest/tmpdir.py, src/_pytest/warning_types.py, testing/test_python_path.py
=> Spelling and grammar fixes

src/_pytest/fixtures.py, src/_pytest/pathlib.py, src/_pytest/python.py
While working on some other changes I've accrued these small commits. It will be good to have them in `main`.
=> Small fixes and improvements

doc/en/reference/plugin_list.rst, scripts/update-plugin-list.py
This is a result of question #11066.
No doc updates are included as this is a script to be run by pytest's devs. It seems to not have tests either, but checked this to work OK IRL.
For the same reasons explained above, I didn't touch the changelog or included myself in AUTHORS file.
=> Introduced a hardcoded list of project to include as plugins beyond those found by their names.

doc/en/example/simple.rst
The example in the [docs](https://docs.pytest.org/en/7.1.x/example/simple.html#package-directory-level-fixtures-setups) for a package/directory-level fixture uses a session scope. Wouldn't a package scope make more sense, since it tears down the fixture after the last test in the package?
=> Update fixture scope in package/directory fixture example.

changelog/11081.improvement.rst
Refs https://github.com/pytest-dev/pytest/pull/11082#issuecomment-1585762194
=> changelog: add note to `norecursedir`/`pytest_ignore_collect` change

changelog/10169.bugfix.rst, changelog/10894.bugfix.rst, changelog/10987.bugfix.rst, changelog/10999.bugfix.rst, changelog/11028.bugfix.rst, changelog/11054.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-7.3.2.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/getting-started.rst
(cherry picked from commit 5dcd2be4661bc606b3399bff3614c0691ce9c13f)
=> Cherry-pick 7.3.2 release notes

doc/en/index.rst
Something a bit different (more advanced topics) this time, let's see how it goes!
=> doc: Add ep2023 training

changelog/10831.bugfix.rst, changelog/10872.improvement.rst, changelog/10901.feature.rst, changelog/10907.improvement.rst, changelog/10940.improvement.rst, changelog/10991.improvement.rst, changelog/11005.improvement.rst, changelog/11013.improvement.rst, changelog/11031.trivial.rst, changelog/11043.improvement.rst, changelog/11068.bugfix.rst, changelog/11081.improvement.rst, changelog/11104.bugfix.rst, changelog/1904.bugfix.rst, changelog/7781.bugfix.rst, changelog/8711.improvement.rst, changelog/9146.doc.rst, doc/en/announce/index.rst, doc/en/announce/release-7.4.0.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/getting-started.rst, doc/en/reference/reference.rst
(cherry picked from commit fb03d1388b002f63973c663cb4929908a2ca81f5)
=> Cherry-pick 7.4.0 release notes

changelog/7363.breaking.rst, doc/en/reference/reference.rst, src/_pytest/warning_types.py, src/_pytest/warnings.py, src/pytest/__init__.py, testing/acceptance_test.py, testing/deprecated_test.py, testing/test_config.py, testing/test_nose.py, testing/test_warnings.py
Per our backward compatibility policy.
=> Change PytestRemovedIn8Warning to error by default, add PytestRemovedIn9Warning

doc/en/index.rst
One more! [pytest: Professionelles Testen (nicht nur) für Python > Workshop-Tage](https://workshoptage.ch/workshops/2023/pytest-professionelles-testen-nicht-nur-fuer-python-2/)
=> Update open trainings

.pre-commit-config.yaml, doc/en/index.rst, pyproject.toml, testing/_py/test_local.py
Follow on from https://github.com/pytest-dev/pytest/issues/11151 / https://github.com/pytest-dev/pytest/pull/11152.
Update and remove a few other bits and pieces only needed for Python <= 3.7.
=> Update docs and code after dropping EOL 3.7

testing/python/fixtures.py
This test makes clear the need for the `_check_scope()` call in the `pytest_setup_fixture` impl in fixtures.py ([link](https://github.com/pytest-dev/pytest/blob/02ba39bfcd2a14be80e30afd9b72e7f60c61cb38/src/_pytest/fixtures.py#L1162)), which otherwise seems redundant with the one in `_compute_fixture_value` ([link](https://github.com/pytest-dev/pytest/blob/02ba39bfcd2a14be80e30afd9b72e7f60c61cb38/src/_pytest/fixtures.py#L725)).
=> fixtures: add a test for a currently non-covered scope mismatch scenario

doc/en/index.rst
Got a room packed with people (who all now have pytest stickers too :upside_down_face:) and everyone seemed to be happy with it, so great success I'd say!
=> Remove ep2023 training

doc/en/how-to/usage.rst, src/_pytest/config/__init__.py, src/_pytest/config/findpaths.py
These are 3 small commits I collected while looking at some rootdir issues.
=> Rootdir tweaks

AUTHORS, src/_pytest/config/__init__.py, src/_pytest/fixtures.py
These are two minor cherry-picks from @sadra-barikbin's #11243, just to make the diff there smaller. Reviewed by me.
=> 11243 cherry picks

doc/en/how-to/usage.rst
Creating this PR for https://github.com/pytest-dev/pytest/issues/11107
=> Modifying doc for run tests by nodeid section

changelog/11218.trivial.rst, src/_pytest/doctest.py, src/_pytest/fixtures.py, src/_pytest/python.py, testing/python/fixtures.py, testing/test_legacypath.py
=> fixtures: make FixtureRequest abstract, add TopRequest subclass

.github/workflows/update-plugin-list.yml
=> use python 3.11 for update-plugin-list

doc/en/explanation/anatomy.rst
=> Update typo anatomy.rst

AUTHORS, testing/_py/test_local.py
* *removed issue with pre-commit errors with mypy and flake8.*
closes #11356
=> fix: fixing an issue with pre-commit with mypy and flake8

src/_pytest/doctest.py, src/_pytest/fixtures.py, src/_pytest/python.py
These commits are some small improvements to the fixtures code that I've collected while looking at the code.
=> Fixtures tweaks

changelog/11237.bugfix.rst, changelog/11306.bugfix.rst, changelog/11367.bugfix.rst, changelog/11391.doc.rst, changelog/11394.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-7.4.2.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/reportingdemo.rst, doc/en/getting-started.rst
(cherry picked from commit b0c4775a28aebcd3d3d6394ebb36838df01f809d)
=> Cherry-pick release-7.4.2

scripts/update-plugin-list.py
I add my plugin to the list manually.
=> Closes #11435

CONTRIBUTING.rst
=> Update CONTRIBUTING.rst to mention tag fetches

scripts/prepare-release-pr.py
Tested this to trigger the deploy of #11546.
=> Add deploy instructions using the command-line

.github/workflows/deploy.yml, .github/workflows/test.yml
This should fix the action for Python 3.12.
Ref: hynek/build-and-inspect-python-package#72
=> Update build-and-inspect-python-package action

.github/workflows/deploy.yml, .github/workflows/test.yml
This should fix the action for Python 3.12.
Ref: hynek/build-and-inspect-python-package#72
(cherry picked from commit 247436819a49a4c21c0926ed0a12bfe7e8166237)
=> [7.4.x] Update build-and-inspect-python-package action

AUTHORS, CONTRIBUTING.rst
=> Created link to PEP-8 in documentation

doc/en/how-to/assert.rst
=> Adjustments to assert raises docs

doc/en/reference/fixtures.rst
=> Typo in fixtures.rst

changelog/11091.doc.rst, changelog/11146.bugfix.rst, changelog/11572.bugfix.rst, changelog/11710.bugfix.rst, changelog/7966.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-7.4.4.rst, doc/en/changelog.rst, doc/en/getting-started.rst
(cherry picked from commit 18dcd9d38d18fc01bf1f7f5f60db69f785957101)
=> Cherry-pick 7.4.4 release notes

AUTHORS, doc/en/reference/reference.rst, src/_pytest/mark/__init__.py
Clarified `markers` ini property. Fix #11738
-->
=> Clarified `markers` ini property. Fix #11738

scripts/generate-gh-release-notes.py
=> Update docstring of scripts/generate-gh-release-notes.py

src/_pytest/fixtures.py, src/_pytest/nodes.py
A couple of remaining `fspath` cleanups.
=> Small `fspath` cleanups

src/_pytest/config/__init__.py, src/_pytest/fixtures.py, src/_pytest/python.py, src/_pytest/setuponly.py
A few small cleanups -- please see the commits.
=> A few cleanups

testing/python/metafunc.py
Ref: https://github.com/pytest-dev/pytest/pull/11825#issuecomment-1894094641
=> testing: temporarily disable test due to hypothesis issue

changelog/11233.feature.rst, changelog/11706.bugfix.rst, changelog/11758.bugfix.rst, changelog/11825.improvement.rst, changelog/9765.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.0.0rc2.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/example/simple.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/output.rst
(cherry picked from commit 97960bdd148972b2f26bd9b336163e590bbc4c6b)
=> Prepare release version 8.0.0rc2

.github/workflows/deploy.yml
Backport of https://github.com/pytest-dev/pytest/pull/11839.
=> [8.0.x] Properly attach packages to the GH release notes (#11839)

doc/en/how-to/writing_plugins.rst
I tried to update this doc to match reality, though reality is quite messy...
=> doc/writing_plugins: correct inaccuracies re. initial conftest loading

src/_pytest/runner.py
- Reduce the common stacktrace by an entry - this is mostly for benefit of devs looking at crash logs.
- Reduce 6 slow `ihook` calls per test to 3.
Replaces #11851.
=> runner: inline `call_runtest_hook`

changelog/11842.bugfix.rst, changelog/11861.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.0.0.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
(cherry picked from commit 24c681d4eeaad22ba26c5bcf6958e0476ae37a89)
=> Cherry pick 8.0.0 release notes

src/_pytest/pathlib.py
The function currently uses `find_suffixes` which iterates the entire directory searching for files with the given suffix. In some cases though, like in pytest's selftest, the directory can get big:
$ ls /tmp/pytest-of-ran/pytest-0/
7686
and iterating it many times can get slow.
This doesn't fix the underlying issue (iterating the directory) but at least speeds it up a bit by using `os.scandir` instead of `path.iterdir`. So `make_numbered_dir` is still slow for pytest's selftests, but reduces ~10s for me.
=> pathlib: speed up `make_numbered_dir` given a large tmp root

doc/en/how-to/assert.rst
=> fix incorrect examples for group_contains

.pre-commit-config.yaml, doc/en/deprecations.rst, doc/en/funcarg_compare.rst, doc/en/historical-notes.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/skipping.rst, doc/en/reference/reference.rst
Follow-up to #11898 prior to migrating to ruff.
=> Upgrade blacken-doc to black's 2024 style

src/_pytest/compat.py, src/_pytest/python.py, src/_pytest/python_api.py
=> compat: a couple of minor cleanups

pyproject.toml, setup.cfg
Remove some no longer needed sections, and move the mypy config to pyproject.toml.
=> Some setup.cfg cleanups

testing/python/metafunc.py
This reverts commit 5cd0535395541d8940035418b368331318002199.
=> Revert "testing: temporarily disable test due to hypothesis issue (#1836)"

pyproject.toml, src/_pytest/compat.py, src/_pytest/junitxml.py, src/_pytest/python.py, src/_pytest/terminal.py, testing/test_assertrewrite.py
Some opinionated fixes added to lint (from pylint but using the fast ruff implementation with autofix). There's an embedded performance improvement, that I'll create a MR specifically for (b922270ce) if the other changes are too controversial to be merged.
=> [pre-commit] Add some autofixable refactor rules from pylint

changelog/11875.bugfix.rst, changelog/11879.bugfix.rst, changelog/11906.bugfix.rst, changelog/11907.bugfix.rst, changelog/11929.bugfix.rst, changelog/11937.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.0.1.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/getting-started.rst, doc/en/reference/reference.rst
(cherry picked from commit 68524d48586e7f8d070fc1146e5ff90e770d0382)
=> Cherry pick 8.0.1 release notes

changelog/11895.bugfix.rst, changelog/11953.bugfix.rst, changelog/12021.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.0.2.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
(cherry picked from commit e53f79893212391c0bada5f1628b977371a09434)
=> Cherry pick 8.0.2 release notes

README.rst, doc/en/index.rst
=> docs: update plugins number

changelog/10865.improvement.rst, changelog/11311.improvement.rst, changelog/11475.feature.rst, changelog/11475.improvement.rst, changelog/11653.feature.rst, changelog/11785.trivial.rst, changelog/11790.doc.rst, changelog/11801.improvement.rst, changelog/11850.improvement.rst, changelog/11904.bugfix.rst, changelog/11962.improvement.rst, changelog/11978.improvement.rst, changelog/12011.bugfix.rst, changelog/12014.bugfix.rst, changelog/12039.bugfix.rst, changelog/12047.improvement.rst, doc/en/announce/index.rst, doc/en/announce/release-8.1.0.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/example/reportingdemo.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst, doc/en/reference/reference.rst
(cherry picked from commit 0a536810dc5f51dac99bdb90dde06704b5aa034e)
=> Cherry-pick 8.1.0 release notes

TIDELIFT.rst
=> add myself as tidelifter

doc/en/changelog.rst
=> Yank version 8.1.0

changelog/11475.bugfix.rst, changelog/12069.trivial.rst, doc/en/announce/index.rst, doc/en/announce/release-8.1.1.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
Prepare release 8.1.1
(cherry picked from commit abb0cf4922919e3554bd16e9fc540bc107289ee9)
=> Cherry pick release 8.1.1

src/_pytest/stash.py
=> doc: add versionadded to `Stash` and `StashKey`

doc/en/explanation/flaky.rst
=> Add research item in doc

doc/en/reference/reference.rst
Added a missing word and fixed a typo.
=> docs: fix typo

.github/workflows/stale.yml
To avoid confusion, see e.g. https://github.com/pytest-dev/pytest/issues/12123#issuecomment-2035283472
=> Improve stale bot messages

src/_pytest/pathlib.py
Makes the logic more straightforward IMO.
=> Refactor insert_missing_modules function

changelog/12114.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.1.2.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
(cherry picked from commit 7df3dbc545b4b4deb2148683cd02f774b2d19fd8)
=> cherry-pick release-8.1.2

.pre-commit-config.yaml, pyproject.toml, src/_pytest/debugging.py, src/_pytest/hookspec.py
A few tweaks to the pre-commit config.
=> pre-commit tweaks

doc/en/index.rst
We now have a dedicated repo for infos around the sprint.
=> doc: update sprint repo link

doc/en/changelog.rst
=> changelog: document unittest 8.2 change as breaking

changelog/12120.bugfix.rst, changelog/12191.bugfix.rst, changelog/12300.bugfix.rst, changelog/12308.bugfix.rst, changelog/12333.trivial.rst, changelog/12334.improvement.rst, doc/en/announce/index.rst, doc/en/announce/release-8.2.1.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
(cherry picked from commit 66ff8dffdf9eee9b3dd6686de34542c49ff80dcd)
=> Cherry pick 8.2.1 release notes

changelog/12290.doc.rst, changelog/12355.bugfix.rst, changelog/12356.doc.rst, changelog/12363.doc.rst, changelog/12367.bugfix.rst, changelog/12381.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.2.2.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
Prepare release 8.2.2
(cherry picked from commit f3a494cca3bf0491f7277abff229a1331382ae26)
=> Cherry-pick 8.2.2 release notes

doc/en/contact.rst
shouldn't have been there the last 8 years already
=> remove my contact details 

src/_pytest/doctest.py
=> Cleanup MockAwareDocTestFinder.

src/_pytest/_code/code.py, src/_pytest/config/__init__.py, src/_pytest/debugging.py, src/_pytest/fixtures.py, src/_pytest/main.py, src/_pytest/mark/structures.py, src/_pytest/nodes.py, src/_pytest/stepwise.py, src/_pytest/unittest.py, testing/code/test_excinfo.py
It's better not to use it when possible.
=> Avoid some `TYPE_CHECKING`

src/_pytest/_io/terminalwriter.py, testing/test_terminal.py
The first commit intends to help PR #12304 to be cleaner. No functional changes intended.
I also improved a couple of UsageErrors in the 2nd commit.
=> terminalwriter: small refactor of pygments code, improve usage errors

.readthedocs.yml
=> 🧪 Bump RTD env to the latest LTS Ubuntu & Python

changelog/12493.contrib.rst
This is a follow-up for #12493.
=> 📝 Add a change note for PR #12493

doc/en/contact.rst
=> Update `contact.rst`: Update Matrix link

doc/en/index.rst
Once again, a room of ~100 people who now know more about pytest! :sparkles:
=> Remove done Europython training

changelog/12652.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.3.2.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
cherry pick changelog from the 8.3.2 release
=> cherry pick 8.3.2 changelog

RELEASING.rst
Reverts pytest-dev/pytest#9606
See https://github.com/pytest-dev/pytest/issues/12611#issuecomment-2245626409
=> Revert "doc: Add changing RTD version to checklist"

doc/en/contact.rst
As part of onboarding Pierre to the core team.
=> Add Pierre to official contacts

doc/en/reference/reference.rst
Looks like these were removed previously.
=> Remove missing msg parameter from docs

.git-blame-ignore-revs, AUTHORS
Hello,
As told in the issue #13033 that this PR closes, the file name in a comment about the usage of *.git-blame-ignore-revs* was wrong.
Best regards,
Nathan Rousseau / le-chartreux
=> Wrong Comment in .git-blame-ignore-revs (closes #13033)

.pre-commit-config.yaml
=> pre-commit: add zizmor hook

LICENSE
Reverts pytest-dev/pytest#13097, see https://github.com/pytest-dev/pytest/pull/13097#issuecomment-2567045639
=> Revert "Update LICENSE, fix copyright license year"

src/_pytest/hookspec.py
=> Fix example in pytest_collection_modifyitems

doc/en/changelog.rst
Towncier -> Towncrier
Also in https://github.com/pytest-dev/pytest/releases/tag/8.3.5
=> chore(changelog) Minor typo fix

doc/en/index.rst
Another successful training, and the next ones already in the pipeline! (also proposed to Europython, but no decision there yet)
=> doc: Update trainings

.github/FUNDING.yml
=> Enable GitHub Sponsors and thanks.dev in FUNDING.yml

changelog/13461.bugfix.rst, changelog/13477.bugfix.rst, changelog/13492.doc.rst, changelog/13497.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.4.1.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst
(cherry picked from commit 08571152685ab5606efeb879310cb647fb8de50d)
=> Cherry pick 8.4.1 release notes
