pytest-dev/pytest

doc/en/how-to/writing_hook_functions.rst
Just noticed it, can be confusing.
=> Fix syntax typo in writing_hook_functions.rst

src/_pytest/compat.py, src/_pytest/python.py
Since Python 3.7, there is `re.Pattern` for this, but since we need to
support Python 3.6, can use `typing.Pattern` which works as well.
=> compat: replace REGEX_TYPE with typing.Pattern

src/_pytest/assertion/rewrite.py, src/_pytest/config/__init__.py
The problem with `@lru_cache` on methods is that it also captures `self` and leaks it until the entry is evicted (if ever).
I was able to restore the caching in both cases (one straightforward case in the first commit, the other in the second commit).
=> Avoid `@lru_cache` on methods

changelog/5196.feature.rst, src/_pytest/python.py, testing/python/collect.py
Fixes #5196. Closes #7848.
This PR updates @asottile's PR #7848 to also ensure that tests from base classes are ordered before tests defined in the subclasses.
Besides pytest's tests, I also tested it on two projects (using Python 3.9.7):
- pytest: the collection tree is the same. Collection time goes from 5.81s to 3.51s.
- pandas: the collection tree is almost the same, except 2 test classes where tests from base classes are now ordered before the subclasses (for reference, these are `TestDataFrame(Generic)`, `TestCategoricalIndex(Base)`). I think this behavior change is good. Collection time goes from 65.89s to 45.80s.
The main speedup comes from avoiding `inspect.getsource()` calls on test class objects, used previously to manually sort by definition order. The function is slow, and I …
=> py36+ tests are definition ordered [v2]

src/_pytest/main.py
See for reference #9125. From my measurements it is not *that* extreme, however I can confirm it shaves off ~5s from pandas collection time.
=> main: avoid Path(Path(...)) calls, they're slow

.coveragerc
These are assertions that should never trigger.
=> coverage: add assert_never to exclude_lines

src/_pytest/mark/structures.py
`normalize_mark_list` shows up in pandas collection profiles. It's simple enough to improve.
=> mark/structures: slightly optimize some functions

.github/workflows/main.yml, changelog/8133.trivial.rst, pyproject.toml, scripts/release.py, setup.cfg, tox.ini
and use SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYTEST
fixes #8133
=> fixes #8133: migrate to setuptools_scm 6.x 

doc/en/explanation/fixtures.rst
=> Add note about fixture teardown and SIGTERM and SIGQUIT signals

changelog/8818.trivial.rst, doc/en/Makefile, doc/en/builtin.rst, doc/en/example/markers.rst, doc/en/example/nonpython.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/example/reportingdemo.rst, doc/en/example/simple.rst, doc/en/getting-started.rst, doc/en/how-to/assert.rst, doc/en/how-to/cache.rst, doc/en/how-to/capture-stdout-stderr.rst, doc/en/how-to/capture-warnings.rst, doc/en/how-to/doctest.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/output.rst, doc/en/how-to/parametrize.rst, doc/en/how-to/tmp_path.rst, doc/en/how-to/unittest.rst, doc/en/how-to/usage.rst, doc/en/how-to/writing_plugins.rst, doc/en/index.rst, doc/en/reference/reference.rst, tox.ini
#4270 introduced per tox env pytest cachedirs and
never protected regendoc against it
closes #8818
=> fix #8818 - run regendoc without tox cachedir

changelog/9114.feature.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, src/_pytest/pythonpath.py, testing/test_config.py, testing/test_pythonpath.py
Closes #9114
Closes #8964
I made a lot of assumptions here, so please comment if necessary.  
- implemented as a plugin in a new file.  
- test is in a new test file. 
- tests make sense to me, but if they are not clear, please let me know.  
- The changelog entry seems very terse, but I'm at a loss as to how to expand it, at the moment.  
Question:  
- If this is accepted, I assume that docs will need modified. Is that usually part of the initial PR? or does that come later in the process?
Implementation is based on:  
- plugins pytest-pythonpath, pytest-srcpaths
- comment from @bluetech in the issue thread regarding names, hook function to use, and reversing the order of path inclusion
=> Add a `pythonpath` setting to allow paths to be added to `sys.path`.

changelog/9163.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
These are new additions in Python 3.8:
https://docs.python.org/3/whatsnew/3.8.html#ast
I'm not sure what's using them but we should set them anyway.
=> rewrite: fixup end_lineno, end_col_offset of rewritten asserts

changelog/8994.improvement.rst, src/_pytest/nodes.py, testing/test_nodes.py
This commit add the fullname on the Node construction warning.
Also add a test for this case.
closes #8994
=> Show fullname on direct Node construction warning

changelog/9023.feature.rst, src/_pytest/assertion/truncate.py, src/_pytest/assertion/util.py, testing/test_assertion.py
follow-up to #1314, for similar reasons
closes #9023
=> always show full diff in ci

src/_pytest/mark/structures.py, testing/test_collection.py
Regressed in c4b9b14a4 -- the `set` stuff had a reason which I had missed.
=> mark/structures: fix NodeKeywords.{__iter__,__len__} given duplicates

changelog/9131.bugfix.rst, src/_pytest/pastebin.py, testing/test_pastebin.py
This fixes an issue that I am seeing when adding `--pastebin=failed` to pytest that results in a `bad response: HTTP Error 405: Not Allowed` error. Small repro below:
My environment:
* python 3.9.5 and also tried 3.6.10
* pytest 6.2.5
* Ubuntu 20.04.2 LTS and 18.04.5 LTS
test_fail.py:
```python
import pytest
def test_fail():
assert False
```
cmd: `pytest --pastebin=failed --no-header test_fail.py`
output: 
```
================================= test session starts =================================
collected 1 item
test_fail.py F                                                                  [100%]
====================================== FAILURES =======================================
______________________________________ test_fail ______________________________________
tmpdir = …
```
=> Update pastebin URL from bpaste to bpa.st

.readthedocs.yml, changelog/9242.doc.rst, doc/en/conf.py
Read the Docs recently [added support for Ubuntu 20.04][2004]. This has
a newer version of TeX Live with better Unicode support. Specifically,
it is now possible to configure a list of fallback fonts to try for
characters missing from the current font, instead of displaying question
marks.
In the existing PDF docs, you can see some missing Unicode characters in
the descriptions for the pytest-addons-test and pytest-hammertime
plugins, which contain placeholder question marks.
Sadly, to get colour unicode support in PDFs, we will need to wait for
even newer software from Read the Docs, e.g., the `LuaHBTeX, Version
1.12.0 (TeX Live 2020/Debian)` of Ubuntu 20.10, to which one can add
`"Noto Color Emoji:mode=harf;",` to the fallback list.
[2004]: …
=> Use Ubuntu 20.04, lualatex for readthedocs builds

AUTHORS, changelog/8990.bugfix.rst, src/_pytest/pathlib.py, src/_pytest/terminal.py, testing/logging/test_reporting.py
Closes #8990 
* Correct input arg type passed to `_pytest.pathlib.bestrelpath` (expects a `Path` object).
* Associated test.
* Type annotations added.
=> Use correct input arg type for _bestrelpath

doc/en/adopt.rst, doc/en/announce/release-2.9.0.rst, doc/en/announce/release-2.9.1.rst, doc/en/announce/release-2.9.2.rst, doc/en/backwards-compatibility.rst, doc/en/changelog.rst, doc/en/conf.py, doc/en/deprecations.rst, doc/en/explanation/fixtures.rst, doc/en/historical-notes.rst, doc/en/how-to/capture-warnings.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/logging.rst, doc/en/how-to/monkeypatch.rst, doc/en/how-to/nose.rst, doc/en/py27-py34-deprecation.rst, doc/en/reference/customize.rst, doc/en/reference/reference.rst, src/_pytest/junitxml.py, src/_pytest/monkeypatch.py
This PR replaces referencing Github issues via hardcoded URLs to https://github.com/pytest-dev/pytest/issues by using `sphinx.ext.extlinks` plugin.
Old usage example:
```
`#123 <https://github.com/pytest-dev/pytest/issues/123>`__
```
New usage replacement:
```
:issue:`123`
```
This PR partially addresses #9081.
=> Replace hardcoded links to Github issues with extlinks

changelog/9272.bugfix.rst, src/_pytest/nose.py, src/_pytest/python.py, testing/test_nose.py
Fixes #9272.
Fixing the issue directly in the plugin is somewhat hard, so do it in core, by moving the aliasing directly to the pytest xunit fixture support. Since the plugin is going to be deprecated, I figure it's OK to cheat a bit.
=> nose: fix class- and module-level fixture behavior

doc/en/announce/release-2.9.0.rst, doc/en/announce/release-2.9.1.rst, doc/en/announce/release-2.9.2.rst, doc/en/changelog.rst, doc/en/conf.py, doc/en/historical-notes.rst
This PR replaces referencing Github pull requests via hardcoded URLs to https://github.com/pytest-dev/pytest/pulls by using `sphinx.ext.extlinks` plugin.
Old usage example:
```
`#123 <https://github.com/pytest-dev/pytest/pull/123>`__
```
New usage replacement:
```
:pull:`123`
```
This PR partially addresses #9081.
=> Replace hardcoded links to Github pull requests with extlinks

doc/en/changelog.rst, doc/en/conf.py
This PR replaces referencing Python bugs via hardcoded URLs to https://bugs.python.org/ by using `sphinx.ext.extlinks` plugin.
Old usage example:
```
`bpo-123 <https://bugs.python.org/issue123>`__
```
New usage replacement:
```
:bpo:`123`
```
This PR partially addresses #9081.
Note that ATM there is only one reference to BPO in the docs. Introducing a new extlink just for one URL thus may be a complete overkill! Maybe it's wise to close this PR w/o merging.
=> Replace hardcoded links to Python bugs with extlinks

src/_pytest/nodes.py, testing/test_nodes.py
=> nodes: keep plugins which subclass Item, File working for a bit more

src/_pytest/legacypath.py
Fixes #9280. Closes #9284.
Previous approach didn't support pytester being loaded using `pytest_plugins = "pytester"` in a conftest.
Replaces #9284 while keeping the proper behavior instead of a revert.
=> legacypath: support late-loading of pytester plugin

changelog/8822.improvement.rst, src/_pytest/python.py, testing/python/fixtures.py
Before this PR:
```
caplog -- .tox/py39-pyqt515/lib/python3.9/site-packages/_pytest/logging.py:476
Access and control log capturing
```
with it:
```
caplog -- .../_pytest/logging.py:491
Access and control log capturing.
```
Note that we still display the full path for fixtures from plugins, though. I think a fix for that would be a bit more involved, and probably not something for 7.0.
Fixes #8822
=> Elide pytest-internal paths for --fixtures

tox.ini
See https://github.com/twisted/towncrier/issues/346
Closes #8817, supersedes #9045 and #9046.
@nicoddemus Any particular reason you pinned to 18.6 in #9045? I think 19.9 is the newest non-affected version.
=> Pin towncrier to 19.9.0

changelog/9277.breaking.rst, doc/en/deprecations.rst, src/_pytest/deprecated.py, src/_pytest/junitxml.py, src/_pytest/main.py, src/_pytest/mark/__init__.py, src/_pytest/nodes.py, src/_pytest/python.py, src/_pytest/terminal.py, src/pytest/__init__.py, src/pytest/collect.py, testing/deprecated_test.py, testing/python/collect.py, testing/python/integration.py, testing/test_cacheprovider.py, testing/test_collection.py, testing/test_junitxml.py, testing/test_nose.py, testing/test_session.py
Given a test file like this:
```py
class TestIt:
def test_it(): pass
```
the collection tree is
```
<Module test_file.py>
<Class TestIt>
<Instance ()>
<Function test_it>
```
- The `obj` of the `Module` is the `test_file.py` module object
- The `obj` of the `Class` is the class type `TestIt`.
- The `obj` of the `Instance` is an *instance* of `TestIt` i.e. `TestIt()`. An instance is created when the `Instance` does its `collect()`, to pick up fixtures, and is (mutably) refreshed by each child `Function` setup phase, which each want a fresh instance.
- The `obj` of the `Function` is the bound method `test_it`.
So the main thing encapsulated by `Instance` is the instantiation of test classes. It provides the property that for a given `Function` item `func`, `getattr(func.parent, …
=> [RFC] python: remove the `Instance` collector node

doc/en/announce/release-2.9.0.rst, doc/en/announce/release-2.9.1.rst, doc/en/announce/release-2.9.2.rst, doc/en/changelog.rst, doc/en/conf.py, doc/en/history.rst
This PR replaces referencing Github users via hardcoded URLs to `https://github.com/{username}` by using `sphinx.ext.extlinks` plugin.
Old usage example:
```
`@hoefling <https://github.com/hoefling>`__
```
New usage replacement:
```
:user:`hoefling`
```
This PR partially addresses #9081.
=> Replace hardcoded links to Github user accounts with extlinks

testing/test_assertrewrite.py
This at least will allow our PRs to have fully green CI results.
Temporary while this is being investigated by @RonnyPfannschmidt.
Related to #9298
=> Skip TestPyCacheDir.test_sys_pycache_prefix_integration on Windows + Python 3.9

changelog/7480.improvement.rst, changelog/9308.breaking.rst, doc/en/backwards-compatibility.rst, src/_pytest/deprecated.py, src/_pytest/warning_types.py, src/_pytest/warnings.py, src/pytest/__init__.py, testing/deprecated_test.py, testing/test_mark.py, testing/test_terminal.py, testing/test_warnings.py
This fixes #9308. The first attempt #8837 ran into trouble because some deprecations weren't ready for removal. I make things work by adding `PytestRemovedInX` warnings. Please see the commit messages for more details.
The reason I worked on this is I'm eager to remove one deprecation - the `FILLFUNCARGS` - and don't want to wait until pytest 8.1 for that :)
=> Change deprecation warnings into errors for 7.0 release, using a new mechanism

changelog/9308.breaking.rst, doc/en/backwards-compatibility.rst
Follow-up to #9309.
The issue in the changelog broke the docs build with:
doc/en/_changelog_towncrier_draft.rst:47: WARNING: Inline literal start-string
without end-string.
The second change isn't as critical, but caused the text to be rendered as
monospace including the tilde (i.e. `~pytest.PytestDeprecationwarning`).
=> Fix doc issues in deprecation change

.readthedocs.yml
Adds HTML zip output to the docs.
We could also use the `all` keyword.
Closes #9340 .
=> Add HTML output for docs

AUTHORS, src/_pytest/reports.py
This PR fixes an issue where empty workerinfo lines are displayed (resulting in an unnecessary newline in that case) when using xdist. Closes https://github.com/pytest-dev/pytest/issues/9316.
=> Do not display empty worker info

changelog/8144.feature.rst, doc/en/deprecations.rst, src/_pytest/config/compat.py, src/_pytest/doctest.py, src/_pytest/hookspec.py, src/_pytest/main.py, src/_pytest/python.py, src/_pytest/terminal.py, testing/acceptance_test.py, testing/conftest.py, testing/deprecated_test.py, testing/example_scripts/collect/package_infinite_recursion/conftest.py, testing/example_scripts/fixtures/custom_item/conftest.py, testing/example_scripts/issue88_initial_file_multinodes/conftest.py, testing/plugins_integration/requirements.txt, testing/python/collect.py, testing/test_collection.py, testing/test_conftest.py, testing/test_junitxml.py, testing/test_skipping.py, testing/test_terminal.py
=> Rename pathlib hook parameters 

changelog/7259.deprecation.rst, changelog/8144.feature.rst, changelog/8251.feature.rst, changelog/9341.doc.rst, doc/en/deprecations.rst, src/_pytest/nodes.py, src/_pytest/python.py
Closes #9283
IMHO the last step towards a 7.0 rc (finally! :sweat_smile:), unless I missed something (if so, please yell now!).
I also fixed some other issues I noticed while looking through the reference docs.
=> Improve reference and path/fspath docs

README.rst
This reverts commit 15989ddc8f20e49602858e6e4a2631b71e8b9ef1.
Reverts #8945, thus reintroducing #8926 temporarily, but we should be close to
the 7.0.0 release now, where this is the correct URL to use.
Closes #8831 as follow-up to #8858.
=> Revert "Fix Dead link in README for 'assert statements' "

changelog/8733.breaking.rst, src/_pytest/capture.py
Fix #8733
Closes #8847
* Also add types-atomicwrites as extras to mypy pre-commit hook (Windows)
=> Drop readline workaround introduced in #1281

doc/en/example/nonpython/conftest.py
Follow up to #9363
See https://github.com/pytest-dev/pytest/pull/9371/files#diff-523905715b1e18335a8ff84ab46e2c3a28f2c5fec4c63e001574286339fb8c74R30
=> Fix hook param name in nonpython example

doc/en/announce/release-7.0.0rc1.rst
The changelog does not exist at /stable because an rc isn't stable...
=> Fix changelog URL in 7.0.0rc1 announcement

AUTHORS, changelog/9355.bugfix.rst, src/_pytest/_code/source.py, testing/code/test_source.py
=> [7.0.x] Fixed error message prints function decorators when using assert in Python 3.9 and above

scripts/prepare-release-pr.py, scripts/release.pre.rst, scripts/release.py
With a prerelease, /stable won't show the correct changelog.
Can't really test this until the next prerelease though... See #9379.
Should be backported just in case we need a rc2.
=> scripts: Use release branch for changelog URL

doc/en/announce/release-7.0.0rc1.rst
The changelog does not exist at /stable because an rc isn't stable...
(cherry picked from commit 5cb50fa13cfc2485f4ea4fcac4eec295aa93f94b)
=> [7.0.x] Fix changelog URL in 7.0.0rc1 announcement (#9379)

RELEASING.rst
After this is merged, should tag commit 0ad452bcb with `7.1.0.dev0`.
=> RELEASING: should also tag dev0 for prereleases

src/_pytest/python_api.py
This makes the error traceback point directly to the offending usage, rather
than to the internal `Approx.__bool__` method.
Not sure if this warrants a test.
=> Hide internal stack when using pytest.approx() in bool context

src/_pytest/python_api.py
This makes the error traceback point directly to the offending usage, rather
than to the internal `Approx.__bool__` method.
(cherry picked from commit 3ba9c01f9bfd442f2bcc4711e15612aa5b518cc3)
=> [7.0.x] Hide internal stack when using pytest.approx() in bool context (#9394)

src/_pytest/hookspec.py, src/_pytest/python.py, src/_pytest/unittest.py
The `pytest_pycollector_makeitem` argument `collector` is currently annotated with type `PyCollector`. As part of #7469, that would have required us to expose it in the public API. But really it's an implementation detail, not something we want to expose. So replace the annotation with the concrete python collector types that are passed.
Strictly speaking, `pytest_pycollect_makeitem` is called from `PyCollector.collect()`, so the new type annotation is incorrect if another type subclasses `PyCollector`. But the set of python collectors is closed (mapping to language constructs), and the type is private, so there shouldn't be any other deriving classes, and we can consider it effectively sealed (unfortunately Python does not provide a way to express this - yet?).
=> Make PyCollector an implementation detail - don't use in hook type annotation

.github/workflows/backport.yml, CONTRIBUTING.rst
To backport a PR, e.g. 1000, to another branch, e.g. `7.0.x`, add a
label `backport 7.0.x` to the PR. This will trigger a workflow which
will create a branch `backport-1000-to-7.0.x` based on the `7.0.x`
branch with a cherry-pick of the PR's merge commit, and create a new PR
for it against the `7.0.x` branch.
It is very simplistic, for instance it doesn't handle cherry-pick
failure gracefully, doesn't validate the state of the PR, doesn't check
if the branch already exists, etc. But we can improve on it later as
needed.
Finally, PRs created by github actions do not themselves trigger further
actions, i.e. the PR isn't checked. You need to close & reopen the PR
for the checks to trigger. There are workarounds for this but they are
either less secure or require more setup.
=> ci: add a workflow for backporting to other branches

doc/en/changelog.rst, doc/en/conf.py, doc/en/deprecations.rst, doc/en/reference/reference.rst, src/_pytest/hookspec.py, src/_pytest/main.py, src/_pytest/python.py
Allow writing
:hook:`pytest_cmdline_main`
instead of
:func:`pytest_cmdline_main <_pytest.hookspec.pytest_cmdline_main>`
=> doc: add a `hook` crossref type

doc/en/changelog.rst, doc/en/conf.py, doc/en/deprecations.rst, doc/en/reference/reference.rst, src/_pytest/hookspec.py, src/_pytest/main.py, src/_pytest/python.py
Backport #9401
(cherry picked from commit 8040cfd9651bb8697b5efd774b315a17e4756d43)
=> [7.0.x] Backport "doc: add a `hook` crossref type" 

.github/workflows/main.yml, testing/test_skipping.py
Decided to remove the condition altogether as seems reasonable to state
that our own test suite requires Python 3.10.1.
Fix #9413
=> Fix test_errors_in_xfail_skip_expressions for Python 3.10.1

.github/workflows/main.yml, testing/test_skipping.py
Backport of https://github.com/pytest-dev/pytest/pull/9417
=> [7.0.x] Fix test_errors_in_xfail_skip_expressions for Python 3.10.1

doc/en/how-to/writing_hook_functions.rst
=> doc: fix a reference in "Writing hook functions"

doc/en/how-to/writing_hook_functions.rst
doc: fix a reference in "Writing hook functions"
(cherry picked from commit 443aa0219c0b5170a2f858c1ccea013cf88c6a6c)
=> [7.0.x] Backport "doc: fix a reference in "Writing hook functions""

src/_pytest/python.py, testing/test_nose.py
Since commit 89f0b5b5a2f485f77999d15cb9437ad9234003a1 cases as in the
added test started to fail, like they do for the standard pytest names
(`setup_module` etc). But the name `setup` in particular is way too
common for us to start taking it over more aggressively, so restore the
previous behavior which required the object to be callable.
Fix #9391.
=> python: skip nose setup/teardown fixtures if non-callable

doc/en/reference/reference.rst
=> doc/reference: add 4 missing hooks to reference

src/_pytest/python.py, testing/test_nose.py
(cherry picked from commit 7fc2cf51c22c0ec6b1599662d9069f620374873a)
=> [7.0.x] Backport "python: skip nose setup/teardown fixtures if non-callable"

doc/en/reference/reference.rst
(cherry picked from commit 7a42db2bf03e021d8c3a409c279cd9ef27e3c122)
=> [7.0.x] Backport "doc/reference: add 4 missing hooks to reference"

src/_pytest/_code/code.py
This is extracted from/alternative to #9440 which keeps the breaking change for the `path` properties but fixes this particular compat issue.
Before 7.0.0rc1, the function accepted `Union[str, py.path.local]`, and
`py.path.local` compares equal to the string path, so a user was able to
pass the path as a string and it would work. In 7.0.0rc1 we changed the
`py.path.local` to `Path` which doesn't compare equal to the string
path, which breaks compatibility (e.g. the `sybil` package).
This restores compatibility for this function by accepting any
`os.PathLike[str]` and only comparing the string representations.
=> code: accept any `os.PathLike[str]` in `Traceback.cut`

src/_pytest/legacypath.py, src/pytest/__init__.py
The monkeypatch approach doesn't work for `import pytest;
pytest.TempdirFactory`.
Fix #9432.
=> pytest: bring back direct imports of TempdirFactory, Testdir

doc/en/changelog.rst
=> doc: document {Code,TracebackEntry}.path changes as breaking

doc/en/changelog.rst
(cherry picked from commit 1131f23e047fb0620a093fdf84d156c13ed14cbc)
=> [7.0.x] Backport "doc: document {Code,TracebackEntry}.path changes as breaking"

.github/workflows/main.yml, tox.ini
Latest Django release dropped support for 3.7.
=> ci: run plugins job with python 3.9 instead of 3.7

.github/workflows/main.yml, .pre-commit-config.yaml, README.rst, changelog/9437.breaking.rst, doc/en/getting-started.rst, doc/en/how-to/skipping.rst, doc/en/index.rst, pyproject.toml, setup.cfg, src/_pytest/assertion/rewrite.py, src/_pytest/compat.py, src/_pytest/logging.py, src/_pytest/pytester.py, testing/test_debugging.py, testing/test_parseopt.py, tox.ini
Part of https://github.com/pytest-dev/pytest/issues/9437
=> Drop Python3.6 in CI, setup.cfg, and readme.

pyproject.toml, src/_pytest/assertion/rewrite.py, src/_pytest/capture.py, src/_pytest/python.py, testing/deprecated_test.py, testing/test_assertrewrite.py, testing/test_capture.py, testing/test_compat.py, testing/test_error_diffs.py, testing/test_pathlib.py
Follow on from https://github.com/pytest-dev/pytest/pull/9442 / https://github.com/pytest-dev/pytest/issues/9437, remove some more redundant code for EOL Python 3.6.
=> Remove redundant Python 3.6 code

.github/workflows/backport.yml
In #9416, @bluetech says:
> So the backport workflow doesn't work - permission error: https://github.com/pytest-dev/pytest/runs/4546997247?check_suite_focus=true. It did work for me in a private test repo, so I'll try to figure out why it fails here. Will create a manual backport for now.
And indeed the [debug output](https://github.com/pytest-dev/pytest/runs/4546997247?check_suite_focus=true#step:1:13) reveals:
```
GITHUB_TOKEN Permissions
Contents: read
Metadata: read
PullRequests: read
Secret source: None
```
which I think is due to [this](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request):
> When you create a pull request from a forked repository to the base repository, GitHub sends the `pull_request` event to the base repository and no …
=> ci: Try backporting via pull_request_target

changelog/9396.bugfix.rst, src/_pytest/legacypath.py, testing/test_config.py, testing/test_legacypath.py
=> Ensure Config.inifile is available during pytest_cmdline_main

doc/en/how-to/capture-warnings.rst
As a new user ([I'm not the only one](https://stackoverflow.com/questions/58645563/how-does-pytest-mark-filterwarnings-work)) I was a bit lost on what syntax I should be using, and that Python itself heavily documents this.
I've updated the documentation to bring this towards the top under its own heading, and linked to the specific user facing Python documentation.
=> Doc update: clarify -W syntax

src/_pytest/config/__init__.py
This made the cache not work as intended, causing a major slowdown.
See #9478 for discussion and context.
Authored-by: @asottile
=> config: fix incorrect cache hit check in _getconftestmodules

src/_pytest/python.py, testing/test_collection.py
Regressed in 062d91ab4 (pytest 7.0.0rc1 only).
Fix #9486.
=> python: add back `instance` accessor to all python nodes, not just Function

changelog/9493.bugfix.rst, src/_pytest/config/__init__.py, src/_pytest/main.py, testing/test_conftest.py, testing/test_monkeypatch.py
As a follow up to #9478, I started looking at the conftest code. I have some ideas (`_dirpath2confmods` is actually quite tricky. also ideally all conftest loading will be done purely during collection), but ran out of time so these are the changes thus far.
There is one logic change related to symlinks, see the changelog entry. I consider it a bugfix, and think it will allow further improvements since it aligns how conftests are loaded with how collection works.
Better viewed per-commit.
=> Some conftest changes

changelog/9505.trivial.rst, doc/en/reference/customize.rst
To avoid confusions the part of that "the configuration file can
be locate on your tests folder" is removed.
closes #9505
=> Improve on configuration file docs section

changelog/9505.trivial.rst, doc/en/reference/customize.rst
=> [7.0.x] Improve on configuration file docs section

changelog/9404.doc.rst, doc/en/deprecations.rst, doc/en/how-to/capture-warnings.rst, src/_pytest/deprecated.py, testing/deprecated_test.py
Closes https://github.com/pytest-dev/pytest/issues/9404.
I added more context on the deprecation doc, but I have been wondering whether it would be useful to have these example on [the main doc of `pytest.warns()`](https://docs.pytest.org/en/latest/reference/reference.html?highlight=warns#pytest-warns), as people might not reach the first one.
Thoughts?
=> Add docs on pytest.warns(None) deprecation

testing/test_config.py
I'm planning some pluggy changes that would break this - but it's good to avoid regardless.
=> testing: avoid private pluggy attributes in test

changelog/9521.improvement.rst, testing/test_assertrewrite.py
Additional test verifies that rewrite->compile->write->read results in a valid pyc file.
closes #9521
=> Add Test To Verify Rewritten *.pyc Files Are Readable

src/_pytest/fixtures.py, src/_pytest/python.py
The docstring (and function name itself) described things as if IDs are being assigned to the argnames, but actually they're assigned to the parameter sets.
---
Also another minor commit: "fixtures: use node.ihook instead of open-coding it"
=> python: fix confused docstring of `Metafunc._resolve_arg_ids`

src/_pytest/config/__init__.py
Fix #9478.
I'll also say Closes #9125 since it shouldn't be that slow anymore (also with next version of pluggy). I ran a profile on pandas collection with this PR and `gethookproxy` (which #9125 caches) comes out at ~1.5s out of ~30s.
I've looked at various ways to speed this up, but they were either too ugly/intrusive or not as effective. In the end, the conftest data structure `_dirpath2confmods`  is pretty efficient for what it does, and the API with the `is_file`/`parent` is mostly unavoidable given that. So a cache it is.
Note that this cache is safe (assuming a path does not change from file <-> dir during the run, which is already assumed), unlike the previous caches which worked on the entire `_getconftestmodules` function.
=> config: avoid stat storm in _getconftestmodules

src/_pytest/config/__init__.py
config: avoid stat storm in _getconftestmodules
(cherry picked from commit 5c69eced6cb3b844ab5a25e4e45d1c23bb1ebab2)
Conflicts:
src/_pytest/config/__init__.py
=> [7.0.x] config: avoid stat storm in _getconftestmodules

changelog/9521.improvement.rst, testing/test_assertrewrite.py
(Created manually instead of using the backport workflow due to conflicts)
=> [7.0.x] Merge pull request #9522 from holmanb/rewrite-test

src/_pytest/python.py, testing/python/metafunc.py
ran: This is a commit cherry-picked from #9420 by @haxtibal with some tweaks by me. It is meant to accommodate the other changes in #9420 but I think it's nice regardless so picking it out already to reduce the size of #9420.
---
This commit only refactors, it does not change or add functionality yet. Public
API is retained. Reason or refactoring:
User provided parameter IDs (e.g. Metafunc.parametrize(ids=...)) had so far
only been used to calculate a unique test ID for each test invocation. That
test ID was a joined string where each parameter contributed some partial ID.
We're soon going to reuse functionality to generate parameter keys for
reorder_items and FixtureDef cache. We will be interested in the partial
IDs, and only if they originate from explicit user information. Refactoring …
=> Refactor idmaker functions into class IdMaker

doc/en/deprecations.rst, doc/en/example/nonpython/conftest.py, src/_pytest/nodes.py
Fixes #9488
Probably still needs test adjustments, but I'd like some feedback from @RonnyPfannschmidt if this is the way to go.
=> Add additional docs for uncooperative ctor deprecation

src/_pytest/pytester.py, src/_pytest/pytester_assertions.py, testing/test_pytester.py
Fix #9471
I don't think we need a CHANGELOG here, as this has not really been officially released yet.
=> Make 'warnings' and 'deselected' in assert_outcomes optional

doc/en/how-to/capture-warnings.rst
I feel like this makes it clearer where the code which was inside 'pytest.warns' is supposed to go.
Follow-up for #9495 - great work there, @olgarithms, this is just something minor that only came to mind when I re-read it now.
=> doc: Add ellipsis to warning usecase list

changelog/9488.deprecation.rst
This was supposed to be part of #9488, but I only now noticed it was lying around uncommitted in my git dir
=> Add missing cooperative constructor changelog

.github/workflows/main.yml
macOS apparently can be slow, https://github.com/pytest-dev/pytest/runs/4965510831 for #9556 got cancelled at 91%
(cherry picked from commit 7bffcd0ac46befcf17708452fa3bed8b68116235)
Manual backport of #9560
=> [7.0.x] ci: Bump up timeout

testing/test_config.py
I had to update the `hookimpls` list to match the original as of 6.2.x.
=> Backport #9512 to 6.2.x

.github/workflows/main.yml, testing/test_skipping.py
Please backport the py3.10 fix to 6.2.x. It applies cleanly and fixes the test failures. It will take some time before everyone's ready for 7.0.0, so fixing 6.2.x seems to be the right thing to do.
=> Backport #9417 to 6.2.x

testing/test_unittest.py
Please backport #8664 to 6.2.x branch. Note that I had to modify the code to keep using `testdir.runpytest()`.
=> Backport 8664 to 6.2.x

scripts/prepare-release-pr.py
Looks like something (tox?) does not deal with empty arguments being passed to release.py correctly...
See https://github.com/pytest-dev/pytest/runs/5049339603?check_suite_focus=true#step:6:61
=> releasing: Always set doc_version

scripts/prepare-release-pr.py, scripts/release.major.rst, scripts/release.minor.rst
With pytest 6.0.0, we still used a manual releasing workflow (at least if I
remember correctly), and apparently we never wrote a release announcement
template for major releases. Instead, the minor release template claimed that
the release would contain "breaking changes", which doesn't seem reasonable.
Thus, this adds a new major template based on the former minor template, and
adjusts the latter to only mention fixes and new features instead.
=> releasing: Add template for major releases

.github/workflows/main.yml
alinsa_vix in Discord noticed that we are not testing Python 3.9 and 3.10 on macOS, which seems strange. Maybe this is due how to macOS CI resources were quite scarce for a while, but I believe this has improved since.
=> ci: Add missing macOS CI envs

RELEASING.rst
The docs already assume an 'upstream' remote, so we can only fetch from there instead of fetching all remotes. We also don't need to hardcode the remote URL.
=> doc: Streamline remote handling in releasing docs

doc/en/how-to/tmp_path.rst
Help people who might want to reduce the number of temporary directories kept. See #9599
=> Mention basetemp in docs as a way to only keep last temp dir

src/_pytest/mark/structures.py
Should hopefully work now in Python>=3.7.
=> mark/structures: use class-based NamedTuple syntax

testing/test_assertrewrite.py, testing/test_doctest.py
originally reproduced with this pollution set:
```
testing/test_assertrewrite.py::TestEarlyRewriteBailout::test_pattern_contains_subdirectories
testing/test_assertrewrite.py::TestRewriteOnImport::test_remember_rewritten_modules
```
=> fix test pollution in test_assertrewrite

changelog/9642.bugfix.rst, src/_pytest/main.py, testing/test_main.py
for example in pytest's suite:
before this was failing with:
```console
$ pytest testing/test_mark_expression.py::test_valid_idents[:::]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.0.dev178+g6f936aa97, pluggy-1.0.0
rootdir: /tmp/y/pytest, configfile: pyproject.toml
plugins: hypothesis-6.36.1
collected 0 items                                                              
============================ no tests ran in 0.03s =============================
ERROR: not found: /tmp/y/pytest/testing/test_mark_expression.py::test_valid_idents[:::]
(no name '/tmp/y/pytest/testing/test_mark_expression.py::test_valid_idents[:::]' in any of [<Module testing/test_mark_expression.py>])
```
=> allow running testids which contain :: in the parametrized portion

doc/en/conf.py, doc/en/deprecations.rst, doc/en/how-to/plugins.rst
Initially I just wanted to fix http -> https, but I think it's not worth
having at all just for this one reference.
=> doc: remove django intersphinx mapping

changelog/9608.bugfix.rst, src/_pytest/assertion/rewrite.py
This exists https://github.com/python/cpython/blob/3.10/Lib/importlib/readers.py and FileReader is in there
This is a 404 https://github.com/python/cpython/blob/3.9/Lib/importlib/readers.py
This change needs to get backported to the 7.0.z branch(s) too
closes https://github.com/pytest-dev/pytest/issues/9608
I'm going to go ahead and open this PR, if you think we need a changelog for this LMK
=> importlib.readers not valid until python 3.10

doc/en/how-to/capture-warnings.rst
Follow up of #9495 . Turns out `pytest.warns()` is not a drop-in replacement for the way we use `pytest.warns(None)` (astropy/astropy#12823). "Any" in the doc got me to believe that it will pass even with zero warning but the test fails when there is no warning with this, so this is an attempt to improve a doc a bit more.
p.s. This does not need a change log and I don't think a one word change qualify my name on authors list.
=> DOC: pytest.warns() fails on zero warning

changelog/9610.bugfix.rst, src/_pytest/unittest.py, testing/test_unittest.py
This fixes #9610. Test case by @jiridanek.
pytest 7.0.0 (unintentionally) changed `UnitTestFunction.obj`'s behavior
to match `Function.obj`. That is probably a good thing to have, however
it evidently causes some regressions as described in the issue, so
restore the previous behavior for now. In the future we might want to
make this change again, but with proper consideration.
=> unittest: restore `UnitTestFunction.obj` to return unbound rather than bound method

RELEASING.rst
=> doc: Discourage squashing for release

changelog/9645.bugfix.rst, src/_pytest/pathlib.py, testing/test_collection.py, testing/test_pathlib.py
The dummy modules we introduce in `insert_missing_modules` (due to #7856 and #7859) 
would cause problems if the dummy modules end up replacing modules 
which could be imported normally because they are available in `PYTHONPATH`.
Now we attempt to first import the module via normal mechanisms, and only
introduce the dummy modules if the intermediary modules don't actually exist.
Close #9645
---
Original PR text, when opened as a draft, for reference:
I spent some time investigating this and narrowed it down to this function:
https://github.com/pytest-dev/pytest/blob/c01a5c177b7bcabc0fbfc1d80b4c841088f8d14b/src/_pytest/pathlib.py#L595-L612
which is called during `import_path` when `importmode=importlib`.
The function was introduced because of #7856 and #7859, and it did feel like a hack at …
=> Try to import module before creating dummy modules with 'importmode=importlib'

changelog/9626.bugfix.rst, src/_pytest/terminal.py, testing/test_cacheprovider.py, testing/test_terminal.py
If there were errors or skipped modules on collection,
pytest would mistakenly subtract those from the selected count.
Close #9626
=> Fix count of selected tests on terminal collection summary

changelog/9678.improvement.rst, src/_pytest/fixtures.py, src/_pytest/python.py, testing/python/metafunc.py
In the following
```py
@pytest.mark.parametrize(..., ids=[val])
```
the ID values are only allowed to be `str`, `float`, `int` or `bool`.
In the following
```py
@pytest.mark.parametrize(..., [val])
```
```py
@pytest.mark.parametrize(..., [pytest.param(..., id=val])
```
a different code path is used, which also allows `bytes`, `complex`, `re.Pattern`, `Enum` and anything with a `__name__`.
In the interest of consistency, use the latter code path for all cases.
=> python: unify code to generate ID from value

changelog/5192.improvement.rst, src/_pytest/assertion/util.py, testing/acceptance_test.py, testing/test_assertion.py, testing/test_error_diffs.py
`_compare_eq_verbose` doesn't seem to useful in the end, with the examples we
have in the test suite.
Close #5192
cc @mdmintz
=> Fix diff output for data types where `-v` would show less information

src/_pytest/fixtures.py
Also a refactor commit to make some code flow clearer.
This conflicts with #9420 so not meant for merging right away.
=>  fixtures: document FixtureDef's attributes

changelog/9644.improvement.rst, doc/en/how-to/capture-warnings.rst, src/_pytest/warnings.py, testing/test_warnings.py
=> Expand warnings output for ResourceWarning

doc/en/how-to/bash-completion.rst
fix link of argcomplete page.
https://argcomplete.readthedocs.io/ says that 
Documentation for this project has moved to https://kislyuk.github.io/argcomplete
=> fix link of argcomplete page.

changelog/9326.bugfix.rst, changelog/9362.improvement.rst
While answering to https://github.com/pytest-dev/pytest/pull/9407#issuecomment-1049028494, I noticed the change log entry had a typo in its number. While at it I improved the text a bit.
=> Fix numbering and improve changelog entry for #9362

changelog/9692.improvement.rst, src/_pytest/python_api.py, testing/python/approx.py
=> Disallow unordered sequences in pytest.approx

changelog/9708.bugfix.rst, src/_pytest/pytester.py, testing/test_pytester.py
It is tempting to use `monkeypatch` to replace the other mechanisms in pytester which change global 
state: `CwdSnapshot`, `SysModulesSnapshot`, `SysPathsSnapshot`, however those are more delicate 
than they look at first glance so leaving those alone for now.
Close #9708
=> pytester now requests monkeypatch instead of creating its own instance

changelog/9730.bugfix.rst, src/_pytest/config/findpaths.py, testing/test_config.py
Including the file name is enough to let the user know what the problem is.
The same is not needed for `.ini` files because their error message includes the path to the file by default.
Fix #9730
=> Improve error message for malformed pyproject.toml files

doc/en/deprecations.rst
=> Fix typo in deprecation documentation

doc/en/index.rst, doc/en/talks.rst
Also see https://twitter.com/the_compiler/status/1501247315809640464
Submitted but not accepted yet trainings commented out for now.
=> Update upcoming trainings

src/_pytest/recwarn.py
A word was missing in the docstring of the warns function.
As the change is trivial, I didn't run any test or add anything to the changelog.
=> Typo correction

src/_pytest/pytester.py
=> Fixed typo in pytester docs.

changelog/9767.bugfix.rst, src/_pytest/config/__init__.py, testing/test_conftest.py
The change from `path not in confuctdir.parents` to the `relative_to` check in 0c98f1923101e5905c54ba07650a043fca374f4b broke picking up conftest files when running against an installed package/site-packages. See the issue for more details.
Fix #9767.
=> config: restore pre-pytest 7.1.0 confcutdir exclusion behavior

extra/setup-py.test/setup.py, testing/test_assertrewrite.py
Regressed in fac8f284cd6ffd44c7d401093c67799766473be1, didn't notice
since we don't run tests in CI with `-v`.
=> testing: fix tests when run under `-v` or `-vv`

AUTHORS, changelog/9742.improvement.rst, src/_pytest/_io/saferepr.py, src/_pytest/assertion/util.py, testing/io/test_saferepr.py, testing/test_assertion.py
fix #9742
I've done this in the least intrusive way possible, a cleaner solution would be to alter `saferepr` to behave like the new `saferepr_unlimited` method when `maxsize=None`, but that might effect some other code (though I think use of `saferepr()` with `maxsize=None` is very rare).
=> Remove newlines from left/right operands with '-vv'

.github/workflows/deploy.yml, .github/workflows/test.yml, README.rst
This will trigger a deploy directly when a tag is pushed, avoiding
having to wait for another lenghty build.
This is safe since we only push release tags after the release PR has passed all its tests.
See comments in #9793.
Close #9793
=> Split test/deploy workflows

changelog/8508.improvement.rst, src/_pytest/_code/code.py, src/_pytest/recwarn.py, testing/code/test_excinfo.py, testing/python/raises.py, testing/test_recwarn.py
=> Enhance errors for exception/warnings matching

testing/test_collection.py
Getting the current working directory has no side-effects, so these context managers were no-ops.
Discovered because `Path.__enter__` is deprecated in Python 3.11, for removal in 3.13.
See e.g. https://github.com/pytest-dev/pytest/runs/5621307685?check_suite_focus=true for previous failures.
=> Fix CI for Python 3.11

testing/test_collection.py
As discussed in https://github.com/pytest-dev/pytest/pull/9800, this uses monkeypatch to change directories for two tests in `test_collection.py`, to preserve their original purpose (even if just removing it doesn't seem to affect the outcome).
=> Change directories during some tests in test_collection.py

changelog/9820.bugfix.rst, src/_pytest/assertion/util.py, testing/example_scripts/dataclasses/test_compare_initvar.py, testing/test_assertion.py
=> fix comparison of dataclasses with `InitVar`

AUTHORS, changelog/9871.bugfix.rst, src/_pytest/tmpdir.py
This fixes an [issue that I have](https://github.com/ZELLMECHANIK-DRESDEN/dclab/runs/6099944514?check_suite_focus=true) in combination with coverage and the `tmp_path` fixture:
I am not sure what exactly causes this. Maybe coverage hides some environment variables. I also find it strange that It is not possible to import a module from the standard library. But in any case, I think this fix is light-weight and should not cause any trouble in the future.
The error message goes like this:
```
==================================== ERRORS ====================================
_______________ ERROR at setup of test_store_and_get_certificate _______________
cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x7f8bd786f7f0>
when = 'setup'
reraise = …
```
=> fix: move 'import getpass' statement to try-clause

AUTHORS, changelog/9823.improvement.rst, src/_pytest/main.py, testing/acceptance_test.py, testing/test_config.py
In case no collector is found for a given file (e.g. if you run `pytest something.unrecognized`), then the somewhat cryptic error message
```
ERROR: not found: something.unrecognized
(no name 'something.unrecognized' in any of [])
``` 
With this PR, a more meaningful error message is displayed.
Not sure if such an almost-trivial change warrants an a changelog and authors entry.
=> Clarify error message in case no collectors are found for a file

doc/en/how-to/logging.rst, doc/en/reference/reference.rst
If a relative path is passed for the `--log-file` CLI argument, *or* the `log_file` config option is set, it is always resolved relative to the current working directory - pytest doesn't have any special logic beyond that in the standard library `logging.FileHandler`.
Unfortunately this was incorrectly documented as being relative to the `pytest.ini` file (*not* rootdir), which kicked off a considerable chain of confusion.  This PR therefore fixes #7336, closes #7350, and closes #9700.
Any proposal to change the current internally-consistent behaviour should start from a fresh issue, and include a description of why the alternative semantics are more desirable, and how to manage the backwards-compatibility implications of moving so many users' log files.
=> Fix wrong `log_file` docs

changelog/9906.trivial.rst, src/_pytest/compat.py
I'm fixing a bug in mypy's `--no-implicit-reexport` logic in
https://github.com/python/mypy/pull/12704 and mypy-primer flagged this
=> Re-export importlib.metadata from _pytest.compat

doc/en/how-to/doctest.rst
This PR addresses one issue in #9892: the original wording suggests that it compares to the level of precision.  The new text explicitly lays out how the numbers are compared using `pytest.approx`.
=> Clarify precision when using NUMBER option in --doctest-modules

changelog/9910.trivial.rst, src/_pytest/cacheprovider.py
Add `encoding="UTF-8"` and `ensure_ascii=False` in `_pytest/cacheprovider.py` to fix `EncodingWarning`.
Closes #9910
=> Fix default encoding in cacheprovider

testing/test_conftest.py
=> testing: fix Path.rglob("") failures in Python 3.11b1

doc/en/reference/reference.rst
Up to now, some had the prefix, some didn't. I think it's good to have
this prefix to give more context, otherwise the links sometimes blend
into the description.
In one case, the link goes to an example, so I used `**Example**:` there.
Also, there was a mixture of having a period at the end or not. I normalized to not have a period because the displayed how to names are usually not full sentences.
=> Consistently add **Tutorial**: in front of how-to links in reference

doc/en/reference/reference.rst, src/_pytest/capture.py, src/_pytest/doctest.py, src/_pytest/recwarn.py
It's better to have the documentation in one place, instead
of having some in the docstring and some additional
information added to the reference documentation in
`reference.rst`.
=> Move documentation contents from reference.rst to docstrings

src/_pytest/terminal.py, testing/test_skipping.py, testing/test_terminal.py
Note that here I also moved the **XFAIL reason** to the same line, similar to the summary we have for failures. I think this is more pleasing, and was implemented when we didn't have the failure summary on each line, and not updated as an oversight.
Fix #9873
---
I personally like [2], but posting [1] in case people prefer it.
---
The fact that SKIPS are formatted differently and also folded together bothers me a bit, opened https://github.com/pytest-dev/pytest/issues/9876 for discussion.
=> Add colors to summary

changelog/9920.improvement.rst, src/_pytest/terminal.py, testing/test_terminal.py
Fixes #9920
This skips crash message truncation, if a `CI` environment variable is set and truthy.
Should this be mentioned in the docs, maybe as a note? https://github.com/pytest-dev/pytest/blob/main/doc/en/how-to/output.rst#producing-a-detailed-summary-report
*Thanks to blueyed for some hints in #5284.*
=> Do Not Truncate Crash Messages In Short Test Summary on CI

doc/en/_templates/globaltoc.html
Follow up to #9957 - I missed that the globaltoc is hard-coded
and the page needs to be removed there as well.
=> Remove "Python 2.7 and 3.4 Support" from globaltoc

doc/en/reference/index.rst
This changes the order to:
- API Reference
- Fixtures reference
- Configuration
- Exit codes
- Plugin List
which is approximately sorted from general to specific and often used to less used.
Plugin List ist at the end because it points to further external resources.
=> Reorder the reference guides in the docs

AUTHORS, changelog/9897.feature.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, src/_pytest/terminal.py, testing/test_collection.py
The implementation uses the standard `glob` module to perform wildcard
expansion in Config.parse().
This is especially useful for large repositories (e.g. monorepos) that
use a hierarchical file system organization for nested test paths.
src/*/tests
The related logic that determines whether or not to include 'testpaths'
in the terminal header was previously relying on a weak heuristic: if
Config.args matched 'testpaths', then its value was printed. That
generally worked, but it could also print when the user explicitly used
the same arguments on the command-line as listed in 'testpaths'. Not a
big deal, but it shows that the check was logically incorrect.
Now that 'testpaths' can contain wildcards, it's no longer possible to
perform this simple comparison, so this change also introduces a …
=> Add shell-style wildcard support to 'testpaths'

doc/en/_templates/globaltoc.html, doc/en/conf.py, doc/en/index.rst
- Remove the index page https://docs.pytest.org/en/7.1.x/genindex.html
Such an index is reasonable in books but not so much in HTML pages.
IMHO the integrated search is much more user-friendly and sufficient.
- Remove the PDF link from the entry page. The PDF is already linked
  in the sidebar. I anticipate that getting the PDF documentation is
  not a major concern for users.
This is removed:  ![grafik](https://user-images.githubusercontent.com/2836374/168692889-905a71c8-9315-4248-9d95-54a2e536f371.png)
because we still have
- Remove the sections "Changelog" and "License" from the entry page.
These section only contain links to the respective pages.
The topics are purely technical. They should be easily accessible
(which they still are through sidebar section "About the project"),
but …
=> Declutter doc entry page

AUTHORS, changelog/7337.improvement.rst, doc/en/deprecations.rst, doc/en/reference/reference.rst, src/_pytest/python.py, src/_pytest/warning_types.py, src/pytest/__init__.py, testing/acceptance_test.py
Adding a warning in `pytest_pyfunc_call` after the `async_warn_and_skip` will check if the return is something other than `None`.
Closes #7337; see that issue for details.
CC @Zac-HD
=> Give warning when test function return other than None

changelog/9984.trivial.rst, src/_pytest/fixtures.py
- Improve the error message when we attempt to access a fixture that has been
torn down.
- Add an additional sentence to the docstring explaining when it's not a good
idea to call getfixturevalue.
closes #9984
=> Improve error message in getfixturevalue

src/_pytest/pytester.py
These pytester utility methods were annotated to only receive `str`
names, but they naturally support os.PathLike values, as well.
This makes writing some pytester calls a little nicer, such as when
creating a directory based on a `.joinpath()` call. We previously needed
to cast that intermediate value to a `str`.
=> Let mkdir() and mkpydir() receive PathLike names

src/_pytest/fixtures.py
This is equivalent to the long-form logic that was being used here: call
`getattr` and catch`TEST_OUTCOME`.
This could alternatively use `inspect.getattr_static` because `_pytestfixturefunction`
is an "internal" attribute that's only assigned by `FixtureFunctionMarker`, and it's
unlikely we'd need to support descriptors and dynamic attribute lookups.
=> Use safe_getattr() in getfixturemarker()

doc/en/explanation/goodpractices.rst, doc/en/explanation/pythonpath.rst
It is clear at this point that changing the default would break a lot of suites, and is not a clear win in all cases anyway.
Close #10003
=> Do not advertise that importlib will be default import mode

changelog/9883.improvement.rst, doc/en/reference/reference.rst, src/_pytest/assertion/__init__.py, src/_pytest/cacheprovider.py, src/_pytest/capture.py, src/_pytest/config/__init__.py, src/_pytest/config/argparsing.py, src/_pytest/debugging.py, src/_pytest/doctest.py, src/_pytest/faulthandler.py, src/_pytest/fixtures.py, src/_pytest/helpconfig.py, src/_pytest/junitxml.py, src/_pytest/logging.py, src/_pytest/main.py, src/_pytest/mark/__init__.py, src/_pytest/pastebin.py, src/_pytest/pytester.py, src/_pytest/python.py, src/_pytest/runner.py, src/_pytest/setuponly.py, src/_pytest/setupplan.py, src/_pytest/skipping.py, src/_pytest/stepwise.py, src/_pytest/terminal.py, testing/test_config.py, testing/test_helpconfig.py, testing/test_stepwise.py
Recently had to look this up in the source code.
So include in help text it shows during `pytest --help` and on https://docs.pytest.org/en/7.1.x/reference/reference.html#command-line-flags
---
Whilst looking at the the help texts at https://docs.pytest.org/en/7.1.x/reference/reference.html#command-line-flags, there's quite a bit of variation in case and whether to use a full stop after a single or multiple sentence:
* Sentence case
* Sentence case.
* Sentence case. Sentence case.
* Sentence case. Sentence case
* lower case
* lower case.
* lower case. Sentence case
* lower case. Sentence case.
I can update them if you have a preference? 
I suggest: use sentence case, no full stop for single sentence. If there's more than one sentence, end each with a full stop.
=> Document the --code-highlight default

AUTHORS, doc/en/how-to/monkeypatch.rst
Since #8006 MonkeyPatch is publicly available on [`pytest.MonkeyPatch`](https://docs.pytest.org/en/7.1.x/reference/reference.html?#pytest.MonkeyPatch).
<details>
<summary>Before</summary>
</details>
<details>
<summary>With PR</summary>
</details>
Small doc fix
=> docs(monkeypatch): Fix autodoc reference links

AUTHORS, doc/en/monkeypatch.rst, extra/setup-py.test/setup.py
Backport of PR https://github.com/pytest-dev/pytest/pull/10013 to 6.2.x branch.
PR created by @tony per @nicoddemus conversation in https://github.com/pytest-dev/pytest/pull/10015#issuecomment-1144873243
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> [6.2.x] docs(monkeypatch): Fix autodoc reference links

src/_pytest/compat.py, src/_pytest/config/argparsing.py, src/_pytest/fixtures.py, src/_pytest/mark/expression.py, src/_pytest/outcomes.py, src/_pytest/reports.py
This is a very minor PR that repairs a false positive with PyLint: https://github.com/PyCQA/pylint/issues/6815
=> Use symbolic NoReturn as a type annotation

doc/en/conf.py
`usage.rst` has been moved from `doc/en` to `doc/en/how-to`, so the `man_pages` configuration
value needs to be updated to the new location, so that we dont get this warning:
writing... WARNING: "man_pages" config value references unknown document usage
=> Update location of `usage.rst` to fix manpage compilation

testing/test_debugging.py
=> Mark pdb+expect tests as xfail for now

doc/en/how-to/fixtures.rst
As the description before this test example says:
> we'll likely have to make sure the other user's mailbox is emptied before deleting that user, otherwise the system may
complain.
So the method `clear_mailbox` of `user` should be invoked to fulfill it, or else the inbox still has an email after the user is deleted.
Besides, the following 2 counterpart test examples using `addfinalizer` and `compact` mode also have the mailbox clear before deleting the user.
=> Doc: Clear mailbox before deleting the user

doc/en/conf.py, testing/test_debugging.py
Replace `logging.warn` (deprecated in [Python 2.7, 2011](https://github.com/python/cpython/commit/04d5bc00a219860c69ea17eaa633d3ab9917409f)) with `logging.warning` (added in [Python 2.3, 2003](https://github.com/python/cpython/commit/6fa635df7aa88ae9fd8b41ae42743341316c90f7)).
* https://docs.python.org/3/library/logging.html#logging.Logger.warning
* https://github.com/python/cpython/issues/57444
=> Replace deprecated logging.warn with logging.warning

AUTHORS, src/_pytest/fixtures.py
Changed:
`  def path(self) -> Path:
if self.scope not in ("function", "class", "module", "package"):
raise AttributeError(f"path not available in {self.scope}-scoped context")
To:
`  def path(self) -> Path:
"""Path where the test function was collected."""
if self.scope not in ("function", "class", "module", "package"):
raise AttributeError(f"path not available in {self.scope}-scoped context")
- [X ] Include documentation when adding new features.
* *Terminal summary statistics …
=> Added Docstring description for the Path property of FixtureRequest #9975

doc/en/reference/reference.rst
This PR adds a note in the reference documentation for `pytest.mark.xfail` that indicates that a tuple of exceptions is allowed. Currently, a user (:wave:) can only discover this functionality in the supplementary remarks about `xfail` in the [`skipping`](https://pytest.org/en/stable/how-to/skipping.html#raises-parameter) documentation.
=> Indicate support for a tuple of exceptions in xfail raises=

changelog/10060.bugfix.rst, src/_pytest/unittest.py, testing/test_unittest.py
=> Do not call tearDown for skipped unittest.TestCases with --pdb

doc/en/example/parametrize.rst, testing/python/raises.py
(cherry picked from commit 2941da0f2bdc58cabfc6977f45bea3c9404493ea)
backport of #10090 (conflict occurred)
=> [7.1.x] update does_not_raise docs now that pytest is 3.7+ only

AUTHORS, changelog/3396.improvement.rst, src/_pytest/doctest.py, testing/test_doctest.py
This allows doctest to be used with namespace modules in tox, as illustrated in the new unit test. See also #3396.
=> Pass importmode to import_path in DoctestModule

AUTHORS, changelog/9877.bugfix.rst, src/_pytest/logging.py, testing/logging/test_fixture.py
Closes #9877
~~Add "when" property to `LogCaptureHandler` in `_pytest/logging.py`  to fix caplog stage records not reset after `caplog.clear()`~~
`caplog_handler.reset()` set LogCaptureHandler.records a new list object, which lost bind to item.stash
As each running stage use one caplog_handler object and it's records object reference in item.stash `item.stash[caplog_records_key][when] = caplog_handler.records`. So after clear, any log records can not be captured to item.stash
=> Fix stage caplog records not clear

.pre-commit-config.yaml, changelog/10114.trivial.rst, setup.cfg, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
resolves #10114
diff is best viewed with [?w=1](https://github.com/pytest-dev/pytest/pull/10115/files?w=1)
=> replace atomicwrites with os.replace

.pre-commit-config.yaml, changelog/10114.trivial.rst, setup.cfg, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
(cherry picked from commit 7dc540f258cf898b7ffe540f5d460490bd825425)
manually resolved the conflicts
=> [7.1.x] replace atomicwrites with os.replace

AUTHORS, changelog/9514.bugfix.rst, src/_pytest/fixtures.py
For now, mark it as Any until #8073 is solved
Closes #9514
- [N/A] Include documentation when adding new features.
(added a type annotation in the file to prove it works)
=> Add typing for FixtureRequest.param

AUTHORS, changelog/9937.doc.rst, doc/en/how-to/tmp_path.rst, src/_pytest/legacypath.py
Explicit note that ``tmpdir`` fixture is discouraged in favour of ``tmp_path``.
Closes #9937 
- [N/A] Include documentation when adding new features.
- [N/A] Include new tests or update existing tests when applicable.
=> Explicit note that tmpdir fixture is discouraged in favour of tmp_path #9937

doc/en/how-to/monkeypatch.rst
This is just a small doc addition.
I consider myself a moderately experienced pytest user, but I had no idea about `monkeypatch.context()` until today. (And I am very happy to start using it where I still had `mock.patch` calls!) I think making it more prominent will help more users like me.
=> Add monkeypatch.context() to how-to doc intro

doc/en/example/markers.rst
=> Fix typo in example/markers documentation

changelog/10150.bugfix.rst, src/_pytest/capture.py, testing/test_capture.py
Fixes #10150 
head-fork: PurityLake/pytest
compare: fix-file-like-object
base-fork: pytest-dev/pytest
base: main
Fixes an issue with `DontReadFromInput` class by added methods that a "file-like" object may contain.
Methods added:
* flush - raises UnsupportedOperation
* readable - returns False
* seek - raises UnsupportedOperation
* seekable - returns False
* tell - raises UnsupportedOperation
* truncate - raises UnsupportedOperation
* write - raises UnsupportedOperation
* writelines - raises UnsupportedOperation
* writable - returns False
=> Added file-like methods to DontReadFromInput

changelog/10012.deprecation.rst, src/_pytest/warning_types.py
currently the PytestUnhandledCoroutineWarning are a regular PytestWarning. However really they are just a more important special case of PytestReturnNotNoneWarning
If the plan is to upbraid PytestReturnNotNoneWarning into a PytestReturnNotNoneError in pytest 8, we should turn both of these into an error at the same time.
See https://github.com/pytest-dev/pytest/pull/9956#issuecomment-1143853734
And https://github.com/pytest-dev/pytest/issues/7363
=>  Update :class:`pytest.PytestUnhandledCoroutineWarning` to a deprecation; it will raise an error in pytest 8. [SQUASH]

doc/en/fixture.rst
The text references a "previous example" that doesn't exist in the document. Readers coming directly to this document via a search engine may not have seen the previous example. It is possible that the example has been removed from the documentation.
This change makes a reference to a test case within the same document, so the reader is able to find the example.
=> Change example to reference from within same page

src/_pytest/monkeypatch.py
It was never mentioned in the docs, and I keep forgetting that it's `.undo()` and not `.stopall()` or something...
=> Mention `monkeypatch.context()` in the docs

doc/en/conf.py, doc/en/reference/customize.rst, doc/en/reference/reference.rst, doc/en/requirements.txt, src/_pytest/assertion/__init__.py, src/_pytest/compat.py, src/_pytest/config/argparsing.py, src/_pytest/fixtures.py, src/_pytest/hookspec.py, src/_pytest/junitxml.py, src/_pytest/logging.py, src/_pytest/main.py, src/_pytest/mark/__init__.py, src/_pytest/monkeypatch.py, src/_pytest/nodes.py, src/_pytest/outcomes.py, src/_pytest/pytester.py, src/_pytest/python_api.py, src/_pytest/recwarn.py, src/_pytest/reports.py, src/_pytest/tmpdir.py
Sphinx 4 (or releases since) provides two nice things (see [changelog](https://www.sphinx-doc.org/en/master/changes.html)):
- It supports "canonical" names for types. I'm not sure exactly what it is, but makes a lot more internal type annotations references resolve in the API Reference. Previously sphinx was confused by the `pytest.*` reexports from `_pytest`.
- ~~`python_use_unqualified_type_names` config which makes the API Reference signatures a little less noisy.~~
=> doc: support sphinx 5

changelog/9248.doc.rst
I forgot to add a changelog entry for #9248. It might be relevant for some distributions, and also if there are any regressions.
=> changelog: add missing entry for PR #9248 (Sphinx 5)

doc/en/how-to/monkeypatch.rst, src/_pytest/monkeypatch.py
This should help users with the common issue of patching the wrong place.
Also took the opportunity of using proper links in the monkeypatch introduction.
Related to #10216
=> Add reference to the Where to patch docs in monkeypatch.setattr

changelog/10218.improvement.rst, src/_pytest/mark/structures.py, src/_pytest/python.py
The main motivation for this change is to simplify the type shown in code editors -- `Sequence[str]` is easier to follow than `Union[list[str], tuple[str, ...]]`.
It also permits using other types if desired. It might lead to problems if someone uses some oddball sequence type, but hopefully they won't do that.
=> mark: allow any Sequence[str] for parametrize(argnames), not just list/tuple

doc/en/how-to/fixtures.rst
Fixes #10023 
Add note to clarify the difference in execution order between after-yield finalizers and `request.addfinalizer` finalizers.
=> Update fixtures.rst w/ finalizer order

changelog/9291.doc.rst, doc/en/how-to/capture-warnings.rst, src/_pytest/recwarn.py
closes #9291
Co-authored-by: Dani Sancas <lord.sancas@gmail.com>
On-behalf-of: @clarityai-eng <tech@clarity.ai>
Signed-off-by: Tatiana Ovary <tatiana.ovary@clarity.ai>
=> Update documentation on how pytest.warns affects DeprecationWarning #9291

.github/workflows/test.yml, .pre-commit-config.yaml, AUTHORS, changelog/9159.bugfix.rst, setup.cfg, src/_pytest/_code/code.py, testing/code/test_excinfo.py, tox.ini
Picking up work on and therefore closes #10071 to temporarily address #9159
Improvements over the previous PR:
* Handles `BaseExceptionGroup`
* Handles exception chains properly, using `excinfo_` instead of `excinfo`, and sets `reprcrash`
* fixed tox.ini
* rewrote tests extending them, previous ones also had regex bugs
I'm not entirely sure how to handle the envlist in tox.ini, since hypothesis currently depends on `exceptiongroup`, making an extra environment for it redundant. I also wanted a test for py311 without `exceptiongroup` installed, but it got messy setting up a separate testenv without `extras=testing`. An alternative is a 3.11-only test that modifies `_pytest._code.code.ExceptionGroups` removing `exceptiongroup.BaseExceptionGroup` from it.
The test is still somewhat WIP, I …
=> fallback to native traceback when handling ExceptionGroup (take 2) [SQUASH]

doc/en/explanation/goodpractices.rst
It is unnecessary and has been deleted from the setuptools' docs too.
The setuptools' PEP 517 build backend implementation has been
auto-adding the `wheel` dependency since it's first been implemented.
Looks like it's been dropped from the main packaging config too, recently: https://github.com/pytest-dev/pytest/commit/56862c03cbb3f9cae3464c33390fbbaf8a91823a.
=> Drop `wheel` from `pyproject.toml` example

changelog/10230.bugfix.rst, src/_pytest/config/__init__.py, testing/test_config.py
Fixes #10230, relatively trivial change.
=> Ignore editable installation modules

doc/en/how-to/fixtures.rst
The finalizers example was wiping out code needed for the examples below.
Noticed this in #10250
Closes #10252
=> Fix regendoc

doc/en/conf.py, doc/en/explanation/goodpractices.rst, doc/en/how-to/fixtures.rst
The importlib import mode has no* drawbacks while the default mode `prepend` has a major footgun. That one has one popular workaround which in turn has further drawbacks.
Also one of the sections correctly says “subfolder”, but others misleadingly say “subpackage”. Should I get rid of that too?
*I consider the fact that you can’t import from test files a feature, as it cleans up the distinction between test files and python packages. It encourages to keep your test utils in one location and reduces dependencies between test files.
=> Revamp good practices

doc/en/conf.py, doc/en/explanation/goodpractices.rst, doc/en/how-to/fixtures.rst
* Recommend importlib import mode for new projects
* Recommend src layout more strongly
* Switch to hatchling as the packaging tool in the example (following PyPA)
* Add explanation about the different import modes
(cherry picked from commit 245a8c23dd0ffeb03710f0fbabd1f5e6a56611ab)
=> [7.1.x] Revamp good practices (#10206)

doc/en/reference/reference.rst
While taking a look at the docs I noticed they were not properly sorted.
This just moves the sections around so they are sorted alphabetically, without any other changes.
=> Sort fixtures in reference.rst alphabetically

CONTRIBUTING.rst, doc/en/changelog.rst, doc/en/example/nonpython.rst, src/_pytest/recwarn.py
I fixed a few broken links in the documentation as well as in a docstring.
=> Fix a few broken links in the documentation.

src/_pytest/config/__init__.py
=> Mark tryfirst/trylast as deprecated in their docs.

src/_pytest/warning_types.py, testing/test_warning_types.py
as the warning systems own warn_explicit looses the information we add them explicitly to the warning exceptions
@The-Compiler this should resolve the issue you noted
closes #10342
=> fix #10342: put location into warning exceptions

doc/en/explanation/goodpractices.rst
Fixes #9833. `PYTHONPATH`/`pythonpath` is required in case of the recommended `src` layout.
=> Mention pythonpath confval in Good Integration Practices

changelog/10313.trivial.rst, src/_pytest/doctest.py, src/pytest/__init__.py
=> Export `pytest.DoctestItem` for typing / runtime purposes

.github/workflows/backport.yml, .github/workflows/prepare-release-pr.yml, .github/workflows/update-plugin-list.yml
The builtin actions token is not allowed to trigger further workflows. So when we create a PR using that token, the PR checks don't run, and a maintainer must close & open the PR to make them run. This is quite annoying, so switch back to the "machine user" approach.
Fixes #9554.
=> ci: fix PR not triggering workflows by switching back to pytestbot access token

src/_pytest/capture.py
Although slightly pointless, this avoids an `EncodingWarning` in Python 3.10 or greater when running under the `-X warn_default_encoding` flag.
----
I think this meets the bar for triviality so I haven't included a changelog entry. PR created per @nicoddemus's request in #10326, though this is not sufficient to close that issue.
A
=> Use an explicit encoding when opening `os.devnul`

doc/en/how-to/tmp_path.rst
The legacypath plugin handles the tmpdir and tmpdir_factory which should be update to their modern counterparts that uses pathlib.
Disabling this plugin allows developer to easily find and thus update the use of these fixtures.
Fixes #10199
=> Add note in documentation to help modernize code bases to use pathlib

.github/workflows/backport.yml, .github/workflows/prepare-release-pr.yml, .github/workflows/update-plugin-list.yml
Reverts pytest-dev/pytest#10346
Unfortunately the CHATOPS credentials no longer work, or don't have the necessary permissions. Was worth a try.
For now let's revert to get things working again, but can try again if:
- Someone who has access to `pytestbot` can refresh the `CHATOPS` secret (with maybe a more appropriate name...)
- We create a new machine user
=> Revert "ci: fix PR not triggering workflows by switching back to pytestbot access token"

AUTHORS, changelog/10344.doc.rst, doc/en/how-to/writing_plugins.rst
This PR replaces the documentation on writing plugins and making them discoverable to Pytest
by favouring the use of `pyproject.toml` instead of `setuptools.py`
Closes #10344.
=> Replace entrypoint example with `pyproject.toml` in docs

changelog/10196.trivial.rst, doc/en/reference/reference.rst, src/_pytest/compat.py, src/_pytest/warning_types.py
=> PytestReturnNotNoneWarning now subclasses PytestRemovedIn8Warning

changelog/7792.bugfix.rst, src/_pytest/mark/structures.py, testing/test_mark.py
fixes #7792
closes #9105 as superseeded
adding extra reviewers as this can be seen as breaking change wrt the contents of the pytestmark attribute
it may be necessary (and a good idea) to start to deprecate pytestmark as name and start using a private name as a follow up
=> fix #7792: consider marks from the mro

changelog/10381.improvement.rst, doc/en/how-to/output.rst, src/_pytest/terminal.py, testing/test_terminal.py
Fixes #10381
This is necessary for `addopts=--showlocals` where individual test runs need to not show locals.
=> :wrench: `--no-showlocals` to negate `addopts` w/ `--showlocals`

AUTHORS, changelog/10382.bugfix.rst, src/_pytest/debugging.py, testing/test_debugging.py
Closes https://github.com/pytest-dev/pytest/issues/10382
Don't break into pdb when `raise unittest.SkipTest()` appears top-level in a file.
I attempted to follow the instructions [here](https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst#long-version).  Please let me know if I missed anything.
I can't run the pytests directly, so let's see what CI says once I open this PR.  Both the `pip` and `tox` [instructions](https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst#long-version) fail with a `minversion` error:
<details><summary>tox error</summary>
```
(venv) user@virtual-machine:~/pytest$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
(venv) user@virtual-machine:~/pytest$ git rev-parse HEAD
15ac0349b2c7d8dc48fe2e25a1b4fa47c9fda25c …
```
=> Don't break into pdb when `raise unittest.SkipTest()` appears top-level in a file

CONTRIBUTING.rst
Tags from the main repository are required for testing to work properly, but the current documentation does not reflect this, and at least one new contributor has been tripped up by this. Update the documentation with a short explanation and directions.
=> Add note on tags to CONTRIBUTING.rst

.github/workflows/test.yml, .pre-commit-config.yaml, changelog/10396.deprecation.rst, setup.cfg, src/_pytest/_py/error.py, src/_pytest/_py/path.py, src/_pytest/compat.py, src/py.py, testing/_py/test_local.py, testing/test_pathlib.py, tox.ini
there is one tiny behavioural change -- that is `sysexec` now raises `RuntimeError` instead of a sepcialized `py.process.cmdexec` error -- I think this is probably fine, I doubt anyone is actually using `py.path.local.sysexec` 🤷 
otherwise we could vendor that module too -- but seems not worth
=> vendor py.path and py.error

CONTRIBUTING.rst
Fix small grammatical issues in CONTRIBUTING.rst to improve readability.
=> Fix typos in CONTRIBUTING.rst

changelog/7431.feature.rst, doc/en/how-to/logging.rst, src/_pytest/logging.py, testing/logging/test_reporting.py
Users want to suppress logger by name when invoking pytest.
- Added new CLI option to suppress loggers by name.
- A null filter is added to each logger, which returns False for every log entry.
Based off https://github.com/pytest-dev/pytest/pull/7873/files from @symonk 
Closes #7431
=> [7431] Add --suppress-logger CLI option

changelog/10226.improvement.rst, src/_pytest/runner.py, testing/test_runner.py
We might get exceptions from multiple steps of teardown, and now we have a way of reporting more than one!  Fixes #8217.
=> Use exceptiongroup for multiple errors during teardown

.github/workflows/deploy.yml
Otherwise we see this warning:
```
Warning:  You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.
```
=> Use specific tag in the gh-action-pypi-publish action

AUTHORS, src/_pytest/python_api.py
=> fix type in python_api.py

changelog/10452.bugfix.rst, src/_pytest/assertion/rewrite.py, tox.ini
Python 3.12 alpha 1 is [now out](https://discuss.python.org/t/python-3-12-0-alpha-1-released/20298?u=hugovk) and `importlib.abc.TraversableResources` is deprecated in favour of `importlib.resources.abc.TraversableResources`, with the old one set to be removed in Python 3.14:
* https://docs.python.org/3.12/whatsnew/3.12.html#pending-removal-in-python-3-14
* https://github.com/python/cpython/issues/93963
Here's a fix to avoid deprecation warnings during early testing of 3.12 with pytest:
```
DeprecationWarning: 'importlib.abc.TraversableResources' is deprecated and slated for removal in Python 3.14
```
I added 3.12 to `tox.ini` but not to GitHub Actions because it's not there yet, but should be soon:
* https://github.com/actions/setup-python/issues/514
If you prefer, we could test 3.12 via …
=> Fix 'importlib.abc.TraversableResources' deprecation warning in Python 3.12

scripts/update-plugin-list.py
The update of the plugin list has been [failing for two months now](https://github.com/pytest-dev/pytest/actions/workflows/update-plugin-list.yml) due to a plugin that managed to put `null` in its summary (instead of the empty string). I have proposed [a fix to that package](https://github.com/thewtex/pytest-web3-data/pull/6), but we might as well make the update script a bit more robust.
I don't know how it is possible that a null summary was produced, potentially this is a bug in hatchling.
=> scripts/update-plugin-list: Be liberal in accepted summaries

scripts/update-plugin-list.py
PEP 566 does not require a space after the dependency name.
I tested this change and found that it detected all dependencies previously detected, plus some more. There were no unwanted detections. Note that the old test was technically wrong: `"pytest " in requirement` may trigger on a `pytest` suffix. The new test may be slower, but this was not noticeable (the script is not fast anyway).
=> scripts/update-plugin-list: Improve requirement detection

AUTHORS, changelog/8141.feature.rst, doc/en/reference/reference.rst, src/_pytest/main.py, src/_pytest/pathlib.py, src/_pytest/tmpdir.py, testing/test_tmpdir.py
closes #8141
I recognize that the tests are insufficient but I couldn't find a good reference. Is there any integration tests that actually make sure only 3 directories remain after executing a test that uses `tmp_dir` fixture for multiple times? I assume no and it's probably because it's difficult to deal with `atexit.register`?
=> Adds a feature to control how directories created by the `tmp_path` fixture are kept.

AUTHORS, changelog/10457.bugfix.rst, src/_pytest/fixtures.py, testing/test_skipping.py
=> issue-10457/show test name when skipping from fixture

changelog/10502.bugfix.rst, src/_pytest/tmpdir.py, testing/test_tmpdir.py
=> Fix `tmp_path_retention_policy` crash when skipping from fixture

changelog/10506.bugfix.rst, src/_pytest/config/findpaths.py, testing/test_findpaths.py
Closes #10506 
Helps run pytest on machines where the root directory being "C:\" 
is an issue some people have "C://" as their root directory so os.sep fixes this issue, os.path.sep can also work.
=> Issue #10506

doc/en/example/simple.rst, src/_pytest/tmpdir.py
To store test results, it's better to use `.stash` instead of adding attributes on items. However, the documentation currently advises to add attributes. So it's probably better to update the documentation.
Some contexts: 
https://github.com/pytest-dev/pytest/pull/10442#discussion_r1023643840
https://github.com/pytest-dev/pytest/pull/10517
=> Modify documentation to use `.stash` when storing test results.

.pre-commit-config.yaml, .readthedocs.yml, doc/en/explanation/goodpractices.rst, doc/en/requirements.txt, tox.ini
Backport of #10578 (done manually due to conflicts).
=> [7.2.x] Fix tox 4.0 support and docs

AUTHORS, changelog/6267.improvement.rst, src/_pytest/assertion/truncate.py, testing/test_assertion.py
The full output of a test is no longer truncated if the truncation message would be longer than
the hidden text. The line number shown has also been fixed.
I also used f-string for faster string formatting in a previous commit, I don't think this warrant another MR though.
Closes #6267
=> Avoid truncation when truncating means longer output

changelog/8141.feature.rst, doc/en/how-to/tmp_path.rst, doc/en/reference/reference.rst, src/_pytest/tmpdir.py, testing/test_tmpdir.py
Partially addresses #10564.
In any case, we should set the default to `all`.
=> Change the default `tmp_path_retention_policy` to `all`

testing/conftest.py, testing/io/test_terminalwriter.py, testing/test_terminal.py
Fix https://github.com/pytest-dev/pytest/issues/10630
This PR adapt the color tests with the latest pygments 2.14.0 release, adding the some new ending sequence (`\x1b[90m\x1b[39;49;00m`) when it's needed.
=> Fix tests pygments 2.14.0

changelog/10607.bugfix.rst, src/_pytest/junitxml.py
Closes https://github.com/pytest-dev/pytest/issues/10604 which could intermittently display unexpected behavior between checking if the path exists and requesting creation. This was relatively common when pytest was being invoked in parallel by another test runner (CTest) and trying to create the same parent-folder for multiple XMLs. A modest amount of testing did not reproduce additional filesystem race conditions.
This notably does not work around another edge case where the parent path of the XML could be created as a file instead of a folder or link. That vanishingly rare case should cause file creation to fail on the next line, with a fairly obvious exception message.
=> Mitigate directory creation race condition

tox.ini
Since tox 4.0, the `whitelist_external` option has been renamed to [allowlist_externals](https://tox.wiki/en/4.2.6/config.html#allowlist_externals).
Noticed while trying to kick-off `7.2.1`: https://github.com/pytest-dev/pytest/actions/runs/3862747243/jobs/6584505508
=> Fix regen tox environment

changelog/10660.bugfix.rst, src/_pytest/python_api.py, testing/typing_checks.py
Makes `AbstractContextManager` the shared base class between "raises" and other context managers.
Closes #10654.
=> Derive pytest.raises from AbstractContextManager

AUTHORS, changelog/10592.bugfix.rst, src/_pytest/cacheprovider.py, src/_pytest/config/__init__.py, testing/test_cacheprovider.py
Close #10592
if the cmdline contains both the `--cache-show` and `--help` option will cause the internal error .  But if contains the `--collect-only` and `--help` will just output the help message.
the root cause is inside `pytest_cmdline_main` of `cacheprovider` , it will really execute the `wrap_session` , but it will raise   exception due to missing variable assignment .  so add the condition express to avoid the conflict .
=> Fix option error

AUTHORS, changelog/10592.bugfix.rst, src/_pytest/cacheprovider.py, testing/test_cacheprovider.py
Closes #10592
(cherry picked from commit 4d4ed42c34fbd6b30bff1bbdf664aeac3300a83a)
=> [7.2.x] Fix crash if `--cache-show` and `--help` are passed at the same time

changelog/10669.trivial.rst, setup.cfg, src/_pytest/_code/code.py, src/_pytest/cacheprovider.py, src/_pytest/compat.py, src/_pytest/config/__init__.py, src/_pytest/fixtures.py, src/_pytest/legacypath.py, src/_pytest/main.py, src/_pytest/mark/__init__.py, src/_pytest/mark/expression.py, src/_pytest/mark/structures.py, src/_pytest/python.py, src/_pytest/reports.py, src/_pytest/runner.py, src/_pytest/skipping.py, src/_pytest/terminal.py, src/_pytest/tmpdir.py, src/_pytest/warning_types.py, testing/acceptance_test.py, testing/conftest.py, testing/python/metafunc.py, testing/test_config.py, testing/test_pathlib.py, testing/test_tmpdir.py
Since pytest now requires Python>=3.7, we can use the stdlib attrs clone, dataclasses, instead of the OG package.
attrs is still somewhat nicer than dataclasses and has some extra functionality, but for pytest usage there's not really a justification IMO to impose the extra dependency on users when a standard alternative exists.
=> Drop attrs dependency, use dataclasses instead

src/_pytest/capture.py
mypy now supports generic NamedTuple.
=> capture: `CaptureResult` can be a namedtuple again

AUTHORS, changelog/10658.improvement.rst, src/_pytest/config/__init__.py, testing/test_config.py
Most pytest CLI arguments expecting a value accept the form `--arg=value`, which
makes it easy to have a single line per argument in the `addopts = [...]` section of
the configuration.
This is not the case for `-p` (to enable or disable pluggins), because it is
parsed in a different step. This argument must either consist of two strings
(`"-p", "<value>"`), or a single string without space (`"-p<value>"`). This is
perfectly fine for the CLI, but less intuitive for the config file. This PR
allows `"-p <value>"` to work as well.
Basically, this PR makes the following config work:
```toml
[tool.pytest.ini_options]
addopts = [
"-p no:logging",
]
```
Note that this is mostly an esthetic change, the behavior remains the same.
=> CLI: Allow spaces in -p arguments

src/_pytest/capture.py, testing/test_capture.py
I'm looking at improving the capture plugin again, but first I thought I'd finish the typing. Adds some verbosity but needed to "capture" the current usage.
Might be easier to review commit by commit.
=> capture: improve typing

.github/workflows/update-plugin-list.yml, scripts/update-plugin-list.py
The latest 'packaging' release has dropped support for `LegacyVersion`, meaning that version strings which do not conform to the standard now raise an error.
=> Fix update-plugin-list workflow due to new 'packaging'

changelog/10533.bugfix.rst, src/_pytest/python_api.py, testing/python/approx.py
=> added a check if denominator is zero

doc/en/how-to/capture-warnings.rst
Add example using `re.escape` to escape arbitrary literal strings which might contain regular expression characters like ( or .
Also discussed in https://github.com/pytest-dev/pytest/issues/10595
=> Clarify docs for `match` regarding escaping

AUTHORS, changelog/10597.bugfix.rst, src/_pytest/python.py, testing/test_nose.py
Closes #10597 
This behavior seems to have been introduced in #9273
Since I noticed support for `nose` is being deprecated I didn't add any additional test coverage.
But I'm not familiar with how `pytest` should interact with `nose` so any additional verification is welcome :)
=> Bugfix nose teardown regression

AUTHORS, changelog/10710.improvement.rst, src/_pytest/reports.py, testing/test_reports.py
TestReport objects stored only the information about stage duration. This is not enough to correlate pytest stages with external events. Timestamps are already there in CallInfo. They just needed to be propagated to TestReport objects, so that they can be read when TestReports are exported externally (for example with --reportlog option)
Closes #10710
=> Propagate timestamps from CallInfo to TestReport objects

.github/workflows/deploy.yml, .github/workflows/test.yml, pyproject.toml
This uses https://github.com/hynek/build-and-inspect-python-package to ensure our package is correct, both during testing and deploy.
Also include option to cancel running jobs when new commits for the same branch are pushed.
=> Use build-and-inspect-python-package action

.github/workflows/deploy.yml, .github/workflows/test.yml, pyproject.toml
This uses https://github.com/hynek/build-and-inspect-python-package to ensure our package is correct, both during testing and deploy,
Backport of #10722
=> [7.2.x] Use build-and-inspect-python-package action (#10722)

doc/en/explanation/pythonpath.rst, src/_pytest/pathlib.py
Nowadays, the prepend and append import modes use importlib.import_module() instead of __import__().
There was a phrase “which avoids having to use `__import__`”, in which I couldn’t just replace `__import__` by `importlib.import_module` because the latter is used (in insert_missing_modules()) also when using importlib mode. Therefore I removed the part from the sentence.
=> Update import mode documentation to not refer to __import__() anymore.

src/_pytest/python_api.py
Replaced "excepted" with "expected" in docstring and a variable name.
=> Fix typo in python_api.py

changelog/10753.doc.rst, src/_pytest/outcomes.py
this changes the wording of the module level skip to be very explicit about the effect
=> docs: be more explicit about module level skip preventing collection

testing/acceptance_test.py, testing/test_monkeypatch.py
`pgk_resources.declare_namespace` has been deprecated, so added an ignore warnings option to the test.
=> Fix test_cmdline_python_namespace_package

changelog/10533.bugfix.rst, changelog/10597.bugfix.rst, changelog/10626.bugfix.rst, changelog/10660.bugfix.rst, changelog/10753.doc.rst
Went over all changelog entries making sure they follow our guidelines as written at:
https://github.com/pytest-dev/pytest/blob/88c9e92258a15697c4f125ea1b930856ebe2975f/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L18-L21
=> Normalize how changelog entries are written

changelog/10765.bugfix.rst, src/_pytest/compat.py, src/_pytest/tmpdir.py
Emscripten defines `getuid()` as a stub that always returns 0.  This change is necessary for our unit testing suite to pass under node.js.
Have no need to be added to AUTHORS for such a trivial change.
Closes #10765
=> Fix OSError in tmpdir on emscripten due to missing getuid()

changelog/10755.feature.rst, changelog/10755.improvement.rst, doc/en/reference/reference.rst, src/_pytest/terminal.py, testing/test_terminal.py
This PR is missing documentation and changelog! It is intended to jumpstart a discussion about the best approach for allowing progress bars when capture=no. The rationale and more background is in https://github.com/pytest-dev/pytest/issues/10737 along with some possible alternative approaches to solve our underlying "lines too long" problem.
I don't love this solution (and the value is a placeholder!), but a separate ini variable or CLI flag is also inelegant since their purpose is to affect the behavior of a combination of `console_output_style` being `progress` and `capture` being set to `no`.
=> allow a progress bar even when capture=no

changelog/10727.improvement.rst, doc/en/builtin.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/example/reportingdemo.rst, doc/en/example/simple.rst, doc/en/getting-started.rst, doc/en/how-to/output.rst, doc/en/how-to/writing_plugins.rst, doc/en/reference/reference.rst, src/_pytest/terminal.py, testing/test_config.py, testing/test_terminal.py
i found it painful to read crammed in a single line thus rootdir, config file and testpaths now have own lines
=> split up report header lines for config, rootdir and testpaths

AUTHORS, changelog/10840.improvement.rst, src/_pytest/_code/code.py, testing/code/test_excinfo.py
This is a small change to some checks in `FormattedExcinfo` to avoid the following internal crash in pytest given pathological traceback information:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "…/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "…/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "…/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "…/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return …
```
=> FormattedExcinfo.get_source: Avoid a crash when source.lines == 0

tox.ini
This dep is not needed on newer Pythons.
=> tox: remove `dataclasses` dependency from `regen`

doc/en/changelog.rst
As discussed in https://github.com/pytest-dev/pytest/pull/10669#issuecomment-1501497729, we should make the reasoning behind this change more clear, as well as thank the attrs maintainers for the many years of cooperation and support.
=> Amend changelog note for removal of attrs

changelog/10875.improvement.rst, changelog/10890.improvement.rst, src/_pytest/pathlib.py, src/_pytest/unittest.py, testing/test_tmpdir.py
Fixes #10890 and #10875.
py3.12 CI is currently blocked (see #10894), but shouldn't block these changes, which are quite simple and which I tested locally.
=> Python 3.12 alpha fixes

src/_pytest/_code/code.py
This API is OK, I don't think we're going to change something about it at this point.
=> code: drop Experimental API label from ExceptionInfo.from_exc_info

changelog/10901.feature.rst, src/_pytest/_code/code.py, src/_pytest/python_api.py, testing/code/test_excinfo.py
The old-style `sys.exc_info()` triplet is redundant nowadays with `(type(exc), exc, exc.__traceback__)`, and is beginning to get soft-deprecated in Python 3.12.
Add a nicer API to ExceptionInfo which takes just the exc instead of the triplet. There are already a few internal uses which benefit.
=> code: add `ExceptionInfo.from_exception`

AUTHORS, src/_pytest/_code/code.py, src/_pytest/nodes.py, src/_pytest/reports.py, testing/code/test_excinfo.py
By "empty traceback" I mean a traceback all of whose entries have been filtered/cut/pruned out.
Currently, if an empty traceback needs to be repr'ed, the last entry before the filtering is used instead (added in
accd962c9f88dbd5b2b0eef6efe7bf6fe5444b29).
Showing a hidden frame is not so good IMO. This commit does the following instead:
1. Shows details of the exception.
2. Shows a message about how the full trace can be seen.
Example:
```
_____________ test _____________
E   ZeroDivisionError: division by zero
All traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames.
```
Also handles `--tb=native`, though there the `--full-trace` bit is not shown.
This commit contains some pieces from
431ec6d34ef99d80f90b330876ed6231144a3ce7 (which has been reverted).
Helps …
=> code: handle repr'ing empty tracebacks gracefully

changelog/10896.bugfix.rst, src/_pytest/pathlib.py, src/_pytest/tmpdir.py
The problem is that we would loop over all directories of the basetemp directory searching for dead symlinks, for each test, which would compound over the test session run.
Doing the cleanup just once, at the end of the session, fixes the problem.
Fix #10896
=> Fix tmp_path regression introduced in 7.3.0

changelog/10907.improvement.rst
I forgot to git add the changelog for #10907.
=> doc: add missing changelog for #10907

testing/acceptance_test.py, testing/logging/test_reporting.py
Since we've replaced all uses of testdir with pytester, a few were added back.
=> testing: remove usages of testdir that sneaked back in

doc/en/index.rst
There we go again! There might be more coming up (submitted to [Europython](https://ep2023.europython.eu/), planning to submit to [Workshoptage](https://workshoptage.ch/), and possibly [enterPy](https://www.enterpy.de/) if it is again), but ironically, the one most in the future is the first one to be definitive :upside_down_face:
=> Add 2024 pytest training

testing/acceptance_test.py, testing/test_monkeypatch.py
Fixes https://github.com/pytest-dev/pytest/issues/10815
=> Filter new pkg_resources deprecations

doc/en/index.rst
Sorry for the noise - missed that with the original PR, based on the 2023 data. Hopefully it'll be a hybrid one in 2024 again!
=> doc: Fix 2024 training location

doc/en/explanation/goodpractices.rst, doc/en/reference/plugin_list.rst
Hello! This is my first PR in opensource project. Please, don't judge me harshly.
This PR closes #10709 by adding `flake8-pytest-style` to `plugin_list.rst`.
=> add flake8-pytest-style to plugin_list.rst

src/_pytest/_py/path.py, src/_pytest/faulthandler.py
See https://github.com/pytest-dev/pytest/pull/10328#issuecomment-1528045842 for context.
The `py.path` one might be better to leave as-is, but I lean toward fixing.
=> Fix couple of EncodingWarnings

AUTHORS, changelog/10940.improvement.rst, src/_pytest/terminal.py, testing/test_terminal.py
Fixes #10940.
This functionality is covered by an existing test that only needed minor updates to match new output.  There were a couple of identical lines in the output used for text matching, so I added numbers to disambiguate.
Let me know if there are any suggestions or changes needed.
=> Improve verbose output by wrapping skip/xfail reasons with margin

src/_pytest/hookspec.py
This is a minor fix to a reference to a no-longer-existing private module. There should be no runtime effects, because the fix is made under a `typing.TYPE_CHECKING` block.
---
I've read through #7469, where there was a public API typing change
> - [x] `_pytest.code.ExceptionInfo` -> `pytest.ExceptionInfo`
but as the rest of the references in the [same block in `_pytest/hookspec.py`](https://github.com/pytest-dev/pytest/blob/a88ae8289cd21d39dd360666bb2e83dfa98b215e/src/_pytest/hookspec.py#L23-L44) are all for private modules, I thought it would be best to continue using a private module instead of switching the reference to a public `from pytest import ExceptionInfo`.
=> fix reference to non-existent module

.github/workflows/stale.yml, changelog/10169.bugfix.rst, changelog/10987.bugfix.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, testing/test_collection.py, testing/test_conftest.py
The `testpaths` option is meant to be identical to execute pytest passing the 'testpaths' directories explicitly.
This also fixes #10169, given I had to change the same part of the code in order to get tests to pass on Python 3.7. 
Fix #430
Fix #10169 
Fix #10987
=>  Consider testpaths for initial conftests

.pre-commit-config.yaml
This makes it difficult to run on newer python versions than the one specified.
=> pre-commit: remove `default_language_version` setting

doc/en/backwards-compatibility.rst
=> Reference "Status of Python Versions" in backwards-compatibility policy

AUTHORS, changelog/8711.improvement.rst, src/_pytest/config/__init__.py, src/_pytest/logging.py, testing/logging/test_fixture.py
Forces requested `caplog` logging levels to be enabled if they were disabled via `logging.disable()`
`[attr-defined]` mypy error ignored in `logging.py` because there were existing errors with the imports
and `loggin.Logger.manager` is an attr set at runtime. Since it's in the standard lib I can't really fix that.
Ignored an attr-defined error in `src/_pytest/config/__init__.py` because the re-export is necessary.
Closes #8711
=> #8711: Handle disabled logging in 'caplog.set_level' and 'caplog.at_level' 

doc/en/example/nonpython/conftest.py
The definition of `repr_failure` on the `YamlItem` subclass only handled the custom `YamlException` class, which hides all other errors from the user. By adding in the `super` call we ensure all other exception types also appropriately handled by `repr_failure`.
=> nonpython example now repr all exceptions

AUTHORS, changelog/10991.improvement.rst, src/_pytest/logging.py, testing/logging/test_reporting.py
Added handling of ``%f`` directive to print microseconds in log format options, such as ``log-date-format``. It is impossible to do with a standard `logging.Formatter` because it uses `time.strftime` which doesn't know about milliseconds and ``%f``. In this PR I added a custom Formatter which converts `LogRecord` to a `datetime.datetime` object and formats it with ``%f`` flag. This behaviour is enabled only if a microsecond flag is specified in a format string.
Also added a few tests to check the standard and changed behaviour.
Closes #10991.
=> Handle microseconds with custom logging.Formatter

changelog/11028.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
In #10758 we introduced the support for the use of the walrus operator in the test cases. There was a case which was not handled that caused a bug report #11028. This PR aims to fix the issue and also to improve how the walrus operator is handled in the AssertionRewriter class.
closes #11028
Made during ![Open Source Saturday Italy](https://img.shields.io/badge/Open%20Source%20Saturday-Italy-red)
=> 11028 - Fix warlus operator behavior when called by a function

changelog/11054.bugfix.rst, src/_pytest/cacheprovider.py, testing/test_cacheprovider.py
`--lf` has a feature where if a certain `Module` (python file) does not contain any failed tests, it is skipped entirely at the collector level instead of being collected and each item skipped individually. When this happens the collection summary looks like this:
run-last-failure: rerun previous 1 failure (skipped 1 file)
However, this feature didn't work for `Module`s inside of `Package`s, only for those directly beneath the `Session`.
Fix #11054.
=> cacheprovider: fix file-skipping feature for files in packages

changelog/1904.bugfix.rst, src/_pytest/_code/code.py, src/_pytest/nodes.py, src/_pytest/python.py, src/_pytest/unittest.py, testing/code/test_excinfo.py, testing/python/collect.py
This PR is my proposal for fixing #1904 (previous attempt 431ec6d34ef99d80f90b330876ed6231144a3ce7 was reverted).
The main entry for rendering the traceback for a test exception is `Node._repr_failure_py`. It takes the excinfo and returns a `TerminalRepr`. Two parts of it are relevant here:
https://github.com/pytest-dev/pytest/blob/4eca6063c8df11a0bb8dbe23745294aa5d5fec67/src/_pytest/nodes.py#L452-L457
This calls the node's `_prunetraceback` method with the excinfo, which then proceeds to filter out internal entries, hide `__tracebackhide__ = True` frames, etc. It modifies the `excinfo` in-place by updating its `excinfo.traceback` field.
https://github.com/pytest-dev/pytest/blob/4eca6063c8df11a0bb8dbe23745294aa5d5fec67/src/_pytest/nodes.py#L481-L488
This calls into the main …
=> Fix hidden traceback entries of chained exceptions getting shown

changelog/11043.improvement.rst, src/_pytest/config/__init__.py, testing/test_config.py, testing/test_conftest.py
Currently, if `--confcutdir` is not set, `inipath.parent` is used, and if `initpath` is not set, then `confcutdir` is None, which means there is no cutoff.
Having no cutoff is not great, it means we potentially start probing stuff all the way up to the filesystem root directory. So let's add another fallback, to `rootpath`, which is always something reasonable.
=> config: fallback confcutdir to rootpath if inipath is not set

src/_pytest/python.py
They are already inherited exactly the same from FSCollector:
https://github.com/pytest-dev/pytest/blob/24534cdd29d74e302e86db1a719c99e024d7903e/src/_pytest/nodes.py#L646-L652
=> python: remove redundant methods from Package

src/_pytest/cacheprovider.py, testing/test_cacheprovider.py
Continuation of fc538c5766a1c67bfcd704288279ceac5e20070a. Fixes #11054 again.
=> cacheprovider: fix file-skipping functionality across packages

changelog/11068.bugfix.rst, src/_pytest/cacheprovider.py, testing/conftest.py, testing/test_cacheprovider.py
~~NOTE: Includes #11059, will rebase after it's merged.~~
No reason for `--lf`'s whole-file-skipping feature to not for for non-Python files.
Fix #11068.
=> cacheprovider: make file-skipping work with any File, not just Modules

src/_pytest/main.py
- Works better on Windows (case sensitivity)
- Simpler code
=> main: change pkg_roots to work with `Path`s instead of string paths

changelog/11081.improvement.rst, src/_pytest/main.py, src/_pytest/python.py
=> main: move norecursedir check to main's pytest_ignore_collect

.github/workflows/test.yml, .pre-commit-config.yaml, changelog/10894.bugfix.rst, setup.cfg, src/_pytest/assertion/rewrite.py, src/_pytest/mark/expression.py, testing/python/collect.py
~~This is currently blocked on https://github.com/sissaschool/xmlschema/issues/342.~~
Blocked on python 3.12-beta.2 release in https://github.com/actions/python-versions/blob/main/versions-manifest.json
=> Python 3.12 support

AUTHORS, changelog/9146.doc.rst, src/_pytest/logging.py
=> Updated logging.py for #9146

changelog/11104.bugfix.rst, src/_pytest/config/__init__.py, testing/test_collection.py, testing/test_conftest.py
Fixes #11104. See the commits; the first one is just a refactor.
=> config: fix the paths considered for initial conftest discovery

doc/en/reference/reference.rst
=> reference: add note that `pythonpath` does not affect `-p`

changelog/8976.breaking.rst, doc/en/deprecations.rst, src/_pytest/python.py, testing/example_scripts/collect/package_init_given_as_arg/pkg/__init__.py, testing/example_scripts/collect/package_init_given_as_arg/pkg/test_foo.py, testing/python/collect.py, testing/test_collection.py, testing/test_doctest.py, testing/test_nose.py
Previously it would collect the entire package, but this is not what users (including me) expect.
Refs #3749
Fixes #8976
Fixes #9263
Fixes #9313
---
Technically I'd say this is a bug fix, but I'm not entirely sure the previous behavior wasn't intentional (there are certainly several tests to the contrary). And it also has potential of breaking users who somehow rely on the previous behavior. Therefore I've marked this as `breaking`, and it should not be merged before we decide the next version will be a major. Still, acks would be good already :)
=> python: change `pytest pkg/__init__.py` to only collect the `__init__.py` Module

AUTHORS, changelog/11011.doc.rst, doc/en/how-to/logging.rst
Add a warning to the documentation based on my findings for #11011
=> add a warning about modifying the root logger during tests

AUTHORS, changelog/9288.breaking.rst, src/_pytest/recwarn.py, testing/test_recwarn.py
PR Description: 
This issue fixes part of issue #9288 by allowing ``pytest.warns()`` to emit all unmatched warnings. 
One question I have with the design is how to handle the exceptions once we re-emit them. Having ``pytest.warns()`` calls return all exceptions will require refactoring of other tests. There doesn't seem to be a way to check whether the code is within a WarningsChecker frame, so a way to solve this is an optional-argument for re-emitting?
=> Make `pytest.warns()` re-emit all non-matching warnings

changelog/9036.bugfix.rst, src/_pytest/recwarn.py, testing/test_recwarn.py
continue PR #10208 by @eltimen
Fixes #9036 and #11032 (same issue)
When a warning is being warned while an exception is raised, `pytest.warns` should still capture the warning if not matched.
CC @Zac-HD
=> capture warning when exception is raised (fix #9036)

changelog/10811.bugfix.rst, src/_pytest/pathlib.py, testing/acceptance_test.py, testing/test_pathlib.py
The initial implementation (in #7246) introduced the `importlib` mode, which never added the imported module to `sys.modules`, so it included a test to ensure calling `import_path` twice would yield different modules.
Not adding modules to `sys.modules` proved problematic, so we began to add the imported module to `sys.modules` in #7870, but failed to realize that given we are now changing `sys.modules`, we might as well avoid importing it more than once.
Then #10088 came along, passing `importlib` also when importing application modules to collect docstrings (as opposed to only test modules before), which caused problems due to imports having side-effects and the expectation being that they are imported only once.
With this PR, `import_path` returns the module immediately if already in …
=> Fix duplicated imports with importlib mode and doctest-modules

changelog/10447.bugfix.rst, src/_pytest/mark/structures.py, testing/test_mark.py
=> fix #10447 - consider marks in reverse mro order to give base classes priority

.github/workflows/deploy.yml
Closes #10871
Closes #10870
Backport of #10925.
=> [7.4.x] Switch to deploy environment and configure for pypi oidc (#10925)

AUTHORS, changelog/10701.bugfix.rst, pyproject.toml, src/_pytest/recwarn.py, testing/test_recwarn.py
=> fix #10701 - warnings recorder pop match also subclass

tox.ini
=> tox: turn off PYTHONWARNDEFAULTENCODING for pre-commit, sphinx etc.

doc/en/how-to/nose.rst
Introducing a small table with a legend detailing the default naming conventions used by `nose` and `pytest`
Based on the following [discussion](https://github.com/pytest-dev/pytest/discussions/8024#discussioncomment-144309).
Adding the tables here:
| Convention                  | unittest | pytest |
|-----------------------------|----------|--------|
| Ⓜ test*.py                 | ✅       |        |
| Ⓜ test_*.py                | ✅       | ✅     |
| Ⓜ *_test.py                |          | ✅     |
| Ⓜ *_tests.py               |          |        |
|    Ⓒ  *(unittest.TestCase) | ✅       | ✅    |
|       ⓜ test_*             | ✅       | ✅    |
|    Ⓒ Test*                 |          | ✅      |
|       ⓜ  test_*            |          | ✅      |
|    ⓕ test_*                |          | ✅ …
=> [docs] add naming convention defaults for nose and pytest

changelog/10702.bugfix.rst, src/_pytest/python_api.py, testing/python/approx.py
Closes #10702
Dict comparsion in the ApproxMapping class did not check if values were None before attempting to subtract for max_abs_diff stat, which was throwing an TypeError instead of being handled by pytest error assertion. Check for None has been added before these calculations, so that None will properly show as Obtained/Expected in pytest assert message
=> Fix error assertion handling in approx when None in dict comparison

doc/en/example/nonpython/conftest.py, doc/en/example/simple.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/tmp_path.rst, doc/en/how-to/unittest.rst
Otherwise the warnings show in the regen output.
=> doc: fix EncodingWarnings in examples

doc/en/reference/reference.rst, src/_pytest/main.py, src/_pytest/nodes.py, src/_pytest/python.py
Please see the commit messages.
=> reference: improve the node types docs a bit

doc/en/how-to/usage.rst, src/_pytest/config/__init__.py
Add explicit mentions of the somewhat confusing default behavior (discussed in #11183) to both API reference and how-to section about ways to invoke pytest.
=> Clarify docs for pytest.main default behavior

changelog/11208.trivial.rst, changelog/7469.feature.rst, doc/en/reference/reference.rst, src/_pytest/compat.py, src/_pytest/doctest.py, src/_pytest/fixtures.py, src/pytest/__init__.py, testing/python/fixtures.py, testing/test_legacypath.py
These are some relatively small changes I made while going over the fixture code. Please see the commits.
=> fixtures: some tweaks & improvements

src/_pytest/_py/path.py, src/_pytest/config/argparsing.py, src/_pytest/fixtures.py, src/_pytest/hookspec.py, src/_pytest/logging.py, src/_pytest/main.py, src/_pytest/python.py, src/_pytest/reports.py, src/_pytest/runner.py, src/_pytest/scope.py, src/_pytest/terminal.py, src/_pytest/tmpdir.py, src/_pytest/warnings.py
Literal was added in Python 3.8 which we now require so can use it freely.
=> Use typing.Literal without TYPE_CHECKING checks

changelog/11216.improvement.rst, src/_pytest/fixtures.py, testing/test_skipping.py
=> fixtures: show test as skip location if skipped from an xunit setup function

AUTHORS, changelog/11227.improvement.rst, src/_pytest/_code/code.py, src/_pytest/python_api.py, testing/code/test_excinfo.py
Closes #11223
Adds support for matching against `__notes__` added to an exception within `pytest.raises`. See issue for discussion/ design.
* The doctest is skipped because `add_note` is only available in 3.11+
* An alternative could be to add a backport of this feature to `exceptiongroup`: https://github.com/agronholm/exceptiongroup/issues/31
=> Have pytest.raises match against exception `__notes__`

doc/en/example/multipython.py, doc/en/example/parametrize.rst
Remove "Indirect" from a few section names -- not actually indirect.
Also few minor updates to the related multipython.py example.
=> doc/example/parametrize: a few fixes/improvements

changelog/11255.bugfix.rst, src/_pytest/fixtures.py, testing/python/metafunc.py
There is handling for `scope="class"` without a class, but not for `scope="package"` without a package. It would fail the assert.
=> fixtures: fix crash when `parametrize(scope="package")` is used without a Package

changelog/11137.breaking.rst, doc/en/deprecations.rst, src/_pytest/cacheprovider.py, src/_pytest/fixtures.py, src/_pytest/main.py, src/_pytest/python.py
Fix #11137.
I'll leave detailed notes on the changes below to hopefully make them easier to understand.
=> python: change `Package` to no longer be a `Module`/`File`

doc/en/example/parametrize.rst
=> Improve example

doc/en/how-to/assert.rst
=> doc: update information about assertion messages

doc/en/reference/reference.rst
Links to here: [How to invoke pytest — pytest documentation](https://docs.pytest.org/en/7.4.x/how-to/usage.html#calling-pytest-from-python-code)
=> doc: Link pytest.main to how-to guide

changelog/11234.bugfix.rst, src/_pytest/fixtures.py, src/_pytest/python.py, testing/python/metafunc.py
Currently, when there are multiple fixturedefs for a param, `_find_parametrized_scope` picks the farthest one, while it should pick the nearest one.
=> Fix a tiny bug in `python.py::_find_parametrized_scope`

.github/workflows/test.yml
Pluggy dropped Python 3.7 support.
Also see 165fbbd12a74ab639d61ce1f28dfef1511a2c2e2
Fixes #11293
=> ci: Use Python 3.8 to test latest pluggy

src/_pytest/python.py
This would IMO fix the documentation-side of #11289.
As for the "feature-request-side" of it, if you see any chance to get allow `pytest_generate_tests` ever be used in an "overwriting" fashion, as can be done with fixture functions, I'd like to open a separate feature request issue on that.
=> Improve duplicate values documentation

src/_pytest/config/__init__.py, src/_pytest/main.py, testing/python/fixtures.py, testing/test_config.py, testing/test_conftest.py
Previously, the `_getconftestmodules` function was used both to load conftest modules for a path (during `pytest_load_initial_conftests`), and to retrieve conftest modules for a path (during hook dispatch and for fetching `collect_ignore`). This made things muddy - it is usually nicer to have clear separation between "command" and "query" functions, when they occur in separate phases.
So split into "load" and "get".
Currently, `gethookproxy` still loads conftest itself. I hope to change this in the future.
=> config: split `_getconftestmodules` and `_loadconftestmodules`

src/_pytest/fixtures.py, src/_pytest/python.py, testing/example_scripts/issue_519.py, testing/python/metafunc.py
- To remove `fixtures.py::add_funcargs_pseudo_fixture_def` and add its logic i.e. registering funcargs as params and making corresponding fixturedefs, right to `Metafunc.parametrize` in which parametrization takes place.
- ~To compute param indices smarter to have a better reordering experience.~ Moved to #11257 
- To remove `funcargs` from metafunc attributes as we populate metafunc params and make pseudo fixturedefs simultaneously and there's no need to keep funcargs separately.
=> Move `fixtures.py::add_funcarg_pseudo_fixture_def` to `Metafunc.parametrize`

src/_pytest/python.py
Follow up to https://github.com/pytest-dev/pytest/pull/11220#discussion_r1278265042
=> python: use clearer terminology for `_resolve_arg_value_types`

doc/en/reference/reference.rst, src/_pytest/mark/structures.py, src/_pytest/outcomes.py
=> doc: fix a few `xfail` nits

tox.ini
Explicitly add `doctest-coverage` to the `envlist` in `tox.ini` to fix failing CI, for example here: https://github.com/pytest-dev/pytest/actions/runs/5912812576/job/16036585548?pr=11317
_More details:_
Latest tox version enforces allowed tox environments to be explicitly in the tox `envlist` (https://github.com/tox-dev/tox/pull/3089).
Note there is some follow up work to relax these rules: https://github.com/tox-dev/tox/pull/3099
=> Add doctesting-coverage to envlist

pyproject.toml
Setting `norecursedirs` overrides the default, so we end up scanning dot-directories and such which slows down collection unnecessarily (by 150ms on my working directory for a noop).
=> testing: add `.*` to `norecursedirs`

scripts/update-plugin-list.py
Adding https://github.com/network-unit-testing-system/nuts to the plugin list.
=> add nuts to plugin list

changelog/7966.bugfix.rst, src/_pytest/assertion/util.py, testing/test_assertrewrite.py
Fixes #7966
Previously, the assertion rewrite mechanism would fail to capture raised errors within ``__iter__`` and suggest the error is within ``__repr__``, which this new reporting now fixes.
=> Improve reporting from __iter__ exceptions

src/pytest/__init__.py, testing/deprecated_test.py
=> use `if not TYPE_CHECKING` on `pytest.__getattr__` to prevent type checkers from using it

src/_pytest/pytester.py
=> doc: fix docstring spelling in pytester

changelog/11353.trivial.rst, doc/en/reference/reference.rst, setup.cfg, src/_pytest/config/__init__.py, src/_pytest/helpconfig.py, src/_pytest/logging.py, src/_pytest/pytester.py, testing/test_pluginmanager.py
Since version 1.3 pluggy added typing, which requires some fixes to please mypy.
*Pending release of pluggy 1.3*
I intend to backport this to 7.4.x but without bumping the pluggy requirement so will be a little different.
=> Fixes for typed pluggy

doc/en/reference/reference.rst, src/_pytest/config/__init__.py, src/_pytest/helpconfig.py, src/_pytest/logging.py, src/_pytest/pytester.py, testing/test_pluginmanager.py
Since version 1.3 pluggy added typing, which requires some fixes to please mypy.
Cherry pick of #11353 but not bumping the pluggy requirement.
=> [7.4.x] Fixes for typed pluggy

src/_pytest/compat.py, testing/test_parseopt.py
On Windows 10.0.19045, the mypy hook is failing on pre-commit because of two `[attr-defined]` errors, which prevents me from staging changes. The problem was first reported in #11343. This PR applies a fix by adding `type: ignore` comments to the erroring lines:
```
src\_pytest\compat.py:324: error: Module has no attribute "getuid"; maybe "getpid" or "getppid"?  [attr-defined]
testing\test_parseopt.py:294: error: Module has no attribute "getencoding"  [attr-defined]
```
=> fix: closes #11343's [attr-defined] type errors

AUTHORS, doc/en/how-to/cache.rst, doc/en/reference/reference.rst, src/_pytest/cacheprovider.py
closes #11354 
* *Improved documentation for last-failed-no-failures to make functionality more clear.*
=> Issue 11354 fixing docs for lfnf

.github/workflows/deploy.yml, .github/workflows/test.yml, RELEASING.rst
* Build the package only once, and test on all platforms.
* Deploy is now triggered manually via an Action, which is then responsible for tagging the repository after the package has been uploaded successfully.
* Drop 'docs': we nowadays rely on readthedocs preview PR builds.
---
This is cherry-picked from #11377: realized that we need to have `deploy` in `main` in order to be able to trigger `workflow_dispatch`.
=> Improve CI workflow

AUTHORS, changelog/11367.bugfix.rst, src/_pytest/junitxml.py, testing/test_junitxml.py
seem like not all the cases of calling `finalize` were adding the properties into the test case element, which leads to some test cases missing the expected properties.
Fixes: #11367
=> [junit] move properties handling to `finalize()`

AUTHORS, changelog/11367.bugfix.rst, src/_pytest/junitxml.py, testing/test_junitxml.py
Move handling of user_properties to `finalize()`.
Previously if a fixture failed during teardown, `pytest_runtest_logreport` would not be called with "teardown", resulting in the user properties not being saved on the JUnit XML file.
Fixes: #11367
(cherry picked from commit 917ce9aa0102c7f0ec8fdac118058c41ffb603e6)
=> [7.4.x] Fix user_properties not saved to XML if fixture errors during teardown

changelog/11306.bugfix.rst, src/_pytest/pathlib.py, testing/test_pathlib.py
For packages, `import_path` receives the path to the package's `__init__.py` file, however module names (as they live in `sys.modules`) should not include the `__init__` part.
For example, `app/core/__init__.py` should be imported as `app.core`, not as `app.core.__init__`.
Fix #11306
=> Fix import_path for packages

AUTHORS, changelog/11237.bugfix.rst, src/_pytest/doctest.py, testing/test_doctest.py
I'll be first to admit that the proposed solution is _very_ hacky but felt inspired by some adjacent code to do things this way. Suggestions for improvement are welcomed. 🙂
closes #11237
=> Fix doctest collection of `functools.cached_property` objects.

changelog/11394.bugfix.rst, src/_pytest/main.py, src/_pytest/pathlib.py, testing/test_main.py, testing/test_pathlib.py
=> Fix crash when passing a very long cmdline argument

changelog/11394.bugfix.rst, src/_pytest/config/__init__.py, src/_pytest/config/findpaths.py, src/_pytest/main.py, src/_pytest/pathlib.py, testing/test_main.py, testing/test_pathlib.py
Fixes #11394
(cherry picked from commit 28ccf476b91be32ffda303f0d7a8b57e475b465b)
=> [7.4.x] Fix crash when passing a very long cmdline argument (#11404)

src/_pytest/config/__init__.py, src/_pytest/config/findpaths.py, src/_pytest/pathlib.py, testing/test_pathlib.py
When backporting #11404 to `7.4.x`, Python 3.7 builds uncovered more places where the same treatment should be applied.
Related to #11394
=> [port from 7.4.x] Use _pytest.pathlib.safe_exists in get_dirs_from_args

.github/workflows/deploy.yml, RELEASING.rst, scripts/prepare-release-pr.py
As discussed in #11408:
* Improve documentation for the release process.
* Fix the description for the PRs created by the `prepare release pr` workflow.
* Fix pushing tag in the `deploy` workflow.
=> Adjustments to the release process

.github/workflows/deploy.yml, RELEASING.rst, scripts/prepare-release-pr.py
As discussed in #11408:
* Improve documentation for the release process.
* Fix the description for the PRs created by the `prepare release pr` workflow.
* Fix pushing tag in the `deploy` workflow.
(cherry picked from commit e5c81fa41aa437261009d2dcbed5f05bb2b86647)
=> [7.4.x] Adjustments to the release process (#11410)

src/_pytest/doctest.py, src/_pytest/fixtures.py, src/_pytest/python.py, testing/python/fixtures.py
A few more small fixture cleanups/improvements from looking at #11243.
The second commit is picked from #11243 authored by @sadra-barikbin. The idea is to make #11243 a bit smaller after it's rebased on top of this (which I'll be happy to do if @sadra-barikbin prefers).
The last commits are some doctest cleanups after checking its fixture handling. If we ever want to provide a proper interface for (non-`Function`) items to support fixtures, `DoctestItem` can be our model case.
=> fixtures: more tweaks

AUTHORS, changelog/11239.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
Fixes #11239
Track the rudimentary scope where `:=` are used to prevent replacing variables in other test cases. AFAICT it's not necessary to be precise and track every scope change as only `assert` nodes are visited anyway and those are not usually used in comprehensions, for example.
=> Fix assert rewriting with assignment expressions

src/_pytest/pathlib.py, testing/test_pathlib.py
Starting with `resolve_package_path()` and its associated tests, this refactoring seeks to make path concatenation more readable and consistent.
To be consistent, all uses of `.joinpath()` need to be replaced with the `/` operator or the other way around. I have chosen to standardise the use of the `/` operator across `resolve_package_path()` and its tests because
1) it is already used in the tests
2) it is more succinct and readable
3) casual profiling with `%timeit` didn't reveal a performance loss
`/` operator: 273 µs ± 86.6 µs
`.joinpath()`: 269 µs ± 99.4 µs
Eventual consistency within and across all files is the ultimate goal. This is achievable. There are currently 428 uses of `.joinpath()` across 45 files. Counting assignment expressions only, there are 111 uses of the `/` operator …
=> refactor: use division operator to join paths.

AUTHORS, changelog/11239.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
Fixes #11239
(cherry picked from commit 7259e8db9844f6f973c1d0c0ce46cc68c8248abb)
=> [7.4.x] Fix assert rewriting with assignment expressions (#11414)

src/_pytest/pathlib.py, testing/test_pathlib.py
We cannot have an empty module name when importing a `__init__.py` file that is at the rootdir.
Fixes #11417
=> Fix --import-mode=importlib when root contains `__init__.py` file

testing/python/collect.py
In the `testing/python/collect.py::TestSorting::test_ordered_by_definition_order` tests, self is not passed, this is an invalid signature of class functions.
=> Fix invalid signature in TestSorting tests

testing/conftest.py
=> Force terminal width when running tests

testing/conftest.py
Related to #11423
(cherry picked from commit 241f2a890e3fb3f83eac807de0b4ad00510c7f65)
=> [7.4.x] Force terminal width when running tests (#11425)

AUTHORS, changelog/10441.feature.rst, doc/en/getting-started.rst, doc/en/how-to/assert.rst, src/_pytest/_code/code.py, testing/code/test_excinfo.py
Tests if a captured exception group contains an expected exception. Will raise `AssertionError` if the wrapped exception is not an exception group. Supports recursive search into nested exception groups.
(edit by Zac) Fixes #10441.
=> Add new `ExceptionInfo.group_contains` assertion helper method

changelog/11447.improvement.rst, src/_pytest/recwarn.py, testing/test_recwarn.py
=> Add `FutureWarning` to `deprecated_call`

AUTHORS, changelog/11314.improvement.rst, src/_pytest/logging.py, testing/logging/test_reporting.py
**Overview**
Before this fix is applied, the current behavior when using CLI logging with the log_cli = true setting is as follows:
1) If --log-cli-format is not specified but --log-format is provided as argument, then value provided in --log-format is used as fallback
2) If --log-cli-date-format is not specified but --log-date-format is provided, then --log-date-format is used as fallback
3) If --log-cli-level is not specified but --log-level is provided, then --log-level is used as fallback
If no options are provided (neither specific CLI ones nor the generic ones) then hardcoded default values for these options are used.
The above behavior is inline with the expected behavior.
However, when using logging to file with the log_file option, the above behavior is not demonstrated. When …
=> Fixes issue #11314 - log_file_format does not default to log_format

AUTHORS, changelog/11439.bugfix.rst, src/_pytest/faulthandler.py
Closes #11439
Fix is to add ValueError to the caught exceptions in get_stderr_fileno().
The io.UnsupportedOperation exception inherits from ValueError so this has been removed.
=> fix for ValueError raised in faulthandler teardown code

src/_pytest/nodes.py
I attempt to add a docstring for `NodeMeta` that contains a helpful summary of what it does and the reason for its existence, as well as a link to a project board that contains more information. The intention was to make the docstring helpful to new and experienced contributors alike.
Note: I did a direct edit on the pytest repo but I am unsure if it came through. If the direct edit and this PR clash, then this PR is the authoritative contribution.
1) I am unsure whether my summary is accurate or current, so I'd be especially grateful if @RonnyPfannschmidt or others involved with detangling `Node` relationships could review this.
2) I don't have much experience with Sphinx documentation. I tried to use directives but I am unsure if linking to a project board should be handled in a …
=> Add class docstring to NodeMeta

changelog/11315.trivial.rst, src/_pytest/pytester.py, testing/_py/test_local.py, testing/code/test_excinfo.py, testing/test_assertrewrite.py, testing/test_pathlib.py, testing/test_pytester.py
The current method as the following problem, described by @sadra-barikbin in https://github.com/pytest-dev/pytest/pull/11236#issuecomment-1666851689:
The tests that request both `pytester` and `monkeypatch` and use `monkeypatch.chdir` without context, relying on `monkeypatch`'s teardown to restore cwd. This doesn't work because the following sequence of actions take place:
- `monkeypatch` is set up.
- `pytester` is set up. It saves the original cwd and changes it to a new one dedicated to the test function.
- Test function calls `monkeypatch.chdir()` without context. `monkeypatch` saves cwd, which is not the original one, before changing it.
- `pytester` is torn down. It restores the cwd to the original one.
- `monkeypatch` is torn down. It restores cwd to what it has saved.
The solution …
=> pytester: use `monkeypatch.chdir()` for dir changing

changelog/10617.feature.rst, src/_pytest/assertion/util.py, testing/test_assertion.py
This resolves #10617 and adds more powerful set assertion rewrites for comparisons other than equality ``==``. Previously, only ``==`` was supported for sets. Now, the additional following operations are supported: ``!=``, ``<=``, ``>=``, ``<``, and ``>``.
=> Add more set assertion rewrites e.g. ``>=``

.readthedocs.yml, doc/en/reference/customize.rst
Important to catch broken links and references.
=> Configure ReadTheDocs to fail on warnings

testing/logging/test_fixture.py
Logging has many global states, and we did foresee this by creating a ``cleanup_disabled_logging`` fixture, however one might still forget to use it and failures leak later -- sometimes not even in the same PR, because the order of the tests might change in the future, specially when running under xdist.
This problem surfaced during pytest-dev/pytest#11530, where tests unrelated to the change started to fail.
=> Ensure logging tests always cleanup after themselves

changelog/11065.doc.rst, doc/en/how-to/cache.rst
to be consistent with the API documentation.
Closes #11065
=> Use pytestconfig instead of request.config in cache example

AUTHORS, changelog/11520.improvement.rst, src/_pytest/_io/terminalwriter.py, src/_pytest/assertion/util.py, testing/conftest.py, testing/logging/test_fixture.py, testing/test_assertion.py
Previously, it would get printed all in red, which makes it hard to read and actually understand.
However, the diffs shown are standard and have a supported lexer in Pygments. As such, use this to color the output when pygments is available.
This is a step towards #11520 but does not address all the discussion points yet.
I am unsure about two things here:
- How we expose the lexers on the terminal writer. Having to pass a string and hoping it will do the right thing is not ideal, I believe it is slightly better than providing one when doing the call as, that way, only the terminalwriter has to handle whether pygments is available or not
- The testing might be a bit clunky and prone to breaking. If needed we could reduce the strictness of checks, let me know what you prefer
=> Color the full diff that pytest shows as a diff

.github/workflows/deploy.yml
Traditionally pytest publishes tags in the form `X.Y.Z`, however the deploy workflow (copied from somewhere else) published tags in the form `vX.Y.Z`.
This is the root cause of #11548, because it tried to publish the release notes for tag `X.Y.Z` (which did not exist).
Fix #11548
=> Fix tag name generated by deploy workflow

.github/workflows/deploy.yml
Traditionally pytest publishes tags in the form `X.Y.Z`, however the deploy workflow (copied from somewhere else) published tags in the form `vX.Y.Z`.
This is the root cause of #11548, because it tried to publish the release notes for tag `X.Y.Z` (which did not exist).
Fix #11548
=> [7.4.x] Fix tag name generated by deploy workflow (#11550)

changelog/11507.doc.rst, doc/en/how-to/output.rst
- Closes #11507.
- Added references to command line options `-q (--quiet )` ,`--capture` and `-s (--capture)` in the output documentation.
=> Mention -q and -s in the docs

changelog/11563.bugfix.rst, src/_pytest/python.py, testing/python/metafunc.py
=> Fix crash using empty string for parametrized value more than once

doc/en/requirements.txt
They seem to work fine, let's allow them.
=> doc: allow Sphinx 6.x and 7.x

doc/en/reference/reference.rst
Previously, the sidebar TOC had unlimited depth, making it useless and interfering with the content. This seems to have regressed in pytest 7.2.x going by the RTD version selector.
=> doc/reference: fix sidebar TOC depth

doc/en/how-to/assert.rst, doc/en/reference/reference.rst, src/_pytest/python_api.py
* Mention that subclassse are also matched.
* Improve some formatting and add some cross referencing.
* Add warning about using `pytest.raises(Exception)` (#4475)
Fix #11577
=> Improve pytest.raises docs

AUTHORS, changelog/11600.improvement.rst, doc/en/reference/reference.rst, src/_pytest/mark/structures.py
- [N/A] Include new tests or update existing tests when applicable.
Fixes comments https://github.com/pypa/setuptools/pull/3979#discussion_r1367963793 and https://github.com/pytest-dev/pytest/issues/10094#issuecomment-1774215699  
This makes it explicit that `None` is not a contractually supported value (even if it "works" because it's falsy). See https://github.com/pytest-dev/pytest/pull/11565#issuecomment-1801655848
* *Improved verbose diff output with …
=> Use `False`, instead of `None` as default for `_XfailMarkDecorator`'s `condition` param and update doc

AUTHORS, changelog/11387.feature.rst, doc/en/how-to/output.rst, doc/en/reference/reference.rst, src/_pytest/assertion/__init__.py, src/_pytest/assertion/rewrite.py, src/_pytest/assertion/truncate.py, src/_pytest/assertion/util.py, src/_pytest/config/__init__.py, src/pytest/__init__.py, testing/test_assertion.py, testing/test_assertrewrite.py, testing/test_config.py
`OuputVerbosity` is a new class that allows for retrieving a verbosity level for a specific output type. If nothing is specifically configured, the application wide verbose value is used.
The first use of this functionality is `verbosity_assertions` which can be used to make the assertion reports output at the most verbose level while still showing a single character for each test case when progress is being reported.
Addresses #11387
=> Add OuputVerbosity and use it in assertions

README.rst
if we were ever to change the `name:` field in `test.yml` this would suddenly break -- this references the workflow file directly (and is what github generates now for badges)
=> use name-independent github actions badge

src/_pytest/_io/pprint.py, src/_pytest/_io/saferepr.py, src/_pytest/assertion/util.py, testing/io/test_pprint.py, testing/io/test_saferepr.py
As part of #11571, where lots of changes are added to how diffs are pretty printed, we need to vendor in the pprint module from cpython.
This is a separate PR to do just that for easier reviews.
I was not sure if we should keep the original 'Author' from CPython in the comment at the top of the module or if we should put another type of heading.
I have also added some tests (adapted from #11571) to ensure this functionality was working for when we get there.
@bluetech I ended up splitting it in more commits than you requested as I believed it would make it easier to review. I am happy to squash some of them back if you wish 
And finally, I believe there are some cleanups I believe we can do later on on the pprint module (adding types, cleaning up data structures). Is that something you …
=> Vendor in and absorb the pprint module from upstream

changelog/11572.bugfix.rst, src/_pytest/faulthandler.py
Closes #11572 
remember stderr fileno in config.stash to be restored on faulthandler teardown
=> Fix for operation on closed file in faulthandler teardown

AUTHORS, changelog/11610.feature.rst, src/_pytest/logging.py, testing/logging/test_fixture.py
Closes #11610 
Please note that I also added a `versionadded:: 7.5` to the method’s docstring, though I’m not exactly sure how you guys handle the version number.
Also, regarding typing of the fixture args please note the recent change https://github.com/python/typeshed/pull/11018 and how with Python 3.12 the return type of the filter has changed. I am not sure how you’d like to handle that, please advise.
=> Add new filtering() context manager to LogCaptureFixture class

changelog/11638.trivial.rst, testing/conftest.py
Reset color-related environment variables in a fixture to prevent them from affecting test results.  Otherwise, some of the tests fail e.g. if NO_COLOR is set in the calling environment.
--------
=> Reset color-related envvars for testing

changelog/1531.improvement.rst, src/_pytest/_io/pprint.py, src/_pytest/assertion/util.py, testing/io/test_pprint.py, testing/test_assertion.py, testing/test_error_diffs.py
**Note**: This is an alternative implementation to #11537, and vendors pprint in
The normal default pretty printer is not great when objects are nested  it can get hard to read the diffs produced.
Instead, provide a pretty printer that behaves more like when json get  which allows for smaller, more meaningful differences, at the  expense of a slightly longer diff.
This also has the nice side effect of making diffs stable across python versions, which it was not previously, as, for example, dataclass support was added in python3.9
Fix #1531 
This has the disadvantage that diffs are now longer, even for small changes (like `[1, 2] == [1, 3]`). We could potentially still keep the previous implementation for the case where the diff is the same length AND has a single line. This would take …
=> Improve the full diff by having more consistent indentation in the PrettyPrinter

src/_pytest/_io/pprint.py
After vendoring and refactoring how we use the pprint module, there is quite a lot of code that can be simplified.
This is a first stab at it for various simple cleanups.
I was not sure if that's worth adding a changelog entry for it, please let me know what category it should be if you think it is
=> Various cleanups of the vendored pprint module

src/_pytest/pytester.py, testing/test_parseopt.py
When running `tox -e py-lsof` I get a deluge of this warning:
```
src/pytest/.tox/py-lsof-numpy-pexpect/lib/python3.11/site-packages/_pytest/pytester.py:130: EncodingWarning: UTF-8 Mode affects locale.getpreferredencoding(). Consider locale.getencoding() instead.
```
Use `locale.getencoding` instead.
=> pytester: avoid EncodingWarning from `locale.getpreferredencoding`

testing/test_terminal.py
The default for `_prepareconfig` is to use `sys.argv`, which in this case are the flags passed to (top-level) `pytest`. This is not the intention, the tests themselves should not be affected by it.
=> testing: fix isolation issue in `tr` fixture

testing/test_config.py
pytest-xdist was released at 2019-02-15, seems enough time.
=> testing: remove a no longer necessary skip

doc/en/how-to/logging.rst
Close #11573 
Hello,
The initialisation of logging-plugin is done with the option "trylast=True".
https://github.com/pytest-dev/pytest/blob/81c06b3955b542280e801c2627266425f00ccbc9/src/_pytest/logging.py#L624-L627
The problem is solved when I add also "trylast=True" to make it run after the initialisation.
=> Fix: fix the "Customizing Colors" documentation section

changelog/11676.breaking.rst, doc/en/reference/reference.rst, src/_pytest/fixtures.py, src/_pytest/nodes.py, src/_pytest/python.py, testing/deprecated_test.py, testing/example_scripts/issue88_initial_file_multinodes/conftest.py, testing/test_collection.py, testing/test_nodes.py
=> nodes,python: mark abstract node classes as ABCs

doc/en/changelog.rst, doc/en/conf.py, doc/en/example/simple.rst, doc/en/funcarg_compare.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, src/_pytest/hookspec.py, src/_pytest/nodes.py, src/_pytest/python_api.py
See:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky
This ensures we have no more broken references.
=> docs: enable Sphinx nitpicky mode

AUTHORS, doc/en/reference/reference.rst, src/_pytest/outcomes.py
=> Improves clarity in Sphinx documentation for function signature.

src/_pytest/_io/pprint.py
The vendored version of pprint doesn't use all those features, we can simplify and reduce the amount of code we have to handle.
Since the module has already quite diverged from upstream, it doesn't really make sense to keep those in
=> Remove more unused pprint features

changelog/11520.improvement.rst, src/_pytest/_io/terminalwriter.py, src/_pytest/assertion/util.py, testing/io/test_terminalwriter.py, testing/test_assertion.py, testing/test_terminal.py
This is part of https://github.com/pytest-dev/pytest/issues/11520
This adds colors to the normal explanations outputted by pytest whenever it shows python code in order to make it more readable amongst the sea of red text. It only affects the output when Pygments in present.
<details>
<summary>Example</summary>
</details>
- Not sure how and how much to test this. Making this change barely broke any tests. What would you recommend/want?
- The `{reset}` color that we add at the start should technically be added on every line to be extra safe, but does currently work. Do we want to be stricter about checking those?
- The output that we have is actually not exactly valid python, as `repr` can generate an output that is not python. As such, this breaks the lexer in subtle ways, which might …
=> Add syntactic highlights to the error explanations

AUTHORS, changelog/11712.bugfix.rst, doc/en/reference/reference.rst, src/_pytest/_io/terminalwriter.py, testing/io/test_terminalwriter.py
Fix handling NO_COLOR and FORCE_COLOR environment variables to correctly be ignored when they are set to an empty value, as defined in the specification:
> Command-line software which adds ANSI color to its output by default
> should check for a NO_COLOR environment variable that, when present
> *and not an empty string* (regardless of its value), prevents
> the addition of ANSI color.
(emphasis mine, https://no-color.org/)
The same is true of FORCE_COLOR, https://force-color.org/.
----
* *Terminal summary statistics now use multiple …
=> Fix handling empty values of NO_COLOR and FORCE_COLOR

src/_pytest/deprecated.py, testing/deprecated_test.py
The deprecation has only been added in 8.0, so can't be removed in 8. That will have to wait for 9.
=> Change "Marks applied to fixtures" removal from 8 to 9

changelog/11710.bugfix.rst, src/_pytest/nodes.py, testing/test_collection.py
=> nodes: fix tracebacks from collection errors are not getting pruned

AUTHORS, changelog/11140.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
(cherry picked from commit 084d756ae6a03bba7a257ebae3c83095b228988f)
[ran: adapted to 7.4.x, fixed changelog issue number]
=> [7.4.x] Ensure the docstring is a string

changelog/11758.bugfix.rst, src/_pytest/_io/terminalwriter.py, testing/io/test_terminalwriter.py
For quick checking I don't know how we can reach here with an empty source, so test just checks the function directly.
Fix #11758.
=> terminalwriter: fix crash trying to highlight empty source

AUTHORS, changelog/11706.bugfix.rst, src/_pytest/main.py, src/_pytest/runner.py, testing/test_runner.py, testing/test_session.py
=> Fix teardown error reporting when `--maxfail=1`

.github/workflows/deploy.yml, .pre-commit-config.yaml, scripts/.gitignore, scripts/generate-gh-release-notes.py, scripts/prepare-release-pr.py, scripts/release.py, scripts/towncrier-draft-to-file.py, scripts/update-plugin-list.py, tox.ini
This changes the existing script to just generate the release notes and delegate the actual publishing to the `softprops/action-gh-release@v1` action.
This allows us to delete the custom code, which failed recently in https://github.com/pytest-dev/pytest/actions/runs/7370258570/job/20056477756.
In addition, the 2nd commit enables type checking in `scripts/` for additional safety.
I will remove the secrets that are no longer needed from the repository after this is merged.
=> Improve GitHub release workflow

src/_pytest/recwarn.py
While trying to update some tests for compatibility with pytest 8.0.0rc1, I found that lists of warning types didn't work as the docstring suggested. Indeed, both the internal logic and type annotations are actually more strict, so I think just fixing the docstring is enough ?
=> Fix a mistake in pytest.warns' docstring (expect_warning accepts tuples, not any sequence)

src/_pytest/unittest.py
The indirection makes things harder to follow in this case IMO.
This change makes some thing I'm planning easier, but I think it's good on its own so submitting separately.
=> unittest: inline `_make_xunit_fixture`

src/_pytest/fixtures.py, src/_pytest/python.py, src/_pytest/unittest.py
(Based on #11776, ignore first commit)
See the commit messages, and the discussion in #11662.
=> Add an internal "register fixture" API and use it replace object patching for fixture injection

changelog/11785.trivial.rst, src/_pytest/fixtures.py, src/_pytest/nodes.py, testing/plugins_integration/requirements.txt, testing/python/fixtures.py, testing/test_nodes.py, tox.ini
Refs #11662.
Each fixture definition has a "visibility", the `FixtureDef.baseid` attribute. This is nodeid-like string. When a certain `node` requests a certain fixture name, we match node's nodeid against the fixture definitions with this name.
The matching currently happens on the *textual* representation of the nodeid - we split `node.nodeid` to its "parent nodeids" and then check if the fixture's `baseid` is in there.
While this has worked so far, we really should try to avoid textual manipulation of nodeids as much as possible. It has also caused problem in an odd case of a `Package` in the root directory: the `Package` gets nodeid `.`, while a `Module` in it gets nodeid `test_module.py`. And textually, `.` is not a parent of `test_module.py`.
Avoid this entirely by just checking the …
=> fixtures: match fixtures based on actual node hierarchy, not textual nodeids

changelog/11790.doc.rst, doc/en/how-to/tmp_path.rst
Closes #11790. Slight change to `tmp_path` documentation to more clearly illustrate it's behavior
Feel free to suggest changes if the updated documentation is still misleading :)
=> Doc tmp_path

doc/en/deprecations.rst, src/_pytest/python.py
Since we're removing nose support, let's also drop support for this attribute.
From doing a code search on github, this seems completely unused outside of nose, except for some projects which used to use it, but no longer do.
=> python: remove support for nose's `compat_co_firstlineno`

changelog/11801.improvement.rst, src/_pytest/fixtures.py, src/_pytest/nodes.py, src/_pytest/python.py
This is a useful addition to the existing `listchain`. While `listchain` returns top-to-bottom, `iterchain` is bottom-to-top and doesn't require an internal full iteration + `reverse`.
Follow up on https://github.com/pytest-dev/pytest/pull/11785#discussion_r1444663550
=> nodes: add `Node.iterchain()` function

doc/en/how-to/fixtures.rst
The behavior of package scope is surprising to some  (as seen by related questions on SO), this note should clarify it a bit.
See for example [this question](https://stackoverflow.com/questions/77749958/why-isnt-my-fixture-created-once-per-package-with-the-package-scope) which gave me the idea (not the first of this kind).
I guess the change is trivial enough to not require an entry in the release notes.
=> Add note about package scope

src/_pytest/doctest.py
(Diff better viewed ignoring whitespace)
Since e1c66ab0ad8eda13e5552dfc939e07d7290ecd39, conftest loading is handled at the directory level before sub-nodes are collected, so there is no need for the doctest plugin to handle it specially.
This was probably the case even before e1c66ab0ad8eda13e5552dfc939e07d7290ecd39, but I haven't verified this.
=> doctest: remove special conftest handling

changelog/9765.bugfix.rst, src/_pytest/config/__init__.py, testing/acceptance_test.py, testing/test_pluginmanager.py
Fixes https://github.com/pytest-dev/pytest/issues/9765
What happens is that `str(conftestpath)` is not necessarily equal to `mod.__file__`, which is the key that is really used in `self._name2plugin`. For instance I've noticed that on windows, the `module.__file__` string for some modules is sometimes small cased (`c:\\users...`), while `str(conftestpath)` is not (`C:\\Users...`). For my particular reproducer of https://github.com/pytest-dev/pytest/issues/9765, it causes some plugins loaded from conftest to be double loaded, since the preliminary lookup fails because the key is wrong. And double-loading leads to a crash.
This might not be a good fix if there are other direct calls to `self.register` in other areas of the code base that would risk to format the keys differently when it's …
=> FIX key formating divergence when inspecting plugin dictionary.

src/_pytest/config/__init__.py
Related to #9765, add a better error message than `assert mod not in mods`. This would have been super useful to figure out from the error message the difference from `conftestpath` and `mod.__file__`. Hopefully the #11708 will be merged and this error is less likely to occur, but at least if a variation of the issue occurs again there will be a better error message.
Here is the error on my reproducer https://github.com/lesteve/pytest-issue-9765-reproducer:
```
AssertionError: str(conftestpath)='C:\\msys64\\home\\lesteve\\dev\\pytest-issue-9765-reproducer\\project\\conftest.py'
has already been loaded as the module mod=<module 'project.conftest' from 'c:\\msys64\\home\\lesteve\\dev\\pytest-issue
-9765-reproducer\\project\\conftest.py'>
```
For now I keep an `AssertionError` but let me …
=> Improve assert mod not in mods error message

src/_pytest/main.py, src/_pytest/python.py
Follow up on https://github.com/pytest-dev/pytest/pull/11646#discussion_r1412155970
This removes one thing that directory collectors need to worry about.
This adds one hook dispatch per `__pycache__` file, but I think it's worth it for consistency.
=> main,python: move `__pycache__` ignore to `pytest_ignore_collect`

changelog/11801.improvement.rst, src/_pytest/fixtures.py, src/_pytest/nodes.py, src/_pytest/python.py
After the fact I remembered that there is `node.iter_markers()`, so let's be consistent with that rather than with `listchain()`.
=> nodes: rename `iterparents()` -> `iter_parents()`

src/_pytest/config/__init__.py, src/_pytest/debugging.py, src/_pytest/nodes.py, testing/test_config.py
In recent python versions all of the info is on the exception object itself so no reason to deal with the annoying tuple.
=> config: stop using exception triplets in `ConftestImportError`

doc/en/index.rst
The one in March is fully booked apparently! Still leaving it in for now in case there are any cancellations or anything - but we decided to go for a second date in June, and also already announce the one for 2025.
Finally, I also added a link to the sprint discussion and date poll, in the hope of getting some more attention to it.
=> doc: Update training dates and add pytest sprint

doc/en/index.rst
Apologies for the PR churn - only now Python Academy told me they will remove the sold out training from their website, so it makes sense to remove it on pytest.org too :sweat_smile:
=> doc: Remove sold out training

src/_pytest/hookspec.py
These are commits extracted from #9496
=> hookspec: minor doc tweaks

.pre-commit-config.yaml, changelog/11825.improvement.rst, src/_pytest/config/__init__.py, src/_pytest/fixtures.py, src/_pytest/hookspec.py
closes https://github.com/pytest-dev/pytest/issues/11816
Alternative fix to https://github.com/pytest-dev/pytest/pull/11821.
The plugin name is equal to the path for conftest plugins (suggested in https://github.com/pytest-dev/pytest/issues/11816#issuecomment-1893364761). Use that instead of `plugin.__file__`.
Test with the h5py CI that was broken by the issue: https://github.com/h5py/h5py/pull/2370
Another way of testing this MR:
```
python -m pip install "ewokscore==0.7.1" matplotlib ipykernel^
git+https://github.com/woutdenolf/pytest.git@fix_missing_fixture_issue --no-cache
python -m pytest -v --pyargs ewokscore.tests
```
=> avoid using __file__ in pytest_plugin_registered as can be wrong on Windows

.pre-commit-config.yaml, changelog/11825.improvement.rst, src/_pytest/config/__init__.py, src/_pytest/fixtures.py, src/_pytest/hookspec.py
(Manual) Backport PR #11825 to 8.0.x.
=> [8.0.x] avoid using __file__ in pytest_plugin_registered as can be wrong on Windows

.github/workflows/deploy.yml
Follow up to https://github.com/pytest-dev/pytest/pull/11754, noticed that the latest GitHub release does not contain the attached files.
[Output log](https://github.com/pytest-dev/pytest/actions/runs/7562055008/job/20591844192) from the action:
```
🤔 Pattern 'dist/*' does not match any files.
```
=> Properly attach packages to the GH release notes

AUTHORS, changelog/11790.doc.rst, doc/en/how-to/tmp_path.rst, src/_pytest/legacypath.py, src/_pytest/tmpdir.py
=> [DOCS] Clarify temporary directory location and retention

src/_pytest/config/__init__.py, src/_pytest/config/findpaths.py, src/_pytest/helpconfig.py, src/_pytest/python.py, testing/test_config.py, testing/test_conftest.py, testing/test_findpaths.py
We should aim to remove all `cwd()` calls except one (for the invocation dir), otherwise things will go bad if the working directory changes. Use the invocation dir instead.
=> Prefer using the invocation dir over CWD

changelog/11842.bugfix.rst, src/_pytest/junitxml.py, testing/test_junitxml.py
Escape invalid characters in the skip message in junitxml.
Small repro:
```
import pytest
class TestA:
@pytest.mark.skip("\33[31;1madsfsd\33[0m")
def test_a(self):
assert 2 == 2
```
Run the above via `pytest repro.py --junit-xml=repro.xml`
The result is (formatted for easier reading):
```
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite name="pytest" errors="0" failures="0" skipped="1" tests="1" time="0.045"
timestamp="2024-01-18T09:38:22.499385" hostname="csl-mbp">
<testcase classname="repro.TestA" name="test_a" time="0.000">
<skipped type="pytest.skip" message="[31;1mrandom colored skip reason[0m">/Users/csl/zzzzzzzz/random-testing/repro.py:4:
#x1B[31;1mrandom colored skip reason#x1B[0m</skipped>
</testcase>
</testsuite>
</testsuites>
```
There's an invalid XML character …
=> Escape skip reason in junitxml

testing/test_debugging.py
While debugging https://github.com/pytest-dev/pytest/pull/11825#issuecomment-1894094641 in hypothesis, I was sidetracked by some `xfail`s that unexpectedly passed. Based on https://github.com/pytest-dev/pytest/issues/10042#issuecomment-1237132867 and https://github.com/pytest-dev/pytest/issues/10042#issuecomment-1274655510 it looks like these particular ones should not fail the test suite if they unexpectedly pass.
This trivial change has no linked issue, and does not require a changelog entry or AUTHORS addition.
=> Mark some xfails from #10042 as non-strict

src/_pytest/hookspec.py
Have each hook explain how implementing it in conftests works. This is part of the functional specification of a hook.
Also a few other related small related doc commits.
=> hookspec: document conftest behavior for all hooks

.pre-commit-config.yaml, setup.cfg, src/_pytest/config/__init__.py
The function was added in pluggy 1.4.0.
=> config: use `pluginmanager.unblock` instead of accessing pluggy's internals

changelog/11861.bugfix.rst, changelog/11861.trivial.rst, src/_pytest/logging.py
I'm using pytest with python 3.9, and my `log-date-format` is enabled for microseconds. However, my testsuite occasionally fails with the message below:
```
ValueError: microsecond must be in 0..999999
```
I'm pretty sure the issue occurred because we're rounding up microsecond here, which make it exceeds 999999.
https://github.com/pytest-dev/pytest/blob/ac2cd72e5fb00257ef1f6e17b2c16336362c6234/src/_pytest/logging.py#L72-L75
As we can see `msecs` can take more than 4 digits after decimal points, hence it can be rounded up to `1_000_000` after multiplying with `1_000`. (in python 3.9)
```python
>>> import logging
>>> r = logging.makeLogRecord({'msg': 'Message'})
>>> r.msecs
696.0451602935791
```
This is "fixed" in python 3.10 and 3.11 https://github.com/python/cpython/issues/89047
They …
=> fix: avoid rounding microsecond to `1_000_000`

AUTHORS, changelog/11875.bugfix.rst, src/_pytest/tmpdir.py
- Previously, `getpass.getuser()` would leak an ImportError if the USERNAME environment variable was not set on Windows because the `pwd` module cannot be imported.
- Starting in Python 3.13.0a3, it only raises `OSError`.
- Closes #11874
=> Catch `OSError` from `getpass.getuser()`

testing/plugins_integration/requirements.txt
The current version (0.23.4) explicitly does not support pytest 8 yet, so we fallback to the previous release in the hope that at least our integration tests pass.
=> Pin back pytest-asyncio to 8.0.0 compatible release

doc/en/changelog.rst
=> Add a changelog entry about FixtureManager.getfixtureclosure losing a default argument

AUTHORS, changelog/11879.bugfix.rst, src/_pytest/_code/code.py, testing/acceptance_test.py, testing/python/raises.py
Closes #11872
Thanks @bluetech for your guidance !
=> BUG: fix an edge case where ExceptionInfo._stringify_exception could crash pytest.raises

.pre-commit-config.yaml, doc/en/deprecations.rst, doc/en/funcarg_compare.rst, doc/en/historical-notes.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/skipping.rst, doc/en/reference/reference.rst
(cherry picked from commit 4546d5445aaefe6a03957db028c263521dfb5c4b)
Follow up to #11899.
=> [8.0.x] Upgrade blacken-doc to black's 2024 style (#11899)

pyproject.toml
The file is generated. This makes `ruff src/` run cleanly (when not running through pre-commit).
=> Ignore isort on _version.py

.pre-commit-config.yaml, pyproject.toml, setup.cfg
This is a follow-up to https://github.com/pytest-dev/pytest/pull/11928. Diff between what is generated on main and what is generated on last commit of this branch using ``python -m build`` is as follow:
```diff
diff --git a/pytest-8.1.0.dev153+gaaa9ca732/.pre-commit-config.yaml b/pytest-8.1.0.dev153+gaaa9ca732/.pre-commit-config.yaml
index 032fe8c4d..ca3b41d58 100644
--- a/pytest-8.1.0.dev153+gaaa9ca732/.pre-commit-config.yaml
+++ b/pytest-8.1.0.dev153+gaaa9ca732/.pre-commit-config.yaml
@@ -21,11 +21,6 @@ repos:
hooks:
-   id: blacken-docs
additional_dependencies: [black==24.1.1]
--   repo: https://github.com/asottile/setup-cfg-fmt
-    rev: v2.5.0
-    hooks:
-    -   id: setup-cfg-fmt
-        args: ["--max-py-version=3.12", "--include-version-classifiers"]
-   repo: …
```
=> Migration from ``setup.cfg`` to ``pyproject.toml``

changelog/11929.bugfix.rst, src/_pytest/doctest.py, testing/test_doctest.py
Fix #11929. There is also a prerequisite commit, please see the commit message.
=> doctest: fix autouse fixtures possibly not getting picked up

changelog/11929.bugfix.rst, src/_pytest/doctest.py, testing/test_doctest.py
doctest: fix autouse fixtures possibly not getting picked up (cherry picked from commit 6c0b6c2f92b68757988cdb11499cac750ba71862)
Note - the backport is not clean due to 06dbd3c21ccdf1ac76e8fa264048133cb4660842, but as argued in that commit we can just ignore the `conftest.py` branch.
=> [8.0.x] Merge pull request #11941 from bluetech/doctest-parsefactories

bench/bench.py, doc/en/example/assertion/failure_demo.py, pyproject.toml, src/_pytest/_py/path.py, src/_pytest/assertion/rewrite.py, testing/python/fixtures.py, testing/test_assertion.py, testing/test_assertrewrite.py, testing/test_collection.py, testing/test_config.py, testing/test_skipping.py, testing/test_warnings.py
Fix the following warning:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
```
Enable https://docs.astral.sh/ruff/rules/#flake8-pie-pie
Enable https://docs.astral.sh/ruff/rules/blanket-noqa/
=> Fix ruff deprecation warning + enable few more rules

src/_pytest/fixtures.py, testing/python/fixtures.py
While obvious in hindsight, this error message confused me. I thought my fixture function was used in a test function twice, since the wording is ambiguous.
Also, the error does not tell me *which* function is the culprit.
Finally, this adds a test, which wasn't done in
cfd16d0dac1c935952b892bfbc225978c9b25de3 where this was originally implemented.
=> Improve error message when using @pytest.fixture twice

changelog/11937.bugfix.rst, src/_pytest/main.py, testing/acceptance_test.py, testing/test_collection.py
Since we're working with a stack (last in first out), we need to append to it in reverse to preserve the order when popped.
Fix #11937.
=> main: fix reversed collection order in Session

changelog/11311.improvement.rst, src/_pytest/config/__init__.py, src/_pytest/config/argparsing.py, testing/test_config.py
Previously this would trigger an `AssertionError`.
While it could be considered a bug-fix, but given it now can be relied upon, it is probably better to consider it an improvement.
Fix #11311
=> Consider paths and pathlists relative to cwd in case of an absent ini-file

changelog/11962.improvement.rst, doc/en/reference/customize.rst, src/_pytest/config/findpaths.py, testing/test_config.py
Today `pyproject.toml` is the standard for declaring a Python project root, so seems reasonable to consider it for the ini configuration (and specially `rootdir`) in case we do not find other suitable candidates.
Related to #11311
=> Consider pyproject.toml files for config if no other config files were found

changelog/11907.bugfix.rst, src/_pytest/recwarn.py, testing/test_recwarn.py
=> recwarn: let base exceptions propagate through `pytest.warns` again

changelog/11907.bugfix.rst, src/_pytest/recwarn.py, testing/test_recwarn.py
(cherry picked from commit 718cd400152d64e6e6d47dc96f61bf1e6c06011a)
=> [8.0.x] recwarn: let base exceptions propagate through `pytest.warns` again

scripts/update-plugin-list.py
=> scripts/update-plugin-list: include packages starting with "pytest_" (underscore)

AUTHORS, changelog/10865.improvement.rst, src/_pytest/recwarn.py, testing/test_recwarn.py
[`warnigns.warn()` expects its first argument to be a `str` or a `Warning`](https://docs.python.org/3/library/warnings.html#available-functions) (see also [`WarningMessage` in typeshed](https://github.com/python/typeshed/blob/9d90eeb29646f88937bcee38e4dd954a6a769ed2/stdlib/warnings.pyi#L43-L44)) and using a different type can cause difficult to diagnose errors (as was reported in #10865):
```python
>>> import warnings
>>> with warnings.catch_warnings():
...     warnings.filterwarnings("ignore", "test")
...     warnings.warn("Warning!")
...     warnings.warn(RuntimeWarning())
...     warnings.warn(0)
... 
<stdin>:3: UserWarning: Warning!
<stdin>:4: RuntimeWarning: 
File "<stdin>", line 5, in <module>
TypeError: expected string or bytes-like object
``` …
=> Allow using `warnings.warn()` with a `Warning`

changelog/11906.bugfix.rst, src/_pytest/recwarn.py, testing/test_recwarn.py
Fix #11906.
This is a rebase of #11917 so can be included in 8.0.1. I can't update the original PR so created a new one.
=> recwarn: fix pytest.warns handling of Warnings with multiple arguments

changelog/11953.bugfix.rst, src/_pytest/_code/source.py
Fix #11953.
I haven't been able to reproduce (needs a multiline statement which starts with a blank line?), though I didn't try very hard. However the fix is pretty innocent so I think it's OK to merge without a regression test.
=> code: fix `IndexError` crash in `getstatementrange_ast`

src/_pytest/compat.py
As the comment above it states, we need to keep the comparison simple so mypy can understand it, otherwise it will fail to properly handle this on Windows and will flag ``os.getuid()`` missing.
=> Revert sys.platform verification to simple comparison

doc/en/requirements.txt
Using Sphinx 6.x and 7.x the search bar disappears. Restrict to Sphinx 5.x for now until we find a solution.
Reverts #11568
Fixes #11988
=> Disallow Sphinx 6 and 7

doc/en/_templates/slim_searchbox.html, doc/en/requirements.txt
Thanks to https://github.com/pytest-dev/pytest/issues/11988#issuecomment-1950318888, the problem was our custom template.
The solution was to copy the template from Sphinx 7 and remove the header.
=> Allow Sphinx 7.x

src/_pytest/config/__init__.py
Follow up to #12006, let's put some comments clarifying `is_in_confcutdir` semantics, as this is not the first time someone misunderstands it.
Also removed an obsolete comment in `_loadconftestmodules`: we already set the `confcutdir` based on `rootdir`/`initfile` if not explicitly given.
=> Clarify PytestPluginManager._is_in_confcutdir

changelog/12011.bugfix.rst, testing/test_doctest.py
Refs #12011 (only fails on 8.0.1, not main).
=> testing: add a regression test for `setup_module` + `--doctest-modules`

AUTHORS, changelog/11978.improvement.rst, doc/en/how-to/logging.rst, src/_pytest/logging.py, testing/logging/test_reporting.py
Previously, the mode was hard-coded to be "w" which truncates the file before logging. Relevant documentation has been updated and tests have been added to validate the new functionality.
Closes #11978
=> Add --log-file-mode option to the logging plugin, enabling appending to log-files

src/_pytest/fixtures.py, src/_pytest/python.py, testing/python/fixtures.py
First 2 commits are simple code cleanups, the 3rd commit is described below. I saw it when looking into #12008 but it's unrelated to it.
---
Dicts these days preserve order, so the sort is no longer needed to achieve determinism.
As shown by the `test_dynamic_parametrized_ordering` test, this can change the ordering of items, but only in equivalent ways (same number of setups/teardowns per scope), it will just respect the user's given ordering better (hence `vxlan` items now ordered before `vlan` items compared to the previous ordering).
=> fixtures: remove a no longer needed sort

TIDELIFT.rst
As discussed in the core development channels, `@asottile` asked to no longer be a Tidelift participant, at least for the time being.
=> Remove Anthony from Tidelift participants

changelog/12014.bugfix.rst, src/_pytest/mark/structures.py, testing/deprecated_test.py
This is really proposal-by-PR (because the PR is pretty trivial). In MNE-Python at least it takes this warning on 8.0.1:
```
================================================================================= warnings summary =================================================================================
../pytest/src/_pytest/mark/structures.py:357
/home/larsoner/python/pytest/src/_pytest/mark/structures.py:357: PytestRemovedIn9Warning: Marks applied to fixtures have no effect
See docs: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function
store_mark(func, self.mark)
```
and puts it on the correct line needed to fix the warning
```
================================================================================= warnings summary …
```
=> ENH: Improve warning stacklevel

src/_pytest/doctest.py, src/_pytest/main.py, src/_pytest/nodes.py, src/_pytest/python.py, src/_pytest/unittest.py, testing/test_collection.py
Up to now the return values of `from_parent` were untyped, this is an attempt to make it work with `typing.Self`.
=> Add typing to `from_parent` return values

changelog/11895.bugfix.rst, src/_pytest/compat.py, src/_pytest/main.py, testing/test_collection.py
Passing a short path in the command line was causing the matchparts check to fail, because `Path(short_path) != Path(long_path)`.
Using `os.path.samefile` as fallback ensures the comparison works on Windows when comparing short/long paths.
Fix #11895
=> Fix collection of short paths on Windows

src/_pytest/fixtures.py
In `CallSpec2.setmulti` the `params` and `_arg2scope` dicts are always set together ([link](https://github.com/pytest-dev/pytest/blob/010ce2ab0f6d2e90f295d4e3f9e725d31dd5721d/src/_pytest/python.py#L1078-L1083)).
Further, the `get_parametrized_fixture_keys` accesses `_arg2scope` for all argnames without a check ([link](https://github.com/pytest-dev/pytest/blob/010ce2ab0f6d2e90f295d4e3f9e725d31dd5721d/src/_pytest/fixtures.py#L175-L177)), which I think rules out that the code protects against plugin shenanigans.
After removing the suppress, adjust the comment and code to make more sense.
=> fixtures: remove an unneeded suppress

AUTHORS, changelog/11850.improvement.rst, src/_pytest/runner.py, testing/test_runner.py
Fix #11850
This PR is same as #11934 by @robotherapist with the comments fixed, so we can include it pytest 8.1 (I can't update the original PR).
Reviewed by me.
Closes #11934
=> runner: add support for `sys.last_exc` for post-mortem debugging on Python>=3.12

src/_pytest/fixtures.py
According to my understanding, this code, which handles obtaining the relevant fixturedefs when a dynamic `getfixturevalue` is used, has an optimization where it only grabs fixturedefs that are visible to the *parent* of the item, instead of the item itself, under the assumption that a fixturedef can't be visible to a single item, only to a collector.
Remove this optimization for the following reasons:
- It doesn't save much (one loop iteration in `matchfactories`)
- It slightly complicates the complex fixtures code
- If some plugin wants to make a fixture visible only to a single item, why not let it?
- In the static case (`getfixtureclosure`), this optimization is not done (despite the confusing name `parentnode`, it is *not* the parent node). This is inconsistent.
=> fixtures: remove unneeded optimization from `_getnextfixturedef`

changelog/11904.bugfix.rst, src/_pytest/main.py, testing/test_collection.py, testing/test_main.py
This should fix #11904. It does *not* fix all permission error situations that popped up with pytest 8.0.0 but most complaints were about `--pyargs` and others are mostly misconfigurations as far I could tell, so let's start with this to unblock pytest 8.1.0 and see about the others as the come.
The PR has some preparatory commits, here is the description of the main change (last commit):
In pytest<8, the collection tree for `pyargs` arguments in an invocation like this:
pytest --collect-only --pyargs pyflakes.test.test_undefined_names
looked like this:
```xml
<Package test>
<Module test_undefined_names.py>
<UnitTestCase Test>
<TestCaseFunction test_annotationUndefined>
... snipped ...
```
The pytest 8 collection improvements changed it to this:
```xml
<Dir pytest>
<Dir .tox>
<Dir venv> …
```
=> Fix collection failures due to permission errors when using `--pyargs`

testing/test_debugging.py
Noticed this one test failing due to me having locally set `PYTHONBREAKPOINT`, and while fixing I noticed another test that resolved same issue with a `skipif` - but I don't see any reason to skip instead of monkeypatching. This should have zero effect on running tests in CI, mostly just a small QoL for some devs running tests locally.
=> [minor/QoL] monkeypatch.delenv PYTHONBREAKPOINT in two tests that previously failed/skipped

changelog/12047.improvement.rst, src/_pytest/fixtures.py, testing/python/fixtures.py
Fix #12047.
Previously, if more than one fixture finalizer raised, only the first was reported, and the other errors were lost.
Use an exception group to report them all. This is similar to the change we made in node teardowns (in `SetupState`).
=> fixtures: use exception group when multiple finalizers raise in fixture teardown

src/_pytest/fixtures.py
pytest allows a fixture to request its own name (directly or indirectly), in which case the fixture with the same name but one level up is used.
To know which fixture should be used next, pytest keeps a mutable item-global dict `_arg2index` which maintains this state. This is not great:
- Mutable state like this is hard to understand and reason about.
- It is conceptually buggy; the indexing is global (e.g. if requesting   `fix1` and `fix2`, the indexing is shared between them), but actually   different branches of the subrequest tree should not affect each   other.
This is not an issue in practice because pytest keeps a cache of the  fixturedefs it resolved anyway (`_fixture_defs`), but if the cache is removed it becomes evident.
Instead of the `_arg2index` state, count how many …
=> fixtures: avoid mutable arg2index state in favor of looking up the request chain

changelog/11475.bugfix.rst, src/_pytest/pathlib.py, testing/test_pathlib.py
Regression brought up by #11475.
=> Do not import duplicated modules with --importmode=importlib

CONTRIBUTING.rst, pyproject.toml, tox.ini
Minor, but seems `dev` is more standard for the development extras than `testing`, being the default for tools like `poetry`.
=> Rename 'testing' extra to 'dev'

src/_pytest/compat.py, src/_pytest/fixtures.py, src/_pytest/python.py, src/_pytest/unittest.py, testing/test_unittest.py
Previously, the `obj` of a `TestCaseFunction` (the unittest plugin item type) was the unbound method. This is unlike regular `Class` where the `obj` is a bound method to a fresh instance.
This difference necessitated several special cases in in places outside of the unittest plugin, such as `FixtureDef` and `FixtureRequest`, and made things a bit harder to understand.
Instead, match how the python plugin does it, including collecting fixtures from a fresh instance.
The downside is that now this instance for fixture-collection is kept around in memory, but it's the same as `Class` so nothing new. Users should only initialize stuff in `setUp`/`setUpClass` and similar methods, and not in `__init__` which is generally off-limits in `TestCase` subclasses.
I am not sure why there was a …
=> unittest: make `obj` work more like `Function`/`Class`

changelog/12069.trivial.rst, doc/en/conf.py, doc/en/deprecations.rst, src/_pytest/compat.py, src/_pytest/config/__init__.py, src/_pytest/config/compat.py, src/_pytest/deprecated.py, src/_pytest/hookspec.py, src/_pytest/legacypath.py, src/_pytest/main.py, src/_pytest/nodes.py, src/_pytest/python.py, testing/deprecated_test.py, testing/test_legacypath.py, testing/test_nodes.py
This reverts commits 6c89f9261c6f5bde93bd116ef56b7ac96fc0ef21 and a98f02d4238793300f1be01f75bf0fff5609a241 (as usual, thanks @bluetech for care with the git commit history), bringing back the legacy path arguments to hooks and `Node` constructors.
We will need to manually fix the changelog for `8.1.1` at the time of release.
Fix #12069
=> Revert legacy path removals

src/_pytest/fixtures.py, testing/python/fixtures.py
These are a few more cleanup commits to the fixtures code, in the continuing quest to bring out its inner beauty :)
=> fixtures: a few more cleanups

changelog/12065.bugfix.rst, src/_pytest/fixtures.py, src/_pytest/python.py, src/_pytest/unittest.py, testing/python/fixtures.py, testing/python/integration.py
and also fixes a regression in pytest 8.0.0 where `setup_method` crashes if the class has static or class method tests.
It is allowed to have a test class with static/class methods which request non-static/class method fixtures (including `setup_method` xunit-fixture). I take it as a given that we need to support this somewhat odd scenario (stdlib unittest also supports it).
This raises a question -- when a staticmethod test requests a bound fixture, what is that fixture's `self`?
stdlib unittest says - a fresh instance for the test.
Previously, pytest said - some instance that is shared by all static/class methods. This is definitely broken since it breaks test isolation.
Change pytest to behave like stdlib unittest here.
In practice, this means stopping to rely on `self.obj.__self__` to …
=>  python: fix instance handling in static and class method tests

doc/en/explanation/flaky.rst
The plugin is abandoned and no longer working with new pytest versions.
I also reordered a bit to put pytest-rerunfailures first since it seems most maintained and is under pytest-dev.
=> doc/flaky: remove `box/flaky` plugin suggestion

doc/en/conf.py, doc/en/how-to/writing_hook_functions.rst, doc/en/index.rst
Added a missing word and fixed two codespell warnings in documentation.
=> doc: fix typos

testing/python/fixtures.py
Split out from #11833, as they are probably useful tests independent of that PR. I feel like I've seen tests somewhere in the test suite that kind of tests for the same thing(s), but I can't find them now, so it's probably good to have explicit tests for this either way.
=> Add tests to ensure setup&finalization for scoped fixtures only run once.

src/_pytest/_code/code.py
`ExceptionInfo.group_contains()` [was added in 8.0.0](https://docs.pytest.org/en/8.0.x/changelog.html#additional-support-for-exception-groups-and-notes) (via #11424) and currently lacks the `versionadded` data in pytest's docs:
- https://docs.pytest.org/en/8.0.x/reference/reference.html#pytest.ExceptionInfo.group_contains
- https://docs.pytest.org/en/latest/reference/reference.html#pytest.ExceptionInfo.group_contains
=> doc: add versionadded to `ExceptionInfo.group_contains`

src/_pytest/fixtures.py
When `param` is not defined, `param_index` is always 0 (see [`_compute_fixture_value`](https://github.com/pytest-dev/pytest/blob/c650e3a94fb7e64001ada05ed9b0855d65693395/src/_pytest/fixtures.py#L606-L614)), so no point in using it besides adding some confusion.
=> fixtures: stop using `request.param_index` in fixture cache key

changelog/12135.bugfix.rst, src/_pytest/fixtures.py, testing/python/fixtures.py
Fixes #12135
> When getting the value of a fixture, it will always add its finalizer to parent fixtures, regardless of if it's cached or not. When we have several subfixtures, this leads to unpredictable ordering between them when they're torn down (if triggered by the parent fixture being torn down). It is also an obvious inefficiency, where a long-lived parent fixture could rack up tons of irrelevant fixtures.
Adds two regression tests: one that checks the ordering failure, and one that checks the number of finalizers.
The implementation would be slightly cleaner if parent fixture parametrization was included in the cache key, as discussed in https://github.com/pytest-dev/pytest/issues/4871#issuecomment-2002622725
=> Don't reregister subfixture finalizer in parent fixture if value is cached

src/_pytest/fixtures.py, src/_pytest/python.py
It makes more sense, also, we have a long term idea of generalizing fixture support to items defined by other plugins, not just python, in which case `--fixtures` would definitely not be python-plugin specific.
=> Move show-fixtures code from python.py to fixtures.py

doc/en/how-to/doctest.rst
Change is trivial or a small documentation fix (e.g., a typo or reword of a small section).
The `conftest.py` example does not work without the `import pytest`, which leads to the following error:
```
py310: commands[0]> pytest --doctest-modules --doctest-continue-on-failure --pyargs src
ImportError while loading conftest '[...]/mooplot/python/src/conftest.py'.
src/conftest.py:4: in <module>
@pytest.fixture(autouse=True)
E   NameError: name 'pytest' is not defined
```
=> doc: `import pytest` in `conftest.py` example in `doctest.rst`

changelog/12167.trivial.rst, src/_pytest/cacheprovider.py, testing/test_assertrewrite.py
Creating and initializing the cache directory is interruptible; this
avoids a pathological case where interrupting a cache write can cause
the cache directory to never be properly initialized with its supporting
files.
Unify `Cache.mkdir` with `Cache.set` while I'm here so the former also
properly initializes the cache directory.
Closes #12167.
=> Initialize cache directory in isolation

testing/test_cacheprovider.py
=> Add test for Cache.mkdir

AUTHORS, changelog/9502.improvement.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, testing/test_runner.py
=> Added an environment variable which helps to check if a code is running from within a pytest run, Fixes #9502

testing/test_runner.py
Fixes https://github.com/pytest-dev/pytest/pull/12190#discussion_r1570666814
=> Makes sure PYTEST_VERSION env variable is cleaned up after the running test_pytest_version_env_var ut

changelog/12194.bugfix.rst, src/_pytest/pathlib.py, testing/test_pathlib.py
Now `importlib` mode will correctly set the imported modules as an attribute of their parent modules.
As helpfully posted on #12194, that's how the Python import module works so we should follow suit.
In addition, we also try to import the parent modules as part of the process of importing a child module, again mirroring how Python importing works.
Because of the latter, I think it is more prudent to *not* backport this and release this in the next minor release: I fear importing the parent module like we are doing here might trigger some side effect in test suites in the wild, which would count as a change in behavior.
Fix #12194
=> importlib: set children as attribute of parent modules

src/_pytest/pathlib.py
Add full type annotations to `pathlib.py` and remove the `allow-untyped-defs` directive.
=> Fully type annotate pathlib.py

.pre-commit-config.yaml, changelog/12069.deprecation.rst, changelog/12069.trivial.rst, doc/en/requirements.txt, pyproject.toml, src/_pytest/hookspec.py, testing/deprecated_test.py
This adds the deprecation that we missed in 7.x (see #12069) so that we can remove them again in 9.x.
Uses new feature of pluggy to deprecate parameters, ~~not yet merged~~ released in pluggy 1.5: https://github.com/pytest-dev/pluggy/pull/495
=> hookspec: deprecate hookimpls requesting py.path parameters

.travis.yml, AUTHORS, changelog/12114.bugfix.rst, src/_pytest/python_api.py, testing/python/approx.py
Fixed the bug for _repr_compare in the ApproxNumpy class located in pytest.approx to ensure that other_side is a numpy array before comparing np_array_shape != other_side.shape. I have verified that the provided test cases, along with the test case provided in #12114, have all passed using pytest testing/python/approx.py.
=> Fixed Bug Regarding Attribute Error in pytest.approx For Types Implicitly Convertible to Numpy Arrays

src/_pytest/_code/code.py, src/_pytest/config/argparsing.py, src/_pytest/fixtures.py, src/_pytest/nodes.py, src/_pytest/pathlib.py, src/_pytest/runner.py, testing/code/test_excinfo.py, testing/test_runner.py, testing/test_skipping.py
Just 2 small cleanups - please see the commits.
=> 2 small cleanups

AUTHORS, changelog/11728.improvement.rst, src/_pytest/unittest.py, testing/test_unittest.py
=> Report class cleanup exceptions

src/_pytest/fixtures.py
The `getfixturevalue` code is split over several functions, but I find it mostly obscures the flow of the logic. This PR inlines `_getnextfixturedef` and `_compute_fixture_value` into  `_get_active_fixturedef` which is now a single linear function, mostly. I did move some sanity checking code out of the function since it mostly distracts.
=> fixtures: inline some functions to streamline the code

src/_pytest/runner.py
In these two cases which re-raise an immediately-caught exception, do the re-raising with `raise` instead of `raise exc`, because the `raise exc` adds an uninteresting entry to the exception's traceback (that of itself), while `raise` doesn't.
=> runner: avoid adding uninteresting entry to tracebacks

changelog/7166.bugfix.rst, src/_pytest/terminal.py
Fix #7166.
The first commit is just preparation without logic changes. The second commit is the fix. After some consideration this is the least disruptive change I could come up with.
There is no test, because it's hard to come up with a deterministic test for this without manually orchestrating hook calls, which is too much effort for me. I manually tested scenarios I could think of.
=> terminal: fix progress percentages not aligning correctly in xdist

changelog/12153.doc.rst, doc/en/example/simple.rst
Add a better way to detect if a code is running from within a pytest run.
=> Updated docs: Documented two ways to detect if a code is running from within a pytest run

changelog/12204.bugfix.rst, src/_pytest/fixtures.py, src/_pytest/runner.py, testing/python/fixtures.py, testing/test_runner.py
Fix #12204 - please see the explanation in https://github.com/pytest-dev/pytest/issues/12204#issuecomment-2081239376
=> fixtures,runner: fix tracebacks getting longer and longer

testing/plugins_integration/requirements.txt, tox.ini
=> testing: restore integration testing with pytest-bdd

changelog/11706.bugfix.rst, src/_pytest/runner.py, testing/test_runner.py
Closes #11706.
Originally fixed in #11721, but then reverted in #12022 due to a regression in `pytest-xdist`.
The regression was fixed on the `pytest-xdist` side in https://github.com/pytest-dev/pytest-xdist/pull/1026.
=> Add back "Fix teardown error reporting when --maxfail=1 (#11721)"

AUTHORS, changelog/12191.bugfix.rst, src/_pytest/runner.py, testing/test_collection.py
=> Consider KeyboardInterrupt/SystemExit at collection time

doc/en/reference/reference.rst, src/_pytest/outcomes.py
As commented on: https://github.com/pytest-dev/pytest/issues/7469#issuecomment-2094104215
=> Document exceptions raised by exit, skip, xfail, fail, and importorskip

AUTHORS, changelog/12300.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
As described in #12300 , pytest crashes with `OSError: [Errno 38] Function not implemented` when it's run under a squashfuse_ll mountpoint. the exception comes from within
```
_pytest/assertion/rewrite.py:1102: in try_makedirs
os.makedirs(cache_dir, exist_ok=True)
```
this is because squashfuse_ll returns `ENOSYS` instead of `EROFS` for a read-only filesystem, which pytest doesn't know how to handle.  This change adds handling of the error code.
closes #12300
=> Fixes crashing under a squashfuse_ll read-only mount

changelog/12275.bugfix.rst, src/_pytest/python.py, src/_pytest/unittest.py, testing/python/collect.py, testing/test_unittest.py
=> python,unittest: don't collect abstract classes

changelog/12120.bugfix.rst, src/_pytest/python.py, testing/test_collection.py
=> python: add workaround for permission error crashes from non-selected directories

changelog/12328.bugfix.rst, src/_pytest/fixtures.py, testing/python/fixtures.py
The `.parent` was incorrectly removed in
a21fb87a90974189c1b8b26189959507189bb3a1, but it was actually correct (well, it assumes that Module.path.parent == Package.path, which I'm not sure is always correct, but that's a different matter). Restore it.
Fix #12328.
=> fixtures: fix non-working package-scope parametrization reordering

.github/workflows/deploy.yml, .github/workflows/test.yml, changelog/12333.trivial.rst
This uses the new build provenance support added in [build-and-inspect-python-package 2.5.0](https://github.com/hynek/build-and-inspect-python-package/blob/main/CHANGELOG.md#250---2024-05-13).
More information: https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
Tested also in https://github.com/pytest-dev/pytest-mock/pull/431.
Note: even though it is technically necessary only for the `deploy` workflow, as the `test` workflow does not publish its packages, decided to always attest the provenance in both cases to avoid any surprises related to this (say a misconfiguration) when deploying.
=> Attest package provenance

src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
python/typeshed#11880 adds more precise types for AST nodes. I'm submitting some changes to adapt pytest to these changes.
=> Fix new typing issues in AST code

.github/workflows/test.yml, changelog/12334.improvement.rst, pyproject.toml, src/_pytest/_code/code.py, src/_pytest/pytester.py, testing/code/test_excinfo.py, testing/code/test_source.py, testing/test_cacheprovider.py, testing/test_doctest.py, testing/test_main.py, tox.ini
=> Add Python 3.13 (beta) support

AUTHORS, changelog/12356.doc.rst, doc/en/explanation/flaky.rst
=> Add thread safety section to flaky test docs

changelog/12367.bugfix.rst, src/_pytest/unittest.py, testing/test_unittest.py
=> unittest: fix class instances no longer released on test teardown since pytest 8.2.0

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
This is used to set the <link rel="canonical" href="X"> tag that points to the canonical version of the webpage. Including this indicates to search engines which version to include in their indexes, and should prevent older versions showing up.
Fixes https://github.com/pytest-dev/pytest/issues/12363
It would be worth checking the ReadTheDocs admin settings first, which I don't have access to. But if the domain is already set correctly as the canonical one, then this PR should manually add in the required HTML tag.
This change will also have to be backported to old versions of the documentation to have the desired effect on search engine indexes.
=> Add html_baseurl to sphinx conf.py

pyproject.toml, src/_pytest/fixtures.py, testing/test_reports.py, testing/test_warnings.py
Using `` maxsplit=1`` from ``use-maxplit-args`` will make splits slightly faster and is the important one that will improve performances.
The other fix are about readability / style.
=> [pylint] Fixes all ``use-maxplit-args``, ``consider-using-enumerate``

src/_pytest/hookspec.py
=> Clarify pytest_ignore_collect docs

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 8.0.x branch. Needed on all currently published documentation branches to resolve the issue.
=> [8.0.x] Add html_baseurl to sphinx conf.py (#12364)

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
[7.3.x] Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 7.3.x branch. Needed on all currently published documentation branches to resolve the issue.
=> [7.3.x] Add html_baseurl to sphinx conf.py (#12364)

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 7.2.x branch. Needed on all currently published documentation branches to resolve the issue.
=> [7.2.x] Add html_baseurl to sphinx conf.py (#12364)

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 7.1.x branch. Needed on all currently published documentation branches to resolve the issue.
=> [7.1.x] Add html_baseurl to sphinx conf.py (#12364)

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 7.0.x branch. Needed on all currently published documentation branches to resolve the issue.
=> [7.0.x] Add html_baseurl to sphinx conf.py (#12364)

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 7.4.x branch. Needed on all currently published documentation branches to resolve the issue.
=> [7.4.x] Add html_baseurl to sphinx conf.py (#12364)

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 8.1.x branch. Needed on all currently published documentation to resolve the issue.
=> [8.1.x] Add html_baseurl to sphinx conf.py (#12364)

AUTHORS, changelog/12363.doc.rst, doc/en/conf.py
Backport of PR https://github.com/pytest-dev/pytest/pull/12364 to 6.2.x branch. Needed on all currently published documentation branches to resolve the issue.
=> [6.2.x] Add html_baseurl to sphinx conf.py (#12364)

doc/en/index.rst
- Remove upcoming Python Academy training (cancelled due to only 2 sign-ups)
- Add link for Europython training
- Add training [at Workshoptage](https://pretalx.com/workshoptage-2024/talk/9VUHYB/)
- More infos and consistent formatting
=> doc: Update trainings/events

changelog/12355.bugfix.rst, src/_pytest/fixtures.py, testing/python/fixtures.py
Manual minimal backport from commit e89d23b24741c001e8651a77303992cfa41c1664.
=> [8.2.x] fixtures: fix catastrophic performance problem in `reorder_items`

.pre-commit-config.yaml, testing/test_unittest.py
=> filter all code over `pyupgrade --py38-plus`

src/_pytest/fixtures.py
There is no reason to allow this.
=> fixtures: change `register_fixture` to not accept `scope=None`

changelog/12424.bugfix.rst, src/_pytest/unittest.py, testing/plugins_integration/pytest_rerunfailures_integration.py, tox.ini
This fixes unittest test reruns when using plugins like pytest-rerunfailures.
The `instance` property uses AttributeError to check if the instance needs to be initialized, so `del` is the correct way to clear it, not setting to `None`.
Regressed in 8.2.2.
Fix #12424
=> unittest: fix assertion errors on unittest reruns

src/_pytest/capture.py, src/_pytest/config/__init__.py, src/_pytest/monkeypatch.py, src/_pytest/pytester.py
Caused by 4588653b2497ed25976b7aaff225b889fb476756. ~~I disabled the offending Ruff rule.~~
Fix #12437.
=> doc: fix broken code blocks

testing/acceptance_test.py
The `subprocess.run()` invocation is present in the `test_issue_9765` regression test
that is always skipped unconditionally, resulting in the
`EncodingWarning` never manifesting itself in CI or development
environments of the contributors. This patch corrects the problem by passing the encoding value.
This patch also replaces the `setup.py` call w/ `pip install` in the same test.
Using this CLI interface has been deprecated in `setuptools` [[1]].
[1]: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
=> Modernize the skipped `test_issue_9765` regression test

src/_pytest/doctest.py
There was a regression caused by #12431 that excluded the patch on broken CPython patch version ranges 3.11.0–3.11.8 and 3.12.0–3.12.2.
This change fixes that by adjusting the patching conditional clause to include said versions.
Closes #12430.
=> 🚑 Clarify patch condition for doctest finder hack

.github/workflows/test.yml
This adds a GHA job that reliably determines if all the required
dependencies have succeeded or not.
It also allows to reduce the list of required branch protection CI
statuses to just one — `check`. This reduces the maintenance burden
by a lot and have been battle-tested across a small bunch of projects
in its action form and in-house implementations of other people.
I was curious about the spread of use. And I've just discovered that
it is now in use in aiohttp (and other aio-libs projects), CherryPy,
some of the Ansible repositories, all of the jaraco's projects (like
`setuptools`, `importlib_metadata`), some PyCQA, PyCA and pytest
projects, a few AWS Labs projects. Admittedly, I maintain a few of
these but it seems to address some of the pain folks have:
jaraco/skeleton#55 (comment). …
=> Introduce a gate/check GHA job

.github/patchback.yml
This patch prepares the project's backporting process to start being handled by the Patchback GitHub App [[1]].
Ref #9384
Resolves #9385
Resolves #9553
Resolves #9554
Resolves #9555
[1]: https://github.com/apps/patchback
=> 💅 Add a config for the Patchback GitHub App

.github/chronographer.yml
This app allows requiring changelog fragments to be included with each pull request.
=> 💅 Add a config for the Chronographer GitHub App

changelog/11797.bugfix.rst, src/_pytest/python_api.py, testing/python/approx.py
this needs a validation as it allows partially implemented sequences
closes #11797 
this changes the recursive map of approx to accept all sequences (just like approx)
i would like to gather feedback form @nicoddemus and @Zac-HD on whether to accept the recursion in general,
or if we ought to limit it by changing the toplevel call in ApproxSequenceLike to a listcomp operating only on the elements of the sequence
=> fix #11797: be more lenient on SequenceLike approx

.github/workflows/test.yml
The original PR required all the matrix jobs to pass. This patch corrects that, allowing some of them to fail according to how the branch protection is set up now.
=> 🧪 Make required CI jobs match branch protection

changelog/12469.doc.rst, changelog/12469.improvement.rst, doc/en/example/simple.rst, doc/en/how-to/fixtures.rst, doc/en/how-to/usage.rst, doc/en/how-to/writing_plugins.rst, doc/en/reference/customize.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, src/_pytest/helpconfig.py, testing/test_assertion.py, testing/test_helpconfig.py
This feature grew out of `setuptools` but the modern interface for extracting this information from the distribution package metadata is `importlib.metadata`. So the patch attempts to reflect this in the documentation messaging.
Refs:
* https://docs.python.org/3/library/importlib.metadata.html#entry-points
* https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata
* https://packaging.python.org/en/latest/specifications/entry-points/#entry-points
Docs previews:
* https://pytest--12469.org.readthedocs.build/en/12469/example/simple.html#dynamically-adding-command-line-options
* https://pytest--12469.org.readthedocs.build/en/12469/example/simple.html#freezing-pytest
* https://pytest--12469.org.readthedocs.build/en/12469/how-to/fixtures.html#using-f …
=> 📝 Make "setuptools entrypoint" term generic

tox.ini
It is called when building the docs. Apparently, `tox -e docs` is not
invoked in CI, neither is it called in RTD, resulting in the
regression having been caught only in local development environments.
This is a follow-up for #12493.
=> 🚑🧪📝 Allow invoking git in tox

changelog/12498.contrib.rst, tox.ini
Previously, a part of the environments weren't documented in the config, making it difficult for the newbies to figure out what their purposes are. This patch sets the descriptions for all the envs listed with the `tox -av` command, leveraging the dynamic factor-dependent explanation fragments.
```console
default environments:
linting                   -> run pre-commit-defined linters under `python3`
py38                      -> run the tests under `py38`
py39                      -> run the tests under `py39`
py310                     -> run the tests under `py310`
py311                     -> run the tests under `py311`
py312                     -> run the tests under `py312`
py313                     -> run the tests under `py313`
pypy3                     -> run the tests under …
```
=> 🎨 Add descriptions to all `tox` environments

.github/workflows/test.yml, .github/workflows/update-plugin-list.yml, changelog/12502.contrib.rst
Normally, PRs/commits published using the default GitHub Actions CI/CD API token are not propagated to any integrations. This patch marks the plugin update PR as a draft and leaves a comment asking the maintainers to mark it as ready for review in order to actually trigger a CI run.
This idea is found in GitHub's own repos:
* https://github.com/github/codeql-action/pull/2263#issuecomment-2078311173
* https://github.com/github/codeql-action/blob/4ebadbc7/.github/workflows/update-dependencies.yml#L38-L41
* https://github.com/github/codeql-action/pull/1868
* https://github.com/github/codeql-action/pull/679
=> 🧪 Make a draft based plugin bump PR CI trigger

.github/workflows/test.yml, codecov.yml
The #11921 update broke uploading coverage of the `main` branch (or any in-repo pushes for that matter) to Codecov 4 months ago. Version 4 requires an upload token to be provided and since there was no configuration for it, the upload was failing. But the step itself was showing up as successful due to `fail_ci_if_error: true` being set. The error is visible in the console output, though.
This patch flips the setting to `fail_ci_if_error: false` and sets the Codecov upload token in the config in clear text. The non-secret part allows the PRs uploads to be more stable.
=> 🧪🚑 Pass a Codecov config to the action @ GHA

AUTHORS, changelog/389.improvement.rst, src/_pytest/_io/saferepr.py, src/_pytest/assertion/rewrite.py, testing/io/test_saferepr.py, testing/test_assertrewrite.py
Closes #389
With the help of @flub and @obestwalter, we were able to find an easy way to simplify the output of assertion failures to something like this, while keeping the old behavior same as before for unbounded objects:
```
=================================== FAILURES ===================================
_____________________________________ test _____________________________________
def test():
>       assert Help().fun() == 2
E       assert 1 == 2
E        +  where 1 = fun()
E        +    where fun = <test_local.Help object at 0x1074be230>.fun
E        +      where <test_local.Help object at 0x1074be230> = Help()
test_local.py:13: AssertionError
=========================== 1 failed in 0.03 seconds ===========================
```
However, I opened an issue (#12499) to refactor the …
=> refactor: simplify bound method representation

.github/workflows/test.yml
This version drops the use of the outdated GHA syntax for setting action output values.
=> 🧪 Bump the `alls-green` action to 223erbb7

.github/workflows/test.yml
It's necessary since it seems that the currently used Codecov uploader doesn't read the token from the config sometimes.
This is a follow-up for #12508 which wasn't enough.
=> 🚑🧪 Set the Codecov token directly in GHA

changelog/12522.contrib.rst, doc/en/announce/release-2.9.0.rst, doc/en/announce/release-2.9.1.rst, doc/en/announce/release-2.9.2.rst, doc/en/changelog.rst, doc/en/conf.py, doc/en/historical-notes.rst, doc/en/requirements.txt
This Sphinx extension implements more generic roles that can also be used
more flexibly. Relying on an external extension allows us to stop
maintaining an in-repo copy of the commonly used behavior.
As a part of the change, the `:pull:` RST role is being replaced with `:pr:`.
=> 📝 Replace GH/PyPI `extlinks` w/ `sphinx-issues`

doc/en/example/markers.rst, doc/en/how-to/usage.rst, src/_pytest/mark/expression.py, testing/test_mark.py, testing/test_mark_expression.py
=> Improve documentation & other kinks of marker keyword expression PR #12500

AUTHORS, changelog/12544.improvement.rst, doc/en/reference/reference.rst, src/_pytest/main.py, testing/test_collection.py
closes #12544
- Updated the `_in_venv` function in `src/_pytest/main.py` to correctly detect Python virtual environments.
- Updated the test cases in `testing/test_collection.py` to validate the new behavior.
- Created a changelog fragment to document this improvement.
=> Support venv detection on Windows with mingw Python

.coveragerc, changelog/12531.contrib.rst
These tests are known to only be executed partially or not at all. So we always get incomplete, missing, and sometimes flaky, coverage in the test functions that are expected to fail.
This change updates the ``coverage.py`` config to prevent said tests from influencing the coverage level measurement.
=> 🧪 Unmeasure coverage in tests expected to fail

changelog/12472.bugfix.rst, src/_pytest/reports.py, src/_pytest/terminal.py, testing/test_terminal.py
The following snippet would have resulted in crash on multiple places since
`_get_verbose_word` expects only string, not a tuple.
```python
@pytest.hookimpl(tryfirst=True)
def pytest_report_teststatus(report: pytest.CollectReport | pytest.TestReport, config: pytest.Config):
if report.when == "call":
return ("error", "A",  ("AVC", {"bold": True, "red": True}))
return None
```
```python-traceback
File "/home/pbrezina/workspace/sssd/.venv/bin/pytest", line 8, in <module>
sys.exit(console_main())
^^^^^^^^^^^^^^
File "/home/pbrezina/workspace/pytest/src/_pytest/config/__init__.py", line 207, in console_main
code = main()
^^^^^^
File "/home/pbrezina/workspace/pytest/src/_pytest/config/__init__.py", line 179, in main
ret: Union[ExitCode, int] = …
```
=> testresult: correctly apply verbose word markup and avoid crash

.github/workflows/test.yml
Reverts pytest-dev/pytest#12516.
https://github.com/codecov/codecov-cli/pull/464 has been released in codecov-cli v0.7.2 so this hack should no longer be necessary.
=> Revert "🚑🧪 Set the Codecov token directly in GHA"

changelog/12544.improvement.rst, changelog/12545.improvement.rst
The original change note didn't use RST in places with identifiers.
This patch corrects that and includes the byline into the sentence.
Preview: https://pytest--12559.org.readthedocs.build/en/12559/changelog.html#improvements-in-existing-functionality
=> 📝 Add markup to the PR #12545 changelog entry

.pre-commit-config.yaml, changelog/12562.contrib.rst
It is easy to forget backticks in change note bylines. It's happened in #12531 already, requiring a hotfix in #12560.
The pre-commit based check idea is coming from the Tox project and have been battle-tested in aiohttp, CherryPy, and other ecosystems.
=> 🧪 Lint for typos in `:user:` RST role

testing/python/fixtures.py
=> [python 3.13] Mark functool.partial test to be skipped

changelog/12567.feature.rst, doc/en/how-to/output.rst, src/_pytest/terminal.py, testing/test_terminal.py
This controlls how the skipped tests are displayed in the short summary.
- yes (default): keeps the current behavior that folds the skipped tests
together
- no: each skipped test is on its own line, display as any other status
Resolves: https://github.com/pytest-dev/pytest/issues/9876
=> feat: add --fold-skipped=yes|no cli option

changelog/12577.doc.rst, doc/en/explanation/ci.rst, doc/en/explanation/index.rst, doc/en/reference/reference.rst, src/_pytest/helpconfig.py
I also added the mention in `pytest -h`.  Closes https://github.com/pytest-dev/pytest/issues/12577.
FYI, the doc of 8.x is not very well referenced, and when I was looking for this env var, I always was on the doc of version 7.x
=> details impact of specifying CI or BUILD_NUMBER

doc/en/index.rst
"Security" was marked with a different heading level than all other entries on that page, effectively making it a subsection of "pytest for enterprise". This seems like an oversight. Security is not just for enterprises and should be on the same level as all other sections.
=> Fix heading level on index.rst

doc/en/contact.rst
Follow-up to #12427 plus some more cleanups:
- Mention `core@pytest.org` as mail point of contact ~~(not live yet, hence why this is a draft PR)~~
- Also add a list of core maintainers receiving such mails. Unfortunately the [GitHub Team page](https://github.com/orgs/pytest-dev/teams/core) is not public, so we can't just link to it. Still I feel like it's important to have a public-facing list of people that actually are in the core team, and I suppose this will be the right place?
- Mention Bruhin Software for trainings/consulting. Let me know if you'd rather not have me do that, but given that Merlinux was mentioned there and I pretty much took those things over from Holger, I suppose it should be fine?
- Remove dead link references
- Restructure channels into different groups for more …
=> Update contact channels

pyproject.toml, src/_pytest/_io/saferepr.py, src/_pytest/helpconfig.py
Activate the PLR/PLC messages from ruff, and disable most of them. Also add some comments on existing pylint disables that are deactivated in ruff, so it's easy to see that the disable is voluntary and not because there's too much to fix.
=> [pylint/ruff] Activate PLR / PLC messages in ruff

AUTHORS, changelog/6962.bugfix.rst, src/_pytest/fixtures.py, testing/python/fixtures.py
The fix for Issue #6541 caused a regression where cache hits unexpectedly became cache misses.  Attempt to restore the previous behavior, while also retaining the fix for the bug.
Fixes: Issue #6962
=> fix: improved caching of parameterized fixtures

.github/workflows/test.yml, changelog/11771.contrib.rst, changelog/12557.contrib.rst, testing/test_skipping.py
As we were encountering this - 
```python-traceback
__________________ ERROR collecting testing/_py/test_local.py __________________
/opt/hostedtoolcache/PyPy/3.8.16/x64/lib/pypy3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1023: in _gcd_import
???
<frozen importlib._bootstrap>:1000: in _find_and_load
???
<frozen importlib._bootstrap>:984: in _find_and_load_unlocked
???
<frozen importlib._bootstrap>:680: in _load_unlocked
???
.tox/pypy3-xdist/lib/pypy3.8/site-packages/_pytest/assertion/rewrite.py:166: in exec_module
source_stat, co = _rewrite_test(fn, self.config)
.tox/pypy3-xdist/lib/pypy3.8/site-packages/_pytest/assertion/rewrite.py:350: in _rewrite_test
co = compile(tree, strfn, "exec", …
```
=> Bump PyPy runtime to v3.9 @ GHA 

doc/en/changelog.rst
Applying @nicoddemus suggestions from #12635. Applying to 8.3.x so I can cherry-pick to master in one shot.
=> [8.3.x] doc/changelog: update 8.3.0 notes

changelog/12652.bugfix.rst, src/_pytest/main.py, testing/test_collection.py
initially we accidentially detected conda environmnts by just testing too many files
after steamlining we no longer detected conda environments
now we explicitly detect conda environments and test for support
@jezdez - i believe this should solve it more future-proof, thanks for the input
Closes #12652
=> explicitly detect conda envs - fixes #12652

doc/en/broken-dep-constraints.txt, doc/en/requirements.txt
Pin `towncrier` until we find a solution to https://github.com/sphinx-contrib/sphinxcontrib-towncrier/issues/92.
The 2nd commit just removes an obsolete comment and explicit dependency (see commit message).
=> Pin towncrier due to incompatibility with sphinxcontrib-towncrier

AUTHORS, changelog/12678.doc.rst, doc/en/reference/reference.rst
Previously the docs contained an example for `tmp_path_retention_policy` which included quotes around the value. If the configuration was actually set with this value. The following error would be encountered
`INTERNALERROR> ValueError: tmp_path_retention_policy must be either all, failed, none. Current input: "all".`
This is because the value of the field was not being unwrapped from the quotes when parsed.
This commit removes the quotes from the example so that if used in the configuration file, no error will occur.
closes #12678
=> Remove quotes from example tmp_path_retention_policy

changelog/6682.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
Seems like we just missed that case when more fine-grained verbosity levels were added.
Fixes #6682, #12307
=> Obey verbosity level when printing 'msg' part of assertions

CONTRIBUTING.rst
As discussed in https://github.com/pytest-dev/pytest/discussions/12633.
=> Add merge/squash guidelines to CONTRIBUTING.rst

doc/en/reference/reference.rst
I found myself pausing to decipher the following sentence in the pytest reference [docs](https://docs.pytest.org/en/8.3.x/reference/reference.html#confval-cache_dir), "Sets a directory where stores content of cache plugin.". With little context, the sentence is unclear and can easily interrupt a reader's _flow_. This PR introduces an update to revise the description for the `cache_dir` configuration options section to improve semantics and clarity.
> This section outlines notable considerations for developers/maintainers.
- This PRs branch is based on `pytest/main` from my forked checkout. Kindly advise me on how to cascade this change across all pytest doc versions (ie. `latest`, `stable`, `8.3.x`, etc).
- Alternative sentence **variations** to use to improve clarity:
- Specifies the …
=> docs: Revise `cache_dir` option section

changelog/12663.doc.rst, src/_pytest/hookspec.py
Addresses confusion around `pytest_deselected` usage flagged in #12663
=> docs: clarify `pytest_deselected`/`pytest_collection_modifyitems` usage

pyproject.toml
This adds back the classifier as it was removed by accident, and I also added the config to avoid pyproject-fmt from removing it again.
See https://github.com/pytest-dev/pytest/pull/12321#issuecomment-2311805015 for context.
=> MAINT: adding back Python 3.13 classifier

changelog/12744.bugfix.rst, src/_pytest/doctest.py, src/_pytest/nodes.py, src/_pytest/python.py
Fixes https://github.com/pytest-dev/pytest/pull/11916#issuecomment-2313758038
Importing `Self` from `typing` breaks the return type on Python 3.9 and under. You should be using `from typing_extension import Self` instead.
For example, the following code:
```py
def pytest_collect_file(file_path: pathlib.Path, parent: Node) -> CheckdocsItem | None:
if file_path.name not in project_files:
return None
return CheckdocsItem.from_parent(parent, name='project')
```
Will error with `Returning Any from function declared to return "CheckdocsItem | None"  [no-any-return]` on 3.8 & 3.9, but pass on 3.10+ Which can only be worked around by disabling the error entirely in mypy, or doing:
```py
def pytest_collect_file(file_path: pathlib.Path, parent: Node) -> CheckdocsItem | None:
if file_path.name not …
```
=> Replaced `typing.Self` with `typing_extensions.Self`

.pre-commit-config.yaml, src/_pytest/main.py, src/_pytest/runner.py, testing/test_runner.py
Follow up to #12744, this ensures type checking works at the oldest Python version supported by pytest.
=> Use oldest supported Python in mypy pre-commit checks

doc/en/index.rst
Unfortunately needed to be cancelled as there were only one sign-up :sweat_smile:
=> doc: Remove past training

doc/en/example/parametrize.rst
A space is needed for ``ZeroDivisionError`` to render as teletype.
I don't have 3.12 on this computer so I did not build the docs locally to test.  However, compare renderings of `ZeroDivisionError` with current main
https://github.com/pytest-dev/pytest/blob/main/doc/en/example/parametrize.rst#parametrizing-conditional-raising
and this pr
https://github.com/svenevs/pytest/blob/fix/docs-example-parametrize-minor-typo/doc/en/example/parametrize.rst#parametrizing-conditional-raising
Thanks for the docs, I definitely want to start adding some test id's for what I'm working on (current output = chaos xD).  Was easy to find in the docs! :slightly_smiling_face:
=> [doc] Fix minor typo in example/parametrize.rst

AUTHORS, changelog/12707.improvement.rst, src/_pytest/debugging.py, testing/test_debugging.py
=> Exception chains can be navigated when dropped into Pdb in Python 3.13+

changelog/12446.bugfix.rst, src/_pytest/fixtures.py, testing/python/collect.py
=> do not discover properties when iterating fixtures

scripts/release.py
As noted in #12789, the `release.py` script did not consider `Co-authored-by` fields, and since we introduced the new backport bot, this problem became more apparent due to how the backport commit and PR are generated.
Previously, the list of authors produced by the script in the #12789 branch was:
```
* Avasam
* Bruno Oliveira
* Ronny Pfannschmidt
* Sviatoslav Sydorenko (Святослав Сидоренко)
```
With this script:
```
* Anthony Sottile
* Avasam
* Bruno Oliveira
* Christian Clauss
* Eugene Mwangi
* Florian Bruhin
* GTowers1
* Nauman Ahmed
* Pierre Sassoulas
* Reagan Lee
* Ronny Pfannschmidt
* Stefaan Lippens
* Sviatoslav Sydorenko (Святослав Сидоренко)
* dongfangtianyu
```
=> Include co-authors in release announcement

scripts/update-plugin-list.py
Adding it as a `ADDITIONAL_PROJECTS`, because our naming conventions can't fit `pytest-` as a prefix.
See:
- https://github.com/databrickslabs/pytester
- https://pypi.org/project/databricks-labs-pytester/
=> Added mention of Databricks fixture plugin for PyTest

doc/en/how-to/capture-stdout-stderr.rst
This paragraph and the previous paragraph had the same opening clause, making it seem like they were duplicates. I added some text making it clearer that this paragraph is about filedescriptors.
=> Clarify that `capfdbinary` captures on a filedescriptor level.

AUTHORS, changelog/12818.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
=> preserve source positions for assertion rewriting

AUTHORS, changelog/9037.bugfix.rst, doc/en/reference/reference.rst, src/_pytest/mark/structures.py, src/_pytest/python.py, testing/python/metafunc.py
Closes #9037 .
The additional test cases were implemented in almost the same way as the existing similar test cases.
=> Fix `disable_test_id_escaping_and_forfeit_all_rights_to_community_support` option when using `pytest.param(..., id="...")`

changelog/12866.doc.rst, doc/en/builtin.rst, doc/en/how-to/capture-warnings.rst, doc/en/reference/reference.rst, src/_pytest/recwarn.py
=> Docs: improve/cleanup reference from/to recwarn

.pre-commit-config.yaml
=> [pre-commit] Fix local pre-commit installation for python != 3.8

.pre-commit-config.yaml, pyproject.toml
Follow-up for #12869 see https://github.com/pytest-dev/pytest/pull/12869#issuecomment-2404928901
=> [mypy] python-version independant from pre-commit

.github/workflows/test.yml, changelog/12497.contrib.rst, testing/test_debugging.py
Python 3.13 makes pdb break on the breakpoint() call, rather than on the next line:
https://docs.python.org/3/whatsnew/3.13.html#pdb
Also runs the pdb tests on Python 3.13 in CI.
See #12884 for a more proper solution for that.
Fixes #12497
=> Fix pdb selftests on Python 3.13

AUTHORS, changelog/10558.doc.rst, src/_pytest/config/__init__.py, testing/test_config.py
Also add tests to cement the current behavior.
Supersedes #12879 (I did not have permissions to push an additional commit to it).
=> Improve pytest.Config.getoption docstring

testing/python/fixtures.py
Very minor irk, I got this test failing because I created a git worktree that contained the string "error".
=> [minor] avoid test failing if the working path contains the string 'error'

changelog/10829.doc.rst, doc/en/how-to/tmp_path.rst, doc/en/reference/reference.rst, src/_pytest/legacypath.py, src/_pytest/tmpdir.py
Improve coverage of current handling of `--basetemp` option and its lack of retention functionality.
- ~[ ] Include documentation when adding new features.~
- ~[ ] Include new tests or update existing tests when applicable.~
Addresses (part of) issue #10829:
the `--basetemp` option and the default retention feature can not be combined currently. This is completely unclear from the current docs. While I initially requested to allow the combination of retention with `--basetemp` in #10829, this PR just attempts better document the current behavior.
=> Improve docs on basetemp and retention

pyproject.toml, src/_pytest/mark/__init__.py
The first commit is a small optimization, the second fix would have been opinionated so I disabled it locally in the second commit. (Had to recreate the MR from https://github.com/pytest-dev/pytest/pull/12924
=> [pylint consider-using-any-or-all] Fix or disable all detected issues

src/_pytest/fixtures.py
Broken out from #12930 where I originally was going to raise a `FixtureLookupError` but noticed that `formatrepr` crashed. I haven't researched thoroughly why it's currently making these assumptions, but it *will* crash if this assert doesn't hold - so thought I'd at least save some developer time in case anybody tries to use `FixtureLookupError` again (e.g. when #12930 turns into an error)
=> add assertion to FixtureLookupError.formatrepr

changelog/12966.doc.rst, doc/en/how-to/capture-warnings.rst
- ~[ ] Include documentation when adding new features.~
- ~[ ] Include new tests or update existing tests when applicable.~
Addresses #12966  by clarifying how to specify multiple `filterwarnings` marks and how order/precedence works. Also improves some `filterwarnings`  related cross-references
=> Clarify docs on specifying multiple filters with pytest.mark.filterwarnings

changelog/12535.doc.rst, doc/en/example/simple.rst
Current state deals with the setup outcome only:
* testing only for "failed" should not be reported as "or skipped"
* test for "skipped" explicitly instead
I'm unclear what to do about the test call outcome, as I don't see in which case "call" would not be in report, while setup was "passed" (was this intended for the case where setup was indeed "skipped"?  would't that be unintuitive?).
=> examples: be more precise about TestReport outcome

changelog/12981.bugfix.rst, src/_pytest/config/__init__.py, testing/test_config.py
=> prevent Config.add_cleanup callbacks preventing other cleanups running

doc/en/explanation/goodpractices.rst
Follow-up to #7870, see #12983.
cc @tadeu
=> docs: Fix wrong statement about sys.modules with importlib import mode

AUTHORS, changelog/12426.improvement.rst, src/_pytest/fixtures.py, testing/plugins_integration/pytest.ini, testing/python/fixtures.py
Follow up to #12439.
Closes #12426
Closes #12439
=> Fix `pytest.mark.usefixtures()` without arguments silently erroring

RELEASING.rst, scripts/release.patch.rst
While of course `pip` is still the most used tool to install packages, currently there are a lot of alternatives (`poetry`, `uv`, etc), so it feels a bit dated to suggest `pip install --upgrade` directly on the release announcement.
Also, all the other release notes do not mention `pip` too, so it makes sense to remove it from the patch release announcement.
=> Remove 'pip' command hint from release announcement

changelog/13016.improvement.rst, changelog/13028.improvement.rst, src/_pytest/threadexception.py, testing/test_threadexception.py
fixes #13028 13028 per review comment https://github.com/pytest-dev/pytest/pull/13016#discussion_r1870340465
=> remove 1-second join from threadexception plugin

changelog/13026.bugfix.rst, src/_pytest/pathlib.py, testing/test_pathlib.py
closes #13026 .
Only parent modules with the `__path__` attribute can be used by the `find_spec` function, and most of the standard library does not meet this condition.
https://github.com/python/cpython/blob/3.9/Lib/importlib/_bootstrap_external.py#L1223
```python
def _find_parent_path_names(self):
"""Returns a tuple of (parent-module-name, parent-path-attr-name)"""
parent, dot, me = self._name.rpartition('.')
if dot == '':
return 'sys', 'path'
return parent, '__path__'
```
So this PR adds a condition check.
=> fix `AttributeError`  crash when using `--import-mode=importlib`

AUTHORS, changelog/12863.bugfix.rst, pyproject.toml, src/_pytest/mark/structures.py, testing/test_mark.py
Fixed parametrized markers over staticmethod and classmethod decorators.
closes #12863 
An interesting thing about this solution and python (<3.9 vs 3.10<) compatibility:
In python3.10, they changed `@staticmethod` and `@classmethod` decorators to inherit method attributes.
Before that version, functions wrapped with them did not return true for  `callable()` func, so it failed tests for py39 and succeeded for py310. 
[link to changelog](https://docs.python.org/3/whatsnew/3.10.html#other-language-changes)
For example: 
```python
from pytest import mark
class TestA:
@mark.parametrize("value", [1, 2])
@staticmethod
def test_foo(value: int):
"""Didn't work. Now fixed :)"""
@pytest.mark.parametrize("value", [1, 2])
@classmethod
def test_bar(cls, value: int):
"""Didn't work. Now fixed :)""" …
```
=> Fix parametrized mark over staticmethod decorator

.github/workflows/deploy.yml, .github/workflows/prepare-release-pr.yml, .github/workflows/update-plugin-list.yml
"zizmor" is a new tool to statically analyze github actions files for security issues. See See: https://woodruffw.github.io/zizmor/.
Fix all issues reported by zizmor 0.9.2 running locally.
=> ci: harden github actions according to "zizmor" recommendations

.github/workflows/test.yml
Some of the pluggy jobs (I guess the ones fetching from git) started to fail since pluggy dropped support for 3.8 and the jobs are running with 3.8. So bump them to 3.9.
=> [8.3.x] ci: fix failing jobs due to pluggy requiring Python>=3.9

changelog/13031.improvement.rst, src/_pytest/mark/structures.py, testing/test_mark.py
this ensures we dont invoke idfunc with the internal NOTSET enum token
closes #13031
=> fix #13031: use the concrete id NOTSET for the empty parameter list

changelog/13112.contrib.rst, testing/conftest.py, testing/test_terminal.py
With Pygments 2.19, the Python lexer now emits
Text.Whitespace (rather than Text) tokens after "def", which get highlighted as "bright black".
See https://github.com/pygments/pygments/issues/1905
Fixes #13112
(also fixes the current CI failures, I hope!)
=> Fix selftests with Pygments >= 2.19.0

AUTHORS, changelog/13083.bugfix.rst, src/_pytest/pathlib.py, testing/test_pathlib.py
This PR addresses issue #13083 by modifying the scandir function to handle the case where a non-existent directory is provided. Previously, the function did not return a result for such cases, potentially leading to unhandled errors. Now, if the directory does not exist, the function will return an empty list instead.
Changes made:
Updated scandir to catch FileNotFoundError and return an empty list if the directory does not exist.
Updated the function docstring to reflect the new behavior.
Testing:
Also two tests were added. 
Closes #13083
=> Fix scandir() crash by returning [] when directory is not found (#13083)

changelog/13122.improvement.rst, src/_pytest/stepwise.py, testing/test_cacheprovider.py, testing/test_stepwise.py
Now `--stepwise` will remember the last failed test, even if the previous pytest invocations did not receive `--stepwise`.
Previously it would always clear the cache if not active, which hinders certain interactive workflows, which is the prime use case for the flag.
=> Improve stepwise to not forget failed tests

src/_pytest/_py/error.py
When running `pre-commit` on Windows, I get the error below:
```
src\_pytest\_py\error.py:95: error: Invalid index type "Optional[int]" for "dict[int, int]"; expected type "int"  [index]
Found 1 error in 1 file (checked 234 source files)
```
Ignore the error because we do catch the `KeyError` anyway.
=> Fix internal mypy error on Windows

AUTHORS, changelog/13115.improvement.rst, src/_pytest/python_api.py, testing/code/test_excinfo.py
Accept `(Base)ExceptionGroup` with generic arguments in `pytest.raises`
Closes #13115
=> Accept generic ExceptionGroups for raises

changelog/11777.bugfix.rst, changelog/12713.feature.rst, src/_pytest/assertion/rewrite.py, src/_pytest/terminal.py, testing/test_terminal.py
Closes #12713. 
The fix for issue #11777 removed any output shortening in the test summary output when `-vv` is used, leading to potentially long/redundant summary messages. The issue in #11777 is also now fully fixed, as series were still condensed in output even with full verbosity.
Since the removal of the summary shortening has been in place for a while, the addition of a new runtime option seemed to be the best way to address #12713 without changes to existing functionality. `--force-short-summary` was added to always show a shortened summary message regardless of the verbosity setting. Additionally, when using `-vv`, `saferepr_unlimited` is now called to fully resolve #11777.
=> Add --force-short-summary option and extend sequence printing with -vv

changelog/11777.bugfix.rst, src/_pytest/assertion/rewrite.py, testing/test_terminal.py
Fix #11777
Backport of #13061.
=> [8.3.x] Fix sequences being shortened even with `-vv` verbosity.

AUTHORS, changelog/10224.improvement.rst, src/_pytest/_code/code.py, src/_pytest/_code/source.py, testing/code/test_excinfo.py
Hey folks this is just a proof of concept for https://github.com/pytest-dev/pytest/issues/10224 to serve as a reference for if any contributor wants to give this a full shot.
This adds a very basic implementation of the PEP657 style expression highlighting in the short and long traceback modes. It's not the full fledged python `traceback.py` implementation where we try to differentiate which parts contain operators.
I don't think I'll have time to finish this out fully, there's some interesting problems here like `mypy` complaining because typeshed doesn't have some of the newer `traceback` `FrameSummary` attrs like `colno`. Additionally, since the python offsets are from the start of the line, we have to know the line before it gets de-dented in `Source`.
-----
Example of what it looks …
=> Add basic implementation of PEP657 style expression markers in tracebacks

changelog/12888.bugfix.rst, src/_pytest/capture.py, testing/test_capture.py
We had a very similar workaround before for pyreadline, which had a similar issue:
- Introduced in #1281
- Removed in #8848 for #8733 and #8847
This technically will regress the issues above, but those issues just mean that `import readline` is broken in general, so the user should fix it instead (by e.g. uninstalling pyreadline).
Fixes #12888
Fixes #13170
=> Add readline workaround for libedit

.github/workflows/deploy.yml, .github/workflows/test.yml
Otherwise the build is broken as Python 3.13 is used, but the pinned pydantic-core version doesn't have support.
build-and-inspect-python-package v2.6.0: https://github.com/hynek/build-and-inspect-python-package/blob/v2.6.0/requirements/tools.txt#L297
v2.12.0: https://github.com/hynek/build-and-inspect-python-package/blob/v2.12.0/requirements/tools.txt#L303
3.13 support added in Pydantic v2.8.0: https://docs.pydantic.dev/latest/changelog/#v280-2024-07-01
and build-and-inspect-python-package uses `python-version: 3.x`: https://github.com/hynek/build-and-inspect-python-package/blob/v2.12.0/action.yml#L58
which I'm assuming broke this by switching from 3.12 to 3.13 at some point.
=> [8.3.x] Fix CI

doc/en/index.rst
Since we only have 4 sign-ups so far (2 of them originally on-site), we decided to switch to remote-only.
=> doc: Change training to remote only

tox.ini
It's a pain to have these when testing locally, they're unnecessary, and will prompt for ssh password (my ssh-agent env vars aren't passing through to tox).
Testing to see if this breaks CI
=> remove `git fetch` from tox docs environment

changelog/13175.bugfix.rst, changelog/7683.improvement.rst, pyproject.toml, src/_pytest/_io/terminalwriter.py, src/_pytest/assertion/util.py, testing/test_assertion.py
- Closes https://github.com/pytest-dev/pytest/issues/7683
- Fixes https://github.com/pytest-dev/pytest/issues/13175
=> Make pygments mandatory and fix string highlighting

doc/en/how-to/capture-warnings.rst
This was linking to a completely unrelated PEP, presumably due to a typo.
Sorry there's no changelog, filing from my phone.
<hr>
Unless your change is trivial or a small documentation fix (e.g., a typo or reword of a small section) **(it is)** please:
<details>
</details>
=> Update capture-warnings.rst: Fix PEP number in link

doc/en/how-to/capture-stdout-stderr.rst, doc/en/how-to/parametrize.rst
This got added in 38fb6aae7830837209c40ec1a4ccb68950bc107c, where the "The return value ... changed" made a lot of sense. However, 9c5da9c0d15ccf7ab9f3a8fbd6540e4a56ea789f removed the "versionadded" without adjusting the wording.
Also see 3a4435fb59604d40c5d2e2f65e9acba99dd9cff0.
=> doc: Clarify capturing .readouterr() return value

changelog/11381.improvement.rst, src/_pytest/config/__init__.py, src/_pytest/config/argparsing.py, src/_pytest/config/findpaths.py, testing/test_config.py
Implements #11381 
parsing of ``int`` and ``float`` configuration values from the **ini** files has been improved
=> Improvement for Parser.addini to facilite parsing of 'int' and 'float' values

changelog/13221.doc.rst, src/_pytest/capture.py, src/_pytest/debugging.py, src/_pytest/helpconfig.py, src/_pytest/main.py, src/_pytest/mark/__init__.py, src/_pytest/pastebin.py, src/_pytest/terminal.py
Probably best reviewed commit by commit. Notably, this fixes:
pytest-warnings:
-W, --pythonwarnings PYTHONWARNINGS
Set which warnings to report, see -W option of Python itself
--maxfail=num         Exit after first num failures or errors
--strict-config       Any warnings encountered while parsing the `pytest` section of the configuration file raise errors
--strict-markers      Markers not registered in the `markers` section of the configuration file raise errors
--strict              (Deprecated) alias to --strict-markers
-c, --config-file FILE
Load configuration from `FILE` instead of trying to locate one of the implicit configuration files.
--continue-on-collection-errors
Force test execution even if collection errors occur
--rootdir=ROOTDIR     Define root directory for tests. Can be …
=> Fix help sections for CLI options

AUTHORS, changelog/13228.feature.rst, doc/en/reference/reference.rst, src/_pytest/mark/__init__.py, src/_pytest/mark/structures.py, src/_pytest/python.py, src/pytest/__init__.py, testing/python/metafunc.py, testing/test_mark.py
=> Allow hiding a parameter set from test name

changelog/13256.contrib.rst, doc/en/broken-dep-constraints.txt
https://github.com/sphinx-contrib/sphinxcontrib-towncrier/issues/92 has been resolved and the recent Towncrier versions are compatible with the `sphinxcontrib.towncrier` Sphinx extension project yet again.
=> 📦📝 Allow modern Towncrier in docs builds

changelog/12946.bugfix.rst, src/_pytest/debugging.py, testing/test_debugging.py
=> Copy docstrings to wrapped pdb methods

AUTHORS, changelog/12842.doc.rst, doc/en/explanation/index.rst, doc/en/explanation/types.rst, doc/en/how-to/types.rst
Fix (#12842 )
* *Added dedicated page about using types with pytest, `doc/en/how-to/types.rst`.*
This guide explains how to apply typing in pytest, covering typing test functions, fixtures, and parameterized tests to improve code readability and prevent type-related errors.
=> Added dedicated page about using types with pytest #12842

changelog/13253.feature.rst, doc/en/how-to/plugins.rst, doc/en/reference/reference.rst, src/_pytest/config/__init__.py, src/_pytest/helpconfig.py, testing/test_assertion.py, testing/test_config.py
fixes #8969
I'm pretty sure the implementation is solid, but I have a bunch of question marks in comments that should be resolved before merging. I can probably resolve them on my own by digging deep enough into the innards, but wouldn't mind explanations if somebody is more familiar with that territory.
I'm not entirely sure that `test_installed_plugin_rewrite` should be parametrized to hell, as opposed to creating a dedicated test.
I also found a random unrelated typo in `test_installed_plugin_rewrite` with `check_first` -> `check_first2`, so fixed that + improved the `fnmatch_lines`.
=> add --disable-plugin-autoload

changelog/10558.doc.rst, changelog/10829.doc.rst, changelog/11777.bugfix.rst, changelog/12497.contrib.rst, changelog/12592.bugfix.rst, changelog/12818.bugfix.rst, changelog/12842.doc.rst, changelog/12849.bugfix.rst, changelog/12866.doc.rst, changelog/12888.bugfix.rst, changelog/12966.doc.rst, changelog/13026.bugfix.rst, changelog/13053.bugfix.rst, changelog/13083.bugfix.rst, changelog/13112.contrib.rst, changelog/13256.contrib.rst, changelog/9353.bugfix.rst, doc/en/announce/index.rst, doc/en/announce/release-8.3.4.rst, doc/en/announce/release-8.3.5.rst, doc/en/builtin.rst, doc/en/changelog.rst, doc/en/example/parametrize.rst, doc/en/example/pythoncollection.rst, doc/en/example/reportingdemo.rst, doc/en/example/simple.rst, doc/en/getting-started.rst, doc/en/how-to/fixtures.rst, doc/en/reference/reference.rst
Release 8.3.5
(cherry picked from commit f004b11caf49fa6fbacc8648bbc9c650a2e08bec)
---
Really sorry, but it seems when I released `8.3.4` I missed this step, that's why we are bringing the changes for `8.3.4` and `8.3.5` to `main`. 😓
=> Cherry-pick release 8.3.5

codecov.yml
The status quo is for patch coverage to be greater than or equal to the project% (currently 96.87%), which means that in practice it's 100% .. except if a PR is big enough, at which point a couple lines can sneak through.
I just merged #13192 which had 98.26% coverage for no reason, I'll add more tests and stuff in a followup to retroactively get it to 100%.
=> require codecov patch % to be 100%

src/_pytest/_code/code.py, src/_pytest/raises_group.py, testing/python/raises.py, testing/python/raises_group.py
#13192 merged without 100% patch coverage due to #13273, this PR fixes those.
=> improve raisesgroup code coverage

changelog/13291.bugfix.rst, src/_pytest/assertion/util.py
=> fix attrs==25.2.0 compatibility

.github/workflows/prepare-release-pr.yml, RELEASING.rst, scripts/prepare-release-pr.py, tox.ini
The script is [currently failing with](https://github.com/pytest-dev/pytest/actions/runs/13615071695/job/38057071681):
```
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/pytest-dev/pytest.git/'
```
Decided to remove the usage of `github3` and use the `gh` command-line tool directly, which simplifies the script, integrates nicely with GH, and enables to run it locally seamlessly.
=> Fix prepare-release-pr script

scripts/update-plugin-list.py
Hi everyone,
I've working hard on a new pytest plugin, unfortunatly,
the name of the plugin doesn't starts with `pytest-` (pytest-gherkin was already taken and looks unmaintained).
The project is already on pypi - https://pypi.org/project/tursu/
the code is on github - https://github.com/mardiros/tursu
and documented on my github pages - https://mardiros.github.io/tursu/
I don't know exactly where to promote it, bu starting by refered it from the pluging list should be a good starts.
Thanks for all you works.
=> Update additional projects list to include my new plugin

changelog/13317.packaging.rst, pyproject.toml
This PR specifies minimum allowed versions of `colorama`, `iniconfig`, and `packaging`, and bumps the minimum requirement of `exceptiongroup` to no longer be a release candidate.  
The first draft of this PR specifies minimum allowed versions that are several years old, but these can be changed to be more recent.
[`uv`](https://docs.astral.sh/uv/) has multiple dependency [resolution strategies](https://docs.astral.sh/uv/concepts/resolution/#resolution-strategy):
- `lowest` will install the lowest allowed version for _all_ dependencies, both direct and indirect (transitive).
- `lowest-direct` will use the lowest compatible versions for all _direct_ dependencies, while using the latest compatible versions for all other dependencies.
Up until now, `pytest` has not specified the minimum …
=> Specify minimum requirements for dependencies

AUTHORS, changelog/13047.bugfix.rst, src/_pytest/python_api.py, testing/python/approx.py
Fixed an issue in equality checks where `bool` and `numpy.bool_` types were not handled consistently.  
This ensures proper handling of native and numpy boolean types. See #13047.
Fix #13047
=> Fix broken ``approx`` when mixing numpy booleans and booleans

src/_pytest/python_api.py, testing/python/approx.py
Closes #13218.
- Added title to draw attention to the easily-missed information on non-numeric types for approx.
- Changed spelling of all cases of "nonnumeric" to "non-numeric" within docstrings for clarity and consistency with .rst files.
=> Add title and change spelling for use of approx with non-numerics

changelog/13345.bugfix.rst, src/_pytest/reports.py
These are set in `TestReport.__init__` but weren't being picked up by type checkers because of the annotations on `BaseReport`.
Fixes #12941.
=> Fix type hints for `TestReport.when` and `TestReport.location`

changelog/13348.misc.rst, src/_pytest/reports.py, testing/typing_checks.py
Based on discussion in #13345.
=> Clean up type hints from #13345 and add a test

changelog/8612.doc.rst, doc/en/example/pythoncollection.rst
This PR adds a new recipe to the documentation for handling abstract test classes in pytest. The recipe demonstrates how to use a mixin class to automatically manage the __test__ attribute for subclasses of abstract test classes. This ensures that subclasses are collected by pytest without requiring manual configuration.
Closes #8612
=> Add note on using mixin classes for abstract test classes in documentation

changelog/12647.bugfix.rst, changelog/12647.contrib.rst, testing/test_helpconfig.py, testing/test_terminal.py
Fixes #12647.
Indeed it's enough to add `monkeypatch.delenv("PYTEST_PLUGINS", raising=False)` to the failing tests, as the @mtelka suggested.
=> Bugfix for pytest plugins set to  hypothesis pytestplugin (#12647)

changelog/13377.bugfix.rst, src/_pytest/compat.py, testing/python/fixtures.py
– by supporting positional-only self parameters in `_pytest.compat.getfuncargnames()`
Fixes #13376
_Tests & changelog entry will be added if PR is seen as useful ... :)_
=> Fix parameter handling of non-static test methods

changelog/13377.bugfix.rst, src/_pytest/compat.py, testing/python/fixtures.py
Fixes #13376
Manually cherry-picked due to conflicts.
(cherry picked from commit 61c204a0355c89946cb0f3202820c5a0ec85e13d)
=> [8.3.x] Fix handling of positional-only parameters in test methods (#13377)

src/_pytest/junitxml.py, src/_pytest/pytester.py, src/_pytest/runner.py, src/_pytest/terminal.py, src/_pytest/timing.py, testing/_py/test_local.py, testing/test_pytester.py
Throughout the codebase we often need to track elapsed times, using a performance clock, and also start/end times that given seconds since epoch (via `time.time()`).
`Instant` encapsulates both functionalities to simplify the code and ensure we are using the correct functions from `_pytest.timing`, which we can mock in tests for reliability.
Built on top of https://github.com/pytest-dev/pytest/pull/13394, will rebase once it gets merged.
=> Add `Instant` class to conveniently track elapsed and start/end times

AUTHORS, CITATION, changelog/13415.improvement.rst
=> Willynilly update citation files

changelog/5473.improvement.rst, src/_pytest/assertion/rewrite.py, testing/test_assertrewrite.py
Hi,
can you please consider patch to mare assertion rewrite warning messages filterable using the standard `-W` option. It addresses #5473.
The issue arises when a Python package defines a `pytest` plugin, and also calls `pytest.main()` programmatically, after importing one of its own submodules. Because the module is already imported, `pytest.main()` cannot rewrite its assertions and emits a warning like:
```Module already imported so cannot be rewritten: basilisp```
Unfortunately, the `:` in the message conflicts with Python’s warning filter syntax, where `:` is used as a delimiter. This prevents users from filtering out the warning via `-W`.
This patch replaces the `:` in the warning message with a `;`, making it possible to write a valid warning filter like:
`-W ignore:Module already …
=> Make assertion rewrite warning messages filterable 

testing/acceptance_test.py, testing/test_monkeypatch.py
setuptools is intending to remove `pkg_resources` at the end of the year. Version 80.9.0 changed the deprecation to a UserMessage which broke the test. Instead of making them compatible, just skip them on versions >= 80 in preparation for the final removal.
Following [Ronny's suggestion](https://github.com/pytest-dev/pytest/pull/13442#issuecomment-2911689268).
=> testing: skip `pkg_resources` tests if modern setuptools

CONTRIBUTING.rst, doc/en/contact.rst
As discussed recently in https://mail.python.org/archives/list/pytest-dev@python.org/thread/Y2HCDCXAAN6PLY63KLLY7FSUFDR6G5LC/, we will archive the mailing in favor of GitHub Discussions.
=> Sunset the mailing list contact information

.github/workflows/test.yml, changelog/13308.improvement.rst, pyproject.toml, src/_pytest/pastebin.py, testing/python/raises.py, testing/test_debugging.py, testing/test_parseopt.py, testing/test_pastebin.py, testing/test_unraisableexception.py, tox.ini
https://github.com/pytest-dev/pytest/issues/13308
=> officially support python 3.14

RELEASING.rst
=> RELEASING: remove pytest mailing list

doc/en/builtin.rst, src/_pytest/capture.py
=> Fix possible typo in docs regarding capteesys

changelog/13492.doc.rst, doc/en/how-to/failures.rst
This PR removes the outdated warning regarding `faulthandler_timeout` on Windows as suggested in issue #13456.
The option is now functional on Windows, so the "(not available on Windows)" note has been removed from the documentation (`failures.rst`).
=> Remove outdated warning about faulthandler_timeout on Windows

src/_pytest/pytester.py, src/_pytest/unraisableexception.py, testing/test_config.py, testing/test_unraisableexception.py
This is an alternative to #13513. I had to change some tests to run in a subprocess and tweak them a bit to make it work.
Fixes #13482.
Closes #13513.
=> pytester: avoid unraisableexception gc collects in inline runs to speed up test suite

src/_pytest/unittest.py
Support for `nose` has been dropped in 8.0.
Noticed this while working on #13502.
=> Remove unused code related to `nose`

changelog/13549.bugfix.rst, src/_pytest/compat.py, src/_pytest/fixtures.py, src/_pytest/nodes.py, testing/test_collection.py
=> Defer annotation eval on Python 3.14

changelog/13480.bugfix.rst, changelog/13480.contrib.rst
Since this is related only to internal testing and does not affect end-users, it is more appropriate to announce it in the "Contributor" section of the changelog.
Follow up to #13481.
=> Rename 13480.bugfix to 13480.contrib

AUTHORS, changelog/13563.bugfix.rst, src/_pytest/python_api.py
Introduced in https://github.com/pytest-dev/pytest/pull/13338.
This matches existing conditional-import behavior in `pytest.approx`, and improves runtime for users of `pytest.approx and not numpy`.
=> Import numpy conditionally in `pytest.approx`

AUTHORS, changelog/13445.bugfix.rst, src/_pytest/outcomes.py, testing/python/collect.py
This is a more canonical way of typing generic callbacks/decorators
(see https://mypy.readthedocs.io/en/stable/protocols.html#callback-protocols)
This helps with potential issues/ambiguity with `__call__` semanics in
type checkers -- according to python spec, `__call__` needs to be present
on the class, rather than as an instance attribute to be considered callable.
This worked in mypy because it didn't handle the spec 100% correctly (in this case this has no negative consequences)
However, `ty` type checker is stricter/more correct about it and every `pytest.skip` usage results in:
`error[call-non-callable]: Object of type `_WithException[Unknown, <class 'Skipped'>]` is not callable`
For more context, see:
- https://github.com/astral-sh/ruff/pull/17832#issuecomment-2855425767
- …
=> use callable protocols for pytest.skip/exit/fail/xfail instead of _WithException wrapper with __call__ attribute

changelog/478.feature.rst, doc/en/reference/reference.rst, src/_pytest/main.py, testing/test_collection.py, testing/test_main.py
Previously, when running `--pyargs pkg`, if you didn't have `pkg/__init__.py`, pytest would fail with `ERROR: module or package not found: pkg (missing __init__.py?)`.
Now it's discovering the package and tests inside it correctly.
If used in conjunction with `consider_namespace_packages` in config, test modules get correct `__package__` and `__name__` attributes as well.
Fixes: https://github.com/pytest-dev/pytest/issues/478
Other relevant issues:
- https://github.com/pytest-dev/pytest/issues/2371
- https://github.com/pytest-dev/pytest/issues/10569
In addition, remove `"namespace"` origin handling -- this value isn't used since python 3.8. See:
- https://github.com/python/cpython/pull/5481
- https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec.submodule_search_l …
=> Support PEP420 (implicit namespace packages) as `--pyargs` target.

pyproject.toml
Prompted by this post https://bsky.app/profile/hynek.me/post/3lc5n7g6kr22f
Ref: https://github.com/python-attrs/attrs/pull/1377
=> Apply PEP 639

changelog/13621.contrib.rst, testing/test_capture.py
In case of hanging filesystems (e.g. unreachable sshfs), `lsof` can hang for a long time (3 minutes in my case). Set a more reasonable timeout and skip the affected test (like already done with other problems regarding lsof) in such a case.
=> selftests: Set a timeout for lsof

src/_pytest/raises.py
super small formatting error I noticed when reading the docs https://docs.pytest.org/en/stable/reference/reference.html#pytest.RaisesExc
I checked that this didn't occur elsewhere with `git grep ':\(kw\)\?param[^:]*$'`, which we could add to pre-commit
=> add missing colon

doc/en/explanation/pythonpath.rst
objective: address minor typo in pythonpath documentation.
=> docs(pythonpath): address minor typo

src/_pytest/raises.py, testing/python/raises_group.py
Hello.
Fix typo Exeption -> Ex**c**eption in error message and fix it in test.
=> fix: change Exeption to Exception in raises.py

.github/workflows/doc-check-links.yml, AUTHORS, changelog/12474.contrib.rst
Closes https://github.com/pytest-dev/pytest/issues/12474
Adds a new GitHub Action workflow called `Doc Check Links`. It will setup Python, upgrade pip, install tox and run the linkchecks via `tox -e docs-checklinks`.
Tested in fork repo: https://github.com/marcosboger/pytest/actions/runs/17279769140/job/49045434081
For now, not making any changes to linkcheck/sphinx configuration.
=> Run Link Checks via scheduled workflow

changelog/13598.bugfix.rst, src/_pytest/main.py, src/_pytest/pathlib.py, testing/test_collection.py
The previous check does not account for multiple levels of symlinks: given a -> b -> c, a would match b.
Note, I don't use Windows and can't actually verify it, I only saw it reading the code. But if it's wrong hopefully the existing `test_do_not_collect_symlink_siblings` test will catch it on Windows CI.
=> main: use a better windows short-path comparison method

changelog/13700.improvement.rst, src/_pytest/junitxml.py, testing/test_junitxml.py
=> junitxml: do not print summary with `--quiet`

AUTHORS, changelog/13732.improvement.rst, src/_pytest/config/__init__.py, testing/test_config.py, testing/test_warnings.py
We stumbled into an issue using tools like [pants](https://www.pantsbuild.org/) that will generate test environment with minimal dependencies. If used with warning filters with categories from third-party library, pytest is going to fail for any test without this third-party. This is unecessary and any workaround in `conftest.py` is impossible due to https://github.com/pytest-dev/pytest/issues/13485
So this PR change the behavior of failed category import to just log a warning and skip the warning entry.
=> config: Do not fail if a warning filter category cannot be imported

.pre-commit-config.yaml, doc/en/example/.ruff.toml
This isn't seen unless there's a ruff error locally.
=> [ruff configuration] Fix legacy alias and top-level linter settings

doc/en/getting-started.rst
Very simple change to markup in a documentation.
=> Format file patterns

changelog/13779.breaking.rst, src/_pytest/deprecated.py, src/_pytest/warning_types.py, src/_pytest/warnings.py, src/pytest/__init__.py, testing/acceptance_test.py, testing/test_warnings.py
Per our backward compatibility policy.
Fix #13779
=> Change PytestRemovedIn9Warning to error by default

changelog/13791.packaging.rst, pyproject.toml
This is a quick follow up to #13317 to make it even easier for downstream packages to test with uv's `--resolution=lowest`:
- iniconfig 1.0.1 has a wheel, while 1.0.0 doesn't. It currently builds fine, but using a wheel makes it even less likely to break in the future (for instance if setuptools breaks building 1.0.0)
- packaging 22.0.0 is the first zero-dependency version, which avoids any incompatibilities with *its* dependencies, most importantly including `six`, which I think is bound to break one day or another.
=> DEP: bump minimal requirements for iniconfig (1.0.0 -> 1.0.1) and packaging (20.0.0 -> 22.0.0)

AUTHORS, changelog/12244.contrib.rst, testing/io/test_terminalwriter.py
Dumb terminals are incapable of handling color, so this test would fail when ran in such an environment. We encountered this on the Solus build infrastructure which uses such a headless terminal.
=> Fixed color test when TERM=dumb

AUTHORS, changelog/13771.contrib.rst, testing/test_collection.py
On Windows environments without Developer Mode or admin privileges,
symlink creation is not supported. This caused
`test_do_not_collect_symlink_siblings` to fail even though pytest
behavior was correct.
This patch adds a skip condition to avoid false negatives.
Closes #13771 
Added `changelog/12039.bugfix.rst`:
* Skip `test_do_not_collect_symlink_siblings` on Windows without symlink support.
=> Skip symlink sibling test on Windows without symlink support

testing/python/fixtures.py
Currently the `prune_dependency_tree` method is not semantically covered; if the call to it is commented out, all tests still pass.
Add a test that would fail, to prevent regressions and show why it's (annoyingly) needed.
=> testing: add a test demonstrating why `prune_dependency_tree` is needed
